/* Fiches françaises pour js/birds2.js — générées par src/build.js */
Object.assign(BIRDS_FR, {
  "european-honey-buzzard": {
    name: "Bondrée apivore",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "52–60 cm",
    wingspan: "130–150 cm",
    weight: "440–1 050 g",
    summary: "Rapace élancé des bois d’Europe et d’Asie occidentale, qui se nourrit de larves de guêpes et d’abeilles. Erratique très rare en Mongolie.",
    description: "La Bondrée apivore niche en Europe et en Asie occidentale et hiverne en Afrique tropicale. Malgré son nom anglais (« buse »), elle est plus proche des milans que des vraies buses. Elle déterre les nids de guêpes et d’abeilles pour en manger les larves ; des plumes faciales denses, comme des écailles, la protègent des piqûres. En Mongolie, elle n’a été observée que très rarement ; c’est sa cousine orientale, la Bondrée orientale, que l’on voit normalement ici.",
    features: ["Petite tête de pigeon au bout d’un cou assez long.", "Longue queue avec deux fines barres sombres à la base et une large bande sombre près de l’extrémité.", "Le mâle a la tête gris bleu, la femelle la tête brune.", "Plumage très variable, du pâle au brun foncé.", "Plane sur des ailes plates aux extrémités légèrement abaissées."],
    similar: "Bondrée orientale — plus grande, courte huppe, six « doigts » aux ailes. Buse variable — plus massive, queue plus courte, tête plus large.",
    habitatText: "Forêts feuillues et mixtes avec clairières.",
    distribution: "Erratique rare ; très peu de mentions en Mongolie.",
    migration: "Grande migratrice entre l’Europe/l’Asie occidentale et l’Afrique.",
    food: "Larves et nymphes de guêpes et d’abeilles ; aussi insectes, grenouilles et petits oiseaux.",
    breeding: "Niche haut dans les arbres ; 1 à 3 œufs.",
    behavior: "Marche au sol pour déterrer les nids de guêpes avec ses pattes.",
    voice: "Un « piii-lou » plaintif et sifflé.",
    culture: "Son nom latin apivorus signifie « mangeur d’abeilles ».",
    conservation: "Préoccupation mineure ; tirée en migration dans certains pays.",
    watching: "Pas régulière en Mongolie — examinez bien les bondrées en migration.",
    bestTime: "mai, septembre",
    facts: ["Mange des larves de guêpes.", "Face couverte de plumes raides comme des écailles.", "Hiverne en Afrique."]
  },
  "east-asian-honey-buzzard": {
    name: "Bondrée orientale",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "52–68 cm",
    wingspan: "128–155 cm",
    weight: "0.75–1.5 kg",
    summary: "Grande bondrée au plumage variable et à petite huppe, qui pille les nids d’abeilles et de guêpes. Traverse la Mongolie au printemps et à l’automne.",
    description: "La Bondrée orientale niche en Sibérie et au Japon et hiverne en Asie du Sud-Est et en Inde. Sa tête longue et étroite, sa langue creusée d’un sillon et ses plumes faciales denses sont des adaptations pour fouiller les nids d’abeilles et de guêpes. En Mongolie, la plupart des observations ont lieu en mai et en septembre, lors de la migration.",
    features: ["Petite tête avec une courte huppe à l’arrière.", "Six longs « doigts » à l’extrémité de l’aile.", "Queue barrée de larges bandes sombres régulièrement espacées.", "Plumage du pâle au très sombre ; gorge souvent pâle avec un trait sombre.", "Plane sur des ailes plates."],
    similar: "Bondrée apivore — plus petite, sans huppe ; rare ici. Buse variable — queue plus courte, ailes plus arrondies, tête plus large.",
    habitatText: "Forêt et steppe boisée ; en migration, aussi au-dessus de la steppe et du Gobi.",
    distribution: "Surtout de passage — Gobi, forêts du Khentii et de la Selenge, ouest de la Mongolie.",
    migration: "Migratrice de passage, avec des pics en mai et en septembre.",
    food: "Larves et rayons d’abeilles et de guêpes ; aussi insectes et petits vertébrés.",
    breeding: "Niche dans les forêts sibériennes, haut dans les arbres ; 1 à 3 œufs.",
    behavior: "Suit les abeilles jusqu’à leur nid et le déterre.",
    voice: "Un « oui-oui-oui » aigu et sifflé.",
    culture: "Migre en grandes bandes le long de la côte d’Asie orientale, un spectacle célèbre chez les ornithologues.",
    conservation: "Préoccupation mineure.",
    watching: "Surveillez le ciel au-dessus du Gobi et de la steppe boisée en mai et septembre.",
    bestTime: "mai, septembre",
    facts: ["Langue à sillon pour extraire les larves de guêpes.", "Plumes de la tête protectrices contre les piqûres.", "Certains jeunes imitent les aigles huppés."]
  },
  "egyptian-vulture": {
    name: "Vautour percnoptère",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "En danger (EN).",
    length: "47–70 cm",
    wingspan: "155–180 cm",
    weight: "1.6–2.4 kg",
    summary: "Petit vautour blanc à face jaune et queue cunéiforme — l’un des rares oiseaux à utiliser des outils. Erratique très rare en Mongolie.",
    description: "Le Vautour percnoptère est présent de l’Europe du Sud et l’Afrique du Nord jusqu’en Inde. Il se nourrit de charognes et brise les œufs d’autruches et d’autres grands oiseaux en leur lançant des pierres — un rare exemple d’utilisation d’outils chez les oiseaux. En fort déclin dans une grande partie de son aire, il est classé « En danger ». On ne compte que quelques mentions en Mongolie.",
    features: ["Adulte surtout blanc, rémiges noires.", "Face nue jaune ; bec fin à pointe sombre.", "Queue blanche cunéiforme.", "Plumes du cou ébouriffées.", "Juvéniles brun foncé."],
    similar: "Gypaète barbu — bien plus grand, longue queue cunéiforme, dessus sombre et dessous orangé.",
    habitatText: "Terrains ouverts et secs, falaises, décharges.",
    distribution: "Erratique très rare en Mongolie.",
    migration: "Les populations nordiques migrent vers le sud en hiver.",
    food: "Charognes, œufs, excréments, petits animaux.",
    breeding: "Niche sur des corniches ; 1 ou 2 œufs.",
    behavior: "Lance des pierres pour casser les œufs.",
    voice: "Généralement silencieux.",
    culture: "Surnommé « poule des pharaons » ; figure dans les hiéroglyphes égyptiens.",
    conservation: "En danger — empoisonnement, lignes électriques et raréfaction de la nourriture.",
    watching: "Non attendu en Mongolie.",
    bestTime: "—",
    facts: ["Utilise des pierres comme outils.", "Menacé à l’échelle mondiale.", "Sa face devient jaune vif chez l’adulte."]
  },
  "short-toed-eagle": {
    name: "Circaète Jean-le-Blanc",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "59–70 cm",
    wingspan: "162–195 cm",
    weight: "1.2–2.3 kg",
    summary: "Aigle pâle à tête de hibou, qui fait du surplace au-dessus des versants et se nourrit presque exclusivement de serpents. Présent l’été surtout dans le sud de la Mongolie.",
    description: "Le Circaète Jean-le-Blanc niche de l’Europe du Sud à l’Asie centrale et hiverne en Afrique et en Inde. Il chasse en vol plané ou en surplace, puis fond sur les serpents et les lézards ; il avale les serpents entiers en vol. En Mongolie, la plupart des observations proviennent du Gobi, d’avril à octobre.",
    features: ["Dessous très pâle, finement barré.", "Haut de la poitrine et gorge bruns, formant un « capuchon ».", "Grosse tête ronde de hibou, yeux jaune vif.", "Trois ou quatre barres sur la queue.", "Fait souvent du surplace comme une crécerelle."],
    similar: "Buse de Chine — taches carpales sombres, queue pâle. Balbuzard pêcheur — bandeau sombre sur l’œil, tête blanche, près de l’eau.",
    habitatText: "Collines sèches, semi-désert et steppe rocheuse riches en reptiles.",
    distribution: "Surtout le Gobi ; occasionnellement plus au nord.",
    migration: "Visiteur d’été, d’avril à octobre ; pics en mai et septembre.",
    food: "Serpents et lézards, parfois petits mammifères.",
    breeding: "Petit nid de branches dans un arbre ou sur une falaise ; un seul œuf.",
    behavior: "Fait du surplace face au vent, puis fond sur sa proie.",
    voice: "Un « ouiio » miaulé, rappelant une mouette.",
    culture: "Son nom français signifie « Jean le Blanc ».",
    conservation: "Préoccupation mineure.",
    watching: "Piémonts du Gobi à la fin du printemps.",
    bestTime: "mai–sept.",
    facts: ["Se nourrit presque uniquement de serpents.", "Avale les serpents la tête la première.", "Ne pond qu’un seul œuf."]
  },
  "himalayan-griffon": {
    name: "Vautour de l'Himalaya",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Quasi menacée (NT).",
    length: "103–110 cm",
    wingspan: "256–310 cm",
    weight: "6–12.5 kg",
    summary: "Immense vautour pâle de l’Himalaya et du Tibet ; de nombreux jeunes passent l’été dans les montagnes et le Gobi de Mongolie.",
    description: "Le Vautour de l’Himalaya est le deuxième plus grand vautour de l’Ancien Monde après le Vautour moine. Il niche dans l’Himalaya et sur le plateau tibétain. Le suivi par satellite a montré que de nombreux immatures remontent passer l’été en Mongolie, où on les voit régulièrement sur les carcasses dans le Gobi, le Khangaï et l’Altaï.",
    features: ["Corps et couvertures alaires chamois pâle.", "Rémiges et rectrices brun foncé contrastant avec le corps pâle.", "Longue collerette pâle hérissée.", "Tête couverte de duvet blanchâtre ; bec jaunâtre.", "Ailes très longues et larges, extrémités digitées."],
    similar: "Vautour moine — entièrement sombre. Vautour fauve — plus petit, plus roux, moins contrasté. Gypaète barbu — ailes pointues, longue queue cunéiforme.",
    habitatText: "Montagnes, hauts plateaux, steppe et Gobi près des carcasses.",
    distribution: "Altaï du Gobi, Khangaï, Altaï et Mongolie centrale — en été.",
    migration: "Visiteur d’été non nicheur, d’avril à octobre (pic en juin).",
    food: "Carcasses de bétail et d’ongulés sauvages.",
    breeding: "Niche sur les falaises himalayennes ; un œuf.",
    behavior: "Plane pendant des heures et se rassemble sur les carcasses avec les Vautours moines.",
    voice: "Grognements et sifflements sur les carcasses.",
    culture: "Joue un rôle important dans les funérailles célestes tibétaines.",
    conservation: "Quasi menacé — empoisonnement et médicaments vétérinaires.",
    watching: "Gobi Gurvan Saikhan, Ikh Nart et Khangaï de juin à août.",
    bestTime: "juin–août",
    facts: ["L’un des plus grands rapaces du monde.", "Les jeunes passent l’été en Mongolie.", "Peut planer au-dessus de 6 000 m."]
  },
  "griffon-vulture": {
    name: "Vautour fauve",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "93–122 cm",
    wingspan: "230–280 cm",
    weight: "6.2–10.5 kg",
    summary: "Grand vautour brun sable à collerette blanche. Il vit dans l’Altaï et le Tian Shan et reste rare en Mongolie.",
    description: "Le Vautour fauve est présent de l’Espagne à l’Asie centrale, notamment dans l’Altaï et le Tian Shan. Il niche en colonies sur les falaises et prospecte les milieux ouverts à la recherche de carcasses. En Mongolie, il n’a été noté que quelques fois, surtout dans le Gobi en été.",
    features: ["Corps brun chamois.", "Collerette blanche.", "Tête blanche, bec jaune.", "Rémiges sombres contrastant avec des couvertures plus pâles.", "Ailes larges, queue courte."],
    similar: "Vautour de l’Himalaya — plus grand, plus pâle et plus contrasté. Vautour moine — entièrement sombre.",
    habitatText: "Montagnes à falaises, pâturages ouverts.",
    distribution: "Rare en Mongolie — quelques mentions dans le Gobi.",
    migration: "Surtout sédentaire ; les jeunes erratiques.",
    food: "Carcasses de grands mammifères.",
    breeding: "Colonial sur les falaises ; un œuf.",
    behavior: "Les groupes se rassemblent vite sur les carcasses.",
    voice: "Sifflements et croassements sur les carcasses.",
    culture: "L’Espagne abrite plus de 90 % de la population européenne.",
    conservation: "Préoccupation mineure.",
    watching: "Rare — cherchez-le parmi les autres vautours du Gobi.",
    bestTime: "juin–août",
    facts: ["Niche en colonies.", "Collerette blanche.", "Repère une carcasse à plusieurs kilomètres."]
  },
  "mountain-hawk-eagle": {
    name: "Aigle montagnard",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Quasi menacée (NT).",
    length: "66–84 cm",
    wingspan: "134–175 cm",
    weight: "1.5–3.5 kg",
    summary: "Grand aigle forestier d’Asie du Sud et de l’Est, huppé et aux pattes emplumées. Signalé seulement exceptionnellement en Mongolie.",
    description: "L’Aigle montagnard (ou aigle huppé de Hodgson) vit dans les forêts, de l’Himalaya au Japon. Il chasse oiseaux, mammifères et reptiles depuis un perchoir caché. Sa présence en Mongolie est exceptionnelle.",
    features: ["Courte huppe à l’arrière de la tête.", "Dessus brun, dessous pâle fortement strié.", "Ventre et cuisses barrés.", "Pattes emplumées jusqu’aux doigts.", "Ailes larges et arrondies."],
    similar: "Autour des palombes — plus petit, sans huppe. Aigle botté — plus petit, plages pâles aux ailes.",
    habitatText: "Forêts de montagne.",
    distribution: "Erratique exceptionnel en Mongolie.",
    migration: "Surtout sédentaire ; les oiseaux du nord se déplacent peu.",
    food: "Oiseaux, mammifères et reptiles.",
    breeding: "Grand nid dans un grand arbre ; 1 œuf.",
    behavior: "Chasse depuis un perchoir en forêt.",
    voice: "Un « tluiit-ouit-ouit » perçant.",
    culture: "Porte aussi le nom du naturaliste Brian Hodgson.",
    conservation: "Quasi menacé — déforestation.",
    watching: "Non attendu en Mongolie.",
    bestTime: "—",
    facts: ["Un aigle forestier.", "Porte une huppe.", "Pattes emplumées."]
  },
  "greater-spotted-eagle": {
    name: "Aigle criard",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Vulnérable (VU).",
    length: "59–71 cm",
    wingspan: "157–179 cm",
    weight: "1.7–3.2 kg",
    summary: "Aigle sombre et trapu des steppes boisées humides ; les juvéniles sont couverts de taches blanches. Visiteur d’été peu commun dans le nord de la Mongolie.",
    description: "L’Aigle criard niche de l’Europe de l’Est à la Sibérie orientale, dans les forêts humides proches des marais et des plaines inondables, et hiverne en Asie du Sud, au Moyen-Orient et en Afrique. Il est classé « Vulnérable ». En Mongolie, la plupart des observations proviennent de la steppe boisée du Khentii et de la Selenge, d’avril à octobre.",
    features: ["Adulte brun foncé uniforme.", "Juvénile couvert de rangées de taches blanches sur les ailes.", "Queue courte et ailes larges.", "« U » pâle au-dessus de la queue.", "Narine ronde."],
    similar: "Aigle des steppes — plus grand, commissure du bec prolongée derrière l’œil. Aigle impérial — nuque dorée et taches blanches aux épaules.",
    habitatText: "Bois humides près des marais, vallées fluviales et prairies inondables.",
    distribution: "Steppe boisée du Khentii, de la Selenge et du Khangaï ; aussi Dornod en passage.",
    migration: "Visiteur d’été, d’avril à octobre.",
    food: "Rongeurs, grenouilles, oiseaux d’eau et charognes.",
    breeding: "Nid dans un grand arbre près d’une zone humide ; 1 à 3 œufs.",
    behavior: "Se pose souvent au sol dans les prairies humides.",
    voice: "Un « kyak-kyak » aboyé.",
    culture: "Son nom latin clanga signifie « cri ».",
    conservation: "Vulnérable — drainage des zones humides et hybridation avec l’Aigle pomarin en Europe.",
    watching: "Vallées du Khentii (Onon, Khurkh) en été.",
    bestTime: "mai–août",
    facts: ["Les juvéniles sont couverts de taches blanches.", "Vulnérable à l’échelle mondiale.", "Lié aux zones humides."]
  },
  "bonellis-eagle": {
    name: "Aigle de Bonelli",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "55–67 cm",
    wingspan: "143–180 cm",
    weight: "1.5–2.5 kg",
    summary: "Aigle puissant des montagnes méditerranéennes et d’Asie du Sud, au corps blanc et à la queue barrée de sombre. Erratique exceptionnel en Mongolie.",
    description: "L’Aigle de Bonelli est présent de l’Europe du Sud et de l’Afrique du Nord jusqu’en Inde et au sud de la Chine. Il vit dans les collines rocheuses et chasse lapins, gallinacés et pigeons. Sa présence en Mongolie est exceptionnelle.",
    features: ["Dessous pâle finement strié de sombre.", "Dessus brun foncé avec une tache pâle sur le dos.", "Longue queue grise à large bande terminale sombre.", "Bande sombre le long du dessous de l’aile.", "Longues pattes."],
    similar: "Aigle botté — plus petit, avec des « phares » blancs aux épaules. Circaète Jean-le-Blanc — tête plus grosse, sans bande sombre à la queue.",
    habitatText: "Collines rocheuses et montagnes.",
    distribution: "Erratique exceptionnel en Mongolie.",
    migration: "Surtout sédentaire.",
    food: "Lapins, gallinacés, pigeons.",
    breeding: "Niche sur les falaises ; 1 à 3 œufs.",
    behavior: "Les couples chassent souvent ensemble.",
    voice: "Généralement silencieux.",
    culture: "Porte le nom de l’ornithologue italien Franco Andrea Bonelli.",
    conservation: "Préoccupation mineure, mais en déclin en Europe.",
    watching: "Non attendu en Mongolie.",
    bestTime: "—",
    facts: ["Les couples chassent en équipe.", "Porte le nom d’un naturaliste italien.", "En déclin en Europe."]
  },
  "booted-eagle": {
    name: "Aigle botté",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "42–51 cm",
    wingspan: "110–132 cm",
    weight: "510–1 250 g",
    summary: "Petit aigle de la taille d’une buse, aux pattes emplumées et aux « phares » blancs à la base des ailes. Visiteur d’été des montagnes boisées de toute la Mongolie.",
    description: "L’Aigle botté niche de la péninsule Ibérique et de l’Afrique du Nord jusqu’en Mongolie à travers l’Asie centrale, et hiverne en Afrique tropicale et en Inde. Il existe une forme claire (corps blanc, rémiges noires) et une forme sombre (entièrement brune). Il capture oiseaux, lézards et petits mammifères en piqué rapide depuis le vol plané. En Mongolie, il est répandu d’avril à octobre dans les forêts du Khentii, de l’Altaï et du Khangaï et dans les montagnes boisées du Gobi ; il chasse souvent autour d’Oulan-Bator et de Terelj.",
    features: ["Taille d’une buse mais ailes plus étroites, aux bords parallèles, et queue plus longue et carrée.", "Deux petites taches blanches à la jonction des ailes et du corps (« phares »), visibles de face.", "Forme claire : corps et couvertures sous-alaires blancs contrastant avec des rémiges noires.", "Forme sombre : dessous brun, queue plus pâle.", "Bande pâle sur les couvertures sus-alaires et « U » pâle au croupion."],
    similar: "Milan noir — queue fourchue, sans taches blanches. Buse variable et Buse de Chine — ailes plus larges, taches carpiennes sombres. Circaète Jean-le-Blanc — plus grand, tête de hibou.",
    habitatText: "Forêts mixtes et lisières dans les collines et montagnes, souvent près de milieux ouverts.",
    distribution: "Répandu en été : steppe boisée du Khentii et de la Selenge (Terelj, Oulan-Bator), lac Khar Us, Altaï, Khangaï et montagnes boisées du Gobi.",
    migration: "Visiteur d’été de fin avril à début octobre ; pics de passage en mai et septembre.",
    food: "Petits et moyens oiseaux, lézards, spermophiles et autres petits mammifères.",
    breeding: "Nid de branches dans un grand arbre ou sur une falaise ; 1 ou 2 œufs. Les couples réutilisent le même nid chaque année.",
    behavior: "Plane haut puis pique brusquement, ailes repliées ; parades nuptiales en couple au printemps.",
    voice: "Un « kli-kli-kli » aigu et sifflé, surtout près du nid.",
    culture: "Son nom vient des « bottes » de plumes de ses pattes, caractère des vrais aigles.",
    conservation: "Préoccupation mineure.",
    watching: "Terelj et les collines boisées autour d’Oulan-Bator, lac Khar Us et vallées de l’Altaï, de mai à septembre.",
    bestTime: "mai–sept.",
    facts: ["L’un des plus petits vrais aigles.", "Existe en deux formes de couleur.", "Pattes emplumées jusqu’aux doigts."]
  },
  "western-marsh-harrier": {
    name: "Busard des roseaux",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "43–55 cm",
    wingspan: "115–130 cm",
    weight: "400–800 g",
    summary: "Grand busard aux ailes larges qui patrouille à basse altitude au-dessus des roselières. En Mongolie, il niche surtout dans les lacs à roseaux de l’ouest.",
    description: "Le Busard des roseaux niche en Europe et en Asie occidentale ; la Mongolie est à la limite orientale de son aire, où il rencontre le Busard d’Orient et s’hybride parfois avec lui. Il glisse bas au-dessus des roseaux, ailes relevées en V, puis se laisse tomber sur ses proies. La plupart des mentions mongoles proviennent du lac Khar Us et de la dépression des Grands Lacs, quelques-unes des lacs du Khangaï et du Gobi.",
    features: ["Mâle : corps brun, tête pâle, queue grise et panneaux gris sur les ailes, extrémités noires.", "Femelle : brun chocolat avec la calotte et la gorge crème.", "Vole bas, ailes relevées en V.", "Ailes plus larges que les autres busards.", "Pas de croupion blanc (contrairement à la plupart des busards)."],
    similar: "Busard d’Orient — mâle noir et gris, dessous blanc ; femelle plus striée, souvent à croupion blanc. Milan noir — queue fourchue, plane plus haut.",
    habitatText: "Roselières et marais autour des lacs et des rivières lentes.",
    distribution: "Surtout l’ouest (lac Khar Us, dépression des Grands Lacs) ; aussi Böön Tsagaan, lac Orog et parfois le Khentii.",
    migration: "Visiteur d’été d’avril à octobre.",
    food: "Grenouilles, petits mammifères, canetons et jeunes oiseaux d’eau, œufs.",
    breeding: "Nid de roseaux dans une roselière dense ; 3 à 6 œufs.",
    behavior: "Pendant la nidification, le mâle passe la nourriture à la femelle en vol.",
    voice: "Surtout silencieux ; un « ki-a » fin près du nid.",
    culture: "Son nom latin aeruginosus signifie « couleur de rouille ».",
    conservation: "Préoccupation mineure ; dépend des roselières menacées par le drainage et le feu.",
    watching: "Scrutez les roselières du lac Khar Us en été.",
    bestTime: "mai–sept.",
    facts: ["S’hybride avec le Busard d’Orient en Mongolie.", "Pratique le passage de proie en vol.", "Le plus grand busard d’Europe."]
  },
  "eastern-marsh-harrier": {
    name: "Busard d'Orient",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "48–58 cm",
    wingspan: "113–137 cm",
    weight: "400–800 g",
    summary: "Le busard des marais d’Asie orientale — les mâles sont nettement noirs, gris et blancs. Visiteur d’été commun des zones humides du nord et de l’est de la Mongolie.",
    description: "Le Busard d’Orient niche dans le nord-est de la Chine, l’est de la Mongolie et le sud-est de la Sibérie, et hiverne dans le sud de la Chine et en Asie du Sud-Est. Il a longtemps été considéré comme une sous-espèce du Busard des roseaux. En Mongolie, il est commun d’avril à octobre dans les vallées et les lacs comme la vallée de Khurkh-Khüiten, le lac Ögii et le lac Buir.",
    features: ["Mâle : tête, poitrine et dos noirs striés de blanc ; ailes grises à extrémités noires ; dessous blanc.", "Femelle : brun foncé, striée de chamois sur la tête et la poitrine, souvent à croupion blanc.", "Juvénile : brun foncé à tête pâle.", "Glisse bas, ailes en léger V."],
    similar: "Busard des roseaux — mâle brun et gris, femelle chocolat à tête crème. Busard tchoug — mâle plus nettement noir et blanc, plus petit et plus fin. Busard Saint-Martin — plus petit, grand croupion blanc.",
    habitatText: "Marais, lacs à roseaux, prairies humides et vallées fluviales.",
    distribution: "Khentii et Selenge (Khurkh, Onon), Dornod (lac Buir, Mongol Daguur), lacs du Khangaï (lac Ögii) et vallée des Lacs.",
    migration: "Visiteur d’été, de fin mars à octobre ; maximum en mai–juin.",
    food: "Grenouilles, campagnols, jeunes oiseaux d’eau et poissons.",
    breeding: "Nid de roseaux dans les zones humides ; 3 à 7 œufs.",
    behavior: "Chasse en patrouillant bas au-dessus des roseaux et des herbes ; dortoirs collectifs en hiver.",
    voice: "Généralement silencieux ; cris miaulés au dortoir.",
    culture: "S’hybride avec le Busard des roseaux autour du lac Baïkal et en Mongolie.",
    conservation: "Préoccupation mineure.",
    watching: "Vallée de Khurkh-Khüiten, lac Ögii et lac Buir, de mai à août.",
    bestTime: "mai–août",
    facts: ["Commun dans les zones humides de l’est de la Mongolie.", "Longtemps réuni avec le Busard des roseaux.", "Mâle et femelle sont totalement différents."]
  },
  "hen-harrier": {
    name: "Busard Saint-Martin",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "44–52 cm",
    wingspan: "97–122 cm",
    weight: "300–700 g",
    summary: "Busard élancé à longue queue et large croupion blanc ; le mâle est gris pâle à extrémités d’ailes noires. Migrateur de passage dans toute la Mongolie, surtout en septembre.",
    description: "Le Busard Saint-Martin niche dans le nord de l’Eurasie, dans les landes, marais et prairies, et hiverne plus au sud. Il niche en petit nombre dans le nord de la Mongolie mais s’observe surtout en migration, en particulier en septembre, chassant bas au-dessus de la steppe.",
    features: ["Mâle : gris bleuté pâle, ventre blanc, extrémités des ailes noires.", "Femelle et juvénile : bruns, striés dessous, avec un grand croupion blanc.", "Disque facial rappelant une chouette.", "Ailes et queue longues ; glisse bas, ailes en V."],
    similar: "Busard pâle — mâle plus pâle avec un fin coin noir au bout de l’aile ; femelle au dessin facial plus marqué. Busard tchoug — mâle noir et blanc. Busard cendré — mâle avec barre alaire noire et stries rousses.",
    habitatText: "Steppe, marais, prairies et cultures.",
    distribution: "Toute la Mongolie en migration ; Khurkh, lac Khar Us, lac Ögii, lac Buir et steppes de l’est.",
    migration: "Surtout migrateur de passage (avril–mai, septembre–octobre) ; quelques nicheurs et hivernants.",
    food: "Campagnols, petits oiseaux et insectes.",
    breeding: "Nid au sol dans la végétation haute ; 4 à 6 œufs.",
    behavior: "Chasse en vol bas, se laissant tomber sur ses proies qu’il repère aussi à l’oreille.",
    voice: "Un « tchèk-èk-èk » près du nid.",
    culture: "Son nom anglais (« busard des poules ») rappelle son ancienne habitude de capturer des volailles.",
    conservation: "Préoccupation mineure, mais persécuté dans certaines régions d’Europe.",
    watching: "En septembre dans les steppes du Khentii et du Dornod.",
    bestTime: "septembre",
    facts: ["Disque facial pour chasser à l’oreille.", "Le mâle est bien plus pâle que la femelle.", "Surtout vu en migration en Mongolie."]
  },
  "pallid-harrier": {
    name: "Busard pâle",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Quasi menacée (NT).",
    length: "40–48 cm",
    wingspan: "95–120 cm",
    weight: "315–445 g",
    summary: "Busard fin des steppes ; le mâle, d’une pâleur fantomatique, porte un fin coin noir au bout de l’aile. Migrateur rare en Mongolie.",
    description: "Le Busard pâle niche dans les steppes du sud de la Russie et du Kazakhstan et hiverne en Inde et en Afrique. La Mongolie est à l’est de son aire principale ; on n’y compte que quelques mentions par an, surtout en migration d’automne dans l’ouest et le nord.",
    features: ["Mâle : gris très pâle, presque blanc dessous, fin coin noir à l’extrémité de l’aile.", "Femelle : brune à croupion blanc, collier pâle marqué et joue sombre.", "Fin, aux ailes étroites et pointues.", "Vol léger, rappelant une sterne."],
    similar: "Busard Saint-Martin — mâle plus gris, extrémités noires plus larges ; femelle sans collier. Busard cendré — mâle avec des barres noires sur l’aile.",
    habitatText: "Steppes ouvertes et prairies.",
    distribution: "Rare ; mentions au lac Khar Us, à Khurkh et près d’Oulan-Bator.",
    migration: "Migrateur de passage, mai et août–octobre.",
    food: "Campagnols, alouettes et autres petits oiseaux, lézards et insectes.",
    breeding: "Niche au sol dans la steppe (pas en Mongolie).",
    behavior: "Chasse bas au-dessus des prairies.",
    voice: "Généralement silencieux.",
    culture: "Son nom latin macrourus signifie « à longue queue ».",
    conservation: "Quasi menacé — conversion des steppes en cultures.",
    watching: "Examinez bien les busards en automne dans l’ouest.",
    bestTime: "septembre",
    facts: ["Quasi menacé à l’échelle mondiale.", "Niche depuis peu en Europe de l’Ouest.", "En vol, le mâle paraît presque blanc."]
  },
  "pied-harrier": {
    name: "Busard tchoug",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "41–49 cm",
    wingspan: "110–125 cm",
    weight: "265–455 g",
    summary: "Élégant busard asiatique ; le mâle est nettement noir et blanc. Visiteur d’été local des prairies humides du nord-est de la Mongolie.",
    description: "Le Busard tchoug niche du sud-est de la Sibérie et du nord-est de la Mongolie jusqu’au nord-est de la Chine et à la Corée, et hiverne en Asie du Sud-Est. En Mongolie, il niche dans les prairies humides des vallées du Khentii et du Dornod ; la vallée de Khurkh-Khüiten et le lac Buir sont les sites les plus connus.",
    features: ["Mâle : tête, poitrine et dos noirs ; dessous blanc ; ailes grises à barre noire et extrémités noires.", "Femelle : brune dessus, pâle et striée dessous, petit croupion blanc.", "Yeux jaunes chez le mâle.", "Silhouette fine de busard."],
    similar: "Busard d’Orient — mâle noir strié, plus grand, aux ailes plus larges. Busard Saint-Martin — mâle gris, pas noir.",
    habitatText: "Prairies humides, bords de marais et vallées herbeuses.",
    distribution: "Nord-est : Khentii (Khurkh, Onon), Dornod (lac Buir, Mongol Daguur).",
    migration: "Visiteur d’été, mai–septembre.",
    food: "Grenouilles, campagnols, petits oiseaux et gros insectes.",
    breeding: "Nid au sol dans l’herbe ou les roseaux ; 4 ou 5 œufs.",
    behavior: "Se pose sur des piquets ou au sol ; chasse en vol bas.",
    voice: "Surtout silencieux.",
    culture: "L’un des busards les plus spectaculaires au monde.",
    conservation: "Préoccupation mineure.",
    watching: "Vallée de Khurkh-Khüiten de juin à août.",
    bestTime: "juin–août",
    facts: ["Le mâle est noir et blanc.", "Ne niche qu’en Asie orientale.", "Se pose rarement dans les arbres."]
  },
  "montagus-harrier": {
    name: "Busard cendré",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "43–47 cm",
    wingspan: "97–115 cm",
    weight: "225–445 g",
    summary: "Busard gracieux aux ailes étroites, d’Europe et d’Asie occidentale. Seulement quelques mentions dans l’ouest de la Mongolie.",
    description: "Le Busard cendré niche de l’Europe à la Sibérie occidentale et au Kazakhstan et hiverne en Afrique et en Inde. Il est très rare en Mongolie : les quelques mentions viennent surtout de l’ouest, en fin d’été et en automne.",
    features: ["Mâle : gris, extrémités des ailes noires, barre noire sur le dessus de l’aile, stries rousses sur les flancs.", "Femelle : brune à croupion blanc, comme les autres femelles de busards.", "Ailes très étroites et pointues.", "Vol léger, rappelant une sterne."],
    similar: "Busards pâle et Saint-Martin — mâles sans barres alaires noires ; femelles difficiles à séparer.",
    habitatText: "Prairies ouvertes et cultures.",
    distribution: "Très rare ; ouest de la Mongolie et Khövsgöl.",
    migration: "Erratique ou migrateur rare.",
    food: "Campagnols, petits oiseaux, lézards et insectes.",
    breeding: "Niche au sol dans les céréales ou les herbes (pas en Mongolie).",
    behavior: "Glisse très bas au-dessus des champs.",
    voice: "Généralement silencieux.",
    culture: "Son nom anglais honore le naturaliste George Montagu.",
    conservation: "Préoccupation mineure.",
    watching: "Non attendu — examinez les busards dans l’ouest.",
    bestTime: "—",
    facts: ["Nom anglais d’après George Montagu.", "Niche souvent dans les céréales en Europe.", "Très rare en Mongolie."]
  },
  "shikra": {
    name: "Épervier shikra",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "26–30 cm",
    wingspan: "50–60 cm",
    weight: "100–220 g",
    summary: "Petit épervier pâle d’Asie tropicale et d’Afrique. Inscrit sur la liste mongole, mais sans mention documentée dans le GBIF — erratique exceptionnel.",
    description: "L’Épervier shikra est commun en Inde, en Asie du Sud-Est et en Afrique, dans les bois clairs, les jardins et les villages. Il figure sur la liste de Mongolie sur la base de très rares mentions ; toute observation doit être soigneusement documentée.",
    features: ["Dessus gris pâle ; dessous finement barré de roux.", "Trait sombre vertical sur la gorge blanche.", "Œil rouge chez l’adulte.", "Ailes courtes et arrondies, queue assez longue."],
    similar: "Épervier d’Europe — plus grand, plus sombre dessus, sans trait gulaire. Épervier du Japon — plus petit, plus sombre, œil sombre.",
    habitatText: "Bois clairs, bosquets et villages.",
    distribution: "Erratique exceptionnel.",
    migration: "Surtout sédentaire ; les oiseaux du nord se déplacent peu.",
    food: "Lézards, petits oiseaux, rongeurs et insectes.",
    breeding: "Niche dans les arbres ; 2 à 4 œufs (pas en Mongolie).",
    behavior: "Chasse à l’affût depuis un perchoir caché.",
    voice: "Un « ti-toui » perçant, souvent imité par les drongos.",
    culture: "Son nom vient du hindi-ourdou « shikra », un faucon de chasse.",
    conservation: "Préoccupation mineure.",
    watching: "Non attendu en Mongolie.",
    bestTime: "—",
    facts: ["Les drongos imitent son cri.", "Récemment placé dans le genre Tachyspiza.", "Très commun en Inde."]
  },
  "japanese-sparrowhawk": {
    name: "Épervier du Japon",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "23–30 cm",
    wingspan: "46–58 cm",
    weight: "90–190 g",
    summary: "Minuscule épervier d’Asie orientale, avec un fin trait sombre sur la gorge. Migrateur rare dans l’est et le nord de la Mongolie.",
    description: "L’Épervier du Japon niche dans l’Extrême-Orient russe, en Corée, au Japon et dans le nord-est de la Chine, et hiverne en Asie du Sud-Est. Il migre en grandes bandes le long de la côte d’Asie orientale. En Mongolie, il est rare, avec quelques mentions dans l’est et le Khangaï, surtout en mai.",
    features: ["Très petit épervier aux ailes arrondies et à queue courte.", "Mâle : gris foncé dessus, flancs roux, œil rouge.", "Femelle : dessous barré de brun, œil jaune.", "Fin trait sombre sur la gorge blanche."],
    similar: "Épervier d’Europe — plus grand, queue plus longue, sans trait gulaire. Épervier shikra — plus pâle dessus.",
    habitatText: "Forêts et lisières ; en migration, aussi les parcs.",
    distribution: "Rare ; est de la Mongolie et Khangaï.",
    migration: "Migrateur de passage, mai et septembre.",
    food: "Petits oiseaux, insectes et lézards.",
    breeding: "Niche dans les arbres ; 2 à 5 œufs (nidification non confirmée en Mongolie).",
    behavior: "Vol en battements rapides et glissades ; migre en bandes.",
    voice: "Un « kiki-kik-kik » jacassant.",
    culture: "En danger au Japon mais commun ailleurs.",
    conservation: "Préoccupation mineure.",
    watching: "Surveillez les petits éperviers en mai dans l’est.",
    bestTime: "mai",
    facts: ["L’un des plus petits éperviers d’Asie.", "Migre en bandes.", "Porte un trait sur la gorge."]
  },
  "eurasian-sparrowhawk": {
    name: "Épervier d'Europe",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "28–40 cm",
    wingspan: "56–78 cm",
    weight: "110–340 g",
    summary: "Petit rapace fougueux qui surprend les passereaux ; le mâle est gris-bleu dessus et barré d’orange dessous. Commun en migration dans toute la Mongolie, il niche dans les forêts du nord.",
    description: "L’Épervier d’Europe est présent dans toutes les régions tempérées de l’Ancien Monde. Chasseur d’oiseaux spécialisé, il surprend ses proies par des vols rapides et bas le long des haies et des lisières ; il chasse souvent en ville. La femelle est jusqu’à un quart plus grande que le mâle. En Mongolie, il niche dans les forêts du Khentii, du Khangaï et de l’Altaï et se voit partout en migration, y compris dans les oasis du Gobi comme Yolyn Am, avec des pics en avril–mai et en septembre.",
    features: ["Mâle : gris-bleu dessus, barré d’orange dessous, joues orangées.", "Femelle : gris-brun dessus, barrée de gris-brun dessous, sourcil blanc.", "Œil jaune ; longues pattes fines et jaunes.", "Ailes courtes et arrondies, longue queue carrée.", "Vol « battements–battements–glissade »."],
    similar: "Autour des palombes — bien plus grand et lourd, poitrine bombée, sous-caudales blanches. Épervier du Japon — plus petit, trait gulaire. Faucon crécerelle — ailes pointues, fait du surplace.",
    habitatText: "Forêts, lisières, parcs et villes ; tous milieux en migration.",
    distribution: "Toute la Mongolie : Oulan-Bator et Terelj, Khurkh, lac Khar Us, Yolyn Am et steppes de l’est.",
    migration: "Niche dans le nord (avril–octobre) ; pics de passage en mai et septembre ; quelques hivernants.",
    food: "Petits oiseaux : moineaux, mésanges, fringilles et grives.",
    breeding: "Nid de brindilles dans un arbre ; 4 ou 5 œufs bleutés ; éclosion au bout de 33 jours.",
    behavior: "Surprend les oiseaux par des attaques soudaines ; parades en vol plané au printemps.",
    voice: "Un « kèk-kèk-kèk » rapide au nid.",
    culture: "Traditionnellement utilisé en fauconnerie pour chasser la caille.",
    conservation: "Préoccupation mineure ; rétabli en Europe après l’interdiction des pesticides.",
    watching: "Parcs d’Oulan-Bator, Terelj et oasis du Gobi en migration.",
    bestTime: "avril–mai, sept.",
    facts: ["La femelle est bien plus grande que le mâle.", "Chasse les oiseaux en ville.", "S’est rétabli après l’interdiction du DDT."]
  },
  "northern-goshawk": {
    name: "Autour des palombes",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "46–63 cm",
    wingspan: "89–122 cm",
    weight: "0.6–1.4 kg",
    summary: "Puissant rapace forestier au sourcil blanc marqué et aux yeux rouge orangé. Résident rare et discret de la taïga et de la steppe boisée de Mongolie.",
    description: "L’Autour des palombes vit dans toutes les forêts tempérées d’Eurasie. Grand et lourd, il chasse oiseaux et mammifères par de courtes attaques explosives entre les arbres. Les oiseaux de l’extrême nord sont très pâles. En Mongolie, il niche dans les forêts de mélèzes et de pins du Khentii, du Khövsgöl et du Khangaï ; en hiver, certains descendent vers la steppe boisée et les vallées. Farouche et facilement négligé, il compte peu de mentions.",
    features: ["Grand rapace à poitrine large et longue queue arrondie.", "Adulte : gris dessus, finement barré de gris dessous, sourcil blanc marqué et joue sombre.", "Œil jaune à rouge orangé foncé.", "Juvénile : brun dessus, chamois dessous avec des gouttes sombres.", "Sous-caudales blanches et duveteuses, bien visibles en parade."],
    similar: "Épervier d’Europe — bien plus petit et fin, queue étroite, sans sourcil marqué. Faucons sacre et gerfaut — ailes pointues, œil sombre.",
    habitatText: "Forêts matures de conifères et mixtes, lisières et ripisylves.",
    distribution: "Forêts du Khentii, de la Selenge, du Khövsgöl et du Khangaï ; parfois Terelj et Oulan-Bator en hiver.",
    migration: "Surtout sédentaire ; les oiseaux nordiques erratiques en hiver.",
    food: "Tétras, gélinottes, pigeons, corvidés, écureuils et lièvres.",
    breeding: "Grand nid de branches haut dans un conifère ; 2 à 4 œufs.",
    behavior: "Chasse à couvert par attaques soudaines ; parade en battements lents et profonds au-dessus de la forêt au début du printemps.",
    voice: "Un « kyèk-kyèk-kyèk » fort et rauque près du nid.",
    culture: "Oiseau prisé des fauconniers depuis l’Antiquité ; Attila en aurait porté l’image sur son casque.",
    conservation: "Préoccupation mineure.",
    watching: "Sentiers forestiers calmes de Terelj, du Khentii et du Khövsgöl au début du printemps, quand les couples paradent.",
    bestTime: "mars–mai",
    facts: ["Les femelles sont bien plus grandes que les mâles.", "Peut capturer un lièvre.", "Les oiseaux nordiques peuvent être presque blancs."]
  },
  "white-tailed-sea-eagle": {
    name: "Pygargue à queue blanche",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "66–94 cm",
    wingspan: "178–245 cm",
    weight: "3.1–6.9 kg",
    summary: "Aigle immense au gros bec jaune, aux ailes larges comme des « portes de grange » et à la courte queue blanche. Il niche près des grands lacs et rivières du nord de la Mongolie.",
    description: "Le Pygargue à queue blanche est le plus grand aigle d’Europe et d’Asie du Nord. Il vit près des lacs, des rivières et des côtes, se nourrit de poissons et d’oiseaux d’eau et consomme des charognes. Après un siècle de persécution et d’empoisonnement par les pesticides, il s’est rétabli dans une grande partie de l’Europe. En Mongolie, il niche dans de grands arbres ou sur des falaises près des grands lacs et rivières — lac Ögii, lac Khar Us, Terkhiin Tsagaan Nuur, Khövsgöl, vallées de Khurkh et de l’Onon — d’avril à octobre–novembre.",
    features: ["Très grand, ailes longues, larges et rectangulaires aux extrémités digitées.", "Adulte : corps brun, tête et cou plus pâles, queue cunéiforme blanc pur.", "Énorme bec jaune ; pattes et yeux jaunes.", "Juvénile : brun foncé, bec sombre, queue pâle bordée de sombre.", "En vol, la tête et la queue dépassent autant l’une que l’autre."],
    similar: "Pygargue de Pallas — queue blanche à large bande noire, tête pâle. Aigle royal — queue plus longue, tête plus petite, pas de queue blanche. Vautour moine — entièrement sombre, petite tête.",
    habitatText: "Grands lacs, rivières et zones humides avec grands arbres ou falaises.",
    distribution: "Lacs du Khangaï (Ögii, Terkhiin Tsagaan), Khövsgöl, lac Khar Us, Khentii (Khurkh, Onon), lacs du Dornod.",
    migration: "Visiteur d’été, avril–novembre ; pics en juin et septembre ; quelques hivernants.",
    food: "Poissons, canards et foulques, autres oiseaux d’eau, charognes.",
    breeding: "Très grand nid dans un arbre ou sur une falaise, utilisé de nombreuses années ; 1 à 3 œufs.",
    behavior: "Reste longtemps perché ; vole la nourriture d’autres oiseaux.",
    voice: "Un « kli-kli-kli » glapissant, souvent en duo.",
    culture: "Symbole des lacs sauvages du Nord.",
    conservation: "Préoccupation mineure ; inscrit au Livre rouge de Mongolie.",
    watching: "Lac Ögii, lac Khar Us et vallée de Khurkh en été.",
    bestTime: "mai–sept.",
    facts: ["Envergure jusqu’à 2,45 m.", "Réutilise le même nid pendant des décennies.", "S’est rétabli en Europe après l’interdiction des pesticides."]
  },
  "black-kite": {
    name: "Milan noir",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "48–60 cm",
    wingspan: "130–155 cm",
    weight: "0.6–1.1 kg",
    summary: "Rapace brun foncé à queue légèrement fourchue, tournoyant sans cesse au-dessus des villes, des yourtes et des vallées. Le grand rapace le plus commun de l’été mongol.",
    description: "Le Milan noir est peut-être le rapace le plus nombreux au monde. Opportuniste, il se nourrit de charognes, vole de la nourriture et capture de petits animaux. La sous-espèce orientale (milan à oreilles noires) niche dans toute la Mongolie et se rassemble en grand nombre autour d’Oulan-Bator, des camps de yourtes, des décharges et du bétail. Il arrive en avril et repart en septembre vers l’Asie du Sud.",
    features: ["Rapace brun moyen à grand, aux longues ailes coudées.", "Queue légèrement fourchue, qu’il tord sans cesse.", "Plage pâle à la base des primaires.", "Tache sombre sur la joue chez la sous-espèce orientale.", "Souvent en groupes lâches."],
    similar: "Aigle botté (forme sombre) — queue carrée, « phares » blancs. Busard des roseaux (femelle) — queue plus longue, vol bas. Buses — queue large et arrondie.",
    habitatText: "Villes, camps de yourtes, vallées, steppe et lisières.",
    distribution: "Toute la Mongolie ; très commun autour d’Oulan-Bator, Khurkh, Terelj, Khustai et des lacs.",
    migration: "Visiteur d’été, avril–septembre ; maximum en mai–juin.",
    food: "Charognes, déchets, rongeurs, poissons, insectes et petits oiseaux.",
    breeding: "Niche dans les arbres, sur les falaises ou les pylônes, décorant son nid de chiffons et de plastique ; 2 ou 3 œufs.",
    behavior: "Plane pendant des heures ; saisit la nourriture au sol ou sur l’eau en vol.",
    voice: "Un « pii-èrrr » aigu et hennissant.",
    culture: "En Australie, on dit que les milans propagent les feux en transportant des brindilles enflammées.",
    conservation: "Préoccupation mineure.",
    watching: "Partout en été — surtout au-dessus d’Oulan-Bator et des camps de yourtes.",
    bestTime: "mai–août",
    facts: ["Peut-être le rapace le plus nombreux au monde.", "Décore son nid de déchets.", "Se sert de sa queue comme d’un gouvernail."]
  },
  "grey-faced-buzzard": {
    name: "Busautour à joues grises",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "41–46 cm",
    wingspan: "101–110 cm",
    weight: "375–435 g",
    summary: "Rapace élancé d’Asie orientale à face grise et trait gulaire sombre. Sur la liste mongole, mais sans mention GBIF — erratique exceptionnel.",
    description: "Le Busautour à joues grises niche en Mandchourie, en Corée et au Japon et hiverne en Asie du Sud-Est, migrant en grandes bandes. Ce n’est pas une vraie buse mais un genre distinct. Sa présence en Mongolie est exceptionnelle.",
    features: ["Tête et face grises, gorge blanche avec un trait central sombre.", "Dos brun ; dessous barré de brun et de blanc.", "Longues ailes, queue assez longue.", "Juvénile : brun avec un large sourcil blanc."],
    similar: "Buses variable et de Chine — plus massives, queue plus courte, sans trait gulaire.",
    habitatText: "Forêts et lisières près de milieux ouverts.",
    distribution: "Erratique exceptionnel.",
    migration: "Migrateur ; non attendu en Mongolie.",
    food: "Lézards, grenouilles, petits mammifères et gros insectes.",
    breeding: "Niche dans les arbres (pas en Mongolie).",
    behavior: "Chasse à l’affût en lisière.",
    voice: "Un « pik-kouii » sifflé.",
    culture: "Sa migration massive est un temps fort de l’automne au Japon et à Taïwan.",
    conservation: "Préoccupation mineure.",
    watching: "Non attendu en Mongolie.",
    bestTime: "—",
    facts: ["Migre par milliers.", "N’est pas une vraie buse du genre Buteo.", "Doit son nom à sa face grise."]
  },
  "rough-legged-buzzard": {
    name: "Buse pattue",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "46–68 cm",
    wingspan: "120–153 cm",
    weight: "0.6–1.7 kg",
    summary: "Buse arctique aux pattes emplumées, à queue blanche barrée de noir et au ventre sombre. Hivernante peu commune dans les steppes de Mongolie.",
    description: "La Buse pattue niche dans la toundra arctique d’Eurasie et d’Amérique du Nord et descend vers le sud en hiver. Elle fait souvent du surplace en chassant, comme une crécerelle. En Mongolie, c’est une migratrice et hivernante peu commune, notée dans toutes les régions d’octobre à avril.",
    features: ["Pattes emplumées jusqu’aux doigts.", "Queue blanche avec une large bande noire près de l’extrémité.", "Ventre sombre et taches carpiennes sombres sous l’aile.", "Tête pâle.", "Fait régulièrement du surplace."],
    similar: "Buse de Chine — plus grande, queue pâle sans bande noire nette. Buse variable — queue barrée. Buse féroce — queue rousse.",
    habitatText: "Steppes ouvertes, champs et vallées en hiver.",
    distribution: "Peu commune partout ; lac Khar Us, Khurkh, Oulan-Bator et Gobi.",
    migration: "Hivernante et migratrice de passage, octobre–avril.",
    food: "Campagnols, lemmings et pikas ; aussi oiseaux et charognes.",
    breeding: "Niche sur les falaises arctiques (pas en Mongolie) ; la ponte dépend de l’abondance des lemmings.",
    behavior: "Fait du surplace face au vent ; se pose sur des buttes ou des piquets.",
    voice: "Un « pii-you » miaulé.",
    culture: "Son nom latin lagopus signifie « pied de lièvre ».",
    conservation: "Préoccupation mineure.",
    watching: "Steppes hivernales près d’Oulan-Bator et dans l’est.",
    bestTime: "nov.–mars",
    facts: ["Pattes emplumées comme un lagopède.", "L’un des rares rapaces à faire du surplace.", "Niche dans l’Arctique."]
  },
  "eurasian-buzzard": {
    name: "Buse variable",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "40–58 cm",
    wingspan: "109–140 cm",
    weight: "0.4–1.4 kg",
    summary: "Buse de taille moyenne au plumage variable, planant sur des ailes larges. En Mongolie, la forme orientale « buse des steppes » se voit surtout dans l’ouest et en migration.",
    description: "La Buse variable est le rapace le plus commun d’Europe. Son aire s’étend vers l’est jusqu’au Tian Shan, à la Sibérie occidentale et au nord-ouest de la Mongolie ; les oiseaux orientaux (sous-espèce vulpinus, « buse des steppes ») migrent jusqu’en Afrique. En Mongolie, elle fréquente surtout les forêts de l’Altaï et du Khangaï et passe en migration, notamment en septembre.",
    features: ["Ailes larges et arrondies, queue courte en éventail.", "Plumage très variable, du pâle au brun foncé ou roux.", "Bande pâle sur la poitrine chez beaucoup d’oiseaux.", "Queue finement barrée.", "Ailes en léger V en vol plané."],
    similar: "Buse de Chine — plus grande, plus pâle, queue pâle. Buse féroce — queue rousse, ventre sombre. Buse pattue — queue blanche à bande noire.",
    habitatText: "Lisières et vallées boisées près de milieux ouverts.",
    distribution: "Surtout l’ouest et le Khangaï ; partout en migration (Oulan-Bator, Terelj, lac Khar Us).",
    migration: "Visiteuse d’été et migratrice, avril–octobre.",
    food: "Campagnols et autres rongeurs, reptiles, oiseaux, vers de terre.",
    breeding: "Niche dans les arbres ; 2 à 4 œufs.",
    behavior: "Attend souvent sur un perchoir ; tournoie dans les ascendances.",
    voice: "Un « piii-ya » miaulé, le cri classique de la buse.",
    culture: "Son cri est souvent utilisé au cinéma pour les aigles.",
    conservation: "Préoccupation mineure.",
    watching: "Vallées de l’Altaï et du Khangaï en été ; migration en septembre.",
    bestTime: "mai–sept.",
    facts: ["Le rapace le plus commun d’Europe.", "Les oiseaux orientaux migrent en Afrique.", "Couleur extrêmement variable."]
  },
  "long-legged-buzzard": {
    name: "Buse féroce",
    altNames: "",
    order: "Accipitriformes",
    family: "Accipitridae (buses, aigles et vautours)",
    statusText: "Préoccupation mineure (LC).",
    length: "50–65 cm",
    wingspan: "126–155 cm",
    weight: "0.6–1.8 kg",
    summary: "Grande buse aux longues ailes, à tête pâle et queue unie roux orangé. Visiteuse d’été des déserts et montagnes sèches du Gobi et de l’ouest de la Mongolie.",
    description: "La Buse féroce est présente du sud-est de l’Europe et de l’Afrique du Nord jusqu’en Asie centrale, dans les pays secs et ouverts. En Mongolie, elle niche dans le Gobi et l’ouest aride, sur les falaises et les affleurements rocheux, et chasse gerbilles, mérions et spermophiles. Elle côtoie la Buse de Chine dans le Gobi, et les deux sont parfois difficiles à distinguer.",
    features: ["Tête et poitrine pâles, souvent crème.", "Queue unie roux orangé, sans barres, plus pâle à la base.", "Ventre et culottes sombres ; taches carpiennes noires sous l’aile.", "Longues ailes, relevées en V en vol plané.", "Fait souvent du surplace."],
    similar: "Buse de Chine — plus grande, queue blanchâtre, pattes emplumées. Buse variable — plus petite, queue barrée.",
    habitatText: "Déserts, semi-déserts, collines rocheuses et vallées de montagne sèches.",
    distribution: "Gobi (Yolyn Am, lac Orog, Böön Tsagaan, Taatsiin Tsagaan) et ouest (lac Khar Us) ; aussi lac Ögii.",
    migration: "Visiteuse d’été, avril–octobre.",
    food: "Gerbilles, mérions, spermophiles et autres rongeurs ; reptiles et insectes.",
    breeding: "Niche sur les falaises ou les rochers ; 2 à 4 œufs.",
    behavior: "Chasse depuis un rocher ou en surplace ; plane au-dessus des collines sèches.",
    voice: "Un cri miaulé, plus aigu que celui de la Buse variable.",
    culture: "Réputée la plus agressive des buses.",
    conservation: "Préoccupation mineure.",
    watching: "Yolyn Am et lacs du Gobi en été.",
    bestTime: "mai–août",
    facts: ["Queue rousse sans barres.", "Vit dans des régions chaudes et sèches.", "Difficile à distinguer de la Buse de Chine."]
  },
  "lesser-kestrel": {
    name: "Faucon crécerellette",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Préoccupation mineure (LC).",
    length: "27–33 cm",
    wingspan: "58–72 cm",
    weight: "90–208 g",
    summary: "Petit faucon colonial ; le mâle a le dos roux uni, la tête et la queue gris-bleu. Visiteur d’été commun dans la steppe et le Gobi, chassant souvent les insectes en groupe.",
    description: "Le Faucon crécerellette niche de la Méditerranée à l’Asie centrale, à la Mongolie et au nord de la Chine, et hiverne en Afrique australe. Il niche en colonies dans les falaises, les ruines et les bâtiments et se nourrit surtout de sauterelles et de coléoptères, capturés au sol ou en vol. En Mongolie, il est répandu d’avril à septembre, en particulier dans le Gobi et les steppes du Khentii et du Töv ; on trouve des colonies à Khustai, Ikh Nart et Yolyn Am.",
    features: ["Mâle : dos roux uni sans taches, tête gris-bleu sans moustache, panneau gris-bleu sur l’aile.", "Femelle : brun roux barré de sombre, très semblable à la femelle de crécerelle.", "Griffes pâles (noires chez la crécerelle).", "Queue légèrement cunéiforme à bande noire.", "Souvent en petits groupes."],
    similar: "Faucon crécerelle — mâle au dos tacheté et à moustache sombre ; plus grand ; souvent seul. Faucon de l’Amour — mâle gris foncé à « culotte » rouge.",
    habitatText: "Steppe et semi-désert ouverts avec falaises, ruines ou bâtiments pour nicher.",
    distribution: "Gobi (Yolyn Am, Ikh Nart), steppe centrale (Khustai), Khentii (Khurkh) et ouest.",
    migration: "Visiteur d’été, avril–septembre ; pic en mai.",
    food: "Sauterelles, coléoptères et autres gros insectes ; parfois lézards et petits rongeurs.",
    breeding: "Colonial ; niche dans des cavités de falaises, de murs et de toits ; 3 à 6 œufs.",
    behavior: "Chasse en groupes lâches, fait moins de surplace que la crécerelle ; dortoirs collectifs.",
    voice: "Un « tché-tché-tché » rauque à la colonie.",
    culture: "En Méditerranée, il niche traditionnellement dans les clochers et les vieux remparts.",
    conservation: "Préoccupation mineure ; en déclin en Europe puis rétabli grâce à la conservation.",
    watching: "Khustai, Ikh Nart et Yolyn Am, mai–août.",
    bestTime: "mai–août",
    facts: ["Niche en colonies.", "Mange surtout des insectes.", "Hiverne en Afrique australe."]
  },
  "common-kestrel": {
    name: "Faucon crécerelle",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Préoccupation mineure (LC).",
    length: "32–39 cm",
    wingspan: "65–82 cm",
    weight: "136–314 g",
    summary: "Le faucon qui fait du « Saint-Esprit » : dos roux tacheté de noir, longue queue, et l’habitude de rester immobile dans le vent. Présent dans toute la Mongolie, c’est le faucon le plus commun.",
    description: "Le Faucon crécerelle est présent en Europe, en Asie et en Afrique. Il chasse campagnols, lézards et insectes en faisant du surplace face au vent puis en se laissant tomber sur sa proie. En Mongolie, il niche partout, de l’Altaï au Dornod et de la taïga au Gobi, sur les falaises, dans les arbres, les vieux nids de corvidés, les bâtiments et même les interstices des toits de yourtes. La plupart partent à l’automne, mais certains hivernent autour d’Oulan-Bator et dans les vallées abritées.",
    features: ["Mâle : tête grise et queue grise à bande noire ; dos roux tacheté de noir.", "Femelle : tête brune et queue brune barrée.", "Fine moustache sombre sous l’œil.", "Longues ailes pointues et longue queue.", "Fait du surplace face au vent, queue étalée."],
    similar: "Faucon crécerellette — mâle au dos roux uni, sans moustache ; souvent en groupe. Faucon émerillon — plus petit, ne fait pas de surplace, vol fougueux. Épervier d’Europe — ailes arrondies.",
    habitatText: "Tous milieux ouverts : steppe, bordures de désert, falaises, villes et lisières.",
    distribution: "Toute la Mongolie : Oulan-Bator, Khustai, Terelj, Khurkh, lac Khar Us, Yolyn Am et steppes de l’est.",
    migration: "Surtout visiteur d’été (mars–octobre) ; quelques hivernants.",
    food: "Campagnols, gerbilles, lézards, sauterelles et coléoptères ; petits oiseaux.",
    breeding: "Ne construit pas de nid — utilise corniches, cavités ou vieux nids de corvidés ; 3 à 6 œufs.",
    behavior: "Fait du surplace ; se pose sur les poteaux et les fils.",
    voice: "Un « kii-kii-kii » aigu.",
    culture: "Son surplace lui vaut le surnom de « Saint-Esprit » en français.",
    conservation: "Préoccupation mineure.",
    watching: "Partout dans la campagne ; cherchez un petit faucon en surplace au bord de la route.",
    bestTime: "avril–sept.",
    facts: ["Voit l’ultraviolet et suit ainsi les traces d’urine des campagnols.", "Ne construit pas son nid.", "Le faucon le plus commun de Mongolie."]
  },
  "red-footed-falcon": {
    name: "Faucon kobez",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Vulnérable (VU).",
    length: "28–31 cm",
    wingspan: "65–76 cm",
    weight: "130–197 g",
    summary: "Petit faucon insectivore d’Europe de l’Est ; le mâle est gris foncé à « culotte » rouge. Connu en Mongolie seulement par de très anciennes mentions — erratique.",
    description: "Le Faucon kobez niche de l’Europe de l’Est à la Sibérie occidentale et hiverne en Afrique australe. Il ressemble beaucoup à son cousin oriental, le Faucon de l’Amour, commun en Mongolie. Les rares mentions mongoles datent du XIXᵉ siècle et pourraient résulter d’une confusion avec ce dernier.",
    features: ["Mâle : gris ardoise foncé, culottes et sous-caudales rouge brique ; couvertures sous-alaires sombres.", "Femelle : calotte et dessous orangés, dos gris barré.", "Pattes et cercle orbital rouge orangé.", "Fait souvent du surplace."],
    similar: "Faucon de l’Amour — mâle aux couvertures sous-alaires blanches ; femelle plus blanche dessous, striée de sombre.",
    habitatText: "Steppes ouvertes parsemées d’arbres.",
    distribution: "Erratique ; anciennes mentions dans l’ouest.",
    migration: "Très rare.",
    food: "Gros insectes, surtout libellules et coléoptères.",
    breeding: "Colonial dans les nids de Corbeaux freux (pas en Mongolie).",
    behavior: "Chasse les insectes en vol en groupes lâches.",
    voice: "Un « kiou-kiou-kiou » jacassant.",
    culture: "Son nom « kobez » vient d’un mot russe désignant ce faucon.",
    conservation: "Vulnérable — disparition des corbeautières et des prairies.",
    watching: "Non attendu ; examinez tous les Faucons de l’Amour.",
    bestTime: "—",
    facts: ["Vulnérable à l’échelle mondiale.", "Niche dans de vieux nids de freux.", "Proche parent du Faucon de l’Amour."]
  },
  "merlin": {
    name: "Faucon émerillon",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Préoccupation mineure (LC).",
    length: "24–33 cm",
    wingspan: "50–73 cm",
    weight: "125–300 g",
    summary: "Petit faucon trapu et très rapide qui poursuit les petits oiseaux au ras du sol. En Mongolie, surtout migrateur et hivernant.",
    description: "Le Faucon émerillon niche dans le nord de l’Eurasie et de l’Amérique du Nord, dans les landes, les lisières de taïga et la toundra, et hiverne plus au sud. Il poursuit alouettes et pipits en vol rapide, bas et sinueux. En Mongolie, il niche peut-être dans le nord mais se voit surtout en migration en septembre–octobre et en hiver, dans toutes les régions.",
    features: ["Petit faucon trapu aux ailes courtes et pointues.", "Mâle : gris-bleu dessus, chamois orangé strié dessous.", "Femelle : brune dessus, fortement striée dessous ; queue barrée.", "Moustache faible.", "Vol rapide, bas et fougueux — fait rarement du surplace."],
    similar: "Faucon crécerelle — plus grand, longue queue, fait du surplace. Faucon hobereau — ailes plus longues, moustache nette, culotte rousse. Épervier d’Europe — ailes arrondies, œil jaune.",
    habitatText: "Steppe ouverte, vallées et lisières.",
    distribution: "Partout ; Khurkh, lac Khar Us, Oulan-Bator, Khustai, lac Ögii et lac Buir.",
    migration: "Migrateur et hivernant, septembre–avril ; pic en septembre.",
    food: "Petits oiseaux : alouettes, pipits, bruants.",
    breeding: "Niche au sol ou dans de vieux nids de corvidés (peu de mentions en Mongolie) ; 3 à 5 œufs.",
    behavior: "Poursuit ses proies longuement, souvent à un mètre du sol.",
    voice: "Un « ki-ki-ki » rapide.",
    culture: "Au Moyen Âge, c’était le faucon des dames de la noblesse.",
    conservation: "Préoccupation mineure.",
    watching: "Steppes ouvertes en septembre–octobre et en hiver.",
    bestTime: "sept.–oct.",
    facts: ["L’un des plus petits faucons.", "Chasse les oiseaux en poursuite.", "Faucon des dames au Moyen Âge."]
  },
  "eurasian-hobby": {
    name: "Faucon hobereau",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Préoccupation mineure (LC).",
    length: "29–35 cm",
    wingspan: "70–84 cm",
    weight: "131–340 g",
    summary: "Faucon élégant, rappelant un martinet, aux longues ailes en faucille, à la moustache marquée et à la « culotte » rousse. Visiteur d’été de la steppe boisée et des vallées.",
    description: "Le Faucon hobereau niche en Europe et en Asie et hiverne en Afrique et en Asie du Sud. Assez rapide pour attraper hirondelles et martinets en vol, il capture aussi des libellules qu’il mange en volant. En Mongolie, il niche dans les zones boisées du nord et les oasis du Gobi, arrive en mai et repart en septembre ; on le voit souvent à Khurkh, à Terelj et autour d’Oulan-Bator.",
    features: ["Dessus gris ardoise foncé.", "Moustache noire marquée sur une joue blanche.", "Dessous blanc fortement strié de noir.", "Culotte et sous-caudales rouille.", "Longues ailes pointues de martinet, queue courte."],
    similar: "Faucon pèlerin — plus grand et lourd, barré dessous, sans culotte rousse. Faucon de l’Amour — plus petit ; mâle gris uni. Faucon émerillon — ailes plus courtes, sans moustache marquée.",
    habitatText: "Lisières, vallées arborées et milieux ouverts avec bosquets.",
    distribution: "Khentii et Selenge (Khurkh, Terelj, Oulan-Bator), Khustai, steppes de l’est et oasis du Gobi.",
    migration: "Visiteur d’été, mai–septembre ; pic en mai–juin.",
    food: "Libellules et autres gros insectes, hirondelles, martinets, alouettes.",
    breeding: "Utilise de vieux nids de corvidés ou de pies ; 2 ou 3 œufs, les jeunes éclosant avec les jeunes hirondelles.",
    behavior: "Chasse en vol rapide ; mange les insectes en vol en les passant de la patte au bec.",
    voice: "Un « kiou-kiou-kiou » rapide.",
    culture: "Son nom vient du vieux français hobé, « sautiller ».",
    conservation: "Préoccupation mineure.",
    watching: "Vallée de Khurkh et Terelj, juin–août, au-dessus des zones humides riches en libellules.",
    bestTime: "juin–août",
    facts: ["Peut capturer des martinets en vol.", "Mange les libellules en volant.", "Niche dans de vieux nids de corvidés."]
  },
  "gyrfalcon": {
    name: "Faucon gerfaut",
    altNames: "",
    order: "Falconiformes",
    family: "Falconidae (faucons)",
    statusText: "Préoccupation mineure (LC).",
    length: "48–65 cm",
    wingspan: "110–130 cm",
    weight: "0.8–2.1 kg",
    summary: "Le plus grand faucon du monde, du blanc au gris foncé, nicheur arctique. Erratique hivernal exceptionnel en Mongolie, sans mention GBIF.",
    description: "Le Faucon gerfaut niche sur les côtes et la toundra arctiques d’Eurasie et d’Amérique du Nord et chasse lagopèdes, oiseaux d’eau et lièvres. Il descend rarement vers le sud ; en Mongolie, il n’est connu que par quelques observations hivernales, peut-être confondues avec des Faucons sacres pâles.",
    features: ["Très grand faucon lourd, ailes larges à la base et longue queue.", "Couleur du presque blanc au gris foncé.", "Moustache faible.", "Battements lents et puissants."],
    similar: "Faucon sacre — plus brun, tête plus pâle ; commun en Mongolie. Faucon pèlerin — plus petit, moustache marquée. Autour des palombes — ailes arrondies.",
    habitatText: "Toundra et côtes arctiques ; en hiver, milieux ouverts.",
    distribution: "Erratique hivernal exceptionnel.",
    migration: "Erratique en hiver.",
    food: "Lagopèdes, tétras, canards, lièvres.",
    breeding: "Niche sur les falaises arctiques (pas en Mongolie).",
    behavior: "Poursuit ses proies en longs vols puissants au ras du sol.",
    voice: "Un « kyak-kyak » rauque.",
    culture: "Dans la fauconnerie médiévale, il était réservé aux rois.",
    conservation: "Préoccupation mineure.",
    watching: "Non attendu ; examinez les faucons pâles en hiver.",
    bestTime: "—",
    facts: ["Le plus grand faucon du monde.", "Autrefois réservé aux rois.", "Peut être presque entièrement blanc."]
  },
  "osprey": {
    name: "Balbuzard pêcheur",
    altNames: "",
    order: "Accipitriformes",
    family: "Pandionidae (balbuzards)",
    statusText: "Préoccupation mineure (LC).",
    length: "50–66 cm",
    wingspan: "127–180 cm",
    weight: "0.9–2.1 kg",
    summary: "Rapace pêcheur à tête blanche, bandeau sombre sur l’œil et longues ailes coudées. Il plonge pattes en avant dans les lacs et rivières ; en Mongolie, surtout en migration.",
    description: "Le Balbuzard pêcheur est présent sur tous les continents sauf l’Antarctique. Il se nourrit presque uniquement de poissons, fait du surplace au-dessus de l’eau puis plonge pattes en avant. Son doigt externe réversible et ses soles épineuses l’aident à tenir les poissons glissants. En Mongolie, c’est un visiteur d’été rare et un migrateur sur les lacs et rivières, avec des pics en mai et septembre ; le lac Ögii est l’un des meilleurs sites.",
    features: ["Dessous et tête blancs avec un bandeau sombre à travers l’œil.", "Dessus brun foncé.", "Longues ailes étroites coudées comme celles d’un goéland, taches carpiennes noires.", "Bande pectorale sombre, plus marquée chez la femelle.", "Plonge pattes en avant."],
    similar: "Pygargue à queue blanche — bien plus grand, dessous sombre. Grands goélands — sans bandeau sombre, vol différent.",
    habitatText: "Lacs, rivières et réservoirs poissonneux.",
    distribution: "Lacs du Khangaï (lac Ögii), rivières du Khentii et de la Selenge, lacs de l’ouest et du Gobi en migration.",
    migration: "Migrateur et visiteur d’été rare ; pics en mai et septembre.",
    food: "Poissons.",
    breeding: "Grand nid de branches au sommet d’un arbre, sur une falaise ou un pylône ; 2 à 4 œufs.",
    behavior: "Fait du surplace puis plonge ; transporte le poisson la tête vers l’avant.",
    voice: "Une série de sifflements clairs, « kiou-kiou ».",
    culture: "Seul représentant vivant de sa famille, les Pandionidés.",
    conservation: "Préoccupation mineure ; rétabli après l’interdiction des pesticides.",
    watching: "Lac Ögii en mai et septembre.",
    bestTime: "mai, sept.",
    facts: ["Son doigt externe peut se tourner vers l’arrière.", "Présent sur tous les continents sauf l’Antarctique.", "Porte le poisson tête en avant pour réduire la traînée."]
  }
});
