B2T("en", {
  "european-honey-buzzard": {
    T: { c: { brown: .45, gray: .2, white: .2, buff: .15 }, hb: ["forest", "steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["52–60 cm", "130–150 cm", "440–1,050 g"] },
    s: "A slim raptor of European and western Asian woodland that feeds on the grubs of wasps and bees. It is a rare vagrant to Mongolia.",
    d: "The European Honey Buzzard breeds in Europe and western Asia and winters in tropical Africa. Despite its name it is closer to kites than to true buzzards. It digs out wasp and bee nests to eat the larvae, and dense, scale-like feathers on the face protect it from stings. In Mongolia it has been recorded only very rarely; its eastern relative, the East Asian Honey Buzzard, is the one normally seen here.",
    f: ["Small, pigeon-like head on a longish neck.", "Long tail with two narrow dark bars near the base and a broad dark band near the tip.", "Male has a blue-grey head; female’s head is brown.", "Plumage very variable, from pale to dark brown.", "Soars on flat wings with slightly drooping tips."],
    si: "East Asian Honey Buzzard — larger, with a short crest and six-fingered wingtips. Eurasian Buzzard — heavier, shorter tail, broader head.",
    h: "Deciduous and mixed woodland with clearings.",
    di: "A rare vagrant; very few records from Mongolia.",
    mi: "Long-distance migrant between Europe/western Asia and Africa.",
    fo: "Wasp and bee larvae and pupae; also insects, frogs and small birds.",
    br: "Nests high in trees; 1–3 eggs.",
    be: "Walks on the ground to dig out wasp nests with its feet.",
    v: "A plaintive, whistling “peee-lu”.",
    cu: "Its Latin name apivorus means “bee-eater”.",
    co: "Least Concern; shooting on migration is a threat in some countries.",
    w: "Not regularly seen in Mongolia — check honey buzzards carefully on migration.",
    bt: "May, September",
    fa: ["Eats wasp grubs.", "Face covered in stiff, scale-like feathers.", "Winters in Africa."]
  },
  "east-asian-honey-buzzard": {
    T: { c: { brown: .45, white: .2, gray: .15, buff: .15, black: .05 }, hb: ["forest", "steppe", "desert"], bk: "hooked", bh: ["soar", "perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["52–68 cm", "128–155 cm", "0.75–1.5 kg"] },
    s: "A large, variable honey buzzard with a small crest that raids wasp and bee nests. Passes through Mongolia in spring and autumn.",
    d: "The East Asian (Crested) Honey Buzzard breeds in Siberia and Japan and winters in Southeast Asia and India. Its long, narrow head, grooved tongue and dense facial feathers are adaptations for digging into bee and wasp nests. In Mongolia most records come in May and September, when birds cross the country on migration.",
    f: ["Small head with a short crest at the back.", "Six long “fingers” at the wingtip.", "Tail with broad, evenly spaced dark bars.", "Plumage from pale to very dark; throat often pale with a dark stripe.", "Soars on flat wings."],
    si: "European Honey Buzzard — smaller, no crest; rare here. Eurasian Buzzard — shorter tail, rounder wings, broader head.",
    h: "Forest and forest-steppe; on migration also over steppe and Gobi.",
    di: "Mostly on passage — Gobi, Khentii and Selenge forests, and western Mongolia.",
    mi: "Passage migrant, peaking in May and September.",
    fo: "Larvae and honeycomb of bees and wasps; also insects and small vertebrates.",
    br: "Breeds in Siberian forests; nests high in trees, 1–3 eggs.",
    be: "Follows bees back to their nests and digs them out.",
    v: "A high, whistling “wee-wee-wee”.",
    cu: "Migrates in large flocks along the East Asian coast, a famous sight for birders.",
    co: "Least Concern.",
    w: "Watch the sky over the Gobi and forest-steppe in May and September.",
    bt: "May, September",
    fa: ["Grooved tongue for pulling out wasp grubs.", "Head feathers protect it from stings.", "Some young birds mimic hawk-eagles."]
  },
  "egyptian-vulture": {
    T: { c: { white: .6, black: .25, yellow: .1, buff: .05 }, hb: ["mountain", "desert", "steppe"], bk: "hooked", bh: ["soar", "walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["47–70 cm", "155–180 cm", "1.6–2.4 kg"] },
    s: "A small white vulture with a yellow face and a wedge-shaped tail — one of the few birds that uses tools. A very rare vagrant to Mongolia.",
    d: "The Egyptian Vulture ranges from southern Europe and North Africa to India. It feeds on carrion and breaks ostrich and other large eggs by throwing stones at them — a rare example of tool use in birds. It has declined sharply across much of its range and is listed as Endangered. Only a handful of records exist from Mongolia.",
    f: ["Adult mostly white with black flight feathers.", "Bare yellow face; thin bill with a dark tip.", "Wedge-shaped white tail.", "Shaggy neck feathers.", "Juveniles are dark brown."],
    si: "Lammergeier — much larger, with a long wedge tail, dark upperparts and orange underparts.",
    h: "Open, dry country, cliffs and rubbish tips.",
    di: "Very rare vagrant in Mongolia.",
    mi: "Northern populations migrate south in winter.",
    fo: "Carrion, eggs, dung, small animals.",
    br: "Nests on cliff ledges; 1–2 eggs.",
    be: "Throws stones to crack eggs.",
    v: "Mostly silent.",
    cu: "Called “pharaoh’s chicken”; appears in ancient Egyptian hieroglyphs.",
    co: "Endangered — poisoning, power lines and loss of food.",
    w: "Not expected in Mongolia.",
    bt: "—",
    fa: ["Uses stones as tools.", "Endangered worldwide.", "Its face turns bright yellow in adults."]
  },
  "short-toed-eagle": {
    T: { c: { white: .45, brown: .35, gray: .1, buff: .1 }, hb: ["desert", "steppe", "mountain"], bk: "hooked", bh: ["soar", "perch"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["59–70 cm", "162–195 cm", "1.2–2.3 kg"] },
    s: "A pale, owl-headed eagle that hovers over hillsides and feeds almost entirely on snakes. Occurs in summer mainly in southern Mongolia.",
    d: "The Short-toed Snake Eagle breeds from southern Europe to Central Asia and winters in Africa and India. It hunts from a high soar or a hover, dropping onto snakes and lizards, and swallows snakes whole in flight. In Mongolia most records come from the Gobi between April and October.",
    f: ["Very pale underside with light barring.", "Brown upper breast and throat forming a “hood”.", "Large, rounded, owl-like head with bright yellow eyes.", "Three or four bars on the tail.", "Often hovers like a kestrel."],
    si: "Upland Buzzard — dark carpal patches, pale tail. Osprey — dark eye-stripe, white head, lives by water.",
    h: "Dry hills, semi-desert and rocky steppe with reptiles.",
    di: "Mainly the Gobi; occasionally further north.",
    mi: "Summer visitor, April–October; peaks in May and September.",
    fo: "Snakes and lizards, sometimes small mammals.",
    br: "Small stick nest on a tree or cliff; a single egg.",
    be: "Hovers facing the wind, then drops onto prey.",
    v: "A mewing, gull-like “weeo”.",
    cu: "Its French name, Circaète Jean-le-Blanc, means “John the White”.",
    co: "Least Concern.",
    w: "Gobi foothills in late spring.",
    bt: "May–Sep",
    fa: ["Feeds almost only on snakes.", "Swallows snakes head first.", "Lays just one egg."]
  },
  "himalayan-griffon": {
    T: { c: { buff: .45, brown: .35, white: .15, black: .05 }, hb: ["mountain", "steppe", "desert"], bk: "hooked", bh: ["soar", "walk"], vt: ["silent", "croak"], ac: "day", se: ["summer"], sz: ["103–110 cm", "256–310 cm", "6–12.5 kg"] },
    s: "A huge pale vulture of the Himalaya and Tibet; many young birds spend the summer in Mongolia’s mountains and Gobi.",
    d: "The Himalayan Griffon is the second-largest Old World vulture after the Cinereous Vulture. It breeds in the Himalaya and on the Tibetan Plateau. Satellite tracking has shown that many immature birds travel north to spend the summer in Mongolia, where they are regularly seen at carcasses in the Gobi, Khangai and Altai.",
    f: ["Pale buff body and wing coverts.", "Dark brown flight and tail feathers contrasting with the pale body.", "Long, spiky pale ruff.", "Head covered in whitish down; yellowish bill.", "Very long, broad wings with splayed fingers."],
    si: "Cinereous Vulture — all dark. Griffon Vulture — smaller, more rufous, less contrast. Lammergeier — pointed wings, long wedge tail.",
    h: "Mountains, high plateaus, steppe and Gobi near carcasses.",
    di: "Gobi Altai, Khangai, Altai and central Mongolia — in summer.",
    mi: "Non-breeding summer visitor, April–October (peak in June).",
    fo: "Carrion of livestock and wild ungulates.",
    br: "Breeds on Himalayan cliffs; one egg.",
    be: "Soars for hours and gathers at carcasses with Cinereous Vultures.",
    v: "Grunts and hisses at carcasses.",
    cu: "Important in Tibetan sky burials.",
    co: "Near Threatened — poisoning and veterinary drugs.",
    w: "Gobi Gurvan Saikhan, Ikh Nart and the Khangai in June–August.",
    bt: "Jun–Aug",
    fa: ["One of the largest birds of prey.", "Young birds summer in Mongolia.", "Can soar above 6,000 m."]
  },
  "griffon-vulture": {
    T: { c: { buff: .4, brown: .4, white: .15, black: .05 }, hb: ["mountain", "steppe"], bk: "hooked", bh: ["soar", "walk"], vt: ["silent", "croak"], ac: "day", se: ["summer"], sz: ["93–122 cm", "230–280 cm", "6.2–10.5 kg"] },
    s: "A large sandy-brown vulture with a white neck ruff. It lives in the Altai and Tian Shan and is rare in Mongolia.",
    d: "The Eurasian Griffon Vulture ranges from Spain to Central Asia, including the Altai and Tian Shan. It nests in colonies on cliffs and searches for carcasses over open country. In Mongolia it has been recorded only a few times, mainly in the Gobi in summer.",
    f: ["Buff-brown body.", "White neck ruff.", "White head with a yellow bill.", "Dark flight feathers contrasting with paler coverts.", "Broad wings and a short tail."],
    si: "Himalayan Griffon — larger and paler with stronger contrast. Cinereous Vulture — all dark.",
    h: "Mountains with cliffs, open grazing land.",
    di: "Rare in Mongolia — a few records from the Gobi.",
    mi: "Mostly resident; young birds wander.",
    fo: "Carrion of large mammals.",
    br: "Colonial on cliffs; one egg.",
    be: "Flocks gather quickly at carcasses.",
    v: "Hisses and croaks at carcasses.",
    cu: "Spain holds over 90% of Europe’s population.",
    co: "Least Concern.",
    w: "Rare — look among other vultures in the Gobi.",
    bt: "Jun–Aug",
    fa: ["Nests in colonies.", "White neck ruff.", "Can spot a carcass from kilometres away."]
  },
  "mountain-hawk-eagle": {
    T: { c: { brown: .5, white: .25, buff: .15, black: .1 }, hb: ["forest", "mountain"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["66–84 cm", "134–175 cm", "1.5–3.5 kg"] },
    s: "A large forest eagle of South and East Asia with a crest and feathered legs. Only exceptionally recorded in Mongolia.",
    d: "The Mountain Hawk-Eagle (Hodgson’s Hawk-Eagle) lives in forests from the Himalaya to Japan. It hunts birds, mammals and reptiles from a hidden perch. Its occurrence in Mongolia is exceptional.",
    f: ["Short crest on the back of the head.", "Brown upperparts, pale underparts with heavy streaking.", "Barred belly and thighs.", "Legs feathered to the toes.", "Broad, rounded wings."],
    si: "Northern Goshawk — smaller, no crest. Booted Eagle — smaller, pale wing panels.",
    h: "Mountain forest.",
    di: "Exceptional vagrant in Mongolia.",
    mi: "Mostly resident; northern birds move short distances.",
    fo: "Birds, mammals and reptiles.",
    br: "Large nest in a tall tree; 1 egg.",
    be: "Hunts from a perch within the forest.",
    v: "A shrill “tlueet-weet-weet”.",
    cu: "Also named after the naturalist Brian Hodgson.",
    co: "Near Threatened — forest loss.",
    w: "Not expected in Mongolia.",
    bt: "—",
    fa: ["A forest eagle.", "Has a crest.", "Feathered legs."]
  },
  "greater-spotted-eagle": {
    T: { c: { brown: .75, black: .15, white: .05, buff: .05 }, hb: ["water", "forest", "steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["59–71 cm", "157–179 cm", "1.7–3.2 kg"] },
    s: "A dark, compact eagle of wet forest-steppe; juveniles are covered with white spots. A scarce summer visitor to northern Mongolia.",
    d: "The Greater Spotted Eagle breeds from eastern Europe to eastern Siberia in wet forests near marshes and river floodplains, and winters in South Asia, the Middle East and Africa. It is listed as Vulnerable. In Mongolia most records come from the forest-steppe of Khentii and Selenge between April and October.",
    f: ["Uniformly dark brown adult.", "Juvenile covered with rows of white spots on the wings.", "Short tail and broad wings.", "Pale “U” above the tail.", "Nostril round."],
    si: "Steppe Eagle — larger, long gape line reaching behind the eye. Eastern Imperial Eagle — golden nape and white shoulder patches.",
    h: "Wet woodland near marshes, river valleys and floodplain meadows.",
    di: "Forest-steppe of Khentii, Selenge and the Khangai; also Dornod on passage.",
    mi: "Summer visitor, April–October.",
    fo: "Rodents, frogs, waterbirds and carrion.",
    br: "Nest in a tall tree near wetland; 1–3 eggs.",
    be: "Often sits on the ground in wet meadows.",
    v: "A barking “kyak-kyak”.",
    cu: "Its Latin name clanga means “scream”.",
    co: "Vulnerable — wetland drainage and hybridisation with the Lesser Spotted Eagle in Europe.",
    w: "River valleys of Khentii (Onon, Khurkh) in summer.",
    bt: "May–Aug",
    fa: ["Juveniles are covered in white spots.", "Vulnerable worldwide.", "Tied to wetlands."]
  },
  "bonellis-eagle": {
    T: { c: { brown: .4, white: .35, black: .15, buff: .1 }, hb: ["mountain"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["55–67 cm", "143–180 cm", "1.5–2.5 kg"] },
    s: "A powerful eagle of Mediterranean and South Asian mountains with a white body and a dark tail band. An exceptional vagrant in Mongolia.",
    d: "Bonelli’s Eagle ranges from southern Europe and North Africa to India and southern China. It lives in rocky hills and hunts rabbits, gamebirds and pigeons. Its occurrence in Mongolia is exceptional.",
    f: ["Pale underparts with fine dark streaks.", "Dark brown upperparts with a pale patch on the back.", "Long grey tail with a broad dark terminal band.", "Dark band along the underwing.", "Long legs."],
    si: "Booted Eagle — smaller, with white “landing lights”. Short-toed Snake Eagle — larger head, no dark tail band.",
    h: "Rocky hills and mountains.",
    di: "Exceptional vagrant in Mongolia.",
    mi: "Mostly resident.",
    fo: "Rabbits, gamebirds, pigeons.",
    br: "Nests on cliffs; 1–3 eggs.",
    be: "Pairs often hunt together.",
    v: "Mostly silent.",
    cu: "Named after the Italian ornithologist Franco Andrea Bonelli.",
    co: "Least Concern, but declining in Europe.",
    w: "Not expected in Mongolia.",
    bt: "—",
    fa: ["Pairs hunt as a team.", "Named after an Italian naturalist.", "Declining in Europe."]
  }
});
