B2T("fr", {
  "european-honey-buzzard": {
    s: "Rapace élancé des bois d’Europe et d’Asie occidentale, qui se nourrit de larves de guêpes et d’abeilles. Erratique très rare en Mongolie.",
    d: "La Bondrée apivore niche en Europe et en Asie occidentale et hiverne en Afrique tropicale. Malgré son nom anglais (« buse »), elle est plus proche des milans que des vraies buses. Elle déterre les nids de guêpes et d’abeilles pour en manger les larves ; des plumes faciales denses, comme des écailles, la protègent des piqûres. En Mongolie, elle n’a été observée que très rarement ; c’est sa cousine orientale, la Bondrée orientale, que l’on voit normalement ici.",
    f: ["Petite tête de pigeon au bout d’un cou assez long.", "Longue queue avec deux fines barres sombres à la base et une large bande sombre près de l’extrémité.", "Le mâle a la tête gris bleu, la femelle la tête brune.", "Plumage très variable, du pâle au brun foncé.", "Plane sur des ailes plates aux extrémités légèrement abaissées."],
    si: "Bondrée orientale — plus grande, courte huppe, six « doigts » aux ailes. Buse variable — plus massive, queue plus courte, tête plus large.",
    h: "Forêts feuillues et mixtes avec clairières.",
    di: "Erratique rare ; très peu de mentions en Mongolie.",
    mi: "Grande migratrice entre l’Europe/l’Asie occidentale et l’Afrique.",
    fo: "Larves et nymphes de guêpes et d’abeilles ; aussi insectes, grenouilles et petits oiseaux.",
    br: "Niche haut dans les arbres ; 1 à 3 œufs.",
    be: "Marche au sol pour déterrer les nids de guêpes avec ses pattes.",
    v: "Un « piii-lou » plaintif et sifflé.",
    cu: "Son nom latin apivorus signifie « mangeur d’abeilles ».",
    co: "Préoccupation mineure ; tirée en migration dans certains pays.",
    w: "Pas régulière en Mongolie — examinez bien les bondrées en migration.",
    bt: "mai, septembre",
    fa: ["Mange des larves de guêpes.", "Face couverte de plumes raides comme des écailles.", "Hiverne en Afrique."]
  },
  "east-asian-honey-buzzard": {
    s: "Grande bondrée au plumage variable et à petite huppe, qui pille les nids d’abeilles et de guêpes. Traverse la Mongolie au printemps et à l’automne.",
    d: "La Bondrée orientale niche en Sibérie et au Japon et hiverne en Asie du Sud-Est et en Inde. Sa tête longue et étroite, sa langue creusée d’un sillon et ses plumes faciales denses sont des adaptations pour fouiller les nids d’abeilles et de guêpes. En Mongolie, la plupart des observations ont lieu en mai et en septembre, lors de la migration.",
    f: ["Petite tête avec une courte huppe à l’arrière.", "Six longs « doigts » à l’extrémité de l’aile.", "Queue barrée de larges bandes sombres régulièrement espacées.", "Plumage du pâle au très sombre ; gorge souvent pâle avec un trait sombre.", "Plane sur des ailes plates."],
    si: "Bondrée apivore — plus petite, sans huppe ; rare ici. Buse variable — queue plus courte, ailes plus arrondies, tête plus large.",
    h: "Forêt et steppe boisée ; en migration, aussi au-dessus de la steppe et du Gobi.",
    di: "Surtout de passage — Gobi, forêts du Khentii et de la Selenge, ouest de la Mongolie.",
    mi: "Migratrice de passage, avec des pics en mai et en septembre.",
    fo: "Larves et rayons d’abeilles et de guêpes ; aussi insectes et petits vertébrés.",
    br: "Niche dans les forêts sibériennes, haut dans les arbres ; 1 à 3 œufs.",
    be: "Suit les abeilles jusqu’à leur nid et le déterre.",
    v: "Un « oui-oui-oui » aigu et sifflé.",
    cu: "Migre en grandes bandes le long de la côte d’Asie orientale, un spectacle célèbre chez les ornithologues.",
    co: "Préoccupation mineure.",
    w: "Surveillez le ciel au-dessus du Gobi et de la steppe boisée en mai et septembre.",
    bt: "mai, septembre",
    fa: ["Langue à sillon pour extraire les larves de guêpes.", "Plumes de la tête protectrices contre les piqûres.", "Certains jeunes imitent les aigles huppés."]
  },
  "egyptian-vulture": {
    s: "Petit vautour blanc à face jaune et queue cunéiforme — l’un des rares oiseaux à utiliser des outils. Erratique très rare en Mongolie.",
    d: "Le Vautour percnoptère est présent de l’Europe du Sud et l’Afrique du Nord jusqu’en Inde. Il se nourrit de charognes et brise les œufs d’autruches et d’autres grands oiseaux en leur lançant des pierres — un rare exemple d’utilisation d’outils chez les oiseaux. En fort déclin dans une grande partie de son aire, il est classé « En danger ». On ne compte que quelques mentions en Mongolie.",
    f: ["Adulte surtout blanc, rémiges noires.", "Face nue jaune ; bec fin à pointe sombre.", "Queue blanche cunéiforme.", "Plumes du cou ébouriffées.", "Juvéniles brun foncé."],
    si: "Gypaète barbu — bien plus grand, longue queue cunéiforme, dessus sombre et dessous orangé.",
    h: "Terrains ouverts et secs, falaises, décharges.",
    di: "Erratique très rare en Mongolie.",
    mi: "Les populations nordiques migrent vers le sud en hiver.",
    fo: "Charognes, œufs, excréments, petits animaux.",
    br: "Niche sur des corniches ; 1 ou 2 œufs.",
    be: "Lance des pierres pour casser les œufs.",
    v: "Généralement silencieux.",
    cu: "Surnommé « poule des pharaons » ; figure dans les hiéroglyphes égyptiens.",
    co: "En danger — empoisonnement, lignes électriques et raréfaction de la nourriture.",
    w: "Non attendu en Mongolie.",
    bt: "—",
    fa: ["Utilise des pierres comme outils.", "Menacé à l’échelle mondiale.", "Sa face devient jaune vif chez l’adulte."]
  },
  "short-toed-eagle": {
    s: "Aigle pâle à tête de hibou, qui fait du surplace au-dessus des versants et se nourrit presque exclusivement de serpents. Présent l’été surtout dans le sud de la Mongolie.",
    d: "Le Circaète Jean-le-Blanc niche de l’Europe du Sud à l’Asie centrale et hiverne en Afrique et en Inde. Il chasse en vol plané ou en surplace, puis fond sur les serpents et les lézards ; il avale les serpents entiers en vol. En Mongolie, la plupart des observations proviennent du Gobi, d’avril à octobre.",
    f: ["Dessous très pâle, finement barré.", "Haut de la poitrine et gorge bruns, formant un « capuchon ».", "Grosse tête ronde de hibou, yeux jaune vif.", "Trois ou quatre barres sur la queue.", "Fait souvent du surplace comme une crécerelle."],
    si: "Buse de Chine — taches carpales sombres, queue pâle. Balbuzard pêcheur — bandeau sombre sur l’œil, tête blanche, près de l’eau.",
    h: "Collines sèches, semi-désert et steppe rocheuse riches en reptiles.",
    di: "Surtout le Gobi ; occasionnellement plus au nord.",
    mi: "Visiteur d’été, d’avril à octobre ; pics en mai et septembre.",
    fo: "Serpents et lézards, parfois petits mammifères.",
    br: "Petit nid de branches dans un arbre ou sur une falaise ; un seul œuf.",
    be: "Fait du surplace face au vent, puis fond sur sa proie.",
    v: "Un « ouiio » miaulé, rappelant une mouette.",
    cu: "Son nom français signifie « Jean le Blanc ».",
    co: "Préoccupation mineure.",
    w: "Piémonts du Gobi à la fin du printemps.",
    bt: "mai–sept.",
    fa: ["Se nourrit presque uniquement de serpents.", "Avale les serpents la tête la première.", "Ne pond qu’un seul œuf."]
  },
  "himalayan-griffon": {
    s: "Immense vautour pâle de l’Himalaya et du Tibet ; de nombreux jeunes passent l’été dans les montagnes et le Gobi de Mongolie.",
    d: "Le Vautour de l’Himalaya est le deuxième plus grand vautour de l’Ancien Monde après le Vautour moine. Il niche dans l’Himalaya et sur le plateau tibétain. Le suivi par satellite a montré que de nombreux immatures remontent passer l’été en Mongolie, où on les voit régulièrement sur les carcasses dans le Gobi, le Khangaï et l’Altaï.",
    f: ["Corps et couvertures alaires chamois pâle.", "Rémiges et rectrices brun foncé contrastant avec le corps pâle.", "Longue collerette pâle hérissée.", "Tête couverte de duvet blanchâtre ; bec jaunâtre.", "Ailes très longues et larges, extrémités digitées."],
    si: "Vautour moine — entièrement sombre. Vautour fauve — plus petit, plus roux, moins contrasté. Gypaète barbu — ailes pointues, longue queue cunéiforme.",
    h: "Montagnes, hauts plateaux, steppe et Gobi près des carcasses.",
    di: "Altaï du Gobi, Khangaï, Altaï et Mongolie centrale — en été.",
    mi: "Visiteur d’été non nicheur, d’avril à octobre (pic en juin).",
    fo: "Carcasses de bétail et d’ongulés sauvages.",
    br: "Niche sur les falaises himalayennes ; un œuf.",
    be: "Plane pendant des heures et se rassemble sur les carcasses avec les Vautours moines.",
    v: "Grognements et sifflements sur les carcasses.",
    cu: "Joue un rôle important dans les funérailles célestes tibétaines.",
    co: "Quasi menacé — empoisonnement et médicaments vétérinaires.",
    w: "Gobi Gurvan Saikhan, Ikh Nart et Khangaï de juin à août.",
    bt: "juin–août",
    fa: ["L’un des plus grands rapaces du monde.", "Les jeunes passent l’été en Mongolie.", "Peut planer au-dessus de 6 000 m."]
  },
  "griffon-vulture": {
    s: "Grand vautour brun sable à collerette blanche. Il vit dans l’Altaï et le Tian Shan et reste rare en Mongolie.",
    d: "Le Vautour fauve est présent de l’Espagne à l’Asie centrale, notamment dans l’Altaï et le Tian Shan. Il niche en colonies sur les falaises et prospecte les milieux ouverts à la recherche de carcasses. En Mongolie, il n’a été noté que quelques fois, surtout dans le Gobi en été.",
    f: ["Corps brun chamois.", "Collerette blanche.", "Tête blanche, bec jaune.", "Rémiges sombres contrastant avec des couvertures plus pâles.", "Ailes larges, queue courte."],
    si: "Vautour de l’Himalaya — plus grand, plus pâle et plus contrasté. Vautour moine — entièrement sombre.",
    h: "Montagnes à falaises, pâturages ouverts.",
    di: "Rare en Mongolie — quelques mentions dans le Gobi.",
    mi: "Surtout sédentaire ; les jeunes erratiques.",
    fo: "Carcasses de grands mammifères.",
    br: "Colonial sur les falaises ; un œuf.",
    be: "Les groupes se rassemblent vite sur les carcasses.",
    v: "Sifflements et croassements sur les carcasses.",
    cu: "L’Espagne abrite plus de 90 % de la population européenne.",
    co: "Préoccupation mineure.",
    w: "Rare — cherchez-le parmi les autres vautours du Gobi.",
    bt: "juin–août",
    fa: ["Niche en colonies.", "Collerette blanche.", "Repère une carcasse à plusieurs kilomètres."]
  },
  "mountain-hawk-eagle": {
    s: "Grand aigle forestier d’Asie du Sud et de l’Est, huppé et aux pattes emplumées. Signalé seulement exceptionnellement en Mongolie.",
    d: "L’Aigle montagnard (ou aigle huppé de Hodgson) vit dans les forêts, de l’Himalaya au Japon. Il chasse oiseaux, mammifères et reptiles depuis un perchoir caché. Sa présence en Mongolie est exceptionnelle.",
    f: ["Courte huppe à l’arrière de la tête.", "Dessus brun, dessous pâle fortement strié.", "Ventre et cuisses barrés.", "Pattes emplumées jusqu’aux doigts.", "Ailes larges et arrondies."],
    si: "Autour des palombes — plus petit, sans huppe. Aigle botté — plus petit, plages pâles aux ailes.",
    h: "Forêts de montagne.",
    di: "Erratique exceptionnel en Mongolie.",
    mi: "Surtout sédentaire ; les oiseaux du nord se déplacent peu.",
    fo: "Oiseaux, mammifères et reptiles.",
    br: "Grand nid dans un grand arbre ; 1 œuf.",
    be: "Chasse depuis un perchoir en forêt.",
    v: "Un « tluiit-ouit-ouit » perçant.",
    cu: "Porte aussi le nom du naturaliste Brian Hodgson.",
    co: "Quasi menacé — déforestation.",
    w: "Non attendu en Mongolie.",
    bt: "—",
    fa: ["Un aigle forestier.", "Porte une huppe.", "Pattes emplumées."]
  },
  "greater-spotted-eagle": {
    s: "Aigle sombre et trapu des steppes boisées humides ; les juvéniles sont couverts de taches blanches. Visiteur d’été peu commun dans le nord de la Mongolie.",
    d: "L’Aigle criard niche de l’Europe de l’Est à la Sibérie orientale, dans les forêts humides proches des marais et des plaines inondables, et hiverne en Asie du Sud, au Moyen-Orient et en Afrique. Il est classé « Vulnérable ». En Mongolie, la plupart des observations proviennent de la steppe boisée du Khentii et de la Selenge, d’avril à octobre.",
    f: ["Adulte brun foncé uniforme.", "Juvénile couvert de rangées de taches blanches sur les ailes.", "Queue courte et ailes larges.", "« U » pâle au-dessus de la queue.", "Narine ronde."],
    si: "Aigle des steppes — plus grand, commissure du bec prolongée derrière l’œil. Aigle impérial — nuque dorée et taches blanches aux épaules.",
    h: "Bois humides près des marais, vallées fluviales et prairies inondables.",
    di: "Steppe boisée du Khentii, de la Selenge et du Khangaï ; aussi Dornod en passage.",
    mi: "Visiteur d’été, d’avril à octobre.",
    fo: "Rongeurs, grenouilles, oiseaux d’eau et charognes.",
    br: "Nid dans un grand arbre près d’une zone humide ; 1 à 3 œufs.",
    be: "Se pose souvent au sol dans les prairies humides.",
    v: "Un « kyak-kyak » aboyé.",
    cu: "Son nom latin clanga signifie « cri ».",
    co: "Vulnérable — drainage des zones humides et hybridation avec l’Aigle pomarin en Europe.",
    w: "Vallées du Khentii (Onon, Khurkh) en été.",
    bt: "mai–août",
    fa: ["Les juvéniles sont couverts de taches blanches.", "Vulnérable à l’échelle mondiale.", "Lié aux zones humides."]
  },
  "bonellis-eagle": {
    s: "Aigle puissant des montagnes méditerranéennes et d’Asie du Sud, au corps blanc et à la queue barrée de sombre. Erratique exceptionnel en Mongolie.",
    d: "L’Aigle de Bonelli est présent de l’Europe du Sud et de l’Afrique du Nord jusqu’en Inde et au sud de la Chine. Il vit dans les collines rocheuses et chasse lapins, gallinacés et pigeons. Sa présence en Mongolie est exceptionnelle.",
    f: ["Dessous pâle finement strié de sombre.", "Dessus brun foncé avec une tache pâle sur le dos.", "Longue queue grise à large bande terminale sombre.", "Bande sombre le long du dessous de l’aile.", "Longues pattes."],
    si: "Aigle botté — plus petit, avec des « phares » blancs aux épaules. Circaète Jean-le-Blanc — tête plus grosse, sans bande sombre à la queue.",
    h: "Collines rocheuses et montagnes.",
    di: "Erratique exceptionnel en Mongolie.",
    mi: "Surtout sédentaire.",
    fo: "Lapins, gallinacés, pigeons.",
    br: "Niche sur les falaises ; 1 à 3 œufs.",
    be: "Les couples chassent souvent ensemble.",
    v: "Généralement silencieux.",
    cu: "Porte le nom de l’ornithologue italien Franco Andrea Bonelli.",
    co: "Préoccupation mineure, mais en déclin en Europe.",
    w: "Non attendu en Mongolie.",
    bt: "—",
    fa: ["Les couples chassent en équipe.", "Porte le nom d’un naturaliste italien.", "En déclin en Europe."]
  }
});
