B2T("en", {
  "booted-eagle": {
    T: { c: { brown: 0.45, white: 0.3, buff: 0.15, black: 0.1 }, hb: ["forest", "mountain"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer", "passage"], sz: ["42–51 cm", "110–132 cm", "510–1,250 g"] },
    s: "A small, buzzard-sized eagle with feathered legs and white ‘landing lights’ at the base of the wings. A summer visitor to wooded mountains across Mongolia.",
    d: "The Booted Eagle breeds from Iberia and North Africa across Central Asia to Mongolia and winters in tropical Africa and India. It comes in a pale morph (white underbody, black flight feathers) and a dark morph (all brown). It hunts birds, lizards and small mammals in fast stoops from a soar. In Mongolia it is widespread from April to October in the Khentii, Altai and Khangai forests and along wooded Gobi mountains; birds often hunt around Ulaanbaatar and Terelj.",
    f: ["Size of a buzzard but with narrower, parallel-edged wings and a longer square tail.", "Two small white spots where the wings join the body (‘landing lights’) — visible head-on.", "Pale morph: white body and underwing coverts contrasting with black flight feathers.", "Dark morph: brown underneath with a paler tail.", "Pale panel on the upperwing coverts and pale ‘U’ on the rump."],
    si: "Black Kite — forked tail, no white spots. Eurasian Buzzard and Upland Buzzard — broader wings, dark carpal patches. Short-toed Eagle — larger, owl-headed, no contrasting black flight feathers.",
    h: "Mixed forest and forest edges in hills and mountains, often near open ground.",
    di: "Widespread in summer: Khentii–Selenge forest-steppe (Terelj, Ulaanbaatar), Khar Us Nuur and the Altai, Khangai, and wooded Gobi mountains.",
    mi: "Summer visitor from late April to early October; passage peaks in May and September.",
    fo: "Small and medium birds, lizards, ground squirrels and other small mammals.",
    br: "Builds a stick nest in a large tree or on a cliff; lays 1–2 eggs. Pairs return to the same nest each year.",
    be: "Soars high, then stoops steeply on prey with folded wings; often seen in pairs displaying.",
    v: "A shrill, whistling ‘kli-kli-kli’, especially near the nest.",
    cu: "Its name comes from the feathered ‘boots’ on its legs, a feature shared with true eagles.",
    co: "Least Concern.",
    w: "Terelj and the forested hills around Ulaanbaatar, Khar Us Nuur and Altai valleys, May–September.",
    bt: "May–September",
    fa: ["One of the smallest true eagles.", "Has two colour morphs.", "Its legs are feathered to the toes."]
  },
  "western-marsh-harrier": {
    T: { c: { brown: 0.5, buff: 0.2, gray: 0.15, rufous: 0.15 }, hb: ["water"], bk: "hooked", bh: ["soar"], vt: ["silent"], ac: "day", se: ["summer", "passage"], sz: ["43–55 cm", "115–130 cm", "400–800 g"] },
    s: "A large, broad-winged harrier that quarters low over reedbeds. In Mongolia it breeds mainly in the reed-fringed lakes of the west.",
    d: "The Western Marsh Harrier breeds across Europe and western Asia; Mongolia lies at the eastern edge of its range, where it meets and sometimes hybridises with the Eastern Marsh Harrier. It glides low over reeds with wings held in a shallow V, dropping onto prey. Most Mongolian records come from Khar Us Nuur and the Great Lakes Depression, with smaller numbers in the Khangai and Gobi lakes.",
    f: ["Male: brown body, pale head, grey tail and grey panels on the wings with black tips.", "Female: dark chocolate brown with a creamy crown and throat.", "Flies low with wings raised in a V.", "Broader wings than other harriers.", "No white rump (unlike most harriers)."],
    si: "Eastern Marsh Harrier — male black-and-grey with white underparts; female streakier, often with a white rump. Black Kite — forked tail, soars higher.",
    h: "Reedbeds and marshes around lakes and slow rivers.",
    di: "Mainly western Mongolia (Khar Us Nuur, Great Lakes Depression); also Böön Tsagaan, Orog Nuur and occasionally Khentii.",
    mi: "Summer visitor April–October.",
    fo: "Frogs, small mammals, ducklings and other young waterbirds, eggs.",
    br: "Nests on a platform of reeds in dense reedbeds; 3–6 eggs.",
    be: "The male passes food to the female in the air during breeding — a ‘food pass’.",
    v: "Mostly silent; a thin ‘kee-a’ near the nest.",
    cu: "Its scientific name aeruginosus means ‘rusty’.",
    co: "Least Concern; depends on reedbeds that are threatened by drainage and fire.",
    w: "Scan the reedbeds of Khar Us Nuur in summer.",
    bt: "May–September",
    fa: ["Meets and hybridises with the Eastern Marsh Harrier in Mongolia.", "Performs aerial food passes.", "Largest harrier in Europe."]
  },
  "eastern-marsh-harrier": {
    T: { c: { black: 0.3, white: 0.25, gray: 0.2, brown: 0.25 }, hb: ["water", "steppe"], bk: "hooked", bh: ["soar"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["48–58 cm", "113–137 cm", "400–800 g"] },
    s: "The marsh harrier of eastern Asia — males are strikingly black, grey and white. A common summer visitor to wetlands in northern and eastern Mongolia.",
    d: "The Eastern Marsh Harrier breeds in north-east China, eastern Mongolia and south-east Siberia and winters in southern China and South-East Asia. It was long treated as a subspecies of the Western Marsh Harrier. In Mongolia it is common from April to October in river valleys and lakes such as the Khurkh–Khuiten valley, Ögii Nuur and Buir Nuur.",
    f: ["Male: black head, breast and back streaked white; grey wings with black tips; white underparts.", "Female: dark brown, streaked buff on head and breast, often with a white rump.", "Juvenile: dark brown with a pale head.", "Glides low with wings in a shallow V."],
    si: "Western Marsh Harrier — male brown and grey, female chocolate with a creamy head. Pied Harrier — male cleaner black-and-white, smaller and slimmer. Hen Harrier — smaller, with a big white rump.",
    h: "Marshes, reedy lakes, wet meadows and river valleys.",
    di: "Khentii and Selenge (Khurkh, Onon), Dornod (Buir Nuur, Mongol Daguur), Khangai lakes (Ögii Nuur) and Valley of the Lakes.",
    mi: "Summer visitor, late March to October; peak numbers May–June.",
    fo: "Frogs, voles, young waterbirds and fish.",
    br: "Nests on a reed platform in wetlands; 3–7 eggs.",
    be: "Hunts by quartering low over reeds and grass; roosts communally in winter.",
    v: "Usually silent; a mewing call at roosts.",
    cu: "Hybridises with the Western Marsh Harrier around Lake Baikal and in Mongolia.",
    co: "Least Concern.",
    w: "Khurkh–Khuiten valley, Ögii Nuur and Buir Nuur, May–August.",
    bt: "May–August",
    fa: ["Common in Mongolia’s eastern wetlands.", "Once lumped with the Western Marsh Harrier.", "Male and female look completely different."]
  },
  "hen-harrier": {
    T: { c: { gray: 0.35, white: 0.25, brown: 0.25, black: 0.15 }, hb: ["steppe", "water"], bk: "hooked", bh: ["soar"], vt: ["screech"], ac: "day", se: ["passage", "summer"], sz: ["44–52 cm", "97–122 cm", "300–700 g"] },
    s: "A slim, long-tailed harrier with a bold white rump; males are pale grey with black wingtips. A passage migrant across Mongolia, most numerous in September.",
    d: "The Hen Harrier breeds across northern Eurasia in open moors, marshes and grassland, and winters to the south. It breeds in small numbers in northern Mongolia but is most often seen on migration, especially in September, hunting low over the steppe.",
    f: ["Male: pale blue-grey with a white belly and black wingtips.", "Female and juvenile: brown, streaked below, with a large white rump (a ‘ringtail’).", "Owl-like facial disc.", "Long wings and tail; glides low with wings in a V."],
    si: "Pallid Harrier — male paler with narrow black wedge at the wingtip; female with a stronger face pattern. Pied Harrier — male black and white. Montagu’s Harrier — male with black wing bar and rufous streaks.",
    h: "Steppe, marshes, meadows and farmland.",
    di: "Throughout Mongolia on passage; Khurkh, Khar Us Nuur, Ögii Nuur, Buir Nuur and the eastern steppes.",
    mi: "Mostly a passage migrant (April–May, September–October); a few breed and a few winter.",
    fo: "Voles, small birds and insects.",
    br: "Nests on the ground in tall vegetation; 4–6 eggs.",
    be: "Hunts by gliding low and dropping on prey, using hearing as well as sight.",
    v: "A chattering ‘chek-ek-ek’ near the nest.",
    cu: "Named for its old habit of taking free-range chickens.",
    co: "Least Concern, but persecuted in parts of Europe.",
    w: "September on the steppes of Khentii and Dornod.",
    bt: "September",
    fa: ["Females are called ‘ringtails’.", "Has an owl-like face for hunting by ear.", "Males are much paler than females."]
  },
  "pallid-harrier": {
    T: { c: { gray: 0.35, white: 0.35, brown: 0.2, black: 0.1 }, hb: ["steppe"], bk: "hooked", bh: ["soar"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["40–48 cm", "95–120 cm", "315–445 g"] },
    s: "A slender steppe harrier; the male is ghostly pale with a narrow black wedge at the wingtip. A scarce passage migrant in Mongolia.",
    d: "The Pallid Harrier breeds on the steppes of southern Russia and Kazakhstan and winters in India and Africa. Mongolia lies east of its main range, and there are only a few records a year, mostly on autumn passage in the west and north.",
    f: ["Male: very pale grey, almost white below, with a narrow black wedge on the outer wing.", "Female: brown with a white rump and a strong pale collar and dark cheek.", "Slim, with narrow pointed wings.", "Buoyant, tern-like flight."],
    si: "Hen Harrier — male darker grey with broad black wingtips; female lacks the neck collar. Montagu’s Harrier — male with black bars on the wing.",
    h: "Open steppe and grassland.",
    di: "Scarce; records from Khar Us Nuur, Khurkh and Ulaanbaatar areas.",
    mi: "Passage migrant, May and August–October.",
    fo: "Voles, larks and other small birds, lizards and insects.",
    br: "Nests on the ground in steppe (not in Mongolia).",
    be: "Hunts low over grassland.",
    v: "Usually silent.",
    cu: "Its name macrourus means ‘long-tailed’.",
    co: "Near Threatened — loss of steppe to farming.",
    w: "Check harriers carefully in autumn in the west.",
    bt: "September",
    fa: ["Near Threatened worldwide.", "Recently started breeding in western Europe.", "Male looks almost white in flight."]
  },
  "pied-harrier": {
    T: { c: { black: 0.4, white: 0.4, gray: 0.1, brown: 0.1 }, hb: ["water", "steppe"], bk: "hooked", bh: ["soar"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["41–49 cm", "110–125 cm", "265–455 g"] },
    s: "An elegant Asian harrier; the male is boldly black and white. A local summer visitor to wet meadows in north-eastern Mongolia.",
    d: "The Pied Harrier breeds from south-east Siberia and north-east Mongolia to north-east China and Korea, and winters in South-East Asia. In Mongolia it nests in wet river meadows of Khentii and Dornod, with the Khurkh–Khuiten valley and Buir Nuur as the best-known sites.",
    f: ["Male: black head, breast and back; white underparts; grey wings with a black bar and black tips.", "Female: brown above, pale below with streaks, small white rump.", "Yellow eyes in the male.", "Slim harrier shape."],
    si: "Eastern Marsh Harrier — male streaky black, bigger and broader-winged. Hen Harrier — male grey, not black.",
    h: "Wet meadows, marsh edges and grassy river valleys.",
    di: "North-eastern Mongolia: Khentii (Khurkh, Onon), Dornod (Buir Nuur, Mongol Daguur).",
    mi: "Summer visitor, May–September.",
    fo: "Frogs, voles, small birds and large insects.",
    br: "Nests on the ground among grass or reeds; 4–5 eggs.",
    be: "Perches on posts or the ground; hunts low.",
    v: "Mostly silent.",
    cu: "One of the most striking harriers in the world.",
    co: "Least Concern.",
    w: "Khurkh–Khuiten valley in June–August.",
    bt: "June–August",
    fa: ["The male is black and white.", "Breeds only in eastern Asia.", "Rarely perches in trees."]
  },
  "montagus-harrier": {
    T: { c: { gray: 0.35, brown: 0.3, white: 0.15, black: 0.1, rufous: 0.1 }, hb: ["steppe"], bk: "hooked", bh: ["soar"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["43–47 cm", "97–115 cm", "225–445 g"] },
    s: "A graceful, narrow-winged harrier of Europe and western Asia. Only a handful of records in western Mongolia.",
    d: "Montagu’s Harrier breeds from Europe to western Siberia and Kazakhstan and winters in Africa and India. It is very rare in Mongolia, with only a few records, mostly in the west in late summer and autumn.",
    f: ["Male: grey with black wingtips, a black bar across the upperwing and rufous streaks on the flanks.", "Female: brown with a white rump, similar to other ringtails.", "Very narrow, pointed wings.", "Light, tern-like flight."],
    si: "Pallid and Hen Harriers — males lack the black wing bars; females are hard to separate.",
    h: "Open grassland and farmland.",
    di: "Very rare; western Mongolia and Khövsgöl.",
    mi: "Vagrant or scarce migrant.",
    fo: "Voles, small birds, lizards and insects.",
    br: "Nests on the ground in crops or grass (not in Mongolia).",
    be: "Glides very low over fields.",
    v: "Usually silent.",
    cu: "Named after the English naturalist George Montagu.",
    co: "Least Concern.",
    w: "Not expected — check harriers in the west.",
    bt: "—",
    fa: ["Named after George Montagu.", "Often nests in cereal crops in Europe.", "Very rare in Mongolia."]
  },
  "shikra": {
    T: { c: { gray: 0.4, white: 0.3, rufous: 0.2, black: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["26–30 cm", "50–60 cm", "100–220 g"] },
    s: "A small pale hawk of tropical Asia and Africa. Listed for Mongolia, but with no documented records in GBIF — an exceptional vagrant.",
    d: "The Shikra is a common hawk of India, South-East Asia and Africa, living in open woodland, gardens and villages. It is included in the Mongolian checklist on very few records; birdwatchers should document any claim carefully.",
    f: ["Pale grey upperparts; fine rufous barring below.", "Dark vertical stripe on the white throat.", "Red eye in the adult.", "Short rounded wings, fairly long tail."],
    si: "Eurasian Sparrowhawk — larger, darker above, no throat stripe. Japanese Sparrowhawk — smaller, darker, dark eye.",
    h: "Open woodland, groves and villages.",
    di: "Exceptional vagrant.",
    mi: "Mostly sedentary; northern birds move short distances.",
    fo: "Lizards, small birds, rodents and insects.",
    br: "Nests in trees; 2–4 eggs (not in Mongolia).",
    be: "Hunts from a hidden perch with a quick dash.",
    v: "A sharp ‘ti-tui’, much imitated by drongos.",
    cu: "Its name comes from Hindi-Urdu ‘shikra’, a word for a hunting hawk.",
    co: "Least Concern.",
    w: "Not expected in Mongolia.",
    bt: "—",
    fa: ["Drongos imitate its call.", "Recently moved to the genus Tachyspiza.", "Very common in India."]
  },
  "japanese-sparrowhawk": {
    T: { c: { gray: 0.4, white: 0.3, rufous: 0.2, black: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["23–30 cm", "46–58 cm", "90–190 g"] },
    s: "A tiny East Asian hawk with a thin dark throat stripe. A rare migrant in eastern and northern Mongolia.",
    d: "The Japanese Sparrowhawk breeds in Russia’s Far East, Korea, Japan and north-east China and winters in South-East Asia. It migrates in large flocks along the East Asian coast. In Mongolia it is rare, with only a few records in the east and the Khangai, mostly in May.",
    f: ["Very small hawk with rounded wings and a short tail.", "Male: dark grey above, rufous flanks, red eye.", "Female: brown barring below and yellow eye.", "Thin dark stripe down the white throat."],
    si: "Eurasian Sparrowhawk — larger, longer-tailed, no throat stripe. Shikra — paler above.",
    h: "Forests and forest edges; on migration also parks.",
    di: "Rare; eastern Mongolia and the Khangai.",
    mi: "Passage migrant, May and September.",
    fo: "Small birds, insects and lizards.",
    br: "Nests in trees; 2–5 eggs (not confirmed in Mongolia).",
    be: "Flies with quick flaps and glides; migrates in flocks.",
    v: "A chattering ‘kiki-kik-kik’.",
    cu: "Endangered in Japan but common elsewhere.",
    co: "Least Concern.",
    w: "Look for small hawks in May in eastern Mongolia.",
    bt: "May",
    fa: ["One of the smallest hawks in Asia.", "Migrates in flocks.", "Has a throat stripe."]
  },
  "eurasian-sparrowhawk": {
    T: { c: { gray: 0.35, rufous: 0.2, white: 0.2, brown: 0.25 }, hb: ["forest", "settlement", "steppe"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["summer", "passage"], sz: ["28–40 cm", "56–78 cm", "110–340 g"] },
    s: "A dashing small hawk that ambushes songbirds; the male is blue-grey above with orange barring below. Common across Mongolia on migration and breeds in northern forests.",
    d: "The Eurasian Sparrowhawk is found throughout the temperate Old World. It is a specialist bird-hunter that surprises its prey with fast, low flights along hedges and forest edges; it often hunts in towns. The female is up to a quarter larger than the male. In Mongolia it breeds in the Khentii, Khangai and Altai forests and is widespread on passage, including in Gobi oases such as Yolyn Am, peaking in April–May and September.",
    f: ["Male: blue-grey above, orange-barred below, orange cheeks.", "Female: brown-grey above, grey-brown barring below, white eyebrow.", "Yellow eye; long thin yellow legs.", "Short rounded wings and a long square tail.", "Flap-flap-glide flight."],
    si: "Northern Goshawk — much larger, heavier, with a bulging chest and white undertail. Japanese Sparrowhawk — smaller, with a throat stripe. Common Kestrel — pointed wings, hovers.",
    h: "Forests, forest edges, parks and settlements; any habitat on migration.",
    di: "Throughout Mongolia: Ulaanbaatar and Terelj, Khurkh, Khar Us Nuur, Yolyn Am and the eastern steppes.",
    mi: "Breeds in the north (April–October); passage peaks in May and September; a few winter.",
    fo: "Small birds such as sparrows, tits, finches and thrushes.",
    br: "Builds a twig nest in a tree; 4–5 bluish eggs; chicks hatch after 33 days.",
    be: "Ambushes birds with sudden dashes; soars in display in spring.",
    v: "A rapid ‘kek-kek-kek’ at the nest.",
    cu: "Traditionally used in falconry for hunting quail.",
    co: "Least Concern; recovered in Europe after pesticide bans.",
    w: "Ulaanbaatar parks, Terelj and Gobi oases on migration.",
    bt: "April–May, September",
    fa: ["The female is much larger than the male.", "Hunts birds in towns.", "Recovered after DDT was banned."]
  }
});
