B2T("fr", {
  "booted-eagle": {
    s: "Petit aigle de la taille d’une buse, aux pattes emplumées et aux « phares » blancs à la base des ailes. Visiteur d’été des montagnes boisées de toute la Mongolie.",
    d: "L’Aigle botté niche de la péninsule Ibérique et de l’Afrique du Nord jusqu’en Mongolie à travers l’Asie centrale, et hiverne en Afrique tropicale et en Inde. Il existe une forme claire (corps blanc, rémiges noires) et une forme sombre (entièrement brune). Il capture oiseaux, lézards et petits mammifères en piqué rapide depuis le vol plané. En Mongolie, il est répandu d’avril à octobre dans les forêts du Khentii, de l’Altaï et du Khangaï et dans les montagnes boisées du Gobi ; il chasse souvent autour d’Oulan-Bator et de Terelj.",
    f: ["Taille d’une buse mais ailes plus étroites, aux bords parallèles, et queue plus longue et carrée.", "Deux petites taches blanches à la jonction des ailes et du corps (« phares »), visibles de face.", "Forme claire : corps et couvertures sous-alaires blancs contrastant avec des rémiges noires.", "Forme sombre : dessous brun, queue plus pâle.", "Bande pâle sur les couvertures sus-alaires et « U » pâle au croupion."],
    si: "Milan noir — queue fourchue, sans taches blanches. Buse variable et Buse de Chine — ailes plus larges, taches carpiennes sombres. Circaète Jean-le-Blanc — plus grand, tête de hibou.",
    h: "Forêts mixtes et lisières dans les collines et montagnes, souvent près de milieux ouverts.",
    di: "Répandu en été : steppe boisée du Khentii et de la Selenge (Terelj, Oulan-Bator), lac Khar Us, Altaï, Khangaï et montagnes boisées du Gobi.",
    mi: "Visiteur d’été de fin avril à début octobre ; pics de passage en mai et septembre.",
    fo: "Petits et moyens oiseaux, lézards, spermophiles et autres petits mammifères.",
    br: "Nid de branches dans un grand arbre ou sur une falaise ; 1 ou 2 œufs. Les couples réutilisent le même nid chaque année.",
    be: "Plane haut puis pique brusquement, ailes repliées ; parades nuptiales en couple au printemps.",
    v: "Un « kli-kli-kli » aigu et sifflé, surtout près du nid.",
    cu: "Son nom vient des « bottes » de plumes de ses pattes, caractère des vrais aigles.",
    co: "Préoccupation mineure.",
    w: "Terelj et les collines boisées autour d’Oulan-Bator, lac Khar Us et vallées de l’Altaï, de mai à septembre.",
    bt: "mai–sept.",
    fa: ["L’un des plus petits vrais aigles.", "Existe en deux formes de couleur.", "Pattes emplumées jusqu’aux doigts."]
  },
  "western-marsh-harrier": {
    s: "Grand busard aux ailes larges qui patrouille à basse altitude au-dessus des roselières. En Mongolie, il niche surtout dans les lacs à roseaux de l’ouest.",
    d: "Le Busard des roseaux niche en Europe et en Asie occidentale ; la Mongolie est à la limite orientale de son aire, où il rencontre le Busard d’Orient et s’hybride parfois avec lui. Il glisse bas au-dessus des roseaux, ailes relevées en V, puis se laisse tomber sur ses proies. La plupart des mentions mongoles proviennent du lac Khar Us et de la dépression des Grands Lacs, quelques-unes des lacs du Khangaï et du Gobi.",
    f: ["Mâle : corps brun, tête pâle, queue grise et panneaux gris sur les ailes, extrémités noires.", "Femelle : brun chocolat avec la calotte et la gorge crème.", "Vole bas, ailes relevées en V.", "Ailes plus larges que les autres busards.", "Pas de croupion blanc (contrairement à la plupart des busards)."],
    si: "Busard d’Orient — mâle noir et gris, dessous blanc ; femelle plus striée, souvent à croupion blanc. Milan noir — queue fourchue, plane plus haut.",
    h: "Roselières et marais autour des lacs et des rivières lentes.",
    di: "Surtout l’ouest (lac Khar Us, dépression des Grands Lacs) ; aussi Böön Tsagaan, lac Orog et parfois le Khentii.",
    mi: "Visiteur d’été d’avril à octobre.",
    fo: "Grenouilles, petits mammifères, canetons et jeunes oiseaux d’eau, œufs.",
    br: "Nid de roseaux dans une roselière dense ; 3 à 6 œufs.",
    be: "Pendant la nidification, le mâle passe la nourriture à la femelle en vol.",
    v: "Surtout silencieux ; un « ki-a » fin près du nid.",
    cu: "Son nom latin aeruginosus signifie « couleur de rouille ».",
    co: "Préoccupation mineure ; dépend des roselières menacées par le drainage et le feu.",
    w: "Scrutez les roselières du lac Khar Us en été.",
    bt: "mai–sept.",
    fa: ["S’hybride avec le Busard d’Orient en Mongolie.", "Pratique le passage de proie en vol.", "Le plus grand busard d’Europe."]
  },
  "eastern-marsh-harrier": {
    s: "Le busard des marais d’Asie orientale — les mâles sont nettement noirs, gris et blancs. Visiteur d’été commun des zones humides du nord et de l’est de la Mongolie.",
    d: "Le Busard d’Orient niche dans le nord-est de la Chine, l’est de la Mongolie et le sud-est de la Sibérie, et hiverne dans le sud de la Chine et en Asie du Sud-Est. Il a longtemps été considéré comme une sous-espèce du Busard des roseaux. En Mongolie, il est commun d’avril à octobre dans les vallées et les lacs comme la vallée de Khurkh-Khüiten, le lac Ögii et le lac Buir.",
    f: ["Mâle : tête, poitrine et dos noirs striés de blanc ; ailes grises à extrémités noires ; dessous blanc.", "Femelle : brun foncé, striée de chamois sur la tête et la poitrine, souvent à croupion blanc.", "Juvénile : brun foncé à tête pâle.", "Glisse bas, ailes en léger V."],
    si: "Busard des roseaux — mâle brun et gris, femelle chocolat à tête crème. Busard tchoug — mâle plus nettement noir et blanc, plus petit et plus fin. Busard Saint-Martin — plus petit, grand croupion blanc.",
    h: "Marais, lacs à roseaux, prairies humides et vallées fluviales.",
    di: "Khentii et Selenge (Khurkh, Onon), Dornod (lac Buir, Mongol Daguur), lacs du Khangaï (lac Ögii) et vallée des Lacs.",
    mi: "Visiteur d’été, de fin mars à octobre ; maximum en mai–juin.",
    fo: "Grenouilles, campagnols, jeunes oiseaux d’eau et poissons.",
    br: "Nid de roseaux dans les zones humides ; 3 à 7 œufs.",
    be: "Chasse en patrouillant bas au-dessus des roseaux et des herbes ; dortoirs collectifs en hiver.",
    v: "Généralement silencieux ; cris miaulés au dortoir.",
    cu: "S’hybride avec le Busard des roseaux autour du lac Baïkal et en Mongolie.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh-Khüiten, lac Ögii et lac Buir, de mai à août.",
    bt: "mai–août",
    fa: ["Commun dans les zones humides de l’est de la Mongolie.", "Longtemps réuni avec le Busard des roseaux.", "Mâle et femelle sont totalement différents."]
  },
  "hen-harrier": {
    s: "Busard élancé à longue queue et large croupion blanc ; le mâle est gris pâle à extrémités d’ailes noires. Migrateur de passage dans toute la Mongolie, surtout en septembre.",
    d: "Le Busard Saint-Martin niche dans le nord de l’Eurasie, dans les landes, marais et prairies, et hiverne plus au sud. Il niche en petit nombre dans le nord de la Mongolie mais s’observe surtout en migration, en particulier en septembre, chassant bas au-dessus de la steppe.",
    f: ["Mâle : gris bleuté pâle, ventre blanc, extrémités des ailes noires.", "Femelle et juvénile : bruns, striés dessous, avec un grand croupion blanc.", "Disque facial rappelant une chouette.", "Ailes et queue longues ; glisse bas, ailes en V."],
    si: "Busard pâle — mâle plus pâle avec un fin coin noir au bout de l’aile ; femelle au dessin facial plus marqué. Busard tchoug — mâle noir et blanc. Busard cendré — mâle avec barre alaire noire et stries rousses.",
    h: "Steppe, marais, prairies et cultures.",
    di: "Toute la Mongolie en migration ; Khurkh, lac Khar Us, lac Ögii, lac Buir et steppes de l’est.",
    mi: "Surtout migrateur de passage (avril–mai, septembre–octobre) ; quelques nicheurs et hivernants.",
    fo: "Campagnols, petits oiseaux et insectes.",
    br: "Nid au sol dans la végétation haute ; 4 à 6 œufs.",
    be: "Chasse en vol bas, se laissant tomber sur ses proies qu’il repère aussi à l’oreille.",
    v: "Un « tchèk-èk-èk » près du nid.",
    cu: "Son nom anglais (« busard des poules ») rappelle son ancienne habitude de capturer des volailles.",
    co: "Préoccupation mineure, mais persécuté dans certaines régions d’Europe.",
    w: "En septembre dans les steppes du Khentii et du Dornod.",
    bt: "septembre",
    fa: ["Disque facial pour chasser à l’oreille.", "Le mâle est bien plus pâle que la femelle.", "Surtout vu en migration en Mongolie."]
  },
  "pallid-harrier": {
    s: "Busard fin des steppes ; le mâle, d’une pâleur fantomatique, porte un fin coin noir au bout de l’aile. Migrateur rare en Mongolie.",
    d: "Le Busard pâle niche dans les steppes du sud de la Russie et du Kazakhstan et hiverne en Inde et en Afrique. La Mongolie est à l’est de son aire principale ; on n’y compte que quelques mentions par an, surtout en migration d’automne dans l’ouest et le nord.",
    f: ["Mâle : gris très pâle, presque blanc dessous, fin coin noir à l’extrémité de l’aile.", "Femelle : brune à croupion blanc, collier pâle marqué et joue sombre.", "Fin, aux ailes étroites et pointues.", "Vol léger, rappelant une sterne."],
    si: "Busard Saint-Martin — mâle plus gris, extrémités noires plus larges ; femelle sans collier. Busard cendré — mâle avec des barres noires sur l’aile.",
    h: "Steppes ouvertes et prairies.",
    di: "Rare ; mentions au lac Khar Us, à Khurkh et près d’Oulan-Bator.",
    mi: "Migrateur de passage, mai et août–octobre.",
    fo: "Campagnols, alouettes et autres petits oiseaux, lézards et insectes.",
    br: "Niche au sol dans la steppe (pas en Mongolie).",
    be: "Chasse bas au-dessus des prairies.",
    v: "Généralement silencieux.",
    cu: "Son nom latin macrourus signifie « à longue queue ».",
    co: "Quasi menacé — conversion des steppes en cultures.",
    w: "Examinez bien les busards en automne dans l’ouest.",
    bt: "septembre",
    fa: ["Quasi menacé à l’échelle mondiale.", "Niche depuis peu en Europe de l’Ouest.", "En vol, le mâle paraît presque blanc."]
  },
  "pied-harrier": {
    s: "Élégant busard asiatique ; le mâle est nettement noir et blanc. Visiteur d’été local des prairies humides du nord-est de la Mongolie.",
    d: "Le Busard tchoug niche du sud-est de la Sibérie et du nord-est de la Mongolie jusqu’au nord-est de la Chine et à la Corée, et hiverne en Asie du Sud-Est. En Mongolie, il niche dans les prairies humides des vallées du Khentii et du Dornod ; la vallée de Khurkh-Khüiten et le lac Buir sont les sites les plus connus.",
    f: ["Mâle : tête, poitrine et dos noirs ; dessous blanc ; ailes grises à barre noire et extrémités noires.", "Femelle : brune dessus, pâle et striée dessous, petit croupion blanc.", "Yeux jaunes chez le mâle.", "Silhouette fine de busard."],
    si: "Busard d’Orient — mâle noir strié, plus grand, aux ailes plus larges. Busard Saint-Martin — mâle gris, pas noir.",
    h: "Prairies humides, bords de marais et vallées herbeuses.",
    di: "Nord-est : Khentii (Khurkh, Onon), Dornod (lac Buir, Mongol Daguur).",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Grenouilles, campagnols, petits oiseaux et gros insectes.",
    br: "Nid au sol dans l’herbe ou les roseaux ; 4 ou 5 œufs.",
    be: "Se pose sur des piquets ou au sol ; chasse en vol bas.",
    v: "Surtout silencieux.",
    cu: "L’un des busards les plus spectaculaires au monde.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh-Khüiten de juin à août.",
    bt: "juin–août",
    fa: ["Le mâle est noir et blanc.", "Ne niche qu’en Asie orientale.", "Se pose rarement dans les arbres."]
  },
  "montagus-harrier": {
    s: "Busard gracieux aux ailes étroites, d’Europe et d’Asie occidentale. Seulement quelques mentions dans l’ouest de la Mongolie.",
    d: "Le Busard cendré niche de l’Europe à la Sibérie occidentale et au Kazakhstan et hiverne en Afrique et en Inde. Il est très rare en Mongolie : les quelques mentions viennent surtout de l’ouest, en fin d’été et en automne.",
    f: ["Mâle : gris, extrémités des ailes noires, barre noire sur le dessus de l’aile, stries rousses sur les flancs.", "Femelle : brune à croupion blanc, comme les autres femelles de busards.", "Ailes très étroites et pointues.", "Vol léger, rappelant une sterne."],
    si: "Busards pâle et Saint-Martin — mâles sans barres alaires noires ; femelles difficiles à séparer.",
    h: "Prairies ouvertes et cultures.",
    di: "Très rare ; ouest de la Mongolie et Khövsgöl.",
    mi: "Erratique ou migrateur rare.",
    fo: "Campagnols, petits oiseaux, lézards et insectes.",
    br: "Niche au sol dans les céréales ou les herbes (pas en Mongolie).",
    be: "Glisse très bas au-dessus des champs.",
    v: "Généralement silencieux.",
    cu: "Son nom anglais honore le naturaliste George Montagu.",
    co: "Préoccupation mineure.",
    w: "Non attendu — examinez les busards dans l’ouest.",
    bt: "—",
    fa: ["Nom anglais d’après George Montagu.", "Niche souvent dans les céréales en Europe.", "Très rare en Mongolie."]
  },
  "shikra": {
    s: "Petit épervier pâle d’Asie tropicale et d’Afrique. Inscrit sur la liste mongole, mais sans mention documentée dans le GBIF — erratique exceptionnel.",
    d: "L’Épervier shikra est commun en Inde, en Asie du Sud-Est et en Afrique, dans les bois clairs, les jardins et les villages. Il figure sur la liste de Mongolie sur la base de très rares mentions ; toute observation doit être soigneusement documentée.",
    f: ["Dessus gris pâle ; dessous finement barré de roux.", "Trait sombre vertical sur la gorge blanche.", "Œil rouge chez l’adulte.", "Ailes courtes et arrondies, queue assez longue."],
    si: "Épervier d’Europe — plus grand, plus sombre dessus, sans trait gulaire. Épervier du Japon — plus petit, plus sombre, œil sombre.",
    h: "Bois clairs, bosquets et villages.",
    di: "Erratique exceptionnel.",
    mi: "Surtout sédentaire ; les oiseaux du nord se déplacent peu.",
    fo: "Lézards, petits oiseaux, rongeurs et insectes.",
    br: "Niche dans les arbres ; 2 à 4 œufs (pas en Mongolie).",
    be: "Chasse à l’affût depuis un perchoir caché.",
    v: "Un « ti-toui » perçant, souvent imité par les drongos.",
    cu: "Son nom vient du hindi-ourdou « shikra », un faucon de chasse.",
    co: "Préoccupation mineure.",
    w: "Non attendu en Mongolie.",
    bt: "—",
    fa: ["Les drongos imitent son cri.", "Récemment placé dans le genre Tachyspiza.", "Très commun en Inde."]
  },
  "japanese-sparrowhawk": {
    s: "Minuscule épervier d’Asie orientale, avec un fin trait sombre sur la gorge. Migrateur rare dans l’est et le nord de la Mongolie.",
    d: "L’Épervier du Japon niche dans l’Extrême-Orient russe, en Corée, au Japon et dans le nord-est de la Chine, et hiverne en Asie du Sud-Est. Il migre en grandes bandes le long de la côte d’Asie orientale. En Mongolie, il est rare, avec quelques mentions dans l’est et le Khangaï, surtout en mai.",
    f: ["Très petit épervier aux ailes arrondies et à queue courte.", "Mâle : gris foncé dessus, flancs roux, œil rouge.", "Femelle : dessous barré de brun, œil jaune.", "Fin trait sombre sur la gorge blanche."],
    si: "Épervier d’Europe — plus grand, queue plus longue, sans trait gulaire. Épervier shikra — plus pâle dessus.",
    h: "Forêts et lisières ; en migration, aussi les parcs.",
    di: "Rare ; est de la Mongolie et Khangaï.",
    mi: "Migrateur de passage, mai et septembre.",
    fo: "Petits oiseaux, insectes et lézards.",
    br: "Niche dans les arbres ; 2 à 5 œufs (nidification non confirmée en Mongolie).",
    be: "Vol en battements rapides et glissades ; migre en bandes.",
    v: "Un « kiki-kik-kik » jacassant.",
    cu: "En danger au Japon mais commun ailleurs.",
    co: "Préoccupation mineure.",
    w: "Surveillez les petits éperviers en mai dans l’est.",
    bt: "mai",
    fa: ["L’un des plus petits éperviers d’Asie.", "Migre en bandes.", "Porte un trait sur la gorge."]
  },
  "eurasian-sparrowhawk": {
    s: "Petit rapace fougueux qui surprend les passereaux ; le mâle est gris-bleu dessus et barré d’orange dessous. Commun en migration dans toute la Mongolie, il niche dans les forêts du nord.",
    d: "L’Épervier d’Europe est présent dans toutes les régions tempérées de l’Ancien Monde. Chasseur d’oiseaux spécialisé, il surprend ses proies par des vols rapides et bas le long des haies et des lisières ; il chasse souvent en ville. La femelle est jusqu’à un quart plus grande que le mâle. En Mongolie, il niche dans les forêts du Khentii, du Khangaï et de l’Altaï et se voit partout en migration, y compris dans les oasis du Gobi comme Yolyn Am, avec des pics en avril–mai et en septembre.",
    f: ["Mâle : gris-bleu dessus, barré d’orange dessous, joues orangées.", "Femelle : gris-brun dessus, barrée de gris-brun dessous, sourcil blanc.", "Œil jaune ; longues pattes fines et jaunes.", "Ailes courtes et arrondies, longue queue carrée.", "Vol « battements–battements–glissade »."],
    si: "Autour des palombes — bien plus grand et lourd, poitrine bombée, sous-caudales blanches. Épervier du Japon — plus petit, trait gulaire. Faucon crécerelle — ailes pointues, fait du surplace.",
    h: "Forêts, lisières, parcs et villes ; tous milieux en migration.",
    di: "Toute la Mongolie : Oulan-Bator et Terelj, Khurkh, lac Khar Us, Yolyn Am et steppes de l’est.",
    mi: "Niche dans le nord (avril–octobre) ; pics de passage en mai et septembre ; quelques hivernants.",
    fo: "Petits oiseaux : moineaux, mésanges, fringilles et grives.",
    br: "Nid de brindilles dans un arbre ; 4 ou 5 œufs bleutés ; éclosion au bout de 33 jours.",
    be: "Surprend les oiseaux par des attaques soudaines ; parades en vol plané au printemps.",
    v: "Un « kèk-kèk-kèk » rapide au nid.",
    cu: "Traditionnellement utilisé en fauconnerie pour chasser la caille.",
    co: "Préoccupation mineure ; rétabli en Europe après l’interdiction des pesticides.",
    w: "Parcs d’Oulan-Bator, Terelj et oasis du Gobi en migration.",
    bt: "avril–mai, sept.",
    fa: ["La femelle est bien plus grande que le mâle.", "Chasse les oiseaux en ville.", "S’est rétabli après l’interdiction du DDT."]
  }
});
