B2T("en", {
  "northern-goshawk": {
    T: { c: { gray: 0.45, white: 0.3, brown: 0.15, black: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["46–63 cm", "89–122 cm", "0.6–1.4 kg"] },
    s: "A powerful forest hawk with a fierce white eyebrow and orange-red eyes. A scarce, secretive resident of Mongolia’s taiga and forest-steppe.",
    d: "The Northern (Eurasian) Goshawk lives throughout the temperate forests of Eurasia. It is a large, heavy hawk that hunts birds and mammals with short, explosive dashes through the trees. Birds from the far north are very pale. In Mongolia it breeds in the larch and pine forests of Khentii, Khövsgöl and the Khangai, and in winter some move into the forest-steppe and valleys. It is shy and easily overlooked, so records are few.",
    f: ["Large hawk with a broad chest and a long, rounded tail.", "Adult: grey above, finely barred grey below, bold white eyebrow and dark cheek.", "Eye yellow to deep orange-red.", "Juvenile: brown above, buff below with dark teardrop streaks.", "Fluffy white undertail coverts, obvious in display."],
    si: "Eurasian Sparrowhawk — much smaller and slimmer, with a thin tail and no strong eyebrow. Saker and Gyrfalcon — pointed wings, dark eye.",
    h: "Mature coniferous and mixed forest, forest edges and river woodlands.",
    di: "Khentii, Selenge, Khövsgöl and Khangai forests; occasionally Terelj and Ulaanbaatar in winter.",
    mi: "Mostly resident; northern birds wander south in winter.",
    fo: "Grouse, hazel grouse, pigeons, crows, squirrels and hares.",
    br: "Builds a large stick nest high in a conifer; 2–4 eggs.",
    be: "Hunts from cover with sudden fast attacks; displays with slow, deep wingbeats over the forest in early spring.",
    v: "A loud, harsh ‘kyek-kyek-kyek’ near the nest.",
    cu: "A prized bird of falconers since ancient times; Attila the Hun is said to have carried a goshawk on his helmet.",
    co: "Least Concern.",
    w: "Quiet forest trails in Terelj, Khentii and Khövsgöl in early spring, when pairs display.",
    bt: "March–May",
    fa: ["Females are much larger than males.", "Can catch prey as big as a hare.", "Northern birds can be almost white."]
  },
  "white-tailed-sea-eagle": {
    T: { c: { brown: 0.65, white: 0.15, buff: 0.1, yellow: 0.1 }, hb: ["water", "forest"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer", "passage"], sz: ["66–94 cm", "178–245 cm", "3.1–6.9 kg"] },
    s: "A huge eagle with a massive yellow bill, broad ‘barn-door’ wings and a short white tail. It breeds at large lakes and rivers across northern Mongolia.",
    d: "The White-tailed Eagle is the largest eagle in Europe and northern Asia. It lives by lakes, rivers and coasts, eating fish and waterbirds and taking carrion. After a century of persecution and pesticide poisoning it has recovered in much of Europe. In Mongolia it nests in tall trees or on cliffs near large lakes and rivers such as Ögii Nuur, Khar Us Nuur, Terkhiin Tsagaan Nuur, Khövsgöl and the Khurkh and Onon valleys, arriving in April and leaving in October–November.",
    f: ["Very large, with long, broad, rectangular wings with ‘fingered’ tips.", "Adult: brown body, paler head and neck, pure white wedge-shaped tail.", "Massive yellow bill; yellow legs and eyes.", "Juvenile: dark brown with a dark bill and a dark-edged pale tail.", "Head and tail stick out equally in flight."],
    si: "Pallas’s Fish Eagle — white tail with a broad black band, pale head. Golden Eagle — longer tail, smaller head, no white tail. Cinereous Vulture — all dark, tiny head.",
    h: "Large lakes, rivers and wetlands with tall trees or cliffs.",
    di: "Khangai lakes (Ögii, Terkhiin Tsagaan), Khövsgöl, Khar Us Nuur, Khentii (Khurkh, Onon), Dornod lakes.",
    mi: "Summer visitor, April–November; peak in June and September; a few winter.",
    fo: "Fish, ducks and coots, other waterbirds, carrion.",
    br: "Very large nest in a tree or on a cliff, used for many years; 1–3 eggs.",
    be: "Sits for long periods on a tree or shore; steals food from other birds.",
    v: "A yelping ‘klee-klee-klee’, often in duet.",
    cu: "Once called the ‘erne’; a symbol of wild northern lakes.",
    co: "Least Concern; in the Mongolian Red Book.",
    w: "Ögii Nuur, Khar Us Nuur and Khurkh valley in summer.",
    bt: "May–September",
    fa: ["Wingspan up to 2.45 m.", "Uses the same nest for decades.", "Recovered in Europe after pesticide bans."]
  },
  "black-kite": {
    T: { c: { brown: 0.7, rufous: 0.1, gray: 0.1, buff: 0.1 }, hb: ["settlement", "steppe", "water"], bk: "hooked", bh: ["soar", "perch"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["48–60 cm", "130–155 cm", "0.6–1.1 kg"] },
    s: "A dark brown raptor with a shallow forked tail, constantly circling over towns, gers and river valleys. The commonest large raptor of Mongolian summers.",
    d: "The Black Kite may be the world’s most numerous bird of prey. It is an opportunist that scavenges, steals food and catches small animals. The eastern subspecies (Black-eared Kite) breeds throughout Mongolia and gathers in large numbers around Ulaanbaatar, ger camps, rubbish dumps and livestock. It arrives in April and leaves in September for southern Asia.",
    f: ["Medium-large brown raptor with long, angled wings.", "Shallow fork in the tail, which it twists constantly.", "Pale patch at the base of the primaries.", "Dark ‘ear’ patch in the eastern subspecies.", "Often in loose flocks."],
    si: "Booted Eagle (dark morph) — square tail, white ‘landing lights’. Western Marsh Harrier (female) — longer tail, flies low. Upland and Eurasian Buzzard — broad, rounded tail.",
    h: "Towns, ger camps, river valleys, steppe and forest edges.",
    di: "All of Mongolia; very common around Ulaanbaatar, Khurkh, Terelj, Khustai and lakes.",
    mi: "Summer visitor, April–September; most numerous May–June.",
    fo: "Carrion, scraps, rodents, fish, insects and small birds.",
    br: "Nests in trees, on cliffs or on pylons, often decorated with rags and plastic; 2–3 eggs.",
    be: "Soars and glides for hours; snatches food from the ground or water in flight.",
    v: "A shrill, whinnying ‘pee-errr’.",
    cu: "In Australia kites are said to spread bushfires by carrying burning sticks.",
    co: "Least Concern.",
    w: "Anywhere in summer — especially over Ulaanbaatar and ger camps.",
    bt: "May–August",
    fa: ["Possibly the most numerous raptor in the world.", "Decorates its nest with rubbish.", "Twists its tail like a rudder."]
  },
  "grey-faced-buzzard": {
    T: { c: { brown: 0.5, gray: 0.2, white: 0.2, rufous: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch", "soar"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["41–46 cm", "101–110 cm", "375–435 g"] },
    s: "A slim East Asian hawk with a grey face and a dark throat stripe. On the Mongolian list, but with no GBIF records — an exceptional vagrant.",
    d: "The Grey-faced Buzzard breeds in Manchuria, Korea and Japan and winters in South-East Asia, migrating in large flocks. It is not a true buzzard but belongs to a separate genus. Records in Mongolia are exceptional.",
    f: ["Grey head and face with a white throat and dark central throat stripe.", "Brown back; underparts barred brown and white.", "Long wings and a fairly long tail.", "Juvenile: brown with a broad white eyebrow."],
    si: "Eurasian and Upland Buzzards — bulkier, shorter-tailed, no throat stripe.",
    h: "Forest and forest edges beside open land.",
    di: "Exceptional vagrant.",
    mi: "Migratory; not expected in Mongolia.",
    fo: "Lizards, frogs, small mammals and large insects.",
    br: "Nests in trees (not in Mongolia).",
    be: "Hunts from a perch on forest edges.",
    v: "A whistled ‘pik-kwee’.",
    cu: "Its mass migration is a highlight of autumn in Japan and Taiwan.",
    co: "Least Concern.",
    w: "Not expected in Mongolia.",
    bt: "—",
    fa: ["Migrates in flocks of thousands.", "Not a true Buteo buzzard.", "Grey face gives it its name."]
  },
  "rough-legged-buzzard": {
    T: { c: { white: 0.35, brown: 0.35, buff: 0.2, black: 0.1 }, hb: ["steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["winter", "passage"], sz: ["46–68 cm", "120–153 cm", "0.6–1.7 kg"] },
    s: "An Arctic buzzard with feathered legs, a white tail with a black band and a dark belly patch. A scarce winter visitor to Mongolia’s steppes.",
    d: "The Rough-legged Buzzard breeds on the Arctic tundra of Eurasia and North America and moves south in winter. It often hovers while hunting, like a kestrel. It is a scarce passage migrant and winter visitor in Mongolia, recorded in all regions from October to April.",
    f: ["Legs feathered to the toes.", "White tail with a broad black band near the tip.", "Dark belly patch and dark wrist patches under the wing.", "Pale head.", "Hovers regularly."],
    si: "Upland Buzzard — larger, pale tail without a sharp black band. Eurasian Buzzard — barred tail. Long-legged Buzzard — rufous tail.",
    h: "Open steppe, fields and river valleys in winter.",
    di: "Scarce throughout; Khar Us Nuur, Khurkh, Ulaanbaatar and the Gobi.",
    mi: "Winter visitor and passage migrant, October–April.",
    fo: "Voles, lemmings and pikas; also birds and carrion.",
    br: "Nests on Arctic cliffs (not in Mongolia); clutch size depends on lemming numbers.",
    be: "Hovers into the wind; sits on low mounds or posts.",
    v: "A mewing ‘pee-yow’.",
    cu: "Its scientific name lagopus means ‘hare-footed’.",
    co: "Least Concern.",
    w: "Winter steppes near Ulaanbaatar and in the east.",
    bt: "November–March",
    fa: ["Legs feathered like a ptarmigan’s.", "One of the few raptors that hovers.", "Breeds in the Arctic."]
  },
  "eurasian-buzzard": {
    T: { c: { brown: 0.6, white: 0.2, buff: 0.1, rufous: 0.1 }, hb: ["forest", "steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer", "passage"], sz: ["40–58 cm", "109–140 cm", "0.4–1.4 kg"] },
    s: "A medium-sized, variable buzzard that soars on broad wings. In Mongolia the eastern ‘Steppe Buzzard’ occurs mainly in the west and on migration.",
    d: "The Common (Eurasian) Buzzard is Europe’s commonest raptor. Its range extends east to the Tian Shan, western Siberia and north-western Mongolia; eastern birds (subspecies vulpinus, ‘Steppe Buzzard’) are long-distance migrants. In Mongolia it is found mainly in the forests of the Altai and Khangai and on migration, especially in September.",
    f: ["Broad rounded wings and a short, fan-shaped tail.", "Plumage very variable, from pale to dark brown or rufous.", "Pale band across the breast in many birds.", "Tail finely barred.", "Holds wings in a shallow V when soaring."],
    si: "Upland Buzzard — larger, paler, with a pale tail. Long-legged Buzzard — rufous tail and dark belly. Rough-legged Buzzard — white tail with black band.",
    h: "Forest edges and wooded valleys beside open land.",
    di: "Mainly western Mongolia and the Khangai; on passage throughout (Ulaanbaatar, Terelj, Khar Us Nuur).",
    mi: "Summer visitor and passage migrant, April–October.",
    fo: "Voles and other rodents, reptiles, birds, earthworms.",
    br: "Nests in trees; 2–4 eggs.",
    be: "Often waits on a perch; soars and circles in thermals.",
    v: "A mewing ‘peee-yah’, the classic buzzard call.",
    cu: "Its call is often used in films for eagles.",
    co: "Least Concern.",
    w: "Altai and Khangai valleys in summer; migration in September.",
    bt: "May–September",
    fa: ["Europe’s commonest raptor.", "Eastern birds migrate to Africa.", "Hugely variable in colour."]
  },
  "long-legged-buzzard": {
    T: { c: { rufous: 0.35, brown: 0.3, buff: 0.25, white: 0.1 }, hb: ["desert", "mountain", "steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["50–65 cm", "126–155 cm", "0.6–1.8 kg"] },
    s: "A large, long-winged buzzard with a pale head and a plain rufous-orange tail. A summer visitor to the deserts and dry mountains of the Gobi and western Mongolia.",
    d: "The Long-legged Buzzard ranges from south-east Europe and North Africa to Central Asia. It is a bird of dry, open country. In Mongolia it breeds in the Gobi and the arid west, nesting on cliffs and rocky outcrops, and hunts gerbils, jirds and ground squirrels. It meets the Upland Buzzard in the Gobi, and the two can be hard to tell apart.",
    f: ["Pale, often creamy head and breast.", "Plain rufous-orange tail, unbarred and paler at the base.", "Dark belly and thighs; black wrist patches under the wing.", "Long wings, held in a V when soaring.", "Often hovers."],
    si: "Upland Buzzard — larger, with a paler whitish tail, feathered legs. Eurasian Buzzard — smaller, barred tail.",
    h: "Deserts, semi-deserts, rocky hills and dry mountain valleys.",
    di: "Gobi (Yolyn Am, Orog Nuur, Böön Tsagaan, Taatsiin Tsagaan) and western Mongolia (Khar Us Nuur); also Ögii Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Gerbils, jirds, ground squirrels and other rodents; reptiles and insects.",
    br: "Nests on cliffs or rocky outcrops; 2–4 eggs.",
    be: "Hunts from a rock perch or by hovering; soars over dry hills.",
    v: "A mewing call, higher than Eurasian Buzzard.",
    cu: "Considered the most aggressive of the buzzards.",
    co: "Least Concern.",
    w: "Yolyn Am and the Gobi lakes in summer.",
    bt: "May–August",
    fa: ["Has an unbarred rufous tail.", "Lives in hot, dry country.", "Hard to tell from the Upland Buzzard."]
  },
  "osprey": {
    T: { c: { white: 0.45, brown: 0.4, black: 0.15 }, hb: ["water"], bk: "hooked", bh: ["soar", "perch"], vt: ["whistle"], ac: "day", se: ["passage", "summer"], sz: ["50–66 cm", "127–180 cm", "0.9–2.1 kg"] },
    s: "A fish-eating raptor with a white head, a dark eye-stripe and long, angled wings. It plunges feet-first into lakes and rivers; seen in Mongolia mainly on migration.",
    d: "The Osprey is found on every continent except Antarctica. It feeds almost entirely on fish, hovering over water and then diving feet-first. Its reversible outer toe and spiny soles help it hold slippery fish. In Mongolia it is a scarce summer visitor and passage migrant at lakes and rivers, with peaks in May and September; Ögii Nuur is one of the best sites.",
    f: ["White underparts and head with a dark stripe through the eye.", "Dark brown upperparts.", "Long, narrow wings bent at the wrist like a gull’s, with black wrist patches.", "Dark breast band, stronger in females.", "Plunges feet-first."],
    si: "White-tailed Eagle — much larger, dark underneath. Large gulls — no dark eye-stripe, different flight.",
    h: "Lakes, rivers and reservoirs with fish.",
    di: "Khangai lakes (Ögii Nuur), rivers of Khentii and Selenge, western lakes and Gobi lakes on passage.",
    mi: "Passage migrant and scarce summer visitor; peaks in May and September.",
    fo: "Fish.",
    br: "Large stick nest on a tree top, cliff or pylon; 2–4 eggs.",
    be: "Hovers over water, then dives, carrying the fish head-forward.",
    v: "A series of clear whistles, ‘kyew-kyew’.",
    cu: "The only living member of its family, Pandionidae.",
    co: "Least Concern; recovered after pesticide bans.",
    w: "Ögii Nuur in May and September.",
    bt: "May, September",
    fa: ["Its outer toe can turn backwards.", "Found on every continent except Antarctica.", "Carries fish head-first to reduce drag."]
  }
});
