B2T("fr", {
  "northern-goshawk": {
    name: "Autour des palombes",
    s: "Puissant rapace forestier au sourcil blanc marqué et aux yeux rouge orangé. Résident rare et discret de la taïga et de la steppe boisée de Mongolie.",
    d: "L’Autour des palombes vit dans toutes les forêts tempérées d’Eurasie. Grand et lourd, il chasse oiseaux et mammifères par de courtes attaques explosives entre les arbres. Les oiseaux de l’extrême nord sont très pâles. En Mongolie, il niche dans les forêts de mélèzes et de pins du Khentii, du Khövsgöl et du Khangaï ; en hiver, certains descendent vers la steppe boisée et les vallées. Farouche et facilement négligé, il compte peu de mentions.",
    f: ["Grand rapace à poitrine large et longue queue arrondie.", "Adulte : gris dessus, finement barré de gris dessous, sourcil blanc marqué et joue sombre.", "Œil jaune à rouge orangé foncé.", "Juvénile : brun dessus, chamois dessous avec des gouttes sombres.", "Sous-caudales blanches et duveteuses, bien visibles en parade."],
    si: "Épervier d’Europe — bien plus petit et fin, queue étroite, sans sourcil marqué. Faucons sacre et gerfaut — ailes pointues, œil sombre.",
    h: "Forêts matures de conifères et mixtes, lisières et ripisylves.",
    di: "Forêts du Khentii, de la Selenge, du Khövsgöl et du Khangaï ; parfois Terelj et Oulan-Bator en hiver.",
    mi: "Surtout sédentaire ; les oiseaux nordiques erratiques en hiver.",
    fo: "Tétras, gélinottes, pigeons, corvidés, écureuils et lièvres.",
    br: "Grand nid de branches haut dans un conifère ; 2 à 4 œufs.",
    be: "Chasse à couvert par attaques soudaines ; parade en battements lents et profonds au-dessus de la forêt au début du printemps.",
    v: "Un « kyèk-kyèk-kyèk » fort et rauque près du nid.",
    cu: "Oiseau prisé des fauconniers depuis l’Antiquité ; Attila en aurait porté l’image sur son casque.",
    co: "Préoccupation mineure.",
    w: "Sentiers forestiers calmes de Terelj, du Khentii et du Khövsgöl au début du printemps, quand les couples paradent.",
    bt: "mars–mai",
    fa: ["Les femelles sont bien plus grandes que les mâles.", "Peut capturer un lièvre.", "Les oiseaux nordiques peuvent être presque blancs."]
  },
  "white-tailed-sea-eagle": {
    name: "Pygargue à queue blanche",
    s: "Aigle immense au gros bec jaune, aux ailes larges comme des « portes de grange » et à la courte queue blanche. Il niche près des grands lacs et rivières du nord de la Mongolie.",
    d: "Le Pygargue à queue blanche est le plus grand aigle d’Europe et d’Asie du Nord. Il vit près des lacs, des rivières et des côtes, se nourrit de poissons et d’oiseaux d’eau et consomme des charognes. Après un siècle de persécution et d’empoisonnement par les pesticides, il s’est rétabli dans une grande partie de l’Europe. En Mongolie, il niche dans de grands arbres ou sur des falaises près des grands lacs et rivières — lac Ögii, lac Khar Us, Terkhiin Tsagaan Nuur, Khövsgöl, vallées de Khurkh et de l’Onon — d’avril à octobre–novembre.",
    f: ["Très grand, ailes longues, larges et rectangulaires aux extrémités digitées.", "Adulte : corps brun, tête et cou plus pâles, queue cunéiforme blanc pur.", "Énorme bec jaune ; pattes et yeux jaunes.", "Juvénile : brun foncé, bec sombre, queue pâle bordée de sombre.", "En vol, la tête et la queue dépassent autant l’une que l’autre."],
    si: "Pygargue de Pallas — queue blanche à large bande noire, tête pâle. Aigle royal — queue plus longue, tête plus petite, pas de queue blanche. Vautour moine — entièrement sombre, petite tête.",
    h: "Grands lacs, rivières et zones humides avec grands arbres ou falaises.",
    di: "Lacs du Khangaï (Ögii, Terkhiin Tsagaan), Khövsgöl, lac Khar Us, Khentii (Khurkh, Onon), lacs du Dornod.",
    mi: "Visiteur d’été, avril–novembre ; pics en juin et septembre ; quelques hivernants.",
    fo: "Poissons, canards et foulques, autres oiseaux d’eau, charognes.",
    br: "Très grand nid dans un arbre ou sur une falaise, utilisé de nombreuses années ; 1 à 3 œufs.",
    be: "Reste longtemps perché ; vole la nourriture d’autres oiseaux.",
    v: "Un « kli-kli-kli » glapissant, souvent en duo.",
    cu: "Symbole des lacs sauvages du Nord.",
    co: "Préoccupation mineure ; inscrit au Livre rouge de Mongolie.",
    w: "Lac Ögii, lac Khar Us et vallée de Khurkh en été.",
    bt: "mai–sept.",
    fa: ["Envergure jusqu’à 2,45 m.", "Réutilise le même nid pendant des décennies.", "S’est rétabli en Europe après l’interdiction des pesticides."]
  },
  "black-kite": {
    name: "Milan noir",
    s: "Rapace brun foncé à queue légèrement fourchue, tournoyant sans cesse au-dessus des villes, des yourtes et des vallées. Le grand rapace le plus commun de l’été mongol.",
    d: "Le Milan noir est peut-être le rapace le plus nombreux au monde. Opportuniste, il se nourrit de charognes, vole de la nourriture et capture de petits animaux. La sous-espèce orientale (milan à oreilles noires) niche dans toute la Mongolie et se rassemble en grand nombre autour d’Oulan-Bator, des camps de yourtes, des décharges et du bétail. Il arrive en avril et repart en septembre vers l’Asie du Sud.",
    f: ["Rapace brun moyen à grand, aux longues ailes coudées.", "Queue légèrement fourchue, qu’il tord sans cesse.", "Plage pâle à la base des primaires.", "Tache sombre sur la joue chez la sous-espèce orientale.", "Souvent en groupes lâches."],
    si: "Aigle botté (forme sombre) — queue carrée, « phares » blancs. Busard des roseaux (femelle) — queue plus longue, vol bas. Buses — queue large et arrondie.",
    h: "Villes, camps de yourtes, vallées, steppe et lisières.",
    di: "Toute la Mongolie ; très commun autour d’Oulan-Bator, Khurkh, Terelj, Khustai et des lacs.",
    mi: "Visiteur d’été, avril–septembre ; maximum en mai–juin.",
    fo: "Charognes, déchets, rongeurs, poissons, insectes et petits oiseaux.",
    br: "Niche dans les arbres, sur les falaises ou les pylônes, décorant son nid de chiffons et de plastique ; 2 ou 3 œufs.",
    be: "Plane pendant des heures ; saisit la nourriture au sol ou sur l’eau en vol.",
    v: "Un « pii-èrrr » aigu et hennissant.",
    cu: "En Australie, on dit que les milans propagent les feux en transportant des brindilles enflammées.",
    co: "Préoccupation mineure.",
    w: "Partout en été — surtout au-dessus d’Oulan-Bator et des camps de yourtes.",
    bt: "mai–août",
    fa: ["Peut-être le rapace le plus nombreux au monde.", "Décore son nid de déchets.", "Se sert de sa queue comme d’un gouvernail."]
  },
  "grey-faced-buzzard": {
    name: "Busautour à joues grises",
    s: "Rapace élancé d’Asie orientale à face grise et trait gulaire sombre. Sur la liste mongole, mais sans mention GBIF — erratique exceptionnel.",
    d: "Le Busautour à joues grises niche en Mandchourie, en Corée et au Japon et hiverne en Asie du Sud-Est, migrant en grandes bandes. Ce n’est pas une vraie buse mais un genre distinct. Sa présence en Mongolie est exceptionnelle.",
    f: ["Tête et face grises, gorge blanche avec un trait central sombre.", "Dos brun ; dessous barré de brun et de blanc.", "Longues ailes, queue assez longue.", "Juvénile : brun avec un large sourcil blanc."],
    si: "Buses variable et de Chine — plus massives, queue plus courte, sans trait gulaire.",
    h: "Forêts et lisières près de milieux ouverts.",
    di: "Erratique exceptionnel.",
    mi: "Migrateur ; non attendu en Mongolie.",
    fo: "Lézards, grenouilles, petits mammifères et gros insectes.",
    br: "Niche dans les arbres (pas en Mongolie).",
    be: "Chasse à l’affût en lisière.",
    v: "Un « pik-kouii » sifflé.",
    cu: "Sa migration massive est un temps fort de l’automne au Japon et à Taïwan.",
    co: "Préoccupation mineure.",
    w: "Non attendu en Mongolie.",
    bt: "—",
    fa: ["Migre par milliers.", "N’est pas une vraie buse du genre Buteo.", "Doit son nom à sa face grise."]
  },
  "rough-legged-buzzard": {
    name: "Buse pattue",
    s: "Buse arctique aux pattes emplumées, à queue blanche barrée de noir et au ventre sombre. Hivernante peu commune dans les steppes de Mongolie.",
    d: "La Buse pattue niche dans la toundra arctique d’Eurasie et d’Amérique du Nord et descend vers le sud en hiver. Elle fait souvent du surplace en chassant, comme une crécerelle. En Mongolie, c’est une migratrice et hivernante peu commune, notée dans toutes les régions d’octobre à avril.",
    f: ["Pattes emplumées jusqu’aux doigts.", "Queue blanche avec une large bande noire près de l’extrémité.", "Ventre sombre et taches carpiennes sombres sous l’aile.", "Tête pâle.", "Fait régulièrement du surplace."],
    si: "Buse de Chine — plus grande, queue pâle sans bande noire nette. Buse variable — queue barrée. Buse féroce — queue rousse.",
    h: "Steppes ouvertes, champs et vallées en hiver.",
    di: "Peu commune partout ; lac Khar Us, Khurkh, Oulan-Bator et Gobi.",
    mi: "Hivernante et migratrice de passage, octobre–avril.",
    fo: "Campagnols, lemmings et pikas ; aussi oiseaux et charognes.",
    br: "Niche sur les falaises arctiques (pas en Mongolie) ; la ponte dépend de l’abondance des lemmings.",
    be: "Fait du surplace face au vent ; se pose sur des buttes ou des piquets.",
    v: "Un « pii-you » miaulé.",
    cu: "Son nom latin lagopus signifie « pied de lièvre ».",
    co: "Préoccupation mineure.",
    w: "Steppes hivernales près d’Oulan-Bator et dans l’est.",
    bt: "nov.–mars",
    fa: ["Pattes emplumées comme un lagopède.", "L’un des rares rapaces à faire du surplace.", "Niche dans l’Arctique."]
  },
  "eurasian-buzzard": {
    name: "Buse variable",
    s: "Buse de taille moyenne au plumage variable, planant sur des ailes larges. En Mongolie, la forme orientale « buse des steppes » se voit surtout dans l’ouest et en migration.",
    d: "La Buse variable est le rapace le plus commun d’Europe. Son aire s’étend vers l’est jusqu’au Tian Shan, à la Sibérie occidentale et au nord-ouest de la Mongolie ; les oiseaux orientaux (sous-espèce vulpinus, « buse des steppes ») migrent jusqu’en Afrique. En Mongolie, elle fréquente surtout les forêts de l’Altaï et du Khangaï et passe en migration, notamment en septembre.",
    f: ["Ailes larges et arrondies, queue courte en éventail.", "Plumage très variable, du pâle au brun foncé ou roux.", "Bande pâle sur la poitrine chez beaucoup d’oiseaux.", "Queue finement barrée.", "Ailes en léger V en vol plané."],
    si: "Buse de Chine — plus grande, plus pâle, queue pâle. Buse féroce — queue rousse, ventre sombre. Buse pattue — queue blanche à bande noire.",
    h: "Lisières et vallées boisées près de milieux ouverts.",
    di: "Surtout l’ouest et le Khangaï ; partout en migration (Oulan-Bator, Terelj, lac Khar Us).",
    mi: "Visiteuse d’été et migratrice, avril–octobre.",
    fo: "Campagnols et autres rongeurs, reptiles, oiseaux, vers de terre.",
    br: "Niche dans les arbres ; 2 à 4 œufs.",
    be: "Attend souvent sur un perchoir ; tournoie dans les ascendances.",
    v: "Un « piii-ya » miaulé, le cri classique de la buse.",
    cu: "Son cri est souvent utilisé au cinéma pour les aigles.",
    co: "Préoccupation mineure.",
    w: "Vallées de l’Altaï et du Khangaï en été ; migration en septembre.",
    bt: "mai–sept.",
    fa: ["Le rapace le plus commun d’Europe.", "Les oiseaux orientaux migrent en Afrique.", "Couleur extrêmement variable."]
  },
  "long-legged-buzzard": {
    name: "Buse féroce",
    s: "Grande buse aux longues ailes, à tête pâle et queue unie roux orangé. Visiteuse d’été des déserts et montagnes sèches du Gobi et de l’ouest de la Mongolie.",
    d: "La Buse féroce est présente du sud-est de l’Europe et de l’Afrique du Nord jusqu’en Asie centrale, dans les pays secs et ouverts. En Mongolie, elle niche dans le Gobi et l’ouest aride, sur les falaises et les affleurements rocheux, et chasse gerbilles, mérions et spermophiles. Elle côtoie la Buse de Chine dans le Gobi, et les deux sont parfois difficiles à distinguer.",
    f: ["Tête et poitrine pâles, souvent crème.", "Queue unie roux orangé, sans barres, plus pâle à la base.", "Ventre et culottes sombres ; taches carpiennes noires sous l’aile.", "Longues ailes, relevées en V en vol plané.", "Fait souvent du surplace."],
    si: "Buse de Chine — plus grande, queue blanchâtre, pattes emplumées. Buse variable — plus petite, queue barrée.",
    h: "Déserts, semi-déserts, collines rocheuses et vallées de montagne sèches.",
    di: "Gobi (Yolyn Am, lac Orog, Böön Tsagaan, Taatsiin Tsagaan) et ouest (lac Khar Us) ; aussi lac Ögii.",
    mi: "Visiteuse d’été, avril–octobre.",
    fo: "Gerbilles, mérions, spermophiles et autres rongeurs ; reptiles et insectes.",
    br: "Niche sur les falaises ou les rochers ; 2 à 4 œufs.",
    be: "Chasse depuis un rocher ou en surplace ; plane au-dessus des collines sèches.",
    v: "Un cri miaulé, plus aigu que celui de la Buse variable.",
    cu: "Réputée la plus agressive des buses.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am et lacs du Gobi en été.",
    bt: "mai–août",
    fa: ["Queue rousse sans barres.", "Vit dans des régions chaudes et sèches.", "Difficile à distinguer de la Buse de Chine."]
  },
  "osprey": {
    name: "Balbuzard pêcheur",
    s: "Rapace pêcheur à tête blanche, bandeau sombre sur l’œil et longues ailes coudées. Il plonge pattes en avant dans les lacs et rivières ; en Mongolie, surtout en migration.",
    d: "Le Balbuzard pêcheur est présent sur tous les continents sauf l’Antarctique. Il se nourrit presque uniquement de poissons, fait du surplace au-dessus de l’eau puis plonge pattes en avant. Son doigt externe réversible et ses soles épineuses l’aident à tenir les poissons glissants. En Mongolie, c’est un visiteur d’été rare et un migrateur sur les lacs et rivières, avec des pics en mai et septembre ; le lac Ögii est l’un des meilleurs sites.",
    f: ["Dessous et tête blancs avec un bandeau sombre à travers l’œil.", "Dessus brun foncé.", "Longues ailes étroites coudées comme celles d’un goéland, taches carpiennes noires.", "Bande pectorale sombre, plus marquée chez la femelle.", "Plonge pattes en avant."],
    si: "Pygargue à queue blanche — bien plus grand, dessous sombre. Grands goélands — sans bandeau sombre, vol différent.",
    h: "Lacs, rivières et réservoirs poissonneux.",
    di: "Lacs du Khangaï (lac Ögii), rivières du Khentii et de la Selenge, lacs de l’ouest et du Gobi en migration.",
    mi: "Migrateur et visiteur d’été rare ; pics en mai et septembre.",
    fo: "Poissons.",
    br: "Grand nid de branches au sommet d’un arbre, sur une falaise ou un pylône ; 2 à 4 œufs.",
    be: "Fait du surplace puis plonge ; transporte le poisson la tête vers l’avant.",
    v: "Une série de sifflements clairs, « kiou-kiou ».",
    cu: "Seul représentant vivant de sa famille, les Pandionidés.",
    co: "Préoccupation mineure ; rétabli après l’interdiction des pesticides.",
    w: "Lac Ögii en mai et septembre.",
    bt: "mai, sept.",
    fa: ["Son doigt externe peut se tourner vers l’arrière.", "Présent sur tous les continents sauf l’Antarctique.", "Porte le poisson tête en avant pour réduire la traînée."]
  }
});
