B2T("en", {
  "lesser-kestrel": {
    T: { c: { rufous: 0.4, gray: 0.3, buff: 0.2, black: 0.1 }, hb: ["steppe", "settlement", "mountain"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["27–33 cm", "58–72 cm", "90–208 g"] },
    s: "A small, colonial falcon; the male has a plain chestnut back and a blue-grey head and tail. A common summer visitor to steppe and Gobi, often hunting insects in groups.",
    d: "The Lesser Kestrel breeds from the Mediterranean to Central Asia, Mongolia and north China and winters in southern Africa. It nests in colonies in cliffs, ruins and buildings and feeds mostly on grasshoppers and beetles, caught on the ground or in the air. In Mongolia it is widespread from April to September, especially in the Gobi and the steppe of Khentii and Töv; colonies are found at Khustai, Ikh Nart and Yolyn Am.",
    f: ["Male: plain unspotted chestnut back, blue-grey head without a moustache, blue-grey panel on the wing.", "Female: rufous-brown with dark barring, very like a female Common Kestrel.", "Pale claws (black in Common Kestrel).", "Slightly wedge-shaped tail with a black band.", "Often in small flocks."],
    si: "Common Kestrel — male has a spotted back and a dark moustache; bigger; usually alone. Amur Falcon — male dark grey with red ‘trousers’.",
    h: "Open steppe and semi-desert with cliffs, ruins or buildings for nesting.",
    di: "Gobi (Yolyn Am, Ikh Nart), central steppe (Khustai), Khentii (Khurkh) and western Mongolia.",
    mi: "Summer visitor, April–September; peak in May.",
    fo: "Grasshoppers, beetles and other large insects; occasionally lizards and small rodents.",
    br: "Colonial; nests in holes in cliffs, walls and roofs; 3–6 eggs.",
    be: "Hunts in loose groups, hovering less than the Common Kestrel; roosts communally.",
    v: "A hoarse, chattering ‘che-che-che’ at the colony.",
    cu: "In the Mediterranean it traditionally nests in church towers and old town walls.",
    co: "Least Concern; declined in Europe but recovered after conservation work.",
    w: "Khustai, Ikh Nart and Yolyn Am, May–August.",
    bt: "May–August",
    fa: ["Nests in colonies.", "Eats mainly insects.", "Winters in southern Africa."]
  },
  "common-kestrel": {
    T: { c: { rufous: 0.4, gray: 0.25, buff: 0.2, black: 0.15 }, hb: ["steppe", "settlement", "mountain", "desert"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["summer", "resident"], sz: ["32–39 cm", "65–82 cm", "136–314 g"] },
    s: "The familiar hovering falcon: chestnut back spotted with black, long tail, and a habit of hanging motionless in the wind. Found all over Mongolia and the most common falcon.",
    d: "The Common Kestrel ranges across Europe, Asia and Africa. It hunts voles, lizards and insects by hovering in the wind and dropping onto prey. In Mongolia it breeds everywhere, from the Altai to Dornod and from the taiga to the Gobi, nesting on cliffs, in trees, old crow nests, buildings and even in gers’ roof gaps. Most leave in autumn, but some winter around Ulaanbaatar and in sheltered valleys.",
    f: ["Male: grey head and grey tail with a black band; chestnut back with black spots.", "Female: brown head and barred brown tail.", "Thin dark moustache below the eye.", "Long pointed wings and long tail.", "Hovers into the wind with fanned tail."],
    si: "Lesser Kestrel — male plain chestnut back, no moustache; usually in groups. Merlin — smaller, no hovering, dashing flight. Eurasian Sparrowhawk — rounded wings.",
    h: "Open country of all kinds: steppe, desert edges, cliffs, towns and forest edges.",
    di: "Throughout Mongolia: Ulaanbaatar, Khustai, Terelj, Khurkh, Khar Us Nuur, Yolyn Am and the eastern steppes.",
    mi: "Mostly a summer visitor (March–October); some winter.",
    fo: "Voles, gerbils, lizards, grasshoppers and beetles; small birds.",
    br: "No nest of its own — uses cliff ledges, holes or old crow nests; 3–6 eggs.",
    be: "Hovers in the wind; perches on poles and wires.",
    v: "A shrill ‘kee-kee-kee’.",
    cu: "Its hovering has earned it the English nickname ‘windhover’.",
    co: "Least Concern.",
    w: "Anywhere in the countryside; look for a small falcon hovering beside the road.",
    bt: "April–September",
    fa: ["Can see ultraviolet light and so follow vole urine trails.", "Does not build its own nest.", "Mongolia’s most common falcon."]
  },
  "red-footed-falcon": {
    T: { c: { gray: 0.6, rufous: 0.15, black: 0.15, buff: 0.1 }, hb: ["steppe"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["28–31 cm", "65–76 cm", "130–197 g"] },
    s: "A small, insect-eating falcon of eastern Europe; the male is dark grey with red ‘trousers’. Known in Mongolia only from very old records — a vagrant.",
    d: "The Red-footed Falcon breeds from eastern Europe to western Siberia and winters in southern Africa. It is very similar to its eastern relative the Amur Falcon, which is common in Mongolia. The few Mongolian records date from the 19th century and may involve confusion with the Amur Falcon.",
    f: ["Male: dark slate grey with chestnut-red thighs and undertail; dark underwing coverts.", "Female: orange crown and underparts, grey barred back.", "Red-orange legs and eye-ring.", "Often hovers."],
    si: "Amur Falcon — male has white underwing coverts; female whiter below with dark streaks.",
    h: "Open steppe with scattered trees.",
    di: "Vagrant; old records in the west.",
    mi: "Very rare.",
    fo: "Large insects, especially dragonflies and beetles.",
    br: "Colonial in rook nests (not in Mongolia).",
    be: "Hunts insects in flight in loose flocks.",
    v: "Chattering ‘kew-kew-kew’.",
    cu: "Its French name kobez comes from a Russian word for this falcon.",
    co: "Vulnerable — loss of rookeries and grassland.",
    w: "Not expected; check all Amur Falcons.",
    bt: "—",
    fa: ["Vulnerable worldwide.", "Nests in old rook nests.", "Closely related to the Amur Falcon."]
  },
  "merlin": {
    T: { c: { gray: 0.3, brown: 0.3, rufous: 0.2, buff: 0.2 }, hb: ["steppe", "forest", "water"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage", "winter"], sz: ["24–33 cm", "50–73 cm", "125–300 g"] },
    s: "A small, compact and very fast falcon that chases small birds low over open ground. Mostly a passage migrant and winter visitor in Mongolia.",
    d: "The Merlin breeds across northern Eurasia and North America in moorland, taiga edges and tundra, and winters farther south. It pursues larks and pipits in fast, low, twisting flight. In Mongolia it may breed in the north but is seen mostly on passage in September–October and in winter, in all regions.",
    f: ["Small, stocky falcon with short pointed wings.", "Male: blue-grey above, orange-buff below with dark streaks.", "Female: brown above, heavily streaked below; tail barred.", "Weak moustache.", "Fast, low, dashing flight — rarely hovers."],
    si: "Common Kestrel — larger, long-tailed, hovers. Eurasian Hobby — longer wings, strong moustache, red thighs. Eurasian Sparrowhawk — rounded wings, yellow eye.",
    h: "Open steppe, river valleys and forest edges.",
    di: "Throughout; Khurkh, Khar Us Nuur, Ulaanbaatar, Khustai, Ögii Nuur and Buir Nuur.",
    mi: "Passage migrant and winter visitor, September–April; peak in September.",
    fo: "Small birds such as larks, pipits and buntings.",
    br: "Nests on the ground or in old crow nests (few Mongolian records); 3–5 eggs.",
    be: "Chases prey in long tail-chases, often only a metre above the ground.",
    v: "A rapid ‘ki-ki-ki’.",
    cu: "In medieval Europe the Merlin was the falcon of noble ladies.",
    co: "Least Concern.",
    w: "Open steppe in September–October and in winter.",
    bt: "September–October",
    fa: ["One of the smallest falcons.", "Hunts birds in tail-chases.", "Once flown by noble ladies."]
  },
  "eurasian-hobby": {
    T: { c: { gray: 0.35, white: 0.25, black: 0.2, rufous: 0.2 }, hb: ["forest", "steppe", "water"], bk: "hooked", bh: ["soar", "perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["29–35 cm", "70–84 cm", "131–340 g"] },
    s: "An elegant, swift-like falcon with long sickle wings, a bold moustache and red ‘trousers’. A summer visitor to forest-steppe and river valleys.",
    d: "The Eurasian Hobby breeds across Europe and Asia and winters in Africa and southern Asia. It is fast enough to catch swallows and swifts in the air, and also takes dragonflies, eating them on the wing. In Mongolia it breeds in wooded areas across the north and in Gobi oases, arriving in May and leaving in September; it is frequently seen at Khurkh, Terelj and around Ulaanbaatar.",
    f: ["Dark slate-grey upperparts.", "Bold black moustache on a white cheek.", "White underparts heavily streaked black.", "Rusty-red thighs and undertail.", "Long, pointed, swift-like wings and a short tail."],
    si: "Peregrine Falcon — larger, heavier, barred below, no red thighs. Amur Falcon — smaller; male plain grey. Merlin — shorter wings, no bold moustache.",
    h: "Forest edges, river valleys with trees, and open country with groves.",
    di: "Khentii and Selenge (Khurkh, Terelj, Ulaanbaatar), Khustai, eastern steppes and Gobi oases.",
    mi: "Summer visitor, May–September; peak in May–June.",
    fo: "Dragonflies and other large insects, swallows, swifts, larks.",
    br: "Uses old crow or magpie nests in trees; 2–3 eggs, timed to feed chicks on young swallows.",
    be: "Hunts in fast flight; eats insects in the air, passing them from foot to bill.",
    v: "A rapid ‘kew-kew-kew’.",
    cu: "Its name comes from Old French hobé, ‘to jump about’.",
    co: "Least Concern.",
    w: "Khurkh valley and Terelj, June–August, over wetlands with dragonflies.",
    bt: "June–August",
    fa: ["Can catch swifts in flight.", "Eats dragonflies on the wing.", "Nests in old crow nests."]
  },
  "gyrfalcon": {
    T: { c: { white: 0.4, gray: 0.35, brown: 0.15, black: 0.1 }, hb: ["steppe", "mountain"], bk: "hooked", bh: ["perch", "soar"], vt: ["screech"], ac: "day", se: ["winter"], sz: ["48–65 cm", "110–130 cm", "0.8–2.1 kg"] },
    s: "The largest falcon in the world, from white to dark grey, breeding in the Arctic. An exceptional winter vagrant to Mongolia with no GBIF records.",
    d: "The Gyrfalcon breeds on Arctic coasts and tundra of Eurasia and North America and hunts ptarmigan, waterfowl and hares. It rarely wanders south; in Mongolia it is known only from a few winter reports, some possibly confused with pale Saker Falcons.",
    f: ["Very large, heavy falcon with broad-based wings and a long tail.", "Colour ranges from almost white to dark grey.", "Weak moustache.", "Slow, powerful wingbeats."],
    si: "Saker Falcon — browner, with a paler head; common in Mongolia. Peregrine Falcon — smaller, strong moustache. Northern Goshawk — rounded wings.",
    h: "Arctic tundra and coasts; in winter, open country.",
    di: "Exceptional winter vagrant.",
    mi: "Winter wanderer.",
    fo: "Ptarmigan, grouse, ducks, hares.",
    br: "Nests on Arctic cliffs (not in Mongolia).",
    be: "Chases prey in long, powerful flights low over the ground.",
    v: "A harsh ‘kyak-kyak’.",
    cu: "In medieval falconry it was reserved for kings.",
    co: "Least Concern.",
    w: "Not expected; check pale falcons in winter.",
    bt: "—",
    fa: ["The world’s largest falcon.", "Once reserved for kings.", "Can be almost pure white."]
  }
});
