B2T("fr", {
  "lesser-kestrel": {
    name: "Faucon crécerellette",
    s: "Petit faucon colonial ; le mâle a le dos roux uni, la tête et la queue gris-bleu. Visiteur d’été commun dans la steppe et le Gobi, chassant souvent les insectes en groupe.",
    d: "Le Faucon crécerellette niche de la Méditerranée à l’Asie centrale, à la Mongolie et au nord de la Chine, et hiverne en Afrique australe. Il niche en colonies dans les falaises, les ruines et les bâtiments et se nourrit surtout de sauterelles et de coléoptères, capturés au sol ou en vol. En Mongolie, il est répandu d’avril à septembre, en particulier dans le Gobi et les steppes du Khentii et du Töv ; on trouve des colonies à Khustai, Ikh Nart et Yolyn Am.",
    f: ["Mâle : dos roux uni sans taches, tête gris-bleu sans moustache, panneau gris-bleu sur l’aile.", "Femelle : brun roux barré de sombre, très semblable à la femelle de crécerelle.", "Griffes pâles (noires chez la crécerelle).", "Queue légèrement cunéiforme à bande noire.", "Souvent en petits groupes."],
    si: "Faucon crécerelle — mâle au dos tacheté et à moustache sombre ; plus grand ; souvent seul. Faucon de l’Amour — mâle gris foncé à « culotte » rouge.",
    h: "Steppe et semi-désert ouverts avec falaises, ruines ou bâtiments pour nicher.",
    di: "Gobi (Yolyn Am, Ikh Nart), steppe centrale (Khustai), Khentii (Khurkh) et ouest.",
    mi: "Visiteur d’été, avril–septembre ; pic en mai.",
    fo: "Sauterelles, coléoptères et autres gros insectes ; parfois lézards et petits rongeurs.",
    br: "Colonial ; niche dans des cavités de falaises, de murs et de toits ; 3 à 6 œufs.",
    be: "Chasse en groupes lâches, fait moins de surplace que la crécerelle ; dortoirs collectifs.",
    v: "Un « tché-tché-tché » rauque à la colonie.",
    cu: "En Méditerranée, il niche traditionnellement dans les clochers et les vieux remparts.",
    co: "Préoccupation mineure ; en déclin en Europe puis rétabli grâce à la conservation.",
    w: "Khustai, Ikh Nart et Yolyn Am, mai–août.",
    bt: "mai–août",
    fa: ["Niche en colonies.", "Mange surtout des insectes.", "Hiverne en Afrique australe."]
  },
  "common-kestrel": {
    name: "Faucon crécerelle",
    s: "Le faucon qui fait du « Saint-Esprit » : dos roux tacheté de noir, longue queue, et l’habitude de rester immobile dans le vent. Présent dans toute la Mongolie, c’est le faucon le plus commun.",
    d: "Le Faucon crécerelle est présent en Europe, en Asie et en Afrique. Il chasse campagnols, lézards et insectes en faisant du surplace face au vent puis en se laissant tomber sur sa proie. En Mongolie, il niche partout, de l’Altaï au Dornod et de la taïga au Gobi, sur les falaises, dans les arbres, les vieux nids de corvidés, les bâtiments et même les interstices des toits de yourtes. La plupart partent à l’automne, mais certains hivernent autour d’Oulan-Bator et dans les vallées abritées.",
    f: ["Mâle : tête grise et queue grise à bande noire ; dos roux tacheté de noir.", "Femelle : tête brune et queue brune barrée.", "Fine moustache sombre sous l’œil.", "Longues ailes pointues et longue queue.", "Fait du surplace face au vent, queue étalée."],
    si: "Faucon crécerellette — mâle au dos roux uni, sans moustache ; souvent en groupe. Faucon émerillon — plus petit, ne fait pas de surplace, vol fougueux. Épervier d’Europe — ailes arrondies.",
    h: "Tous milieux ouverts : steppe, bordures de désert, falaises, villes et lisières.",
    di: "Toute la Mongolie : Oulan-Bator, Khustai, Terelj, Khurkh, lac Khar Us, Yolyn Am et steppes de l’est.",
    mi: "Surtout visiteur d’été (mars–octobre) ; quelques hivernants.",
    fo: "Campagnols, gerbilles, lézards, sauterelles et coléoptères ; petits oiseaux.",
    br: "Ne construit pas de nid — utilise corniches, cavités ou vieux nids de corvidés ; 3 à 6 œufs.",
    be: "Fait du surplace ; se pose sur les poteaux et les fils.",
    v: "Un « kii-kii-kii » aigu.",
    cu: "Son surplace lui vaut le surnom de « Saint-Esprit » en français.",
    co: "Préoccupation mineure.",
    w: "Partout dans la campagne ; cherchez un petit faucon en surplace au bord de la route.",
    bt: "avril–sept.",
    fa: ["Voit l’ultraviolet et suit ainsi les traces d’urine des campagnols.", "Ne construit pas son nid.", "Le faucon le plus commun de Mongolie."]
  },
  "red-footed-falcon": {
    name: "Faucon kobez",
    s: "Petit faucon insectivore d’Europe de l’Est ; le mâle est gris foncé à « culotte » rouge. Connu en Mongolie seulement par de très anciennes mentions — erratique.",
    d: "Le Faucon kobez niche de l’Europe de l’Est à la Sibérie occidentale et hiverne en Afrique australe. Il ressemble beaucoup à son cousin oriental, le Faucon de l’Amour, commun en Mongolie. Les rares mentions mongoles datent du XIXᵉ siècle et pourraient résulter d’une confusion avec ce dernier.",
    f: ["Mâle : gris ardoise foncé, culottes et sous-caudales rouge brique ; couvertures sous-alaires sombres.", "Femelle : calotte et dessous orangés, dos gris barré.", "Pattes et cercle orbital rouge orangé.", "Fait souvent du surplace."],
    si: "Faucon de l’Amour — mâle aux couvertures sous-alaires blanches ; femelle plus blanche dessous, striée de sombre.",
    h: "Steppes ouvertes parsemées d’arbres.",
    di: "Erratique ; anciennes mentions dans l’ouest.",
    mi: "Très rare.",
    fo: "Gros insectes, surtout libellules et coléoptères.",
    br: "Colonial dans les nids de Corbeaux freux (pas en Mongolie).",
    be: "Chasse les insectes en vol en groupes lâches.",
    v: "Un « kiou-kiou-kiou » jacassant.",
    cu: "Son nom « kobez » vient d’un mot russe désignant ce faucon.",
    co: "Vulnérable — disparition des corbeautières et des prairies.",
    w: "Non attendu ; examinez tous les Faucons de l’Amour.",
    bt: "—",
    fa: ["Vulnérable à l’échelle mondiale.", "Niche dans de vieux nids de freux.", "Proche parent du Faucon de l’Amour."]
  },
  "merlin": {
    name: "Faucon émerillon",
    s: "Petit faucon trapu et très rapide qui poursuit les petits oiseaux au ras du sol. En Mongolie, surtout migrateur et hivernant.",
    d: "Le Faucon émerillon niche dans le nord de l’Eurasie et de l’Amérique du Nord, dans les landes, les lisières de taïga et la toundra, et hiverne plus au sud. Il poursuit alouettes et pipits en vol rapide, bas et sinueux. En Mongolie, il niche peut-être dans le nord mais se voit surtout en migration en septembre–octobre et en hiver, dans toutes les régions.",
    f: ["Petit faucon trapu aux ailes courtes et pointues.", "Mâle : gris-bleu dessus, chamois orangé strié dessous.", "Femelle : brune dessus, fortement striée dessous ; queue barrée.", "Moustache faible.", "Vol rapide, bas et fougueux — fait rarement du surplace."],
    si: "Faucon crécerelle — plus grand, longue queue, fait du surplace. Faucon hobereau — ailes plus longues, moustache nette, culotte rousse. Épervier d’Europe — ailes arrondies, œil jaune.",
    h: "Steppe ouverte, vallées et lisières.",
    di: "Partout ; Khurkh, lac Khar Us, Oulan-Bator, Khustai, lac Ögii et lac Buir.",
    mi: "Migrateur et hivernant, septembre–avril ; pic en septembre.",
    fo: "Petits oiseaux : alouettes, pipits, bruants.",
    br: "Niche au sol ou dans de vieux nids de corvidés (peu de mentions en Mongolie) ; 3 à 5 œufs.",
    be: "Poursuit ses proies longuement, souvent à un mètre du sol.",
    v: "Un « ki-ki-ki » rapide.",
    cu: "Au Moyen Âge, c’était le faucon des dames de la noblesse.",
    co: "Préoccupation mineure.",
    w: "Steppes ouvertes en septembre–octobre et en hiver.",
    bt: "sept.–oct.",
    fa: ["L’un des plus petits faucons.", "Chasse les oiseaux en poursuite.", "Faucon des dames au Moyen Âge."]
  },
  "eurasian-hobby": {
    name: "Faucon hobereau",
    s: "Faucon élégant, rappelant un martinet, aux longues ailes en faucille, à la moustache marquée et à la « culotte » rousse. Visiteur d’été de la steppe boisée et des vallées.",
    d: "Le Faucon hobereau niche en Europe et en Asie et hiverne en Afrique et en Asie du Sud. Assez rapide pour attraper hirondelles et martinets en vol, il capture aussi des libellules qu’il mange en volant. En Mongolie, il niche dans les zones boisées du nord et les oasis du Gobi, arrive en mai et repart en septembre ; on le voit souvent à Khurkh, à Terelj et autour d’Oulan-Bator.",
    f: ["Dessus gris ardoise foncé.", "Moustache noire marquée sur une joue blanche.", "Dessous blanc fortement strié de noir.", "Culotte et sous-caudales rouille.", "Longues ailes pointues de martinet, queue courte."],
    si: "Faucon pèlerin — plus grand et lourd, barré dessous, sans culotte rousse. Faucon de l’Amour — plus petit ; mâle gris uni. Faucon émerillon — ailes plus courtes, sans moustache marquée.",
    h: "Lisières, vallées arborées et milieux ouverts avec bosquets.",
    di: "Khentii et Selenge (Khurkh, Terelj, Oulan-Bator), Khustai, steppes de l’est et oasis du Gobi.",
    mi: "Visiteur d’été, mai–septembre ; pic en mai–juin.",
    fo: "Libellules et autres gros insectes, hirondelles, martinets, alouettes.",
    br: "Utilise de vieux nids de corvidés ou de pies ; 2 ou 3 œufs, les jeunes éclosant avec les jeunes hirondelles.",
    be: "Chasse en vol rapide ; mange les insectes en vol en les passant de la patte au bec.",
    v: "Un « kiou-kiou-kiou » rapide.",
    cu: "Son nom vient du vieux français hobé, « sautiller ».",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh et Terelj, juin–août, au-dessus des zones humides riches en libellules.",
    bt: "juin–août",
    fa: ["Peut capturer des martinets en vol.", "Mange les libellules en volant.", "Niche dans de vieux nids de corvidés."]
  },
  "gyrfalcon": {
    name: "Faucon gerfaut",
    s: "Le plus grand faucon du monde, du blanc au gris foncé, nicheur arctique. Erratique hivernal exceptionnel en Mongolie, sans mention GBIF.",
    d: "Le Faucon gerfaut niche sur les côtes et la toundra arctiques d’Eurasie et d’Amérique du Nord et chasse lagopèdes, oiseaux d’eau et lièvres. Il descend rarement vers le sud ; en Mongolie, il n’est connu que par quelques observations hivernales, peut-être confondues avec des Faucons sacres pâles.",
    f: ["Très grand faucon lourd, ailes larges à la base et longue queue.", "Couleur du presque blanc au gris foncé.", "Moustache faible.", "Battements lents et puissants."],
    si: "Faucon sacre — plus brun, tête plus pâle ; commun en Mongolie. Faucon pèlerin — plus petit, moustache marquée. Autour des palombes — ailes arrondies.",
    h: "Toundra et côtes arctiques ; en hiver, milieux ouverts.",
    di: "Erratique hivernal exceptionnel.",
    mi: "Erratique en hiver.",
    fo: "Lagopèdes, tétras, canards, lièvres.",
    br: "Niche sur les falaises arctiques (pas en Mongolie).",
    be: "Poursuit ses proies en longs vols puissants au ras du sol.",
    v: "Un « kyak-kyak » rauque.",
    cu: "Dans la fauconnerie médiévale, il était réservé aux rois.",
    co: "Préoccupation mineure.",
    w: "Non attendu ; examinez les faucons pâles en hiver.",
    bt: "—",
    fa: ["Le plus grand faucon du monde.", "Autrefois réservé aux rois.", "Peut être presque entièrement blanc."]
  }
});
