B2T("en", {
  "hawk-owl": {
    T: { c: { gray: 0.35, white: 0.35, brown: 0.2, black: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["36–41 cm", "69–82 cm", "215–380 g"] },
    s: "A long-tailed, hawk-like owl of the northern taiga that hunts by day from treetops. A rare resident of Mongolia’s northern forests.",
    d: "The Northern Hawk Owl lives in the boreal forests of Eurasia and North America. With its long tail and pointed wings it looks and flies like a sparrowhawk, and it hunts voles in daylight from the tip of a tree. In Mongolia it is a rare bird of the larch taiga of Khövsgöl, the Khentii and the northern Khangai; numbers rise in years with many voles.",
    f: ["Long, graduated tail — unusual for an owl.", "Grey-brown above with white spots; white below with fine dark barring.", "White face framed by bold black ‘sideburns’.", "Yellow eyes; no ear tufts.", "Perches upright on treetops in daylight, often flicking its tail."],
    si: "Eurasian Sparrowhawk — has yellow legs and a hawk face, but no facial disc. Tengmalm’s Owl — much smaller, short tail, nocturnal.",
    h: "Open larch and spruce taiga, burnt forest and bogs.",
    di: "Khövsgöl, Khentii and northern Khangai forests.",
    mi: "Resident; wanders in years when voles are scarce.",
    fo: "Voles and other small rodents; small birds in winter.",
    br: "Nests in tree hollows or broken trunks; clutch size depends on vole numbers.",
    be: "Active in daylight; hovers briefly and dives on prey.",
    v: "A rolling, trilling ‘ulululu’ in spring.",
    cu: "Can detect voles under snow by hearing.",
    co: "Least Concern.",
    w: "Larch taiga around Khövsgöl Nuur; scan the tops of dead trees.",
    bt: "March–July",
    fa: ["Hunts by day.", "Looks like a hawk.", "Numbers follow vole cycles."]
  },
  "eurasian-pygmy-owl": {
    T: { c: { brown: 0.5, white: 0.3, gray: 0.2 }, hb: ["forest"], bk: "hooked", bh: ["perch", "night"], vt: ["whistle"], ac: "night", se: ["resident"], sz: ["15–19 cm", "32–39 cm", "47–83 g"] },
    s: "The smallest owl of Europe and northern Asia — sparrow-sized, with a fierce look. A rare resident of the northern conifer forests, recorded around Terelj and Ulaanbaatar.",
    d: "The Eurasian Pygmy Owl lives in mature conifer forests from Scandinavia to the Russian Far East. Despite its size it catches birds as big as itself. It is active at dawn and dusk and stores food in tree holes for the winter. In Mongolia it occurs in the forests of the Khentii (Terelj, Bogd Khan Uul) and the Khangai.",
    f: ["Tiny, round-headed owl.", "Brown with white spots above; streaked below.", "Small yellow eyes under white ‘eyebrows’.", "Tail often cocked and flicked.", "Two dark ‘false eyes’ on the back of the head."],
    si: "Tengmalm’s Owl — larger, with a big pale facial disc. Little Owl — lives in open country, not forest.",
    h: "Mature spruce, pine and larch forest.",
    di: "Khentii (Terelj, Bogd Khan Uul near Ulaanbaatar, Khurkh), Khangai.",
    mi: "Resident.",
    fo: "Small birds and voles.",
    br: "Uses old woodpecker holes; 3–7 eggs.",
    be: "Active at twilight; stores prey in tree holes in winter.",
    v: "A soft, repeated whistle ‘hjuu … hjuu’, often imitated to attract songbirds.",
    cu: "Songbirds mob it noisily — a useful sign of its presence.",
    co: "Least Concern.",
    w: "Bogd Khan Uul and Terelj forests at dusk in early spring.",
    bt: "February–April",
    fa: ["No bigger than a sparrow.", "Has ‘false eyes’ on the back of its head.", "Stores food for winter."]
  },
  "tengmalms-owl": {
    T: { c: { brown: 0.5, white: 0.35, buff: 0.15 }, hb: ["forest"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["resident"], sz: ["22–27 cm", "50–62 cm", "90–200 g"] },
    s: "A small, big-headed forest owl with a pale ‘surprised’ face and yellow eyes. A strictly nocturnal resident of northern and western Mongolia’s conifer forests.",
    d: "Tengmalm’s (Boreal) Owl lives in the boreal and mountain forests of Eurasia and North America. It nests in old woodpecker holes, especially those of the Black Woodpecker. In Mongolia it is found in the forests of the Khangai, Khövsgöl and Altai, but is rarely seen because it is active only at night.",
    f: ["Large square head with a pale facial disc edged in black.", "Raised ‘eyebrows’ give a surprised look.", "Brown with white spots above.", "Yellow eyes.", "Feathered feet."],
    si: "Eurasian Pygmy Owl — much smaller, small head. Little Owl — flatter head, lives in open country.",
    h: "Old spruce, larch and pine forest.",
    di: "Khangai (Terkhiin Tsagaan Nuur area), Khövsgöl, Altai.",
    mi: "Resident; young birds disperse.",
    fo: "Voles, shrews and small birds.",
    br: "Nests in woodpecker holes; 3–7 eggs.",
    be: "Strictly nocturnal; hunts from low perches.",
    v: "A rapid series of soft hoots ‘po-po-po-po-po’.",
    cu: "Named after the Swedish naturalist Peter Gustaf Tengmalm.",
    co: "Least Concern.",
    w: "Listen for its song on still nights in March–April.",
    bt: "March–April",
    fa: ["Depends on Black Woodpecker holes.", "Named after a Swedish naturalist.", "Its ears are asymmetric for precise hearing."]
  },
  "eurasian-scops-owl": {
    T: { c: { gray: 0.45, brown: 0.35, buff: 0.2 }, hb: ["forest", "settlement"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["summer"], sz: ["19–21 cm", "47–54 cm", "60–135 g"] },
    s: "A tiny eared owl with bark-like plumage and a monotonous ‘tyoo’ call. A scarce summer visitor, mainly to western Mongolia.",
    d: "The Eurasian Scops Owl breeds from southern Europe to Central Asia and winters in Africa. It feeds mainly on large insects. In Mongolia it is found in riverine woods and settlements in the west (Khovd, Khar Us Nuur) and occasionally elsewhere, from May to September.",
    f: ["Very small owl with short ear tufts.", "Grey-brown, finely patterned like tree bark.", "Yellow eyes.", "Slim; can stretch itself to look like a branch.", "Long wings for a migrant owl."],
    si: "Oriental (East Asian) Scops Owl — very similar; best told by call. Little Owl — no ear tufts, rounder.",
    h: "Open woodland, poplar and willow groves along rivers, parks and villages.",
    di: "Mainly western Mongolia (Khovd, Khar Us Nuur); also Khangai and occasionally near Ulaanbaatar.",
    mi: "Summer visitor, May–September.",
    fo: "Moths, grasshoppers, crickets and beetles; sometimes small rodents.",
    br: "Nests in tree holes or crevices; 3–5 eggs.",
    be: "Nocturnal; sings for hours from a hidden perch.",
    v: "A single, soft, repeated ‘tyoo’ every 2–3 seconds.",
    cu: "Its call is a familiar sound of summer nights in the Mediterranean.",
    co: "Least Concern.",
    w: "Listen at dusk in riverside groves around Khovd in June.",
    bt: "June–July",
    fa: ["Feeds mainly on insects.", "Camouflaged like tree bark.", "Migrates to Africa."]
  },
  "east-asian-scops-owl": {
    T: { c: { gray: 0.4, brown: 0.35, rufous: 0.15, buff: 0.1 }, hb: ["forest"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["passage", "summer"], sz: ["18–21 cm", "45–50 cm", "75–95 g"] },
    s: "The eastern counterpart of the Scops Owl, with a three- or four-note call. A rare summer visitor and migrant in eastern and northern Mongolia.",
    d: "The Oriental (East Asian) Scops Owl breeds from south-east Siberia and north-east China to Korea and Japan and winters in South-East Asia. It has grey and rufous colour forms. In Mongolia there are few records, from the east, the Khentii and occasionally the Gobi on migration.",
    f: ["Very small eared owl.", "Grey or rufous, bark-patterned.", "Yellow eyes.", "Pale scapular line on the shoulders."],
    si: "Eurasian Scops Owl — almost identical; its call is a single note.",
    h: "Deciduous and mixed forest, river woodland.",
    di: "Rare; eastern Mongolia, Khentii (Terelj, Khurkh), Gobi on migration.",
    mi: "Summer visitor and migrant, May–September.",
    fo: "Large insects.",
    br: "Nests in tree holes; 3–5 eggs.",
    be: "Nocturnal and hidden by day.",
    v: "A rhythmic ‘tok-tototok’ of three or four notes.",
    cu: "In Japan its call is said to sound like ‘Buppōsō’ — ‘Buddha, law, monk’.",
    co: "Least Concern.",
    w: "Listen in river woods of Khentii in June.",
    bt: "June",
    fa: ["Has grey and rufous forms.", "Best identified by call.", "Migrates to South-East Asia."]
  },
  "long-eared-owl": {
    T: { c: { brown: 0.45, buff: 0.3, rufous: 0.15, black: 0.1 }, hb: ["forest", "steppe", "desert"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["summer", "passage"], sz: ["35–40 cm", "90–100 cm", "220–435 g"] },
    s: "A slim, orange-eyed owl with long ear tufts. Found across Mongolia wherever there are trees, including Gobi oases on migration.",
    d: "The Long-eared Owl breeds across Europe, Asia and North America. It nests in old crow and magpie nests and hunts voles over open ground at night. In winter it often roosts communally in dense trees. In Mongolia it breeds in woods and groves in the north and east and is common on migration in the Gobi, for example at Yolyn Am.",
    f: ["Long ear tufts, often raised when alarmed.", "Bright orange eyes.", "Orange-buff facial disc with a white ‘X’ between the eyes.", "Streaked buff-brown body.", "Slim; stretches itself upright when disturbed."],
    si: "Short-eared Owl — tiny ear tufts, yellow eyes, open country. Eurasian Eagle-Owl — much larger.",
    h: "Woods, groves and shelterbelts beside open ground; oases on migration.",
    di: "Khentii (Khurkh, Terelj), Ulaanbaatar, eastern Mongolia (Ganga Nuur), Gobi (Yolyn Am).",
    mi: "Summer visitor and migrant; peaks in April–May and September; some winter.",
    fo: "Voles and mice; some small birds.",
    br: "Uses old crow or magpie nests; 4–6 eggs.",
    be: "Nocturnal; roosts pressed against a tree trunk.",
    v: "A low, soft ‘hoo’ every few seconds; young birds squeak like a gate hinge.",
    cu: "Its ear tufts are feathers, not ears.",
    co: "Least Concern.",
    w: "Gobi oases (Yolyn Am) during migration; check dense trees for roosting birds.",
    bt: "April–May, September",
    fa: ["The ‘ears’ are just feathers.", "Nests in old crow nests.", "Roosts communally in winter."]
  },
  "short-eared-owl": {
    T: { c: { buff: 0.45, brown: 0.35, white: 0.2 }, hb: ["steppe", "water"], bk: "hooked", bh: ["soar", "perch"], vt: ["silent"], ac: "day", se: ["summer", "passage"], sz: ["34–42 cm", "85–110 cm", "200–500 g"] },
    s: "A pale, open-country owl that flies low over grassland in daylight with slow, moth-like wingbeats. Found across Mongolia’s steppes and marshes.",
    d: "The Short-eared Owl is one of the most widespread owls in the world. It lives in grasslands, marshes and tundra and nests on the ground. It is often active in the day, especially at dusk, quartering like a harrier. In Mongolia it breeds in wet meadows and steppe, notably in the Khurkh valley and around Buir Nuur, and passes through in September.",
    f: ["Pale buff with brown streaks.", "Yellow eyes set in black patches — a fierce look.", "Tiny ear tufts, usually invisible.", "Long wings with dark wrist patches and barred tips.", "Flies low with stiff, rowing wingbeats."],
    si: "Long-eared Owl — orange eyes, long ear tufts, forests. Harriers — slimmer, long tails, no round face.",
    h: "Steppe, wet meadows, marshes and open country.",
    di: "Khentii (Khurkh), Dornod (Buir Nuur), western lakes and Gobi on migration.",
    mi: "Summer visitor and migrant; most records in September.",
    fo: "Voles and other small rodents.",
    br: "Nests on the ground in tall grass; 4–8 eggs, more in vole years.",
    be: "Hunts by quartering low; claps its wings in display flight.",
    v: "Mostly silent; a barking ‘kee-aw’ near the nest.",
    cu: "One of the few owls found on every continent except Australia and Antarctica.",
    co: "Least Concern.",
    w: "Khurkh valley meadows at dusk, June–September.",
    bt: "June–September",
    fa: ["Hunts in daylight.", "Nests on the ground.", "Found on five continents."]
  },
  "ural-owl": {
    T: { c: { gray: 0.45, white: 0.3, brown: 0.25 }, hb: ["forest"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["resident"], sz: ["50–62 cm", "110–134 cm", "0.5–1.3 kg"] },
    s: "A large, pale grey forest owl with a round face and small dark eyes. A rare resident of the Khentii and Khangai forests.",
    d: "The Ural Owl lives in the old forests of northern Eurasia from Scandinavia to Japan. It is fearless in defending its nest and may attack people who come too close. In Mongolia it occurs in the mountain forests of the Khentii (Bogd Khan Uul, Terelj) and the Khangai (Orkhon valley).",
    f: ["Large, pale grey-brown owl with a long tail.", "Round, plain pale face with no ear tufts.", "Small dark eyes.", "Streaked below.", "Yellowish bill."],
    si: "Great Grey Owl — larger, with concentric rings on the face and yellow eyes. Eurasian Eagle-Owl — ear tufts, orange eyes.",
    h: "Mature mixed and coniferous forest with clearings.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khangai (Orkhon valley).",
    mi: "Resident.",
    fo: "Voles, mice, squirrels and birds.",
    br: "Nests in broken trunks, large holes or old raptor nests; 2–4 eggs.",
    be: "Nocturnal; fiercely defends its nest.",
    v: "A deep ‘wooho … woohuhoo’.",
    cu: "Called the ‘long-tailed owl’ in some languages.",
    co: "Least Concern.",
    w: "Bogd Khan Uul forests; listen at night in spring.",
    bt: "March–June",
    fa: ["Attacks intruders at the nest.", "Has dark eyes.", "Lives in old forests."]
  },
  "great-grey-owl": {
    T: { c: { gray: 0.65, white: 0.2, black: 0.15 }, hb: ["forest"], bk: "hooked", bh: ["perch", "night"], vt: ["hoot"], ac: "night", se: ["resident"], sz: ["61–84 cm", "128–153 cm", "0.6–1.9 kg"] },
    s: "A huge, grey owl with a giant face of concentric rings, yellow eyes and a white ‘bow tie’. A very rare resident of the northern taiga, with a single GBIF record.",
    d: "The Great Grey Owl is the tallest owl in the world, though much of its bulk is feathers. It lives in the boreal forests of Eurasia and North America and can hear voles under deep snow. In Mongolia it is known from the taiga of Khövsgöl and the northern Khangai, but records are very few.",
    f: ["Very large, all grey owl.", "Enormous facial disc with concentric rings.", "Small yellow eyes.", "White ‘moustache’ or bow tie under the bill.", "No ear tufts."],
    si: "Ural Owl — smaller, plain face, dark eyes. Eurasian Eagle-Owl — ear tufts, orange eyes.",
    h: "Old boreal forest near bogs and clearings.",
    di: "Very rare; Khövsgöl and northern Khangai taiga.",
    mi: "Resident; may move in poor vole years.",
    fo: "Voles, which it catches by plunging into the snow.",
    br: "Nests in old raptor nests or broken trunks; 3–5 eggs.",
    be: "Hunts by listening from a low perch, often in daylight.",
    v: "A slow series of very deep hoots.",
    cu: "Known as the ‘phantom of the north’.",
    co: "Least Concern.",
    w: "Rarely seen; taiga clearings around Khövsgöl.",
    bt: "—",
    fa: ["The world’s tallest owl.", "Hears voles under deep snow.", "Mostly feathers — weighs less than it looks."]
  },
  "snowy-owl": {
    T: { c: { white: 0.8, black: 0.1, brown: 0.1 }, hb: ["steppe"], bk: "hooked", bh: ["perch"], vt: ["silent"], ac: "day", se: ["winter"], sz: ["52–71 cm", "125–150 cm", "1.6–3 kg"] },
    s: "A large white Arctic owl with yellow eyes. A very rare winter visitor to Mongolia with no GBIF records.",
    d: "The Snowy Owl breeds on the Arctic tundra and hunts lemmings. In winters when lemmings crash, some move far south. It has been reported in northern Mongolia only a handful of times. It is classed as Vulnerable because its population appears to have declined.",
    f: ["Mostly white; females and young barred with black-brown.", "Round head without ear tufts.", "Yellow eyes.", "Heavily feathered feet.", "Often sits on the ground."],
    si: "No other white owl occurs in Mongolia; a pale Gyrfalcon has pointed wings.",
    h: "Arctic tundra; in winter, open steppe.",
    di: "Very rare winter visitor in the north.",
    mi: "Irruptive winter wanderer.",
    fo: "Lemmings, voles, hares and birds.",
    br: "Nests on the tundra (not in Mongolia).",
    be: "Active by day; sits on mounds in open country.",
    v: "Mostly silent in winter.",
    cu: "Made famous by Hedwig in the Harry Potter books.",
    co: "Vulnerable.",
    w: "Not expected.",
    bt: "—",
    fa: ["Active in daylight.", "Vulnerable worldwide.", "Can eat over 1,500 lemmings a year."]
  }
});
