B2T("fr", {
  "hawk-owl": {
    name: "Chouette épervière",
    s: "Chouette à longue queue, rappelant un épervier, de la taïga septentrionale, qui chasse de jour depuis la cime des arbres. Résidente rare des forêts du nord de la Mongolie.",
    d: "La Chouette épervière vit dans les forêts boréales d’Eurasie et d’Amérique du Nord. Avec sa longue queue et ses ailes pointues, elle ressemble à un épervier et vole comme lui ; elle chasse les campagnols en plein jour depuis la pointe d’un arbre. En Mongolie, elle est rare dans la taïga de mélèzes du Khövsgöl, du Khentii et du nord du Khangaï ; ses effectifs augmentent les années à campagnols.",
    f: ["Longue queue étagée — inhabituelle chez une chouette.", "Gris-brun dessus tacheté de blanc ; blanc dessous finement barré.", "Face blanche encadrée de « favoris » noirs.", "Yeux jaunes ; pas d’aigrettes.", "Se tient droite à la cime des arbres en plein jour, agitant la queue."],
    si: "Épervier d’Europe — pattes jaunes, tête de rapace, sans disque facial. Chouette de Tengmalm — bien plus petite, queue courte, nocturne.",
    h: "Taïga claire de mélèzes et d’épicéas, forêts brûlées et tourbières.",
    di: "Forêts du Khövsgöl, du Khentii et du nord du Khangaï.",
    mi: "Résidente ; erratique les années pauvres en campagnols.",
    fo: "Campagnols et autres petits rongeurs ; petits oiseaux en hiver.",
    br: "Niche dans des cavités ou des troncs brisés ; la ponte dépend des campagnols.",
    be: "Active de jour ; fait un bref surplace puis plonge sur sa proie.",
    v: "Un trille roulé « ululululu » au printemps.",
    cu: "Repère les campagnols sous la neige à l’oreille.",
    co: "Préoccupation mineure.",
    w: "Taïga de mélèzes autour du lac Khövsgöl ; scrutez la cime des arbres morts.",
    bt: "mars–juil.",
    fa: ["Chasse de jour.", "Ressemble à un épervier.", "Ses effectifs suivent les cycles des campagnols."]
  },
  "eurasian-pygmy-owl": {
    name: "Chevêchette d’Europe",
    s: "La plus petite chouette d’Europe et d’Asie du Nord — de la taille d’un moineau, à l’air farouche. Résidente rare des forêts de conifères du nord, notée à Terelj et près d’Oulan-Bator.",
    d: "La Chevêchette d’Europe vit dans les forêts de conifères matures, de la Scandinavie à l’Extrême-Orient russe. Malgré sa taille, elle capture des oiseaux aussi gros qu’elle. Active à l’aube et au crépuscule, elle stocke de la nourriture dans des cavités pour l’hiver. En Mongolie, elle fréquente les forêts du Khentii (Terelj, Bogd Khan Uul) et du Khangaï.",
    f: ["Minuscule chouette à tête ronde.", "Brune tachetée de blanc dessus ; striée dessous.", "Petits yeux jaunes sous des « sourcils » blancs.", "Queue souvent relevée et agitée.", "Deux « faux yeux » sombres à l’arrière de la tête."],
    si: "Chouette de Tengmalm — plus grande, grand disque facial pâle. Chevêche d’Athéna — milieux ouverts, pas la forêt.",
    h: "Forêts matures d’épicéas, de pins et de mélèzes.",
    di: "Khentii (Terelj, Bogd Khan Uul près d’Oulan-Bator, Khurkh), Khangaï.",
    mi: "Résidente.",
    fo: "Petits oiseaux et campagnols.",
    br: "Utilise d’anciennes loges de pics ; 3 à 7 œufs.",
    be: "Crépusculaire ; stocke ses proies dans des cavités en hiver.",
    v: "Un sifflement doux et répété « hjou … hjou », souvent imité pour attirer les passereaux.",
    cu: "Les passereaux la houspillent bruyamment — un bon indice de sa présence.",
    co: "Préoccupation mineure.",
    w: "Forêts du Bogd Khan Uul et de Terelj au crépuscule, au début du printemps.",
    bt: "févr.–avril",
    fa: ["Pas plus grande qu’un moineau.", "Porte de « faux yeux » sur la nuque.", "Fait des réserves pour l’hiver."]
  },
  "tengmalms-owl": {
    name: "Chouette de Tengmalm",
    s: "Petite chouette forestière à grosse tête, à la face pâle « étonnée » et aux yeux jaunes. Résidente strictement nocturne des forêts de conifères du nord et de l’ouest de la Mongolie.",
    d: "La Chouette de Tengmalm vit dans les forêts boréales et montagnardes d’Eurasie et d’Amérique du Nord. Elle niche dans d’anciennes loges de pics, surtout celles du Pic noir. En Mongolie, on la trouve dans les forêts du Khangaï, du Khövsgöl et de l’Altaï, mais on la voit rarement car elle n’est active que la nuit.",
    f: ["Grosse tête carrée avec un disque facial pâle bordé de noir.", "« Sourcils » relevés donnant un air étonné.", "Brune tachetée de blanc dessus.", "Yeux jaunes.", "Pattes emplumées."],
    si: "Chevêchette d’Europe — bien plus petite, petite tête. Chevêche d’Athéna — tête plus plate, milieux ouverts.",
    h: "Vieilles forêts d’épicéas, de mélèzes et de pins.",
    di: "Khangaï (région de Terkhiin Tsagaan Nuur), Khövsgöl, Altaï.",
    mi: "Résidente ; les jeunes se dispersent.",
    fo: "Campagnols, musaraignes et petits oiseaux.",
    br: "Niche dans des loges de pics ; 3 à 7 œufs.",
    be: "Strictement nocturne ; chasse depuis des perchoirs bas.",
    v: "Une série rapide de doux « po-po-po-po-po ».",
    cu: "Nommée d’après le naturaliste suédois Peter Gustaf Tengmalm.",
    co: "Préoccupation mineure.",
    w: "Écoutez son chant par nuits calmes en mars–avril.",
    bt: "mars–avril",
    fa: ["Dépend des loges du Pic noir.", "Porte le nom d’un naturaliste suédois.", "Ses oreilles asymétriques permettent une écoute précise."]
  },
  "eurasian-scops-owl": {
    name: "Petit-duc scops",
    s: "Minuscule hibou à aigrettes, au plumage d’écorce et au chant monotone « tiou ». Visiteur d’été peu commun, surtout dans l’ouest de la Mongolie.",
    d: "Le Petit-duc scops niche de l’Europe du Sud à l’Asie centrale et hiverne en Afrique. Il se nourrit surtout de gros insectes. En Mongolie, il fréquente de mai à septembre les bois riverains et les villages de l’ouest (Khovd, lac Khar Us), et parfois d’autres régions.",
    f: ["Très petit hibou à courtes aigrettes.", "Gris-brun finement dessiné comme de l’écorce.", "Yeux jaunes.", "Fin ; peut s’étirer pour ressembler à une branche.", "Ailes longues pour un rapace nocturne migrateur."],
    si: "Petit-duc d’Orient — très semblable ; se distingue au chant. Chevêche d’Athéna — sans aigrettes, plus ronde.",
    h: "Bois clairs, peupleraies et saulaies riveraines, parcs et villages.",
    di: "Surtout l’ouest (Khovd, lac Khar Us) ; aussi le Khangaï et parfois près d’Oulan-Bator.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Papillons de nuit, sauterelles, grillons et coléoptères ; parfois petits rongeurs.",
    br: "Niche dans des cavités d’arbres ou des fissures ; 3 à 5 œufs.",
    be: "Nocturne ; chante des heures depuis un perchoir caché.",
    v: "Un « tiou » doux et unique, répété toutes les 2–3 secondes.",
    cu: "Son chant est un son familier des nuits d’été méditerranéennes.",
    co: "Préoccupation mineure.",
    w: "Écoutez au crépuscule dans les bosquets riverains autour de Khovd en juin.",
    bt: "juin–juil.",
    fa: ["Se nourrit surtout d’insectes.", "Camouflé comme de l’écorce.", "Migre en Afrique."]
  },
  "east-asian-scops-owl": {
    name: "Petit-duc d’Orient",
    s: "Le pendant oriental du Petit-duc scops, au chant de trois ou quatre notes. Visiteur d’été et migrateur rare dans l’est et le nord de la Mongolie.",
    d: "Le Petit-duc d’Orient niche du sud-est de la Sibérie et du nord-est de la Chine jusqu’en Corée et au Japon, et hiverne en Asie du Sud-Est. Il existe des formes grise et rousse. En Mongolie, les mentions sont rares, dans l’est, le Khentii et parfois le Gobi en migration.",
    f: ["Très petit hibou à aigrettes.", "Gris ou roux, dessiné comme de l’écorce.", "Yeux jaunes.", "Ligne scapulaire pâle sur l’épaule."],
    si: "Petit-duc scops — presque identique ; son chant est d’une seule note.",
    h: "Forêts feuillues et mixtes, bois riverains.",
    di: "Rare ; est de la Mongolie, Khentii (Terelj, Khurkh), Gobi en migration.",
    mi: "Visiteur d’été et migrateur, mai–septembre.",
    fo: "Gros insectes.",
    br: "Niche dans des cavités d’arbres ; 3 à 5 œufs.",
    be: "Nocturne, caché le jour.",
    v: "Un « tok-tototok » rythmé de trois ou quatre notes.",
    cu: "Au Japon, on dit que son chant fait « Buppōsō » — « Bouddha, loi, moine ».",
    co: "Préoccupation mineure.",
    w: "Écoutez dans les bois riverains du Khentii en juin.",
    bt: "juin",
    fa: ["Existe en formes grise et rousse.", "S’identifie surtout au chant.", "Migre en Asie du Sud-Est."]
  },
  "long-eared-owl": {
    name: "Hibou moyen-duc",
    s: "Hibou élancé aux yeux orange et aux longues aigrettes. Présent partout en Mongolie où il y a des arbres, y compris dans les oasis du Gobi en migration.",
    d: "Le Hibou moyen-duc niche en Europe, en Asie et en Amérique du Nord. Il occupe d’anciens nids de corvidés et chasse les campagnols la nuit en terrain ouvert. En hiver, il forme souvent des dortoirs collectifs dans les arbres denses. En Mongolie, il niche dans les bois et bosquets du nord et de l’est et il est commun en migration dans le Gobi, par exemple à Yolyn Am.",
    f: ["Longues aigrettes, dressées quand il est inquiet.", "Yeux orange vif.", "Disque facial chamois orangé avec un « X » blanc entre les yeux.", "Corps chamois-brun strié.", "Élancé ; s’étire à la verticale quand on le dérange."],
    si: "Hibou des marais — aigrettes minuscules, yeux jaunes, milieux ouverts. Grand-duc d’Europe — bien plus grand.",
    h: "Bois, bosquets et haies près de milieux ouverts ; oasis en migration.",
    di: "Khentii (Khurkh, Terelj), Oulan-Bator, est (lac Ganga), Gobi (Yolyn Am).",
    mi: "Visiteur d’été et migrateur ; pics en avril–mai et septembre ; quelques hivernants.",
    fo: "Campagnols et souris ; quelques petits oiseaux.",
    br: "Utilise de vieux nids de corvidés ou de pies ; 4 à 6 œufs.",
    be: "Nocturne ; se tient plaqué contre un tronc le jour.",
    v: "Un « hou » grave et doux toutes les quelques secondes ; les jeunes grincent comme une porte.",
    cu: "Ses « oreilles » sont des plumes, pas des oreilles.",
    co: "Préoccupation mineure.",
    w: "Oasis du Gobi (Yolyn Am) en migration ; inspectez les arbres denses.",
    bt: "avril–mai, sept.",
    fa: ["Les « oreilles » ne sont que des plumes.", "Niche dans de vieux nids de corvidés.", "Dortoirs collectifs en hiver."]
  },
  "short-eared-owl": {
    name: "Hibou des marais",
    s: "Hibou pâle des milieux ouverts qui survole les prairies en plein jour, à battements lents comme un papillon de nuit. Présent dans les steppes et marais de toute la Mongolie.",
    d: "Le Hibou des marais est l’un des rapaces nocturnes les plus répandus au monde. Il vit dans les prairies, les marais et la toundra et niche au sol. Souvent actif de jour, surtout au crépuscule, il patrouille comme un busard. En Mongolie, il niche dans les prairies humides et la steppe, notamment dans la vallée de Khurkh et autour du lac Buir, et passe en septembre.",
    f: ["Chamois pâle strié de brun.", "Yeux jaunes cerclés de noir — regard farouche.", "Aigrettes minuscules, généralement invisibles.", "Longues ailes avec taches carpiennes sombres et extrémités barrées.", "Vol bas à battements raides, comme des coups de rame."],
    si: "Hibou moyen-duc — yeux orange, longues aigrettes, forêts. Busards — plus fins, longue queue, sans face ronde.",
    h: "Steppe, prairies humides, marais et milieux ouverts.",
    di: "Khentii (Khurkh), Dornod (lac Buir), lacs de l’ouest et Gobi en migration.",
    mi: "Visiteur d’été et migrateur ; la plupart des mentions en septembre.",
    fo: "Campagnols et autres petits rongeurs.",
    br: "Niche au sol dans l’herbe haute ; 4 à 8 œufs, davantage les années à campagnols.",
    be: "Chasse en patrouillant bas ; claque des ailes en vol nuptial.",
    v: "Surtout silencieux ; un « kii-ao » aboyé près du nid.",
    cu: "L’un des rares rapaces nocturnes présents sur tous les continents sauf l’Australie et l’Antarctique.",
    co: "Préoccupation mineure.",
    w: "Prairies de la vallée de Khurkh au crépuscule, juin–septembre.",
    bt: "juin–sept.",
    fa: ["Chasse de jour.", "Niche au sol.", "Présent sur cinq continents."]
  },
  "ural-owl": {
    name: "Chouette de l’Oural",
    s: "Grande chouette forestière gris pâle à face ronde et petits yeux sombres. Résidente rare des forêts du Khentii et du Khangaï.",
    d: "La Chouette de l’Oural vit dans les vieilles forêts du nord de l’Eurasie, de la Scandinavie au Japon. Elle défend son nid sans crainte et peut attaquer les personnes qui s’approchent trop. En Mongolie, elle fréquente les forêts de montagne du Khentii (Bogd Khan Uul, Terelj) et du Khangaï (vallée de l’Orkhon).",
    f: ["Grande chouette gris-brun pâle à longue queue.", "Face ronde, pâle et unie, sans aigrettes.", "Petits yeux sombres.", "Dessous strié.", "Bec jaunâtre."],
    si: "Chouette lapone — plus grande, cercles concentriques sur la face, yeux jaunes. Grand-duc d’Europe — aigrettes, yeux orange.",
    h: "Forêts mixtes et de conifères matures avec clairières.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khangaï (vallée de l’Orkhon).",
    mi: "Résidente.",
    fo: "Campagnols, souris, écureuils et oiseaux.",
    br: "Niche dans des troncs brisés, de grandes cavités ou d’anciens nids de rapaces ; 2 à 4 œufs.",
    be: "Nocturne ; défend farouchement son nid.",
    v: "Un « wouho … wouhouhou » grave.",
    cu: "Appelée « chouette à longue queue » dans certaines langues.",
    co: "Préoccupation mineure.",
    w: "Forêts du Bogd Khan Uul ; écoutez la nuit au printemps.",
    bt: "mars–juin",
    fa: ["Attaque les intrus au nid.", "A les yeux sombres.", "Vit dans les vieilles forêts."]
  },
  "great-grey-owl": {
    name: "Chouette lapone",
    s: "Énorme chouette grise à la face immense faite de cercles concentriques, aux yeux jaunes et au « nœud papillon » blanc. Résidente très rare de la taïga du nord, avec une seule mention GBIF.",
    d: "La Chouette lapone est la plus haute chouette du monde, même si son volume est surtout fait de plumes. Elle vit dans les forêts boréales d’Eurasie et d’Amérique du Nord et entend les campagnols sous une épaisse couche de neige. En Mongolie, elle est connue de la taïga du Khövsgöl et du nord du Khangaï, mais les mentions sont très rares.",
    f: ["Très grande chouette entièrement grise.", "Énorme disque facial à cercles concentriques.", "Petits yeux jaunes.", "« Moustache » blanche en nœud papillon sous le bec.", "Pas d’aigrettes."],
    si: "Chouette de l’Oural — plus petite, face unie, yeux sombres. Grand-duc d’Europe — aigrettes, yeux orange.",
    h: "Vieille forêt boréale près des tourbières et clairières.",
    di: "Très rare ; taïga du Khövsgöl et du nord du Khangaï.",
    mi: "Résidente ; peut se déplacer les années pauvres en campagnols.",
    fo: "Campagnols, capturés en plongeant dans la neige.",
    br: "Niche dans d’anciens nids de rapaces ou des troncs brisés ; 3 à 5 œufs.",
    be: "Chasse à l’écoute depuis un perchoir bas, souvent de jour.",
    v: "Une série lente de « hou » très graves.",
    cu: "Surnommée le « fantôme du Nord ».",
    co: "Préoccupation mineure.",
    w: "Rarement vue ; clairières de taïga autour du Khövsgöl.",
    bt: "—",
    fa: ["La plus haute chouette du monde.", "Entend les campagnols sous la neige.", "Surtout des plumes — plus légère qu’elle n’en a l’air."]
  },
  "snowy-owl": {
    name: "Harfang des neiges",
    s: "Grande chouette blanche de l’Arctique aux yeux jaunes. Visiteur d’hiver très rare en Mongolie, sans mention GBIF.",
    d: "Le Harfang des neiges niche dans la toundra arctique et chasse les lemmings. Les hivers où les lemmings s’effondrent, certains descendent très loin vers le sud. Il n’a été signalé qu’une poignée de fois dans le nord de la Mongolie. Il est classé Vulnérable, sa population semblant avoir diminué.",
    f: ["Surtout blanc ; femelles et jeunes barrés de brun-noir.", "Tête ronde sans aigrettes.", "Yeux jaunes.", "Pattes très emplumées.", "Se pose souvent au sol."],
    si: "Aucune autre chouette blanche en Mongolie ; un Faucon gerfaut pâle a des ailes pointues.",
    h: "Toundra arctique ; en hiver, steppe ouverte.",
    di: "Visiteur d’hiver très rare dans le nord.",
    mi: "Erratique hivernal par invasions.",
    fo: "Lemmings, campagnols, lièvres et oiseaux.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Actif de jour ; se pose sur des buttes en terrain ouvert.",
    v: "Surtout silencieux en hiver.",
    cu: "Rendu célèbre par Hedwige dans Harry Potter.",
    co: "Vulnérable.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Actif de jour.", "Vulnérable à l’échelle mondiale.", "Peut manger plus de 1 500 lemmings par an."]
  }
});
