B2T("en", {
  "red-crowned-crane": {
    T: { c: { white: 0.6, black: 0.3, red: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["trumpet"], ac: "day", se: ["summer"], sz: ["138–158 cm", "220–250 cm", "7–10 kg"] },
    s: "One of the rarest and heaviest cranes: snow-white with black neck and wing feathers and a red cap. A very rare summer visitor to the far east of Mongolia.",
    d: "The Red-crowned (Japanese) Crane breeds in the Amur basin of Russia and north-east China and resident birds live on Hokkaido, Japan. Mainland birds winter in Korea and eastern China. Only about 3,000 remain in the wild. In Mongolia it has been recorded only in the easternmost Dornod — along the Khalkh and Ulz rivers and in Mongol Daguur — where a few pairs may occasionally breed.",
    f: ["Very large, mostly white crane.", "Bare red crown patch.", "Black neck and face with a white band from the eye to the nape.", "Black secondary and tertial feathers form a black ‘tail’ when standing; wingtips white in flight.", "Dark grey-green bill."],
    si: "Siberian Crane — all white with a red face and black wingtips. White-naped Crane — grey body, pink legs. Oriental Stork — black flight feathers, red legs, no red crown.",
    h: "Large reed marshes and wet meadows in river valleys.",
    di: "Very rare; far eastern Dornod (Khalkh River, Mongol Daguur).",
    mi: "Summer visitor; recorded in July and October.",
    fo: "Fish, amphibians, crustaceans, insects, rice and seeds.",
    br: "Builds a platform of reeds in the marsh; 2 eggs.",
    be: "Pairs perform elaborate dances with bows, leaps and duet calls.",
    v: "A loud trumpeting duet.",
    cu: "A symbol of longevity, fidelity and happiness in Japan, China and Korea; appears on Japan Airlines’ logo.",
    co: "Vulnerable — wetland drainage in China and Russia.",
    w: "Only in the far east; do not approach nesting areas.",
    bt: "June–September",
    fa: ["Among the heaviest cranes.", "Only about 3,000 left in the wild.", "Symbol of long life in East Asia."]
  },
  "swinhoes-rail": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.1, black: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["silent"], ac: "night", se: ["summer"], sz: ["12–13 cm", "—", "30–50 g"] },
    s: "A tiny, secretive rail of wet meadows with white patches on the wings. Listed for eastern Mongolia but almost never seen — no GBIF records.",
    d: "Swinhoe’s Rail breeds in the wet sedge meadows of south-east Siberia and north-east China and winters in southern China. It is one of the least known birds of Asia and is Vulnerable according to some assessments. It may breed in wet meadows of eastern Mongolia.",
    f: ["Sparrow-sized rail.", "Brown upperparts streaked black and barred white.", "White patch on the inner wing, visible in flight.", "Buff breast, barred flanks."],
    si: "Baillon’s Crake — larger, grey face and breast, no white wing patch.",
    h: "Wet sedge meadows and shallow marshes.",
    di: "Very rare; possibly Dornod.",
    mi: "Summer visitor.",
    fo: "Insects, snails and seeds.",
    br: "Nests hidden in sedges.",
    be: "Runs like a mouse through vegetation; flies reluctantly.",
    v: "A ticking ‘kyok-kyok’ at night.",
    cu: "Named after Robert Swinhoe, a British consul and naturalist in China.",
    co: "Least Concern (poorly known).",
    w: "Almost impossible to see.",
    bt: "—",
    fa: ["One of Asia’s least known birds.", "Smaller than a sparrow.", "Calls at night."]
  },
  "eastern-water-rail": {
    T: { c: { brown: 0.4, gray: 0.35, black: 0.15, red: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["23–29 cm", "38–45 cm", "90–190 g"] },
    s: "A slim, secretive marsh bird with a long red bill and grey face, more often heard than seen. A summer visitor to reedbeds, especially in the Khurkh valley.",
    d: "The Eastern (Brown-cheeked) Water Rail breeds from Mongolia and south-east Siberia to northern Japan and winters in southern China and South-East Asia. It squeals like a piglet from dense reeds. In Mongolia it breeds in the reedbeds of Khentii, especially in the Khurkh–Khuiten valley, and in Dornod.",
    f: ["Long, slightly drooping red bill.", "Blue-grey face and breast with a brown stripe through the eye.", "Brown upperparts streaked black.", "Flanks barred black and white.", "Flicks its short tail, showing white undertail."],
    si: "Common Moorhen — red and yellow bill shield, black body. Spotted Crake — short yellow bill, white spots.",
    h: "Dense reedbeds and marshes.",
    di: "Khentii (Khurkh valley), Dornod (Ganga Nuur, Buir Nuur), occasional in the Gobi.",
    mi: "Summer visitor, May–September.",
    fo: "Insects, snails, worms, small fish and seeds.",
    br: "Nests in reeds just above the water; 5–9 eggs.",
    be: "Walks through reeds with a flattened body.",
    v: "Squealing and grunting sounds, like a piglet.",
    cu: "Until recently lumped with the Western Water Rail.",
    co: "Least Concern.",
    w: "Listen at dusk in the Khurkh valley reedbeds.",
    bt: "May–August",
    fa: ["Squeals like a piglet.", "Flattens its body to move through reeds.", "Split from Water Rail in 2010."]
  },
  "corncrake": {
    T: { c: { buff: 0.45, brown: 0.3, gray: 0.15, rufous: 0.1 }, hb: ["steppe", "water"], bk: "short", bh: ["walk", "night"], vt: ["croak"], ac: "night", se: ["summer"], sz: ["27–30 cm", "42–53 cm", "135–200 g"] },
    s: "A secretive rail of hay meadows, known by its rasping double call at night. A scarce summer visitor to northern and western Mongolia.",
    d: "The Corncrake breeds from Europe across Siberia to north-west Mongolia and winters in Africa. It hides in tall grass and is rarely seen, but males call ‘crex-crex’ all night. It declined in Europe because of early mowing. In Mongolia it occurs in moist meadows of the north and west.",
    f: ["Buff-brown with dark-centred feathers on the back.", "Grey face and neck in males.", "Chestnut wings, obvious in flight.", "Short, stout pinkish bill.", "Flies with dangling legs."],
    si: "Spotted Crake — smaller, white spots, near water. Quails — smaller, rounder.",
    h: "Hay meadows, tall grass near rivers and forest edges.",
    di: "Scarce; northern and western Mongolia.",
    mi: "Summer visitor, May–September.",
    fo: "Insects, worms, snails and seeds.",
    br: "Nests in tall grass; 8–12 eggs.",
    be: "Runs through grass rather than flying.",
    v: "A rasping, repeated ‘crex-crex’, like a comb drawn across a matchbox.",
    cu: "Its scientific name Crex crex copies its call.",
    co: "Least Concern.",
    w: "Listen on June nights in meadows.",
    bt: "June–July",
    fa: ["Its Latin name imitates its call.", "Calls all night.", "Winters in Africa."]
  },
  "spotted-crake": {
    T: { c: { brown: 0.45, gray: 0.3, white: 0.15, buff: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "night", se: ["summer"], sz: ["22–24 cm", "37–42 cm", "60–130 g"] },
    s: "A small, starry-spotted crake with a yellow-red bill that whips out a ‘hwit’ call at night. A rare summer visitor to Mongolian marshes.",
    d: "The Spotted Crake breeds from Europe to western Mongolia and winters in Africa and India. It lives in shallow marshes and is shy. There are only a few records from Mongolia.",
    f: ["Brown and grey, densely spotted with white.", "Short yellow bill with a red base.", "Buff undertail.", "Barred flanks."],
    si: "Baillon’s Crake — smaller, no dense white spots, green bill. Eastern Water Rail — long red bill.",
    h: "Shallow marshes with sedges.",
    di: "Rare; Orog Nuur, Khentii and Dornod.",
    mi: "Summer visitor.",
    fo: "Insects, snails and seeds.",
    br: "Nests in marsh vegetation; 8–12 eggs.",
    be: "Walks at the edge of vegetation, flicking its tail.",
    v: "A whiplash ‘hwitt’ repeated at night.",
    cu: "Its call is compared to a drop of water falling into a bucket.",
    co: "Least Concern.",
    w: "Listen at night in sedge marshes.",
    bt: "June",
    fa: ["Covered in white ‘stars’.", "Calls at night.", "Winters in Africa."]
  },
  "baillons-crake": {
    T: { c: { brown: 0.4, gray: 0.4, black: 0.1, white: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "night", se: ["summer"], sz: ["17–19 cm", "33–37 cm", "25–55 g"] },
    s: "A tiny, sparrow-sized crake with a blue-grey face and a frog-like rattling call. A secretive summer visitor to reedy marshes across Mongolia.",
    d: "Baillon’s Crake has a wide but patchy range across Europe, Asia, Africa and Australia. It is the smallest crake of the region. In Mongolia it breeds in reedy marshes, notably in the Khurkh valley, and around Gobi and western lakes like Böön Tsagaan and Khar Us Nuur.",
    f: ["Very small crake.", "Blue-grey face, throat and breast.", "Brown back with white streaks.", "Black and white barred flanks.", "Short green bill."],
    si: "Spotted Crake — larger, spotted, yellow-red bill. Swinhoe’s Rail — white wing patch.",
    h: "Marshes and reedy lake edges.",
    di: "Khentii (Khurkh), Gobi lakes (Böön Tsagaan), Khar Us Nuur, Dornod.",
    mi: "Summer visitor, May–October.",
    fo: "Insects, snails and seeds.",
    br: "Nests in dense vegetation; 4–8 eggs.",
    be: "Very secretive; walks on floating plants.",
    v: "A dry, frog-like rattle.",
    cu: "Named after the French naturalist Louis Antoine François Baillon.",
    co: "Least Concern.",
    w: "Listen at dusk in the Khurkh valley.",
    bt: "June",
    fa: ["The smallest crake in Mongolia.", "Sounds like a frog.", "Named after a French naturalist."]
  },
  "white-breasted-waterhen": {
    T: { c: { black: 0.4, white: 0.35, rufous: 0.15, gray: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["28–33 cm", "49–56 cm", "200–330 g"] },
    s: "A bold, black-and-white waterhen of tropical Asia. A rare vagrant to Mongolia, recorded at Ögii Nuur.",
    d: "The White-breasted Waterhen is common in South and South-East Asia, around ponds, ditches and paddies. It has been spreading north. In Mongolia it is a vagrant, with a few recent records at Ögii Nuur and elsewhere.",
    f: ["Dark grey-black upperparts.", "White face, throat and breast.", "Rufous undertail.", "Yellow-green bill with a red base."],
    si: "Common Moorhen — black body, red shield, white flank line.",
    h: "Ponds, marshes and ditches with cover.",
    di: "Rare vagrant; Ögii Nuur.",
    mi: "Vagrant.",
    fo: "Insects, snails, worms and seeds.",
    br: "Nests in bushes near water (not in Mongolia).",
    be: "Walks with tail cocked and jerking.",
    v: "Loud, harsh croaking choruses at dusk.",
    cu: "Its noisy calls are a familiar sound in Asian villages.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Spreading northwards.", "Very noisy at dusk.", "Black above, white below."]
  },
  "common-moorhen": {
    T: { c: { black: 0.6, gray: 0.15, red: 0.1, white: 0.1, yellow: 0.05 }, hb: ["water"], bk: "short", bh: ["swim", "walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["30–38 cm", "50–62 cm", "250–400 g"] },
    s: "A dark waterbird with a red forehead shield and yellow-tipped bill, jerking its white-edged tail. A summer visitor to reedy lakes and ponds.",
    d: "The Common Moorhen is found across Europe, Asia and Africa. It swims with a nodding head and walks on floating vegetation. In Mongolia it breeds on reedy lakes, especially in the west (Khar Us Nuur) and the Gobi (Böön Tsagaan, Orog Nuur), and also near Ulaanbaatar and in the Khentii.",
    f: ["Blackish body with a white line along the flanks.", "Red forehead shield and red bill with a yellow tip.", "White undertail sides, flashed as it flicks its tail.", "Long green-yellow legs and toes."],
    si: "Common Coot — all black with a white bill and shield. Eastern Water Rail — long red bill, streaked back.",
    h: "Reedy lakes, ponds and slow rivers.",
    di: "Khar Us Nuur, Böön Tsagaan, Orog Nuur, Ulaanbaatar, Yolyn Am oasis, Khurkh.",
    mi: "Summer visitor, April–October.",
    fo: "Water plants, seeds, insects and snails.",
    br: "Nests in reeds; 5–9 eggs; may raise two broods.",
    be: "Nods its head while swimming; runs over the water to take off.",
    v: "A loud, sudden ‘krrruk’.",
    cu: "Called ‘moorhen’ from the old word ‘mere’, a lake.",
    co: "Least Concern.",
    w: "Khar Us Nuur reed edges in summer.",
    bt: "May–August",
    fa: ["Walks on floating leaves.", "Nods its head when swimming.", "Young from the first brood help feed the second."]
  },
  "common-coot": {
    T: { c: { black: 0.85, white: 0.15 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["36–39 cm", "70–80 cm", "0.6–1.2 kg"] },
    s: "A plump, all-black waterbird with a white bill and forehead shield. One of the most common waterbirds on Mongolian lakes in summer.",
    d: "The Eurasian Coot lives across Europe, Asia, Africa and Australia. It dives for water plants and is aggressive towards its neighbours. In Mongolia it breeds on reedy lakes throughout the country; large numbers gather at Ögii Nuur, Khar Us Nuur, Böön Tsagaan and Buir Nuur before migration in September–October.",
    f: ["All black with a white bill and white frontal shield.", "Red eye.", "Lobed toes, not webbed.", "Round body; sits high in the water.", "Runs along the water to take off."],
    si: "Common Moorhen — red shield, white flank line. Ducks — flat bills.",
    h: "Lakes and ponds with reeds and water plants.",
    di: "All regions: Ögii Nuur, Khurkh, Khar Us Nuur, Ulaanbaatar ponds, Böön Tsagaan, Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Water plants, seeds, snails and insects.",
    br: "Floating nest of reeds; 6–10 eggs.",
    be: "Dives briefly; fights rivals by splashing and kicking.",
    v: "A short, loud ‘kowk’ or ‘pitt’.",
    cu: "‘Bald as a coot’ refers to its white shield.",
    co: "Least Concern.",
    w: "Any reedy lake in summer.",
    bt: "May–September",
    fa: ["Has lobed, not webbed, toes.", "Very territorial.", "Gathers in thousands before migration."]
  },
  "great-bustard": {
    T: { c: { brown: 0.35, gray: 0.3, white: 0.25, rufous: 0.1 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["75–105 cm", "190–260 cm", "3.5–16 kg"] },
    s: "The heaviest flying bird in the world: a huge, grey-headed steppe bird with a chestnut, black-barred back. An endangered summer visitor to Mongolia’s steppes and river valleys.",
    d: "The Great Bustard breeds from Iberia to eastern Asia. The eastern subspecies (dybowskii) breeds in Mongolia, Transbaikalia and north-east China and winters in China. It lives in open steppe and farmland. Males display in spring by turning themselves into white ‘feather balls’. Numbers in eastern Asia have fallen sharply; in Mongolia it is found in Khentii (Khurkh), Uvs, Dornod and the Khangai valleys.",
    f: ["Very large, heavy steppe bird.", "Grey head and neck; chestnut back barred black.", "White belly and large white wing panels in flight.", "Males have long white ‘whiskers’ in spring.", "Walks slowly and deliberately."],
    si: "Asian Houbara — smaller, sandy, with black neck plumes. Cranes — longer legs and neck, grey.",
    h: "Open steppe, river valleys and fields.",
    di: "Khentii (Khurkh), Uvs, Dornod (Buir Nuur, Mongol Daguur), Khangai.",
    mi: "Summer visitor, April–October; peak in May.",
    fo: "Plants, seeds, insects and small vertebrates.",
    br: "Nests on the ground in steppe; 2–3 eggs.",
    be: "Males gather at display grounds (leks) in spring.",
    v: "Mostly silent.",
    cu: "Hunting it is banned in Mongolia; it is listed in the Mongolian Red Book.",
    co: "Endangered — hunting, farming and power lines.",
    w: "Khurkh valley steppe in May, from a distance.",
    bt: "May",
    fa: ["Heaviest flying bird in the world.", "Males can be four times heavier than females.", "Endangered in Asia."]
  },
  "houbara-bustard": {
    T: { c: { buff: 0.5, brown: 0.2, white: 0.2, black: 0.1 }, hb: ["desert"], bk: "short", bh: ["walk"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["55–65 cm", "135–170 cm", "1.2–3.2 kg"] },
    s: "A sandy, desert bustard with a black stripe of plumes on the neck. The Asian Houbara breeds in the Gobi, but is heavily hunted on its wintering grounds.",
    d: "The Asian (MacQueen’s) Houbara Bustard breeds in the deserts of Central Asia, western China and southern Mongolia and winters in Pakistan, Iran and Arabia. It is the main quarry of Arab falconers, and illegal hunting and trapping have caused steep declines. In Mongolia it breeds on the gravel plains and saxaul desert of the southern Gobi.",
    f: ["Sandy, finely vermiculated upperparts.", "Black-and-white plumes down the side of the neck.", "White underparts.", "Large white patches on the black wings in flight.", "Runs rather than flies."],
    si: "Great Bustard — much larger, grey head. Pallas’s Sandgrouse — smaller, pointed tail.",
    h: "Semi-desert, gravel plains and saxaul scrub.",
    di: "Southern Gobi (Ömnögovi, Dornogovi, Gobi-Altai).",
    mi: "Summer visitor, April–October.",
    fo: "Plants, seeds, insects and lizards.",
    br: "Nests on the ground; 2–3 eggs.",
    be: "Males display by raising the neck plumes over their heads and running.",
    v: "Mostly silent.",
    cu: "Arab falconers’ favourite quarry.",
    co: "Vulnerable — hunting and trapping on the wintering grounds.",
    w: "Southern Gobi in spring; keep your distance.",
    bt: "April–June",
    fa: ["Favourite prey of Arab falconers.", "Vulnerable worldwide.", "Males display with neck plumes."]
  }
});
