B2T("fr", {
  "red-crowned-crane": {
    name: "Grue du Japon",
    s: "L’une des grues les plus rares et les plus lourdes : blanc neige, cou et rémiges noirs, calotte rouge. Visiteur d’été très rare à l’extrême est de la Mongolie.",
    d: "La Grue du Japon niche dans le bassin de l’Amour en Russie et dans le nord-est de la Chine ; une population sédentaire vit à Hokkaidō. Les oiseaux continentaux hivernent en Corée et dans l’est de la Chine. Il n’en reste qu’environ 3 000 à l’état sauvage. En Mongolie, elle n’a été notée qu’à l’extrême est du Dornod — le long des rivières Khalkh et Ulz et à Mongol Daguur — où quelques couples nichent peut-être occasionnellement.",
    f: ["Très grande grue surtout blanche.", "Calotte rouge nue.", "Cou et face noirs avec une bande blanche de l’œil à la nuque.", "Rémiges secondaires et tertiaires noires formant une « queue » noire au repos ; extrémités des ailes blanches en vol.", "Bec gris-vert foncé."],
    si: "Grue de Sibérie — entièrement blanche, face rouge, extrémités des ailes noires. Grue à cou blanc — corps gris, pattes roses. Cigogne orientale — rémiges noires, pattes rouges, sans calotte rouge.",
    h: "Grands marais à roseaux et prairies humides des vallées.",
    di: "Très rare ; extrême est du Dornod (rivière Khalkh, Mongol Daguur).",
    mi: "Visiteur d’été ; noté en juillet et octobre.",
    fo: "Poissons, amphibiens, crustacés, insectes, riz et graines.",
    br: "Plateforme de roseaux dans le marais ; 2 œufs.",
    be: "Les couples exécutent des danses élaborées avec saluts, sauts et duos.",
    v: "Un duo claironnant puissant.",
    cu: "Symbole de longévité, de fidélité et de bonheur au Japon, en Chine et en Corée ; figure sur le logo de Japan Airlines.",
    co: "Vulnérable — drainage des zones humides en Chine et en Russie.",
    w: "Uniquement à l’extrême est ; ne pas approcher des zones de nidification.",
    bt: "juin–sept.",
    fa: ["Parmi les grues les plus lourdes.", "Environ 3 000 à l’état sauvage.", "Symbole de longévité en Asie orientale."]
  },
  "swinhoes-rail": {
    name: "Râle de Swinhoe",
    s: "Minuscule râle discret des prairies humides, aux taches alaires blanches. Inscrit pour l’est de la Mongolie mais presque jamais vu — aucune mention GBIF.",
    d: "Le Râle de Swinhoe niche dans les prairies humides à laîches du sud-est de la Sibérie et du nord-est de la Chine et hiverne dans le sud de la Chine. C’est l’un des oiseaux les moins connus d’Asie. Il niche peut-être dans les prairies humides de l’est de la Mongolie.",
    f: ["Râle de la taille d’un moineau.", "Dessus brun strié de noir et barré de blanc.", "Tache blanche sur l’aile interne, visible en vol.", "Poitrine chamois, flancs barrés."],
    si: "Marouette de Baillon — plus grande, face et poitrine grises, sans tache alaire blanche.",
    h: "Prairies humides à laîches et marais peu profonds.",
    di: "Très rare ; peut-être le Dornod.",
    mi: "Visiteur d’été.",
    fo: "Insectes, escargots et graines.",
    br: "Nid caché dans les laîches.",
    be: "Court comme une souris dans la végétation ; s’envole à contrecœur.",
    v: "Un « kyok-kyok » cliquetant la nuit.",
    cu: "Nommé d’après Robert Swinhoe, consul britannique et naturaliste en Chine.",
    co: "Préoccupation mineure (mal connu).",
    w: "Presque impossible à voir.",
    bt: "—",
    fa: ["L’un des oiseaux les moins connus d’Asie.", "Plus petit qu’un moineau.", "Chante la nuit."]
  },
  "eastern-water-rail": {
    name: "Râle à joues brunes",
    s: "Oiseau de marais fin et discret, au long bec rouge et à la face grise, plus souvent entendu que vu. Visiteur d’été des roselières, surtout dans la vallée de Khurkh.",
    d: "Le Râle à joues brunes niche de la Mongolie et du sud-est de la Sibérie jusqu’au nord du Japon et hiverne dans le sud de la Chine et en Asie du Sud-Est. Il pousse des cris de porcelet depuis les roseaux denses. En Mongolie, il niche dans les roselières du Khentii, surtout dans la vallée de Khurkh-Khüiten, et dans le Dornod.",
    f: ["Long bec rouge légèrement arqué.", "Face et poitrine gris-bleu avec un trait brun à travers l’œil.", "Dessus brun strié de noir.", "Flancs barrés de noir et de blanc.", "Agite sa queue courte, montrant des sous-caudales blanches."],
    si: "Gallinule poule-d’eau — plaque frontale rouge et jaune, corps noir. Marouette ponctuée — bec court jaune, taches blanches.",
    h: "Roselières denses et marais.",
    di: "Khentii (vallée de Khurkh), Dornod (lacs Ganga et Buir), parfois le Gobi.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes, escargots, vers, petits poissons et graines.",
    br: "Niche dans les roseaux juste au-dessus de l’eau ; 5 à 9 œufs.",
    be: "Se faufile entre les roseaux, le corps aplati.",
    v: "Cris aigus et grognements de porcelet.",
    cu: "Longtemps réuni avec le Râle d’eau d’Europe.",
    co: "Préoccupation mineure.",
    w: "Écoutez au crépuscule dans les roselières de Khurkh.",
    bt: "mai–août",
    fa: ["Crie comme un porcelet.", "S’aplatit pour passer entre les roseaux.", "Séparé du Râle d’eau en 2010."]
  },
  "corncrake": {
    name: "Râle des genêts",
    s: "Râle discret des prairies de fauche, connu pour son cri double et râpeux la nuit. Visiteur d’été peu commun dans le nord et l’ouest de la Mongolie.",
    d: "Le Râle des genêts niche de l’Europe à la Sibérie et au nord-ouest de la Mongolie et hiverne en Afrique. Il se cache dans l’herbe haute et se voit rarement, mais les mâles chantent « crex-crex » toute la nuit. Il a décliné en Europe à cause des fauches précoces. En Mongolie, il fréquente les prairies humides du nord et de l’ouest.",
    f: ["Chamois-brun, plumes du dos à centre sombre.", "Face et cou gris chez le mâle.", "Ailes rousses, bien visibles en vol.", "Bec court et fort, rosâtre.", "Vole les pattes pendantes."],
    si: "Marouette ponctuée — plus petite, tachetée de blanc, près de l’eau. Cailles — plus petites et rondes.",
    h: "Prairies de fauche, herbes hautes près des rivières et des lisières.",
    di: "Peu commun ; nord et ouest de la Mongolie.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes, vers, escargots et graines.",
    br: "Niche dans l’herbe haute ; 8 à 12 œufs.",
    be: "Court dans l’herbe plutôt que de s’envoler.",
    v: "Un « crex-crex » râpeux et répété, comme un peigne frotté sur une boîte d’allumettes.",
    cu: "Son nom latin Crex crex imite son cri.",
    co: "Préoccupation mineure.",
    w: "Écoutez les nuits de juin dans les prairies.",
    bt: "juin–juil.",
    fa: ["Son nom latin imite son chant.", "Chante toute la nuit.", "Hiverne en Afrique."]
  },
  "spotted-crake": {
    name: "Marouette ponctuée",
    s: "Petite marouette constellée de blanc, au bec jaune et rouge, dont le « huitt » claque la nuit. Visiteur d’été rare des marais mongols.",
    d: "La Marouette ponctuée niche de l’Europe à l’ouest de la Mongolie et hiverne en Afrique et en Inde. Elle vit dans les marais peu profonds et est farouche. On ne compte que quelques mentions en Mongolie.",
    f: ["Brun et gris, densément piqueté de blanc.", "Bec court jaune à base rouge.", "Sous-caudales chamois.", "Flancs barrés."],
    si: "Marouette de Baillon — plus petite, sans taches blanches denses, bec vert. Râle à joues brunes — long bec rouge.",
    h: "Marais peu profonds à laîches.",
    di: "Rare ; lac Orog, Khentii et Dornod.",
    mi: "Visiteur d’été.",
    fo: "Insectes, escargots et graines.",
    br: "Niche dans la végétation du marais ; 8 à 12 œufs.",
    be: "Marche en bordure de végétation en agitant la queue.",
    v: "Un « huitt » claquant comme un fouet, répété la nuit.",
    cu: "Son chant évoque une goutte d’eau tombant dans un seau.",
    co: "Préoccupation mineure.",
    w: "Écoutez la nuit dans les marais à laîches.",
    bt: "juin",
    fa: ["Couverte d’« étoiles » blanches.", "Chante la nuit.", "Hiverne en Afrique."]
  },
  "baillons-crake": {
    name: "Marouette de Baillon",
    s: "Minuscule marouette de la taille d’un moineau, à face gris-bleu et au chant de grenouille. Visiteur d’été discret des marais à roseaux de toute la Mongolie.",
    d: "La Marouette de Baillon a une aire vaste mais morcelée en Europe, en Asie, en Afrique et en Australie. C’est la plus petite marouette de la région. En Mongolie, elle niche dans les marais à roseaux, notamment dans la vallée de Khurkh, et autour des lacs du Gobi et de l’ouest comme Böön Tsagaan et Khar Us.",
    f: ["Très petite marouette.", "Face, gorge et poitrine gris-bleu.", "Dos brun strié de blanc.", "Flancs barrés de noir et de blanc.", "Bec court vert."],
    si: "Marouette ponctuée — plus grande, tachetée, bec jaune et rouge. Râle de Swinhoe — tache alaire blanche.",
    h: "Marais et rives de lacs à roseaux.",
    di: "Khentii (Khurkh), lacs du Gobi (Böön Tsagaan), lac Khar Us, Dornod.",
    mi: "Visiteur d’été, mai–octobre.",
    fo: "Insectes, escargots et graines.",
    br: "Niche dans la végétation dense ; 4 à 8 œufs.",
    be: "Très discrète ; marche sur les plantes flottantes.",
    v: "Un crépitement sec, comme une grenouille.",
    cu: "Nommée d’après le naturaliste français Louis Antoine François Baillon.",
    co: "Préoccupation mineure.",
    w: "Écoutez au crépuscule dans la vallée de Khurkh.",
    bt: "juin",
    fa: ["La plus petite marouette de Mongolie.", "Chante comme une grenouille.", "Porte le nom d’un naturaliste français."]
  },
  "white-breasted-waterhen": {
    name: "Râle à poitrine blanche",
    s: "Râle hardi noir et blanc d’Asie tropicale. Erratique rare en Mongolie, noté au lac Ögii.",
    d: "Le Râle à poitrine blanche est commun en Asie du Sud et du Sud-Est, autour des mares, des fossés et des rizières. Il s’étend vers le nord. En Mongolie, c’est un erratique, avec quelques mentions récentes au lac Ögii et ailleurs.",
    f: ["Dessus gris-noir foncé.", "Face, gorge et poitrine blanches.", "Sous-caudales rousses.", "Bec jaune-vert à base rouge."],
    si: "Gallinule poule-d’eau — corps noir, plaque rouge, ligne blanche sur le flanc.",
    h: "Mares, marais et fossés avec couvert.",
    di: "Erratique rare ; lac Ögii.",
    mi: "Erratique.",
    fo: "Insectes, escargots, vers et graines.",
    br: "Niche dans les buissons près de l’eau (pas en Mongolie).",
    be: "Marche la queue relevée et saccadée.",
    v: "Chœurs de croassements forts et rauques au crépuscule.",
    cu: "Ses cris bruyants sont familiers dans les villages d’Asie.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["S’étend vers le nord.", "Très bruyant au crépuscule.", "Noir dessus, blanc dessous."]
  },
  "common-moorhen": {
    name: "Gallinule poule-d’eau",
    s: "Oiseau d’eau sombre à plaque frontale rouge et bec à pointe jaune, qui agite sa queue bordée de blanc. Visiteur d’été des lacs à roseaux et des étangs.",
    d: "La Gallinule poule-d’eau est présente en Europe, en Asie et en Afrique. Elle nage en hochant la tête et marche sur la végétation flottante. En Mongolie, elle niche sur les lacs à roseaux, surtout dans l’ouest (lac Khar Us) et le Gobi (Böön Tsagaan, lac Orog), ainsi que près d’Oulan-Bator et dans le Khentii.",
    f: ["Corps noirâtre avec une ligne blanche le long des flancs.", "Plaque frontale rouge et bec rouge à pointe jaune.", "Côtés des sous-caudales blancs, montrés quand elle agite la queue.", "Longues pattes et doigts vert-jaune."],
    si: "Foulque macroule — entièrement noire, bec et plaque blancs. Râle à joues brunes — long bec rouge, dos strié.",
    h: "Lacs à roseaux, étangs et rivières lentes.",
    di: "Lac Khar Us, Böön Tsagaan, lac Orog, Oulan-Bator, oasis de Yolyn Am, Khurkh.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes aquatiques, graines, insectes et escargots.",
    br: "Niche dans les roseaux ; 5 à 9 œufs ; peut élever deux nichées.",
    be: "Hoche la tête en nageant ; court sur l’eau pour décoller.",
    v: "Un « krrrouk » fort et soudain.",
    cu: "Son nom anglais vient du vieux mot « mere », un lac.",
    co: "Préoccupation mineure.",
    w: "Bords de roselières du lac Khar Us en été.",
    bt: "mai–août",
    fa: ["Marche sur les feuilles flottantes.", "Hoche la tête en nageant.", "Les jeunes de la première nichée nourrissent la seconde."]
  },
  "common-coot": {
    name: "Foulque macroule",
    s: "Oiseau d’eau dodu entièrement noir, au bec et à la plaque frontale blancs. L’un des oiseaux d’eau les plus communs des lacs mongols en été.",
    d: "La Foulque macroule vit en Europe, en Asie, en Afrique et en Australie. Elle plonge pour chercher des plantes aquatiques et se montre agressive envers ses voisines. En Mongolie, elle niche sur les lacs à roseaux de tout le pays ; de grands rassemblements se forment aux lacs Ögii, Khar Us, Böön Tsagaan et Buir avant la migration en septembre–octobre.",
    f: ["Entièrement noire avec bec et plaque frontale blancs.", "Œil rouge.", "Doigts lobés, non palmés.", "Corps rond ; flotte haut sur l’eau.", "Court sur l’eau pour décoller."],
    si: "Gallinule poule-d’eau — plaque rouge, ligne blanche sur le flanc. Canards — bec plat.",
    h: "Lacs et étangs avec roseaux et plantes aquatiques.",
    di: "Toutes les régions : lac Ögii, Khurkh, lac Khar Us, étangs d’Oulan-Bator, Böön Tsagaan, lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes aquatiques, graines, escargots et insectes.",
    br: "Nid flottant de roseaux ; 6 à 10 œufs.",
    be: "Plonge brièvement ; se bat à coups d’éclaboussures et de pattes.",
    v: "Un « kowk » ou « pitt » court et fort.",
    cu: "L’expression anglaise « chauve comme une foulque » vient de sa plaque blanche.",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac à roseaux en été.",
    bt: "mai–sept.",
    fa: ["Doigts lobés et non palmés.", "Très territoriale.", "Se rassemble par milliers avant la migration."]
  },
  "great-bustard": {
    name: "Grande Outarde",
    s: "L’oiseau volant le plus lourd du monde : immense oiseau des steppes à tête grise et dos roux barré de noir. Visiteur d’été menacé des steppes et vallées de Mongolie.",
    d: "La Grande Outarde niche de la péninsule Ibérique à l’Asie orientale. La sous-espèce orientale (dybowskii) niche en Mongolie, en Transbaïkalie et dans le nord-est de la Chine et hiverne en Chine. Elle vit dans la steppe ouverte et les cultures. Au printemps, les mâles paradent en se transformant en « boules de plumes » blanches. Les effectifs d’Asie orientale ont fortement chuté ; en Mongolie, on la trouve dans le Khentii (Khurkh), l’Uvs, le Dornod et les vallées du Khangaï.",
    f: ["Très grand oiseau lourd des steppes.", "Tête et cou gris ; dos roux barré de noir.", "Ventre blanc et grands panneaux alaires blancs en vol.", "Longues « moustaches » blanches chez le mâle au printemps.", "Marche lentement et posément."],
    si: "Outarde houbara — plus petite, couleur sable, plumes noires sur le cou. Grues — pattes et cou plus longs, grises.",
    h: "Steppe ouverte, vallées et champs.",
    di: "Khentii (Khurkh), Uvs, Dornod (lac Buir, Mongol Daguur), Khangaï.",
    mi: "Visiteur d’été, avril–octobre ; pic en mai.",
    fo: "Plantes, graines, insectes et petits vertébrés.",
    br: "Niche au sol dans la steppe ; 2 ou 3 œufs.",
    be: "Les mâles se rassemblent sur des places de parade (leks) au printemps.",
    v: "Surtout silencieuse.",
    cu: "Sa chasse est interdite en Mongolie ; inscrite au Livre rouge de Mongolie.",
    co: "En danger — chasse, agriculture et lignes électriques.",
    w: "Steppe de la vallée de Khurkh en mai, à distance.",
    bt: "mai",
    fa: ["L’oiseau volant le plus lourd du monde.", "Le mâle peut peser quatre fois plus que la femelle.", "Menacée en Asie."]
  },
  "houbara-bustard": {
    name: "Outarde de Macqueen",
    s: "Outarde du désert couleur sable, avec une bande de plumes noires sur le cou. L’outarde asiatique niche dans le Gobi mais est très chassée sur ses sites d’hivernage.",
    d: "L’Outarde de Macqueen (houbara asiatique) niche dans les déserts d’Asie centrale, de l’ouest de la Chine et du sud de la Mongolie, et hiverne au Pakistan, en Iran et en Arabie. C’est la proie favorite des fauconniers arabes, et la chasse et le piégeage illégaux ont entraîné de fortes baisses. En Mongolie, elle niche dans les plaines caillouteuses et les déserts à saxaoul du sud du Gobi.",
    f: ["Dessus couleur sable finement vermiculé.", "Plumes noires et blanches le long du cou.", "Dessous blanc.", "Grandes taches blanches sur les ailes noires en vol.", "Court plutôt que de voler."],
    si: "Grande Outarde — bien plus grande, tête grise. Syrrhapte paradoxal — plus petit, queue pointue.",
    h: "Semi-désert, plaines caillouteuses et fourrés de saxaoul.",
    di: "Sud du Gobi (Ömnögovi, Dornogovi, Gobi-Altaï).",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes, graines, insectes et lézards.",
    br: "Niche au sol ; 2 ou 3 œufs.",
    be: "Le mâle parade en rabattant ses plumes de cou sur la tête et en courant.",
    v: "Surtout silencieuse.",
    cu: "Proie favorite des fauconniers arabes.",
    co: "Vulnérable — chasse et piégeage sur les sites d’hivernage.",
    w: "Sud du Gobi au printemps ; gardez vos distances.",
    bt: "avril–juin",
    fa: ["Proie favorite des fauconniers arabes.", "Vulnérable à l’échelle mondiale.", "Le mâle parade avec ses plumes de cou."]
  }
});
