B2T("en", {
  "little-grebe": {
    T: { c: { brown: 0.5, rufous: 0.25, black: 0.15, yellow: 0.1 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["laugh"], ac: "day", se: ["summer"], sz: ["23–29 cm", "40–45 cm", "100–235 g"] },
    s: "A tiny, round grebe with chestnut cheeks and a bright yellow spot at the base of the bill. A summer visitor to small, reedy ponds.",
    d: "The Little Grebe (Dabchick) is found across Europe, Asia and Africa. It dives constantly for small fish and insects and hides in reeds when alarmed. In Mongolia it breeds on small lakes and ponds with vegetation, from the Khurkh valley and Ulaanbaatar to Gobi oases such as Yolyn Am and Ganga Nuur in the east.",
    f: ["Very small and rounded, with a fluffy rear end.", "Breeding: dark brown with chestnut cheeks and neck.", "Bright yellow-green patch at the base of the bill.", "Winter: plain buff-brown.", "Dives with a little jump."],
    si: "Black-necked Grebe — larger, black neck, golden ear-tufts, red eye. Young coots — larger bills.",
    h: "Small ponds, oxbow lakes and reedy lake edges.",
    di: "Khentii (Khurkh), Ulaanbaatar, Yolyn Am, Ganga Nuur, Khar Us Nuur, Khövsgöl.",
    mi: "Summer visitor, April–October.",
    fo: "Small fish, insects and their larvae, snails.",
    br: "Floating nest anchored to plants; 4–6 eggs, covered with weed when the bird leaves.",
    be: "Dives often; runs across the water in territorial chases.",
    v: "A long, whinnying trill.",
    cu: "Its old English name ‘dabchick’ means ‘dipping chick’.",
    co: "Least Concern.",
    w: "Small ponds at Yolyn Am and in the Khurkh valley in June.",
    bt: "May–August",
    fa: ["The smallest grebe in Mongolia.", "Covers its eggs with weed.", "Trills like a horse’s whinny."]
  },
  "red-necked-grebe": {
    T: { c: { gray: 0.35, rufous: 0.3, white: 0.2, black: 0.15 }, hb: ["water"], bk: "long", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["40–50 cm", "77–85 cm", "0.7–1.1 kg"] },
    s: "A stocky grebe with a chestnut neck, pale grey cheeks and a yellow-based bill. A local summer visitor, mostly on lakes in eastern Mongolia.",
    d: "The Red-necked Grebe breeds on shallow, vegetated lakes across northern Eurasia and North America. In Mongolia it breeds mainly in the east, especially at Buir Nuur and other Dornod lakes, with smaller numbers in the Khentii and near Ulaanbaatar.",
    f: ["Chestnut-red neck and upper breast in summer.", "Pale grey cheeks bordered white.", "Black cap.", "Dagger-like bill, black with a yellow base.", "Bulkier than other small grebes."],
    si: "Great Crested Grebe — larger, white face with orange frills, pink bill. Slavonian Grebe — smaller, golden ‘horns’.",
    h: "Shallow lakes with reeds and floating vegetation.",
    di: "Dornod (Buir Nuur), Khentii (Khurkh, Onon), Ulaanbaatar area.",
    mi: "Summer visitor, May–October.",
    fo: "Fish, insects, crustaceans and molluscs.",
    br: "Floating nest; 3–5 eggs; chicks ride on the parents’ backs.",
    be: "Noisy courtship with loud braying calls.",
    v: "Loud wailing and braying calls in spring.",
    cu: "Chicks ride on their parents’ backs for the first weeks.",
    co: "Least Concern.",
    w: "Buir Nuur in June–July.",
    bt: "June–July",
    fa: ["Very vocal in spring.", "Carries chicks on its back.", "Mainly in eastern Mongolia."]
  },
  "great-crested-grebe": {
    T: { c: { white: 0.4, brown: 0.3, rufous: 0.2, black: 0.1 }, hb: ["water"], bk: "long", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["46–52 cm", "59–73 cm", "0.9–1.5 kg"] },
    s: "An elegant, long-necked grebe with a black crest and orange-and-black frills. The most common grebe on Mongolia’s large lakes.",
    d: "The Great Crested Grebe breeds from Europe across Asia and in Africa and Australia. It is famous for its courtship ‘weed dance’, in which both birds rise breast-to-breast holding water plants. In Mongolia it breeds on reedy lakes throughout the country, with large numbers at Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur and Buir Nuur.",
    f: ["Long white neck and white face.", "Black crest and orange-chestnut frills with black edges in summer.", "Pink dagger-shaped bill.", "Brown-grey back.", "Winter: plain grey and white, with white above the eye."],
    si: "Red-necked Grebe — smaller, chestnut neck, grey cheeks. Black-throated Diver — larger, heavier, with a straight black bill.",
    h: "Large lakes with reedy margins.",
    di: "Khangai (Ögii Nuur), Khar Us Nuur, Ulaanbaatar ponds, Gobi lakes (Böön Tsagaan, Orog Nuur), Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Fish; also insects and crustaceans.",
    br: "Floating nest in reeds; 3–5 eggs; chicks are striped and ride on the parents’ backs.",
    be: "Elaborate courtship with head-shaking and ‘weed dance’.",
    v: "Harsh, growling ‘rah-rah-rah’.",
    cu: "Victorian demand for its plumes nearly wiped it out in Britain and led to the founding of the RSPB.",
    co: "Least Concern.",
    w: "Ögii Nuur in May–June, when courtship is at its peak.",
    bt: "May–June",
    fa: ["Performs a ‘weed dance’ in courtship.", "Eats its own feathers to protect its stomach.", "Its plumes were once used in fashion."]
  },
  "slavonian-grebe": {
    T: { c: { black: 0.4, rufous: 0.3, yellow: 0.15, white: 0.15 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["31–38 cm", "46–55 cm", "300–470 g"] },
    s: "A small grebe with golden ‘horns’, a black head and a chestnut neck in summer. A widespread summer visitor on Mongolian lakes, globally Vulnerable.",
    d: "The Horned (Slavonian) Grebe breeds on small lakes across northern Eurasia and North America. It is now listed as Vulnerable because of declines in North America and Europe. In Mongolia it is widespread on vegetated lakes in the Khangai, Khentii and eastern steppes, with Ögii Nuur and the Khurkh valley holding good numbers.",
    f: ["Black head with golden-yellow ‘horns’ from the eye to the back of the head.", "Chestnut-red neck and flanks.", "Short, straight black bill with a pale tip.", "Red eye.", "Winter: black-and-white, with a sharply defined black cap."],
    si: "Black-necked Grebe — black neck, fan of golden feathers behind the eye, upturned bill. Red-necked Grebe — larger, grey cheeks.",
    h: "Small to medium lakes with emergent vegetation.",
    di: "Khangai (Ögii Nuur), Khentii (Khurkh), Böön Tsagaan, Ulaanbaatar area, Dornod.",
    mi: "Summer visitor, May–October.",
    fo: "Aquatic insects, small fish and crustaceans.",
    br: "Floating nest; 3–5 eggs.",
    be: "Courtship includes the ‘penguin dance’ with both birds rising up.",
    v: "Trills and squeals in spring.",
    cu: "Its name refers to the Slavonic lands, where it was first described.",
    co: "Vulnerable.",
    w: "Ögii Nuur in June.",
    bt: "June–August",
    fa: ["Globally Vulnerable.", "Golden ‘horns’ in breeding plumage.", "Chicks ride on their parents’ backs."]
  },
  "black-necked-grebe": {
    T: { c: { black: 0.55, rufous: 0.2, yellow: 0.15, red: 0.1 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["28–34 cm", "56–60 cm", "265–450 g"] },
    s: "A small, sociable grebe with a black neck, a fan of golden feathers behind a red eye, and a slightly upturned bill. Common on lakes in northern and central Mongolia.",
    d: "The Black-necked Grebe is the most numerous grebe in the world. It often nests in colonies among gulls and terns. In Mongolia it breeds on reedy lakes, especially in the Khurkh valley, at Ögii Nuur, Khar Us Nuur and Buir Nuur.",
    f: ["Black head, neck and back in summer.", "Fan of golden plumes behind the eye.", "Bright red eye.", "Slightly upturned black bill.", "Chestnut flanks."],
    si: "Slavonian Grebe — chestnut neck, golden ‘horns’ running back from the eye, straight bill.",
    h: "Shallow, reedy lakes and ponds, often with gull colonies.",
    di: "Khentii (Khurkh), Ögii Nuur, Khar Us Nuur, Buir Nuur, Ulaanbaatar area.",
    mi: "Summer visitor, April–October.",
    fo: "Aquatic insects, larvae, small crustaceans.",
    br: "Colonial; floating nests; 3–4 eggs.",
    be: "Sociable; forms colonies and flocks.",
    v: "A soft, rising whistle ‘poo-eeet’.",
    cu: "Some populations moult on salt lakes and become flightless for two months.",
    co: "Least Concern.",
    w: "Khurkh valley lakes in June.",
    bt: "May–August",
    fa: ["The world’s most numerous grebe.", "Nests in colonies.", "Can be flightless for weeks while moulting."]
  },
  "red-throated-diver": {
    T: { c: { gray: 0.5, white: 0.25, rufous: 0.15, black: 0.1 }, hb: ["water"], bk: "long", bh: ["swim"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["55–67 cm", "91–110 cm", "1–2.7 kg"] },
    s: "The smallest diver, with a slim, upturned bill and a dark red throat patch in summer. A rare migrant in northern and eastern Mongolia.",
    d: "The Red-throated Loon breeds on small tundra pools in the Arctic and winters at sea. It is the only diver that can take off from land. In Mongolia it is a rare passage migrant, with a few records in May–June and October.",
    f: ["Slim, pale grey head and neck in summer.", "Dark red throat patch.", "Thin, slightly upturned bill, held tilted up.", "Plain grey-brown back finely spotted with white in winter.", "Sits low in the water."],
    si: "Black-throated Diver — larger, black throat, chequered back, straight bill. Grebes — smaller, dive with a jump.",
    h: "Lakes and rivers on migration.",
    di: "Rare; Khentii and Dornod.",
    mi: "Passage migrant, May–June and October.",
    fo: "Fish.",
    br: "Nests on Arctic pools (not in Mongolia).",
    be: "Dives for long periods.",
    v: "Goose-like cackling and wailing on the breeding grounds.",
    cu: "Fishermen in Scotland believed its call foretold rain — the ‘rain goose’.",
    co: "Least Concern.",
    w: "Check lakes in the east in May.",
    bt: "May",
    fa: ["The smallest diver.", "Can take off from land.", "Nicknamed the ‘rain goose’."]
  },
  "black-throated-diver": {
    T: { c: { black: 0.4, white: 0.35, gray: 0.25 }, hb: ["water"], bk: "long", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["58–73 cm", "100–130 cm", "2–3.4 kg"] },
    s: "A beautiful diver with a grey head, black throat and white-chequered black back. Breeds on large mountain lakes in western Mongolia and the Khangai.",
    d: "The Black-throated Loon breeds on large, deep lakes across northern Eurasia and winters at sea. It dives for fish, staying underwater for up to two minutes. In Mongolia it breeds on the lakes of the Khangai (Ögii Nuur, Terkhiin Tsagaan Nuur), Khövsgöl, and the Altai lakes of Bayan-Ölgii.",
    f: ["Soft grey head and hindneck.", "Black throat patch with white striped sides.", "Black back with rows of white squares.", "Straight, dagger-like black bill.", "Sits low in the water."],
    si: "Red-throated Diver — smaller, red throat, upturned bill. Great Crested Grebe — slimmer, white face, orange frills.",
    h: "Large, deep, clear lakes.",
    di: "Khangai (Ögii Nuur, Terkhiin Tsagaan Nuur), Khövsgöl, Khar Us Nuur, Altai lakes (Bayan-Ölgii).",
    mi: "Summer visitor, May–October.",
    fo: "Fish.",
    br: "Nests at the water’s edge on islands; 2 eggs.",
    be: "Very awkward on land; dives deep.",
    v: "A haunting, far-carrying wail.",
    cu: "Its wailing call is a symbol of wild northern lakes.",
    co: "Least Concern.",
    w: "Terkhiin Tsagaan Nuur and Ögii Nuur in June.",
    bt: "June–July",
    fa: ["Can stay underwater for two minutes.", "Can hardly walk on land.", "Its call is haunting."]
  },
  "dalmatian-pelican": {
    T: { c: { white: 0.75, gray: 0.15, yellow: 0.1 }, hb: ["water"], bk: "pouch", bh: ["swim", "soar"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["160–183 cm", "270–345 cm", "7–15 kg"] },
    s: "One of the largest flying birds, silvery white with curly nape feathers and an orange pouch in spring. Once bred in western Mongolia; now a very rare visitor.",
    d: "The Dalmatian Pelican breeds in scattered colonies from south-east Europe to Mongolia and China. The Mongolian population, which bred at Khar Us Nuur and other western lakes, has almost disappeared — it was estimated at only a few pairs. Poaching for its bill (used as a horse comb) and disturbance were major causes. There are now only occasional records in the west and the Gobi.",
    f: ["Huge, silvery-white bird.", "Curly feathers on the head and nape.", "Grey legs.", "Bright orange-red pouch in breeding season.", "In flight, underwings whitish with grey flight feathers."],
    si: "Great White Pelican — pinker, with black flight feathers and pink legs (not recorded in Mongolia). Swans — long necks, no pouch.",
    h: "Large lakes with reedbeds and islands.",
    di: "Very rare; western lakes (Khar Us Nuur, Achit Nuur) and Gobi (Böön Tsagaan).",
    mi: "Summer visitor, May–September.",
    fo: "Fish.",
    br: "Colonial on islands or reed mats; 2 eggs.",
    be: "Fishes cooperatively; soars on thermals.",
    v: "Silent except for grunts at colonies.",
    cu: "Mongolian herders used its upper bill as a horse comb (khusuur), which led to its persecution.",
    co: "Near Threatened; Critically Endangered in Mongolia.",
    w: "Rare — report any sightings to conservation authorities.",
    bt: "May–September",
    fa: ["Among the heaviest flying birds.", "Its bill was used as a horse comb.", "The Mongolian population is almost gone."]
  },
  "great-cormorant": {
    T: { c: { black: 0.8, white: 0.15, yellow: 0.05 }, hb: ["water"], bk: "hooked", bh: ["swim", "perch"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["77–94 cm", "121–149 cm", "1.8–3.6 kg"] },
    s: "A big, black fish-eating bird that dives from the surface and stands with wings spread to dry. Very common on Mongolian lakes and rivers.",
    d: "The Great Cormorant is found across Europe, Asia, Africa and Australia. It hunts fish underwater, propelled by its feet. Its feathers get wet, so it hangs its wings out to dry. In Mongolia it breeds in large colonies on islands and in trees at Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Buir Nuur and many other lakes.",
    f: ["Large and black with a bronze sheen.", "White cheeks and throat; white thigh patch in spring.", "Long, hook-tipped bill with yellow skin at the base.", "Swims low with the bill tilted up.", "Flies with neck outstretched, often in lines."],
    si: "Black-throated Diver — straight bill, chequered back. Geese — shorter necks, fly in V’s.",
    h: "Lakes and large rivers with fish.",
    di: "All regions: Ögii Nuur, Khar Us Nuur, Ulaanbaatar (Tuul River), Böön Tsagaan, Khurkh, Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Fish.",
    br: "Colonial; nests of sticks in trees or on the ground; 3–4 eggs.",
    be: "Dives from the surface; stands with wings spread.",
    v: "Grunting and croaking at colonies.",
    cu: "In China and Japan fishermen train cormorants to catch fish.",
    co: "Least Concern.",
    w: "Ögii Nuur colonies in summer.",
    bt: "May–September",
    fa: ["Dries its wings in the sun.", "Trained to fish in China.", "Swims underwater with its feet."]
  },
  "greater-flamingo": {
    T: { c: { white: 0.5, red: 0.3, black: 0.1, gray: 0.1 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["honk"], ac: "day", se: ["passage"], sz: ["120–145 cm", "140–165 cm", "2–4 kg"] },
    s: "A tall, pinkish-white bird with a bent bill and very long legs. A vagrant to Mongolia, recorded at Ögii Nuur.",
    d: "The Greater Flamingo lives on salt lakes and lagoons from the Mediterranean and Africa to Kazakhstan and India. It filters small shrimp and algae with its bent bill, feeding upside down. Mongolia is far from its range; there is a record of several birds at Ögii Nuur in September 2016.",
    f: ["Very tall, with an extremely long neck and legs.", "Pale pink-white plumage; red and black wings in flight.", "Pink bill with a black tip, bent downward.", "Pink legs."],
    si: "Unmistakable in Mongolia.",
    h: "Salt lakes and shallow lagoons.",
    di: "Vagrant; Ögii Nuur.",
    mi: "Vagrant.",
    fo: "Brine shrimp, algae and small invertebrates.",
    br: "Mud-mound nests in huge colonies (not in Mongolia).",
    be: "Feeds with its head upside down.",
    v: "Goose-like honking.",
    cu: "Its pink colour comes from pigments in its food.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Feeds upside down.", "Pink from its food.", "Stands on one leg to save heat."]
  }
});
