B2T("fr", {
  "little-grebe": {
    name: "Grèbe castagneux",
    s: "Minuscule grèbe tout rond, aux joues marron et à la tache jaune vif à la base du bec. Visiteur d’été des petits étangs à roseaux.",
    d: "Le Grèbe castagneux est présent en Europe, en Asie et en Afrique. Il plonge sans cesse pour attraper petits poissons et insectes et se cache dans les roseaux au moindre danger. En Mongolie, il niche sur les petits lacs et étangs riches en végétation, de la vallée de Khurkh et d’Oulan-Bator aux oasis du Gobi comme Yolyn Am et au lac Ganga dans l’est.",
    f: ["Très petit et rond, arrière duveteux.", "Nuptial : brun foncé, joues et cou marron.", "Tache jaune-vert vif à la base du bec.", "Hiver : chamois-brun uni.", "Plonge avec un petit saut."],
    si: "Grèbe à cou noir — plus grand, cou noir, touffes dorées, œil rouge. Jeunes foulques — bec plus grand.",
    h: "Petits étangs, bras morts et bords de lacs à roseaux.",
    di: "Khentii (Khurkh), Oulan-Bator, Yolyn Am, lac Ganga, lac Khar Us, Khövsgöl.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Petits poissons, insectes et larves, escargots.",
    br: "Nid flottant ancré aux plantes ; 4 à 6 œufs, recouverts de végétation quand l’oiseau s’absente.",
    be: "Plonge souvent ; court sur l’eau lors des poursuites territoriales.",
    v: "Un long trille hennissant.",
    cu: "Son nom vient de son chant qui rappelle des castagnettes.",
    co: "Préoccupation mineure.",
    w: "Petits étangs de Yolyn Am et de la vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Le plus petit grèbe de Mongolie.", "Couvre ses œufs de végétation.", "Son trille rappelle un hennissement."]
  },
  "red-necked-grebe": {
    name: "Grèbe jougris",
    s: "Grèbe trapu au cou marron, aux joues gris pâle et au bec à base jaune. Visiteur d’été local, surtout sur les lacs de l’est de la Mongolie.",
    d: "Le Grèbe jougris niche sur les lacs peu profonds et végétalisés du nord de l’Eurasie et de l’Amérique du Nord. En Mongolie, il niche surtout dans l’est, en particulier au lac Buir et sur d’autres lacs du Dornod, en plus petit nombre dans le Khentii et près d’Oulan-Bator.",
    f: ["Cou et haut de la poitrine roux marron en été.", "Joues gris pâle bordées de blanc.", "Calotte noire.", "Bec en poignard, noir à base jaune.", "Plus massif que les autres petits grèbes."],
    si: "Grèbe huppé — plus grand, face blanche à collerette orange, bec rose. Grèbe esclavon — plus petit, « cornes » dorées.",
    h: "Lacs peu profonds avec roseaux et végétation flottante.",
    di: "Dornod (lac Buir), Khentii (Khurkh, Onon), région d’Oulan-Bator.",
    mi: "Visiteur d’été, mai–octobre.",
    fo: "Poissons, insectes, crustacés et mollusques.",
    br: "Nid flottant ; 3 à 5 œufs ; les poussins montent sur le dos des parents.",
    be: "Parades bruyantes avec des cris braillés.",
    v: "Gémissements et braiments sonores au printemps.",
    cu: "Les poussins voyagent sur le dos des parents les premières semaines.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en juin–juillet.",
    bt: "juin–juil.",
    fa: ["Très bruyant au printemps.", "Porte ses poussins sur le dos.", "Surtout dans l’est de la Mongolie."]
  },
  "great-crested-grebe": {
    name: "Grèbe huppé",
    s: "Grèbe élégant au long cou, à huppe noire et collerette orange et noire. Le grèbe le plus commun des grands lacs mongols.",
    d: "Le Grèbe huppé niche de l’Europe à l’Asie, ainsi qu’en Afrique et en Australie. Il est célèbre pour sa parade de la « danse des algues », où les deux oiseaux se dressent poitrine contre poitrine en tenant des plantes aquatiques. En Mongolie, il niche sur les lacs à roseaux de tout le pays, en grand nombre aux lacs Ögii, Khar Us, Böön Tsagaan, Orog et Buir.",
    f: ["Long cou blanc et face blanche.", "Huppe noire et collerette orange-marron bordée de noir en été.", "Bec rose en poignard.", "Dos brun-gris.", "Hiver : gris et blanc uni, blanc au-dessus de l’œil."],
    si: "Grèbe jougris — plus petit, cou marron, joues grises. Plongeon arctique — plus grand et lourd, bec droit noir.",
    h: "Grands lacs bordés de roseaux.",
    di: "Khangaï (lac Ögii), lac Khar Us, étangs d’Oulan-Bator, lacs du Gobi (Böön Tsagaan, Orog), lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Poissons ; aussi insectes et crustacés.",
    br: "Nid flottant dans les roseaux ; 3 à 5 œufs ; poussins rayés portés sur le dos des parents.",
    be: "Parade élaborée avec hochements de tête et « danse des algues ».",
    v: "Un « ra-ra-ra » rauque et grondant.",
    cu: "La mode victorienne de ses plumes l’a presque éliminé de Grande-Bretagne et a mené à la fondation de la RSPB.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai–juin, au pic des parades.",
    bt: "mai–juin",
    fa: ["Exécute une « danse des algues » en parade.", "Avale ses propres plumes pour protéger son estomac.", "Ses plumes servaient autrefois à la mode."]
  },
  "slavonian-grebe": {
    name: "Grèbe esclavon",
    s: "Petit grèbe aux « cornes » dorées, à tête noire et cou marron en été. Visiteur d’été répandu sur les lacs mongols, Vulnérable à l’échelle mondiale.",
    d: "Le Grèbe esclavon niche sur de petits lacs dans le nord de l’Eurasie et de l’Amérique du Nord. Il est désormais classé Vulnérable en raison de déclins en Amérique du Nord et en Europe. En Mongolie, il est répandu sur les lacs végétalisés du Khangaï, du Khentii et des steppes de l’est, avec de bons effectifs au lac Ögii et dans la vallée de Khurkh.",
    f: ["Tête noire avec des « cornes » jaune doré de l’œil à la nuque.", "Cou et flancs roux marron.", "Bec court, droit et noir à pointe pâle.", "Œil rouge.", "Hiver : noir et blanc, calotte noire bien délimitée."],
    si: "Grèbe à cou noir — cou noir, éventail doré derrière l’œil, bec retroussé. Grèbe jougris — plus grand, joues grises.",
    h: "Petits et moyens lacs à végétation émergente.",
    di: "Khangaï (lac Ögii), Khentii (Khurkh), Böön Tsagaan, région d’Oulan-Bator, Dornod.",
    mi: "Visiteur d’été, mai–octobre.",
    fo: "Insectes aquatiques, petits poissons et crustacés.",
    br: "Nid flottant ; 3 à 5 œufs.",
    be: "Parade de la « danse du pingouin », les deux oiseaux dressés.",
    v: "Trilles et cris aigus au printemps.",
    cu: "Son nom évoque les terres slaves où il fut décrit.",
    co: "Vulnérable.",
    w: "Lac Ögii en juin.",
    bt: "juin–août",
    fa: ["Vulnérable à l’échelle mondiale.", "« Cornes » dorées en plumage nuptial.", "Les poussins voyagent sur le dos des parents."]
  },
  "black-necked-grebe": {
    name: "Grèbe à cou noir",
    s: "Petit grèbe grégaire au cou noir, avec un éventail de plumes dorées derrière l’œil rouge et un bec légèrement retroussé. Commun sur les lacs du nord et du centre de la Mongolie.",
    d: "Le Grèbe à cou noir est le grèbe le plus nombreux au monde. Il niche souvent en colonies parmi les mouettes et les sternes. En Mongolie, il niche sur les lacs à roseaux, notamment dans la vallée de Khurkh, aux lacs Ögii, Khar Us et Buir.",
    f: ["Tête, cou et dos noirs en été.", "Éventail de plumes dorées derrière l’œil.", "Œil rouge vif.", "Bec noir légèrement retroussé.", "Flancs marron."],
    si: "Grèbe esclavon — cou marron, « cornes » dorées partant de l’œil, bec droit.",
    h: "Lacs et étangs peu profonds à roseaux, souvent avec des colonies de mouettes.",
    di: "Khentii (Khurkh), lac Ögii, lac Khar Us, lac Buir, région d’Oulan-Bator.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Insectes aquatiques, larves, petits crustacés.",
    br: "Colonial ; nids flottants ; 3 ou 4 œufs.",
    be: "Grégaire ; forme colonies et groupes.",
    v: "Un doux sifflement montant « pou-iit ».",
    cu: "Certaines populations muent sur des lacs salés et ne peuvent plus voler pendant deux mois.",
    co: "Préoccupation mineure.",
    w: "Lacs de la vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Le grèbe le plus nombreux au monde.", "Niche en colonies.", "Peut rester des semaines sans voler pendant la mue."]
  },
  "red-throated-diver": {
    name: "Plongeon catmarin",
    s: "Le plus petit des plongeons, au bec fin retroussé et à la tache gulaire rouge sombre en été. Migrateur rare dans le nord et l’est de la Mongolie.",
    d: "Le Plongeon catmarin niche sur les petites mares de la toundra arctique et hiverne en mer. C’est le seul plongeon capable de s’envoler depuis la terre ferme. En Mongolie, c’est un migrateur rare, avec quelques mentions en mai–juin et en octobre.",
    f: ["Tête et cou fins, gris pâle en été.", "Tache gulaire rouge sombre.", "Bec fin légèrement retroussé, tenu pointé vers le haut.", "Dos gris-brun uni, finement piqueté de blanc en hiver.", "Nage bas sur l’eau."],
    si: "Plongeon arctique — plus grand, gorge noire, dos en damier, bec droit. Grèbes — plus petits, plongent avec un saut.",
    h: "Lacs et rivières en migration.",
    di: "Rare ; Khentii et Dornod.",
    mi: "Migrateur de passage, mai–juin et octobre.",
    fo: "Poissons.",
    br: "Niche sur les mares arctiques (pas en Mongolie).",
    be: "Plonge longuement.",
    v: "Caquètements et gémissements d’oie sur les sites de nidification.",
    cu: "En Écosse, les pêcheurs croyaient que son cri annonçait la pluie — l’« oie de pluie ».",
    co: "Préoccupation mineure.",
    w: "Examinez les lacs de l’est en mai.",
    bt: "mai",
    fa: ["Le plus petit plongeon.", "Peut décoller de la terre ferme.", "Surnommé l’« oie de pluie »."]
  },
  "black-throated-diver": {
    name: "Plongeon arctique",
    s: "Superbe plongeon à tête grise, gorge noire et dos noir damé de blanc. Niche sur les grands lacs de montagne de l’ouest de la Mongolie et du Khangaï.",
    d: "Le Plongeon arctique niche sur les grands lacs profonds du nord de l’Eurasie et hiverne en mer. Il plonge pour pêcher et peut rester deux minutes sous l’eau. En Mongolie, il niche sur les lacs du Khangaï (Ögii, Terkhiin Tsagaan), du Khövsgöl et de l’Altaï au Bayan-Ölgii.",
    f: ["Tête et arrière du cou gris doux.", "Tache gulaire noire bordée de stries blanches.", "Dos noir avec des rangées de carrés blancs.", "Bec droit et noir en poignard.", "Nage bas sur l’eau."],
    si: "Plongeon catmarin — plus petit, gorge rouge, bec retroussé. Grèbe huppé — plus fin, face blanche, collerette orange.",
    h: "Grands lacs profonds et limpides.",
    di: "Khangaï (lacs Ögii, Terkhiin Tsagaan), Khövsgöl, lac Khar Us, lacs de l’Altaï (Bayan-Ölgii).",
    mi: "Visiteur d’été, mai–octobre.",
    fo: "Poissons.",
    br: "Niche au bord de l’eau sur des îlots ; 2 œufs.",
    be: "Très maladroit à terre ; plonge profondément.",
    v: "Un gémissement obsédant qui porte loin.",
    cu: "Son cri plaintif symbolise les lacs sauvages du Nord.",
    co: "Préoccupation mineure.",
    w: "Terkhiin Tsagaan Nuur et lac Ögii en juin.",
    bt: "juin–juil.",
    fa: ["Peut rester deux minutes sous l’eau.", "Marche à peine sur la terre ferme.", "Son chant est obsédant."]
  },
  "dalmatian-pelican": {
    name: "Pélican frisé",
    s: "L’un des plus grands oiseaux volants, blanc argenté avec des plumes frisées sur la nuque et une poche orange au printemps. Il nichait jadis dans l’ouest de la Mongolie ; c’est désormais un visiteur très rare.",
    d: "Le Pélican frisé niche en colonies dispersées du sud-est de l’Europe à la Mongolie et à la Chine. La population mongole, qui nichait au lac Khar Us et sur d’autres lacs de l’ouest, a presque disparu — on l’estimait à quelques couples seulement. Le braconnage pour son bec (utilisé comme racloir à chevaux) et le dérangement en sont les principales causes. Il n’y a plus que des mentions occasionnelles dans l’ouest et le Gobi.",
    f: ["Énorme oiseau blanc argenté.", "Plumes frisées sur la tête et la nuque.", "Pattes grises.", "Poche rouge orangé vif en période nuptiale.", "En vol, dessous des ailes blanchâtre à rémiges grises."],
    si: "Pélican blanc — plus rosé, rémiges noires, pattes roses (non noté en Mongolie). Cygnes — long cou, sans poche.",
    h: "Grands lacs avec roselières et îlots.",
    di: "Très rare ; lacs de l’ouest (Khar Us, Achit) et Gobi (Böön Tsagaan).",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Poissons.",
    br: "Colonial sur des îlots ou des radeaux de roseaux ; 2 œufs.",
    be: "Pêche en groupe ; plane dans les ascendances.",
    v: "Silencieux sauf grognements aux colonies.",
    cu: "Les éleveurs mongols utilisaient la mandibule supérieure comme racloir à sueur pour chevaux (khusuur), ce qui a entraîné sa persécution.",
    co: "Quasi menacé ; en danger critique en Mongolie.",
    w: "Rare — signalez toute observation aux autorités de conservation.",
    bt: "mai–sept.",
    fa: ["Parmi les oiseaux volants les plus lourds.", "Son bec servait de racloir à chevaux.", "La population mongole a presque disparu."]
  },
  "great-cormorant": {
    name: "Grand Cormoran",
    s: "Grand oiseau noir piscivore qui plonge depuis la surface et se tient ailes écartées pour les sécher. Très commun sur les lacs et rivières de Mongolie.",
    d: "Le Grand Cormoran est présent en Europe, en Asie, en Afrique et en Australie. Il chasse les poissons sous l’eau en se propulsant avec les pattes. Ses plumes se mouillent, d’où l’habitude de sécher ses ailes. En Mongolie, il niche en grandes colonies sur des îlots et dans les arbres aux lacs Ögii, Khar Us, Böön Tsagaan, Buir et bien d’autres.",
    f: ["Grand et noir à reflets bronze.", "Joues et gorge blanches ; tache blanche sur la cuisse au printemps.", "Long bec crochu avec peau jaune à la base.", "Nage bas, bec pointé vers le haut.", "Vole cou tendu, souvent en lignes."],
    si: "Plongeon arctique — bec droit, dos en damier. Oies — cou plus court, vol en V.",
    h: "Lacs et grandes rivières poissonneux.",
    di: "Toutes les régions : lac Ögii, lac Khar Us, Oulan-Bator (rivière Tuul), Böön Tsagaan, Khurkh, lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Poissons.",
    br: "Colonial ; nid de branches dans les arbres ou au sol ; 3 ou 4 œufs.",
    be: "Plonge depuis la surface ; se tient ailes déployées.",
    v: "Grognements et croassements aux colonies.",
    cu: "En Chine et au Japon, des pêcheurs dressent des cormorans à pêcher.",
    co: "Préoccupation mineure.",
    w: "Colonies du lac Ögii en été.",
    bt: "mai–sept.",
    fa: ["Sèche ses ailes au soleil.", "Dressé pour pêcher en Chine.", "Nage sous l’eau avec ses pattes."]
  },
  "greater-flamingo": {
    name: "Flamant rose",
    s: "Grand oiseau blanc rosé au bec coudé et aux très longues pattes. Erratique en Mongolie, noté au lac Ögii.",
    d: "Le Flamant rose vit sur les lacs salés et les lagunes, de la Méditerranée et de l’Afrique au Kazakhstan et à l’Inde. Il filtre petites crevettes et algues avec son bec coudé, tête à l’envers. La Mongolie est loin de son aire ; plusieurs oiseaux ont été notés au lac Ögii en septembre 2016.",
    f: ["Très grand, cou et pattes extrêmement longs.", "Plumage blanc rosé pâle ; ailes rouges et noires en vol.", "Bec rose à pointe noire, coudé vers le bas.", "Pattes roses."],
    si: "Inconfondable en Mongolie.",
    h: "Lacs salés et lagunes peu profondes.",
    di: "Erratique ; lac Ögii.",
    mi: "Erratique.",
    fo: "Artémies, algues et petits invertébrés.",
    br: "Nids en monticules de boue dans d’immenses colonies (pas en Mongolie).",
    be: "Se nourrit la tête à l’envers.",
    v: "Cacardements d’oie.",
    cu: "Sa couleur rose provient des pigments de sa nourriture.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Se nourrit la tête à l’envers.", "Rose grâce à sa nourriture.", "Se tient sur une patte pour économiser la chaleur."]
  }
});
