B2T("en", {
  "eurasian-bittern": {
    T: { c: { brown: 0.5, buff: 0.35, black: 0.15 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["69–81 cm", "100–130 cm", "0.9–1.9 kg"] },
    s: "A stocky, streaky brown heron of dense reedbeds, famous for the male’s deep, booming call. A summer visitor to reedy lakes across Mongolia.",
    d: "The Eurasian Bittern breeds from Europe to eastern Asia in large reedbeds. It is superbly camouflaged and, when alarmed, freezes with its bill pointed skywards, swaying like the reeds. Males ‘boom’ in spring with a sound that carries for several kilometres. In Mongolia it breeds in the reedbeds of Dornod, Khentii (Khurkh), the Gobi lakes (Orog Nuur) and Khar Us Nuur.",
    f: ["Golden-brown, heavily streaked and barred with black.", "Black crown and moustache.", "Thick neck and dagger-like yellowish bill.", "Green legs.", "Points its bill upward and sways when alarmed."],
    si: "Black-crowned Night Heron (juvenile) — spotted with white, red eye. Grey Heron — larger, grey.",
    h: "Large, dense reedbeds.",
    di: "Dornod (Buir Nuur, Ganga Nuur), Khentii (Khurkh), Orog Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Fish, frogs, insects and small mammals.",
    br: "Nests on a platform of reeds; 4–6 eggs.",
    be: "Stalks slowly in reeds; freezes when disturbed.",
    v: "A deep, far-carrying ‘boom’, like blowing across a bottle.",
    cu: "In many languages it is named after a bull because of its boom.",
    co: "Least Concern.",
    w: "Listen at dawn in May at the Khurkh valley reedbeds.",
    bt: "May–June",
    fa: ["Its boom carries up to 5 km.", "Sways with the reeds to hide.", "Named ‘water bull’ in Mongolian."]
  },
  "little-bittern": {
    T: { c: { black: 0.35, buff: 0.4, brown: 0.25 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["27–38 cm", "40–58 cm", "60–150 g"] },
    s: "A tiny heron with a black back and a large buff wing patch. Listed for western Mongolia, but no GBIF records — very rare.",
    d: "The Little Bittern breeds from Europe to Central Asia and winters in Africa. It clambers through reeds and is rarely seen in the open. It is known in Mongolia from very few records in the west.",
    f: ["Very small heron.", "Male: black crown and back, pale buff neck and a big pale wing panel.", "Female: browner and streaked.", "Yellow bill and legs."],
    si: "Schrenck’s Bittern — male chestnut above. Chinese Pond Heron — white wings in flight.",
    h: "Reedbeds and willow thickets by water.",
    di: "Very rare; western Mongolia.",
    mi: "Summer visitor.",
    fo: "Small fish, frogs and insects.",
    br: "Nests in reeds (not confirmed in Mongolia).",
    be: "Climbs reed stems like a rail.",
    v: "A deep, repeated ‘hogh’.",
    cu: "One of the smallest herons in the world.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["One of the smallest herons.", "Climbs reeds.", "Winters in Africa."]
  },
  "shrencks-bittern": {
    T: { c: { rufous: 0.45, buff: 0.3, black: 0.15, white: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["33–39 cm", "—", "100–140 g"] },
    s: "A small East Asian bittern; the male has a rich chestnut back. Listed for Mongolia, with no GBIF records — a very rare visitor.",
    d: "Von Schrenck’s Bittern breeds in eastern China, Korea, Japan and the Russian Far East and winters in South-East Asia. It is Near Threatened because of wetland loss. Mongolian records are exceptional.",
    f: ["Male: dark chestnut above, buff below with a dark central stripe.", "Female: chestnut with white spots above.", "Grey flight feathers in flight.", "Small and compact."],
    si: "Little Bittern — male black above with a pale wing patch.",
    h: "Wet paddies, reedy marshes.",
    di: "Exceptional; probably the far east.",
    mi: "Summer visitor.",
    fo: "Small fish, frogs and insects.",
    br: "Nests in marsh vegetation (not in Mongolia).",
    be: "Secretive.",
    v: "A low ‘gup-gup’.",
    cu: "Named after the Baltic-German explorer Leopold von Schrenck.",
    co: "Near Threatened.",
    w: "Not expected.",
    bt: "—",
    fa: ["Near Threatened.", "Named after an explorer of the Amur.", "Male is chestnut."]
  },
  "black-crowned-night-heron": {
    T: { c: { gray: 0.4, black: 0.3, white: 0.25, red: 0.05 }, hb: ["water"], bk: "long", bh: ["perch", "walk", "night"], vt: ["croak"], ac: "night", se: ["summer"], sz: ["58–65 cm", "105–112 cm", "0.5–0.8 kg"] },
    s: "A stocky, short-necked heron with a black cap and back, grey wings and red eyes, most active at dusk. A scarce summer visitor, mainly to Gobi wetlands.",
    d: "The Black-crowned Night Heron is found on every continent except Australia and Antarctica. It roosts in trees by day and feeds at dusk and at night. In Mongolia it is found mostly at Gobi lakes and oases — Böön Tsagaan, Orog Nuur, Yolyn Am — with scattered records elsewhere.",
    f: ["Black crown and back, grey wings, white underparts.", "Two long white plumes on the nape in spring.", "Red eyes.", "Short, thick neck; hunched posture.", "Juvenile: brown, spotted with white."],
    si: "Eurasian Bittern — streaked golden-brown (like a juvenile night heron). Grey Heron — much larger, long neck.",
    h: "Lakes, marshes and rivers with trees or reeds for roosting.",
    di: "Gobi (Böön Tsagaan, Yolyn Am, Orog Nuur), Ulaanbaatar, Ganga Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Fish, frogs, insects.",
    br: "Colonial in trees or reeds; 3–5 eggs.",
    be: "Roosts in groups in trees by day; hunts at dusk.",
    v: "A harsh ‘kwok’ in flight at night.",
    cu: "Its scientific name Nycticorax means ‘night raven’.",
    co: "Least Concern.",
    w: "Böön Tsagaan Nuur at dusk in June.",
    bt: "May–June",
    fa: ["Its name means ‘night raven’.", "Found on five continents.", "Feeds mostly at night."]
  },
  "striated-heron": {
    T: { c: { gray: 0.5, black: 0.25, yellow: 0.1, white: 0.15 }, hb: ["water"], bk: "long", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["35–48 cm", "52–60 cm", "135–300 g"] },
    s: "A small, dark grey heron with a black cap and yellow legs. A rare visitor to Mongolia, mostly at the Yolyn Am oasis.",
    d: "The Striated Heron is widespread in the tropics of Asia, Africa, Australia and South America; the East Asian population breeds north to the Amur. It is known for using bait — dropping insects or bread on the water to lure fish. In Mongolia it is a rare vagrant, with most records at Yolyn Am in the Gobi.",
    f: ["Small, hunched heron.", "Dark grey-green back, grey neck and underparts.", "Black cap with a short crest.", "Yellow legs and eye.", "Juvenile streaked brown."],
    si: "Black-crowned Night Heron — larger, black back, white underparts, red eye.",
    h: "Streams, ponds and shores with overhanging vegetation.",
    di: "Rare; Gobi (Yolyn Am), east.",
    mi: "Vagrant or rare migrant, May–August.",
    fo: "Small fish, frogs and insects.",
    br: "Nests in trees near water (not in Mongolia).",
    be: "Crouches motionless at the water’s edge.",
    v: "A sharp ‘kyow’ when flushed.",
    cu: "One of the few birds known to fish with bait.",
    co: "Least Concern.",
    w: "Check the Yolyn Am stream in June.",
    bt: "June",
    fa: ["Uses bait to catch fish.", "Found on five continents.", "Crouches very still."]
  },
  "chinese-pond-heron": {
    T: { c: { white: 0.45, rufous: 0.25, gray: 0.2, brown: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage", "summer"], sz: ["42–52 cm", "79–90 cm", "250–320 g"] },
    s: "A small heron that looks brown when standing but explodes into white when it flies; breeding birds have a maroon head and slate-grey back. A scarce spring migrant, mostly to Gobi oases.",
    d: "The Chinese Pond Heron breeds in China, Korea and Japan and winters in South-East Asia. It is spreading northward. In Mongolia it is a scarce but increasing migrant in May–June, most often at Yolyn Am and other Gobi oases, with some records in the Khurkh valley.",
    f: ["Breeding: maroon head and neck, slate-grey back.", "White wings, belly and tail — visible in flight.", "Non-breeding: brown streaked head, brownish back.", "Yellow bill with a dark tip; yellow legs."],
    si: "Little Egret — all white with black legs. Cattle Egret — all white, short neck.",
    h: "Ponds, marshes, streams and wet fields.",
    di: "Gobi oases (Yolyn Am, Böön Tsagaan, Orog Nuur), Khurkh valley.",
    mi: "Migrant, May–June; occasional in summer.",
    fo: "Fish, frogs and insects.",
    br: "Colonial in trees (not confirmed in Mongolia).",
    be: "Stands still on the bank; flushes in a burst of white.",
    v: "Mostly silent; a squawk when flushed.",
    cu: "Its sudden flash of white wings startles people walking by paddies.",
    co: "Least Concern.",
    w: "Yolyn Am in late May.",
    bt: "May–June",
    fa: ["Brown at rest, white in flight.", "Spreading northward.", "Increasing in Mongolia."]
  },
  "cattle-egret": {
    T: { c: { white: 0.8, buff: 0.15, yellow: 0.05 }, hb: ["steppe", "water"], bk: "long", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["46–56 cm", "88–96 cm", "300–400 g"] },
    s: "A small, stocky white heron that follows livestock; breeding birds have orange-buff plumes. A rare vagrant to Mongolia with no GBIF records.",
    d: "The Cattle Egret has spread across the world in the last century, following cattle to catch the insects they disturb. The eastern form breeds in South and East Asia. It is a very rare visitor to Mongolia.",
    f: ["Compact white egret with a short, thick neck.", "Short yellow bill.", "Orange-buff crown, breast and back in breeding plumage.", "Yellowish or dark legs."],
    si: "Little Egret — slimmer, black bill, black legs with yellow feet. Great Egret — much larger.",
    h: "Pastures and fields with livestock.",
    di: "Very rare vagrant.",
    mi: "Vagrant.",
    fo: "Grasshoppers, flies and other insects disturbed by livestock.",
    br: "Colonial in trees (not in Mongolia).",
    be: "Walks beside cattle and horses.",
    v: "Mostly silent.",
    cu: "It spread to the Americas on its own in the 19th century.",
    co: "Least Concern.",
    w: "Not expected — check around herds.",
    bt: "—",
    fa: ["Follows livestock.", "Colonised the Americas by itself.", "Feeds on dry land."]
  },
  "grey-heron": {
    T: { c: { gray: 0.55, white: 0.3, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "long", bh: ["walk", "soar"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["84–102 cm", "155–195 cm", "1–2 kg"] },
    s: "A tall, grey heron that stands motionless in the shallows. The most common heron in Mongolia, found at lakes and rivers throughout the country.",
    d: "The Grey Heron is found across Europe, Asia and Africa. It waits patiently at the water’s edge and strikes at fish with its dagger-like bill. It flies with slow wingbeats and its neck drawn in. In Mongolia it breeds in colonies in trees or reeds along rivers and lakes and is found in all regions from March to October.",
    f: ["Tall grey heron with a long neck and legs.", "White head and neck with a black stripe from the eye to a long plume.", "Yellow dagger-like bill.", "Black flight feathers contrast with grey wing coverts in flight.", "Flies with neck retracted."],
    si: "Purple Heron — slimmer, chestnut neck with black stripes. Common Crane — flies with neck outstretched; no dagger bill.",
    h: "Lakes, rivers, marshes and fish ponds.",
    di: "All regions: Khurkh, Ögii Nuur, Khar Us Nuur, Ulaanbaatar (Tuul River), Böön Tsagaan, Buir Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Fish, frogs, voles and insects.",
    br: "Colonial; stick nests in tall trees or reeds; 3–5 eggs.",
    be: "Stands motionless for long periods; stalks slowly.",
    v: "A harsh ‘fraank’ in flight.",
    cu: "A symbol of patience in many cultures.",
    co: "Least Concern.",
    w: "Any lake or river in summer.",
    bt: "May–September",
    fa: ["Can stand still for hours.", "Flies with neck folded.", "Nests in colonies."]
  },
  "purple-heron": {
    T: { c: { rufous: 0.4, gray: 0.35, black: 0.2, buff: 0.05 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["78–97 cm", "120–152 cm", "0.5–1.35 kg"] },
    s: "A slim, snake-necked heron with a chestnut neck striped with black. A rare migrant to Mongolian wetlands.",
    d: "The Purple Heron breeds in dense reedbeds from Europe and Africa to East Asia. It is shyer than the Grey Heron and hides in tall vegetation. In Mongolia there are only a few records, in the east, the Gobi and the west.",
    f: ["Slim, with a thin, snake-like neck.", "Chestnut neck with black stripes.", "Dark grey back, chestnut belly.", "Long yellow bill.", "Long toes stick out behind in flight."],
    si: "Grey Heron — larger, paler, white neck.",
    h: "Dense reedbeds.",
    di: "Rare; Khar Us Nuur, Buir Nuur, Böön Tsagaan, Ulaanbaatar.",
    mi: "Rare migrant, April–September.",
    fo: "Fish, frogs, insects.",
    br: "Nests in reeds (not confirmed in Mongolia).",
    be: "Shy; stalks within reedbeds.",
    v: "A harsh croak.",
    cu: "Its species name purpurea means ‘purple’.",
    co: "Least Concern.",
    w: "Scan reedbeds at Khar Us Nuur.",
    bt: "May, August",
    fa: ["Has a snake-like neck.", "Hides in reeds.", "Rare in Mongolia."]
  },
  "great-egret": {
    T: { c: { white: 0.9, yellow: 0.05, black: 0.05 }, hb: ["water"], bk: "long", bh: ["walk", "soar"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["80–104 cm", "131–170 cm", "0.7–1.5 kg"] },
    s: "A tall, elegant, pure white heron with a long neck and yellow bill. A summer visitor, most common in western Mongolia and the Gobi lakes.",
    d: "The Great Egret is found on all warm and temperate continents. It was hunted almost to extinction for its plumes in the 19th century but has recovered. In Mongolia it breeds at the western lakes (Khar Us Nuur), the Gobi lakes (Böön Tsagaan, Orog Nuur) and Ögii Nuur, and is spreading.",
    f: ["Large, all white heron — almost as big as a Grey Heron.", "Long neck with a kink.", "Yellow bill (black in breeding season).", "Long black legs.", "Gape line extends behind the eye."],
    si: "Little Egret — much smaller, black bill, yellow feet. Cattle Egret — small, stocky.",
    h: "Lakes, marshes and river shallows.",
    di: "Khar Us Nuur, Böön Tsagaan, Orog Nuur, Ögii Nuur, Achit Nuur, Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Fish, frogs, insects.",
    br: "Colonial in reeds or trees; 3–5 eggs.",
    be: "Stalks slowly in shallow water.",
    v: "A low, croaking ‘krrak’.",
    cu: "Its recovery helped launch the bird conservation movement in America.",
    co: "Least Concern.",
    w: "Khar Us Nuur in summer.",
    bt: "May–September",
    fa: ["Almost wiped out for its plumes.", "Symbol of the US National Audubon Society.", "Spreading north."]
  },
  "little-egret": {
    T: { c: { white: 0.85, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["55–65 cm", "88–106 cm", "350–550 g"] },
    s: "A slim, white egret with a black bill, black legs and bright yellow feet. A rare migrant to Gobi wetlands.",
    d: "The Little Egret is found across southern Europe, Africa, Asia and Australia and is spreading north. It dashes through the shallows, stirring up prey with its feet. In Mongolia there are only a few records, mostly at Gobi oases such as Yolyn Am and Böön Tsagaan.",
    f: ["Small white egret.", "Thin black bill.", "Black legs with yellow ‘slippers’.", "Two long plumes on the nape in spring.", "Active, dashing feeding style."],
    si: "Great Egret — much larger, yellow bill. Cattle Egret — stocky, yellow bill.",
    h: "Shallow lakes, streams and marshes.",
    di: "Rare; Yolyn Am, Böön Tsagaan, Orog Nuur, Ögii Nuur.",
    mi: "Rare migrant, May–June.",
    fo: "Small fish, shrimp, insects.",
    br: "Colonial in trees (not in Mongolia).",
    be: "Stirs the water with its feet.",
    v: "A gargling croak.",
    cu: "Its plumes were once worth more than gold by weight.",
    co: "Least Concern.",
    w: "Gobi oases in May.",
    bt: "May–June",
    fa: ["Has yellow feet.", "Stirs up prey with its toes.", "Its plumes were once worth more than gold."]
  },
  "black-headed-ibis": {
    T: { c: { white: 0.75, black: 0.25 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["65–76 cm", "110–125 cm", "1.3–1.8 kg"] },
    s: "A white ibis with a bare black head and neck and a long, down-curved bill. An exceptional vagrant to Mongolia with no GBIF records.",
    d: "The Black-headed Ibis breeds in South and South-East Asia. It is declining because of wetland loss. There are only historic reports from Mongolia.",
    f: ["White body.", "Bare black head and neck.", "Long, thick, down-curved black bill.", "Grey plumes on the back in breeding season."],
    si: "Eurasian Spoonbill — white, but with a spoon-shaped bill.",
    h: "Marshes and flooded fields.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Fish, frogs, insects and worms.",
    br: "Colonial in trees (not in Mongolia).",
    be: "Probes mud with its bill.",
    v: "Mostly silent.",
    cu: "Related to the Sacred Ibis of ancient Egypt.",
    co: "Declining because of wetland drainage and disturbance.",
    w: "Not expected.",
    bt: "—",
    fa: ["Head and neck are bare.", "Related to the Sacred Ibis.", "An Asian species."]
  },
  "eurasian-spoonbill": {
    T: { c: { white: 0.85, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "long", bh: ["walk", "soar"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["80–93 cm", "120–135 cm", "1.1–2 kg"] },
    s: "A white wading bird with a long, flat, spoon-shaped bill, sweeping it side to side in shallow water. A common summer visitor to lakes across Mongolia.",
    d: "The Eurasian Spoonbill breeds from Europe to eastern Asia. It feeds by sweeping its open bill through the water and snapping it shut on small fish and shrimp. Mongolia holds important breeding colonies: it is common at Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur and the Khurkh valley.",
    f: ["All white with a long black bill ending in a yellow ‘spoon’.", "Shaggy crest and yellow breast patch in breeding season.", "Black legs.", "Flies with neck outstretched, often in lines.", "Sweeps bill from side to side when feeding."],
    si: "Great Egret — pointed yellow bill, flies with neck drawn in. Swans — shorter legs, swim.",
    h: "Shallow lakes, marshes and river deltas with reedbeds or islands.",
    di: "All regions: Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khurkh.",
    mi: "Summer visitor, April–October.",
    fo: "Small fish, shrimp, insects and tadpoles.",
    br: "Colonial in reeds or on islands; 3–4 eggs.",
    be: "Feeds in groups; sleeps with bill tucked into feathers.",
    v: "Mostly silent; bill-clapping at colonies.",
    cu: "The Mongolian name compares its bill to a ladle.",
    co: "Least Concern.",
    w: "Ögii Nuur and Böön Tsagaan, May–August.",
    bt: "May–August",
    fa: ["Feeds by sweeping its bill.", "Its bill is shaped like a spoon.", "Common in Mongolia’s lakes."]
  }
});
