B2T("fr", {
  "eurasian-bittern": {
    name: "Butor étoilé",
    s: "Héron trapu brun strié des roselières denses, célèbre pour le chant grave et sourd du mâle. Visiteur d’été des lacs à roseaux de toute la Mongolie.",
    d: "Le Butor étoilé niche de l’Europe à l’Asie orientale dans les grandes roselières. Superbement camouflé, il se fige, bec pointé vers le ciel, en ondulant comme les roseaux lorsqu’il est inquiet. Au printemps, les mâles émettent un « mugissement » audible à plusieurs kilomètres. En Mongolie, il niche dans les roselières du Dornod, du Khentii (Khurkh), des lacs du Gobi (lac Orog) et du lac Khar Us.",
    f: ["Brun doré, fortement strié et barré de noir.", "Calotte et moustache noires.", "Cou épais et bec jaunâtre en poignard.", "Pattes vertes.", "Pointe le bec vers le haut et ondule quand il est inquiet."],
    si: "Bihoreau gris (juvénile) — tacheté de blanc, œil rouge. Héron cendré — plus grand, gris.",
    h: "Grandes roselières denses.",
    di: "Dornod (lacs Buir et Ganga), Khentii (Khurkh), lac Orog, lac Khar Us.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Poissons, grenouilles, insectes et petits mammifères.",
    br: "Niche sur une plateforme de roseaux ; 4 à 6 œufs.",
    be: "Se déplace lentement dans les roseaux ; se fige quand on le dérange.",
    v: "Un « bouh » grave qui porte loin, comme un souffle sur une bouteille.",
    cu: "Dans de nombreuses langues, son nom évoque un taureau à cause de son chant.",
    co: "Préoccupation mineure.",
    w: "Écoutez à l’aube en mai dans les roselières de Khurkh.",
    bt: "mai–juin",
    fa: ["Son chant porte jusqu’à 5 km.", "Ondule avec les roseaux pour se cacher.", "Appelé « taureau d’eau » en mongol."]
  },
  "little-bittern": {
    name: "Blongios nain",
    s: "Minuscule héron au dos noir et à la grande tache alaire chamois. Inscrit pour l’ouest de la Mongolie, mais sans mention GBIF — très rare.",
    d: "Le Blongios nain niche de l’Europe à l’Asie centrale et hiverne en Afrique. Il grimpe dans les roseaux et se montre rarement à découvert. Il n’est connu en Mongolie que par de très rares mentions dans l’ouest.",
    f: ["Très petit héron.", "Mâle : calotte et dos noirs, cou chamois pâle, grand panneau alaire pâle.", "Femelle : plus brune et striée.", "Bec et pattes jaunes."],
    si: "Blongios de Schrenck — mâle marron dessus. Crabier chinois — ailes blanches en vol.",
    h: "Roselières et saulaies au bord de l’eau.",
    di: "Très rare ; ouest de la Mongolie.",
    mi: "Visiteur d’été.",
    fo: "Petits poissons, grenouilles et insectes.",
    br: "Niche dans les roseaux (non confirmé en Mongolie).",
    be: "Grimpe aux tiges de roseaux comme un râle.",
    v: "Un « hogh » grave et répété.",
    cu: "L’un des plus petits hérons du monde.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["L’un des plus petits hérons.", "Grimpe dans les roseaux.", "Hiverne en Afrique."]
  },
  "shrencks-bittern": {
    name: "Blongios de Schrenck",
    s: "Petit blongios d’Asie orientale ; le mâle a le dos marron profond. Inscrit pour la Mongolie, sans mention GBIF — visiteur très rare.",
    d: "Le Blongios de Schrenck niche dans l’est de la Chine, en Corée, au Japon et dans l’Extrême-Orient russe, et hiverne en Asie du Sud-Est. Il est quasi menacé en raison de la perte des zones humides. Les mentions mongoles sont exceptionnelles.",
    f: ["Mâle : marron foncé dessus, chamois dessous avec une bande centrale sombre.", "Femelle : marron tacheté de blanc dessus.", "Rémiges grises en vol.", "Petit et compact."],
    si: "Blongios nain — mâle noir dessus avec un panneau alaire pâle.",
    h: "Rizières humides et marais à roseaux.",
    di: "Exceptionnel ; probablement l’extrême est.",
    mi: "Visiteur d’été.",
    fo: "Petits poissons, grenouilles et insectes.",
    br: "Niche dans la végétation des marais (pas en Mongolie).",
    be: "Discret.",
    v: "Un « goup-goup » grave.",
    cu: "Nommé d’après l’explorateur germano-balte Leopold von Schrenck.",
    co: "Quasi menacé.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Quasi menacé.", "Porte le nom d’un explorateur de l’Amour.", "Le mâle est marron."]
  },
  "black-crowned-night-heron": {
    name: "Bihoreau gris",
    s: "Héron trapu au cou court, à calotte et dos noirs, ailes grises et yeux rouges, surtout actif au crépuscule. Visiteur d’été peu commun, surtout dans les zones humides du Gobi.",
    d: "Le Bihoreau gris est présent sur tous les continents sauf l’Australie et l’Antarctique. Il se repose dans les arbres le jour et se nourrit au crépuscule et la nuit. En Mongolie, on le trouve surtout sur les lacs et oasis du Gobi — Böön Tsagaan, lac Orog, Yolyn Am — avec des mentions éparses ailleurs.",
    f: ["Calotte et dos noirs, ailes grises, dessous blanc.", "Deux longues plumes blanches sur la nuque au printemps.", "Yeux rouges.", "Cou court et épais ; posture voûtée.", "Juvénile : brun tacheté de blanc."],
    si: "Butor étoilé — brun doré strié (comme un jeune bihoreau). Héron cendré — bien plus grand, long cou.",
    h: "Lacs, marais et rivières avec arbres ou roseaux pour le repos.",
    di: "Gobi (Böön Tsagaan, Yolyn Am, lac Orog), Oulan-Bator, lac Ganga.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Poissons, grenouilles, insectes.",
    br: "Colonial dans les arbres ou les roseaux ; 3 à 5 œufs.",
    be: "Dort en groupe dans les arbres le jour ; chasse au crépuscule.",
    v: "Un « kouak » rauque en vol la nuit.",
    cu: "Son nom scientifique Nycticorax signifie « corbeau de nuit ».",
    co: "Préoccupation mineure.",
    w: "Lac Böön Tsagaan au crépuscule en juin.",
    bt: "mai–juin",
    fa: ["Son nom signifie « corbeau de nuit ».", "Présent sur cinq continents.", "Se nourrit surtout la nuit."]
  },
  "striated-heron": {
    name: "Héron strié",
    s: "Petit héron gris foncé à calotte noire et pattes jaunes. Visiteur rare en Mongolie, surtout à l’oasis de Yolyn Am.",
    d: "Le Héron strié est répandu dans les tropiques d’Asie, d’Afrique, d’Australie et d’Amérique du Sud ; la population d’Asie orientale niche jusqu’à l’Amour. Il est connu pour pêcher à l’appât — il dépose insectes ou pain sur l’eau pour attirer les poissons. En Mongolie, c’est un erratique rare, surtout noté à Yolyn Am dans le Gobi.",
    f: ["Petit héron voûté.", "Dos gris-vert foncé, cou et dessous gris.", "Calotte noire à courte huppe.", "Pattes et œil jaunes.", "Juvénile strié de brun."],
    si: "Bihoreau gris — plus grand, dos noir, dessous blanc, œil rouge.",
    h: "Ruisseaux, étangs et rives à végétation surplombante.",
    di: "Rare ; Gobi (Yolyn Am), est.",
    mi: "Erratique ou migrateur rare, mai–août.",
    fo: "Petits poissons, grenouilles et insectes.",
    br: "Niche dans les arbres près de l’eau (pas en Mongolie).",
    be: "Se tapit immobile au bord de l’eau.",
    v: "Un « kiaou » sec à l’envol.",
    cu: "L’un des rares oiseaux connus pour pêcher à l’appât.",
    co: "Préoccupation mineure.",
    w: "Vérifiez le ruisseau de Yolyn Am en juin.",
    bt: "juin",
    fa: ["Pêche à l’appât.", "Présent sur cinq continents.", "Se tapit sans bouger."]
  },
  "chinese-pond-heron": {
    name: "Crabier chinois",
    s: "Petit héron qui paraît brun au repos mais « explose » en blanc à l’envol ; en plumage nuptial, tête marron et dos gris ardoise. Migrateur printanier peu commun, surtout dans les oasis du Gobi.",
    d: "Le Crabier chinois niche en Chine, en Corée et au Japon et hiverne en Asie du Sud-Est ; il s’étend vers le nord. En Mongolie, c’est un migrateur peu commun mais en augmentation en mai–juin, surtout à Yolyn Am et dans d’autres oasis du Gobi, avec quelques mentions dans la vallée de Khurkh.",
    f: ["Nuptial : tête et cou marron foncé, dos gris ardoise.", "Ailes, ventre et queue blancs — visibles en vol.", "Internuptial : tête brune striée, dos brunâtre.", "Bec jaune à pointe sombre ; pattes jaunes."],
    si: "Aigrette garzette — entièrement blanche, pattes noires. Héron garde-bœufs — entièrement blanc, cou court.",
    h: "Étangs, marais, ruisseaux et champs humides.",
    di: "Oasis du Gobi (Yolyn Am, Böön Tsagaan, lac Orog), vallée de Khurkh.",
    mi: "Migrateur, mai–juin ; parfois en été.",
    fo: "Poissons, grenouilles et insectes.",
    br: "Colonial dans les arbres (non confirmé en Mongolie).",
    be: "Reste immobile sur la berge ; s’envole dans un éclair blanc.",
    v: "Surtout silencieux ; un cri rauque à l’envol.",
    cu: "Son brusque éclair blanc surprend les passants au bord des rizières.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am fin mai.",
    bt: "mai–juin",
    fa: ["Brun au repos, blanc en vol.", "S’étend vers le nord.", "En augmentation en Mongolie."]
  },
  "cattle-egret": {
    name: "Héron garde-bœufs",
    s: "Petit héron blanc trapu qui suit le bétail ; en plumage nuptial, plumes chamois orangé. Erratique rare en Mongolie, sans mention GBIF.",
    d: "Le Héron garde-bœufs s’est répandu dans le monde entier au siècle dernier, suivant le bétail pour attraper les insectes qu’il dérange. La forme orientale niche en Asie du Sud et de l’Est. C’est un visiteur très rare en Mongolie.",
    f: ["Aigrette blanche compacte au cou court et épais.", "Bec jaune court.", "Calotte, poitrine et dos chamois orangé en plumage nuptial.", "Pattes jaunâtres ou sombres."],
    si: "Aigrette garzette — plus fine, bec noir, pattes noires à pieds jaunes. Grande Aigrette — bien plus grande.",
    h: "Pâturages et champs avec bétail.",
    di: "Erratique très rare.",
    mi: "Erratique.",
    fo: "Sauterelles, mouches et autres insectes dérangés par le bétail.",
    br: "Colonial dans les arbres (pas en Mongolie).",
    be: "Marche à côté des bovins et des chevaux.",
    v: "Surtout silencieux.",
    cu: "A colonisé les Amériques par lui-même au XIXᵉ siècle.",
    co: "Préoccupation mineure.",
    w: "Non attendu — vérifiez autour des troupeaux.",
    bt: "—",
    fa: ["Suit le bétail.", "A colonisé les Amériques seul.", "Se nourrit en terrain sec."]
  },
  "grey-heron": {
    name: "Héron cendré",
    s: "Grand héron gris immobile dans les hauts-fonds. Le héron le plus commun de Mongolie, présent sur les lacs et rivières de tout le pays.",
    d: "Le Héron cendré est présent en Europe, en Asie et en Afrique. Il attend patiemment au bord de l’eau et harponne les poissons avec son bec en poignard. Il vole à battements lents, le cou replié. En Mongolie, il niche en colonies dans les arbres ou les roseaux le long des rivières et des lacs et se voit dans toutes les régions de mars à octobre.",
    f: ["Grand héron gris au long cou et aux longues pattes.", "Tête et cou blancs avec un trait noir de l’œil à une longue plume.", "Bec jaune en poignard.", "En vol, rémiges noires contrastant avec les couvertures grises.", "Vole le cou replié."],
    si: "Héron pourpré — plus fin, cou roux strié de noir. Grue cendrée — vole le cou tendu ; pas de bec en poignard.",
    h: "Lacs, rivières, marais et étangs à poissons.",
    di: "Toutes les régions : Khurkh, lac Ögii, lac Khar Us, Oulan-Bator (rivière Tuul), Böön Tsagaan, lac Buir.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Poissons, grenouilles, campagnols et insectes.",
    br: "Colonial ; nids de branches dans les grands arbres ou les roseaux ; 3 à 5 œufs.",
    be: "Reste immobile longtemps ; avance lentement.",
    v: "Un « fraank » rauque en vol.",
    cu: "Symbole de patience dans de nombreuses cultures.",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac ou rivière en été.",
    bt: "mai–sept.",
    fa: ["Peut rester immobile des heures.", "Vole le cou replié.", "Niche en colonies."]
  },
  "purple-heron": {
    name: "Héron pourpré",
    s: "Héron élancé au cou de serpent, roux strié de noir. Migrateur rare dans les zones humides mongoles.",
    d: "Le Héron pourpré niche dans les roselières denses, de l’Europe et de l’Afrique à l’Asie orientale. Plus farouche que le Héron cendré, il se cache dans la végétation haute. En Mongolie, on ne compte que quelques mentions dans l’est, le Gobi et l’ouest.",
    f: ["Élancé, au cou fin comme un serpent.", "Cou roux strié de noir.", "Dos gris foncé, ventre marron.", "Long bec jaune.", "Longs doigts dépassant derrière en vol."],
    si: "Héron cendré — plus grand, plus pâle, cou blanc.",
    h: "Roselières denses.",
    di: "Rare ; lac Khar Us, lac Buir, Böön Tsagaan, Oulan-Bator.",
    mi: "Migrateur rare, avril–septembre.",
    fo: "Poissons, grenouilles, insectes.",
    br: "Niche dans les roseaux (non confirmé en Mongolie).",
    be: "Farouche ; chasse à l’intérieur des roselières.",
    v: "Un croassement rauque.",
    cu: "Son nom latin purpurea signifie « pourpre ».",
    co: "Préoccupation mineure.",
    w: "Scrutez les roselières du lac Khar Us.",
    bt: "mai, août",
    fa: ["Cou de serpent.", "Se cache dans les roseaux.", "Rare en Mongolie."]
  },
  "great-egret": {
    name: "Grande Aigrette",
    s: "Grand héron élégant d’un blanc pur, au long cou et au bec jaune. Visiteur d’été, surtout dans l’ouest de la Mongolie et sur les lacs du Gobi.",
    d: "La Grande Aigrette est présente sur tous les continents chauds et tempérés. Chassée presque jusqu’à l’extinction pour ses plumes au XIXᵉ siècle, elle s’est rétablie. En Mongolie, elle niche sur les lacs de l’ouest (Khar Us), du Gobi (Böön Tsagaan, Orog) et au lac Ögii, et continue de s’étendre.",
    f: ["Grand héron entièrement blanc — presque aussi grand qu’un Héron cendré.", "Long cou coudé.", "Bec jaune (noir en période nuptiale).", "Longues pattes noires.", "Commissure prolongée derrière l’œil."],
    si: "Aigrette garzette — bien plus petite, bec noir, pieds jaunes. Héron garde-bœufs — petit et trapu.",
    h: "Lacs, marais et hauts-fonds des rivières.",
    di: "Lac Khar Us, Böön Tsagaan, lac Orog, lac Ögii, lac Achit, lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Poissons, grenouilles, insectes.",
    br: "Colonial dans les roseaux ou les arbres ; 3 à 5 œufs.",
    be: "Avance lentement en eau peu profonde.",
    v: "Un « krrak » grave et croassant.",
    cu: "Son rétablissement a lancé le mouvement de protection des oiseaux en Amérique.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en été.",
    bt: "mai–sept.",
    fa: ["Presque exterminée pour ses plumes.", "Emblème de la National Audubon Society.", "S’étend vers le nord."]
  },
  "little-egret": {
    name: "Aigrette garzette",
    s: "Aigrette blanche et fine au bec noir, aux pattes noires et aux pieds jaune vif. Migrateur rare dans les zones humides du Gobi.",
    d: "L’Aigrette garzette est présente dans le sud de l’Europe, en Afrique, en Asie et en Australie, et s’étend vers le nord. Elle court dans les hauts-fonds en remuant les proies avec ses pieds. En Mongolie, les mentions sont rares, surtout dans les oasis du Gobi comme Yolyn Am et Böön Tsagaan.",
    f: ["Petite aigrette blanche.", "Bec noir et fin.", "Pattes noires à « chaussons » jaunes.", "Deux longues plumes sur la nuque au printemps.", "Se nourrit activement en courant."],
    si: "Grande Aigrette — bien plus grande, bec jaune. Héron garde-bœufs — trapu, bec jaune.",
    h: "Lacs peu profonds, ruisseaux et marais.",
    di: "Rare ; Yolyn Am, Böön Tsagaan, lac Orog, lac Ögii.",
    mi: "Migrateur rare, mai–juin.",
    fo: "Petits poissons, crevettes, insectes.",
    br: "Colonial dans les arbres (pas en Mongolie).",
    be: "Remue l’eau avec ses pieds.",
    v: "Un croassement gargouillé.",
    cu: "Ses plumes valaient autrefois plus que leur poids en or.",
    co: "Préoccupation mineure.",
    w: "Oasis du Gobi en mai.",
    bt: "mai–juin",
    fa: ["A les pieds jaunes.", "Déloge ses proies avec ses doigts.", "Ses plumes valaient plus que l’or."]
  },
  "black-headed-ibis": {
    name: "Ibis à tête noire",
    s: "Ibis blanc à tête et cou nus et noirs et au long bec arqué. Erratique exceptionnel en Mongolie, sans mention GBIF.",
    d: "L’Ibis à tête noire niche en Asie du Sud et du Sud-Est. Il décline en raison de la perte des zones humides. Il n’existe que des mentions historiques en Mongolie.",
    f: ["Corps blanc.", "Tête et cou nus et noirs.", "Long bec noir, épais et arqué.", "Plumes grises sur le dos en période nuptiale."],
    si: "Spatule blanche — blanche, mais au bec en spatule.",
    h: "Marais et champs inondés.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Poissons, grenouilles, insectes et vers.",
    br: "Colonial dans les arbres (pas en Mongolie).",
    be: "Sonde la vase avec son bec.",
    v: "Surtout silencieux.",
    cu: "Proche de l’Ibis sacré de l’Égypte ancienne.",
    co: "En déclin à cause du drainage des zones humides et du dérangement.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Tête et cou nus.", "Parent de l’Ibis sacré.", "Espèce asiatique."]
  },
  "eurasian-spoonbill": {
    name: "Spatule blanche",
    s: "Échassier blanc au long bec plat en forme de spatule, qu’il balaie de gauche à droite dans l’eau peu profonde. Visiteur d’été commun sur les lacs de toute la Mongolie.",
    d: "La Spatule blanche niche de l’Europe à l’Asie orientale. Elle se nourrit en balayant l’eau de son bec entrouvert et le referme sur les petits poissons et crevettes. La Mongolie abrite d’importantes colonies : elle est commune aux lacs Ögii, Khar Us, Böön Tsagaan, Orog, Buir et dans la vallée de Khurkh.",
    f: ["Entièrement blanche, long bec noir terminé par une « spatule » jaune.", "Huppe ébouriffée et tache jaune sur la poitrine en période nuptiale.", "Pattes noires.", "Vole cou tendu, souvent en lignes.", "Balaie l’eau de son bec en se nourrissant."],
    si: "Grande Aigrette — bec pointu jaune, vole le cou replié. Cygnes — pattes courtes, nagent.",
    h: "Lacs peu profonds, marais et deltas avec roselières ou îlots.",
    di: "Toutes les régions : lac Ögii, lac Khar Us, Böön Tsagaan, lac Orog, lac Buir, Khurkh.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Petits poissons, crevettes, insectes et têtards.",
    br: "Colonial dans les roseaux ou sur des îlots ; 3 ou 4 œufs.",
    be: "Se nourrit en groupe ; dort le bec enfoui dans les plumes.",
    v: "Surtout silencieuse ; claquements de bec aux colonies.",
    cu: "Son nom mongol compare son bec à une louche.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii et Böön Tsagaan, mai–août.",
    bt: "mai–août",
    fa: ["Se nourrit en balayant l’eau.", "Son bec a la forme d’une spatule.", "Commune sur les lacs mongols."]
  }
});
