B2T("en", {
  "lesser-whistling-duck": {
    T: { c: { rufous: 0.4, brown: 0.4, buff: 0.2 }, hb: ["water"], bk: "flat", bh: ["swim", "perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["38–42 cm", "—", "450–600 g"] },
    s: "A small, long-necked, chestnut duck of tropical Asia that whistles in flight and perches in trees. On the Mongolian list, but with no GBIF records — an exceptional vagrant.",
    d: "The Lesser Whistling Duck lives on well-vegetated ponds and paddies in South and South-East Asia. It often perches and even nests in trees. A record in Mongolia would be exceptional.",
    f: ["Chestnut-brown with a darker cap.", "Long neck and legs; upright stance.", "Chestnut rump and dark wings in flight.", "Whistling calls in flight."],
    si: "No other duck in Mongolia looks like it.",
    h: "Ponds and paddies with vegetation.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Water plants, seeds and small animals.",
    br: "Nests in tree holes or reeds (not in Mongolia).",
    be: "Rests in flocks; perches in trees.",
    v: "A wheezy, whistled ‘whi-whee’.",
    cu: "Also called the ‘tree duck’.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Whistles in flight.", "Perches in trees.", "A tropical duck."]
  },
  "white-headed-duck": {
    T: { c: { brown: 0.45, white: 0.25, rufous: 0.2, black: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["43–48 cm", "62–70 cm", "0.5–0.9 kg"] },
    s: "A dumpy diving duck with a stiff tail; the male has a white head and a swollen blue bill. An endangered breeder at Khar Us Nuur in western Mongolia.",
    d: "The White-headed Duck is Europe’s and Asia’s only native stifftail. It has declined greatly and is Endangered. Western Mongolia holds a small breeding population: almost all records come from Khar Us Nuur and nearby lakes, where it breeds in reedy shallows from April to October.",
    f: ["Male: white head with a black cap and a swollen sky-blue bill.", "Chestnut body.", "Long, stiff tail often held cocked up.", "Female: brown with a pale face crossed by a dark line.", "Dives often; rarely flies."],
    si: "Ruddy Shelduck — orange body, not a diver. Female Common Pochard — no stiff tail, no face stripe.",
    h: "Shallow, reedy, often brackish lakes.",
    di: "Western Mongolia: Khar Us Nuur, Uvs, Achit Nuur; rare in the Gobi.",
    mi: "Summer visitor, April–October.",
    fo: "Insect larvae (especially midges), seeds and water plants.",
    br: "Nests in reeds, sometimes in old coot nests; lays very large eggs.",
    be: "Dives for food; swims low with tail up.",
    v: "Mostly silent.",
    cu: "Threatened in Spain by hybridisation with the introduced North American Ruddy Duck.",
    co: "Endangered.",
    w: "Khar Us Nuur in summer, from the shore.",
    bt: "May–September",
    fa: ["Endangered worldwide.", "Lays the largest eggs relative to size of any duck.", "Mongolia’s main site is Khar Us Nuur."]
  },
  "mute-swan": {
    T: { c: { white: 0.9, red: 0.05, black: 0.05 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["125–170 cm", "200–240 cm", "8–13 kg"] },
    s: "A huge white swan with an orange bill and black knob, holding its neck in an elegant S-curve. A local summer visitor to lakes in eastern and central Mongolia.",
    d: "The Mute Swan breeds wild in Central Asia, Mongolia and eastern Europe, and has been introduced widely elsewhere. It is less vocal than other swans, but its wings make a loud throbbing sound in flight. In Mongolia it breeds at Buir Nuur and other Dornod lakes, Ögii Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["Very large, all white.", "Orange bill with a black knob at the base (larger in males).", "Neck often held in an S-curve; wings raised like sails when displaying.", "Tail pointed and often raised.", "Wings make a throbbing ‘whoop-whoop’ in flight."],
    si: "Whooper Swan — yellow and black bill, straight neck, loud calls. Tundra Swan — smaller, yellow patch at bill base.",
    h: "Lakes with reeds and water plants.",
    di: "Buir Nuur, Ögii Nuur, Böön Tsagaan, Orog Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Water plants, reaching down with its long neck.",
    br: "Huge nest mound of reeds; 5–7 eggs; defends the nest aggressively.",
    be: "Raises wings and pushes forward in threat display.",
    v: "Mostly silent; hisses and snorts.",
    cu: "Mongolians regard swans as sacred birds that must not be harmed.",
    co: "Least Concern; protected in Mongolia.",
    w: "Buir Nuur and Ögii Nuur in summer.",
    bt: "May–September",
    fa: ["Its wings throb loudly in flight.", "Mostly silent.", "Sacred to Mongolians."]
  },
  "swan-goose": {
    T: { c: { brown: 0.5, white: 0.25, buff: 0.15, black: 0.1 }, hb: ["water", "steppe"], bk: "flat", bh: ["swim", "walk"], vt: ["honk"], ac: "day", se: ["summer"], sz: ["81–94 cm", "165–185 cm", "2.8–3.5 kg"] },
    s: "An elegant, long-necked goose with a long black bill and a dark brown stripe down the back of a pale neck. Mongolia holds a large part of the world’s breeding population of this endangered goose.",
    d: "The Swan Goose breeds only in Mongolia, north-east China and the Russian Far East, and winters almost entirely at a few lakes on the Yangtze in China. It is the wild ancestor of the domestic Chinese goose. It is Endangered because of habitat loss and hunting. In Mongolia it breeds on lakes and river valleys in the Khangai, Khentii and Dornod — Ögii Nuur, the Khurkh valley, Buir Nuur and Böön Tsagaan hold important numbers.",
    f: ["Long, all-black bill, straight and swan-like.", "Dark brown crown and hindneck stripe; pale buff-white foreneck.", "Thin white band at the base of the bill.", "Brown body barred pale.", "Orange legs."],
    si: "Greylag Goose — pink-orange bill, no neck stripe. Bean Goose — dark head and neck, orange band on a dark bill.",
    h: "Lakes, marshes and wet river valleys with grassland.",
    di: "Khangai (Ögii Nuur), Khentii (Khurkh), Ulaanbaatar area, Dornod (Buir Nuur), Gobi lakes (Böön Tsagaan, Orog Nuur).",
    mi: "Summer visitor, March–October.",
    fo: "Grasses, sedges and roots.",
    br: "Nests on the ground near water; 5–6 eggs.",
    be: "Grazes in flocks on wet meadows.",
    v: "A long, rising honk.",
    cu: "Ancestor of the domestic Chinese goose, with its knob on the bill.",
    co: "Endangered; in the Mongolian Red Book.",
    w: "Ögii Nuur and Khurkh valley in May–June, from a distance.",
    bt: "May–September",
    fa: ["Ancestor of the Chinese domestic goose.", "Endangered worldwide.", "Mongolia is its key breeding country."]
  },
  "bean-goose": {
    T: { c: { brown: 0.65, white: 0.15, black: 0.1, yellow: 0.1 }, hb: ["water", "steppe"], bk: "flat", bh: ["walk", "swim"], vt: ["honk"], ac: "day", se: ["passage"], sz: ["66–89 cm", "140–175 cm", "1.7–4 kg"] },
    s: "A dark brown goose with a black bill crossed by an orange band and orange legs. A passage migrant in spring and autumn across northern and eastern Mongolia.",
    d: "The Bean Goose (Taiga and Tundra Bean Geese) breeds in the taiga and tundra of Russia and winters in China, Korea and Japan. Large flocks pass through Mongolia in April–May and September–October, stopping at lakes and river valleys, especially the Khurkh valley.",
    f: ["Dark brown head and neck, darker than the body.", "Black bill with an orange band near the tip.", "Orange legs.", "Brown body with pale feather edges.", "White under the tail."],
    si: "Greylag Goose — paler, all pink-orange bill. Greater White-fronted Goose — white forehead, black belly bars.",
    h: "Lakes, marshes and fields on migration.",
    di: "Khentii (Khurkh), Dornod, Ulaanbaatar area, Yolyn Am, Ögii Nuur.",
    mi: "Passage migrant, March–May and September–October.",
    fo: "Grass, sedges, grain and roots.",
    br: "Nests in the taiga and tundra (not in Mongolia).",
    be: "Travels in large V-shaped flocks.",
    v: "A deep ‘ang-ang’.",
    cu: "Named ‘bean goose’ because it once fed in bean fields in England.",
    co: "Least Concern.",
    w: "Khurkh valley in late April and September.",
    bt: "April, September",
    fa: ["Named after bean fields.", "Includes taiga and tundra forms.", "Flies in V-shaped flocks."]
  },
  "greater-white-fronted-goose": {
    T: { c: { brown: 0.6, white: 0.15, black: 0.15, yellow: 0.1 }, hb: ["water", "steppe"], bk: "flat", bh: ["walk", "swim"], vt: ["honk"], ac: "day", se: ["passage"], sz: ["64–78 cm", "130–165 cm", "1.8–3.3 kg"] },
    s: "A grey-brown goose with a white blaze around the bill and black bars on the belly. A scarce spring and autumn migrant.",
    d: "The Greater White-fronted Goose breeds on the Arctic tundra and winters in temperate Europe, Asia and North America. It passes through Mongolia in small numbers in April–May and October, mostly in the north and east.",
    f: ["White patch around the base of the bill.", "Irregular black bars on the belly.", "Pink bill (eastern birds).", "Orange legs.", "Grey-brown body."],
    si: "Lesser White-fronted Goose — smaller, with a yellow eye-ring and white blaze reaching the crown. Greylag Goose — no white face or belly bars.",
    h: "Lakes, marshes and grassland on migration.",
    di: "Khentii (Khurkh), Dornod, Gobi lakes, Khar Us Nuur.",
    mi: "Passage migrant, April–May and October.",
    fo: "Grass, roots and grain.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Travels in noisy flocks.",
    v: "Musical, high-pitched ‘kow-lyow’.",
    cu: "Its laughing calls give it the French name ‘Oie rieuse’ (laughing goose).",
    co: "Least Concern.",
    w: "Khurkh valley in April–May.",
    bt: "April–May",
    fa: ["Has a white face.", "Belly barred black.", "Calls like laughter."]
  },
  "lesser-white-fronted-goose": {
    T: { c: { brown: 0.6, white: 0.15, black: 0.1, yellow: 0.1, red: 0.05 }, hb: ["water", "steppe"], bk: "flat", bh: ["walk", "swim"], vt: ["honk"], ac: "day", se: ["passage"], sz: ["53–66 cm", "120–135 cm", "1.3–2.5 kg"] },
    s: "A small, dainty goose with a yellow eye-ring and a white forehead blaze reaching onto the crown. A rare migrant; globally Vulnerable.",
    d: "The Lesser White-fronted Goose breeds on the Arctic tundra from Scandinavia to eastern Siberia and winters mainly at Dongting Lake in China. It is Vulnerable because of hunting and habitat loss. In Mongolia it is a rare migrant, with records at Ögii Nuur and in the east in spring and autumn.",
    f: ["Smaller than White-fronted Goose, with a short neck and small pink bill.", "Yellow ring around the eye.", "White blaze extends up onto the forehead.", "Black belly bars.", "Wingtips extend beyond the tail."],
    si: "Greater White-fronted Goose — larger, no eye-ring, smaller blaze.",
    h: "Lakes and grassland on migration.",
    di: "Rare; Ögii Nuur, Dornod, Khentii.",
    mi: "Passage migrant, May and September–October.",
    fo: "Grass and sedges.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Feeds with a faster pecking rate than other geese.",
    v: "High, squeaky ‘kyu-yu-yu’.",
    cu: "Scandinavian conservationists once guided young geese to safe wintering grounds using microlight aircraft.",
    co: "Vulnerable.",
    w: "Check goose flocks at Ögii Nuur in autumn.",
    bt: "September–October",
    fa: ["Globally Vulnerable.", "Has a yellow eye-ring.", "Most winter at one lake in China."]
  },
  "common-shelduck": {
    T: { c: { white: 0.45, black: 0.25, rufous: 0.2, red: 0.1 }, hb: ["water"], bk: "flat", bh: ["walk", "swim"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["55–65 cm", "100–133 cm", "0.8–1.5 kg"] },
    s: "A large, goose-like duck, boldly white with a dark green head, a chestnut breast band and a red bill. Common on salty lakes across Mongolia.",
    d: "The Common Shelduck breeds on coasts and salty inland lakes from Europe to Mongolia and China. It often nests in burrows, including marmot and fox holes. In Mongolia it is common from April to September at saline lakes and marshes in all regions, especially Ögii Nuur, the Khurkh valley, Buir Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["White body with a bottle-green head.", "Broad chestnut band across the breast.", "Bright red bill; male has a knob at the base.", "Black shoulder stripe and black wingtips.", "Pink legs."],
    si: "Ruddy Shelduck — orange-brown with a pale head. Northern Shoveler (male) — green head but chestnut sides and a big spoon bill.",
    h: "Saline and fresh lakes with open shores and mud.",
    di: "All regions: Ögii Nuur, Khurkh, Buir Nuur, Böön Tsagaan, Orog Nuur, Khar Us Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Small snails, crustaceans and insects sieved from mud.",
    br: "Nests in burrows (often marmot holes) or dense cover; 8–10 eggs; young gather in crèches.",
    be: "Sweeps its bill through mud; ducklings join large nurseries.",
    v: "Male whistles; female makes a laughing ‘ak-ak-ak’.",
    cu: "Nesting in marmot burrows ties it to Mongolia’s steppe mammals.",
    co: "Least Concern.",
    w: "Ögii Nuur and Böön Tsagaan in May–June.",
    bt: "May–August",
    fa: ["Nests in marmot burrows.", "Ducklings gather in nurseries.", "Looks like a small goose."]
  },
  "mandarin-duck": {
    T: { c: { rufous: 0.3, white: 0.2, brown: 0.2, gray: 0.15, red: 0.1, black: 0.05 }, hb: ["water", "forest", "settlement"], bk: "flat", bh: ["swim", "perch"], vt: ["whistle"], ac: "day", se: ["passage", "summer"], sz: ["41–49 cm", "65–75 cm", "430–690 g"] },
    s: "Perhaps the most colourful duck in the world: the male has orange ‘sails’ and whiskers. A regular spring migrant and increasingly a breeder around Ulaanbaatar and Terelj.",
    d: "The Mandarin Duck breeds in forested rivers of the Russian Far East, north-east China and Japan, and nests in tree holes. It has been expanding its range westward; in Mongolia it is now seen every spring on the Tuul River in Ulaanbaatar and in Terelj, and has bred in the Khentii.",
    f: ["Male: orange ‘sails’ on the back, orange whiskers, white eye-stripe, purple breast and red bill.", "Female: grey with a white ‘spectacle’ around the eye.", "Perches on branches over water.", "Green speculum."],
    si: "Unmistakable. Female Eurasian Wigeon lacks the white spectacle.",
    h: "Forested rivers and ponds with overhanging trees.",
    di: "Ulaanbaatar (Tuul River), Terelj, Khurkh, occasionally Gobi oases.",
    mi: "Passage migrant and summer visitor, April–October; peak in May.",
    fo: "Seeds, acorns, insects and snails.",
    br: "Nests in tree holes high above the ground; ducklings jump down after hatching.",
    be: "Perches in trees; shy.",
    v: "Soft whistles and clucks.",
    cu: "A symbol of love and fidelity in China and Korea; pairs of wooden mandarin ducks are wedding gifts.",
    co: "Least Concern.",
    w: "Tuul River in Ulaanbaatar in May.",
    bt: "May",
    fa: ["Nests in tree holes.", "Ducklings jump from the nest.", "Symbol of faithful love."]
  },
  "harlequin-duck": {
    T: { c: { gray: 0.35, white: 0.25, rufous: 0.2, black: 0.2 }, hb: ["water", "mountain"], bk: "flat", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["38–45 cm", "63–70 cm", "450–750 g"] },
    s: "A small duck of fast mountain rivers; the male is slate-blue with bold white stripes and chestnut flanks. Listed for northern Mongolia but with no GBIF records.",
    d: "The Harlequin Duck breeds on fast, rocky rivers in eastern Siberia, Iceland and North America and winters on rough sea coasts. It could occur on the fast rivers of the Khentii or Khövsgöl, but records are exceptional.",
    f: ["Male: slate-blue with white stripes and spots edged in black; chestnut flanks.", "Female: dark brown with three white spots on the face.", "Small bill.", "Swims in rapids."],
    si: "Female Long-tailed Duck — paler, with a dark cheek patch.",
    h: "Fast, rocky mountain rivers.",
    di: "Exceptional; possibly northern mountains.",
    mi: "Vagrant.",
    fo: "Insect larvae and crustaceans from the river bed.",
    br: "Nests beside mountain rivers (not in Mongolia).",
    be: "Dives in white water.",
    v: "Mouse-like squeaks.",
    cu: "Named after the colourful Harlequin of Italian comedy.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Feeds in rapids.", "Named after a comic character.", "Often has healed bone fractures from life in rough water."]
  }
});
