B2T("fr", {
  "lesser-whistling-duck": {
    name: "Dendrocygne siffleur",
    s: "Petit canard marron au long cou d’Asie tropicale, qui siffle en vol et se perche dans les arbres. Sur la liste mongole, mais sans mention GBIF — erratique exceptionnel.",
    d: "Le Dendrocygne siffleur vit sur les étangs et rizières riches en végétation d’Asie du Sud et du Sud-Est. Il se perche souvent et niche même dans les arbres. Une mention en Mongolie serait exceptionnelle.",
    f: ["Brun marron avec une calotte plus sombre.", "Long cou et longues pattes ; port dressé.", "Croupion marron et ailes sombres en vol.", "Sifflements en vol."],
    si: "Aucun autre canard mongol ne lui ressemble.",
    h: "Étangs et rizières à végétation.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Plantes aquatiques, graines et petits animaux.",
    br: "Niche dans des cavités d’arbres ou les roseaux (pas en Mongolie).",
    be: "Se repose en groupes ; se perche dans les arbres.",
    v: "Un « ouiii-ouii » sifflé et nasal.",
    cu: "Aussi appelé « canard arboricole ».",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Siffle en vol.", "Se perche dans les arbres.", "Canard tropical."]
  },
  "white-headed-duck": {
    name: "Érismature à tête blanche",
    s: "Canard plongeur trapu à queue raide ; le mâle a la tête blanche et un bec bleu renflé. Nicheur menacé au lac Khar Us, dans l’ouest de la Mongolie.",
    d: "L’Érismature à tête blanche est la seule érismature indigène d’Europe et d’Asie. Elle a fortement décliné et est classée En danger. L’ouest de la Mongolie abrite une petite population nicheuse : presque toutes les mentions proviennent du lac Khar Us et des lacs voisins, où elle niche dans les hauts-fonds à roseaux d’avril à octobre.",
    f: ["Mâle : tête blanche à calotte noire et bec bleu ciel renflé.", "Corps marron.", "Longue queue raide souvent relevée.", "Femelle : brune à face pâle barrée d’une ligne sombre.", "Plonge souvent ; vole rarement."],
    si: "Tadorne casarca — corps orange, ne plonge pas. Femelle de Fuligule milouin — pas de queue raide ni de trait facial.",
    h: "Lacs peu profonds à roseaux, souvent saumâtres.",
    di: "Ouest : lac Khar Us, Uvs, lac Achit ; rare dans le Gobi.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Larves d’insectes (surtout chironomes), graines et plantes aquatiques.",
    br: "Niche dans les roseaux, parfois dans d’anciens nids de foulques ; pond de très gros œufs.",
    be: "Plonge pour se nourrir ; nage bas, queue relevée.",
    v: "Surtout silencieuse.",
    cu: "Menacée en Espagne par l’hybridation avec l’Érismature rousse introduite d’Amérique.",
    co: "En danger.",
    w: "Lac Khar Us en été, depuis la rive.",
    bt: "mai–sept.",
    fa: ["En danger à l’échelle mondiale.", "Pond les plus gros œufs, relativement à sa taille, de tous les canards.", "Son principal site mongol est le lac Khar Us."]
  },
  "mute-swan": {
    name: "Cygne tuberculé",
    s: "Immense cygne blanc au bec orange orné d’un tubercule noir, au cou gracieusement courbé en S. Visiteur d’été local sur les lacs de l’est et du centre de la Mongolie.",
    d: "Le Cygne tuberculé niche à l’état sauvage en Asie centrale, en Mongolie et en Europe de l’Est, et a été introduit dans de nombreux pays. Il est moins bruyant que les autres cygnes, mais ses ailes produisent un fort vrombissement en vol. En Mongolie, il niche au lac Buir et sur d’autres lacs du Dornod, au lac Ögii, à Böön Tsagaan et au lac Orog.",
    f: ["Très grand, entièrement blanc.", "Bec orange avec un tubercule noir à la base (plus grand chez le mâle).", "Cou souvent en S ; ailes relevées comme des voiles en parade.", "Queue pointue souvent relevée.", "Ailes vrombissantes en vol."],
    si: "Cygne chanteur — bec jaune et noir, cou droit, cris sonores. Cygne de Bewick — plus petit, tache jaune à la base du bec.",
    h: "Lacs avec roseaux et plantes aquatiques.",
    di: "Lac Buir, lac Ögii, Böön Tsagaan, lac Orog, lac Khar Us.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes aquatiques, atteintes avec son long cou.",
    br: "Énorme monticule de roseaux ; 5 à 7 œufs ; défend son nid avec agressivité.",
    be: "Relève les ailes et avance en menace.",
    v: "Surtout silencieux ; sifflements et reniflements.",
    cu: "Les Mongols considèrent les cygnes comme des oiseaux sacrés à ne pas blesser.",
    co: "Préoccupation mineure ; protégé en Mongolie.",
    w: "Lacs Buir et Ögii en été.",
    bt: "mai–sept.",
    fa: ["Ses ailes vrombissent en vol.", "Surtout silencieux.", "Sacré pour les Mongols."]
  },
  "swan-goose": {
    name: "Oie cygnoïde",
    s: "Oie élégante au long cou, au long bec noir et à la bande brun foncé sur l’arrière d’un cou pâle. La Mongolie abrite une grande part de la population nicheuse mondiale de cette oie menacée.",
    d: "L’Oie cygnoïde niche uniquement en Mongolie, dans le nord-est de la Chine et l’Extrême-Orient russe, et hiverne presque entièrement sur quelques lacs du Yangtsé. C’est l’ancêtre sauvage de l’oie domestique chinoise. Elle est En danger en raison de la perte d’habitat et de la chasse. En Mongolie, elle niche sur les lacs et vallées du Khangaï, du Khentii et du Dornod — lac Ögii, vallée de Khurkh, lac Buir et Böön Tsagaan en abritent des effectifs importants.",
    f: ["Long bec entièrement noir, droit comme celui d’un cygne.", "Calotte et arrière du cou brun foncé ; devant du cou blanc chamois pâle.", "Fin liseré blanc à la base du bec.", "Corps brun barré de pâle.", "Pattes orange."],
    si: "Oie cendrée — bec orange rosé, sans bande sur le cou. Oie des moissons — tête et cou sombres, bande orange sur un bec sombre.",
    h: "Lacs, marais et vallées humides avec prairies.",
    di: "Khangaï (lac Ögii), Khentii (Khurkh), région d’Oulan-Bator, Dornod (lac Buir), lacs du Gobi (Böön Tsagaan, Orog).",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Herbes, laîches et racines.",
    br: "Niche au sol près de l’eau ; 5 ou 6 œufs.",
    be: "Pâture en groupes dans les prairies humides.",
    v: "Un long cri montant.",
    cu: "Ancêtre de l’oie domestique chinoise à bosse sur le bec.",
    co: "En danger ; inscrite au Livre rouge de Mongolie.",
    w: "Lac Ögii et vallée de Khurkh en mai–juin, à distance.",
    bt: "mai–sept.",
    fa: ["Ancêtre de l’oie domestique chinoise.", "En danger à l’échelle mondiale.", "La Mongolie est son principal pays de nidification."]
  },
  "bean-goose": {
    name: "Oie des moissons",
    s: "Oie brun foncé au bec noir barré d’orange et aux pattes orange. Migratrice de passage au printemps et en automne dans le nord et l’est de la Mongolie.",
    d: "L’Oie des moissons (formes de la taïga et de la toundra) niche dans la taïga et la toundra de Russie et hiverne en Chine, en Corée et au Japon. De grands vols traversent la Mongolie en avril–mai et septembre–octobre, faisant halte sur les lacs et dans les vallées, surtout celle de Khurkh.",
    f: ["Tête et cou brun foncé, plus sombres que le corps.", "Bec noir avec une bande orange près de l’extrémité.", "Pattes orange.", "Corps brun aux liserés pâles.", "Sous-caudales blanches."],
    si: "Oie cendrée — plus pâle, bec entièrement orange rosé. Oie rieuse — front blanc, barres noires sur le ventre.",
    h: "Lacs, marais et champs en migration.",
    di: "Khentii (Khurkh), Dornod, région d’Oulan-Bator, Yolyn Am, lac Ögii.",
    mi: "Migratrice, mars–mai et septembre–octobre.",
    fo: "Herbes, laîches, céréales et racines.",
    br: "Niche dans la taïga et la toundra (pas en Mongolie).",
    be: "Voyage en grands vols en V.",
    v: "Un « ang-ang » grave.",
    cu: "Son nom rappelle qu’elle glanait dans les champs moissonnés.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh fin avril et en septembre.",
    bt: "avril, sept.",
    fa: ["Nommée d’après les moissons.", "Comprend des formes de taïga et de toundra.", "Vole en V."]
  },
  "greater-white-fronted-goose": {
    name: "Oie rieuse",
    s: "Oie gris-brun à tache blanche autour du bec et barres noires sur le ventre. Migratrice peu commune au printemps et en automne.",
    d: "L’Oie rieuse niche dans la toundra arctique et hiverne dans les régions tempérées d’Europe, d’Asie et d’Amérique du Nord. Elle traverse la Mongolie en petit nombre en avril–mai et en octobre, surtout dans le nord et l’est.",
    f: ["Tache blanche à la base du bec.", "Barres noires irrégulières sur le ventre.", "Bec rose (oiseaux orientaux).", "Pattes orange.", "Corps gris-brun."],
    si: "Oie naine — plus petite, cercle orbital jaune, tache blanche montant sur le front. Oie cendrée — sans face blanche ni barres ventrales.",
    h: "Lacs, marais et prairies en migration.",
    di: "Khentii (Khurkh), Dornod, lacs du Gobi, lac Khar Us.",
    mi: "Migratrice, avril–mai et octobre.",
    fo: "Herbes, racines et céréales.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Voyage en vols bruyants.",
    v: "Un « kou-lyou » musical et aigu.",
    cu: "Ses cris évoquant un rire lui ont valu son nom français.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en avril–mai.",
    bt: "avril–mai",
    fa: ["Face blanche.", "Ventre barré de noir.", "Son cri évoque un rire."]
  },
  "lesser-white-fronted-goose": {
    name: "Oie naine",
    s: "Petite oie délicate au cercle orbital jaune et à la tache frontale blanche montant jusqu’à la calotte. Migratrice rare ; Vulnérable à l’échelle mondiale.",
    d: "L’Oie naine niche dans la toundra arctique, de la Scandinavie à la Sibérie orientale, et hiverne principalement au lac Dongting en Chine. Elle est Vulnérable en raison de la chasse et de la perte d’habitat. En Mongolie, c’est une migratrice rare, notée au lac Ögii et dans l’est au printemps et en automne.",
    f: ["Plus petite que l’Oie rieuse, cou court et petit bec rose.", "Cercle jaune autour de l’œil.", "Tache blanche montant sur le front.", "Barres noires sur le ventre.", "Pointes des ailes dépassant la queue."],
    si: "Oie rieuse — plus grande, sans cercle orbital, tache plus petite.",
    h: "Lacs et prairies en migration.",
    di: "Rare ; lac Ögii, Dornod, Khentii.",
    mi: "Migratrice, mai et septembre–octobre.",
    fo: "Herbes et laîches.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Picore plus vite que les autres oies.",
    v: "Un « kyou-you-you » aigu et grinçant.",
    cu: "Des protecteurs scandinaves ont guidé de jeunes oies vers des quartiers d’hiver sûrs à l’aide d’ULM.",
    co: "Vulnérable.",
    w: "Examinez les vols d’oies au lac Ögii en automne.",
    bt: "sept.–oct.",
    fa: ["Vulnérable à l’échelle mondiale.", "Cercle orbital jaune.", "La plupart hivernent sur un seul lac de Chine."]
  },
  "common-shelduck": {
    name: "Tadorne de Belon",
    s: "Grand canard ressemblant à une oie, blanc vif à tête vert foncé, bande pectorale marron et bec rouge. Commun sur les lacs salés de toute la Mongolie.",
    d: "Le Tadorne de Belon niche sur les côtes et les lacs salés intérieurs, de l’Europe à la Mongolie et à la Chine. Il niche souvent dans des terriers, y compris ceux de marmottes et de renards. En Mongolie, il est commun d’avril à septembre sur les lacs et marais salés de toutes les régions, en particulier au lac Ögii, dans la vallée de Khurkh, au lac Buir, à Böön Tsagaan et au lac Orog.",
    f: ["Corps blanc à tête vert bouteille.", "Large bande marron en travers de la poitrine.", "Bec rouge vif ; le mâle porte une caroncule à la base.", "Bande scapulaire noire et extrémités des ailes noires.", "Pattes roses."],
    si: "Tadorne casarca — brun orangé à tête pâle. Canard souchet mâle — tête verte mais flancs marron et grand bec en spatule.",
    h: "Lacs salés et doux à rives dégagées et vasières.",
    di: "Toutes les régions : lac Ögii, Khurkh, lac Buir, Böön Tsagaan, lac Orog, lac Khar Us.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Petits escargots, crustacés et insectes filtrés dans la vase.",
    br: "Niche dans un terrier (souvent de marmotte) ou un couvert dense ; 8 à 10 œufs ; les jeunes se regroupent en crèches.",
    be: "Balaie la vase avec son bec ; les canetons rejoignent de grandes crèches.",
    v: "Le mâle siffle ; la femelle lance un « ak-ak-ak » rieur.",
    cu: "Sa nidification dans les terriers de marmottes le lie aux mammifères de la steppe mongole.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii et Böön Tsagaan en mai–juin.",
    bt: "mai–août",
    fa: ["Niche dans les terriers de marmottes.", "Les canetons se regroupent en crèches.", "Ressemble à une petite oie."]
  },
  "mandarin-duck": {
    name: "Canard mandarin",
    s: "Peut-être le canard le plus coloré du monde : le mâle porte des « voiles » et des favoris orange. Migrateur régulier au printemps et nicheur de plus en plus fréquent autour d’Oulan-Bator et de Terelj.",
    d: "Le Canard mandarin niche le long des rivières boisées de l’Extrême-Orient russe, du nord-est de la Chine et du Japon, dans des cavités d’arbres. Son aire s’étend vers l’ouest ; en Mongolie, on le voit désormais chaque printemps sur la rivière Tuul à Oulan-Bator et à Terelj, et il a niché dans le Khentii.",
    f: ["Mâle : « voiles » orange sur le dos, favoris orange, sourcil blanc, poitrine pourpre et bec rouge.", "Femelle : grise avec des « lunettes » blanches autour de l’œil.", "Se perche sur les branches au-dessus de l’eau.", "Miroir vert."],
    si: "Inconfondable. La femelle de Canard siffleur n’a pas de lunettes blanches.",
    h: "Rivières et étangs boisés avec arbres surplombants.",
    di: "Oulan-Bator (rivière Tuul), Terelj, Khurkh, parfois oasis du Gobi.",
    mi: "Migrateur et visiteur d’été, avril–octobre ; pic en mai.",
    fo: "Graines, glands, insectes et escargots.",
    br: "Niche dans des cavités d’arbres en hauteur ; les canetons sautent au sol après l’éclosion.",
    be: "Se perche dans les arbres ; farouche.",
    v: "Doux sifflements et gloussements.",
    cu: "Symbole d’amour et de fidélité en Chine et en Corée ; on offre des paires de mandarins en bois aux mariés.",
    co: "Préoccupation mineure.",
    w: "Rivière Tuul à Oulan-Bator en mai.",
    bt: "mai",
    fa: ["Niche dans les arbres.", "Les canetons sautent du nid.", "Symbole d’amour fidèle."]
  },
  "harlequin-duck": {
    name: "Arlequin plongeur",
    s: "Petit canard des torrents de montagne ; le mâle est bleu ardoise à rayures blanches et flancs marron. Inscrit pour le nord de la Mongolie, mais sans mention GBIF.",
    d: "L’Arlequin plongeur niche sur les rivières rapides et rocheuses de Sibérie orientale, d’Islande et d’Amérique du Nord, et hiverne sur les côtes agitées. Il pourrait fréquenter les torrents du Khentii ou du Khövsgöl, mais les mentions sont exceptionnelles.",
    f: ["Mâle : bleu ardoise à rayures et taches blanches bordées de noir ; flancs marron.", "Femelle : brun foncé avec trois taches blanches sur la face.", "Petit bec.", "Nage dans les rapides."],
    si: "Femelle de Harelde kakawi — plus pâle, tache sombre sur la joue.",
    h: "Rivières de montagne rapides et rocheuses.",
    di: "Exceptionnel ; peut-être les montagnes du nord.",
    mi: "Erratique.",
    fo: "Larves d’insectes et crustacés du lit des rivières.",
    br: "Niche au bord des torrents (pas en Mongolie).",
    be: "Plonge dans les eaux vives.",
    v: "Couinements de souris.",
    cu: "Nommé d’après l’Arlequin de la commedia dell’arte.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Se nourrit dans les rapides.", "Porte le nom d’un personnage comique.", "Présente souvent d’anciennes fractures dues aux eaux tumultueuses."]
  }
});
