B2T("en", {
  "long-tailed-duck": {
    T: { c: { white: 0.45, black: 0.3, brown: 0.15, gray: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["honk"], ac: "day", se: ["passage"], sz: ["38–58 cm", "65–82 cm", "0.5–1 kg"] },
    s: "A small, pied sea duck; the male has very long, thin central tail feathers. A scarce spring migrant through Mongolian lakes, globally Vulnerable.",
    d: "The Long-tailed Duck breeds on Arctic tundra pools and winters at sea. It is one of the deepest-diving ducks, reaching 60 m. Numbers have dropped sharply, so it is Vulnerable. In Mongolia it is a scarce migrant, mostly in May, in the north and east.",
    f: ["Male: long, needle-like tail; white, black and grey plumage that changes with the season.", "Pink band across the short dark bill.", "Female: brown and white with a dark cheek patch.", "Small, round head.", "Dives often."],
    si: "Common Goldeneye — larger head, white cheek spot, no long tail. Smew — white with black lines.",
    h: "Lakes on migration.",
    di: "Khentii (Khurkh), Dornod, Khar Us Nuur, Orog Nuur, Ulaanbaatar.",
    mi: "Passage migrant, mostly May.",
    fo: "Molluscs, crustaceans and insect larvae.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Dives in groups; very vocal.",
    v: "Yodelling ‘ow-owlee’ calls.",
    cu: "Its old North American name ‘oldsquaw’ referred to its chattering calls.",
    co: "Vulnerable.",
    w: "Check lakes in the north-east in May.",
    bt: "May",
    fa: ["Dives to 60 m.", "Has a long needle tail.", "Globally Vulnerable."]
  },
  "velvet-scoter": {
    T: { c: { black: 0.8, white: 0.15, yellow: 0.05 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["51–58 cm", "90–99 cm", "1.1–2 kg"] },
    s: "A heavy, black sea duck with white wing patches; the eastern form (Stejneger’s Scoter) has a knobbed bill. A rare migrant in northern Mongolia.",
    d: "The Velvet Scoter and its eastern relative, Stejneger’s Scoter, breed on northern lakes of the taiga and tundra and winter at sea. In Mongolia there are only a handful of records, mostly in May, on lakes in the north and the Khangai.",
    f: ["Male: all black with a small white crescent below the eye.", "White secondaries — a white wing patch in flight.", "Bill yellow and black with a knob.", "Female: dark brown with two pale face spots."],
    si: "Common Goldeneye — white body sides. Tufted Duck — white flanks, tuft.",
    h: "Large lakes on migration.",
    di: "Rare; Terkhiin Tsagaan Nuur, Khentii.",
    mi: "Passage migrant, May–August.",
    fo: "Molluscs, crustaceans and insects.",
    br: "Nests near taiga lakes (not in Mongolia).",
    be: "Dives in small groups.",
    v: "Mostly silent.",
    cu: "Named for its velvety black plumage.",
    co: "Vulnerable.",
    w: "Check large lakes in May.",
    bt: "May",
    fa: ["Shows white wing patches in flight.", "Globally Vulnerable.", "Winters at sea."]
  },
  "smew": {
    T: { c: { white: 0.6, black: 0.25, gray: 0.1, rufous: 0.05 }, hb: ["water", "forest"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["passage", "summer"], sz: ["35–44 cm", "55–69 cm", "500–900 g"] },
    s: "A small merganser; the male is snowy white with fine black lines like cracked ice, and the female has a chestnut cap. A migrant and scarce breeder in northern Mongolia.",
    d: "The Smew breeds in the taiga of northern Eurasia, nesting in tree holes near lakes and rivers, and winters farther south. In Mongolia it passes through in April–May and September–October and may breed in the northern taiga. It is regularly seen on ponds around Ulaanbaatar and in the Khurkh valley.",
    f: ["Male: white with a black mask, black lines on the head and back.", "Female (‘redhead’): grey with a chestnut cap and white cheeks.", "Small, narrow serrated bill.", "Dives frequently."],
    si: "Common Goldeneye — larger, dark head with white cheek spot. Female Red-breasted Merganser — larger with a shaggy crest.",
    h: "Lakes and rivers; nests in forest.",
    di: "Khentii (Khurkh), Ulaanbaatar, Ögii Nuur, Buir Nuur.",
    mi: "Passage migrant April–May and September–October; possible breeder.",
    fo: "Small fish and aquatic insects.",
    br: "Nests in tree holes, often old Black Woodpecker holes; 6–9 eggs.",
    be: "Dives in small flocks.",
    v: "Mostly silent.",
    cu: "The male’s pattern resembles white ice with black cracks.",
    co: "Least Concern.",
    w: "Tuul River ponds in Ulaanbaatar in April.",
    bt: "April–May",
    fa: ["Nests in woodpecker holes.", "Male looks like cracked ice.", "Smallest merganser."]
  },
  "red-breasted-merganser": {
    T: { c: { gray: 0.3, white: 0.25, rufous: 0.2, black: 0.15, red: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["51–62 cm", "70–86 cm", "0.8–1.35 kg"] },
    s: "A slim, saw-billed diving duck with a shaggy double crest; the male has a streaky chestnut breast. A migrant on Mongolian lakes, especially in spring.",
    d: "The Red-breasted Merganser breeds on northern lakes and coasts and winters mainly at sea. It chases fish underwater with its serrated bill. In Mongolia it is a regular migrant in May and September–October, seen at Terkhiin Tsagaan Nuur, Buir Nuur, Ögii Nuur and near Ulaanbaatar.",
    f: ["Thin red bill with serrations.", "Shaggy, spiky double crest.", "Male: green-black head, white collar, streaked chestnut breast.", "Female: grey with a brown head blending into the neck.", "Swims low."],
    si: "Common Merganser (Goosander) — larger, male white below, female has a sharp neck line. Smew — smaller, short bill.",
    h: "Lakes and rivers on migration.",
    di: "Terkhiin Tsagaan Nuur, Buir Nuur, Ögii Nuur, Ulaanbaatar, Böön Tsagaan.",
    mi: "Passage migrant, April–May and September–October.",
    fo: "Small fish.",
    br: "Nests on the ground near water in the north (not confirmed in Mongolia).",
    be: "Dives after fish; males display by stretching their necks.",
    v: "Mostly silent.",
    cu: "Holds the level-flight speed record for ducks (about 130 km/h).",
    co: "Least Concern.",
    w: "Terkhiin Tsagaan Nuur in May.",
    bt: "May",
    fa: ["Saw-toothed bill for gripping fish.", "Very fast flier.", "Shaggy crest."]
  },
  "red-crested-pochard": {
    T: { c: { rufous: 0.3, black: 0.3, white: 0.2, red: 0.1, brown: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["53–57 cm", "84–90 cm", "0.8–1.4 kg"] },
    s: "A large, colourful diving duck; the male has a rounded orange head and a bright red bill. A summer visitor, most common on western and Gobi lakes.",
    d: "The Red-crested Pochard breeds from Spain across Central Asia to western Mongolia. It feeds on water plants, often dabbling as well as diving. In Mongolia it is common at Khar Us Nuur, Ögii Nuur, Orog Nuur and Böön Tsagaan.",
    f: ["Male: rounded orange-chestnut head, bright red bill, black breast and tail, white flanks.", "Female: brown with a dark cap and pale cheeks; bill dark with a pink tip.", "Broad white wing stripe in flight."],
    si: "Common Pochard — male has a chestnut head, grey body, dark bill. Female Common Pochard — greyer, with pale spectacles rather than pale cheeks.",
    h: "Large, reedy, often brackish lakes.",
    di: "Khar Us Nuur, Ögii Nuur, Orog Nuur, Böön Tsagaan, Achit Nuur, Yolyn Am.",
    mi: "Summer visitor, April–October.",
    fo: "Water plants (especially stoneworts), seeds.",
    br: "Nests in reeds; 8–10 eggs.",
    be: "Males offer food to females during courtship.",
    v: "Mostly silent; a wheezy sneeze by males.",
    cu: "One of the few ducks in which males feed females.",
    co: "Least Concern.",
    w: "Khar Us Nuur and Ögii Nuur in June.",
    bt: "May–August",
    fa: ["Male feeds the female in courtship.", "Has a bright red bill.", "Dives and dabbles."]
  },
  "common-pochard": {
    T: { c: { gray: 0.45, rufous: 0.25, black: 0.25, red: 0.05 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["42–49 cm", "72–82 cm", "0.7–1.2 kg"] },
    s: "A diving duck with a chestnut head, black breast and pale grey body. Common on lakes across Mongolia, but globally Vulnerable.",
    d: "The Common Pochard breeds from Europe to Mongolia and winters farther south. Its numbers have fallen sharply across its range, so it is now Vulnerable. In Mongolia it is common on reedy lakes from April to October: Ögii Nuur, the Khurkh valley, Khar Us Nuur, Ulaanbaatar ponds and Buir Nuur.",
    f: ["Male: chestnut-red head, black breast and tail, pale grey back and flanks.", "Red eye.", "Dark bill with a pale grey band.", "Female: grey-brown with pale ‘spectacles’.", "Sloping forehead."],
    si: "Red-crested Pochard — orange head, red bill. Ferruginous Duck — all dark chestnut, white eye. Baer’s Pochard — green head, chestnut breast.",
    h: "Reedy lakes and ponds.",
    di: "All regions: Ögii Nuur, Khurkh, Khar Us Nuur, Ulaanbaatar, Buir Nuur, Böön Tsagaan.",
    mi: "Summer visitor, April–October.",
    fo: "Water plants, seeds and insect larvae.",
    br: "Nests in reeds; 8–10 eggs.",
    be: "Dives; rests in flocks.",
    v: "Mostly silent.",
    cu: "Its decline surprised scientists, as it was one of Europe’s most common ducks.",
    co: "Vulnerable.",
    w: "Ögii Nuur in summer.",
    bt: "May–September",
    fa: ["Globally Vulnerable.", "Male has a red eye.", "Still common in Mongolia."]
  },
  "baers-pochard": {
    T: { c: { black: 0.35, rufous: 0.3, white: 0.2, brown: 0.15 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["41–47 cm", "70–79 cm", "680–880 g"] },
    s: "One of the rarest ducks in the world: dark green head, chestnut breast and white eye. A few are seen each spring in Mongolia.",
    d: "Baer’s Pochard breeds in the Russian Far East and north-east China and winters in southern China and Bangladesh. Fewer than 1,000 remain, and it is Critically Endangered because of wetland loss and hunting. Recent spring records in Mongolia (Böön Tsagaan, Ögii Nuur, Buir Nuur) are important for its conservation.",
    f: ["Male: dark green-black head, chestnut breast, brown back, white flanks at the front.", "White eye.", "White undertail.", "Female: duller, with a chestnut patch at the bill base."],
    si: "Ferruginous Duck — all chestnut, no green head. Tufted Duck — tufted, all-black upperparts.",
    h: "Reedy lakes.",
    di: "Rare; Böön Tsagaan, Ögii Nuur, Buir Nuur.",
    mi: "Passage migrant, May–July.",
    fo: "Water plants, seeds and invertebrates.",
    br: "Nests in marsh vegetation (not proven in Mongolia).",
    be: "Mixes with other diving ducks.",
    v: "Mostly silent.",
    cu: "Named after the Baltic-German naturalist Karl Ernst von Baer.",
    co: "Critically Endangered.",
    w: "Check Böön Tsagaan in May; report records.",
    bt: "May",
    fa: ["Fewer than 1,000 left.", "Critically Endangered.", "Has a white eye."]
  },
  "ferruginous-duck": {
    T: { c: { rufous: 0.55, brown: 0.3, white: 0.15 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["38–42 cm", "63–67 cm", "400–650 g"] },
    s: "A small, dark chestnut diving duck with a white eye and pure white undertail. A summer visitor to reedy lakes; Near Threatened.",
    d: "The Ferruginous Duck breeds from southern Europe to western China and Mongolia. It stays close to reeds and is often overlooked. In Mongolia it breeds on lakes at Khar Us Nuur, Böön Tsagaan, Ögii Nuur, Yolyn Am and near Ulaanbaatar.",
    f: ["Rich mahogany-chestnut body.", "Male has a white eye; female’s is dark.", "Bright white undertail.", "Peaked crown.", "White wing bar in flight."],
    si: "Common Pochard — grey body. Tufted Duck (female) — yellow eye, less rich colour. Baer’s Pochard — green head.",
    h: "Shallow lakes with dense reeds.",
    di: "Khar Us Nuur, Böön Tsagaan, Ulaanbaatar, Ögii Nuur, Yolyn Am, Khurkh.",
    mi: "Summer visitor, March–October.",
    fo: "Water plants, seeds and insects.",
    br: "Nests in reeds; 7–10 eggs.",
    be: "Shy; keeps near reeds.",
    v: "Mostly silent.",
    cu: "Its name ‘ferruginous’ means ‘rust-coloured’.",
    co: "Near Threatened.",
    w: "Böön Tsagaan and Khar Us Nuur in June.",
    bt: "May–August",
    fa: ["Rust-coloured.", "White undertail.", "Near Threatened."]
  },
  "tufted-duck": {
    T: { c: { black: 0.55, white: 0.35, yellow: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["40–47 cm", "65–72 cm", "0.6–1 kg"] },
    s: "A neat black-and-white diving duck with a drooping tuft on the back of its head and golden eyes. Common on lakes across Mongolia.",
    d: "The Tufted Duck breeds across northern Eurasia. It dives to the bottom for mussels and insect larvae. In Mongolia it is one of the most numerous diving ducks from April to October, especially in the Khurkh valley, Ögii Nuur, Ulaanbaatar and Khar Us Nuur.",
    f: ["Male: glossy black with bright white flanks.", "Long drooping tuft on the back of the head.", "Golden-yellow eye.", "Blue-grey bill with a black tip.", "Female: dark brown with a short tuft."],
    si: "Greater Scaup — grey back, no tuft. Common Goldeneye — white cheek spot.",
    h: "Lakes, ponds and slow rivers.",
    di: "All regions: Ögii Nuur, Khurkh, Ulaanbaatar, Khar Us Nuur, Böön Tsagaan, Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Mussels, snails and insect larvae.",
    br: "Nests near water in vegetation, often in gull colonies; 8–11 eggs.",
    be: "Dives often; rests in tight flocks.",
    v: "Mostly silent.",
    cu: "Nesting in gull colonies gives it protection from predators.",
    co: "Least Concern.",
    w: "Any lake in summer.",
    bt: "May–September",
    fa: ["Has a tuft on its head.", "Golden eyes.", "Nests among gulls."]
  },
  "greater-scaup": {
    T: { c: { gray: 0.35, black: 0.35, white: 0.25, yellow: 0.05 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["42–51 cm", "71–80 cm", "0.7–1.4 kg"] },
    s: "A diving duck like a Tufted Duck, but with a pale grey back and no tuft. A scarce migrant and summer visitor.",
    d: "The Greater Scaup breeds on tundra and taiga lakes and winters at sea. In Mongolia it is scarce, seen from May to September on lakes such as Ögii Nuur and Böön Tsagaan.",
    f: ["Male: dark green-glossed head, black breast, pale grey back, white flanks.", "No tuft; rounded head.", "Yellow eye.", "Female: brown with a large white patch around the bill base."],
    si: "Tufted Duck — black back, tuft. Common Pochard — chestnut head.",
    h: "Lakes on migration.",
    di: "Ögii Nuur, Böön Tsagaan, Ulaanbaatar, Achit Nuur.",
    mi: "Passage migrant and scarce summer visitor, May–September.",
    fo: "Molluscs and crustaceans.",
    br: "Nests on northern lakes (not confirmed in Mongolia).",
    be: "Dives in flocks.",
    v: "Mostly silent.",
    cu: "‘Scaup’ may come from ‘scalp’, the shellfish beds where it feeds.",
    co: "Least Concern.",
    w: "Scan Tufted Duck flocks at Ögii Nuur.",
    bt: "July",
    fa: ["Grey back, not black.", "Winters at sea.", "Feeds on shellfish."]
  }
});
