B2T("fr", {
  "long-tailed-duck": {
    name: "Harelde kakawi",
    s: "Petit canard marin pie ; le mâle porte de très longues rectrices centrales effilées. Migrateur peu commun au printemps sur les lacs mongols, Vulnérable à l’échelle mondiale.",
    d: "La Harelde kakawi niche sur les mares de la toundra arctique et hiverne en mer. C’est l’un des canards plongeant le plus profond, jusqu’à 60 m. Ses effectifs ont fortement chuté, d’où son statut de Vulnérable. En Mongolie, c’est une migratrice peu commune, surtout en mai, dans le nord et l’est.",
    f: ["Mâle : longue queue en aiguille ; plumage blanc, noir et gris changeant selon la saison.", "Bande rose sur le bec court et sombre.", "Femelle : brune et blanche avec une tache sombre sur la joue.", "Petite tête ronde.", "Plonge souvent."],
    si: "Garrot à œil d’or — tête plus grosse, tache blanche sur la joue, sans longue queue. Harle piette — blanc à lignes noires.",
    h: "Lacs en migration.",
    di: "Khentii (Khurkh), Dornod, lac Khar Us, lac Orog, Oulan-Bator.",
    mi: "Migratrice, surtout en mai.",
    fo: "Mollusques, crustacés et larves d’insectes.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Plonge en groupe ; très bavarde.",
    v: "Cris yodlés « ao-aoli ».",
    cu: "Son nom « kakawi » imite ses cris.",
    co: "Vulnérable.",
    w: "Examinez les lacs du nord-est en mai.",
    bt: "mai",
    fa: ["Plonge jusqu’à 60 m.", "Longue queue en aiguille.", "Vulnérable à l’échelle mondiale."]
  },
  "velvet-scoter": {
    name: "Macreuse brune",
    s: "Canard marin lourd et noir aux miroirs blancs ; la forme orientale (Macreuse de Stejneger) a un bec bossu. Migratrice rare dans le nord de la Mongolie.",
    d: "La Macreuse brune et sa cousine orientale, la Macreuse de Stejneger, nichent sur les lacs de la taïga et de la toundra et hivernent en mer. En Mongolie, on ne compte qu’une poignée de mentions, surtout en mai, sur des lacs du nord et du Khangaï.",
    f: ["Mâle : entièrement noir avec un petit croissant blanc sous l’œil.", "Secondaires blanches — miroir blanc en vol.", "Bec jaune et noir avec une bosse.", "Femelle : brun foncé avec deux taches pâles sur la face."],
    si: "Garrot à œil d’or — flancs blancs. Fuligule morillon — flancs blancs, huppe.",
    h: "Grands lacs en migration.",
    di: "Rare ; Terkhiin Tsagaan Nuur, Khentii.",
    mi: "Migratrice, mai–août.",
    fo: "Mollusques, crustacés et insectes.",
    br: "Niche près des lacs de la taïga (pas en Mongolie).",
    be: "Plonge en petits groupes.",
    v: "Surtout silencieuse.",
    cu: "Son nom anglais évoque son plumage noir velouté.",
    co: "Vulnérable.",
    w: "Examinez les grands lacs en mai.",
    bt: "mai",
    fa: ["Miroirs blancs visibles en vol.", "Vulnérable à l’échelle mondiale.", "Hiverne en mer."]
  },
  "smew": {
    name: "Harle piette",
    s: "Petit harle ; le mâle est blanc neige avec de fines lignes noires comme de la glace fêlée, la femelle a une calotte marron. Migrateur et nicheur rare dans le nord de la Mongolie.",
    d: "Le Harle piette niche dans la taïga du nord de l’Eurasie, dans des cavités d’arbres près des lacs et rivières, et hiverne plus au sud. En Mongolie, il passe en avril–mai et septembre–octobre et niche peut-être dans la taïga du nord. On le voit régulièrement sur les étangs d’Oulan-Bator et dans la vallée de Khurkh.",
    f: ["Mâle : blanc avec un masque noir et des lignes noires sur la tête et le dos.", "Femelle : grise à calotte marron et joues blanches.", "Petit bec étroit dentelé.", "Plonge souvent."],
    si: "Garrot à œil d’or — plus grand, tête sombre à tache blanche. Femelle de Harle huppé — plus grande, huppe ébouriffée.",
    h: "Lacs et rivières ; niche en forêt.",
    di: "Khentii (Khurkh), Oulan-Bator, lac Ögii, lac Buir.",
    mi: "Migrateur avril–mai et septembre–octobre ; nicheur possible.",
    fo: "Petits poissons et insectes aquatiques.",
    br: "Niche dans des cavités d’arbres, souvent d’anciennes loges de Pic noir ; 6 à 9 œufs.",
    be: "Plonge en petits groupes.",
    v: "Surtout silencieux.",
    cu: "Le motif du mâle évoque de la glace blanche fêlée de noir.",
    co: "Préoccupation mineure.",
    w: "Étangs de la Tuul à Oulan-Bator en avril.",
    bt: "avril–mai",
    fa: ["Niche dans les loges de pics.", "Le mâle ressemble à de la glace fêlée.", "Le plus petit harle."]
  },
  "red-breasted-merganser": {
    name: "Harle huppé",
    s: "Canard plongeur élancé au bec en scie et à la double huppe ébouriffée ; le mâle a la poitrine roux strié. Migrateur sur les lacs mongols, surtout au printemps.",
    d: "Le Harle huppé niche sur les lacs et côtes du nord et hiverne surtout en mer. Il poursuit les poissons sous l’eau avec son bec dentelé. En Mongolie, c’est un migrateur régulier en mai et en septembre–octobre, noté à Terkhiin Tsagaan Nuur, au lac Buir, au lac Ögii et près d’Oulan-Bator.",
    f: ["Bec rouge fin et dentelé.", "Double huppe ébouriffée et hérissée.", "Mâle : tête vert-noir, collier blanc, poitrine roux strié.", "Femelle : grise, tête brune se fondant dans le cou.", "Nage bas."],
    si: "Harle bièvre — plus grand, mâle blanc dessous, femelle à limite nette sur le cou. Harle piette — plus petit, bec court.",
    h: "Lacs et rivières en migration.",
    di: "Terkhiin Tsagaan Nuur, lac Buir, lac Ögii, Oulan-Bator, Böön Tsagaan.",
    mi: "Migrateur, avril–mai et septembre–octobre.",
    fo: "Petits poissons.",
    br: "Niche au sol près de l’eau dans le nord (non confirmé en Mongolie).",
    be: "Plonge à la poursuite des poissons ; les mâles paradent en étirant le cou.",
    v: "Surtout silencieux.",
    cu: "Détient le record de vitesse en vol horizontal chez les canards (environ 130 km/h).",
    co: "Préoccupation mineure.",
    w: "Terkhiin Tsagaan Nuur en mai.",
    bt: "mai",
    fa: ["Bec en dents de scie pour tenir les poissons.", "Voleur très rapide.", "Huppe ébouriffée."]
  },
  "red-crested-pochard": {
    name: "Nette rousse",
    s: "Grand canard plongeur coloré ; le mâle a une tête ronde orange et un bec rouge vif. Visiteur d’été, commun sur les lacs de l’ouest et du Gobi.",
    d: "La Nette rousse niche de l’Espagne à l’ouest de la Mongolie à travers l’Asie centrale. Elle se nourrit de plantes aquatiques, en plongeant ou en barbotant. En Mongolie, elle est commune aux lacs Khar Us, Ögii, Orog et à Böön Tsagaan.",
    f: ["Mâle : tête ronde roux orangé, bec rouge vif, poitrine et queue noires, flancs blancs.", "Femelle : brune à calotte sombre et joues pâles ; bec sombre à pointe rose.", "Large barre alaire blanche en vol."],
    si: "Fuligule milouin — mâle à tête marron, corps gris, bec sombre ; femelle gris-brun sans joues pâles.",
    h: "Grands lacs à roseaux, souvent saumâtres.",
    di: "Lac Khar Us, lac Ögii, lac Orog, Böön Tsagaan, lac Achit, Yolyn Am.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes aquatiques (surtout characées), graines.",
    br: "Niche dans les roseaux ; 8 à 10 œufs.",
    be: "Le mâle offre de la nourriture à la femelle pendant la parade.",
    v: "Surtout silencieuse ; éternuement sifflant du mâle.",
    cu: "L’un des rares canards dont le mâle nourrit la femelle.",
    co: "Préoccupation mineure.",
    w: "Lacs Khar Us et Ögii en juin.",
    bt: "mai–août",
    fa: ["Le mâle nourrit la femelle en parade.", "Bec rouge vif.", "Plonge et barbote."]
  },
  "common-pochard": {
    name: "Fuligule milouin",
    s: "Canard plongeur à tête marron, poitrine noire et corps gris pâle. Commun sur les lacs de toute la Mongolie, mais Vulnérable à l’échelle mondiale.",
    d: "Le Fuligule milouin niche de l’Europe à la Mongolie et hiverne plus au sud. Ses effectifs ont fortement chuté dans toute son aire ; il est désormais Vulnérable. En Mongolie, il est commun sur les lacs à roseaux d’avril à octobre : lac Ögii, vallée de Khurkh, lac Khar Us, étangs d’Oulan-Bator et lac Buir.",
    f: ["Mâle : tête roux marron, poitrine et queue noires, dos et flancs gris pâle.", "Œil rouge.", "Bec sombre à bande gris pâle.", "Femelle : gris-brun à « lunettes » pâles.", "Front fuyant."],
    si: "Nette rousse — tête orange, bec rouge. Fuligule nyroca — entièrement marron foncé, œil blanc. Fuligule de Baer — tête verte, poitrine marron.",
    h: "Lacs et étangs à roseaux.",
    di: "Toutes les régions : lac Ögii, Khurkh, lac Khar Us, Oulan-Bator, lac Buir, Böön Tsagaan.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Plantes aquatiques, graines et larves d’insectes.",
    br: "Niche dans les roseaux ; 8 à 10 œufs.",
    be: "Plonge ; se repose en groupes.",
    v: "Surtout silencieux.",
    cu: "Son déclin a surpris les scientifiques, tant il était commun en Europe.",
    co: "Vulnérable.",
    w: "Lac Ögii en été.",
    bt: "mai–sept.",
    fa: ["Vulnérable à l’échelle mondiale.", "Le mâle a l’œil rouge.", "Encore commun en Mongolie."]
  },
  "baers-pochard": {
    name: "Fuligule de Baer",
    s: "L’un des canards les plus rares du monde : tête vert foncé, poitrine marron et œil blanc. Quelques individus sont vus chaque printemps en Mongolie.",
    d: "Le Fuligule de Baer niche dans l’Extrême-Orient russe et le nord-est de la Chine et hiverne dans le sud de la Chine et au Bangladesh. Il en reste moins de 1 000 ; il est En danger critique à cause de la perte des zones humides et de la chasse. Les mentions printanières récentes en Mongolie (Böön Tsagaan, lac Ögii, lac Buir) sont importantes pour sa conservation.",
    f: ["Mâle : tête vert-noir foncé, poitrine marron, dos brun, avant des flancs blanc.", "Œil blanc.", "Sous-caudales blanches.", "Femelle : plus terne, tache marron à la base du bec."],
    si: "Fuligule nyroca — entièrement marron, sans tête verte. Fuligule morillon — huppé, dessus entièrement noir.",
    h: "Lacs à roseaux.",
    di: "Rare ; Böön Tsagaan, lac Ögii, lac Buir.",
    mi: "Migrateur, mai–juillet.",
    fo: "Plantes aquatiques, graines et invertébrés.",
    br: "Niche dans la végétation des marais (non prouvé en Mongolie).",
    be: "Se mêle aux autres canards plongeurs.",
    v: "Surtout silencieux.",
    cu: "Nommé d’après le naturaliste germano-balte Karl Ernst von Baer.",
    co: "En danger critique.",
    w: "Vérifiez Böön Tsagaan en mai ; signalez vos observations.",
    bt: "mai",
    fa: ["Moins de 1 000 individus.", "En danger critique.", "Œil blanc."]
  },
  "ferruginous-duck": {
    name: "Fuligule nyroca",
    s: "Petit canard plongeur marron foncé à œil blanc et sous-caudales d’un blanc pur. Visiteur d’été des lacs à roseaux ; Quasi menacé.",
    d: "Le Fuligule nyroca niche du sud de l’Europe jusqu’à l’ouest de la Chine et à la Mongolie. Il reste près des roseaux et passe souvent inaperçu. En Mongolie, il niche au lac Khar Us, à Böön Tsagaan, au lac Ögii, à Yolyn Am et près d’Oulan-Bator.",
    f: ["Corps acajou profond.", "Œil blanc chez le mâle, sombre chez la femelle.", "Sous-caudales blanc vif.", "Calotte en pointe.", "Barre alaire blanche en vol."],
    si: "Fuligule milouin — corps gris. Femelle de Fuligule morillon — œil jaune, couleur moins riche. Fuligule de Baer — tête verte.",
    h: "Lacs peu profonds à roseaux denses.",
    di: "Lac Khar Us, Böön Tsagaan, Oulan-Bator, lac Ögii, Yolyn Am, Khurkh.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Plantes aquatiques, graines et insectes.",
    br: "Niche dans les roseaux ; 7 à 10 œufs.",
    be: "Farouche ; reste près des roseaux.",
    v: "Surtout silencieux.",
    cu: "Son nom anglais « ferruginous » signifie « couleur de rouille ».",
    co: "Quasi menacé.",
    w: "Böön Tsagaan et lac Khar Us en juin.",
    bt: "mai–août",
    fa: ["Couleur de rouille.", "Sous-caudales blanches.", "Quasi menacé."]
  },
  "tufted-duck": {
    name: "Fuligule morillon",
    s: "Canard plongeur noir et blanc soigné, à huppe tombante sur la nuque et yeux dorés. Commun sur les lacs de toute la Mongolie.",
    d: "Le Fuligule morillon niche dans tout le nord de l’Eurasie. Il plonge jusqu’au fond pour chercher moules et larves d’insectes. En Mongolie, c’est l’un des canards plongeurs les plus nombreux d’avril à octobre, surtout dans la vallée de Khurkh, au lac Ögii, à Oulan-Bator et au lac Khar Us.",
    f: ["Mâle : noir brillant à flancs blanc vif.", "Longue huppe tombante sur la nuque.", "Œil jaune doré.", "Bec gris-bleu à pointe noire.", "Femelle : brun foncé à courte huppe."],
    si: "Fuligule milouinan — dos gris, sans huppe. Garrot à œil d’or — tache blanche sur la joue.",
    h: "Lacs, étangs et rivières lentes.",
    di: "Toutes les régions : lac Ögii, Khurkh, Oulan-Bator, lac Khar Us, Böön Tsagaan, lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Moules, escargots et larves d’insectes.",
    br: "Niche près de l’eau, souvent dans les colonies de mouettes ; 8 à 11 œufs.",
    be: "Plonge souvent ; se repose en groupes serrés.",
    v: "Surtout silencieux.",
    cu: "Nicher parmi les mouettes le protège des prédateurs.",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac en été.",
    bt: "mai–sept.",
    fa: ["Porte une huppe.", "Yeux dorés.", "Niche parmi les mouettes."]
  },
  "greater-scaup": {
    name: "Fuligule milouinan",
    s: "Canard plongeur semblable au Fuligule morillon, mais au dos gris pâle et sans huppe. Migrateur et visiteur d’été peu commun.",
    d: "Le Fuligule milouinan niche sur les lacs de la toundra et de la taïga et hiverne en mer. En Mongolie, il est peu commun, observé de mai à septembre sur des lacs comme le lac Ögii et Böön Tsagaan.",
    f: ["Mâle : tête sombre à reflets verts, poitrine noire, dos gris pâle, flancs blancs.", "Pas de huppe ; tête arrondie.", "Œil jaune.", "Femelle : brune avec une grande tache blanche à la base du bec."],
    si: "Fuligule morillon — dos noir, huppe. Fuligule milouin — tête marron.",
    h: "Lacs en migration.",
    di: "Lac Ögii, Böön Tsagaan, Oulan-Bator, lac Achit.",
    mi: "Migrateur et visiteur d’été peu commun, mai–septembre.",
    fo: "Mollusques et crustacés.",
    br: "Niche sur les lacs du nord (non confirmé en Mongolie).",
    be: "Plonge en groupes.",
    v: "Surtout silencieux.",
    cu: "Son nom anglais viendrait des bancs de coquillages où il se nourrit.",
    co: "Préoccupation mineure.",
    w: "Scrutez les groupes de morillons au lac Ögii.",
    bt: "juillet",
    fa: ["Dos gris, pas noir.", "Hiverne en mer.", "Se nourrit de coquillages."]
  }
});
