B2T("en", {
  "garganey": {
    T: { c: { brown: 0.5, white: 0.2, gray: 0.2, buff: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["37–41 cm", "59–67 cm", "250–600 g"] },
    s: "A small dabbling duck; the male has a bold white stripe curving from the eye to the nape. A common summer visitor to marshy lakes.",
    d: "The Garganey breeds across Europe and Asia and winters in Africa and South Asia — unusual among ducks, it is absent from its breeding grounds all winter. In Mongolia it arrives in May and breeds in shallow, grassy marshes throughout the country, especially Ögii Nuur, Khurkh, Ulaanbaatar and the Gobi lakes.",
    f: ["Male: brown head with a broad white crescent from eye to nape.", "Pale blue-grey forewing in flight.", "Long drooping black-and-white shoulder feathers.", "Female: brown with a striped face (dark eye-stripe, pale spot at bill base).", "Small, teal-sized."],
    si: "Common Teal — female similar but face plainer; male has chestnut-and-green head. Baikal Teal — male with a green-and-buff patterned face.",
    h: "Shallow marshes and grassy lake edges.",
    di: "All regions: Ögii Nuur, Khurkh, Ulaanbaatar, Böön Tsagaan, Orog Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–September; peak in May.",
    fo: "Insects, snails and seeds.",
    br: "Nests in grass near water; 8–11 eggs.",
    be: "Feeds with its head just below the surface.",
    v: "Male makes a dry, crackling rattle like a fingernail on a comb.",
    cu: "Its name may imitate the male’s rattling call.",
    co: "Least Concern.",
    w: "Khurkh valley and Ögii Nuur in May–June.",
    bt: "May–June",
    fa: ["Winters in Africa.", "Male rattles like a comb.", "Has a white eyebrow."]
  },
  "northern-shoveller": {
    T: { c: { white: 0.3, rufous: 0.25, black: 0.2, gray: 0.15, yellow: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["44–52 cm", "73–82 cm", "400–1,000 g"] },
    s: "A dabbling duck with a huge spoon-shaped bill; the male has a green head, white breast and chestnut flanks. Common across Mongolia in summer.",
    d: "The Northern Shoveler breeds across the Northern Hemisphere. Its broad bill has comb-like edges for sieving plankton from the water. Groups often swim in circles to stir up food. In Mongolia it is common on shallow lakes and marshes in all regions from April to October.",
    f: ["Very large, spatula-shaped bill.", "Male: bottle-green head, yellow eye, white breast, chestnut flanks.", "Female: mottled brown with orange edges to the bill.", "Pale blue forewing in flight.", "Sits low at the front."],
    si: "Mallard — narrow yellow bill; male has a white collar and brown breast. Common Shelduck — white body, red bill.",
    h: "Shallow, nutrient-rich lakes and marshes.",
    di: "All regions: Ögii Nuur, Khurkh, Ulaanbaatar, Böön Tsagaan, Khar Us Nuur, Orog Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Plankton, small crustaceans, seeds.",
    br: "Nests in grass near water; 8–12 eggs.",
    be: "Sweeps its bill through the surface; groups spin in circles.",
    v: "Male gives a low ‘took-took’.",
    cu: "Its Mongolian name, ‘ladle duck’, describes its bill.",
    co: "Least Concern.",
    w: "Any shallow lake in May–August.",
    bt: "May–August",
    fa: ["Sieves food through a comb-like bill.", "Swims in circles to feed.", "Bill wider than its head."]
  },
  "baikal-teal": {
    T: { c: { brown: 0.35, buff: 0.25, gray: 0.2, black: 0.1, white: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["39–43 cm", "65–75 cm", "360–520 g"] },
    s: "A small duck; the male’s face is a striking pattern of yellow, green and black. A spring and autumn migrant in northern and eastern Mongolia.",
    d: "The Baikal Teal breeds in the Siberian taiga and winters mainly in South Korea, where flocks of over a million perform swirling flights. Once threatened by hunting, it has recovered strongly. In Mongolia it passes through in April–May and August–October, especially in the Khurkh valley, Buir Nuur and around Ulaanbaatar.",
    f: ["Male: face patterned with cream, green and black crescents.", "Pinkish breast with dark spots; white vertical bar on the side of the breast.", "Female: brown with a round pale spot at the base of the bill.", "Long scapulars."],
    si: "Common Teal — male chestnut-and-green head without the pattern; female lacks the round face spot. Garganey — female with striped face.",
    h: "Lakes and marshes on migration.",
    di: "Khentii (Khurkh), Dornod (Buir Nuur, Mongol Daguur), Ulaanbaatar, Orog Nuur.",
    mi: "Passage migrant, April–May and August–October.",
    fo: "Seeds and water plants.",
    br: "Nests in the Siberian taiga (not in Mongolia).",
    be: "Forms huge flocks in winter.",
    v: "A deep, clucking ‘wot-wot’.",
    cu: "Its winter flocks in Korea are a famous natural spectacle.",
    co: "Least Concern.",
    w: "Khurkh valley in September.",
    bt: "May, September",
    fa: ["Winter flocks exceed a million birds.", "Named after Lake Baikal.", "Recovered from heavy hunting."]
  },
  "falcated-duck": {
    T: { c: { gray: 0.45, black: 0.2, white: 0.2, buff: 0.15 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["46–54 cm", "79–82 cm", "0.6–0.8 kg"] },
    s: "An elegant East Asian duck; the male has a glossy bronze-green ‘maned’ head and long sickle-shaped tertials. A summer visitor, common in the north and east.",
    d: "The Falcated Duck breeds from south-east Siberia and Mongolia to north-east China and Japan, and winters in China. In Mongolia it is a common breeder in the Khurkh valley, around Ulaanbaatar, at Ögii Nuur and in Dornod, from April to September.",
    f: ["Male: glossy green-and-bronze head with a mane on the nape.", "White throat with a black collar.", "Long, curved black-and-grey tertials hang over the tail like sickles.", "Grey finely patterned body.", "Female: plain brown with a dark bill."],
    si: "Gadwall — male plain grey-brown head. Eurasian Wigeon — male chestnut head with a cream crown.",
    h: "Lakes and marshes in river valleys.",
    di: "Khentii (Khurkh), Ulaanbaatar, Ögii Nuur, Dornod (Buir Nuur), Böön Tsagaan.",
    mi: "Summer visitor, April–September.",
    fo: "Water plants and seeds.",
    br: "Nests in grass near water; 6–10 eggs.",
    be: "Dabbles and grazes.",
    v: "Male gives a whistled ‘tyu-tyu’.",
    cu: "‘Falcated’ means ‘sickle-shaped’, from its tertials.",
    co: "Least Concern.",
    w: "Khurkh valley in May.",
    bt: "May–June",
    fa: ["Sickle-shaped wing feathers.", "Has a maned head.", "East Asian species."]
  },
  "gadwall": {
    T: { c: { gray: 0.5, brown: 0.3, black: 0.15, white: 0.05 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["46–56 cm", "78–90 cm", "0.6–1.1 kg"] },
    s: "A subtly patterned grey-brown dabbling duck with a black rear and a white patch on the wing. One of the most common ducks in Mongolia.",
    d: "The Gadwall breeds across the Northern Hemisphere on lakes with rich vegetation. In Mongolia it is abundant from April to October, especially in the Khurkh valley, around Ulaanbaatar, at Ögii Nuur, Khar Us Nuur and Böön Tsagaan.",
    f: ["Male: grey, finely patterned body with a black stern.", "Small white square on the inner wing (speculum), visible in flight.", "Female: mottled brown with an orange-sided bill.", "Steep forehead."],
    si: "Female Mallard — larger, blue speculum. Falcated Duck — male with maned green head.",
    h: "Lakes and marshes with abundant water plants.",
    di: "All regions: Khurkh, Ulaanbaatar, Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Water plants, seeds.",
    br: "Nests in tall grass; 8–12 eggs.",
    be: "Often steals food from diving ducks and coots.",
    v: "Male’s low croak; female’s quack.",
    cu: "Its elegance is in the fine detail of its grey feathers.",
    co: "Least Concern.",
    w: "Any lake in summer.",
    bt: "May–September",
    fa: ["Has a white speculum.", "Steals food from coots.", "One of Mongolia’s commonest ducks."]
  },
  "eurasian-wigeon": {
    T: { c: { gray: 0.35, rufous: 0.3, white: 0.15, buff: 0.1, black: 0.1 }, hb: ["water", "steppe"], bk: "flat", bh: ["swim", "walk"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["42–52 cm", "71–80 cm", "0.5–1.1 kg"] },
    s: "A round-headed dabbling duck; the male has a chestnut head with a cream forehead and whistles loudly. Common across Mongolia, especially on migration.",
    d: "The Eurasian Wigeon breeds across northern Eurasia and often grazes on land like a goose. In Mongolia it breeds on northern lakes and is common on passage in May and September across all regions, especially Ögii Nuur and the Khurkh valley.",
    f: ["Male: chestnut head with a cream-yellow forehead, pinkish breast, grey body.", "Large white wing patch in flight.", "Short blue-grey bill with a black tip.", "Female: rufous-brown with a round head.", "Pointed tail."],
    si: "Common Pochard — male chestnut head but black breast and grey body; dives. Falcated Duck — female similar but darker bill.",
    h: "Lakes, marshes and nearby grassland.",
    di: "All regions: Ögii Nuur, Khurkh, Ulaanbaatar, Böön Tsagaan, Khar Us Nuur.",
    mi: "Summer visitor and passage migrant, April–October.",
    fo: "Grasses, water plants and seeds.",
    br: "Nests in cover near water; 8–9 eggs.",
    be: "Grazes on shore in flocks.",
    v: "Male gives a loud, whistled ‘whee-oo’.",
    cu: "Its whistling calls are a sound of northern winters in Europe.",
    co: "Least Concern.",
    w: "Ögii Nuur in May and September.",
    bt: "May, September",
    fa: ["Grazes like a goose.", "Male whistles.", "Cream forehead."]
  },
  "chinese-spot-billed-duck": {
    T: { c: { brown: 0.6, buff: 0.2, black: 0.1, yellow: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["55–63 cm", "83–91 cm", "0.8–1.4 kg"] },
    s: "A large, brown dabbling duck with a pale face, a dark eye-stripe and a black bill with a yellow tip. A summer visitor, mainly in the north and east.",
    d: "The Eastern Spot-billed Duck breeds in eastern Asia, from Mongolia and south-east Siberia to China and Japan. It is spreading northward. In Mongolia it breeds on rivers and lakes of the Khentii (Khurkh), Selenge, Ulaanbaatar, Ögii Nuur and Dornod.",
    f: ["Dark brown body with a paler buff head.", "Dark cap and a dark stripe through the eye; dark cheek bar.", "Black bill with a yellow tip.", "Blue speculum with white edges.", "Sexes similar."],
    si: "Female Mallard — orange bill, more patterned body. Gadwall — white speculum.",
    h: "Rivers, lakes and marshes.",
    di: "Khentii (Khurkh), Ulaanbaatar, Ögii Nuur, Böön Tsagaan, Buir Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Seeds, water plants and invertebrates.",
    br: "Nests in cover near water; 8–14 eggs.",
    be: "Dabbles in shallow water.",
    v: "A Mallard-like quack.",
    cu: "Hybridises with the Mallard where both occur.",
    co: "Least Concern.",
    w: "Tuul River in Ulaanbaatar and Khurkh valley in summer.",
    bt: "May–August",
    fa: ["Yellow bill tip.", "Male and female look alike.", "Spreading north."]
  },
  "mallard": {
    T: { c: { gray: 0.35, brown: 0.3, white: 0.1, yellow: 0.1, black: 0.15 }, hb: ["water", "settlement"], bk: "flat", bh: ["swim"], vt: ["croak"], ac: "day", se: ["summer", "resident"], sz: ["50–65 cm", "81–98 cm", "0.7–1.6 kg"] },
    s: "The familiar wild duck: the male has a glossy green head, white collar and yellow bill. The most common duck in Mongolia; a few even winter on unfrozen rivers.",
    d: "The Mallard is found across the Northern Hemisphere and is the ancestor of most domestic ducks. It adapts to almost any wetland. In Mongolia it breeds everywhere and is abundant in the Khurkh valley, around Ulaanbaatar, at Ögii Nuur and Khar Us Nuur; some birds winter at warm springs and unfrozen stretches of the Tuul River.",
    f: ["Male: glossy green head, narrow white collar, chestnut breast, grey body, curled black tail feathers.", "Yellow bill (male); orange-and-brown bill (female).", "Female: mottled brown.", "Blue speculum edged with white on both sides."],
    si: "Northern Shoveler — male has green head but huge bill and white breast. Chinese Spot-billed Duck — pale face, yellow bill tip.",
    h: "All kinds of wetlands, including city ponds.",
    di: "All regions: Khurkh, Ulaanbaatar, Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Summer visitor, March–October; a few winter.",
    fo: "Seeds, plants, insects and snails.",
    br: "Nests in cover near water; 8–13 eggs.",
    be: "Up-ends to feed in shallow water.",
    v: "The female’s loud ‘quack-quack-quack’.",
    cu: "Ancestor of nearly all domestic ducks.",
    co: "Least Concern.",
    w: "Anywhere with water.",
    bt: "April–October",
    fa: ["Ancestor of the farmyard duck.", "Only the female quacks loudly.", "Some winter in Ulaanbaatar."]
  },
  "northern-pintail": {
    T: { c: { gray: 0.35, white: 0.25, brown: 0.3, black: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["51–66 cm", "80–95 cm", "0.5–1.3 kg"] },
    s: "A slender, long-necked duck; the male has a chocolate head, a white stripe up the neck and a long pin-like tail. Common across Mongolia, especially on migration.",
    d: "The Northern Pintail breeds across northern Eurasia and North America and is one of the most numerous ducks in the world. In Mongolia it breeds on lakes and marshes and is common on passage in April–May and September, especially at Ögii Nuur, the Khurkh valley and Khar Us Nuur.",
    f: ["Male: chocolate-brown head with a white stripe up the side of the neck.", "Long, needle-like black tail.", "Grey body, white breast.", "Female: slim, brown, with a long neck and pointed tail.", "Elegant, long-necked shape."],
    si: "Long-tailed Duck — a diving duck, pied. Gadwall — shorter neck, no long tail.",
    h: "Lakes, marshes and flooded meadows.",
    di: "All regions: Ögii Nuur, Khurkh, Khar Us Nuur, Ulaanbaatar, Böön Tsagaan.",
    mi: "Summer visitor and passage migrant, March–October.",
    fo: "Seeds, plants and invertebrates.",
    br: "Nests on open ground, often far from water; 7–9 eggs.",
    be: "Up-ends with its long neck to reach deeper food.",
    v: "Male gives a soft, flute-like ‘prrip’.",
    cu: "One of the most widespread ducks on Earth.",
    co: "Least Concern.",
    w: "Ögii Nuur in April and September.",
    bt: "April–May, September",
    fa: ["Has a pin-shaped tail.", "Nests far from water.", "Very widespread."]
  },
  "common-teal": {
    T: { c: { gray: 0.35, rufous: 0.25, brown: 0.2, yellow: 0.1, black: 0.1 }, hb: ["water"], bk: "flat", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["34–38 cm", "53–59 cm", "250–450 g"] },
    s: "The smallest dabbling duck; the male has a chestnut head with a green eye-patch and a yellow triangle under the tail. Common across Mongolia.",
    d: "The Eurasian Teal breeds across northern Eurasia. It is very fast and agile in flight, taking off almost vertically. In Mongolia it breeds on marshes and pools and is common on passage in April–May and September, in all regions.",
    f: ["Male: chestnut head with a broad green band edged in cream.", "Grey body with a white horizontal stripe.", "Yellow triangle beside the black undertail.", "Female: small, mottled brown with a green speculum.", "Tiny size."],
    si: "Garganey — male with a white eyebrow; female with a stronger face pattern. Baikal Teal — male with a patterned face.",
    h: "Marshes, pools and lake edges.",
    di: "All regions: Khurkh, Ögii Nuur, Ulaanbaatar, Buir Nuur, Böön Tsagaan, Khar Us Nuur.",
    mi: "Summer visitor and passage migrant, March–October.",
    fo: "Seeds and small invertebrates.",
    br: "Nests in dense cover near water; 8–11 eggs.",
    be: "Springs almost vertically into the air when disturbed.",
    v: "Male gives a clear ‘krit-krit’ whistle.",
    cu: "Tight, twisting flocks resemble waders in flight.",
    co: "Least Concern.",
    w: "Any marsh in spring or autumn.",
    bt: "April–May, September",
    fa: ["The smallest dabbling duck.", "Takes off almost vertically.", "Yellow triangle under the tail."]
  }
});
