B2T("fr", {
  "garganey": {
    name: "Sarcelle d’été",
    s: "Petit canard barboteur ; le mâle porte un large sourcil blanc courbé de l’œil à la nuque. Visiteur d’été commun des lacs marécageux.",
    d: "La Sarcelle d’été niche en Europe et en Asie et hiverne en Afrique et en Asie du Sud — fait rare chez les canards, elle quitte entièrement ses sites de nidification l’hiver. En Mongolie, elle arrive en mai et niche dans les marais herbeux peu profonds de tout le pays, surtout au lac Ögii, à Khurkh, à Oulan-Bator et sur les lacs du Gobi.",
    f: ["Mâle : tête brune avec un large croissant blanc de l’œil à la nuque.", "Avant de l’aile gris-bleu pâle en vol.", "Longues scapulaires tombantes noires et blanches.", "Femelle : brune à face rayée (trait sombre sur l’œil, tache pâle à la base du bec).", "Petite, de la taille d’une sarcelle."],
    si: "Sarcelle d’hiver — femelle semblable mais face plus unie ; mâle à tête marron et verte. Sarcelle élégante — mâle à face dessinée vert et chamois.",
    h: "Marais peu profonds et rives herbeuses.",
    di: "Toutes les régions : lac Ögii, Khurkh, Oulan-Bator, Böön Tsagaan, lac Orog, lac Khar Us.",
    mi: "Visiteur d’été, avril–septembre ; pic en mai.",
    fo: "Insectes, escargots et graines.",
    br: "Niche dans l’herbe près de l’eau ; 8 à 11 œufs.",
    be: "Se nourrit la tête juste sous la surface.",
    v: "Le mâle émet un crépitement sec, comme un ongle sur un peigne.",
    cu: "Son nom anglais imiterait le crépitement du mâle.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh et lac Ögii en mai–juin.",
    bt: "mai–juin",
    fa: ["Hiverne en Afrique.", "Le mâle crépite comme un peigne.", "Porte un sourcil blanc."]
  },
  "northern-shoveller": {
    name: "Canard souchet",
    s: "Canard barboteur à énorme bec en spatule ; le mâle a la tête verte, la poitrine blanche et les flancs marron. Commun dans toute la Mongolie en été.",
    d: "Le Canard souchet niche dans tout l’hémisphère Nord. Son large bec aux bords en peigne filtre le plancton. Les groupes tournent souvent en rond pour remuer la nourriture. En Mongolie, il est commun sur les lacs et marais peu profonds de toutes les régions d’avril à octobre.",
    f: ["Très grand bec en spatule.", "Mâle : tête vert bouteille, œil jaune, poitrine blanche, flancs marron.", "Femelle : brune mouchetée, bords du bec orange.", "Avant de l’aile bleu pâle en vol.", "Flotte bas à l’avant."],
    si: "Canard colvert — bec jaune étroit ; mâle à collier blanc et poitrine brune. Tadorne de Belon — corps blanc, bec rouge.",
    h: "Lacs et marais peu profonds et riches.",
    di: "Toutes les régions : lac Ögii, Khurkh, Oulan-Bator, Böön Tsagaan, lac Khar Us, lac Orog.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Plancton, petits crustacés, graines.",
    br: "Niche dans l’herbe près de l’eau ; 8 à 12 œufs.",
    be: "Balaie la surface avec son bec ; les groupes tournent en cercle.",
    v: "Le mâle émet un « touk-touk » grave.",
    cu: "Son nom mongol signifie « canard louche ».",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac peu profond de mai à août.",
    bt: "mai–août",
    fa: ["Filtre sa nourriture avec un bec en peigne.", "Tourne en rond pour se nourrir.", "Bec plus large que sa tête."]
  },
  "baikal-teal": {
    name: "Sarcelle élégante",
    s: "Petit canard ; le mâle a la face dessinée d’un motif spectaculaire jaune, vert et noir. Migrateur au printemps et en automne dans le nord et l’est de la Mongolie.",
    d: "La Sarcelle élégante niche dans la taïga sibérienne et hiverne surtout en Corée du Sud, où des vols de plus d’un million d’oiseaux tournoient dans le ciel. Autrefois menacée par la chasse, elle s’est fortement rétablie. En Mongolie, elle passe en avril–mai et août–octobre, surtout dans la vallée de Khurkh, au lac Buir et autour d’Oulan-Bator.",
    f: ["Mâle : face dessinée de croissants crème, verts et noirs.", "Poitrine rosée tachetée de sombre ; barre verticale blanche sur le côté de la poitrine.", "Femelle : brune avec une tache pâle ronde à la base du bec.", "Longues scapulaires."],
    si: "Sarcelle d’hiver — mâle à tête marron et verte sans motif ; femelle sans tache ronde. Sarcelle d’été — femelle à face rayée.",
    h: "Lacs et marais en migration.",
    di: "Khentii (Khurkh), Dornod (lac Buir, Mongol Daguur), Oulan-Bator, lac Orog.",
    mi: "Migratrice, avril–mai et août–octobre.",
    fo: "Graines et plantes aquatiques.",
    br: "Niche dans la taïga sibérienne (pas en Mongolie).",
    be: "Forme d’immenses vols en hiver.",
    v: "Un « wot-wot » grave et gloussé.",
    cu: "Ses vols hivernaux en Corée sont un spectacle naturel célèbre.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en septembre.",
    bt: "mai, sept.",
    fa: ["Vols hivernaux de plus d’un million d’oiseaux.", "Son nom anglais évoque le lac Baïkal.", "S’est rétablie après une forte chasse."]
  },
  "falcated-duck": {
    name: "Canard à faucilles",
    s: "Élégant canard d’Asie orientale ; le mâle a une tête vert bronze brillant à « crinière » et de longues tertiaires en faucille. Visiteur d’été, commun dans le nord et l’est.",
    d: "Le Canard à faucilles niche du sud-est de la Sibérie et de la Mongolie jusqu’au nord-est de la Chine et au Japon, et hiverne en Chine. En Mongolie, c’est un nicheur commun dans la vallée de Khurkh, autour d’Oulan-Bator, au lac Ögii et dans le Dornod, d’avril à septembre.",
    f: ["Mâle : tête vert et bronze brillante avec une crinière sur la nuque.", "Gorge blanche à collier noir.", "Longues tertiaires recourbées noires et grises retombant sur la queue comme des faucilles.", "Corps gris finement dessiné.", "Femelle : brune unie à bec sombre."],
    si: "Canard chipeau — mâle à tête gris-brun unie. Canard siffleur — mâle à tête marron et front crème.",
    h: "Lacs et marais des vallées fluviales.",
    di: "Khentii (Khurkh), Oulan-Bator, lac Ögii, Dornod (lac Buir), Böön Tsagaan.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Plantes aquatiques et graines.",
    br: "Niche dans l’herbe près de l’eau ; 6 à 10 œufs.",
    be: "Barbote et pâture.",
    v: "Le mâle siffle « tiou-tiou ».",
    cu: "Son nom vient de ses tertiaires en forme de faucille.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en mai.",
    bt: "mai–juin",
    fa: ["Plumes alaires en faucille.", "Tête à crinière.", "Espèce d’Asie orientale."]
  },
  "gadwall": {
    name: "Canard chipeau",
    s: "Canard barboteur gris-brun finement dessiné, à l’arrière noir et au miroir blanc. L’un des canards les plus communs de Mongolie.",
    d: "Le Canard chipeau niche dans tout l’hémisphère Nord sur des lacs riches en végétation. En Mongolie, il est abondant d’avril à octobre, surtout dans la vallée de Khurkh, autour d’Oulan-Bator, aux lacs Ögii et Khar Us et à Böön Tsagaan.",
    f: ["Mâle : corps gris finement vermiculé, arrière noir.", "Petit carré blanc sur l’aile interne (miroir), visible en vol.", "Femelle : brune mouchetée, bec bordé d’orange.", "Front abrupt."],
    si: "Femelle de Canard colvert — plus grande, miroir bleu. Canard à faucilles — mâle à tête verte à crinière.",
    h: "Lacs et marais riches en plantes aquatiques.",
    di: "Toutes les régions : Khurkh, Oulan-Bator, lac Ögii, lac Khar Us, Böön Tsagaan, lac Orog.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Plantes aquatiques, graines.",
    br: "Niche dans les herbes hautes ; 8 à 12 œufs.",
    be: "Vole souvent la nourriture des canards plongeurs et des foulques.",
    v: "Croassement grave du mâle ; cancanement de la femelle.",
    cu: "Son élégance tient au fin détail de ses plumes grises.",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac en été.",
    bt: "mai–sept.",
    fa: ["Miroir blanc.", "Vole la nourriture des foulques.", "L’un des canards les plus communs de Mongolie."]
  },
  "eurasian-wigeon": {
    name: "Canard siffleur",
    s: "Canard barboteur à tête ronde ; le mâle a la tête marron et le front crème et siffle fort. Commun dans toute la Mongolie, surtout en migration.",
    d: "Le Canard siffleur niche dans le nord de l’Eurasie et pâture souvent à terre comme une oie. En Mongolie, il niche sur les lacs du nord et passe en nombre en mai et septembre dans toutes les régions, surtout au lac Ögii et dans la vallée de Khurkh.",
    f: ["Mâle : tête marron à front jaune crème, poitrine rosée, corps gris.", "Grande tache alaire blanche en vol.", "Bec court gris-bleu à pointe noire.", "Femelle : brun roux à tête ronde.", "Queue pointue."],
    si: "Fuligule milouin — mâle à tête marron mais poitrine noire et corps gris ; plonge. Canard à faucilles — femelle semblable mais bec plus sombre.",
    h: "Lacs, marais et prairies voisines.",
    di: "Toutes les régions : lac Ögii, Khurkh, Oulan-Bator, Böön Tsagaan, lac Khar Us.",
    mi: "Visiteur d’été et migrateur, avril–octobre.",
    fo: "Herbes, plantes aquatiques et graines.",
    br: "Niche à couvert près de l’eau ; 8 ou 9 œufs.",
    be: "Pâture en groupes sur les rives.",
    v: "Le mâle siffle fort « ouii-ou ».",
    cu: "Ses sifflements sont un son familier des hivers européens.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai et septembre.",
    bt: "mai, sept.",
    fa: ["Pâture comme une oie.", "Le mâle siffle.", "Front crème."]
  },
  "chinese-spot-billed-duck": {
    name: "Canard de Chine",
    s: "Grand canard barboteur brun à face pâle, trait sombre sur l’œil et bec noir à pointe jaune. Visiteur d’été, surtout dans le nord et l’est.",
    d: "Le Canard de Chine niche en Asie orientale, de la Mongolie et du sud-est de la Sibérie à la Chine et au Japon, et s’étend vers le nord. En Mongolie, il niche sur les rivières et lacs du Khentii (Khurkh), de la Selenge, d’Oulan-Bator, du lac Ögii et du Dornod.",
    f: ["Corps brun foncé, tête chamois plus pâle.", "Calotte sombre et trait sombre à travers l’œil ; barre sombre sur la joue.", "Bec noir à pointe jaune.", "Miroir bleu bordé de blanc.", "Sexes semblables."],
    si: "Femelle de Canard colvert — bec orange, corps plus dessiné. Canard chipeau — miroir blanc.",
    h: "Rivières, lacs et marais.",
    di: "Khentii (Khurkh), Oulan-Bator, lac Ögii, Böön Tsagaan, lac Buir.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Graines, plantes aquatiques et invertébrés.",
    br: "Niche à couvert près de l’eau ; 8 à 14 œufs.",
    be: "Barbote en eau peu profonde.",
    v: "Un cancan comme le Colvert.",
    cu: "S’hybride avec le Colvert là où les deux cohabitent.",
    co: "Préoccupation mineure.",
    w: "Rivière Tuul à Oulan-Bator et vallée de Khurkh en été.",
    bt: "mai–août",
    fa: ["Pointe du bec jaune.", "Mâle et femelle se ressemblent.", "S’étend vers le nord."]
  },
  "mallard": {
    name: "Canard colvert",
    s: "Le canard sauvage familier : le mâle a la tête vert brillant, un collier blanc et le bec jaune. Le canard le plus commun de Mongolie ; quelques-uns hivernent même sur les rivières non gelées.",
    d: "Le Canard colvert est présent dans tout l’hémisphère Nord et est l’ancêtre de la plupart des canards domestiques. Il s’adapte à presque toutes les zones humides. En Mongolie, il niche partout et abonde dans la vallée de Khurkh, autour d’Oulan-Bator, aux lacs Ögii et Khar Us ; quelques oiseaux hivernent près des sources chaudes et sur les tronçons non gelés de la Tuul.",
    f: ["Mâle : tête vert brillant, fin collier blanc, poitrine marron, corps gris, rectrices noires bouclées.", "Bec jaune (mâle) ; bec orange et brun (femelle).", "Femelle : brune mouchetée.", "Miroir bleu bordé de blanc des deux côtés."],
    si: "Canard souchet — mâle à tête verte mais énorme bec et poitrine blanche. Canard de Chine — face pâle, pointe du bec jaune.",
    h: "Toutes sortes de zones humides, y compris les étangs urbains.",
    di: "Toutes les régions : Khurkh, Oulan-Bator, lac Ögii, lac Khar Us, Böön Tsagaan, lac Orog.",
    mi: "Visiteur d’été, mars–octobre ; quelques hivernants.",
    fo: "Graines, plantes, insectes et escargots.",
    br: "Niche à couvert près de l’eau ; 8 à 13 œufs.",
    be: "Bascule pour se nourrir en eau peu profonde.",
    v: "Le « coin-coin-coin » sonore de la femelle.",
    cu: "Ancêtre de presque tous les canards domestiques.",
    co: "Préoccupation mineure.",
    w: "Partout où il y a de l’eau.",
    bt: "avril–oct.",
    fa: ["Ancêtre du canard de basse-cour.", "Seule la femelle cancane fort.", "Certains hivernent à Oulan-Bator."]
  },
  "northern-pintail": {
    name: "Canard pilet",
    s: "Canard élancé au long cou ; le mâle a la tête chocolat, une bande blanche remontant le cou et une longue queue en aiguille. Commun dans toute la Mongolie, surtout en migration.",
    d: "Le Canard pilet niche dans le nord de l’Eurasie et de l’Amérique du Nord et compte parmi les canards les plus nombreux au monde. En Mongolie, il niche sur les lacs et marais et passe en nombre en avril–mai et septembre, surtout au lac Ögii, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Mâle : tête brun chocolat avec une bande blanche remontant sur le côté du cou.", "Longue queue noire en aiguille.", "Corps gris, poitrine blanche.", "Femelle : fine, brune, long cou et queue pointue.", "Silhouette élégante au long cou."],
    si: "Harelde kakawi — canard plongeur, pie. Canard chipeau — cou plus court, sans longue queue.",
    h: "Lacs, marais et prairies inondées.",
    di: "Toutes les régions : lac Ögii, Khurkh, lac Khar Us, Oulan-Bator, Böön Tsagaan.",
    mi: "Visiteur d’été et migrateur, mars–octobre.",
    fo: "Graines, plantes et invertébrés.",
    br: "Niche en terrain découvert, souvent loin de l’eau ; 7 à 9 œufs.",
    be: "Bascule avec son long cou pour atteindre la nourriture plus profonde.",
    v: "Le mâle émet un doux « prrip » flûté.",
    cu: "L’un des canards les plus répandus sur Terre.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en avril et septembre.",
    bt: "avril–mai, sept.",
    fa: ["Queue en forme d’aiguille.", "Niche loin de l’eau.", "Très répandu."]
  },
  "common-teal": {
    name: "Sarcelle d’hiver",
    s: "Le plus petit canard barboteur ; le mâle a la tête marron avec une tache verte autour de l’œil et un triangle jaune sous la queue. Commun dans toute la Mongolie.",
    d: "La Sarcelle d’hiver niche dans tout le nord de l’Eurasie. Très rapide et agile en vol, elle décolle presque à la verticale. En Mongolie, elle niche dans les marais et les mares et passe en nombre en avril–mai et septembre dans toutes les régions.",
    f: ["Mâle : tête marron avec une large bande verte bordée de crème.", "Corps gris avec une ligne blanche horizontale.", "Triangle jaune à côté des sous-caudales noires.", "Femelle : petite, brune mouchetée, miroir vert.", "Toute petite taille."],
    si: "Sarcelle d’été — mâle à sourcil blanc ; femelle à dessin facial plus marqué. Sarcelle élégante — mâle à face dessinée.",
    h: "Marais, mares et bords de lacs.",
    di: "Toutes les régions : Khurkh, lac Ögii, Oulan-Bator, lac Buir, Böön Tsagaan, lac Khar Us.",
    mi: "Visiteur d’été et migrateur, mars–octobre.",
    fo: "Graines et petits invertébrés.",
    br: "Niche à couvert dense près de l’eau ; 8 à 11 œufs.",
    be: "S’envole presque verticalement quand on la dérange.",
    v: "Le mâle siffle un « krit-krit » clair.",
    cu: "Ses vols serrés et sinueux rappellent ceux des limicoles.",
    co: "Préoccupation mineure.",
    w: "N’importe quel marais au printemps ou en automne.",
    bt: "avril–mai, sept.",
    fa: ["Le plus petit canard barboteur.", "Décolle presque à la verticale.", "Triangle jaune sous la queue."]
  }
});
