B2T("en", {
  "black-legged-kittiwake": {
    T: { c: { white: 0.6, gray: 0.3, black: 0.1 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["37–42 cm", "93–105 cm", "300–500 g"] },
    s: "A small, gentle-faced ocean gull with ‘ink-dipped’ black wingtips and black legs. An exceptional vagrant to Mongolia, recorded at Böön Tsagaan Nuur.",
    d: "The Black-legged Kittiwake is a true seabird that breeds on sea cliffs around the Arctic and North Pacific and spends the winter far out at sea. It has declined sharply and is Vulnerable. A bird at Böön Tsagaan Nuur in July 2023 is one of very few inland records in Central Asia.",
    f: ["White head, grey back and wings.", "Solid black wingtips without white spots.", "Short black legs.", "Plain yellow bill.", "Juvenile: black ‘W’ across the wings."],
    si: "Common (Mew) Gull — greenish-yellow legs, white spots in the black wingtip.",
    h: "Open sea and sea cliffs; vagrants on large lakes.",
    di: "Exceptional vagrant; Böön Tsagaan Nuur.",
    mi: "Vagrant.",
    fo: "Small fish and plankton.",
    br: "Nests on narrow sea-cliff ledges (not in Mongolia).",
    be: "Buoyant flight; picks food from the surface.",
    v: "A nasal ‘kitti-wa-aake’ at colonies.",
    cu: "Its name copies its call.",
    co: "Vulnerable.",
    w: "Not expected.",
    bt: "—",
    fa: ["Named after its call.", "Spends winter at sea.", "Globally Vulnerable."]
  },
  "slender-billed-gull": {
    T: { c: { white: 0.65, gray: 0.25, red: 0.1 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["37–42 cm", "90–102 cm", "220–350 g"] },
    s: "A pale gull with a long, sloping forehead, a thin dark-red bill and often a pink flush on the breast. A rare visitor to Mongolian lakes.",
    d: "The Slender-billed Gull breeds on salt lakes and lagoons from the Mediterranean to Kazakhstan and Pakistan. In Mongolia it is a rare visitor in May–July, with records at Ögii Nuur and Böön Tsagaan.",
    f: ["All-white head in all seasons.", "Long neck and long, sloping forehead.", "Thin, dark red bill.", "Pale eye.", "Pink tinge to the underparts in spring."],
    si: "Black-headed Gull — dark hood in summer, shorter bill, dark eye.",
    h: "Salt lakes and brackish lagoons.",
    di: "Rare; Ögii Nuur, Böön Tsagaan.",
    mi: "Rare visitor, May–July.",
    fo: "Small fish and insects.",
    br: "Colonial on islands (not in Mongolia).",
    be: "Picks food from the surface while swimming.",
    v: "Lower-pitched than Black-headed Gull.",
    cu: "Named for its long, slender bill.",
    co: "Least Concern.",
    w: "Check gull flocks at Ögii Nuur.",
    bt: "May–July",
    fa: ["Never has a dark hood.", "Pink-flushed in spring.", "Lives on salt lakes."]
  },
  "brown-headed-gull": {
    T: { c: { white: 0.45, gray: 0.3, brown: 0.15, black: 0.1 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["summer"], sz: ["41–45 cm", "105–110 cm", "450–700 g"] },
    s: "A gull of the Tibetan Plateau and Central Asia with a brown hood and pale eyes. A local summer visitor to Gobi lakes, especially Böön Tsagaan.",
    d: "The Brown-headed Gull breeds on high-altitude lakes in Tibet, Qinghai, Central Asia and the Gobi, and winters in India and South-East Asia. In Mongolia it breeds or summers at Böön Tsagaan, Orog Nuur and Ögii Nuur.",
    f: ["Brown hood in summer; white head with a dark ear spot in winter.", "Pale yellow eye (dark in Black-headed Gull).", "Black wingtips with large white ‘mirrors’.", "Red bill and legs.", "Larger than Black-headed Gull."],
    si: "Black-headed Gull — smaller, dark eye, white wedge on the outer wing without big mirrors.",
    h: "Lakes in deserts and high plateaus.",
    di: "Gobi lakes (Böön Tsagaan, Orog Nuur, Taatsiin Tsagaan), Ögii Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Fish, insects and scraps.",
    br: "Colonial on islands in lakes.",
    be: "Mixes with Black-headed Gulls and terns.",
    v: "Harsh ‘gek-gek’ calls.",
    cu: "Visitors to Lake Qinghai and Tibet know it as the most common gull there.",
    co: "Least Concern.",
    w: "Böön Tsagaan Nuur in June.",
    bt: "May–July",
    fa: ["Breeds up to 4,500 m in Tibet.", "Has pale eyes.", "Winters in India."]
  },
  "black-headed-gull": {
    T: { c: { white: 0.55, gray: 0.25, brown: 0.1, red: 0.1 }, hb: ["water", "settlement"], bk: "gull", bh: ["swim", "soar", "walk"], vt: ["laugh"], ac: "day", se: ["summer"], sz: ["37–43 cm", "94–110 cm", "200–350 g"] },
    s: "A small, noisy gull with a chocolate-brown hood in summer and a white wedge on the front of the wing. The most common gull in Mongolia.",
    d: "The Black-headed Gull breeds across Europe and Asia. Despite its name, its summer hood is dark brown, not black. In Mongolia it nests in large colonies on islands and marshes of lakes throughout the country, especially Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Buir Nuur and Orog Nuur, from April to October.",
    f: ["Chocolate-brown hood in summer; white head with a dark ear spot in winter.", "Dark red bill and legs.", "White leading edge to the outer wing.", "Grey back.", "Dark eye with a thin white eye-ring."],
    si: "Brown-headed Gull — larger, pale eye, large white mirrors in black wingtips. Little Gull — smaller, black hood, dark underwings.",
    h: "Lakes, marshes and rivers; also towns and fields.",
    di: "All regions: Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Buir Nuur, Orog Nuur, Ulaanbaatar.",
    mi: "Summer visitor, March–October.",
    fo: "Insects, worms, small fish and scraps.",
    br: "Colonial on islands or floating vegetation; 2–3 eggs.",
    be: "Follows ploughs and fishermen; very noisy at colonies.",
    v: "A harsh, laughing ‘kree-ar’.",
    cu: "Its colonies protect other nesting waterbirds such as grebes.",
    co: "Least Concern.",
    w: "Ögii Nuur colonies in June.",
    bt: "May–August",
    fa: ["Its ‘black’ head is actually brown.", "Loses its hood in winter.", "Mongolia’s most common gull."]
  },
  "little-gull": {
    T: { c: { white: 0.5, gray: 0.3, black: 0.2 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage", "summer"], sz: ["25–30 cm", "70–78 cm", "90–150 g"] },
    s: "The smallest gull in the world, with a black hood and dark grey underwings. A scarce migrant and local breeder on Mongolian lakes.",
    d: "The Little Gull breeds on marshy lakes from the Baltic to eastern Siberia. It flies buoyantly like a tern, picking insects from the water surface. In Mongolia it is a scarce migrant and local summer visitor at Ögii Nuur, Orog Nuur, Böön Tsagaan and in Dornod.",
    f: ["Tiny, with a jet-black hood in summer.", "Dark grey to blackish underwings; rounded white wingtips.", "Short red legs and dark bill.", "Tern-like flight.", "Juvenile with a dark ‘W’ across the wings."],
    si: "Black-headed Gull — larger, brown hood, pale underwing. White-winged Tern — black body in summer, forked tail.",
    h: "Marshy lakes with vegetation.",
    di: "Ögii Nuur, Orog Nuur, Böön Tsagaan, Khar Us Nuur, Buir Nuur.",
    mi: "Passage migrant and summer visitor, May–September.",
    fo: "Insects picked from the surface.",
    br: "Nests in marshes, often with terns; 2–3 eggs.",
    be: "Dips to the water like a marsh tern.",
    v: "Short, nasal ‘kek-kek’.",
    cu: "The world’s smallest gull.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May, August",
    fa: ["World’s smallest gull.", "Dark underwings.", "Flies like a tern."]
  },
  "rosss-gull": {
    T: { c: { white: 0.5, gray: 0.3, red: 0.15, black: 0.05 }, hb: ["water"], bk: "gull", bh: ["soar", "swim"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["29–32 cm", "82–92 cm", "120–250 g"] },
    s: "A rare, beautiful Arctic gull with a pink body, a thin black necklace and a wedge-shaped tail. Listed for Mongolia, but with no GBIF records.",
    d: "Ross’s Gull breeds in the Siberian Arctic and winters along the edge of the Arctic pack ice. It was one of the most sought-after birds by explorers. Any sighting in Mongolia would be exceptional.",
    f: ["Pink flush to the underparts in summer.", "Thin black collar.", "Wedge-shaped tail.", "Small black bill and red legs.", "Grey underwing."],
    si: "Little Gull — black hood, square tail.",
    h: "Arctic tundra and pack ice.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects and small marine animals.",
    br: "Nests in the Siberian Arctic (not in Mongolia).",
    be: "Tern-like flight.",
    v: "Melodious, tern-like calls.",
    cu: "Named after the Arctic explorer James Clark Ross.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Has a pink body.", "Named after a polar explorer.", "Winters at the ice edge."]
  },
  "pallass-gull": {
    T: { c: { white: 0.5, gray: 0.25, black: 0.15, yellow: 0.1 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["summer"], sz: ["55–72 cm", "146–170 cm", "1.1–2 kg"] },
    s: "A huge gull with a black hood, white eye-crescents and a heavy yellow bill banded with black and red. A summer visitor to large western and Gobi lakes.",
    d: "Pallas’s Gull (Great Black-headed Gull) breeds on islands in large lakes from the Black Sea to Mongolia and western China and winters around the Arabian Sea and India. It is the only large gull with a black hood. In Mongolia it breeds in colonies at Khar Us Nuur, Ögii Nuur, Böön Tsagaan, Orog Nuur and Achit Nuur.",
    f: ["Very large, with a black hood in summer and white crescents above and below the eye.", "Heavy yellow bill with a black and red band near the tip.", "Pale grey back; black-and-white wingtips.", "Long, sloping forehead.", "Yellow legs."],
    si: "Black-headed Gull — much smaller, brown hood. Mongolian Gull — white head.",
    h: "Large lakes with islands.",
    di: "Khar Us Nuur, Ögii Nuur, Böön Tsagaan, Orog Nuur, Achit Nuur, Bayan-Ölgii lakes.",
    mi: "Summer visitor, April–October.",
    fo: "Fish; also rodents and insects.",
    br: "Colonial on islands; 2–3 eggs; one of the earliest breeding gulls.",
    be: "Fishes by plunging and snatching.",
    v: "A deep, crow-like ‘kraa-ah’.",
    cu: "Named after Peter Simon Pallas, who explored Mongolia and Siberia.",
    co: "Least Concern.",
    w: "Böön Tsagaan and Khar Us Nuur in June.",
    bt: "May–August",
    fa: ["The only big gull with a black hood.", "Named after Pallas.", "Nests on lake islands."]
  },
  "black-tailed-gull": {
    T: { c: { white: 0.5, gray: 0.3, black: 0.15, red: 0.05 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["44–48 cm", "126–128 cm", "450–650 g"] },
    s: "A medium-sized East Asian coastal gull with a broad black band on the tail and a red-and-black bill tip. Listed for Mongolia, with no GBIF records.",
    d: "The Black-tailed Gull breeds on the coasts of Japan, Korea, eastern China and the Russian Far East. It rarely strays inland; in Mongolia it is an exceptional vagrant.",
    f: ["White tail with a broad black band.", "Dark grey back.", "Yellow bill with a red and black tip.", "Yellow legs."],
    si: "Common Gull — no black tail band.",
    h: "Sea coasts and harbours.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Fish and scraps.",
    br: "Colonial on sea cliffs (not in Mongolia).",
    be: "Follows fishing boats.",
    v: "A cat-like mewing, giving it the Japanese name ‘sea cat’.",
    cu: "Its breeding island in Japan, Kabushima, is a national monument.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Called ‘sea cat’ in Japanese.", "Black band on the tail.", "Coastal species."]
  },
  "mew-gull": {
    T: { c: { white: 0.6, gray: 0.3, black: 0.05, yellow: 0.05 }, hb: ["water", "steppe"], bk: "gull", bh: ["swim", "soar", "walk"], vt: ["laugh"], ac: "day", se: ["summer", "passage"], sz: ["40–46 cm", "100–125 cm", "300–500 g"] },
    s: "A medium-sized, gentle-faced gull with a thin yellow-green bill and legs. A summer visitor and migrant, mostly in northern and eastern Mongolia.",
    d: "The Common Gull (Mew Gull) breeds across northern Eurasia; the eastern form kamtschatschensis is larger. In Mongolia it breeds on lakes and rivers in the north and east (Buir Nuur, Ögii Nuur, Khurkh) and is seen on passage in all regions.",
    f: ["Rounded white head and dark eye — a gentle expression.", "Thin, plain yellow-green bill.", "Greenish-yellow legs.", "Grey back, black wingtips with white spots.", "Winter: head streaked grey."],
    si: "Mongolian Gull — much larger, heavy bill with red spot. Black-legged Kittiwake — black legs, solid black wingtips.",
    h: "Lakes, rivers and steppe.",
    di: "Buir Nuur, Ögii Nuur, Böön Tsagaan, Ulaanbaatar, Khar Us Nuur, Khurkh.",
    mi: "Summer visitor and passage migrant, April–October.",
    fo: "Insects, worms, fish and small rodents.",
    br: "Nests on islands, stumps or shores; 2–3 eggs.",
    be: "Feeds on fields and steppe as well as water.",
    v: "High, mewing ‘kee-ya’.",
    cu: "Its American name, Mew Gull, comes from its cat-like call.",
    co: "Least Concern.",
    w: "Buir Nuur in summer.",
    bt: "May–September",
    fa: ["Has a gentle face.", "Eats worms on fields.", "Mews like a cat."]
  },
  "lesser-black-backed-gull": {
    T: { c: { white: 0.5, gray: 0.35, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["52–67 cm", "128–150 cm", "0.6–1.1 kg"] },
    s: "A large gull with a dark grey back and yellow legs; the Siberian form (Heuglin’s Gull) passes through Mongolia. A scarce migrant.",
    d: "The Lesser Black-backed Gull complex includes Heuglin’s Gull (subspecies heuglini), which breeds on the Siberian tundra and winters in the Middle East and India. It crosses Mongolia on migration in May and August–October in small numbers.",
    f: ["Slate-grey back, darker than the Mongolian Gull.", "Yellow legs.", "Yellow bill with a red spot.", "White head in summer.", "Long wings."],
    si: "Mongolian Gull — paler grey back, pinkish legs.",
    h: "Lakes and rivers on migration.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Khar Us Nuur.",
    mi: "Passage migrant, May and August–October.",
    fo: "Fish, scraps, insects.",
    br: "Nests on Siberian tundra (not in Mongolia).",
    be: "Rests with other gulls on shores.",
    v: "Deep ‘kyow’.",
    cu: "Gull identification is a favourite challenge of birders.",
    co: "Least Concern.",
    w: "Look through large gulls in autumn.",
    bt: "May, September",
    fa: ["Darker back than most gulls.", "Siberian form migrates through Mongolia.", "Yellow legs."]
  },
  "american-herring-gull": {
    latin: "Larus vegae mongolicus",
    name: "Mongolian Gull",
    T: { c: { white: 0.55, gray: 0.35, black: 0.05, yellow: 0.05 }, hb: ["water", "steppe", "settlement"], bk: "gull", bh: ["swim", "soar", "walk"], vt: ["laugh"], ac: "day", se: ["summer"], sz: ["58–68 cm", "140–155 cm", "0.9–1.5 kg"] },
    s: "A big, pale-grey gull with a white head, pale eye and red bill spot — the large gull of Mongolia’s lakes. It belongs to the herring gull group (here the Mongolian Gull).",
    d: "The large ‘herring gulls’ are a complex of closely related forms. In Mongolia the breeding bird is the Mongolian Gull (Larus vegae mongolicus, sometimes treated as a separate species), which nests on islands in lakes across the country and winters in Korea and eastern China. It is common at Ögii Nuur, Khar Us Nuur, Khövsgöl, Terkhiin Tsagaan Nuur and Buir Nuur, and also scavenges at rubbish dumps and around herders’ camps.",
    f: ["Large, with a white head and pale grey back.", "Heavy yellow bill with a red spot near the tip.", "Pale eye with a red eye-ring.", "Pinkish legs.", "Black wingtips with white spots; immatures mottled brown."],
    si: "Pallas’s Gull — black hood, heavier banded bill. Lesser Black-backed (Heuglin’s) Gull — darker back, yellow legs. Common Gull — much smaller.",
    h: "Large lakes, rivers, steppe and rubbish dumps.",
    di: "All regions: Ögii Nuur, Khar Us Nuur, Khövsgöl, Terkhiin Tsagaan Nuur, Buir Nuur, Ulaanbaatar.",
    mi: "Summer visitor, March–October.",
    fo: "Fish, rodents, carrion, eggs and scraps.",
    br: "Colonial on lake islands; 2–3 eggs.",
    be: "An opportunist; steals food and scavenges.",
    v: "A loud, laughing ‘ha-ha-ha’.",
    cu: "Local fishermen see its colonies as a sign of rich fish stocks.",
    co: "Least Concern.",
    w: "Terkhiin Tsagaan Nuur and Khövsgöl in summer.",
    bt: "May–September",
    fa: ["Mongolia’s common large gull.", "Part of the herring gull complex.", "Has a red spot on its bill."]
  },
  "glaucous-gull": {
    T: { c: { white: 0.75, gray: 0.2, yellow: 0.05 }, hb: ["water"], bk: "gull", bh: ["swim", "soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["62–68 cm", "150–165 cm", "1–2.7 kg"] },
    s: "A huge, pale Arctic gull with pure white wingtips. A rare autumn vagrant to western Mongolia.",
    d: "The Glaucous Gull breeds around the Arctic and winters on northern coasts. It is a fearsome predator of seabird chicks. In Mongolia it has been recorded in October at Khar Us Nuur.",
    f: ["Very large and pale.", "Wingtips white — no black.", "Heavy yellow bill with a red spot.", "Immatures pale buff-white with a pink, black-tipped bill."],
    si: "Mongolian Gull — black wingtips.",
    h: "Arctic coasts; vagrants on large lakes.",
    di: "Rare vagrant; Khar Us Nuur.",
    mi: "Vagrant, October.",
    fo: "Fish, eggs, chicks and carrion.",
    br: "Nests on Arctic cliffs (not in Mongolia).",
    be: "Predator and scavenger.",
    v: "Deep, hoarse calls.",
    cu: "Its name ‘glaucous’ means blue-grey.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["No black in the wings.", "One of the largest gulls.", "Arctic predator."]
  }
});
