B2T("fr", {
  "black-legged-kittiwake": {
    name: "Mouette tridactyle",
    s: "Petite mouette océanique à l’air doux, aux extrémités d’ailes « trempées dans l’encre » et aux pattes noires. Erratique exceptionnelle en Mongolie, notée à Böön Tsagaan Nuur.",
    d: "La Mouette tridactyle est un véritable oiseau marin qui niche sur les falaises de l’Arctique et du Pacifique Nord et passe l’hiver au large. Elle a fortement décliné et est Vulnérable. Un oiseau à Böön Tsagaan Nuur en juillet 2023 constitue l’une des très rares mentions à l’intérieur de l’Asie centrale.",
    f: ["Tête blanche, dos et ailes gris.", "Extrémités des ailes entièrement noires, sans taches blanches.", "Courtes pattes noires.", "Bec jaune uni.", "Juvénile : « W » noir sur les ailes."],
    si: "Goéland cendré — pattes jaune verdâtre, taches blanches dans le noir des ailes.",
    h: "Haute mer et falaises côtières ; erratiques sur les grands lacs.",
    di: "Erratique exceptionnelle ; Böön Tsagaan Nuur.",
    mi: "Erratique.",
    fo: "Petits poissons et plancton.",
    br: "Niche sur d’étroites corniches de falaises marines (pas en Mongolie).",
    be: "Vol léger ; prélève sa nourriture en surface.",
    v: "Un « kitti-wa-aake » nasal aux colonies.",
    cu: "Son nom anglais imite son cri.",
    co: "Vulnérable.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Nommée d’après son cri.", "Passe l’hiver en mer.", "Vulnérable à l’échelle mondiale."]
  },
  "slender-billed-gull": {
    name: "Goéland railleur",
    s: "Mouette pâle au long front fuyant, au bec fin rouge sombre et souvent à la poitrine rosée. Visiteur rare des lacs mongols.",
    d: "Le Goéland railleur niche sur les lacs salés et lagunes, de la Méditerranée au Kazakhstan et au Pakistan. En Mongolie, c’est un visiteur rare en mai–juillet, noté au lac Ögii et à Böön Tsagaan.",
    f: ["Tête entièrement blanche en toute saison.", "Long cou et long front fuyant.", "Bec fin rouge sombre.", "Œil pâle.", "Dessous teinté de rose au printemps."],
    si: "Mouette rieuse — capuchon sombre en été, bec plus court, œil sombre.",
    h: "Lacs salés et lagunes saumâtres.",
    di: "Rare ; lac Ögii, Böön Tsagaan.",
    mi: "Visiteur rare, mai–juillet.",
    fo: "Petits poissons et insectes.",
    br: "Colonial sur des îlots (pas en Mongolie).",
    be: "Picore en surface en nageant.",
    v: "Plus grave que la Mouette rieuse.",
    cu: "Nommé pour son long bec fin.",
    co: "Préoccupation mineure.",
    w: "Examinez les groupes de mouettes au lac Ögii.",
    bt: "mai–juil.",
    fa: ["N’a jamais de capuchon sombre.", "Rosé au printemps.", "Vit sur les lacs salés."]
  },
  "brown-headed-gull": {
    name: "Mouette du Tibet",
    s: "Mouette du plateau tibétain et d’Asie centrale, à capuchon brun et yeux pâles. Visiteur d’été local sur les lacs du Gobi, surtout Böön Tsagaan.",
    d: "La Mouette du Tibet niche sur les lacs d’altitude du Tibet, du Qinghai, d’Asie centrale et du Gobi, et hiverne en Inde et en Asie du Sud-Est. En Mongolie, elle niche ou estive à Böön Tsagaan, au lac Orog et au lac Ögii.",
    f: ["Capuchon brun en été ; tête blanche avec tache auriculaire sombre en hiver.", "Œil jaune pâle (sombre chez la Mouette rieuse).", "Extrémités des ailes noires avec de grands « miroirs » blancs.", "Bec et pattes rouges.", "Plus grande que la Mouette rieuse."],
    si: "Mouette rieuse — plus petite, œil sombre, coin blanc sur l’aile externe sans grands miroirs.",
    h: "Lacs des déserts et des hauts plateaux.",
    di: "Lacs du Gobi (Böön Tsagaan, lac Orog, Taatsiin Tsagaan), lac Ögii.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Poissons, insectes et déchets.",
    br: "Colonial sur des îlots lacustres.",
    be: "Se mêle aux Mouettes rieuses et aux sternes.",
    v: "Cris rauques « guèk-guèk ».",
    cu: "C’est la mouette la plus commune du lac Qinghai et du Tibet.",
    co: "Préoccupation mineure.",
    w: "Böön Tsagaan Nuur en juin.",
    bt: "mai–juil.",
    fa: ["Niche jusqu’à 4 500 m au Tibet.", "Yeux pâles.", "Hiverne en Inde."]
  },
  "black-headed-gull": {
    name: "Mouette rieuse",
    s: "Petite mouette bruyante au capuchon chocolat en été et au coin blanc à l’avant de l’aile. La mouette la plus commune de Mongolie.",
    d: "La Mouette rieuse niche en Europe et en Asie. Son capuchon estival est brun chocolat et non noir. En Mongolie, elle niche en grandes colonies sur les îlots et marais des lacs de tout le pays, en particulier aux lacs Ögii, Khar Us, Böön Tsagaan, Buir et Orog, d’avril à octobre.",
    f: ["Capuchon brun chocolat en été ; tête blanche avec tache auriculaire sombre en hiver.", "Bec et pattes rouge sombre.", "Bord d’attaque blanc sur l’aile externe.", "Dos gris.", "Œil sombre avec un fin cercle blanc."],
    si: "Mouette du Tibet — plus grande, œil pâle, grands miroirs blancs. Mouette pygmée — plus petite, capuchon noir, dessous des ailes sombre.",
    h: "Lacs, marais et rivières ; aussi villes et champs.",
    di: "Toutes les régions : lac Ögii, lac Khar Us, Böön Tsagaan, lac Buir, lac Orog, Oulan-Bator.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Insectes, vers, petits poissons et déchets.",
    br: "Colonial sur îlots ou végétation flottante ; 2 ou 3 œufs.",
    be: "Suit les charrues et les pêcheurs ; très bruyante aux colonies.",
    v: "Un « kriè-ar » rauque et rieur.",
    cu: "Ses colonies protègent d’autres oiseaux d’eau nicheurs comme les grèbes.",
    co: "Préoccupation mineure.",
    w: "Colonies du lac Ögii en juin.",
    bt: "mai–août",
    fa: ["Sa tête « noire » est en fait brune.", "Perd son capuchon en hiver.", "La mouette la plus commune de Mongolie."]
  },
  "little-gull": {
    name: "Mouette pygmée",
    s: "La plus petite mouette du monde, à capuchon noir et dessous des ailes gris sombre. Migratrice peu commune et nicheuse locale sur les lacs mongols.",
    d: "La Mouette pygmée niche sur les lacs marécageux, de la Baltique à la Sibérie orientale. Elle vole légèrement comme une sterne, cueillant les insectes à la surface. En Mongolie, c’est une migratrice peu commune et une estivante locale au lac Ögii, au lac Orog, à Böön Tsagaan et dans le Dornod.",
    f: ["Minuscule, capuchon noir de jais en été.", "Dessous des ailes gris sombre à noirâtre ; extrémités blanches arrondies.", "Courtes pattes rouges et bec sombre.", "Vol de sterne.", "Juvénile avec un « W » sombre sur les ailes."],
    si: "Mouette rieuse — plus grande, capuchon brun, dessous d’aile pâle. Guifette leucoptère — corps noir en été, queue fourchue.",
    h: "Lacs marécageux à végétation.",
    di: "Lac Ögii, lac Orog, Böön Tsagaan, lac Khar Us, lac Buir.",
    mi: "Migratrice et visiteuse d’été, mai–septembre.",
    fo: "Insectes cueillis en surface.",
    br: "Niche dans les marais, souvent avec les sternes ; 2 ou 3 œufs.",
    be: "Plonge vers l’eau comme une guifette.",
    v: "Un « kèk-kèk » court et nasal.",
    cu: "La plus petite mouette du monde.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai, août",
    fa: ["Plus petite mouette du monde.", "Dessous des ailes sombre.", "Vole comme une sterne."]
  },
  "rosss-gull": {
    name: "Mouette rosée",
    s: "Rare et superbe mouette arctique au corps rose, fin collier noir et queue cunéiforme. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "La Mouette rosée niche dans l’Arctique sibérien et hiverne en bordure de la banquise. Elle fut l’un des oiseaux les plus recherchés par les explorateurs. Toute observation en Mongolie serait exceptionnelle.",
    f: ["Dessous teinté de rose en été.", "Fin collier noir.", "Queue cunéiforme.", "Petit bec noir et pattes rouges.", "Dessous des ailes gris."],
    si: "Mouette pygmée — capuchon noir, queue carrée.",
    h: "Toundra et banquise arctiques.",
    di: "Erratique exceptionnelle.",
    mi: "Erratique.",
    fo: "Insectes et petits animaux marins.",
    br: "Niche dans l’Arctique sibérien (pas en Mongolie).",
    be: "Vol de sterne.",
    v: "Cris mélodieux, rappelant les sternes.",
    cu: "Nommée d’après l’explorateur polaire James Clark Ross.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Corps rose.", "Porte le nom d’un explorateur polaire.", "Hiverne au bord de la banquise."]
  },
  "pallass-gull": {
    name: "Goéland ichthyaète",
    s: "Énorme goéland à capuchon noir, croissants blancs autour de l’œil et bec jaune massif barré de noir et de rouge. Visiteur d’été des grands lacs de l’ouest et du Gobi.",
    d: "Le Goéland ichthyaète niche sur les îlots des grands lacs, de la mer Noire à la Mongolie et à l’ouest de la Chine, et hiverne autour de la mer d’Arabie et en Inde. C’est le seul grand goéland à capuchon noir. En Mongolie, il niche en colonies aux lacs Khar Us, Ögii, Böön Tsagaan, Orog et Achit.",
    f: ["Très grand, capuchon noir en été et croissants blancs au-dessus et au-dessous de l’œil.", "Bec jaune massif à bande noire et rouge près de l’extrémité.", "Dos gris pâle ; extrémités des ailes noires et blanches.", "Long front fuyant.", "Pattes jaunes."],
    si: "Mouette rieuse — bien plus petite, capuchon brun. Goéland mongol — tête blanche.",
    h: "Grands lacs avec îlots.",
    di: "Lac Khar Us, lac Ögii, Böön Tsagaan, lac Orog, lac Achit, lacs du Bayan-Ölgii.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Poissons ; aussi rongeurs et insectes.",
    br: "Colonial sur des îlots ; 2 ou 3 œufs ; l’un des goélands nichant le plus tôt.",
    be: "Pêche en plongeant et en saisissant les proies.",
    v: "Un « kraa-a » grave, de corbeau.",
    cu: "Nommé d’après Peter Simon Pallas, explorateur de la Mongolie et de la Sibérie.",
    co: "Préoccupation mineure.",
    w: "Böön Tsagaan et lac Khar Us en juin.",
    bt: "mai–août",
    fa: ["Le seul grand goéland à capuchon noir.", "Nommé d’après Pallas.", "Niche sur les îlots des lacs."]
  },
  "black-tailed-gull": {
    name: "Goéland à queue noire",
    s: "Goéland côtier d’Asie orientale de taille moyenne, à large bande noire sur la queue et pointe du bec rouge et noire. Inscrit pour la Mongolie, sans mention GBIF.",
    d: "Le Goéland à queue noire niche sur les côtes du Japon, de Corée, de l’est de la Chine et de l’Extrême-Orient russe. Il s’aventure rarement à l’intérieur des terres ; en Mongolie, c’est un erratique exceptionnel.",
    f: ["Queue blanche à large bande noire.", "Dos gris foncé.", "Bec jaune à pointe rouge et noire.", "Pattes jaunes."],
    si: "Goéland cendré — pas de bande noire sur la queue.",
    h: "Côtes et ports.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Poissons et déchets.",
    br: "Colonial sur les falaises marines (pas en Mongolie).",
    be: "Suit les bateaux de pêche.",
    v: "Un miaulement de chat, d’où son nom japonais de « chat de mer ».",
    cu: "Son île de nidification au Japon, Kabushima, est un monument national.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Appelé « chat de mer » en japonais.", "Bande noire sur la queue.", "Espèce côtière."]
  },
  "mew-gull": {
    name: "Goéland cendré",
    s: "Goéland moyen à l’air doux, au bec fin et aux pattes jaune verdâtre. Visiteur d’été et migrateur, surtout dans le nord et l’est de la Mongolie.",
    d: "Le Goéland cendré niche dans tout le nord de l’Eurasie ; la forme orientale kamtschatschensis est plus grande. En Mongolie, il niche sur les lacs et rivières du nord et de l’est (lac Buir, lac Ögii, Khurkh) et passe dans toutes les régions.",
    f: ["Tête blanche arrondie et œil sombre — expression douce.", "Bec fin jaune verdâtre uni.", "Pattes jaune verdâtre.", "Dos gris, extrémités des ailes noires tachées de blanc.", "Hiver : tête striée de gris."],
    si: "Goéland mongol — bien plus grand, bec massif à tache rouge. Mouette tridactyle — pattes noires, extrémités entièrement noires.",
    h: "Lacs, rivières et steppe.",
    di: "Lac Buir, lac Ögii, Böön Tsagaan, Oulan-Bator, lac Khar Us, Khurkh.",
    mi: "Visiteur d’été et migrateur, avril–octobre.",
    fo: "Insectes, vers, poissons et petits rongeurs.",
    br: "Niche sur des îlots, des souches ou des rives ; 2 ou 3 œufs.",
    be: "Se nourrit dans les champs et la steppe autant que sur l’eau.",
    v: "Un « kii-ya » aigu et miaulé.",
    cu: "Son nom américain, « Mew Gull », vient de son cri de chat.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en été.",
    bt: "mai–sept.",
    fa: ["Expression douce.", "Mange des vers dans les champs.", "Miaule comme un chat."]
  },
  "lesser-black-backed-gull": {
    name: "Goéland brun",
    s: "Grand goéland au dos gris foncé et aux pattes jaunes ; la forme sibérienne (Goéland de Heuglin) traverse la Mongolie. Migrateur peu commun.",
    d: "Le complexe du Goéland brun comprend le Goéland de Heuglin (sous-espèce heuglini), qui niche dans la toundra sibérienne et hiverne au Moyen-Orient et en Inde. Il traverse la Mongolie en petit nombre en mai et en août–octobre.",
    f: ["Dos gris ardoise, plus sombre que le Goéland mongol.", "Pattes jaunes.", "Bec jaune à tache rouge.", "Tête blanche en été.", "Longues ailes."],
    si: "Goéland mongol — dos gris plus pâle, pattes rosées.",
    h: "Lacs et rivières en migration.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Khar Us.",
    mi: "Migrateur, mai et août–octobre.",
    fo: "Poissons, déchets, insectes.",
    br: "Niche dans la toundra sibérienne (pas en Mongolie).",
    be: "Se repose avec d’autres goélands sur les rives.",
    v: "Un « kiaou » grave.",
    cu: "L’identification des goélands est un défi favori des ornithologues.",
    co: "Préoccupation mineure.",
    w: "Examinez les grands goélands en automne.",
    bt: "mai, sept.",
    fa: ["Dos plus sombre que la plupart des goélands.", "La forme sibérienne traverse la Mongolie.", "Pattes jaunes."]
  },
  "american-herring-gull": {
    name: "Goéland mongol",
    s: "Grand goéland gris pâle à tête blanche, œil pâle et tache rouge au bec — le grand goéland des lacs mongols. Il appartient au groupe des goélands argentés (ici le Goéland mongol).",
    d: "Les grands « goélands argentés » forment un complexe de formes très proches. En Mongolie, le nicheur est le Goéland mongol (Larus vegae mongolicus, parfois traité comme espèce à part), qui niche sur les îlots des lacs de tout le pays et hiverne en Corée et dans l’est de la Chine. Il est commun aux lacs Ögii, Khar Us, Khövsgöl, Terkhiin Tsagaan et Buir, et fouille aussi les décharges et les campements d’éleveurs.",
    f: ["Grand, tête blanche et dos gris pâle.", "Bec jaune massif à tache rouge près de l’extrémité.", "Œil pâle cerclé de rouge.", "Pattes rosées.", "Extrémités des ailes noires tachées de blanc ; immatures bruns mouchetés."],
    si: "Goéland ichthyaète — capuchon noir, bec plus massif barré. Goéland brun (de Heuglin) — dos plus sombre, pattes jaunes. Goéland cendré — bien plus petit.",
    h: "Grands lacs, rivières, steppe et décharges.",
    di: "Toutes les régions : lac Ögii, lac Khar Us, Khövsgöl, Terkhiin Tsagaan Nuur, lac Buir, Oulan-Bator.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Poissons, rongeurs, charognes, œufs et déchets.",
    br: "Colonial sur les îlots des lacs ; 2 ou 3 œufs.",
    be: "Opportuniste ; vole la nourriture et charogne.",
    v: "Un « ha-ha-ha » fort et rieur.",
    cu: "Les pêcheurs locaux voient ses colonies comme le signe d’eaux poissonneuses.",
    co: "Préoccupation mineure.",
    w: "Terkhiin Tsagaan Nuur et Khövsgöl en été.",
    bt: "mai–sept.",
    fa: ["Le grand goéland commun de Mongolie.", "Fait partie du complexe des goélands argentés.", "Tache rouge sur le bec."]
  },
  "glaucous-gull": {
    name: "Goéland bourgmestre",
    s: "Énorme goéland arctique pâle aux extrémités d’ailes blanc pur. Erratique automnal rare dans l’ouest de la Mongolie.",
    d: "Le Goéland bourgmestre niche autour de l’Arctique et hiverne sur les côtes nordiques. C’est un redoutable prédateur de poussins d’oiseaux marins. En Mongolie, il a été noté en octobre au lac Khar Us.",
    f: ["Très grand et pâle.", "Extrémités des ailes blanches — sans noir.", "Bec jaune massif à tache rouge.", "Immatures blanc chamois pâle, bec rose à pointe noire."],
    si: "Goéland mongol — extrémités des ailes noires.",
    h: "Côtes arctiques ; erratiques sur les grands lacs.",
    di: "Erratique rare ; lac Khar Us.",
    mi: "Erratique, octobre.",
    fo: "Poissons, œufs, poussins et charognes.",
    br: "Niche sur les falaises arctiques (pas en Mongolie).",
    be: "Prédateur et charognard.",
    v: "Cris graves et rauques.",
    cu: "Son nom évoque les bourgmestres, par son allure imposante.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Aucun noir sur les ailes.", "L’un des plus grands goélands.", "Prédateur arctique."]
  }
});
