B2T("en", {
  "little-tern": {
    T: { c: { white: 0.6, gray: 0.25, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "long", bh: ["soar", "swim"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["21–25 cm", "41–47 cm", "47–63 g"] },
    s: "A tiny, fast-flapping tern with a white forehead, black cap and yellow black-tipped bill. Breeds on sandy and pebbly lake shores.",
    d: "The Little Tern breeds across Europe, Asia and Africa on beaches and river bars. It hovers rapidly before plunging for tiny fish. In Mongolia it nests on bare shores of lakes in the west, Gobi and east — Böön Tsagaan, Buir Nuur, Khar Us Nuur and Orog Nuur.",
    f: ["Very small tern.", "Black cap with a white forehead.", "Yellow bill with a black tip.", "Orange-yellow legs.", "Hovers with fast wingbeats before diving."],
    si: "Common Tern — larger, red bill, no white forehead.",
    h: "Sandy or gravel shores of lakes and rivers.",
    di: "Böön Tsagaan, Buir Nuur, Khar Us Nuur, Orog Nuur, Ögii Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Tiny fish and shrimps.",
    br: "Nests in a scrape on bare shingle; 2–3 eggs.",
    be: "Hovers and plunges; noisy near nests.",
    v: "Sharp, chattering ‘kirrik’.",
    cu: "Its nests on open beaches are easily disturbed by people and vehicles.",
    co: "Least Concern.",
    w: "Böön Tsagaan shore in June; keep away from nests.",
    bt: "June–July",
    fa: ["Smallest tern in Mongolia.", "Has a white forehead.", "Nests on bare shingle."]
  },
  "gull-billed-tern": {
    T: { c: { white: 0.6, gray: 0.25, black: 0.15 }, hb: ["water", "steppe"], bk: "gull", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["35–42 cm", "85–103 cm", "150–300 g"] },
    s: "A pale tern with a thick, black, gull-like bill and black cap, which hunts insects over land. A summer visitor to lakes across Mongolia.",
    d: "The Gull-billed Tern breeds on every continent except Antarctica. Unlike most terns, it seldom dives, instead catching insects, lizards and frogs over marshes and steppe. In Mongolia it breeds on islands and shores at Ögii Nuur, Orog Nuur, Buir Nuur and Böön Tsagaan.",
    f: ["Pale grey back, white underparts.", "Black cap in summer.", "Short, thick black bill.", "Long black legs.", "Shallowly forked tail."],
    si: "Common Tern — red bill, deeper-forked tail, dives for fish. Caspian Tern — much larger, red bill.",
    h: "Lakes and marshes with nearby steppe.",
    di: "Ögii Nuur, Orog Nuur, Buir Nuur, Böön Tsagaan, Khar Us Nuur, Mongol Daguur.",
    mi: "Summer visitor, May–August.",
    fo: "Large insects, lizards, frogs and small rodents.",
    br: "Colonial on islands; 2–3 eggs.",
    be: "Hawks insects in the air; picks prey from the ground.",
    v: "A nasal ‘ger-vik’.",
    cu: "Its name comes from its gull-like bill.",
    co: "Least Concern.",
    w: "Orog Nuur and Buir Nuur in June.",
    bt: "May–July",
    fa: ["Hunts insects over land.", "Thick black bill.", "Found on six continents."]
  },
  "caspian-tern": {
    T: { c: { white: 0.55, gray: 0.25, black: 0.1, red: 0.1 }, hb: ["water"], bk: "long", bh: ["soar", "swim"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["48–56 cm", "127–145 cm", "0.5–0.8 kg"] },
    s: "The largest tern in the world, gull-sized, with a massive red bill and black cap. Breeds on islands in large lakes in western and eastern Mongolia.",
    d: "The Caspian Tern is found on all continents except South America and Antarctica. It plunges for fish with its dagger-like red bill. In Mongolia it nests on islands at Böön Tsagaan, Ögii Nuur, Khar Us Nuur, Buir Nuur and Uvs Nuur.",
    f: ["Very large tern — as big as a gull.", "Huge coral-red bill with a dark tip.", "Black cap.", "Dark undersides to the primaries.", "Heavy, gull-like flight."],
    si: "Pallas’s Gull — heavier, black hood, yellow bill. Common Tern — much smaller.",
    h: "Large lakes with islands.",
    di: "Böön Tsagaan, Ögii Nuur, Khar Us Nuur, Buir Nuur, Orog Nuur, Uvs Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Fish.",
    br: "Colonial on islands; 2–3 eggs.",
    be: "Patrols high over water, then plunges.",
    v: "A deep, heron-like ‘kraa-ah’.",
    cu: "Named after the Caspian Sea, where it was first described.",
    co: "Least Concern.",
    w: "Böön Tsagaan Nuur in June.",
    bt: "May–August",
    fa: ["World’s largest tern.", "Bright red bill.", "Nests on lake islands."]
  },
  "whiskered-tern": {
    T: { c: { gray: 0.5, white: 0.3, black: 0.15, red: 0.05 }, hb: ["water"], bk: "long", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["23–29 cm", "64–70 cm", "80–100 g"] },
    s: "A marsh tern with a black cap, white cheeks and dark grey underparts in summer. Nests on floating vegetation in marshy lakes.",
    d: "The Whiskered Tern breeds in Europe, Asia, Africa and Australia. It builds floating nests among water lilies and weeds. In Mongolia it breeds at Ögii Nuur, Böön Tsagaan, Buir Nuur, Orog Nuur and marshes near Ulaanbaatar.",
    f: ["Black cap and white ‘whiskered’ cheeks.", "Dark grey breast and belly in summer.", "Dark red bill and legs.", "Short, shallowly forked tail.", "Dips to the water rather than diving."],
    si: "White-winged Tern — black body with white wings. Common Tern — white below, longer tail.",
    h: "Marshy lakes with floating plants.",
    di: "Ögii Nuur, Böön Tsagaan, Buir Nuur, Orog Nuur, Khar Us Nuur, Ulaanbaatar.",
    mi: "Summer visitor, May–August.",
    fo: "Insects, small fish and tadpoles.",
    br: "Colonial; floating nest; 2–3 eggs.",
    be: "Flies low over water, dipping to pick food.",
    v: "Harsh ‘krerk’.",
    cu: "Its name comes from the white stripe below its cap.",
    co: "Least Concern.",
    w: "Ögii Nuur in June.",
    bt: "June–July",
    fa: ["Builds floating nests.", "White cheeks look like whiskers.", "A marsh tern."]
  },
  "white-winged-tern": {
    T: { c: { black: 0.55, white: 0.3, gray: 0.1, red: 0.05 }, hb: ["water"], bk: "long", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["20–27 cm", "50–56 cm", "50–80 g"] },
    s: "A striking marsh tern: black body with white wings and tail in summer. One of the most common terns in Mongolia’s wetlands.",
    d: "The White-winged Tern breeds from eastern Europe to eastern Asia and winters in Africa, Asia and Australia. It feeds on insects over marshes. In Mongolia it breeds abundantly at Ögii Nuur, the Khurkh valley, Böön Tsagaan, Khar Us Nuur and Orog Nuur.",
    f: ["Breeding: jet-black head, body and underwing coverts.", "White upperwing forewing, rump and tail.", "Red legs.", "Short black bill.", "Buoyant, fluttering flight."],
    si: "Black Tern — grey wings and tail, dark underwing pale. Whiskered Tern — grey body, white cheeks.",
    h: "Marshes, flooded meadows and shallow lakes.",
    di: "Ögii Nuur, Khurkh, Böön Tsagaan, Khar Us Nuur, Orog Nuur, Buir Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Insects, especially dragonflies and midges.",
    br: "Colonial; floating or mound nests; 2–3 eggs.",
    be: "Hawks insects in the air.",
    v: "Rough ‘kesch’.",
    cu: "Its elegant black-and-white pattern makes it a favourite of photographers.",
    co: "Least Concern.",
    w: "Khurkh valley and Ögii Nuur in June.",
    bt: "June–July",
    fa: ["Black body, white wings.", "Very common in Mongolia.", "Eats insects in flight."]
  },
  "black-tern": {
    T: { c: { black: 0.45, gray: 0.4, white: 0.15 }, hb: ["water"], bk: "long", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["22–26 cm", "57–65 cm", "60–86 g"] },
    s: "A small marsh tern with a black head and body and soft grey wings. A summer visitor to lakes, especially in the Khangai.",
    d: "The Black Tern breeds in marshes across Europe, western Asia and North America. In Mongolia it breeds at Ögii Nuur, Böön Tsagaan, Khar Us Nuur and Orog Nuur, often with White-winged Terns.",
    f: ["Black head and body in summer.", "Grey wings, rump and tail.", "Pale grey underwing.", "White undertail.", "Black bill."],
    si: "White-winged Tern — white wings and tail, black underwing coverts.",
    h: "Marshy lakes.",
    di: "Ögii Nuur, Böön Tsagaan, Khar Us Nuur, Orog Nuur, Ulaanbaatar, Buir Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Insects and small fish.",
    br: "Floating nests in colonies; 2–3 eggs.",
    be: "Dips to the surface in flight.",
    v: "Squeaky ‘kik’.",
    cu: "Declined in Europe with the loss of marshes.",
    co: "Least Concern.",
    w: "Ögii Nuur in June.",
    bt: "June",
    fa: ["Grey wings.", "Nests on floating plants.", "Often with White-winged Terns."]
  },
  "common-tern": {
    T: { c: { white: 0.55, gray: 0.3, black: 0.1, red: 0.05 }, hb: ["water"], bk: "long", bh: ["soar", "swim"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["31–35 cm", "77–98 cm", "110–145 g"] },
    s: "An elegant white tern with a black cap, red bill and long forked tail. The most common tern in Mongolia, nesting on lakes and rivers.",
    d: "The Common Tern breeds across the Northern Hemisphere. In Mongolia the eastern subspecies longipennis (with a black bill) and western forms meet. It nests on islands and gravel bars and fishes by plunge-diving. Very common at Ögii Nuur, the Tuul River in Ulaanbaatar, the Khurkh valley and Khar Us Nuur.",
    f: ["Black cap, pale grey back, white underparts.", "Red bill (black in the eastern form).", "Long, deeply forked tail.", "Red or dark legs.", "Hovers then plunges."],
    si: "Little Tern — smaller, white forehead, yellow bill. Gull-billed Tern — thick black bill, hunts over land.",
    h: "Lakes, rivers and gravel islands.",
    di: "All regions: Ögii Nuur, Ulaanbaatar (Tuul River), Khurkh, Khar Us Nuur, Böön Tsagaan, Buir Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Small fish and insects.",
    br: "Colonial on islands and bars; 2–3 eggs.",
    be: "Plunge-dives; fiercely attacks intruders at the colony.",
    v: "Harsh ‘kee-yah’.",
    cu: "Called the ‘sea swallow’ for its forked tail.",
    co: "Least Concern.",
    w: "Tuul River in Ulaanbaatar in summer.",
    bt: "June–August",
    fa: ["Mongolia’s commonest tern.", "Dives for fish.", "Defends its nest fiercely."]
  },
  "arctic-skua": {
    T: { c: { brown: 0.5, white: 0.25, buff: 0.15, black: 0.1 }, hb: ["water"], bk: "hooked", bh: ["soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["41–46 cm", "110–125 cm", "380–600 g"] },
    s: "A dark, falcon-like seabird that chases gulls and terns to steal their food. On the Mongolian list, with no GBIF records.",
    d: "The Arctic Skua (Parasitic Jaeger) breeds on the Arctic tundra and winters at sea in the Southern Hemisphere. Some cross continents overland on migration. Mongolian records are exceptional.",
    f: ["Pointed central tail feathers.", "Pale and dark forms.", "White flashes at the base of the primaries.", "Falcon-like, agile flight."],
    si: "Pomarine Skua — larger, with blunt, twisted tail feathers.",
    h: "Tundra and open sea.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Fish stolen from other birds; also lemmings and eggs.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Pirates food from terns and gulls.",
    v: "Wailing calls on breeding grounds.",
    cu: "Its scientific name parasiticus refers to its food-stealing habit.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Steals food from other birds.", "Has pale and dark forms.", "Migrates to the southern oceans."]
  },
  "pomarine-skua": {
    T: { c: { brown: 0.5, white: 0.25, black: 0.15, buff: 0.1 }, hb: ["water"], bk: "hooked", bh: ["soar"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["46–51 cm", "125–138 cm", "550–850 g"] },
    s: "A bulky Arctic skua; adults have spoon-shaped, twisted central tail feathers. On the Mongolian list, with no GBIF records.",
    d: "The Pomarine Skua breeds on the high Arctic tundra where it depends on lemmings, and winters in tropical seas. Records in Mongolia are exceptional.",
    f: ["Heavy build with a barrel chest.", "Blunt, twisted ‘spoon’ tail feathers in adults.", "Pale and dark forms.", "Dark breast band in pale birds."],
    si: "Arctic Skua — slimmer, with pointed tail feathers.",
    h: "Tundra and open sea.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Lemmings in summer; fish stolen from seabirds at sea.",
    br: "Nests on high Arctic tundra (not in Mongolia).",
    be: "Chases gulls to make them drop food.",
    v: "Harsh calls on breeding grounds.",
    cu: "Its name refers to the ‘lid’ shape of its tail feathers.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Spoon-shaped tail feathers.", "Depends on lemmings.", "Winters in tropical seas."]
  }
});
