B2T("fr", {
  "little-tern": {
    name: "Sterne naine",
    s: "Minuscule sterne aux battements rapides, à front blanc, calotte noire et bec jaune à pointe noire. Niche sur les rives sableuses et caillouteuses des lacs.",
    d: "La Sterne naine niche en Europe, en Asie et en Afrique sur les plages et bancs de rivière. Elle fait un surplace rapide avant de plonger sur de minuscules poissons. En Mongolie, elle niche sur les rives dénudées des lacs de l’ouest, du Gobi et de l’est — Böön Tsagaan, lacs Buir, Khar Us et Orog.",
    f: ["Très petite sterne.", "Calotte noire à front blanc.", "Bec jaune à pointe noire.", "Pattes jaune orangé.", "Surplace rapide avant de plonger."],
    si: "Sterne pierregarin — plus grande, bec rouge, sans front blanc.",
    h: "Rives sableuses ou caillouteuses de lacs et rivières.",
    di: "Böön Tsagaan, lac Buir, lac Khar Us, lac Orog, lac Ögii.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Minuscules poissons et crevettes.",
    br: "Ponte dans une cuvette sur les galets ; 2 ou 3 œufs.",
    be: "Fait du surplace et plonge ; bruyante près du nid.",
    v: "Un « kirrik » sec et jacassant.",
    cu: "Ses nids sur les plages sont facilement détruits par les personnes et les véhicules.",
    co: "Préoccupation mineure.",
    w: "Rive de Böön Tsagaan en juin ; restez loin des nids.",
    bt: "juin–juil.",
    fa: ["La plus petite sterne de Mongolie.", "Front blanc.", "Niche sur les galets nus."]
  },
  "gull-billed-tern": {
    name: "Sterne hansel",
    s: "Sterne pâle au bec noir épais de goéland et à calotte noire, qui chasse les insectes au-dessus des terres. Visiteuse d’été des lacs de toute la Mongolie.",
    d: "La Sterne hansel niche sur tous les continents sauf l’Antarctique. Contrairement à la plupart des sternes, elle plonge rarement et capture insectes, lézards et grenouilles au-dessus des marais et de la steppe. En Mongolie, elle niche sur les îlots et rives des lacs Ögii, Orog, Buir et à Böön Tsagaan.",
    f: ["Dos gris pâle, dessous blanc.", "Calotte noire en été.", "Bec noir court et épais.", "Longues pattes noires.", "Queue peu fourchue."],
    si: "Sterne pierregarin — bec rouge, queue plus fourchue, plonge pour pêcher. Sterne caspienne — bien plus grande, bec rouge.",
    h: "Lacs et marais proches de la steppe.",
    di: "Lac Ögii, lac Orog, lac Buir, Böön Tsagaan, lac Khar Us, Mongol Daguur.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Gros insectes, lézards, grenouilles et petits rongeurs.",
    br: "Coloniale sur des îlots ; 2 ou 3 œufs.",
    be: "Chasse les insectes en vol ; cueille ses proies au sol.",
    v: "Un « guer-vik » nasal.",
    cu: "Son nom anglais évoque son bec de goéland.",
    co: "Préoccupation mineure.",
    w: "Lacs Orog et Buir en juin.",
    bt: "mai–juil.",
    fa: ["Chasse les insectes au-dessus des terres.", "Bec noir épais.", "Présente sur six continents."]
  },
  "caspian-tern": {
    name: "Sterne caspienne",
    s: "La plus grande sterne du monde, de la taille d’un goéland, au bec rouge massif et à calotte noire. Niche sur les îlots des grands lacs de l’ouest et de l’est de la Mongolie.",
    d: "La Sterne caspienne est présente sur tous les continents sauf l’Amérique du Sud et l’Antarctique. Elle plonge sur les poissons avec son bec rouge en poignard. En Mongolie, elle niche sur les îlots de Böön Tsagaan, des lacs Ögii, Khar Us, Buir et Uvs.",
    f: ["Très grande sterne — de la taille d’un goéland.", "Énorme bec rouge corail à pointe sombre.", "Calotte noire.", "Dessous des primaires sombre.", "Vol lourd de goéland."],
    si: "Goéland ichthyaète — plus lourd, capuchon noir, bec jaune. Sterne pierregarin — bien plus petite.",
    h: "Grands lacs avec îlots.",
    di: "Böön Tsagaan, lac Ögii, lac Khar Us, lac Buir, lac Orog, lac Uvs.",
    mi: "Visiteuse d’été, avril–octobre.",
    fo: "Poissons.",
    br: "Coloniale sur des îlots ; 2 ou 3 œufs.",
    be: "Patrouille haut au-dessus de l’eau puis plonge.",
    v: "Un « kraa-a » grave, de héron.",
    cu: "Nommée d’après la mer Caspienne, où elle fut décrite.",
    co: "Préoccupation mineure.",
    w: "Böön Tsagaan Nuur en juin.",
    bt: "mai–août",
    fa: ["Plus grande sterne du monde.", "Bec rouge vif.", "Niche sur les îlots des lacs."]
  },
  "whiskered-tern": {
    name: "Guifette moustac",
    s: "Guifette à calotte noire, joues blanches et dessous gris foncé en été. Niche sur la végétation flottante des lacs marécageux.",
    d: "La Guifette moustac niche en Europe, en Asie, en Afrique et en Australie. Elle construit des nids flottants parmi les nénuphars et les herbiers. En Mongolie, elle niche au lac Ögii, à Böön Tsagaan, aux lacs Buir et Orog et dans les marais près d’Oulan-Bator.",
    f: ["Calotte noire et joues blanches « moustachues ».", "Poitrine et ventre gris foncé en été.", "Bec et pattes rouge sombre.", "Queue courte peu fourchue.", "Effleure l’eau plutôt que de plonger."],
    si: "Guifette leucoptère — corps noir, ailes blanches. Sterne pierregarin — blanche dessous, queue plus longue.",
    h: "Lacs marécageux à plantes flottantes.",
    di: "Lac Ögii, Böön Tsagaan, lac Buir, lac Orog, lac Khar Us, Oulan-Bator.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes, petits poissons et têtards.",
    br: "Coloniale ; nid flottant ; 2 ou 3 œufs.",
    be: "Vole bas en cueillant sa nourriture à la surface.",
    v: "Un « krèrk » rauque.",
    cu: "Son nom vient de la bande blanche sous sa calotte.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en juin.",
    bt: "juin–juil.",
    fa: ["Construit des nids flottants.", "Joues blanches en « moustaches ».", "Une guifette de marais."]
  },
  "white-winged-tern": {
    name: "Guifette leucoptère",
    s: "Guifette spectaculaire : corps noir aux ailes et queue blanches en été. L’une des sternes les plus communes des zones humides mongoles.",
    d: "La Guifette leucoptère niche de l’Europe de l’Est à l’Asie orientale et hiverne en Afrique, en Asie et en Australie. Elle chasse les insectes au-dessus des marais. En Mongolie, elle niche en abondance au lac Ögii, dans la vallée de Khurkh, à Böön Tsagaan et aux lacs Khar Us et Orog.",
    f: ["Nuptiale : tête, corps et couvertures sous-alaires noir de jais.", "Avant de l’aile, croupion et queue blancs.", "Pattes rouges.", "Bec noir court.", "Vol léger et voletant."],
    si: "Guifette noire — ailes et queue grises. Guifette moustac — corps gris, joues blanches.",
    h: "Marais, prairies inondées et lacs peu profonds.",
    di: "Lac Ögii, Khurkh, Böön Tsagaan, lac Khar Us, lac Orog, lac Buir.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes, surtout libellules et moucherons.",
    br: "Coloniale ; nids flottants ou en monticule ; 2 ou 3 œufs.",
    be: "Chasse les insectes en vol.",
    v: "Un « kèch » rauque.",
    cu: "Son élégant motif noir et blanc en fait la favorite des photographes.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh et lac Ögii en juin.",
    bt: "juin–juil.",
    fa: ["Corps noir, ailes blanches.", "Très commune en Mongolie.", "Mange les insectes en vol."]
  },
  "black-tern": {
    name: "Guifette noire",
    s: "Petite guifette à tête et corps noirs et ailes gris doux. Visiteuse d’été des lacs, surtout dans le Khangaï.",
    d: "La Guifette noire niche dans les marais d’Europe, d’Asie occidentale et d’Amérique du Nord. En Mongolie, elle niche au lac Ögii, à Böön Tsagaan, aux lacs Khar Us et Orog, souvent avec la Guifette leucoptère.",
    f: ["Tête et corps noirs en été.", "Ailes, croupion et queue gris.", "Dessous des ailes gris pâle.", "Sous-caudales blanches.", "Bec noir."],
    si: "Guifette leucoptère — ailes et queue blanches, couvertures sous-alaires noires.",
    h: "Lacs marécageux.",
    di: "Lac Ögii, Böön Tsagaan, lac Khar Us, lac Orog, Oulan-Bator, lac Buir.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes et petits poissons.",
    br: "Nids flottants en colonies ; 2 ou 3 œufs.",
    be: "Effleure la surface en vol.",
    v: "Un « kik » grinçant.",
    cu: "A décliné en Europe avec la disparition des marais.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en juin.",
    bt: "juin",
    fa: ["Ailes grises.", "Niche sur les plantes flottantes.", "Souvent avec la Guifette leucoptère."]
  },
  "common-tern": {
    name: "Sterne pierregarin",
    s: "Élégante sterne blanche à calotte noire, bec rouge et longue queue fourchue. La sterne la plus commune de Mongolie, nichant sur les lacs et rivières.",
    d: "La Sterne pierregarin niche dans tout l’hémisphère Nord. En Mongolie se rencontrent la sous-espèce orientale longipennis (à bec noir) et des formes occidentales. Elle niche sur les îlots et bancs de graviers et pêche en plongeant. Très commune au lac Ögii, sur la Tuul à Oulan-Bator, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Calotte noire, dos gris pâle, dessous blanc.", "Bec rouge (noir chez la forme orientale).", "Longue queue profondément fourchue.", "Pattes rouges ou sombres.", "Fait du surplace puis plonge."],
    si: "Sterne naine — plus petite, front blanc, bec jaune. Sterne hansel — bec noir épais, chasse au-dessus des terres.",
    h: "Lacs, rivières et îlots de graviers.",
    di: "Toutes les régions : lac Ögii, Oulan-Bator (Tuul), Khurkh, lac Khar Us, Böön Tsagaan, lac Buir.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Petits poissons et insectes.",
    br: "Coloniale sur îlots et bancs ; 2 ou 3 œufs.",
    be: "Plonge ; attaque vivement les intrus à la colonie.",
    v: "Un « kii-ya » rauque.",
    cu: "Surnommée « hirondelle de mer » pour sa queue fourchue.",
    co: "Préoccupation mineure.",
    w: "Rivière Tuul à Oulan-Bator en été.",
    bt: "juin–août",
    fa: ["La sterne la plus commune de Mongolie.", "Plonge pour pêcher.", "Défend farouchement son nid."]
  },
  "arctic-skua": {
    name: "Labbe parasite",
    s: "Oiseau marin sombre, rappelant un faucon, qui poursuit mouettes et sternes pour voler leur nourriture. Sur la liste mongole, sans mention GBIF.",
    d: "Le Labbe parasite niche dans la toundra arctique et hiverne dans les mers de l’hémisphère Sud. Certains traversent les continents en migration. Les mentions mongoles sont exceptionnelles.",
    f: ["Rectrices centrales pointues.", "Formes claire et sombre.", "Éclairs blancs à la base des primaires.", "Vol agile de faucon."],
    si: "Labbe pomarin — plus grand, rectrices émoussées et torsadées.",
    h: "Toundra et haute mer.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Poissons volés à d’autres oiseaux ; aussi lemmings et œufs.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Pirate la nourriture des sternes et des mouettes.",
    v: "Gémissements sur les sites de nidification.",
    cu: "Son nom parasiticus renvoie à son habitude de voler la nourriture.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Vole la nourriture d’autres oiseaux.", "Formes claire et sombre.", "Migre vers les océans austraux."]
  },
  "pomarine-skua": {
    name: "Labbe pomarin",
    s: "Labbe arctique massif ; les adultes ont des rectrices centrales en cuillère torsadée. Sur la liste mongole, sans mention GBIF.",
    d: "Le Labbe pomarin niche dans la haute toundra arctique, où il dépend des lemmings, et hiverne dans les mers tropicales. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Carrure lourde, poitrine bombée.", "Rectrices émoussées en « cuillère » torsadée chez l’adulte.", "Formes claire et sombre.", "Bande pectorale sombre chez les clairs."],
    si: "Labbe parasite — plus fin, rectrices pointues.",
    h: "Toundra et haute mer.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Lemmings en été ; poissons volés aux oiseaux marins en mer.",
    br: "Niche dans la haute toundra arctique (pas en Mongolie).",
    be: "Poursuit les goélands pour leur faire lâcher leur proie.",
    v: "Cris rauques sur les sites de nidification.",
    cu: "Son nom évoque la forme en « couvercle » de ses rectrices.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Rectrices en cuillère.", "Dépend des lemmings.", "Hiverne dans les mers tropicales."]
  }
});
