B2T("en", {
  "whimbrel": {
    T: { c: { brown: 0.6, buff: 0.25, white: 0.15 }, hb: ["water", "steppe"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["37–47 cm", "75–90 cm", "270–490 g"] },
    s: "A medium-sized curlew with a striped crown and a down-curved bill. A spring migrant through Mongolia’s lakes and steppes.",
    d: "The Whimbrel breeds in the subarctic and winters on tropical coasts. Its bill is shorter than the Eurasian Curlew’s, with a distinct kink near the tip. Flocks cross Mongolia mainly in May, stopping at Buir Nuur, Ögii Nuur, the Khurkh valley and Böön Tsagaan.",
    f: ["Dark crown with a pale central stripe.", "Down-curved bill, bent near the tip.", "Brown streaked plumage; white rump in flight.", "Smaller than Eurasian Curlew."],
    si: "Eurasian Curlew — larger, longer evenly curved bill, plain crown. Little Curlew — much smaller, short bill.",
    h: "Lake shores, wet meadows and steppe on migration.",
    di: "Buir Nuur, Ögii Nuur, Khurkh, Böön Tsagaan, Orog Nuur.",
    mi: "Passage migrant, mainly May; some in August.",
    fo: "Insects, worms, crabs and berries.",
    br: "Nests on subarctic tundra (not in Mongolia).",
    be: "Flies in lines; feeds by probing and picking.",
    v: "A rippling whistle of seven notes, ‘pu-hu-hu-hu-hu-hu-hu’.",
    cu: "Called the ‘seven whistler’ in England because of its call.",
    co: "Least Concern.",
    w: "Buir Nuur in May.",
    bt: "May",
    fa: ["Its call has seven notes.", "Striped crown.", "Winters on tropical coasts."]
  },
  "little-curlew": {
    T: { c: { buff: 0.5, brown: 0.4, white: 0.1 }, hb: ["steppe", "water"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["28–32 cm", "68–71 cm", "120–240 g"] },
    s: "A tiny curlew, the size of a plover, with a short, slightly curved bill. It passes through the eastern steppes in late summer.",
    d: "The Little Curlew breeds in clearings in the taiga of north-east Siberia and winters in the grasslands of northern Australia. It is a bird of dry grassland rather than mudflats. In Mongolia it passes mainly in August, when flocks feed on steppe and lake shores at Buir Nuur, Ögii Nuur and in Dornod.",
    f: ["Small, plover-sized curlew.", "Short, gently down-curved bill.", "Striped crown.", "Buff, finely streaked plumage.", "No white rump."],
    si: "Whimbrel — much larger, longer bill, white rump.",
    h: "Dry steppe, grassland and lake margins.",
    di: "Dornod (Buir Nuur, Mongol Daguur), Ögii Nuur, Khurkh, Böön Tsagaan.",
    mi: "Passage migrant, mainly August.",
    fo: "Grasshoppers, beetles and seeds.",
    br: "Nests in Siberian taiga clearings (not in Mongolia).",
    be: "Feeds on dry ground in flocks.",
    v: "A soft ‘te-te-te’.",
    cu: "Its close relative, the Eskimo Curlew, is probably extinct.",
    co: "Least Concern.",
    w: "Eastern steppes in August.",
    bt: "August",
    fa: ["The smallest curlew.", "Feeds on dry grassland.", "Winters in Australia."]
  },
  "eurasian-curlew": {
    T: { c: { brown: 0.55, buff: 0.3, white: 0.15 }, hb: ["water", "steppe"], bk: "curved", bh: ["walk", "soar"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["50–60 cm", "80–100 cm", "0.6–1 kg"] },
    s: "A large brown wader with a very long, down-curved bill and a haunting ‘cur-lee’ call. Breeds in wet meadows in northern Mongolia; Near Threatened.",
    d: "The Eurasian Curlew breeds across Europe and Asia in wet meadows and bogs. Its population has declined sharply. In Mongolia it breeds in wet river valleys of the Khentii and Khangai (Khurkh valley, Ögii Nuur) and is seen on passage at many lakes.",
    f: ["Largest wader in Mongolia.", "Very long, evenly down-curved bill.", "Brown, streaked plumage.", "White rump and back in flight.", "Plain crown."],
    si: "Far Eastern Curlew — brown rump, even longer bill. Whimbrel — smaller, striped crown.",
    h: "Wet meadows, bogs and lake shores.",
    di: "Khentii (Khurkh), Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khar Us Nuur.",
    mi: "Summer visitor and migrant, April–September.",
    fo: "Worms, insects, crabs and molluscs.",
    br: "Nests on the ground in meadows; 4 eggs.",
    be: "Probes deeply in mud; flies with slow, gull-like beats.",
    v: "A rising, bubbling ‘cur-lee’.",
    cu: "Its call is a symbol of wild moorland in European poetry.",
    co: "Near Threatened.",
    w: "Khurkh valley meadows in June.",
    bt: "June–August",
    fa: ["Longest bill of any Mongolian wader except the Far Eastern Curlew.", "Near Threatened.", "Its name copies its call."]
  },
  "far-eastern-curlew": {
    T: { c: { brown: 0.6, buff: 0.3, white: 0.1 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage", "summer"], sz: ["53–66 cm", "110 cm", "0.6–1.4 kg"] },
    s: "The largest curlew in the world, with an enormously long bill and brown rump. An endangered bird that breeds in small numbers in eastern Mongolia.",
    d: "The Far Eastern Curlew breeds in south-east Siberia, north-east China and eastern Mongolia and winters mainly in Australia. It depends on the tidal flats of the Yellow Sea, which are being reclaimed, and has declined by about 80 %. In Mongolia it is found in the Dornod marshes, around Buir Nuur and in the Khurkh valley.",
    f: ["Very large, all brown curlew.", "Extremely long, curved bill.", "Brown back and rump (no white).", "Heavily barred underwings."],
    si: "Eurasian Curlew — white rump and pale underwings.",
    h: "Wet meadows and bogs; tidal flats on migration.",
    di: "Dornod (Buir Nuur), Khentii (Khurkh), Orog Nuur.",
    mi: "Summer visitor and migrant, May–September.",
    fo: "Crabs, worms and insects.",
    br: "Nests in bogs and wet meadows; 4 eggs.",
    be: "Probes deep into mud with its long bill.",
    v: "A mournful ‘cur-ee’.",
    cu: "Its scientific name wrongly refers to Madagascar.",
    co: "Endangered.",
    w: "Dornod wetlands in July, from a distance.",
    bt: "July",
    fa: ["World’s largest curlew.", "Declined by 80 %.", "Winters in Australia."]
  },
  "bar-tailed-godwit": {
    T: { c: { rufous: 0.45, brown: 0.35, white: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["37–41 cm", "70–80 cm", "190–630 g"] },
    s: "A long-legged wader with a long, slightly upturned bill; the male turns brick-red in summer. A scarce migrant through Mongolia.",
    d: "The Bar-tailed Godwit breeds on Arctic tundra. Alaskan birds make the longest non-stop flight of any bird, over 11,000 km to New Zealand. In Mongolia it is a scarce migrant at Ögii Nuur, Böön Tsagaan and Khar Us Nuur.",
    f: ["Long, slightly upturned bill.", "Male: deep brick-red underparts in summer.", "Barred tail, no wing bar.", "Shorter legs than Black-tailed Godwit."],
    si: "Black-tailed Godwit — straight bill, black tail band, bold white wing bar.",
    h: "Lake shores and mudflats.",
    di: "Ögii Nuur, Böön Tsagaan, Khar Us Nuur, Buir Nuur.",
    mi: "Passage migrant, May–September.",
    fo: "Worms, molluscs and insects.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Probes mud in shallow water.",
    v: "A nasal ‘kirruc’.",
    cu: "Holds the record for the longest non-stop bird flight.",
    co: "Near Threatened.",
    w: "Ögii Nuur in June.",
    bt: "June",
    fa: ["Flies 11,000 km non-stop.", "Bill slightly upturned.", "Near Threatened."]
  },
  "black-tailed-godwit": {
    T: { c: { rufous: 0.35, brown: 0.3, white: 0.2, black: 0.15 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["40–44 cm", "70–82 cm", "160–500 g"] },
    s: "A tall, elegant wader with a long straight bill, a black tail band and a bold white wing bar. Breeds in wet meadows in northern and eastern Mongolia.",
    d: "The Black-tailed Godwit breeds from Iceland to the Russian Far East. It has declined in Europe and is Near Threatened. In Mongolia it is common in wet meadows of the Khurkh valley, Ögii Nuur, Orog Nuur and Buir Nuur, and breeds there.",
    f: ["Long, straight bill, pinkish at the base.", "Chestnut neck and breast in summer.", "Black tail with a white rump.", "Broad white wing bar in flight.", "Long legs."],
    si: "Bar-tailed Godwit — upturned bill, barred tail, no wing bar. Asian Dowitcher — smaller, all-black bill.",
    h: "Wet meadows and shallow marshes.",
    di: "Khentii (Khurkh), Ögii Nuur, Orog Nuur, Buir Nuur, Böön Tsagaan, Mongol Daguur.",
    mi: "Summer visitor, April–September.",
    fo: "Worms, insect larvae and molluscs.",
    br: "Nests in wet grassland; 4 eggs.",
    be: "Wades deep; parents call loudly from posts.",
    v: "A loud ‘wicka-wicka-wicka’.",
    cu: "The national bird of the Netherlands.",
    co: "Near Threatened.",
    w: "Khurkh valley meadows in June.",
    bt: "May–August",
    fa: ["National bird of the Netherlands.", "Bold white wing bar.", "Near Threatened."]
  },
  "ruddy-turnstone": {
    T: { c: { rufous: 0.35, white: 0.3, black: 0.3, red: 0.05 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["laugh"], ac: "day", se: ["passage"], sz: ["21–26 cm", "50–57 cm", "85–150 g"] },
    s: "A stocky, harlequin-patterned wader with orange legs that flips stones to find food. A regular migrant on lake shores.",
    d: "The Ruddy Turnstone breeds around the Arctic and winters on coasts worldwide. It uses its short, wedge-shaped bill to turn over stones and weed. In Mongolia it passes in May and August, most often at Ögii Nuur, Buir Nuur and Böön Tsagaan.",
    f: ["Black-and-white face pattern.", "Chestnut and black back in summer.", "Short orange legs.", "Short, wedge-shaped bill.", "Bold pattern in flight."],
    si: "Unmistakable.",
    h: "Stony and sandy lake shores.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Orog Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and July–September.",
    fo: "Insects, crustaceans and worms found under stones.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Flips stones with its bill.",
    v: "A rattling ‘tuk-a-tuk’.",
    cu: "Named for its stone-turning habit.",
    co: "Near Threatened.",
    w: "Ögii Nuur in May and August.",
    bt: "May, August",
    fa: ["Turns over stones.", "Orange legs.", "Found on every continent’s coasts."]
  },
  "red-knot": {
    T: { c: { rufous: 0.45, gray: 0.35, white: 0.2 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["23–26 cm", "57–61 cm", "100–200 g"] },
    s: "A plump sandpiper that is brick-red below in summer. A scarce migrant on Mongolian lake shores.",
    d: "The Red Knot breeds on high Arctic tundra and migrates to coasts as far as Australia and South America. Its populations have declined. In Mongolia it is a scarce migrant, mainly in August, at Ögii Nuur, Böön Tsagaan and Buir Nuur.",
    f: ["Stocky, with a short straight bill.", "Brick-red face and underparts in summer.", "Grey in winter.", "Short greenish legs."],
    si: "Curlew Sandpiper — slimmer, long curved bill. Dunlin — smaller, black belly patch in summer.",
    h: "Sandy and muddy lake shores.",
    di: "Ögii Nuur, Böön Tsagaan, Buir Nuur, Orog Nuur.",
    mi: "Passage migrant, June–September; peak in August.",
    fo: "Molluscs and insects.",
    br: "Nests on high Arctic tundra (not in Mongolia).",
    be: "Feeds in tight flocks.",
    v: "A low ‘knut’.",
    cu: "Possibly named after King Canute, who stood at the tide’s edge.",
    co: "Near Threatened.",
    w: "Ögii Nuur in August.",
    bt: "August",
    fa: ["Brick-red in summer.", "Long-distance migrant.", "Near Threatened."]
  },
  "ruff": {
    T: { c: { brown: 0.5, buff: 0.25, white: 0.15, black: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["26–32 cm", "48–58 cm", "70–230 g"] },
    s: "A wader whose males grow huge, colourful neck ruffs for dancing contests. A regular migrant on Mongolian lakes.",
    d: "The Ruff breeds from Scandinavia to eastern Siberia. Males gather at leks where they display with ruffs and ear tufts of many colours; some males look like females and sneak matings. In Mongolia it passes in May and August–September at Ögii Nuur, Orog Nuur, Böön Tsagaan and Khar Us Nuur.",
    f: ["Males in spring: large ruff of black, white or rufous feathers.", "Small head, long neck, pot-bellied shape.", "Scaly brown back.", "Orange or greenish legs.", "Females (Reeves) much smaller."],
    si: "Common Redshank — red legs, white back. Wood Sandpiper — spotted back, white eyebrow.",
    h: "Muddy lake shores and wet meadows.",
    di: "Ögii Nuur, Orog Nuur, Böön Tsagaan, Khar Us Nuur, Khurkh.",
    mi: "Passage migrant, May and July–September.",
    fo: "Insects and seeds.",
    br: "Nests in northern marshes (not in Mongolia).",
    be: "Males display at leks.",
    v: "Mostly silent.",
    cu: "Named after the ruff collars of the 16th century.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May, August",
    fa: ["Males have colourful ruffs.", "Some males mimic females.", "Displays at leks."]
  },
  "broad-billed-sandpiper": {
    T: { c: { brown: 0.5, white: 0.3, black: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["16–18 cm", "34–37 cm", "30–50 g"] },
    s: "A small sandpiper with a double white eyebrow and a bill that droops at the tip. A regular migrant through Mongolia; globally Vulnerable.",
    d: "The Broad-billed Sandpiper breeds in northern bogs and winters on coasts of the Indian Ocean and Australia. In Mongolia it is a regular migrant in May and August at Ögii Nuur, Buir Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["‘Split’ white eyebrow — a double stripe.", "Bill broad at the base and drooping at the tip.", "Dark, snipe-like streaked back.", "Short legs."],
    si: "Dunlin — no split eyebrow, black belly in summer. Little Stint — shorter bill.",
    h: "Muddy lake shores.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Passage migrant, May and August.",
    fo: "Insects, worms and seeds.",
    br: "Nests in northern bogs (not in Mongolia).",
    be: "Feeds slowly with other small waders.",
    v: "A buzzing ‘chrreet’.",
    cu: "Named for its unusually broad bill.",
    co: "Vulnerable.",
    w: "Ögii Nuur in August.",
    bt: "May, August",
    fa: ["Has a split eyebrow.", "Bill droops at the tip.", "Globally Vulnerable."]
  },
  "sharp-tailed-sandpiper": {
    T: { c: { rufous: 0.35, brown: 0.35, buff: 0.2, white: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["17–22 cm", "36–43 cm", "50–100 g"] },
    s: "A medium sandpiper with a rufous cap and arrowhead marks on the breast. An autumn migrant, especially in the east; globally Vulnerable.",
    d: "The Sharp-tailed Sandpiper breeds in the Siberian Arctic and winters in Australia. Many young birds pass through eastern Mongolia in August. It is common at Ögii Nuur and Buir Nuur in autumn.",
    f: ["Bright rufous cap.", "Buff breast with dark arrowhead spots.", "Pointed tail.", "Greenish legs.", "Juveniles have a rich orange breast."],
    si: "Pectoral Sandpiper — sharp line between streaked breast and white belly. Long-toed Stint — smaller.",
    h: "Wet meadows and muddy shores.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Mongol Daguur, Khurkh.",
    mi: "Passage migrant, July–August.",
    fo: "Insects and worms.",
    br: "Nests on Siberian tundra (not in Mongolia).",
    be: "Feeds in grassy margins.",
    v: "A soft ‘trrrit’.",
    cu: "Named for its pointed tail feathers.",
    co: "Vulnerable.",
    w: "Ögii Nuur in August.",
    bt: "August",
    fa: ["Rufous cap.", "Winters in Australia.", "Globally Vulnerable."]
  },
  "curlew-sandpiper": {
    T: { c: { rufous: 0.45, gray: 0.3, white: 0.25 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["18–23 cm", "38–41 cm", "45–90 g"] },
    s: "An elegant sandpiper with a long, down-curved bill that turns deep brick-red in summer. A common migrant on Mongolian lakes; globally Vulnerable.",
    d: "The Curlew Sandpiper breeds on Siberian tundra and winters in Africa, South Asia and Australia. It is common on passage in Mongolia in May and July–August at Ögii Nuur, Buir Nuur and Böön Tsagaan.",
    f: ["Long, down-curved bill.", "Brick-red underparts in summer.", "White rump in flight.", "Long legs."],
    si: "Dunlin — shorter bill, black belly patch, dark rump.",
    h: "Muddy and saline lake shores.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Orog Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and July–August.",
    fo: "Insects, worms and crustaceans.",
    br: "Nests on Siberian tundra (not in Mongolia).",
    be: "Wades in deeper water than stints.",
    v: "A soft ‘chirrip’.",
    cu: "Its breeding success depends on lemming cycles.",
    co: "Vulnerable.",
    w: "Ögii Nuur in July–August.",
    bt: "July–August",
    fa: ["Curved bill like a tiny curlew.", "Brick-red in summer.", "Globally Vulnerable."]
  },
  "temmincks-stint": {
    T: { c: { gray: 0.45, brown: 0.35, white: 0.2 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["13–15 cm", "34–37 cm", "15–35 g"] },
    s: "A tiny, plain grey-brown stint with yellowish legs and white outer tail feathers. A common migrant in May and August.",
    d: "Temminck’s Stint breeds on northern tundra and taiga river banks and winters in Africa and southern Asia. In Mongolia it is common on passage at Ögii Nuur, Buir Nuur, Böön Tsagaan and Khar Us Nuur, often at the grassy edges of pools.",
    f: ["Very small, plain grey-brown.", "Yellow-green legs.", "White outer tail feathers.", "Breast washed grey-brown."],
    si: "Little Stint — black legs, rufous tones. Long-toed Stint — longer yellow legs, rufous back.",
    h: "Grassy margins of lakes and pools.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Khar Us Nuur, Orog Nuur, Yolyn Am.",
    mi: "Passage migrant, May and July–September.",
    fo: "Small insects.",
    br: "Nests in the north (not in Mongolia).",
    be: "Towers up when flushed with a trilling call.",
    v: "A dry trill ‘tirrrr’.",
    cu: "Named after the Dutch naturalist Coenraad Jacob Temminck.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May, August",
    fa: ["Yellowish legs.", "White tail sides.", "Named after a Dutch naturalist."]
  },
  "long-toed-stint": {
    T: { c: { brown: 0.45, rufous: 0.3, white: 0.25 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["13–16 cm", "26–31 cm", "20–37 g"] },
    s: "A small stint with long yellow legs and toes, often standing upright. A common migrant, especially in May.",
    d: "The Long-toed Stint breeds in Siberia and winters in South-East Asia and Australia. It prefers grassy freshwater margins. In Mongolia it is common on passage at Ögii Nuur, Buir Nuur, Böön Tsagaan and around Ulaanbaatar.",
    f: ["Long yellowish legs and long toes.", "Rufous-edged back feathers.", "Dark forehead, pale eyebrow.", "Upright stance."],
    si: "Temminck’s Stint — plain grey. Little Stint — black legs.",
    h: "Grassy freshwater margins.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Ulaanbaatar, Orog Nuur, Yolyn Am.",
    mi: "Passage migrant, May and July–August.",
    fo: "Small insects.",
    br: "Nests in Siberia (not in Mongolia).",
    be: "Stretches its neck up when alarmed.",
    v: "A soft ‘chrrup’.",
    cu: "Named for its long toes.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May",
    fa: ["Long toes.", "Stands upright.", "Winters in Australia."]
  }
});
