B2T("fr", {
  "whimbrel": {
    name: "Courlis corlieu",
    s: "Courlis de taille moyenne à calotte rayée et bec arqué. Migrateur printanier sur les lacs et steppes de Mongolie.",
    d: "Le Courlis corlieu niche dans la zone subarctique et hiverne sur les côtes tropicales. Son bec est plus court que celui du Courlis cendré, avec une cassure nette près de l’extrémité. Des vols traversent la Mongolie surtout en mai, faisant halte au lac Buir, au lac Ögii, dans la vallée de Khurkh et à Böön Tsagaan.",
    f: ["Calotte sombre avec une raie centrale pâle.", "Bec arqué, coudé près de l’extrémité.", "Plumage brun strié ; croupion blanc en vol.", "Plus petit que le Courlis cendré."],
    si: "Courlis cendré — plus grand, bec plus long régulièrement courbé, calotte unie. Courlis nain — bien plus petit, bec court.",
    h: "Rives de lacs, prairies humides et steppe en migration.",
    di: "Lac Buir, lac Ögii, Khurkh, Böön Tsagaan, lac Orog.",
    mi: "Migrateur, surtout en mai ; quelques-uns en août.",
    fo: "Insectes, vers, crabes et baies.",
    br: "Niche dans la toundra subarctique (pas en Mongolie).",
    be: "Vole en lignes ; sonde et picore.",
    v: "Un sifflement roulé de sept notes « pou-hou-hou-hou-hou-hou-hou ».",
    cu: "Appelé le « siffleur à sept notes » en Angleterre.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en mai.",
    bt: "mai",
    fa: ["Son cri a sept notes.", "Calotte rayée.", "Hiverne sur les côtes tropicales."]
  },
  "little-curlew": {
    name: "Courlis nain",
    s: "Minuscule courlis de la taille d’un pluvier, au bec court légèrement courbé. Il traverse les steppes de l’est en fin d’été.",
    d: "Le Courlis nain niche dans les clairières de la taïga du nord-est de la Sibérie et hiverne dans les prairies du nord de l’Australie. C’est un oiseau des prairies sèches plutôt que des vasières. En Mongolie, il passe surtout en août, en groupes qui se nourrissent dans la steppe et sur les rives du lac Buir, du lac Ögii et du Dornod.",
    f: ["Petit courlis de la taille d’un pluvier.", "Bec court doucement arqué.", "Calotte rayée.", "Plumage chamois finement strié.", "Pas de croupion blanc."],
    si: "Courlis corlieu — bien plus grand, bec plus long, croupion blanc.",
    h: "Steppe sèche, prairies et bords de lacs.",
    di: "Dornod (lac Buir, Mongol Daguur), lac Ögii, Khurkh, Böön Tsagaan.",
    mi: "Migrateur, surtout en août.",
    fo: "Sauterelles, coléoptères et graines.",
    br: "Niche dans les clairières de la taïga sibérienne (pas en Mongolie).",
    be: "Se nourrit en groupes sur sol sec.",
    v: "Un doux « té-té-té ».",
    cu: "Son proche parent, le Courlis esquimau, est probablement éteint.",
    co: "Préoccupation mineure.",
    w: "Steppes de l’est en août.",
    bt: "août",
    fa: ["Le plus petit courlis.", "Se nourrit en prairie sèche.", "Hiverne en Australie."]
  },
  "eurasian-curlew": {
    name: "Courlis cendré",
    s: "Grand limicole brun au très long bec arqué et au cri obsédant « cour-li ». Niche dans les prairies humides du nord de la Mongolie ; Quasi menacé.",
    d: "Le Courlis cendré niche en Europe et en Asie dans les prairies humides et les tourbières. Sa population a fortement décliné. En Mongolie, il niche dans les vallées humides du Khentii et du Khangaï (vallée de Khurkh, lac Ögii) et se voit en migration sur de nombreux lacs.",
    f: ["Le plus grand limicole de Mongolie.", "Très long bec régulièrement arqué.", "Plumage brun strié.", "Croupion et dos blancs en vol.", "Calotte unie."],
    si: "Courlis de Sibérie — croupion brun, bec encore plus long. Courlis corlieu — plus petit, calotte rayée.",
    h: "Prairies humides, tourbières et rives de lacs.",
    di: "Khentii (Khurkh), lac Ögii, Böön Tsagaan, lac Orog, lac Buir, lac Khar Us.",
    mi: "Visiteur d’été et migrateur, avril–septembre.",
    fo: "Vers, insectes, crabes et mollusques.",
    br: "Niche au sol dans les prairies ; 4 œufs.",
    be: "Sonde profondément la vase ; vol lent de goéland.",
    v: "Un « cour-li » montant et bouillonnant.",
    cu: "Son cri symbolise les landes sauvages dans la poésie européenne.",
    co: "Quasi menacé.",
    w: "Prairies de la vallée de Khurkh en juin.",
    bt: "juin–août",
    fa: ["Bec le plus long des limicoles mongols après le Courlis de Sibérie.", "Quasi menacé.", "Son nom imite son cri."]
  },
  "far-eastern-curlew": {
    name: "Courlis de Sibérie",
    s: "Le plus grand courlis du monde, au bec démesuré et au croupion brun. Espèce menacée qui niche en petit nombre dans l’est de la Mongolie.",
    d: "Le Courlis de Sibérie niche dans le sud-est de la Sibérie, le nord-est de la Chine et l’est de la Mongolie, et hiverne surtout en Australie. Il dépend des vasières de la mer Jaune, qui sont asséchées, et a décliné d’environ 80 %. En Mongolie, on le trouve dans les marais du Dornod, autour du lac Buir et dans la vallée de Khurkh.",
    f: ["Très grand courlis entièrement brun.", "Bec extrêmement long et arqué.", "Dos et croupion bruns (sans blanc).", "Dessous des ailes fortement barré."],
    si: "Courlis cendré — croupion blanc et dessous des ailes pâle.",
    h: "Prairies humides et tourbières ; vasières en migration.",
    di: "Dornod (lac Buir), Khentii (Khurkh), lac Orog.",
    mi: "Visiteur d’été et migrateur, mai–septembre.",
    fo: "Crabes, vers et insectes.",
    br: "Niche dans les tourbières et prairies humides ; 4 œufs.",
    be: "Sonde profondément la vase avec son long bec.",
    v: "Un « cour-i » mélancolique.",
    cu: "Son nom scientifique évoque à tort Madagascar.",
    co: "En danger.",
    w: "Zones humides du Dornod en juillet, à distance.",
    bt: "juillet",
    fa: ["Le plus grand courlis du monde.", "A décliné de 80 %.", "Hiverne en Australie."]
  },
  "bar-tailed-godwit": {
    name: "Barge rousse",
    s: "Limicole haut sur pattes au long bec légèrement retroussé ; le mâle devient rouge brique en été. Migratrice peu commune en Mongolie.",
    d: "La Barge rousse niche dans la toundra arctique. Les oiseaux d’Alaska réalisent le plus long vol sans escale de tous les oiseaux, plus de 11 000 km jusqu’en Nouvelle-Zélande. En Mongolie, c’est une migratrice peu commune au lac Ögii, à Böön Tsagaan et au lac Khar Us.",
    f: ["Long bec légèrement retroussé.", "Mâle : dessous rouge brique profond en été.", "Queue barrée, pas de barre alaire.", "Pattes plus courtes que la Barge à queue noire."],
    si: "Barge à queue noire — bec droit, bande caudale noire, large barre alaire blanche.",
    h: "Rives de lacs et vasières.",
    di: "Lac Ögii, Böön Tsagaan, lac Khar Us, lac Buir.",
    mi: "Migratrice, mai–septembre.",
    fo: "Vers, mollusques et insectes.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Sonde la vase en eau peu profonde.",
    v: "Un « kirrouc » nasal.",
    cu: "Détient le record du plus long vol sans escale chez les oiseaux.",
    co: "Quasi menacée.",
    w: "Lac Ögii en juin.",
    bt: "juin",
    fa: ["Vole 11 000 km sans escale.", "Bec légèrement retroussé.", "Quasi menacée."]
  },
  "black-tailed-godwit": {
    name: "Barge à queue noire",
    s: "Grand limicole élégant au long bec droit, à bande caudale noire et large barre alaire blanche. Niche dans les prairies humides du nord et de l’est de la Mongolie.",
    d: "La Barge à queue noire niche de l’Islande à l’Extrême-Orient russe. Elle a décliné en Europe et est Quasi menacée. En Mongolie, elle est commune et niche dans les prairies humides de la vallée de Khurkh, du lac Ögii, du lac Orog et du lac Buir.",
    f: ["Long bec droit, rosé à la base.", "Cou et poitrine marron en été.", "Queue noire et croupion blanc.", "Large barre alaire blanche en vol.", "Longues pattes."],
    si: "Barge rousse — bec retroussé, queue barrée, sans barre alaire. Bécassin d’Asie — plus petit, bec entièrement noir.",
    h: "Prairies humides et marais peu profonds.",
    di: "Khentii (Khurkh), lac Ögii, lac Orog, lac Buir, Böön Tsagaan, Mongol Daguur.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Vers, larves d’insectes et mollusques.",
    br: "Niche dans les prairies humides ; 4 œufs.",
    be: "Patauge profondément ; les parents crient fort depuis des piquets.",
    v: "Un « ouika-ouika-ouika » sonore.",
    cu: "Oiseau national des Pays-Bas.",
    co: "Quasi menacée.",
    w: "Prairies de la vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Oiseau national des Pays-Bas.", "Large barre alaire blanche.", "Quasi menacée."]
  },
  "ruddy-turnstone": {
    name: "Tournepierre à collier",
    s: "Limicole trapu au motif d’arlequin et aux pattes orange, qui retourne les pierres pour se nourrir. Migrateur régulier sur les rives des lacs.",
    d: "Le Tournepierre à collier niche autour de l’Arctique et hiverne sur les côtes du monde entier. Il retourne pierres et algues avec son bec court en coin. En Mongolie, il passe en mai et en août, surtout au lac Ögii, au lac Buir et à Böön Tsagaan.",
    f: ["Face à motif noir et blanc.", "Dos roux et noir en été.", "Courtes pattes orange.", "Bec court en coin.", "Motif contrasté en vol."],
    si: "Inconfondable.",
    h: "Rives pierreuses et sableuses des lacs.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Orog, lac Khar Us.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Insectes, crustacés et vers trouvés sous les pierres.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Retourne les pierres avec son bec.",
    v: "Un « touk-a-touk » crépitant.",
    cu: "Nommé d’après son habitude de retourner les pierres.",
    co: "Quasi menacé.",
    w: "Lac Ögii en mai et août.",
    bt: "mai, août",
    fa: ["Retourne les pierres.", "Pattes orange.", "Présent sur les côtes de tous les continents."]
  },
  "red-knot": {
    name: "Bécasseau maubèche",
    s: "Bécasseau dodu, rouge brique dessous en été. Migrateur peu commun sur les rives des lacs mongols.",
    d: "Le Bécasseau maubèche niche dans la haute toundra arctique et migre jusqu’aux côtes d’Australie et d’Amérique du Sud. Ses populations ont décliné. En Mongolie, c’est un migrateur peu commun, surtout en août, au lac Ögii, à Böön Tsagaan et au lac Buir.",
    f: ["Trapu, bec court et droit.", "Face et dessous rouge brique en été.", "Gris en hiver.", "Courtes pattes verdâtres."],
    si: "Bécasseau cocorli — plus fin, long bec arqué. Bécasseau variable — plus petit, plaque ventrale noire en été.",
    h: "Rives sableuses et vaseuses des lacs.",
    di: "Lac Ögii, Böön Tsagaan, lac Buir, lac Orog.",
    mi: "Migrateur, juin–septembre ; pic en août.",
    fo: "Mollusques et insectes.",
    br: "Niche dans la haute toundra arctique (pas en Mongolie).",
    be: "Se nourrit en groupes serrés.",
    v: "Un « knout » grave.",
    cu: "Son nom anglais viendrait du roi Knut, debout au bord de la marée.",
    co: "Quasi menacé.",
    w: "Lac Ögii en août.",
    bt: "août",
    fa: ["Rouge brique en été.", "Grand migrateur.", "Quasi menacé."]
  },
  "ruff": {
    name: "Combattant varié",
    s: "Limicole dont les mâles arborent d’énormes collerettes colorées lors de joutes dansées. Migrateur régulier sur les lacs mongols.",
    d: "Le Combattant varié niche de la Scandinavie à la Sibérie orientale. Les mâles se rassemblent sur des arènes où ils déploient collerettes et aigrettes de toutes couleurs ; certains mâles ressemblent aux femelles et s’accouplent en douce. En Mongolie, il passe en mai et en août–septembre aux lacs Ögii, Orog, Khar Us et à Böön Tsagaan.",
    f: ["Mâle au printemps : grande collerette noire, blanche ou rousse.", "Petite tête, long cou, ventre rond.", "Dos brun écailleux.", "Pattes orange ou verdâtres.", "Femelles bien plus petites."],
    si: "Chevalier gambette — pattes rouges, dos blanc. Chevalier sylvain — dos tacheté, sourcil blanc.",
    h: "Rives vaseuses et prairies humides.",
    di: "Lac Ögii, lac Orog, Böön Tsagaan, lac Khar Us, Khurkh.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Insectes et graines.",
    br: "Niche dans les marais du nord (pas en Mongolie).",
    be: "Les mâles paradent sur des arènes.",
    v: "Surtout silencieux.",
    cu: "Son nom anglais évoque les fraises (collerettes) du XVIᵉ siècle.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai, août",
    fa: ["Les mâles portent des collerettes colorées.", "Certains mâles imitent les femelles.", "Parade sur des arènes."]
  },
  "broad-billed-sandpiper": {
    name: "Bécasseau falcinelle",
    s: "Petit bécasseau au double sourcil blanc et au bec tombant à la pointe. Migrateur régulier en Mongolie ; Vulnérable.",
    d: "Le Bécasseau falcinelle niche dans les tourbières du nord et hiverne sur les côtes de l’océan Indien et d’Australie. En Mongolie, il passe régulièrement en mai et en août au lac Ögii, au lac Buir, à Böön Tsagaan et au lac Orog.",
    f: ["Sourcil blanc « fendu » — double trait.", "Bec large à la base et tombant à la pointe.", "Dos sombre strié comme une bécassine.", "Pattes courtes."],
    si: "Bécasseau variable — sans sourcil fendu, ventre noir en été. Bécasseau minute — bec plus court.",
    h: "Rives vaseuses des lacs.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Orog.",
    mi: "Migrateur, mai et août.",
    fo: "Insectes, vers et graines.",
    br: "Niche dans les tourbières du nord (pas en Mongolie).",
    be: "Se nourrit lentement avec d’autres petits limicoles.",
    v: "Un « chrriit » bourdonnant.",
    cu: "Nommé pour son bec inhabituellement large.",
    co: "Vulnérable.",
    w: "Lac Ögii en août.",
    bt: "mai, août",
    fa: ["Sourcil fendu.", "Bec tombant à la pointe.", "Vulnérable à l’échelle mondiale."]
  },
  "sharp-tailed-sandpiper": {
    name: "Bécasseau à queue pointue",
    s: "Bécasseau moyen à calotte rousse et taches en pointe de flèche sur la poitrine. Migrateur d’automne, surtout dans l’est ; Vulnérable.",
    d: "Le Bécasseau à queue pointue niche dans l’Arctique sibérien et hiverne en Australie. De nombreux jeunes traversent l’est de la Mongolie en août. Il est commun au lac Ögii et au lac Buir en automne.",
    f: ["Calotte rousse vive.", "Poitrine chamois à taches sombres en pointe de flèche.", "Queue pointue.", "Pattes verdâtres.", "Juvéniles à poitrine orange vif."],
    si: "Bécasseau tacheté — démarcation nette entre poitrine striée et ventre blanc. Bécasseau à longs doigts — plus petit.",
    h: "Prairies humides et rives vaseuses.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, Mongol Daguur, Khurkh.",
    mi: "Migrateur, juillet–août.",
    fo: "Insectes et vers.",
    br: "Niche dans la toundra sibérienne (pas en Mongolie).",
    be: "Se nourrit dans les bordures herbeuses.",
    v: "Un doux « trrrit ».",
    cu: "Nommé pour ses rectrices pointues.",
    co: "Vulnérable.",
    w: "Lac Ögii en août.",
    bt: "août",
    fa: ["Calotte rousse.", "Hiverne en Australie.", "Vulnérable à l’échelle mondiale."]
  },
  "curlew-sandpiper": {
    name: "Bécasseau cocorli",
    s: "Bécasseau élégant au long bec arqué, rouge brique en été. Migrateur commun sur les lacs mongols ; Vulnérable.",
    d: "Le Bécasseau cocorli niche dans la toundra sibérienne et hiverne en Afrique, en Asie du Sud et en Australie. Il est commun en migration en Mongolie en mai et en juillet–août au lac Ögii, au lac Buir et à Böön Tsagaan.",
    f: ["Long bec arqué.", "Dessous rouge brique en été.", "Croupion blanc en vol.", "Longues pattes."],
    si: "Bécasseau variable — bec plus court, plaque ventrale noire, croupion sombre.",
    h: "Rives vaseuses et salées.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Orog, lac Khar Us.",
    mi: "Migrateur, mai et juillet–août.",
    fo: "Insectes, vers et crustacés.",
    br: "Niche dans la toundra sibérienne (pas en Mongolie).",
    be: "Patauge plus profondément que les bécasseaux minutes.",
    v: "Un doux « tchirrip ».",
    cu: "Son succès de reproduction dépend des cycles des lemmings.",
    co: "Vulnérable.",
    w: "Lac Ögii en juillet–août.",
    bt: "juil.–août",
    fa: ["Bec arqué comme un petit courlis.", "Rouge brique en été.", "Vulnérable à l’échelle mondiale."]
  },
  "temmincks-stint": {
    name: "Bécasseau de Temminck",
    s: "Minuscule bécasseau gris-brun uni, aux pattes jaunâtres et rectrices externes blanches. Migrateur commun en mai et en août.",
    d: "Le Bécasseau de Temminck niche sur les berges de la toundra et de la taïga et hiverne en Afrique et en Asie du Sud. En Mongolie, il passe en nombre au lac Ögii, au lac Buir, à Böön Tsagaan et au lac Khar Us, souvent sur les bords herbeux des mares.",
    f: ["Très petit, gris-brun uni.", "Pattes jaune-vert.", "Rectrices externes blanches.", "Poitrine lavée de gris-brun."],
    si: "Bécasseau minute — pattes noires, tons roux. Bécasseau à longs doigts — longues pattes jaunes, dos roux.",
    h: "Bords herbeux des lacs et mares.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Khar Us, lac Orog, Yolyn Am.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Petits insectes.",
    br: "Niche dans le nord (pas en Mongolie).",
    be: "S’élève en chandelle avec un trille quand on le dérange.",
    v: "Un trille sec « tirrrr ».",
    cu: "Nommé d’après le naturaliste néerlandais Coenraad Jacob Temminck.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai, août",
    fa: ["Pattes jaunâtres.", "Côtés de la queue blancs.", "Nommé d’après un naturaliste néerlandais."]
  },
  "long-toed-stint": {
    name: "Bécasseau à longs doigts",
    s: "Petit bécasseau aux longues pattes et doigts jaunes, souvent dressé. Migrateur commun, surtout en mai.",
    d: "Le Bécasseau à longs doigts niche en Sibérie et hiverne en Asie du Sud-Est et en Australie. Il préfère les bords herbeux d’eau douce. En Mongolie, il passe en nombre au lac Ögii, au lac Buir, à Böön Tsagaan et autour d’Oulan-Bator.",
    f: ["Longues pattes jaunâtres et longs doigts.", "Plumes du dos bordées de roux.", "Front sombre, sourcil pâle.", "Port dressé."],
    si: "Bécasseau de Temminck — gris uni. Bécasseau minute — pattes noires.",
    h: "Bords herbeux d’eau douce.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, Oulan-Bator, lac Orog, Yolyn Am.",
    mi: "Migrateur, mai et juillet–août.",
    fo: "Petits insectes.",
    br: "Niche en Sibérie (pas en Mongolie).",
    be: "Étire le cou vers le haut quand il est inquiet.",
    v: "Un doux « tchrroup ».",
    cu: "Nommé pour ses longs doigts.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai",
    fa: ["Longs doigts.", "Se tient dressé.", "Hiverne en Australie."]
  }
});
