B2T("en", {
  "red-necked-stint": {
    T: { c: { rufous: 0.4, gray: 0.3, white: 0.3 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["13–16 cm", "29–33 cm", "20–50 g"] },
    s: "A tiny stint whose face and throat turn brick-red in summer. A common migrant, especially in eastern Mongolia.",
    d: "The Red-necked Stint breeds in north-east Siberia and winters in South-East Asia and Australia. It is one of the most numerous waders on the East Asian flyway. In Mongolia it passes in May and July–August, especially at Buir Nuur, Ögii Nuur and Böön Tsagaan.",
    f: ["Brick-red face, throat and upper breast in summer.", "Short black bill and black legs.", "Grey-brown back with rufous edges.", "Winter: plain grey above, white below."],
    si: "Little Stint — longer legs, white throat, rufous breast sides. Temminck’s Stint — yellowish legs.",
    h: "Muddy and sandy lake shores.",
    di: "Buir Nuur, Ögii Nuur, Böön Tsagaan, Orog Nuur, Mongol Daguur.",
    mi: "Passage migrant, May and July–September.",
    fo: "Tiny invertebrates picked from mud.",
    br: "Nests on Siberian tundra (not in Mongolia).",
    be: "Feeds with rapid pecks, running on the mud.",
    v: "A thin ‘chit’.",
    cu: "Weighs less than a sparrow but flies to Australia.",
    co: "Near Threatened.",
    w: "Buir Nuur in May and August.",
    bt: "May, August",
    fa: ["Brick-red throat in summer.", "Flies to Australia.", "Near Threatened."]
  },
  "sanderling": {
    T: { c: { white: 0.5, gray: 0.3, rufous: 0.1, black: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["18–21 cm", "35–39 cm", "40–100 g"] },
    s: "A pale sandpiper that runs like clockwork along the water’s edge. A regular migrant on sandy lake shores.",
    d: "The Sanderling breeds in the high Arctic and winters on sandy beaches worldwide. It has no hind toe. In Mongolia it passes in May and August at Ögii Nuur, Buir Nuur and Orog Nuur.",
    f: ["Very pale grey and white in winter.", "Rufous head and breast in summer.", "Black legs and bill.", "Black shoulder patch.", "Bold white wing bar in flight."],
    si: "Dunlin — darker, longer drooping bill. Little Stint — smaller.",
    h: "Sandy shores.",
    di: "Ögii Nuur, Buir Nuur, Orog Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and August–September.",
    fo: "Small invertebrates.",
    br: "Nests in the high Arctic (not in Mongolia).",
    be: "Chases waves up and down the shore.",
    v: "A short ‘twick’.",
    cu: "Found on beaches on every continent.",
    co: "Least Concern.",
    w: "Sandy shores of Buir Nuur in May.",
    bt: "May, August",
    fa: ["Has no hind toe.", "Runs like clockwork.", "Very pale in winter."]
  },
  "dunlin": {
    T: { c: { brown: 0.35, gray: 0.3, white: 0.2, black: 0.15 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["16–22 cm", "33–40 cm", "40–60 g"] },
    s: "A small wader with a slightly drooping bill and a black belly patch in summer. A regular migrant on Mongolian lakes.",
    d: "The Dunlin breeds across the Arctic and is one of the most common waders in the world. In Mongolia it passes in May and September at Ögii Nuur, Böön Tsagaan, Orog Nuur and Khar Us Nuur.",
    f: ["Black patch on the belly in summer.", "Rufous back in summer.", "Bill slightly drooping at the tip.", "Grey-brown in winter.", "White wing bar."],
    si: "Curlew Sandpiper — longer curved bill, white rump. Broad-billed Sandpiper — split eyebrow.",
    h: "Muddy lake shores.",
    di: "Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and August–October.",
    fo: "Worms, insects and crustaceans.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Feeds with rapid ‘sewing machine’ probing.",
    v: "A rasping ‘treeep’.",
    cu: "Its name means ‘little dun (brown) bird’.",
    co: "Near Threatened.",
    w: "Ögii Nuur in September.",
    bt: "May, September",
    fa: ["Black belly in summer.", "Probes like a sewing machine.", "One of the world’s commonest waders."]
  },
  "little-stint": {
    T: { c: { rufous: 0.35, brown: 0.35, white: 0.3 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["12–14 cm", "28–31 cm", "17–44 g"] },
    s: "A tiny, active stint with black legs and a pale ‘V’ on its back. A common migrant on lake shores across Mongolia.",
    d: "The Little Stint breeds on the Arctic tundra of Europe and Siberia and winters in Africa and South Asia. In Mongolia it is common in May and August at Ögii Nuur, Böön Tsagaan, Orog Nuur and Khar Us Nuur.",
    f: ["Very small, with a short black bill and black legs.", "Rufous-orange tones in summer.", "Pale ‘V’ on the back.", "White throat."],
    si: "Red-necked Stint — shorter legs, red throat. Temminck’s Stint — yellowish legs, plain grey.",
    h: "Muddy lake shores.",
    di: "Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and July–September.",
    fo: "Small insects and crustaceans.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Runs busily, pecking constantly.",
    v: "A short ‘stit’.",
    cu: "One of the smallest waders.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May, August",
    fa: ["Very small.", "Black legs.", "Pale ‘V’ on the back."]
  },
  "pectoral-sandpiper": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["19–23 cm", "37–45 cm", "45–115 g"] },
    s: "A medium sandpiper whose streaked breast ends sharply against a white belly. A rare migrant in Mongolia.",
    d: "The Pectoral Sandpiper breeds on Arctic tundra from Siberia to Canada and winters in South America. Siberian birds cross North America to get there. It is rare in Mongolia, with records at Orog Nuur and Khövsgöl.",
    f: ["Heavily streaked breast with a sharp lower edge.", "White belly.", "Yellowish legs.", "Slightly drooping bill."],
    si: "Sharp-tailed Sandpiper — rufous cap, no sharp breast line.",
    h: "Grassy wetlands.",
    di: "Rare; Orog Nuur, Khövsgöl.",
    mi: "Rare migrant.",
    fo: "Insects.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Males inflate a throat sac in display.",
    v: "A reedy ‘krrik’.",
    cu: "Named for its ‘pectoral’ (breast) pattern.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Sharp breast line.", "Winters in South America.", "Rare in Mongolia."]
  },
  "asian-dowitcher": {
    T: { c: { rufous: 0.45, brown: 0.35, white: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["33–36 cm", "59 cm", "140–245 g"] },
    s: "A godwit-like wader with a long, straight black bill and rusty summer plumage. Mongolia holds important breeding sites of this Near Threatened species.",
    d: "The Asian Dowitcher breeds in scattered colonies in south Siberia, Mongolia and north-east China and winters in South-East Asia and Australia. Mongolia is one of its key breeding areas: colonies occur at Orog Nuur, Ögii Nuur, Böön Tsagaan, Buir Nuur and the Khurkh valley.",
    f: ["Long, straight, all-black bill.", "Brick-red head and underparts in summer.", "Feeds with a ‘sewing machine’ motion.", "Smaller than Black-tailed Godwit."],
    si: "Black-tailed Godwit — larger, pink-based bill, bold wing bar.",
    h: "Shallow lakes and wet meadows.",
    di: "Orog Nuur, Ögii Nuur, Böön Tsagaan, Buir Nuur, Khurkh, Mongol Daguur.",
    mi: "Summer visitor, May–August.",
    fo: "Worms and insect larvae.",
    br: "Colonial in wet grassland; 2–3 eggs.",
    be: "Probes vertically, fast and repeatedly.",
    v: "A yelping ‘chep-chep’.",
    cu: "One of the least known waders of Asia.",
    co: "Near Threatened.",
    w: "Orog Nuur in June.",
    bt: "May–June",
    fa: ["Mongolia is a key breeding area.", "Probes like a sewing machine.", "Near Threatened."]
  },
  "long-billed-dowitcher": {
    T: { c: { rufous: 0.45, brown: 0.35, white: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["24–30 cm", "46–52 cm", "90–120 g"] },
    s: "A stocky, snipe-like wader with a very long bill and white wedge up the back. A rare migrant in eastern Mongolia.",
    d: "The Long-billed Dowitcher breeds in north-east Siberia and Alaska and winters in the Americas. There are a few records from Buir Nuur and Ögii Nuur.",
    f: ["Very long, straight bill.", "Rusty underparts in summer.", "White wedge up the back in flight.", "Barred tail."],
    si: "Asian Dowitcher — larger, no white back wedge. Common Snipe — striped head.",
    h: "Shallow freshwater pools.",
    di: "Rare; Buir Nuur, Ögii Nuur.",
    mi: "Rare migrant, July–August.",
    fo: "Worms and insect larvae.",
    br: "Nests in the tundra (not in Mongolia).",
    be: "Sewing-machine feeding.",
    v: "A sharp ‘keek’.",
    cu: "Mostly an American bird.",
    co: "Least Concern.",
    w: "Check dowitchers at Buir Nuur.",
    bt: "August",
    fa: ["White wedge up the back.", "Very long bill.", "Winters in the Americas."]
  },
  "eurasian-woodcock": {
    T: { c: { brown: 0.5, rufous: 0.3, buff: 0.2 }, hb: ["forest"], bk: "long", bh: ["walk", "night"], vt: ["croak"], ac: "night", se: ["summer", "passage"], sz: ["33–38 cm", "56–60 cm", "250–420 g"] },
    s: "A plump, perfectly camouflaged forest wader with a long bill and eyes set high on the head. A summer visitor to northern forests.",
    d: "The Eurasian Woodcock breeds in damp forests across Eurasia. Its eyes give it almost 360-degree vision. Males perform ‘roding’ flights over the treetops at dusk. In Mongolia it breeds in the Khentii forests and is seen on migration, even in Ulaanbaatar and Gobi oases.",
    f: ["Plump, dead-leaf pattern.", "Long straight bill.", "Dark bars across the crown.", "Large eyes set far back.", "Broad rounded wings."],
    si: "Snipes — striped crowns, live in open wetlands.",
    h: "Damp forests with clearings.",
    di: "Khentii (Terelj, Khurkh), Ulaanbaatar, Dornod, Gobi oases.",
    mi: "Summer visitor and migrant, April–October.",
    fo: "Earthworms and insect larvae.",
    br: "Nests on the forest floor; 4 eggs.",
    be: "Roding display flights at dusk.",
    v: "Croaks and a sharp ‘tsiwick’ in roding flight.",
    cu: "Can carry chicks between its legs in flight.",
    co: "Least Concern.",
    w: "Terelj forests at dusk in May.",
    bt: "May–June",
    fa: ["Almost 360° vision.", "Camouflaged like dead leaves.", "Displays at dusk."]
  },
  "solitary-snipe": {
    T: { c: { brown: 0.5, rufous: 0.25, white: 0.15, buff: 0.1 }, hb: ["water", "mountain"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident", "winter"], sz: ["29–31 cm", "—", "130–170 g"] },
    s: "A large, dark snipe of mountain streams that stays even in winter by unfrozen springs. A scarce bird of Mongolia’s mountains.",
    d: "The Solitary Snipe breeds on mountain streams from Central Asia to Kamchatka and moves to lower valleys in winter. It lives alone along cold, fast streams. In Mongolia it is found in the Altai, the Khangai and the Khentii, including near Ulaanbaatar and Khustai in winter.",
    f: ["Large, dark snipe.", "White stripes on the face and back.", "Rusty breast.", "Long bill."],
    si: "Common Snipe — smaller, paler, white belly.",
    h: "Mountain streams and springs.",
    di: "Altai, Khangai, Khentii, Khustai, Ulaanbaatar.",
    mi: "Resident; moves to unfrozen springs in winter.",
    fo: "Insect larvae and worms.",
    br: "Nests near mountain streams.",
    be: "Solitary; stays hidden.",
    v: "A hoarse ‘pench’.",
    cu: "One of the few waders that winters in Mongolia.",
    co: "Least Concern.",
    w: "Unfrozen springs in winter.",
    bt: "October–March",
    fa: ["Winters in Mongolia.", "Lives alone.", "Loves cold mountain streams."]
  },
  "pintail-snipe": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water", "steppe"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer", "passage"], sz: ["25–27 cm", "44–47 cm", "90–170 g"] },
    s: "A snipe with pin-like outer tail feathers and no white trailing edge to the wing. A summer visitor and migrant.",
    d: "The Pintail Snipe breeds in Siberia and northern Mongolia and winters in South Asia. It is almost identical to Swinhoe’s Snipe. In Mongolia it is seen in the Khurkh valley, Ögii Nuur and Khar Us Nuur.",
    f: ["Very thin, pin-like outer tail feathers.", "No white trailing edge to the wing.", "Striped head.", "Shorter bill than Common Snipe."],
    si: "Common Snipe — white trailing edge. Swinhoe’s Snipe — very similar.",
    h: "Wet meadows and marshes.",
    di: "Khurkh, Ögii Nuur, Khar Us Nuur, Ulaanbaatar.",
    mi: "Summer visitor and migrant, May–September; peak in August.",
    fo: "Worms and insects.",
    br: "Nests in wet meadows.",
    be: "Flushes silently or with a harsh call.",
    v: "A short ‘squik’.",
    cu: "Named for its pin-shaped tail feathers.",
    co: "Least Concern.",
    w: "Khurkh valley in August.",
    bt: "August",
    fa: ["Has pin-like tail feathers.", "Hard to identify.", "Winters in South Asia."]
  },
  "swinhoes-snipe": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water", "forest"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["27–29 cm", "47–50 cm", "82–160 g"] },
    s: "A large snipe that nests in forest-steppe meadows and performs a buzzing display flight. A summer visitor to northern Mongolia.",
    d: "Swinhoe’s Snipe breeds in south-central Siberia and north Mongolia and winters in South-East Asia. In Mongolia it breeds in forest-edge meadows in the Khentii — especially the Khurkh valley and Terelj.",
    f: ["Large snipe with a long bill.", "Striped head.", "No white trailing edge to the wing.", "Many outer tail feathers."],
    si: "Pintail Snipe — slightly smaller; very hard to separate.",
    h: "Forest meadows and edges.",
    di: "Khentii (Khurkh, Terelj), Ögii Nuur, Buir Nuur, Orog Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Worms and insects.",
    br: "Nests in meadows near forest.",
    be: "Display flight with a buzzing dive.",
    v: "A rattling song in display.",
    cu: "Named after Robert Swinhoe.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["Displays with a buzzing dive.", "Named after Swinhoe.", "Nests near forests."]
  },
  "common-snipe": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer", "passage"], sz: ["25–27 cm", "44–47 cm", "80–140 g"] },
    s: "A cryptic wader with a very long bill and striped head; males ‘drum’ with their tail feathers in display. Common in Mongolia’s wetlands.",
    d: "The Common Snipe breeds across northern Eurasia. In display, males dive steeply so that their outer tail feathers vibrate with a bleating sound. In Mongolia it breeds in marshes and wet meadows throughout the country, especially the Khurkh valley.",
    f: ["Very long, straight bill.", "Striped head and back.", "White belly.", "White trailing edge to the wing.", "Zigzag flight when flushed."],
    si: "Pintail and Swinhoe’s Snipes — no white trailing edge. Jack Snipe — smaller, short bill.",
    h: "Marshes and wet meadows.",
    di: "All regions: Khurkh, Ögii Nuur, Orog Nuur, Ulaanbaatar, Buir Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Worms and insect larvae.",
    br: "Nests in tussocks; 4 eggs.",
    be: "Drumming display flights.",
    v: "A harsh ‘scaap’ when flushed.",
    cu: "Its display sound gives it the nickname ‘flying goat’.",
    co: "Least Concern.",
    w: "Khurkh valley in May.",
    bt: "May–August",
    fa: ["Drums with its tail.", "Very long bill.", "Zigzag flight."]
  },
  "jack-snipe": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["17–19 cm", "38–42 cm", "35–75 g"] },
    s: "A small, secretive snipe with a short bill that bobs as it feeds. A very rare migrant with one GBIF record.",
    d: "The Jack Snipe breeds in northern bogs and winters in Europe, Africa and South Asia. It sits tight until almost stepped on. A record from Buir Nuur is one of very few in Mongolia.",
    f: ["Small, with a short bill.", "Split eyebrow, no central crown stripe.", "Glossy green-purple back.", "Bobs up and down."],
    si: "Common Snipe — larger, longer bill.",
    h: "Bogs and marsh edges.",
    di: "Very rare; Buir Nuur.",
    mi: "Rare migrant.",
    fo: "Insects and worms.",
    br: "Nests in northern bogs (not in Mongolia).",
    be: "Flushes silently at the last moment.",
    v: "Mostly silent.",
    cu: "Its display sounds like a galloping horse.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Bobs while feeding.", "Sits tight.", "Very rare in Mongolia."]
  }
});
