B2T("fr", {
  "red-necked-stint": {
    name: "Bécasseau à col roux",
    s: "Minuscule bécasseau dont la face et la gorge deviennent rouge brique en été. Migrateur commun, surtout dans l’est de la Mongolie.",
    d: "Le Bécasseau à col roux niche dans le nord-est de la Sibérie et hiverne en Asie du Sud-Est et en Australie. C’est l’un des limicoles les plus nombreux de la voie de migration est-asiatique. En Mongolie, il passe en mai et juillet–août, surtout au lac Buir, au lac Ögii et à Böön Tsagaan.",
    f: ["Face, gorge et haut de poitrine rouge brique en été.", "Bec court noir et pattes noires.", "Dos gris-brun bordé de roux.", "Hiver : gris uni dessus, blanc dessous."],
    si: "Bécasseau minute — pattes plus longues, gorge blanche, côtés de poitrine roux. Bécasseau de Temminck — pattes jaunâtres.",
    h: "Rives vaseuses et sableuses.",
    di: "Lac Buir, lac Ögii, Böön Tsagaan, lac Orog, Mongol Daguur.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Minuscules invertébrés picorés dans la vase.",
    br: "Niche dans la toundra sibérienne (pas en Mongolie).",
    be: "Picore rapidement en courant sur la vase.",
    v: "Un fin « tchit ».",
    cu: "Plus léger qu’un moineau, il vole pourtant jusqu’en Australie.",
    co: "Quasi menacé.",
    w: "Lac Buir en mai et août.",
    bt: "mai, août",
    fa: ["Gorge rouge brique en été.", "Vole jusqu’en Australie.", "Quasi menacé."]
  },
  "sanderling": {
    name: "Bécasseau sanderling",
    s: "Bécasseau pâle qui court comme un automate au bord de l’eau. Migrateur régulier sur les rives sableuses.",
    d: "Le Bécasseau sanderling niche dans le haut Arctique et hiverne sur les plages du monde entier. Il n’a pas de doigt postérieur. En Mongolie, il passe en mai et août au lac Ögii, au lac Buir et au lac Orog.",
    f: ["Très pâle, gris et blanc en hiver.", "Tête et poitrine rousses en été.", "Pattes et bec noirs.", "Tache noire à l’épaule.", "Barre alaire blanche marquée en vol."],
    si: "Bécasseau variable — plus sombre, bec plus long et tombant. Bécasseau minute — plus petit.",
    h: "Rives sableuses.",
    di: "Lac Ögii, lac Buir, lac Orog, lac Khar Us.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Petits invertébrés.",
    br: "Niche dans le haut Arctique (pas en Mongolie).",
    be: "Poursuit les vagues le long du rivage.",
    v: "Un court « touik ».",
    cu: "Présent sur les plages de tous les continents.",
    co: "Préoccupation mineure.",
    w: "Rives sableuses du lac Buir en mai.",
    bt: "mai, août",
    fa: ["Pas de doigt postérieur.", "Court comme un automate.", "Très pâle en hiver."]
  },
  "dunlin": {
    name: "Bécasseau variable",
    s: "Petit limicole au bec légèrement tombant et à plaque ventrale noire en été. Migrateur régulier sur les lacs mongols.",
    d: "Le Bécasseau variable niche dans tout l’Arctique et compte parmi les limicoles les plus communs au monde. En Mongolie, il passe en mai et septembre au lac Ögii, à Böön Tsagaan, au lac Orog et au lac Khar Us.",
    f: ["Plaque noire sur le ventre en été.", "Dos roux en été.", "Bec légèrement tombant à la pointe.", "Gris-brun en hiver.", "Barre alaire blanche."],
    si: "Bécasseau cocorli — bec plus long et arqué, croupion blanc. Bécasseau falcinelle — sourcil fendu.",
    h: "Rives vaseuses.",
    di: "Lac Ögii, Böön Tsagaan, lac Orog, lac Buir, lac Khar Us.",
    mi: "Migrateur, mai et août–octobre.",
    fo: "Vers, insectes et crustacés.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Sonde rapidement comme une machine à coudre.",
    v: "Un « triiip » râpeux.",
    cu: "Son nom anglais signifie « petit oiseau brun ».",
    co: "Quasi menacé.",
    w: "Lac Ögii en septembre.",
    bt: "mai, sept.",
    fa: ["Ventre noir en été.", "Sonde comme une machine à coudre.", "L’un des limicoles les plus communs au monde."]
  },
  "little-stint": {
    name: "Bécasseau minute",
    s: "Minuscule bécasseau actif aux pattes noires et au « V » pâle sur le dos. Migrateur commun sur les rives de toute la Mongolie.",
    d: "Le Bécasseau minute niche dans la toundra arctique d’Europe et de Sibérie et hiverne en Afrique et en Asie du Sud. En Mongolie, il est commun en mai et en août au lac Ögii, à Böön Tsagaan, au lac Orog et au lac Khar Us.",
    f: ["Très petit, bec court noir et pattes noires.", "Tons roux orangé en été.", "« V » pâle sur le dos.", "Gorge blanche."],
    si: "Bécasseau à col roux — pattes plus courtes, gorge rousse. Bécasseau de Temminck — pattes jaunâtres, gris uni.",
    h: "Rives vaseuses.",
    di: "Lac Ögii, Böön Tsagaan, lac Orog, lac Buir, lac Khar Us.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Petits insectes et crustacés.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Court sans cesse en picorant.",
    v: "Un court « stit ».",
    cu: "L’un des plus petits limicoles.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai, août",
    fa: ["Très petit.", "Pattes noires.", "« V » pâle sur le dos."]
  },
  "pectoral-sandpiper": {
    name: "Bécasseau tacheté",
    s: "Bécasseau moyen dont la poitrine striée s’arrête net sur un ventre blanc. Migrateur rare en Mongolie.",
    d: "Le Bécasseau tacheté niche dans la toundra arctique, de la Sibérie au Canada, et hiverne en Amérique du Sud ; les oiseaux sibériens traversent l’Amérique du Nord pour y parvenir. Il est rare en Mongolie, noté au lac Orog et au Khövsgöl.",
    f: ["Poitrine fortement striée à limite inférieure nette.", "Ventre blanc.", "Pattes jaunâtres.", "Bec légèrement tombant."],
    si: "Bécasseau à queue pointue — calotte rousse, sans limite nette sur la poitrine.",
    h: "Zones humides herbeuses.",
    di: "Rare ; lac Orog, Khövsgöl.",
    mi: "Migrateur rare.",
    fo: "Insectes.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Le mâle gonfle un sac gulaire en parade.",
    v: "Un « krrik » roseau.",
    cu: "Son nom anglais évoque le dessin de sa poitrine.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Limite nette sur la poitrine.", "Hiverne en Amérique du Sud.", "Rare en Mongolie."]
  },
  "asian-dowitcher": {
    name: "Bécassin d’Asie",
    s: "Limicole ressemblant à une barge, au long bec droit noir et au plumage estival rouille. La Mongolie abrite d’importants sites de nidification de cette espèce quasi menacée.",
    d: "Le Bécassin d’Asie niche en colonies dispersées dans le sud de la Sibérie, en Mongolie et dans le nord-est de la Chine, et hiverne en Asie du Sud-Est et en Australie. La Mongolie est l’une de ses principales régions de nidification : des colonies existent au lac Orog, au lac Ögii, à Böön Tsagaan, au lac Buir et dans la vallée de Khurkh.",
    f: ["Long bec droit entièrement noir.", "Tête et dessous rouge brique en été.", "Se nourrit d’un mouvement de machine à coudre.", "Plus petit que la Barge à queue noire."],
    si: "Barge à queue noire — plus grande, bec rose à la base, barre alaire marquée.",
    h: "Lacs peu profonds et prairies humides.",
    di: "Lac Orog, lac Ögii, Böön Tsagaan, lac Buir, Khurkh, Mongol Daguur.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Vers et larves d’insectes.",
    br: "Colonial dans les prairies humides ; 2 ou 3 œufs.",
    be: "Sonde verticalement, vite et à répétition.",
    v: "Un « tchèp-tchèp » glapissant.",
    cu: "L’un des limicoles les moins connus d’Asie.",
    co: "Quasi menacé.",
    w: "Lac Orog en juin.",
    bt: "mai–juin",
    fa: ["La Mongolie est un site de nidification clé.", "Sonde comme une machine à coudre.", "Quasi menacé."]
  },
  "long-billed-dowitcher": {
    name: "Bécassin à long bec",
    s: "Limicole trapu, rappelant une bécassine, au très long bec et au coin blanc sur le dos. Migrateur rare dans l’est de la Mongolie.",
    d: "Le Bécassin à long bec niche dans le nord-est de la Sibérie et en Alaska et hiverne dans les Amériques. On compte quelques mentions au lac Buir et au lac Ögii.",
    f: ["Très long bec droit.", "Dessous rouille en été.", "Coin blanc sur le dos en vol.", "Queue barrée."],
    si: "Bécassin d’Asie — plus grand, sans coin blanc dorsal. Bécassine des marais — tête rayée.",
    h: "Mares d’eau douce peu profondes.",
    di: "Rare ; lac Buir, lac Ögii.",
    mi: "Migrateur rare, juillet–août.",
    fo: "Vers et larves d’insectes.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Se nourrit en machine à coudre.",
    v: "Un « kiik » aigu.",
    cu: "Surtout un oiseau américain.",
    co: "Préoccupation mineure.",
    w: "Vérifiez les bécassins au lac Buir.",
    bt: "août",
    fa: ["Coin blanc sur le dos.", "Très long bec.", "Hiverne dans les Amériques."]
  },
  "eurasian-woodcock": {
    name: "Bécasse des bois",
    s: "Limicole forestier dodu au camouflage parfait, au long bec et aux yeux placés haut sur la tête. Visiteur d’été des forêts du nord.",
    d: "La Bécasse des bois niche dans les forêts humides d’Eurasie. Ses yeux lui offrent une vision de presque 360 degrés. Au crépuscule, les mâles effectuent la « croule » au-dessus des arbres. En Mongolie, elle niche dans les forêts du Khentii et se voit en migration, jusqu’à Oulan-Bator et dans les oasis du Gobi.",
    f: ["Dodue, motif de feuille morte.", "Long bec droit.", "Barres sombres sur la calotte.", "Grands yeux placés en arrière.", "Ailes larges et arrondies."],
    si: "Bécassines — calotte rayée, zones humides ouvertes.",
    h: "Forêts humides avec clairières.",
    di: "Khentii (Terelj, Khurkh), Oulan-Bator, Dornod, oasis du Gobi.",
    mi: "Visiteuse d’été et migratrice, avril–octobre.",
    fo: "Vers de terre et larves d’insectes.",
    br: "Niche au sol en forêt ; 4 œufs.",
    be: "Vols de croule au crépuscule.",
    v: "Grognements et un « tsiouik » aigu pendant la croule.",
    cu: "Pourrait transporter ses poussins entre ses pattes en vol.",
    co: "Préoccupation mineure.",
    w: "Forêts de Terelj au crépuscule en mai.",
    bt: "mai–juin",
    fa: ["Vision de presque 360°.", "Camouflée comme des feuilles mortes.", "Parade au crépuscule."]
  },
  "solitary-snipe": {
    name: "Bécassine solitaire",
    s: "Grande bécassine sombre des torrents de montagne, qui reste même l’hiver près des sources non gelées. Espèce peu commune des montagnes mongoles.",
    d: "La Bécassine solitaire niche le long des torrents de montagne, de l’Asie centrale au Kamtchatka, et descend dans les vallées en hiver. Elle vit seule le long des cours d’eau froids et rapides. En Mongolie, on la trouve dans l’Altaï, le Khangaï et le Khentii, y compris près d’Oulan-Bator et de Khustai en hiver.",
    f: ["Grande bécassine sombre.", "Raies blanches sur la face et le dos.", "Poitrine rouille.", "Long bec."],
    si: "Bécassine des marais — plus petite, plus pâle, ventre blanc.",
    h: "Torrents de montagne et sources.",
    di: "Altaï, Khangaï, Khentii, Khustai, Oulan-Bator.",
    mi: "Résidente ; gagne les sources non gelées en hiver.",
    fo: "Larves d’insectes et vers.",
    br: "Niche près des torrents de montagne.",
    be: "Solitaire ; reste cachée.",
    v: "Un « pèntch » enroué.",
    cu: "L’un des rares limicoles à hiverner en Mongolie.",
    co: "Préoccupation mineure.",
    w: "Sources non gelées en hiver.",
    bt: "oct.–mars",
    fa: ["Hiverne en Mongolie.", "Vit seule.", "Aime les torrents froids."]
  },
  "pintail-snipe": {
    name: "Bécassine à queue pointue",
    s: "Bécassine aux rectrices externes en épingle et sans bord blanc à l’arrière de l’aile. Visiteuse d’été et migratrice.",
    d: "La Bécassine à queue pointue niche en Sibérie et dans le nord de la Mongolie et hiverne en Asie du Sud. Elle est presque identique à la Bécassine de Swinhoe. En Mongolie, on la voit dans la vallée de Khurkh, au lac Ögii et au lac Khar Us.",
    f: ["Rectrices externes très fines, en épingle.", "Pas de bord blanc à l’arrière de l’aile.", "Tête rayée.", "Bec plus court que la Bécassine des marais."],
    si: "Bécassine des marais — bord de fuite blanc. Bécassine de Swinhoe — très semblable.",
    h: "Prairies humides et marais.",
    di: "Khurkh, lac Ögii, lac Khar Us, Oulan-Bator.",
    mi: "Visiteuse d’été et migratrice, mai–septembre ; pic en août.",
    fo: "Vers et insectes.",
    br: "Niche dans les prairies humides.",
    be: "S’envole en silence ou avec un cri rauque.",
    v: "Un court « squik ».",
    cu: "Nommée pour ses rectrices en épingle.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en août.",
    bt: "août",
    fa: ["Rectrices en épingle.", "Difficile à identifier.", "Hiverne en Asie du Sud."]
  },
  "swinhoes-snipe": {
    name: "Bécassine de Swinhoe",
    s: "Grande bécassine qui niche dans les prairies de la steppe boisée et effectue une parade bourdonnante. Visiteuse d’été du nord de la Mongolie.",
    d: "La Bécassine de Swinhoe niche dans le centre-sud de la Sibérie et le nord de la Mongolie et hiverne en Asie du Sud-Est. En Mongolie, elle niche dans les prairies de lisière du Khentii — surtout la vallée de Khurkh et Terelj.",
    f: ["Grande bécassine à long bec.", "Tête rayée.", "Pas de bord blanc à l’arrière de l’aile.", "Nombreuses rectrices externes."],
    si: "Bécassine à queue pointue — un peu plus petite ; très difficile à distinguer.",
    h: "Prairies et lisières forestières.",
    di: "Khentii (Khurkh, Terelj), lac Ögii, lac Buir, lac Orog.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Vers et insectes.",
    br: "Niche dans les prairies proches des forêts.",
    be: "Parade avec un piqué bourdonnant.",
    v: "Un chant crépitant en parade.",
    cu: "Nommée d’après Robert Swinhoe.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Parade avec un piqué bourdonnant.", "Porte le nom de Swinhoe.", "Niche près des forêts."]
  },
  "common-snipe": {
    name: "Bécassine des marais",
    s: "Limicole cryptique au très long bec et à la tête rayée ; les mâles « chevrotent » avec leurs rectrices en parade. Commune dans les zones humides mongoles.",
    d: "La Bécassine des marais niche dans tout le nord de l’Eurasie. En parade, le mâle pique et ses rectrices externes vibrent en produisant un chevrotement. En Mongolie, elle niche dans les marais et prairies humides de tout le pays, surtout dans la vallée de Khurkh.",
    f: ["Très long bec droit.", "Tête et dos rayés.", "Ventre blanc.", "Bord de fuite blanc à l’aile.", "Vol en zigzag à l’envol."],
    si: "Bécassines à queue pointue et de Swinhoe — sans bord de fuite blanc. Bécassine sourde — plus petite, bec court.",
    h: "Marais et prairies humides.",
    di: "Toutes les régions : Khurkh, lac Ögii, lac Orog, Oulan-Bator, lac Buir, lac Khar Us.",
    mi: "Visiteuse d’été, avril–octobre.",
    fo: "Vers et larves d’insectes.",
    br: "Niche dans les touffes ; 4 œufs.",
    be: "Vols de parade chevrotants.",
    v: "Un « scaap » rauque à l’envol.",
    cu: "Son chevrotement lui vaut le surnom de « chèvre volante ».",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en mai.",
    bt: "mai–août",
    fa: ["Chevrote avec sa queue.", "Très long bec.", "Vol en zigzag."]
  },
  "jack-snipe": {
    name: "Bécassine sourde",
    s: "Petite bécassine discrète au bec court, qui se balance en se nourrissant. Migratrice très rare avec une seule mention GBIF.",
    d: "La Bécassine sourde niche dans les tourbières du nord et hiverne en Europe, en Afrique et en Asie du Sud. Elle reste immobile jusqu’à ce qu’on marche presque dessus. Une mention au lac Buir est l’une des très rares en Mongolie.",
    f: ["Petite, bec court.", "Sourcil fendu, sans raie médiane sur la calotte.", "Dos brillant vert-pourpre.", "Se balance de haut en bas."],
    si: "Bécassine des marais — plus grande, bec plus long.",
    h: "Tourbières et bords de marais.",
    di: "Très rare ; lac Buir.",
    mi: "Migratrice rare.",
    fo: "Insectes et vers.",
    br: "Niche dans les tourbières du nord (pas en Mongolie).",
    be: "S’envole silencieusement au dernier moment.",
    v: "Surtout silencieuse.",
    cu: "Sa parade évoque le galop d’un cheval.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Se balance en se nourrissant.", "Reste immobile.", "Très rare en Mongolie."]
  }
});
