B2T("en", {
  "terek-sandpiper": {
    T: { c: { gray: 0.45, white: 0.35, brown: 0.1, yellow: 0.1 }, hb: ["water"], bk: "curved", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["22–25 cm", "57–59 cm", "50–125 g"] },
    s: "A grey sandpiper with short orange legs and a long, upturned bill that dashes after prey. A regular migrant, especially in August.",
    d: "The Terek Sandpiper breeds along rivers in the northern taiga from Finland to eastern Siberia and winters on tropical coasts. In Mongolia it passes in May and August at Ögii Nuur, Buir Nuur, Khar Us Nuur and Böön Tsagaan.",
    f: ["Long, upturned black bill with a yellow base.", "Short orange-yellow legs.", "Grey upperparts with a dark shoulder line.", "White trailing edge to the wing."],
    si: "Common Sandpiper — straight bill, bobbing. Common Greenshank — larger, longer legs.",
    h: "Muddy lake shores.",
    di: "Ögii Nuur, Buir Nuur, Khar Us Nuur, Böön Tsagaan, Mongol Daguur.",
    mi: "Passage migrant, May and July–August.",
    fo: "Insects and crustaceans.",
    br: "Nests on northern river banks (not in Mongolia).",
    be: "Runs fast and erratically after prey.",
    v: "A fluty ‘tu-tu-tu’.",
    cu: "Named after the Terek River in the Caucasus.",
    co: "Least Concern.",
    w: "Ögii Nuur in August.",
    bt: "August",
    fa: ["Upturned bill.", "Short orange legs.", "Named after a Caucasian river."]
  },
  "common-sandpiper": {
    T: { c: { brown: 0.5, white: 0.4, gray: 0.1 }, hb: ["water", "mountain"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["18–21 cm", "32–35 cm", "33–84 g"] },
    s: "A small brown-and-white sandpiper that constantly bobs its tail and flies low with flickering wings. Breeds along rivers and lakes throughout Mongolia.",
    d: "The Common Sandpiper breeds across Eurasia along stony rivers and lakes. It bobs its rear end almost non-stop. In Mongolia it is widespread from May to September — along the Tuul River in Ulaanbaatar, at Ögii Nuur, the Khurkh valley and Terelj.",
    f: ["Brown upperparts; white underparts with a white ‘notch’ in front of the wing.", "Constant tail-bobbing.", "Flies low with stiff, flickering wingbeats.", "White wing bar."],
    si: "Green Sandpiper — darker, white rump, no bobbing. Wood Sandpiper — spotted back.",
    h: "Stony rivers and lake shores.",
    di: "All regions: Ulaanbaatar (Tuul River), Ögii Nuur, Khurkh, Terelj, Buir Nuur, Böön Tsagaan.",
    mi: "Summer visitor, April–October.",
    fo: "Insects and small invertebrates.",
    br: "Nests on the ground near water; 4 eggs.",
    be: "Bobs constantly; flies low over water.",
    v: "A high ‘swee-swee-swee’.",
    cu: "Its bobbing may help it spot prey.",
    co: "Least Concern.",
    w: "Tuul River banks in Ulaanbaatar in summer.",
    bt: "May–August",
    fa: ["Always bobbing.", "Flies with flickering wings.", "Common along rivers."]
  },
  "green-sandpiper": {
    T: { c: { brown: 0.5, white: 0.4, black: 0.1 }, hb: ["water", "forest"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["21–24 cm", "57–61 cm", "53–119 g"] },
    s: "A dark-backed sandpiper with a gleaming white rump, like a large House Martin in flight. Nests in old thrush nests in trees.",
    d: "The Green Sandpiper breeds in wet forests across northern Eurasia and, unusually for a wader, lays its eggs in old nests of other birds in trees. In Mongolia it breeds in the northern forests and is common on migration from July to September in all regions.",
    f: ["Dark olive-brown back with fine pale spots.", "Brilliant white rump and tail with a few dark bars.", "Blackish underwings.", "Greenish legs."],
    si: "Wood Sandpiper — paler, more spotted back, pale underwings.",
    h: "Streams, ponds and forest pools.",
    di: "Ögii Nuur, Ulaanbaatar, Khurkh, Khar Us Nuur, Buir Nuur, Khustai.",
    mi: "Summer visitor and migrant, April–October; peak in August.",
    fo: "Insects and small invertebrates.",
    br: "Uses old thrush nests in trees; 4 eggs.",
    be: "Flies off with a loud call when disturbed.",
    v: "A ringing ‘tluit-weet-weet’.",
    cu: "Nesting in trees is rare among waders.",
    co: "Least Concern.",
    w: "Streams in Ulaanbaatar in August.",
    bt: "July–August",
    fa: ["Nests in trees.", "Bright white rump.", "Dark underwings."]
  },
  "grey-tailed-tattler": {
    T: { c: { gray: 0.6, white: 0.35, yellow: 0.05 }, hb: ["water", "mountain"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["24–27 cm", "60–65 cm", "80–180 g"] },
    s: "A plain grey sandpiper with short yellow legs and a white eyebrow. A scarce migrant, mostly in the north and east.",
    d: "The Grey-tailed Tattler breeds along stony mountain rivers in north-east Siberia and winters on coasts of South-East Asia and Australia. In Mongolia it passes in May and August at Buir Nuur, Ögii Nuur, the Khurkh valley and Böön Tsagaan.",
    f: ["Plain grey upperparts.", "Short yellow legs.", "White eyebrow.", "Fine grey barring below in summer."],
    si: "Common Greenshank — larger, longer greenish legs.",
    h: "Stony shores.",
    di: "Buir Nuur, Ögii Nuur, Khurkh, Böön Tsagaan.",
    mi: "Passage migrant, May and August.",
    fo: "Insects and crustaceans.",
    br: "Nests on Siberian mountain rivers (not in Mongolia).",
    be: "Bobs like a Common Sandpiper.",
    v: "A rising ‘tu-weet’.",
    cu: "‘Tattler’ refers to its warning calls.",
    co: "Least Concern.",
    w: "Buir Nuur in May.",
    bt: "May, August",
    fa: ["Plain grey.", "Yellow legs.", "Winters in Australia."]
  },
  "wandering-tattler": {
    T: { c: { gray: 0.65, white: 0.3, yellow: 0.05 }, hb: ["water", "mountain"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["26–29 cm", "65 cm", "90–210 g"] },
    s: "A dark grey tattler of Pacific rocky coasts. On the Mongolian list, with no GBIF records.",
    d: "The Wandering Tattler breeds on mountain streams in Alaska and north-east Siberia and winters on Pacific islands. A record in Mongolia would be exceptional.",
    f: ["Dark slate-grey upperparts.", "Heavily barred underparts in summer.", "Short yellow legs."],
    si: "Grey-tailed Tattler — paler, finer barring.",
    h: "Rocky shores.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Invertebrates.",
    br: "Nests in Arctic mountains (not in Mongolia).",
    be: "Bobs and teeters.",
    v: "A rippling trill.",
    cu: "Wanders across the Pacific to remote islands.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Winters on Pacific islands.", "Dark grey.", "Exceptional in Mongolia."]
  },
  "spotted-redshank": {
    T: { c: { black: 0.45, white: 0.3, gray: 0.15, red: 0.1 }, hb: ["water"], bk: "long", bh: ["walk", "swim"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["29–32 cm", "61–67 cm", "110–200 g"] },
    s: "An elegant wader that is sooty-black with white spots in summer, with long red legs and a fine bill. A common migrant on Mongolian lakes.",
    d: "The Spotted Redshank breeds in the far north of Eurasia and winters from the Mediterranean to South-East Asia. It often wades belly-deep and even swims. In Mongolia it passes in May and July–September at Ögii Nuur, Buir Nuur and the Khurkh valley.",
    f: ["Summer: almost all black with white spots.", "Long, dark red legs.", "Long, thin bill with a red base.", "White wedge up the back in flight.", "Winter: pale grey with a white eyebrow."],
    si: "Common Redshank — shorter legs, orange-red bill base, white wing trailing edge.",
    h: "Shallow lakes and pools.",
    di: "Ögii Nuur, Buir Nuur, Khurkh, Böön Tsagaan, Mongol Daguur.",
    mi: "Passage migrant, May and July–September.",
    fo: "Insects, shrimps and small fish.",
    br: "Nests in northern forest bogs (not in Mongolia).",
    be: "Feeds in groups, often wading deep.",
    v: "A clear ‘chew-it’.",
    cu: "Males incubate the eggs while females leave early.",
    co: "Least Concern.",
    w: "Ögii Nuur in May and August.",
    bt: "May, August",
    fa: ["Black in summer.", "Wades belly-deep.", "Males incubate."]
  },
  "common-greenshank": {
    T: { c: { gray: 0.5, white: 0.4, black: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["30–35 cm", "68–70 cm", "130–270 g"] },
    s: "A tall, grey wader with long greenish legs and a slightly upturned bill. A common migrant on lakes and rivers.",
    d: "The Common Greenshank breeds in northern bogs and winters from Africa to Australia. In Mongolia it passes in May and July–September in all regions, especially Ögii Nuur, the Khurkh valley and Buir Nuur.",
    f: ["Grey upperparts, white underparts.", "Long greenish legs.", "Slightly upturned grey bill.", "White wedge up the back in flight."],
    si: "Marsh Sandpiper — smaller, needle-thin bill. Common Redshank — red legs.",
    h: "Lake shores, rivers and marshes.",
    di: "Ögii Nuur, Khurkh, Buir Nuur, Orog Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and July–October.",
    fo: "Insects, small fish and tadpoles.",
    br: "Nests in northern bogs (not in Mongolia).",
    be: "Chases small fish in shallow water.",
    v: "A ringing ‘tew-tew-tew’.",
    cu: "Its call is one of the most familiar wader sounds.",
    co: "Least Concern.",
    w: "Any lake in August.",
    bt: "May, August",
    fa: ["Green legs.", "Slightly upturned bill.", "Loud triple call."]
  },
  "common-redshank": {
    T: { c: { brown: 0.45, white: 0.35, gray: 0.1, red: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["24–27 cm", "59–66 cm", "85–155 g"] },
    s: "A noisy brown wader with bright orange-red legs and a broad white trailing edge to the wing. The ‘sentinel’ of Mongolian wet meadows.",
    d: "The Common Redshank breeds across Eurasia. It is very alert and gives loud alarm calls that warn other birds. In Mongolia it is one of the most common breeding waders, in wet meadows at Ögii Nuur, the Khurkh valley, Ulaanbaatar and Böön Tsagaan.",
    f: ["Bright orange-red legs.", "Red base to the bill.", "Brown, streaked upperparts.", "Broad white trailing edge to the wing in flight.", "Perches on posts and calls."],
    si: "Spotted Redshank — longer legs, black in summer, no white wing edge. Ruff — no red legs usually, scaly back.",
    h: "Wet meadows, marshes and lake shores.",
    di: "All regions: Ögii Nuur, Khurkh, Ulaanbaatar, Böön Tsagaan, Orog Nuur, Buir Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Insects, worms and crustaceans.",
    br: "Nests in grass tussocks; 4 eggs.",
    be: "Alarm-calls loudly from posts.",
    v: "A loud ‘teu-hu-hu’.",
    cu: "Known as the ‘warden of the marsh’.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "May–July",
    fa: ["Warns other birds of danger.", "Red legs.", "White wing edge."]
  },
  "wood-sandpiper": {
    T: { c: { brown: 0.5, white: 0.4, buff: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage", "summer"], sz: ["19–21 cm", "56–57 cm", "50–90 g"] },
    s: "A slim, spangled sandpiper with a white eyebrow and yellowish legs. One of the most common migrant waders in Mongolia.",
    d: "The Wood Sandpiper breeds in northern bogs and winters in Africa and South Asia. In Mongolia it may breed in the north and is abundant on migration in May and July–August at Ögii Nuur, Buir Nuur, the Khurkh valley and Ulaanbaatar.",
    f: ["Brown back spangled with white spots.", "Clear white eyebrow.", "Yellowish legs.", "White rump; pale underwings."],
    si: "Green Sandpiper — darker, black underwings. Common Redshank — red legs.",
    h: "Marshes, pools and wet meadows.",
    di: "Ögii Nuur, Buir Nuur, Khurkh, Ulaanbaatar, Böön Tsagaan, Orog Nuur.",
    mi: "Passage migrant, May and July–September.",
    fo: "Insects and larvae.",
    br: "Nests in northern bogs, sometimes in trees.",
    be: "Feeds in shallow freshwater.",
    v: "A dry ‘chiff-iff-iff’.",
    cu: "One of the most numerous Palearctic waders.",
    co: "Least Concern.",
    w: "Any marsh in August.",
    bt: "May, August",
    fa: ["Spangled back.", "Yellowish legs.", "Very common migrant."]
  },
  "marsh-sandpiper": {
    T: { c: { gray: 0.5, white: 0.4, black: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["22–26 cm", "55–59 cm", "55–120 g"] },
    s: "A dainty, long-legged grey wader with a needle-thin bill. Breeds in steppe marshes of Mongolia.",
    d: "The Marsh Sandpiper breeds in the steppe marshes of eastern Europe and Asia and winters in Africa, South Asia and Australia. In Mongolia it breeds at Ögii Nuur, the Khurkh valley and Buir Nuur and is common from May to August.",
    f: ["Very thin, straight bill.", "Long greenish legs.", "Pale grey with dark spots in summer.", "White wedge up the back."],
    si: "Common Greenshank — larger, thicker upturned bill.",
    h: "Steppe marshes and shallow lakes.",
    di: "Ögii Nuur, Khurkh, Buir Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and small crustaceans.",
    br: "Nests in marshy grassland; 4 eggs.",
    be: "Picks food delicately from the surface.",
    v: "A high ‘kyew’.",
    cu: "Looks like a miniature greenshank.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "May–July",
    fa: ["Needle-thin bill.", "Long legs.", "Breeds in Mongolia."]
  },
  "red-necked-phalarope": {
    T: { c: { gray: 0.4, white: 0.3, rufous: 0.2, black: 0.1 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["18–19 cm", "31–34 cm", "30–48 g"] },
    s: "A tiny wader that swims and spins on the water; the female is more colourful than the male. A common migrant on Mongolian lakes.",
    d: "The Red-necked Phalarope breeds on Arctic tundra and winters at sea. Females court the males and leave them to incubate. On lakes it spins in circles to bring food to the surface. In Mongolia it passes mainly in August at Ögii Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["Female: grey head, white throat, red neck band.", "Male: duller.", "Needle-thin black bill.", "Swims buoyantly; spins in circles.", "Winter: grey and white with a black eye patch."],
    si: "Grey Phalarope — thicker bill, reddish underparts in summer.",
    h: "Lakes, especially saline ones.",
    di: "Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khar Us Nuur.",
    mi: "Passage migrant, May and August–September.",
    fo: "Plankton and insects.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Spins on the water to stir up food.",
    v: "A sharp ‘kip’.",
    cu: "Roles reversed: the male incubates the eggs.",
    co: "Least Concern.",
    w: "Ögii Nuur in August.",
    bt: "August",
    fa: ["Spins on the water.", "Female more colourful.", "Male incubates."]
  },
  "grey-phalarope": {
    T: { c: { gray: 0.4, rufous: 0.3, white: 0.2, black: 0.1 }, hb: ["water"], bk: "short", bh: ["swim"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["20–22 cm", "40–44 cm", "50–75 g"] },
    s: "A plump phalarope that is brick-red in summer and pale grey in winter, with a thick bill. A rare migrant in Mongolia.",
    d: "The Grey (Red) Phalarope breeds in the high Arctic and spends the winter far out at sea. In Mongolia it is a rare autumn migrant, with records at Khar Us Nuur.",
    f: ["Summer: brick-red underparts, white face.", "Thick, yellow-based bill.", "Winter: pale grey with a black eye patch.", "Swims and spins."],
    si: "Red-necked Phalarope — needle bill, smaller.",
    h: "Lakes on migration; open sea in winter.",
    di: "Rare; Khar Us Nuur.",
    mi: "Rare migrant, June and September–October.",
    fo: "Plankton.",
    br: "Nests in the high Arctic (not in Mongolia).",
    be: "Spins on the water.",
    v: "A sharp ‘pik’.",
    cu: "Called ‘Red Phalarope’ in North America.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Grey in winter, red in summer.", "Winters at sea.", "Male incubates."]
  }
});
