B2T("fr", {
  "terek-sandpiper": {
    name: "Chevalier bargette",
    s: "Chevalier gris aux courtes pattes orange et au long bec retroussé, qui court après ses proies. Migrateur régulier, surtout en août.",
    d: "Le Chevalier bargette niche le long des rivières de la taïga septentrionale, de la Finlande à la Sibérie orientale, et hiverne sur les côtes tropicales. En Mongolie, il passe en mai et en août au lac Ögii, au lac Buir, au lac Khar Us et à Böön Tsagaan.",
    f: ["Long bec noir retroussé à base jaune.", "Courtes pattes jaune orangé.", "Dessus gris avec une ligne scapulaire sombre.", "Bord de fuite blanc à l’aile."],
    si: "Chevalier guignette — bec droit, hoche la queue. Chevalier aboyeur — plus grand, pattes plus longues.",
    h: "Rives vaseuses.",
    di: "Lac Ögii, lac Buir, lac Khar Us, Böön Tsagaan, Mongol Daguur.",
    mi: "Migrateur, mai et juillet–août.",
    fo: "Insectes et crustacés.",
    br: "Niche sur les berges des rivières du nord (pas en Mongolie).",
    be: "Court vite et de façon erratique après ses proies.",
    v: "Un « tou-tou-tou » flûté.",
    cu: "Son nom anglais vient du fleuve Terek, dans le Caucase.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en août.",
    bt: "août",
    fa: ["Bec retroussé.", "Courtes pattes orange.", "Nommé d’après un fleuve du Caucase."]
  },
  "common-sandpiper": {
    name: "Chevalier guignette",
    s: "Petit chevalier brun et blanc qui hoche sans cesse la queue et vole bas à battements saccadés. Niche le long des rivières et lacs de toute la Mongolie.",
    d: "Le Chevalier guignette niche en Eurasie le long des rivières et lacs pierreux. Il hoche l’arrière du corps presque sans arrêt. En Mongolie, il est répandu de mai à septembre — le long de la Tuul à Oulan-Bator, au lac Ögii, dans la vallée de Khurkh et à Terelj.",
    f: ["Dessus brun ; dessous blanc avec une « encoche » blanche devant l’aile.", "Hochements de queue constants.", "Vol bas à battements raides et saccadés.", "Barre alaire blanche."],
    si: "Chevalier cul-blanc — plus sombre, croupion blanc, ne hoche pas. Chevalier sylvain — dos tacheté.",
    h: "Rivières pierreuses et rives de lacs.",
    di: "Toutes les régions : Oulan-Bator (Tuul), lac Ögii, Khurkh, Terelj, lac Buir, Böön Tsagaan.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Insectes et petits invertébrés.",
    br: "Niche au sol près de l’eau ; 4 œufs.",
    be: "Hoche constamment ; vole au ras de l’eau.",
    v: "Un « suii-suii-suii » aigu.",
    cu: "Ses hochements l’aideraient à repérer ses proies.",
    co: "Préoccupation mineure.",
    w: "Rives de la Tuul à Oulan-Bator en été.",
    bt: "mai–août",
    fa: ["Hoche toujours la queue.", "Vol saccadé.", "Commun le long des rivières."]
  },
  "green-sandpiper": {
    name: "Chevalier cul-blanc",
    s: "Chevalier au dos sombre et au croupion d’un blanc éclatant, rappelant une grande hirondelle de fenêtre en vol. Pond dans de vieux nids de grives dans les arbres.",
    d: "Le Chevalier cul-blanc niche dans les forêts humides du nord de l’Eurasie et, fait rare chez un limicole, pond dans d’anciens nids d’autres oiseaux dans les arbres. En Mongolie, il niche dans les forêts du nord et passe en nombre de juillet à septembre dans toutes les régions.",
    f: ["Dos brun olive foncé finement piqueté de pâle.", "Croupion et queue blanc brillant à quelques barres sombres.", "Dessous des ailes noirâtre.", "Pattes verdâtres."],
    si: "Chevalier sylvain — plus pâle, dos plus tacheté, dessous des ailes pâle.",
    h: "Ruisseaux, étangs et mares forestières.",
    di: "Lac Ögii, Oulan-Bator, Khurkh, lac Khar Us, lac Buir, Khustai.",
    mi: "Visiteur d’été et migrateur, avril–octobre ; pic en août.",
    fo: "Insectes et petits invertébrés.",
    br: "Utilise de vieux nids de grives dans les arbres ; 4 œufs.",
    be: "S’envole en criant fort quand on le dérange.",
    v: "Un « tlouit-ouit-ouit » sonore.",
    cu: "Nicher dans les arbres est rare chez les limicoles.",
    co: "Préoccupation mineure.",
    w: "Ruisseaux d’Oulan-Bator en août.",
    bt: "juil.–août",
    fa: ["Niche dans les arbres.", "Croupion blanc éclatant.", "Dessous des ailes sombre."]
  },
  "grey-tailed-tattler": {
    name: "Chevalier de Sibérie",
    s: "Chevalier gris uni aux courtes pattes jaunes et au sourcil blanc. Migrateur peu commun, surtout dans le nord et l’est.",
    d: "Le Chevalier de Sibérie niche le long des rivières caillouteuses des montagnes du nord-est de la Sibérie et hiverne sur les côtes d’Asie du Sud-Est et d’Australie. En Mongolie, il passe en mai et en août au lac Buir, au lac Ögii, dans la vallée de Khurkh et à Böön Tsagaan.",
    f: ["Dessus gris uni.", "Courtes pattes jaunes.", "Sourcil blanc.", "Fines barres grises dessous en été."],
    si: "Chevalier aboyeur — plus grand, longues pattes verdâtres.",
    h: "Rives caillouteuses.",
    di: "Lac Buir, lac Ögii, Khurkh, Böön Tsagaan.",
    mi: "Migrateur, mai et août.",
    fo: "Insectes et crustacés.",
    br: "Niche sur les rivières de montagne sibériennes (pas en Mongolie).",
    be: "Hoche comme un Chevalier guignette.",
    v: "Un « tou-ouiit » montant.",
    cu: "Son nom anglais « tattler » évoque ses cris d’alarme.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en mai.",
    bt: "mai, août",
    fa: ["Gris uni.", "Pattes jaunes.", "Hiverne en Australie."]
  },
  "wandering-tattler": {
    name: "Chevalier errant",
    s: "Chevalier gris foncé des côtes rocheuses du Pacifique. Sur la liste mongole, sans mention GBIF.",
    d: "Le Chevalier errant niche sur les torrents de montagne d’Alaska et du nord-est de la Sibérie et hiverne sur les îles du Pacifique. Une mention en Mongolie serait exceptionnelle.",
    f: ["Dessus gris ardoise foncé.", "Dessous fortement barré en été.", "Courtes pattes jaunes."],
    si: "Chevalier de Sibérie — plus pâle, barres plus fines.",
    h: "Côtes rocheuses.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Invertébrés.",
    br: "Niche dans les montagnes arctiques (pas en Mongolie).",
    be: "Hoche et se balance.",
    v: "Un trille roulé.",
    cu: "Traverse le Pacifique jusqu’à des îles lointaines.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Hiverne sur les îles du Pacifique.", "Gris foncé.", "Exceptionnel en Mongolie."]
  },
  "spotted-redshank": {
    name: "Chevalier arlequin",
    s: "Élégant limicole noir de suie piqueté de blanc en été, aux longues pattes rouges et au bec fin. Migrateur commun sur les lacs mongols.",
    d: "Le Chevalier arlequin niche dans l’extrême nord de l’Eurasie et hiverne de la Méditerranée à l’Asie du Sud-Est. Il patauge souvent jusqu’au ventre et nage même. En Mongolie, il passe en mai et juillet–septembre au lac Ögii, au lac Buir et dans la vallée de Khurkh.",
    f: ["Été : presque entièrement noir piqueté de blanc.", "Longues pattes rouge sombre.", "Long bec fin à base rouge.", "Coin blanc sur le dos en vol.", "Hiver : gris pâle avec un sourcil blanc."],
    si: "Chevalier gambette — pattes plus courtes, base du bec rouge orangé, bord de fuite blanc.",
    h: "Lacs et mares peu profonds.",
    di: "Lac Ögii, lac Buir, Khurkh, Böön Tsagaan, Mongol Daguur.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Insectes, crevettes et petits poissons.",
    br: "Niche dans les tourbières forestières du nord (pas en Mongolie).",
    be: "Se nourrit en groupe, souvent en eau profonde.",
    v: "Un « tchiou-it » clair.",
    cu: "Le mâle couve les œufs tandis que la femelle part tôt.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai et août.",
    bt: "mai, août",
    fa: ["Noir en été.", "Patauge jusqu’au ventre.", "Le mâle couve."]
  },
  "common-greenshank": {
    name: "Chevalier aboyeur",
    s: "Grand limicole gris aux longues pattes verdâtres et au bec légèrement retroussé. Migrateur commun sur les lacs et rivières.",
    d: "Le Chevalier aboyeur niche dans les tourbières du nord et hiverne de l’Afrique à l’Australie. En Mongolie, il passe en mai et juillet–septembre dans toutes les régions, surtout au lac Ögii, dans la vallée de Khurkh et au lac Buir.",
    f: ["Dessus gris, dessous blanc.", "Longues pattes verdâtres.", "Bec gris légèrement retroussé.", "Coin blanc sur le dos en vol."],
    si: "Chevalier stagnatile — plus petit, bec fin comme une aiguille. Chevalier gambette — pattes rouges.",
    h: "Rives de lacs, rivières et marais.",
    di: "Lac Ögii, Khurkh, lac Buir, lac Orog, lac Khar Us.",
    mi: "Migrateur, mai et juillet–octobre.",
    fo: "Insectes, petits poissons et têtards.",
    br: "Niche dans les tourbières du nord (pas en Mongolie).",
    be: "Poursuit les petits poissons en eau peu profonde.",
    v: "Un « tiou-tiou-tiou » sonore.",
    cu: "Son cri est l’un des sons de limicole les plus familiers.",
    co: "Préoccupation mineure.",
    w: "N’importe quel lac en août.",
    bt: "mai, août",
    fa: ["Pattes vertes.", "Bec légèrement retroussé.", "Triple cri sonore."]
  },
  "common-redshank": {
    name: "Chevalier gambette",
    s: "Limicole brun bruyant aux pattes rouge orangé vif et au large bord de fuite blanc. La « sentinelle » des prairies humides mongoles.",
    d: "Le Chevalier gambette niche dans toute l’Eurasie. Très vigilant, il lance de forts cris d’alarme qui alertent les autres oiseaux. En Mongolie, c’est l’un des limicoles nicheurs les plus communs, dans les prairies humides du lac Ögii, de la vallée de Khurkh, d’Oulan-Bator et de Böön Tsagaan.",
    f: ["Pattes rouge orangé vif.", "Base du bec rouge.", "Dessus brun strié.", "Large bord de fuite blanc en vol.", "Se perche sur les piquets pour crier."],
    si: "Chevalier arlequin — pattes plus longues, noir en été, sans bord blanc. Combattant varié — pattes généralement pas rouges, dos écailleux.",
    h: "Prairies humides, marais et rives de lacs.",
    di: "Toutes les régions : lac Ögii, Khurkh, Oulan-Bator, Böön Tsagaan, lac Orog, lac Buir.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes, vers et crustacés.",
    br: "Niche dans les touffes d’herbe ; 4 œufs.",
    be: "Crie l’alarme depuis les piquets.",
    v: "Un « tiou-hou-hou » sonore.",
    cu: "Surnommé le « gardien du marais ».",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "mai–juil.",
    fa: ["Avertit les autres oiseaux du danger.", "Pattes rouges.", "Bord blanc à l’aile."]
  },
  "wood-sandpiper": {
    name: "Chevalier sylvain",
    s: "Chevalier élancé au dos pailleté, sourcil blanc et pattes jaunâtres. L’un des limicoles migrateurs les plus communs de Mongolie.",
    d: "Le Chevalier sylvain niche dans les tourbières du nord et hiverne en Afrique et en Asie du Sud. En Mongolie, il niche peut-être dans le nord et passe en abondance en mai et en juillet–août au lac Ögii, au lac Buir, dans la vallée de Khurkh et à Oulan-Bator.",
    f: ["Dos brun pailleté de taches blanches.", "Sourcil blanc net.", "Pattes jaunâtres.", "Croupion blanc ; dessous des ailes pâle."],
    si: "Chevalier cul-blanc — plus sombre, dessous des ailes noir. Chevalier gambette — pattes rouges.",
    h: "Marais, mares et prairies humides.",
    di: "Lac Ögii, lac Buir, Khurkh, Oulan-Bator, Böön Tsagaan, lac Orog.",
    mi: "Migrateur, mai et juillet–septembre.",
    fo: "Insectes et larves.",
    br: "Niche dans les tourbières du nord, parfois dans les arbres.",
    be: "Se nourrit en eau douce peu profonde.",
    v: "Un « tchiff-iff-iff » sec.",
    cu: "L’un des limicoles les plus nombreux du Paléarctique.",
    co: "Préoccupation mineure.",
    w: "N’importe quel marais en août.",
    bt: "mai, août",
    fa: ["Dos pailleté.", "Pattes jaunâtres.", "Migrateur très commun."]
  },
  "marsh-sandpiper": {
    name: "Chevalier stagnatile",
    s: "Limicole gris délicat aux longues pattes et au bec fin comme une aiguille. Niche dans les marais de la steppe mongole.",
    d: "Le Chevalier stagnatile niche dans les marais steppiques d’Europe de l’Est et d’Asie et hiverne en Afrique, en Asie du Sud et en Australie. En Mongolie, il niche au lac Ögii, dans la vallée de Khurkh et au lac Buir et il est commun de mai à août.",
    f: ["Bec droit très fin.", "Longues pattes verdâtres.", "Gris pâle taché de sombre en été.", "Coin blanc sur le dos."],
    si: "Chevalier aboyeur — plus grand, bec plus épais et retroussé.",
    h: "Marais steppiques et lacs peu profonds.",
    di: "Lac Ögii, Khurkh, lac Buir, Böön Tsagaan, lac Orog.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes et petits crustacés.",
    br: "Niche dans les prairies marécageuses ; 4 œufs.",
    be: "Cueille délicatement sa nourriture en surface.",
    v: "Un « kiou » aigu.",
    cu: "Ressemble à un Chevalier aboyeur en miniature.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "mai–juil.",
    fa: ["Bec fin comme une aiguille.", "Longues pattes.", "Niche en Mongolie."]
  },
  "red-necked-phalarope": {
    name: "Phalarope à bec étroit",
    s: "Minuscule limicole qui nage et tourne sur l’eau ; la femelle est plus colorée que le mâle. Migrateur commun sur les lacs mongols.",
    d: "Le Phalarope à bec étroit niche dans la toundra arctique et hiverne en mer. Les femelles courtisent les mâles et leur laissent l’incubation. Sur les lacs, il tourne en cercles pour faire remonter la nourriture. En Mongolie, il passe surtout en août au lac Ögii, à Böön Tsagaan et au lac Orog.",
    f: ["Femelle : tête grise, gorge blanche, bande rousse sur le cou.", "Mâle : plus terne.", "Bec noir fin comme une aiguille.", "Nage avec légèreté ; tourne en rond.", "Hiver : gris et blanc avec une tache noire à l’œil."],
    si: "Phalarope à bec large — bec plus épais, dessous roux en été.",
    h: "Lacs, surtout salés.",
    di: "Lac Ögii, Böön Tsagaan, lac Orog, lac Buir, lac Khar Us.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Plancton et insectes.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Tourne sur l’eau pour remuer la nourriture.",
    v: "Un « kip » sec.",
    cu: "Rôles inversés : le mâle couve les œufs.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en août.",
    bt: "août",
    fa: ["Tourne sur l’eau.", "La femelle est plus colorée.", "Le mâle couve."]
  },
  "grey-phalarope": {
    name: "Phalarope à bec large",
    s: "Phalarope dodu, rouge brique en été et gris pâle en hiver, au bec épais. Migrateur rare en Mongolie.",
    d: "Le Phalarope à bec large niche dans le haut Arctique et passe l’hiver en haute mer. En Mongolie, c’est un migrateur d’automne rare, noté au lac Khar Us.",
    f: ["Été : dessous rouge brique, face blanche.", "Bec épais à base jaune.", "Hiver : gris pâle avec une tache noire à l’œil.", "Nage et tourne."],
    si: "Phalarope à bec étroit — bec en aiguille, plus petit.",
    h: "Lacs en migration ; haute mer en hiver.",
    di: "Rare ; lac Khar Us.",
    mi: "Migrateur rare, juin et septembre–octobre.",
    fo: "Plancton.",
    br: "Niche dans le haut Arctique (pas en Mongolie).",
    be: "Tourne sur l’eau.",
    v: "Un « pik » sec.",
    cu: "Appelé « Phalarope roux » en Amérique du Nord.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Gris en hiver, roux en été.", "Hiverne en mer.", "Le mâle couve."]
  }
});
