B2T("en", {
  "grey-plover": {
    T: { c: { black: 0.4, white: 0.35, gray: 0.25 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["27–31 cm", "71–83 cm", "190–280 g"] },
    s: "A stout plover, spangled silver above and jet-black below in summer, with black ‘armpits’ in flight. A migrant on Mongolian lakes; now Vulnerable.",
    d: "The Grey Plover breeds on high Arctic tundra and winters on coasts worldwide. In Mongolia it passes in May and August–September, especially at Ögii Nuur, Buir Nuur, Böön Tsagaan and Khar Us Nuur.",
    f: ["Summer: black face and underparts, silver-spangled back.", "Black axillaries (‘armpits’) under the wing — diagnostic.", "White rump.", "Thick black bill.", "Winter: plain grey."],
    si: "Pacific Golden Plover — golden-spangled back, grey underwing, smaller bill.",
    h: "Lake shores and mudflats.",
    di: "Ögii Nuur, Buir Nuur, Böön Tsagaan, Khar Us Nuur, Orog Nuur.",
    mi: "Passage migrant, May and August–October.",
    fo: "Worms, molluscs and insects.",
    br: "Nests on Arctic tundra (not in Mongolia).",
    be: "Runs, stops and pecks like other plovers.",
    v: "A plaintive ‘tlee-oo-ee’.",
    cu: "Called ‘Black-bellied Plover’ in North America.",
    co: "Vulnerable.",
    w: "Ögii Nuur in May and August.",
    bt: "May, August",
    fa: ["Black ‘armpits’.", "Silver-spangled back.", "Globally Vulnerable."]
  },
  "pacific-golden-plover": {
    T: { c: { black: 0.35, yellow: 0.25, white: 0.2, brown: 0.2 }, hb: ["water", "steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["23–26 cm", "60–67 cm", "100–190 g"] },
    s: "A slim plover spangled with gold, black below in summer. Huge numbers stop over in eastern Mongolia in May.",
    d: "The Pacific Golden Plover breeds on Siberian and Alaskan tundra and winters from India to Australia and Pacific islands. In Mongolia, spectacular spring flocks gather in Dornod, especially in Mongol Daguur, and smaller numbers pass Ögii Nuur and Buir Nuur.",
    f: ["Back spangled with gold and black.", "Black face and belly in summer with a white border.", "Grey underwing.", "Slim, long-legged."],
    si: "Grey Plover — silver back, black ‘armpits’.",
    h: "Steppe, wet meadows and lake shores.",
    di: "Dornod (Mongol Daguur, Buir Nuur), Ögii Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Passage migrant, May and August–September.",
    fo: "Insects, worms and berries.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Feeds in large flocks on grassland.",
    v: "A clear ‘chu-ee’.",
    cu: "Flies non-stop from Alaska to Hawaii.",
    co: "Least Concern.",
    w: "Mongol Daguur in May.",
    bt: "May",
    fa: ["Gold-spangled back.", "Huge spring flocks in Dornod.", "Crosses the Pacific non-stop."]
  },
  "eurasian-dotterel": {
    T: { c: { rufous: 0.3, gray: 0.3, white: 0.2, black: 0.1, brown: 0.1 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["20–22 cm", "57–64 cm", "90–140 g"] },
    s: "A confiding mountain plover with a bold white eyebrow and a chestnut belly. Breeds on high plateaus in western and northern Mongolia.",
    d: "The Eurasian Dotterel breeds on mountain tops and Arctic tundra and winters in North Africa and the Middle East. The female is brighter and leaves the male to incubate. In Mongolia it breeds on alpine plateaus in the Altai, Khangai and Khövsgöl mountains.",
    f: ["Broad white eyebrows meeting at the nape.", "White breast band.", "Chestnut belly with a black centre.", "Very tame."],
    si: "Pacific Golden Plover — spangled back, no white eyebrow.",
    h: "Alpine plateaus and mountain tundra.",
    di: "Altai, Khangai, Khövsgöl, Achit Nuur area.",
    mi: "Summer visitor, May–August.",
    fo: "Insects and spiders.",
    br: "Nests on stony tundra; male incubates.",
    be: "Extremely tame.",
    v: "A soft ‘pwit’.",
    cu: "Its tameness gave it the name ‘dotterel’, meaning ‘little fool’.",
    co: "Least Concern.",
    w: "Alpine plateaus of the Altai in June.",
    bt: "June–July",
    fa: ["Male incubates.", "Very tame.", "Breeds on mountain tops."]
  },
  "common-ringed-plover": {
    T: { c: { brown: 0.4, white: 0.35, black: 0.2, yellow: 0.05 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["18–20 cm", "48–57 cm", "42–78 g"] },
    s: "A small, round plover with a black breast band, orange legs and an orange-based bill. A migrant on lake shores.",
    d: "The Common Ringed Plover breeds on Arctic and northern coasts and winters in Africa and Europe. In Mongolia it passes in May and July at Ögii Nuur, Khar Us Nuur and near Ulaanbaatar.",
    f: ["Black breast band and mask.", "Orange legs.", "Orange bill with a black tip.", "White wing bar in flight.", "No yellow eye-ring."],
    si: "Little Ringed Plover — yellow eye-ring, no wing bar, dull legs.",
    h: "Sandy and gravel lake shores.",
    di: "Ögii Nuur, Khar Us Nuur, Ulaanbaatar, Böön Tsagaan, Khurkh.",
    mi: "Passage migrant, May–September.",
    fo: "Small invertebrates.",
    br: "Nests on bare ground (not confirmed in Mongolia).",
    be: "Pretends to have a broken wing to lure predators from the nest.",
    v: "A mellow ‘too-lee’.",
    cu: "Famous for its ‘broken wing’ distraction display.",
    co: "Least Concern.",
    w: "Ögii Nuur shores in May.",
    bt: "May, July",
    fa: ["Fakes a broken wing.", "Orange legs.", "White wing bar."]
  },
  "little-ringed-plover": {
    T: { c: { brown: 0.4, white: 0.35, black: 0.2, yellow: 0.05 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["14–17 cm", "42–48 cm", "30–50 g"] },
    s: "A small plover with a bright yellow eye-ring and black breast band. Breeds on gravel and sandy shores across Mongolia.",
    d: "The Little Ringed Plover breeds across Eurasia on gravel river banks and lake shores and winters in Africa and South Asia. In Mongolia it breeds at Ögii Nuur, Böön Tsagaan, the Khurkh valley, Achit Nuur and elsewhere.",
    f: ["Bright yellow eye-ring.", "Black breast band.", "Dull pinkish legs.", "No wing bar in flight.", "Small, slim."],
    si: "Common Ringed Plover — orange legs and bill base, wing bar. Kentish Plover — incomplete breast band.",
    h: "Gravel river banks and lake shores.",
    di: "Ögii Nuur, Böön Tsagaan, Khurkh, Achit Nuur, Mongol Daguur, Uvs Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and spiders.",
    br: "Nests on gravel; 4 eggs.",
    be: "Runs and stops; foot-trembles to disturb prey.",
    v: "A falling ‘pee-oo’.",
    cu: "Often nests on gravel pits and building sites in Europe.",
    co: "Least Concern.",
    w: "Gravel shores in June.",
    bt: "May–July",
    fa: ["Yellow eye-ring.", "Nests on gravel.", "No wing bar."]
  },
  "kentish-plover": {
    T: { c: { brown: 0.35, white: 0.45, black: 0.1, rufous: 0.1 }, hb: ["water", "desert"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["15–17 cm", "42–45 cm", "32–56 g"] },
    s: "A pale, sandy plover with dark patches on the sides of the breast instead of a full band. Common on saline lakes in the Gobi and west.",
    d: "The Kentish Plover breeds on coasts and saline lakes across Eurasia and Africa. In Mongolia it is common on salt-lake shores in the Gobi (Böön Tsagaan, Orog Nuur, Taatsiin Tsagaan), the west (Khar Us Nuur) and the east (Buir Nuur).",
    f: ["Pale sandy upperparts.", "Dark patches on the breast sides (not a full band).", "Male has a rufous cap and black forehead bar.", "Black legs.", "White collar."],
    si: "Little Ringed Plover — full black breast band, yellow eye-ring.",
    h: "Saline lake shores and salt flats.",
    di: "Böön Tsagaan, Orog Nuur, Buir Nuur, Ögii Nuur, Khar Us Nuur, Taatsiin Tsagaan.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and small crustaceans.",
    br: "Nests on bare ground; 3 eggs.",
    be: "Runs fast on salt flats.",
    v: "A soft ‘pit’.",
    cu: "Named after Kent in England.",
    co: "Least Concern.",
    w: "Böön Tsagaan in June.",
    bt: "May–August",
    fa: ["Incomplete breast band.", "Lives on salt lakes.", "Named after Kent."]
  },
  "lesser-sand-plover": {
    T: { c: { brown: 0.35, rufous: 0.3, white: 0.25, black: 0.1 }, hb: ["mountain", "water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["18–21 cm", "45–58 cm", "40–110 g"] },
    s: "A plover with a broad chestnut breast band and black mask in summer. The Tibetan form breeds on high plateaus in western Mongolia.",
    d: "The Lesser Sand Plover complex includes the Tibetan Sand Plover (atrifrons group), which breeds on high plateaus of Central Asia including western Mongolia, and the Siberian Sand Plover (mongolus group) of eastern Siberia. It is now classed as Endangered because of the loss of tidal flats. In Mongolia it is found in the high Altai.",
    f: ["Broad chestnut breast band in summer.", "Black mask and forehead.", "Short black bill.", "Dark legs."],
    si: "Greater Sand Plover — larger, longer bill, longer legs.",
    h: "High plateaus and stony steppe near water.",
    di: "Western Mongolia, Altai.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on bare stony ground at high altitude.",
    be: "Runs and pauses.",
    v: "A short ‘drit’.",
    cu: "Its scientific name mongolus refers to Mongolia.",
    co: "Endangered.",
    w: "High plateaus of the Altai in summer.",
    bt: "June–July",
    fa: ["Named after Mongolia.", "Chestnut breast band.", "Endangered."]
  },
  "greater-sand-plover": {
    T: { c: { rufous: 0.3, brown: 0.3, white: 0.3, black: 0.1 }, hb: ["desert", "water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["22–25 cm", "53–60 cm", "55–120 g"] },
    s: "A large, long-legged plover with a chestnut breast band that breeds in deserts. Common in the Gobi and western Mongolia.",
    d: "The Greater Sand Plover breeds in the deserts of Turkey, Central Asia and Mongolia and winters on coasts of Africa, Asia and Australia. In Mongolia it nests on gravel desert near lakes and springs — Khar Us Nuur, Böön Tsagaan, Orog Nuur and Yolyn Am.",
    f: ["Chestnut breast band and black mask in summer.", "Long, heavy black bill.", "Long greenish-grey legs.", "White wing bar."],
    si: "Lesser Sand Plover — smaller, shorter bill. Oriental Plover — longer legs, no mask.",
    h: "Gravel deserts and dry steppe near water.",
    di: "Khar Us Nuur, Böön Tsagaan, Orog Nuur, Yolyn Am, Taatsiin Tsagaan, Achit Nuur.",
    mi: "Summer visitor, April–August.",
    fo: "Beetles, termites and other insects.",
    br: "Nests on bare desert ground; 3 eggs.",
    be: "Runs fast; stands upright.",
    v: "A trilling ‘trrri’.",
    cu: "Named after the French botanist Leschenault de la Tour.",
    co: "Least Concern.",
    w: "Gobi lake shores in May–June.",
    bt: "May–June",
    fa: ["Breeds in deserts.", "Long legs.", "Winters on coasts."]
  },
  "east-asian-plover": {
    T: { c: { buff: 0.4, brown: 0.3, white: 0.2, rufous: 0.1 }, hb: ["desert", "steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["22–25 cm", "46–53 cm", "70–100 g"] },
    s: "An elegant, long-legged plover of the steppe and desert; the male has a white head and chestnut breast band edged in black. A summer visitor, especially in the Gobi.",
    d: "The Oriental (East Asian) Plover breeds in the dry steppes and semi-deserts of Mongolia and adjoining China and Russia and winters in northern Australia. It is a bird of dry land rather than shores. In Mongolia it breeds around Yolyn Am, Taatsiin Tsagaan, Böön Tsagaan and in Dornod.",
    f: ["Male: whitish face and head, chestnut breast band with a black lower edge.", "Long yellowish legs.", "Slim, upright stance.", "Dark underwing in flight."],
    si: "Greater Sand Plover — black mask, heavier bill. Eurasian Dotterel — white eyebrow, chestnut belly.",
    h: "Dry steppe, stony plains and semi-desert.",
    di: "Gobi (Yolyn Am, Taatsiin Tsagaan, Böön Tsagaan), Dornod (Buir Nuur, Mongol Daguur).",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests on bare ground in steppe; 3 eggs.",
    be: "Runs over dry ground.",
    v: "A sharp ‘chip-chip’.",
    cu: "Mongolia is one of its main breeding countries.",
    co: "Least Concern.",
    w: "Yolyn Am area in May.",
    bt: "May–June",
    fa: ["Breeds on dry land.", "Long legs.", "Winters in Australia."]
  },
  "northern-lapwing": {
    T: { c: { black: 0.4, white: 0.4, gray: 0.1, rufous: 0.1 }, hb: ["water", "steppe"], bk: "short", bh: ["walk", "soar"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["28–31 cm", "82–87 cm", "130–330 g"] },
    s: "A black-and-white plover with a long wispy crest, broad rounded wings and a tumbling display flight. Very common in Mongolia’s wet meadows.",
    d: "The Northern Lapwing breeds across Eurasia in wet grassland and fields. Its display flight includes twists, dives and a ‘peewit’ call. In Mongolia it is one of the most widespread waders, breeding in the Khurkh valley, at Ögii Nuur, Khar Us Nuur and Buir Nuur.",
    f: ["Long, thin black crest.", "Glossy green-black back.", "Black breast band, white belly.", "Broad, rounded wings.", "Orange undertail."],
    si: "Grey-headed Lapwing — no crest, grey head, yellow bill.",
    h: "Wet meadows, marshes and steppe.",
    di: "All regions: Khurkh, Ögii Nuur, Khar Us Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Worms and insects.",
    br: "Nests on the ground; 4 eggs.",
    be: "Tumbling display flights; mobs predators.",
    v: "A wheezy ‘pee-wit’.",
    cu: "Its call gave it the English name ‘peewit’.",
    co: "Near Threatened.",
    w: "Khurkh valley in May.",
    bt: "April–July",
    fa: ["Has a long crest.", "Tumbling display.", "Near Threatened."]
  },
  "grey-headed-lapwing": {
    T: { c: { gray: 0.35, brown: 0.3, white: 0.2, black: 0.1, yellow: 0.05 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["screech"], ac: "day", se: ["summer", "passage"], sz: ["34–37 cm", "75–80 cm", "236–410 g"] },
    s: "A large, noisy lapwing with a grey head, yellow bill and legs and bold black-and-white wings. A scarce visitor in eastern Mongolia and the Gobi.",
    d: "The Grey-headed Lapwing breeds in north-east China and Japan and winters in South-East Asia. It is expanding its range and now appears regularly in eastern Mongolia (Buir Nuur) and Gobi oases (Yolyn Am).",
    f: ["Grey head and neck.", "Black breast band.", "Yellow bill with a black tip; yellow legs.", "Black-and-white wing pattern in flight."],
    si: "Northern Lapwing — black crest, green back.",
    h: "Wet fields and marshes.",
    di: "Buir Nuur, Yolyn Am, Mongol Daguur, Khar Us Nuur.",
    mi: "Summer visitor and migrant, April–September.",
    fo: "Insects and worms.",
    br: "Nests on the ground (possible in Mongolia).",
    be: "Very noisy when disturbed.",
    v: "A loud ‘chee-it’.",
    cu: "Common in Japanese rice fields.",
    co: "Least Concern.",
    w: "Buir Nuur in May.",
    bt: "May–June",
    fa: ["Grey head.", "Yellow legs.", "Expanding range."]
  },
  "sociable-lapwing": {
    T: { c: { gray: 0.35, brown: 0.3, white: 0.2, black: 0.15 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["27–30 cm", "70–76 cm", "150–260 g"] },
    s: "A critically endangered steppe lapwing with a black cap and white eyebrow. On the Mongolian list, with no GBIF records.",
    d: "The Sociable Lapwing breeds in the steppes of Kazakhstan and winters in Sudan, the Middle East and India. It is Critically Endangered. A record in Mongolia would be exceptional.",
    f: ["Black cap and eye-stripe with white eyebrow.", "Dark belly patch in summer.", "White secondaries in flight."],
    si: "Northern Lapwing — crest, green back.",
    h: "Dry steppe.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in Kazakh steppe (not in Mongolia).",
    be: "Often near livestock.",
    v: "Harsh ‘kretch’.",
    cu: "Satellite tracking discovered its migration route in 2007.",
    co: "Critically Endangered.",
    w: "Not expected.",
    bt: "—",
    fa: ["Critically Endangered.", "Steppe species.", "Tracked by satellite."]
  }
});
