B2T("fr", {
  "grey-plover": {
    name: "Pluvier argenté",
    s: "Pluvier trapu, argenté dessus et noir de jais dessous en été, aux « aisselles » noires en vol. Migrateur sur les lacs mongols ; désormais Vulnérable.",
    d: "Le Pluvier argenté niche dans la haute toundra arctique et hiverne sur les côtes du monde entier. En Mongolie, il passe en mai et août–septembre, surtout au lac Ögii, au lac Buir, à Böön Tsagaan et au lac Khar Us.",
    f: ["Été : face et dessous noirs, dos pailleté d’argent.", "Axillaires noires sous l’aile — caractère diagnostique.", "Croupion blanc.", "Bec noir épais.", "Hiver : gris uni."],
    si: "Pluvier fauve — dos pailleté d’or, dessous d’aile gris, bec plus petit.",
    h: "Rives de lacs et vasières.",
    di: "Lac Ögii, lac Buir, Böön Tsagaan, lac Khar Us, lac Orog.",
    mi: "Migrateur, mai et août–octobre.",
    fo: "Vers, mollusques et insectes.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Court, s’arrête et picore comme les autres pluviers.",
    v: "Un « tlii-ou-i » plaintif.",
    cu: "Appelé « pluvier à ventre noir » en Amérique du Nord.",
    co: "Vulnérable.",
    w: "Lac Ögii en mai et août.",
    bt: "mai, août",
    fa: ["« Aisselles » noires.", "Dos pailleté d’argent.", "Vulnérable à l’échelle mondiale."]
  },
  "pacific-golden-plover": {
    name: "Pluvier fauve",
    s: "Pluvier élancé pailleté d’or, noir dessous en été. D’immenses effectifs font halte dans l’est de la Mongolie en mai.",
    d: "Le Pluvier fauve niche dans la toundra de Sibérie et d’Alaska et hiverne de l’Inde à l’Australie et aux îles du Pacifique. En Mongolie, de spectaculaires vols printaniers se rassemblent dans le Dornod, surtout à Mongol Daguur, et de plus petits groupes passent au lac Ögii et au lac Buir.",
    f: ["Dos pailleté d’or et de noir.", "Face et ventre noirs en été, bordés de blanc.", "Dessous d’aile gris.", "Élancé, haut sur pattes."],
    si: "Pluvier argenté — dos argenté, « aisselles » noires.",
    h: "Steppe, prairies humides et rives de lacs.",
    di: "Dornod (Mongol Daguur, lac Buir), lac Ögii, Böön Tsagaan, lac Orog.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Insectes, vers et baies.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Se nourrit en grands groupes dans les prairies.",
    v: "Un « tchou-i » clair.",
    cu: "Vole sans escale de l’Alaska à Hawaï.",
    co: "Préoccupation mineure.",
    w: "Mongol Daguur en mai.",
    bt: "mai",
    fa: ["Dos pailleté d’or.", "Énormes vols printaniers dans le Dornod.", "Traverse le Pacifique sans escale."]
  },
  "eurasian-dotterel": {
    name: "Pluvier guignard",
    s: "Pluvier de montagne confiant, au large sourcil blanc et au ventre marron. Niche sur les hauts plateaux de l’ouest et du nord de la Mongolie.",
    d: "Le Pluvier guignard niche sur les sommets et la toundra arctique et hiverne en Afrique du Nord et au Moyen-Orient. La femelle, plus colorée, laisse le mâle couver. En Mongolie, il niche sur les plateaux alpins de l’Altaï, du Khangaï et du Khövsgöl.",
    f: ["Larges sourcils blancs se rejoignant sur la nuque.", "Bande pectorale blanche.", "Ventre marron à centre noir.", "Très confiant."],
    si: "Pluvier fauve — dos pailleté, sans sourcil blanc.",
    h: "Plateaux alpins et toundra de montagne.",
    di: "Altaï, Khangaï, Khövsgöl, région du lac Achit.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes et araignées.",
    br: "Niche sur la toundra caillouteuse ; le mâle couve.",
    be: "Extrêmement confiant.",
    v: "Un doux « pouit ».",
    cu: "Sa confiance lui a valu en anglais le nom de « petit sot ».",
    co: "Préoccupation mineure.",
    w: "Plateaux alpins de l’Altaï en juin.",
    bt: "juin–juil.",
    fa: ["Le mâle couve.", "Très confiant.", "Niche sur les sommets."]
  },
  "common-ringed-plover": {
    name: "Pluvier grand-gravelot",
    s: "Petit pluvier rond au collier noir, aux pattes orange et au bec orange à pointe noire. Migrateur sur les rives des lacs.",
    d: "Le Pluvier grand-gravelot niche sur les côtes arctiques et nordiques et hiverne en Afrique et en Europe. En Mongolie, il passe en mai et juillet au lac Ögii, au lac Khar Us et près d’Oulan-Bator.",
    f: ["Collier pectoral et masque noirs.", "Pattes orange.", "Bec orange à pointe noire.", "Barre alaire blanche en vol.", "Pas de cercle orbital jaune."],
    si: "Pluvier petit-gravelot — cercle orbital jaune, pas de barre alaire, pattes ternes.",
    h: "Rives sableuses et caillouteuses.",
    di: "Lac Ögii, lac Khar Us, Oulan-Bator, Böön Tsagaan, Khurkh.",
    mi: "Migrateur, mai–septembre.",
    fo: "Petits invertébrés.",
    br: "Niche sur sol nu (non confirmé en Mongolie).",
    be: "Simule une aile cassée pour éloigner les prédateurs du nid.",
    v: "Un doux « tou-li ».",
    cu: "Célèbre pour sa parade de diversion de « l’aile cassée ».",
    co: "Préoccupation mineure.",
    w: "Rives du lac Ögii en mai.",
    bt: "mai, juil.",
    fa: ["Simule une aile cassée.", "Pattes orange.", "Barre alaire blanche."]
  },
  "little-ringed-plover": {
    name: "Pluvier petit-gravelot",
    s: "Petit pluvier au cercle orbital jaune vif et au collier noir. Niche sur les rives caillouteuses et sableuses de toute la Mongolie.",
    d: "Le Pluvier petit-gravelot niche en Eurasie sur les berges de graviers et les rives des lacs et hiverne en Afrique et en Asie du Sud. En Mongolie, il niche au lac Ögii, à Böön Tsagaan, dans la vallée de Khurkh, au lac Achit et ailleurs.",
    f: ["Cercle orbital jaune vif.", "Collier pectoral noir.", "Pattes rosâtres ternes.", "Pas de barre alaire en vol.", "Petit et fin."],
    si: "Pluvier grand-gravelot — pattes et base du bec orange, barre alaire. Pluvier à collier interrompu — collier incomplet.",
    h: "Berges de graviers et rives de lacs.",
    di: "Lac Ögii, Böön Tsagaan, Khurkh, lac Achit, Mongol Daguur, lac Uvs.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes et araignées.",
    br: "Niche sur les graviers ; 4 œufs.",
    be: "Court et s’arrête ; fait trembler sa patte pour débusquer ses proies.",
    v: "Un « pii-ou » descendant.",
    cu: "Niche souvent dans les gravières et chantiers en Europe.",
    co: "Préoccupation mineure.",
    w: "Rives caillouteuses en juin.",
    bt: "mai–juil.",
    fa: ["Cercle orbital jaune.", "Niche sur les graviers.", "Pas de barre alaire."]
  },
  "kentish-plover": {
    name: "Pluvier à collier interrompu",
    s: "Pluvier pâle couleur sable aux taches sombres sur les côtés de la poitrine au lieu d’un collier complet. Commun sur les lacs salés du Gobi et de l’ouest.",
    d: "Le Pluvier à collier interrompu niche sur les côtes et lacs salés d’Eurasie et d’Afrique. En Mongolie, il est commun sur les rives des lacs salés du Gobi (Böön Tsagaan, lac Orog, Taatsiin Tsagaan), de l’ouest (lac Khar Us) et de l’est (lac Buir).",
    f: ["Dessus sable pâle.", "Taches sombres sur les côtés de la poitrine (collier incomplet).", "Mâle à calotte rousse et barre frontale noire.", "Pattes noires.", "Collier blanc."],
    si: "Pluvier petit-gravelot — collier noir complet, cercle orbital jaune.",
    h: "Rives de lacs salés et salines.",
    di: "Böön Tsagaan, lac Orog, lac Buir, lac Ögii, lac Khar Us, Taatsiin Tsagaan.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes et petits crustacés.",
    br: "Niche sur sol nu ; 3 œufs.",
    be: "Court vite sur les salines.",
    v: "Un doux « pit ».",
    cu: "Son nom anglais vient du comté de Kent.",
    co: "Préoccupation mineure.",
    w: "Böön Tsagaan en juin.",
    bt: "mai–août",
    fa: ["Collier incomplet.", "Vit sur les lacs salés.", "Nom anglais d’après le Kent."]
  },
  "lesser-sand-plover": {
    name: "Pluvier de Mongolie",
    s: "Pluvier à large bande pectorale rousse et masque noir en été. La forme tibétaine niche sur les hauts plateaux de l’ouest de la Mongolie.",
    d: "Le complexe du Pluvier de Mongolie comprend la forme tibétaine (groupe atrifrons), nicheuse sur les hauts plateaux d’Asie centrale dont l’ouest de la Mongolie, et la forme sibérienne (groupe mongolus) de Sibérie orientale. Il est désormais En danger à cause de la disparition des vasières. En Mongolie, on le trouve dans le haut Altaï.",
    f: ["Large bande pectorale rousse en été.", "Masque et front noirs.", "Bec noir court.", "Pattes sombres."],
    si: "Pluvier de Leschenault — plus grand, bec et pattes plus longs.",
    h: "Hauts plateaux et steppe caillouteuse près de l’eau.",
    di: "Ouest de la Mongolie, Altaï.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche sur sol caillouteux nu en altitude.",
    be: "Court et s’arrête.",
    v: "Un court « drit ».",
    cu: "Son nom mongolus fait référence à la Mongolie.",
    co: "En danger.",
    w: "Hauts plateaux de l’Altaï en été.",
    bt: "juin–juil.",
    fa: ["Porte le nom de la Mongolie.", "Bande pectorale rousse.", "En danger."]
  },
  "greater-sand-plover": {
    name: "Pluvier de Leschenault",
    s: "Grand pluvier haut sur pattes à bande pectorale rousse, nicheur des déserts. Commun dans le Gobi et l’ouest de la Mongolie.",
    d: "Le Pluvier de Leschenault niche dans les déserts de Turquie, d’Asie centrale et de Mongolie et hiverne sur les côtes d’Afrique, d’Asie et d’Australie. En Mongolie, il niche sur les regs près des lacs et sources — lac Khar Us, Böön Tsagaan, lac Orog et Yolyn Am.",
    f: ["Bande pectorale rousse et masque noir en été.", "Long bec noir fort.", "Longues pattes gris-vert.", "Barre alaire blanche."],
    si: "Pluvier de Mongolie — plus petit, bec plus court. Pluvier oriental — pattes plus longues, sans masque.",
    h: "Regs et steppe sèche près de l’eau.",
    di: "Lac Khar Us, Böön Tsagaan, lac Orog, Yolyn Am, Taatsiin Tsagaan, lac Achit.",
    mi: "Visiteur d’été, avril–août.",
    fo: "Coléoptères, termites et autres insectes.",
    br: "Niche sur le sol nu du désert ; 3 œufs.",
    be: "Court vite ; se tient droit.",
    v: "Un « trrri » trillé.",
    cu: "Nommé d’après le botaniste français Leschenault de la Tour.",
    co: "Préoccupation mineure.",
    w: "Rives des lacs du Gobi en mai–juin.",
    bt: "mai–juin",
    fa: ["Niche dans les déserts.", "Longues pattes.", "Hiverne sur les côtes."]
  },
  "east-asian-plover": {
    name: "Pluvier oriental",
    s: "Élégant pluvier aux longues pattes des steppes et déserts ; le mâle a la tête blanche et une bande pectorale rousse bordée de noir. Visiteur d’été, surtout dans le Gobi.",
    d: "Le Pluvier oriental niche dans les steppes sèches et semi-déserts de Mongolie et des régions voisines de Chine et de Russie, et hiverne dans le nord de l’Australie. C’est un oiseau des terres sèches plutôt que des rives. En Mongolie, il niche autour de Yolyn Am, Taatsiin Tsagaan, Böön Tsagaan et dans le Dornod.",
    f: ["Mâle : face et tête blanchâtres, bande pectorale rousse bordée de noir en dessous.", "Longues pattes jaunâtres.", "Silhouette fine et dressée.", "Dessous d’aile sombre en vol."],
    si: "Pluvier de Leschenault — masque noir, bec plus fort. Pluvier guignard — sourcil blanc, ventre marron.",
    h: "Steppe sèche, plaines caillouteuses et semi-désert.",
    di: "Gobi (Yolyn Am, Taatsiin Tsagaan, Böön Tsagaan), Dornod (lac Buir, Mongol Daguur).",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche sur sol nu dans la steppe ; 3 œufs.",
    be: "Court sur le sol sec.",
    v: "Un « tchip-tchip » sec.",
    cu: "La Mongolie est l’un de ses principaux pays de nidification.",
    co: "Préoccupation mineure.",
    w: "Région de Yolyn Am en mai.",
    bt: "mai–juin",
    fa: ["Niche sur terrain sec.", "Longues pattes.", "Hiverne en Australie."]
  },
  "northern-lapwing": {
    name: "Vanneau huppé",
    s: "Pluvier noir et blanc à longue huppe fine, ailes larges et arrondies et parade en vol acrobatique. Très commun dans les prairies humides mongoles.",
    d: "Le Vanneau huppé niche dans toute l’Eurasie, dans les prairies humides et les champs. Sa parade comprend vrilles, piqués et un « pi-ouit » sonore. En Mongolie, c’est l’un des limicoles les plus répandus, nicheur dans la vallée de Khurkh, aux lacs Ögii, Khar Us et Buir.",
    f: ["Longue huppe noire et fine.", "Dos vert-noir brillant.", "Plastron noir, ventre blanc.", "Ailes larges et arrondies.", "Sous-caudales orange."],
    si: "Vanneau à tête grise — sans huppe, tête grise, bec jaune.",
    h: "Prairies humides, marais et steppe.",
    di: "Toutes les régions : Khurkh, lac Ögii, lac Khar Us, Böön Tsagaan, lac Orog, lac Buir.",
    mi: "Visiteur d’été, mars–octobre.",
    fo: "Vers et insectes.",
    br: "Niche au sol ; 4 œufs.",
    be: "Parades acrobatiques ; harcèle les prédateurs.",
    v: "Un « pi-ouit » sifflant.",
    cu: "Son cri lui vaut le nom anglais « peewit ».",
    co: "Quasi menacé.",
    w: "Vallée de Khurkh en mai.",
    bt: "avril–juil.",
    fa: ["Longue huppe.", "Parade acrobatique.", "Quasi menacé."]
  },
  "grey-headed-lapwing": {
    name: "Vanneau à tête grise",
    s: "Grand vanneau bruyant à tête grise, bec et pattes jaunes et ailes noir et blanc. Visiteur peu commun dans l’est de la Mongolie et le Gobi.",
    d: "Le Vanneau à tête grise niche dans le nord-est de la Chine et au Japon et hiverne en Asie du Sud-Est. Il étend son aire et apparaît désormais régulièrement dans l’est de la Mongolie (lac Buir) et les oasis du Gobi (Yolyn Am).",
    f: ["Tête et cou gris.", "Plastron noir.", "Bec jaune à pointe noire ; pattes jaunes.", "Motif alaire noir et blanc en vol."],
    si: "Vanneau huppé — huppe noire, dos vert.",
    h: "Champs humides et marais.",
    di: "Lac Buir, Yolyn Am, Mongol Daguur, lac Khar Us.",
    mi: "Visiteur d’été et migrateur, avril–septembre.",
    fo: "Insectes et vers.",
    br: "Niche au sol (possible en Mongolie).",
    be: "Très bruyant quand on le dérange.",
    v: "Un « tchi-it » sonore.",
    cu: "Commun dans les rizières japonaises.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en mai.",
    bt: "mai–juin",
    fa: ["Tête grise.", "Pattes jaunes.", "Aire en expansion."]
  },
  "sociable-lapwing": {
    name: "Vanneau sociable",
    s: "Vanneau des steppes en danger critique, à calotte noire et sourcil blanc. Sur la liste mongole, sans mention GBIF.",
    d: "Le Vanneau sociable niche dans les steppes du Kazakhstan et hiverne au Soudan, au Moyen-Orient et en Inde. Il est En danger critique. Une mention en Mongolie serait exceptionnelle.",
    f: ["Calotte et trait oculaire noirs, sourcil blanc.", "Plaque ventrale sombre en été.", "Secondaires blanches en vol."],
    si: "Vanneau huppé — huppe, dos vert.",
    h: "Steppe sèche.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les steppes kazakhes (pas en Mongolie).",
    be: "Souvent près du bétail.",
    v: "Un « krètch » rauque.",
    cu: "Le suivi satellitaire a révélé sa route migratoire en 2007.",
    co: "En danger critique.",
    w: "Non attendu.",
    bt: "—",
    fa: ["En danger critique.", "Espèce des steppes.", "Suivi par satellite."]
  }
});
