B2T("en", {
  "pied-avocet": {
    T: { c: { white: 0.65, black: 0.35 }, hb: ["water"], bk: "curved", bh: ["walk", "swim"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["42–45 cm", "77–80 cm", "225–400 g"] },
    s: "A striking black-and-white wader with a thin, upturned bill that it sweeps through the water. Common on saline lakes across Mongolia.",
    d: "The Pied Avocet breeds on saline lakes and coasts from Europe to Mongolia and China. It feeds by sweeping its upcurved bill from side to side. In Mongolia it breeds in colonies at Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur and Khar Us Nuur.",
    f: ["White with a black cap and black wing patches.", "Long, thin, upturned black bill.", "Long blue-grey legs.", "Swims readily."],
    si: "Black-winged Stilt — straight bill, pink legs, black wings.",
    h: "Shallow saline and brackish lakes.",
    di: "Ögii Nuur, Böön Tsagaan, Orog Nuur, Buir Nuur, Khar Us Nuur, Khurkh.",
    mi: "Summer visitor, April–September.",
    fo: "Small crustaceans and insect larvae.",
    br: "Colonial on open shores; 3–4 eggs.",
    be: "Sweeps its bill; mobs intruders noisily.",
    v: "A clear ‘kloo-it’.",
    cu: "The emblem of Britain’s RSPB.",
    co: "Least Concern.",
    w: "Böön Tsagaan and Ögii Nuur in June.",
    bt: "May–July",
    fa: ["Upturned bill.", "Sweeps the water to feed.", "Emblem of the RSPB."]
  },
  "black-winged-stilt": {
    T: { c: { white: 0.55, black: 0.35, red: 0.1 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["35–40 cm", "67–83 cm", "150–200 g"] },
    s: "An elegant wader with enormously long pink legs, black wings and a needle-thin bill. Common on lakes across Mongolia.",
    d: "The Black-winged Stilt has the longest legs relative to body size of any bird after flamingos. It breeds widely in Eurasia and Africa. In Mongolia it nests on shallow lakes and marshes at Ögii Nuur, the Khurkh valley, Böön Tsagaan, Orog Nuur and Khar Us Nuur.",
    f: ["Extremely long pink-red legs.", "Black wings and back; white body.", "Thin, straight black bill.", "Legs trail far behind in flight."],
    si: "Pied Avocet — upturned bill, blue-grey legs.",
    h: "Shallow lakes and marshes.",
    di: "Ögii Nuur, Khurkh, Böön Tsagaan, Orog Nuur, Khar Us Nuur, Buir Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and small crustaceans.",
    br: "Loose colonies; 4 eggs.",
    be: "Wades deep; very noisy near nests.",
    v: "A yelping ‘kek-kek’.",
    cu: "Its legs are up to 60 % of its height.",
    co: "Least Concern.",
    w: "Ögii Nuur in June.",
    bt: "May–July",
    fa: ["Extremely long legs.", "Wades in deep water.", "Very noisy."]
  },
  "east-asian-pratincole": {
    T: { c: { brown: 0.5, buff: 0.25, white: 0.15, black: 0.1 }, hb: ["steppe", "water"], bk: "short", bh: ["soar", "walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["23–24 cm", "59–64 cm", "60–95 g"] },
    s: "A swallow-like wader with a forked tail and a buff throat outlined in black, catching insects in flight. A scarce summer visitor in eastern Mongolia.",
    d: "The Oriental Pratincole breeds in eastern Asia on dry plains near water and winters in South-East Asia and Australia. It hawks insects like a swallow. In Mongolia it occurs mainly at Buir Nuur and other Dornod lakes.",
    f: ["Short bill with a red base.", "Buff throat edged with a black line.", "Forked tail; long pointed wings.", "Chestnut underwing."],
    si: "Swallows — much smaller; terns — longer bills.",
    h: "Dry plains and lake shores.",
    di: "Dornod (Buir Nuur), Böön Tsagaan, Yolyn Am.",
    mi: "Summer visitor, May–August.",
    fo: "Flying insects.",
    br: "Nests on bare ground; 2 eggs.",
    be: "Hawks insects in flight like a swallow.",
    v: "A tern-like ‘krik-krik’.",
    cu: "Its name means ‘meadow dweller’ in Latin.",
    co: "Least Concern.",
    w: "Buir Nuur in June.",
    bt: "June",
    fa: ["Catches insects like a swallow.", "Forked tail.", "Winters in Australia."]
  },
  "eurasian-thick-knee": {
    T: { c: { buff: 0.5, brown: 0.3, white: 0.15, yellow: 0.05 }, hb: ["steppe", "desert"], bk: "short", bh: ["walk", "night"], vt: ["whistle"], ac: "night", se: ["passage"], sz: ["38–45 cm", "76–88 cm", "290–535 g"] },
    s: "A sandy, big-eyed bird of dry steppe, active at night. On the Mongolian list, with no GBIF records.",
    d: "The Eurasian Stone-curlew breeds in dry open country from Europe to Central Asia. It is nocturnal and relies on camouflage by day. Records in Mongolia are exceptional.",
    f: ["Huge yellow eyes.", "Streaked sandy plumage.", "Thick ‘knees’ (actually ankles).", "White wing bars in flight."],
    si: "Unmistakable.",
    h: "Dry steppe and semi-desert.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Beetles, worms and small animals.",
    br: "Nests on bare ground (not in Mongolia).",
    be: "Nocturnal; freezes when disturbed.",
    v: "Wailing ‘cur-lee’ at night.",
    cu: "Its ‘thick knees’ are really its ankle joints.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Huge eyes for night.", "Thick ankle joints.", "Camouflaged by day."]
  },
  "greater-painted-snipe": {
    T: { c: { brown: 0.4, white: 0.25, rufous: 0.2, buff: 0.15 }, hb: ["water"], bk: "long", bh: ["walk"], vt: ["hoot"], ac: "night", se: ["passage"], sz: ["23–28 cm", "50–55 cm", "90–200 g"] },
    s: "A colourful, snipe-like bird in which the female is brighter than the male. On the Mongolian list, with no GBIF records.",
    d: "The Greater Painted-snipe lives in marshes of Africa and southern Asia. Females court males and leave them to incubate. A record in Mongolia would be exceptional.",
    f: ["White ‘spectacles’ around the eye.", "Female: chestnut neck; male duller.", "Long, slightly drooping bill.", "White strap from breast to shoulder."],
    si: "Common Snipe — no white spectacles.",
    h: "Marshes.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects, snails and seeds.",
    br: "Nests in marshes (not in Mongolia).",
    be: "Crepuscular; secretive.",
    v: "Female gives soft hooting notes.",
    cu: "Roles reversed: the female courts.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Female more colourful.", "Male incubates.", "Tropical species."]
  },
  "yellow-legged-buttonquail": {
    T: { c: { buff: 0.45, brown: 0.35, rufous: 0.2 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["hoot"], ac: "day", se: ["summer"], sz: ["15–17 cm", "—", "40–110 g"] },
    s: "A tiny, quail-like bird with yellow legs and only three toes. A rare bird of the eastern grasslands, with a single GBIF record.",
    d: "The Yellow-legged Buttonquail breeds in grasslands from India to the Russian Far East. Like other buttonquails, females court and males raise the chicks. In Mongolia it is known from very few records in Dornod.",
    f: ["Small, rounded, quail-like.", "Yellow legs and bill.", "Only three toes.", "Female has an orange collar."],
    si: "Japanese Quail — four toes, no yellow legs.",
    h: "Tall grassland.",
    di: "Very rare; Dornod.",
    mi: "Summer visitor.",
    fo: "Seeds and insects.",
    br: "Nests in grass; male incubates.",
    be: "Runs rather than flies.",
    v: "A booming ‘hoo-hoo’ by the female.",
    cu: "Not a true quail — related to waders.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Has three toes.", "Related to shorebirds.", "Male raises the young."]
  },
  "common-quail": {
    T: { c: { brown: 0.45, buff: 0.4, black: 0.1, white: 0.05 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["16–18 cm", "32–35 cm", "70–155 g"] },
    s: "A tiny, secretive gamebird of grassland, more often heard than seen: ‘wet-my-lips’. A summer visitor, mainly in western Mongolia.",
    d: "The Common Quail breeds from Europe to western Mongolia and winters in Africa and India. It is the only migratory gamebird in Europe. In Mongolia it breeds in meadows of the west (Khar Us Nuur, Uvs) and north.",
    f: ["Small, rounded, streaked brown.", "Striped head.", "Male has a dark throat pattern.", "Almost never flies unless flushed."],
    si: "Japanese Quail — very similar; male has a rufous face.",
    h: "Meadows and crops.",
    di: "Western Mongolia (Khar Us Nuur, Uvs), Khentii (Khurkh).",
    mi: "Summer visitor, May–September.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 8–13 eggs.",
    be: "Stays hidden in grass.",
    v: "A liquid ‘whit-wit-wit’ (‘wet-my-lips’).",
    cu: "Its call is a sound of summer fields in Europe.",
    co: "Least Concern.",
    w: "Listen in meadows in June.",
    bt: "June",
    fa: ["Heard more than seen.", "Migrates to Africa.", "Smallest gamebird in Mongolia."]
  },
  "japanese-quail": {
    T: { c: { brown: 0.45, buff: 0.35, rufous: 0.15, black: 0.05 }, hb: ["steppe", "water"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer"], sz: ["17–19 cm", "—", "90–100 g"] },
    s: "The eastern counterpart of the Common Quail, with a harsh, rasping call. A summer visitor to grasslands of northern and eastern Mongolia.",
    d: "The Japanese Quail breeds in Mongolia, eastern Siberia, China and Japan and winters in southern China and South-East Asia. It has been domesticated for eggs. Wild populations have declined, so it is Near Threatened. In Mongolia it is common in the Khurkh valley, Buir Nuur, Khustai and around Ulaanbaatar.",
    f: ["Small, rounded, streaked brown.", "Male: rusty face and throat in summer.", "Striped crown.", "Grass-coloured camouflage."],
    si: "Common Quail — whitish face in males, different call.",
    h: "Meadows, steppe and field edges.",
    di: "Khentii (Khurkh), Dornod (Buir Nuur), Khustai, Ulaanbaatar, Terelj.",
    mi: "Summer visitor, May–October.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 7–12 eggs.",
    be: "Secretive; runs in grass.",
    v: "A rasping ‘guku-kr-r-r’.",
    cu: "The domestic quail raised for eggs comes from this species.",
    co: "Near Threatened.",
    w: "Khurkh valley meadows in June.",
    bt: "June–August",
    fa: ["Ancestor of the domestic quail.", "Rasping call.", "Near Threatened."]
  },
  "chukar-partridge": {
    T: { c: { gray: 0.35, buff: 0.25, black: 0.15, rufous: 0.15, red: 0.1 }, hb: ["mountain", "desert"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["32–35 cm", "47–52 cm", "450–800 g"] },
    s: "A plump partridge with a black ‘necklace’ around a cream throat, barred flanks and red bill and legs. A resident of rocky slopes in the Gobi and west.",
    d: "The Chukar lives on dry rocky hillsides from Turkey to Mongolia and China. Its loud ‘chuk-chuk-chukar’ call echoes across valleys. In Mongolia it is found in the mountains of the Gobi and west — Yolyn Am, Khar Us Nuur, Orog Nuur and Ikh Nart.",
    f: ["Cream throat framed by a black band from the eye.", "Bold black-and-chestnut bars on the flanks.", "Red bill and legs.", "Grey back."],
    si: "Daurian Partridge — orange face, dark belly patch, lives in steppe.",
    h: "Rocky slopes and dry valleys.",
    di: "Gobi mountains (Yolyn Am, Ikh Nart, Orog Nuur), west (Khar Us Nuur, Bayan-Ölgii).",
    mi: "Resident.",
    fo: "Seeds, shoots and insects.",
    br: "Nests on the ground under rocks; 8–15 eggs.",
    be: "Runs uphill when disturbed.",
    v: "A loud ‘chuk-chuk-chukar’.",
    cu: "Its name copies its call; the national bird of Pakistan.",
    co: "Least Concern.",
    w: "Yolyn Am in the early morning.",
    bt: "all year",
    fa: ["Named after its call.", "National bird of Pakistan.", "Runs uphill to escape."]
  },
  "common-pheasant": {
    T: { c: { rufous: 0.4, brown: 0.2, black: 0.15, red: 0.1, white: 0.1, gray: 0.05 }, hb: ["water", "forest"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["50–90 cm", "70–90 cm", "0.5–1.5 kg"] },
    s: "A long-tailed gamebird; the male is copper-coloured with a green head and red face. A local resident of riverside thickets in western Mongolia.",
    d: "The Common Pheasant is native to Asia and has been introduced worldwide. In Mongolia wild pheasants live in the reed and tamarisk thickets around Khar Us Nuur and in the Gobi, where they are local.",
    f: ["Male: coppery body, green head, red face wattles, long barred tail.", "Often a white neck ring.", "Female: mottled brown with a shorter tail."],
    si: "Unmistakable.",
    h: "Reed beds and riverside thickets.",
    di: "Western Mongolia (Khar Us Nuur, Khovd river valleys), Gobi.",
    mi: "Resident.",
    fo: "Seeds, grain and insects.",
    br: "Nests on the ground; 8–15 eggs.",
    be: "Runs to cover; explodes into flight.",
    v: "A loud ‘kork-kok’ crow.",
    cu: "Named after the Phasis River in ancient Colchis (Georgia).",
    co: "Least Concern.",
    w: "Khar Us Nuur thickets.",
    bt: "all year",
    fa: ["Named after an ancient river.", "Introduced worldwide.", "Male has a long tail."]
  }
});
