B2T("fr", {
  "pied-avocet": {
    name: "Avocette élégante",
    s: "Limicole noir et blanc saisissant au bec fin retroussé, qu’il balaie dans l’eau. Commune sur les lacs salés de toute la Mongolie.",
    d: "L’Avocette élégante niche sur les lacs salés et les côtes, de l’Europe à la Mongolie et à la Chine. Elle se nourrit en balayant l’eau de son bec recourbé. En Mongolie, elle niche en colonies au lac Ögii, à Böön Tsagaan, aux lacs Orog, Buir et Khar Us.",
    f: ["Blanche à calotte noire et taches alaires noires.", "Long bec noir fin et retroussé.", "Longues pattes gris-bleu.", "Nage volontiers."],
    si: "Échasse blanche — bec droit, pattes roses, ailes noires.",
    h: "Lacs salés et saumâtres peu profonds.",
    di: "Lac Ögii, Böön Tsagaan, lac Orog, lac Buir, lac Khar Us, Khurkh.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Petits crustacés et larves d’insectes.",
    br: "Coloniale sur les rives dégagées ; 3 ou 4 œufs.",
    be: "Balaie l’eau ; harcèle bruyamment les intrus.",
    v: "Un « klou-it » clair.",
    cu: "Emblème de la RSPB britannique.",
    co: "Préoccupation mineure.",
    w: "Böön Tsagaan et lac Ögii en juin.",
    bt: "mai–juil.",
    fa: ["Bec retroussé.", "Balaie l’eau pour se nourrir.", "Emblème de la RSPB."]
  },
  "black-winged-stilt": {
    name: "Échasse blanche",
    s: "Élégant limicole aux pattes roses démesurées, ailes noires et bec fin comme une aiguille. Commune sur les lacs de toute la Mongolie.",
    d: "L’Échasse blanche a les pattes les plus longues, proportionnellement, de tous les oiseaux après les flamants. Elle niche largement en Eurasie et en Afrique. En Mongolie, elle niche sur les lacs et marais peu profonds du lac Ögii, de la vallée de Khurkh, de Böön Tsagaan, des lacs Orog et Khar Us.",
    f: ["Pattes rouge rosé extrêmement longues.", "Ailes et dos noirs ; corps blanc.", "Bec noir fin et droit.", "Pattes dépassant loin en arrière en vol."],
    si: "Avocette élégante — bec retroussé, pattes gris-bleu.",
    h: "Lacs peu profonds et marais.",
    di: "Lac Ögii, Khurkh, Böön Tsagaan, lac Orog, lac Khar Us, lac Buir.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes et petits crustacés.",
    br: "Colonies lâches ; 4 œufs.",
    be: "Patauge profondément ; très bruyante près du nid.",
    v: "Un « kèk-kèk » jappant.",
    cu: "Ses pattes représentent jusqu’à 60 % de sa hauteur.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en juin.",
    bt: "mai–juil.",
    fa: ["Pattes extrêmement longues.", "Patauge en eau profonde.", "Très bruyante."]
  },
  "east-asian-pratincole": {
    name: "Glaréole orientale",
    s: "Limicole ressemblant à une hirondelle, à queue fourchue et gorge chamois bordée de noir, qui chasse les insectes en vol. Visiteuse d’été peu commune dans l’est de la Mongolie.",
    d: "La Glaréole orientale niche en Asie orientale sur les plaines sèches près de l’eau et hiverne en Asie du Sud-Est et en Australie. Elle chasse les insectes comme une hirondelle. En Mongolie, on la trouve surtout au lac Buir et sur d’autres lacs du Dornod.",
    f: ["Bec court à base rouge.", "Gorge chamois cerclée d’un trait noir.", "Queue fourchue ; longues ailes pointues.", "Dessous d’aile roux."],
    si: "Hirondelles — bien plus petites ; sternes — bec plus long.",
    h: "Plaines sèches et rives de lacs.",
    di: "Dornod (lac Buir), Böön Tsagaan, Yolyn Am.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes volants.",
    br: "Niche sur sol nu ; 2 œufs.",
    be: "Chasse les insectes en vol comme une hirondelle.",
    v: "Un « krik-krik » de sterne.",
    cu: "Son nom latin signifie « habitante des prés ».",
    co: "Préoccupation mineure.",
    w: "Lac Buir en juin.",
    bt: "juin",
    fa: ["Attrape les insectes comme une hirondelle.", "Queue fourchue.", "Hiverne en Australie."]
  },
  "eurasian-thick-knee": {
    name: "Œdicnème criard",
    s: "Oiseau couleur sable aux grands yeux, des steppes sèches, actif la nuit. Sur la liste mongole, sans mention GBIF.",
    d: "L’Œdicnème criard niche dans les milieux secs et ouverts, de l’Europe à l’Asie centrale. Nocturne, il compte sur son camouflage le jour. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Énormes yeux jaunes.", "Plumage sable strié.", "« Genoux » épais (en réalité les chevilles).", "Barres alaires blanches en vol."],
    si: "Inconfondable.",
    h: "Steppe sèche et semi-désert.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Coléoptères, vers et petits animaux.",
    br: "Niche sur sol nu (pas en Mongolie).",
    be: "Nocturne ; se fige quand on le dérange.",
    v: "Un « cour-li » gémissant la nuit.",
    cu: "Ses « genoux épais » sont en réalité ses chevilles.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Grands yeux pour la nuit.", "Chevilles épaisses.", "Camouflé le jour."]
  },
  "greater-painted-snipe": {
    name: "Rhynchée peinte",
    s: "Oiseau coloré ressemblant à une bécassine, dont la femelle est plus vive que le mâle. Sur la liste mongole, sans mention GBIF.",
    d: "La Rhynchée peinte vit dans les marais d’Afrique et d’Asie du Sud. Les femelles courtisent les mâles et leur laissent l’incubation. Une mention en Mongolie serait exceptionnelle.",
    f: ["« Lunettes » blanches autour de l’œil.", "Femelle : cou marron ; mâle plus terne.", "Long bec légèrement tombant.", "Bande blanche de la poitrine à l’épaule."],
    si: "Bécassine des marais — sans lunettes blanches.",
    h: "Marais.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes, escargots et graines.",
    br: "Niche dans les marais (pas en Mongolie).",
    be: "Crépusculaire ; discrète.",
    v: "La femelle émet de doux hululements.",
    cu: "Rôles inversés : la femelle fait la cour.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Femelle plus colorée.", "Le mâle couve.", "Espèce tropicale."]
  },
  "yellow-legged-buttonquail": {
    name: "Turnix indien",
    s: "Minuscule oiseau ressemblant à une caille, aux pattes jaunes et à trois doigts seulement. Rare dans les prairies de l’est, avec une seule mention GBIF.",
    d: "Le Turnix indien niche dans les prairies, de l’Inde à l’Extrême-Orient russe. Comme les autres turnix, la femelle fait la cour et le mâle élève les poussins. En Mongolie, il n’est connu que par de très rares mentions dans le Dornod.",
    f: ["Petit, rond, ressemblant à une caille.", "Pattes et bec jaunes.", "Trois doigts seulement.", "La femelle porte un collier orange."],
    si: "Caille du Japon — quatre doigts, pattes non jaunes.",
    h: "Prairies hautes.",
    di: "Très rare ; Dornod.",
    mi: "Visiteur d’été.",
    fo: "Graines et insectes.",
    br: "Niche dans l’herbe ; le mâle couve.",
    be: "Court plutôt que de voler.",
    v: "Un « hou-hou » grave de la femelle.",
    cu: "Pas une vraie caille — apparenté aux limicoles.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Trois doigts.", "Apparenté aux limicoles.", "Le mâle élève les jeunes."]
  },
  "common-quail": {
    name: "Caille des blés",
    s: "Minuscule gallinacé discret des prairies, plus souvent entendu que vu : « paye-tes-dettes ». Visiteuse d’été, surtout dans l’ouest de la Mongolie.",
    d: "La Caille des blés niche de l’Europe à l’ouest de la Mongolie et hiverne en Afrique et en Inde. C’est le seul gallinacé migrateur d’Europe. En Mongolie, elle niche dans les prairies de l’ouest (lac Khar Us, Uvs) et du nord.",
    f: ["Petite, ronde, brune striée.", "Tête rayée.", "Le mâle a un dessin gulaire sombre.", "S’envole rarement sauf si on la débusque."],
    si: "Caille du Japon — très semblable ; mâle à face rousse.",
    h: "Prairies et cultures.",
    di: "Ouest (lac Khar Us, Uvs), Khentii (Khurkh).",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 8 à 13 œufs.",
    be: "Reste cachée dans l’herbe.",
    v: "Un « pay-tes-dettes » liquide.",
    cu: "Son chant est un son des champs d’été en Europe.",
    co: "Préoccupation mineure.",
    w: "Écoutez dans les prairies en juin.",
    bt: "juin",
    fa: ["Plus entendue que vue.", "Migre en Afrique.", "Le plus petit gallinacé de Mongolie."]
  },
  "japanese-quail": {
    name: "Caille du Japon",
    s: "Pendant oriental de la Caille des blés, au chant rauque et râpeux. Visiteuse d’été des prairies du nord et de l’est de la Mongolie.",
    d: "La Caille du Japon niche en Mongolie, en Sibérie orientale, en Chine et au Japon et hiverne dans le sud de la Chine et en Asie du Sud-Est. Elle a été domestiquée pour ses œufs. Les populations sauvages ont décliné, d’où son statut de quasi menacée. En Mongolie, elle est commune dans la vallée de Khurkh, au lac Buir, à Khustai et autour d’Oulan-Bator.",
    f: ["Petite, ronde, brune striée.", "Mâle : face et gorge rouille en été.", "Calotte rayée.", "Camouflage couleur d’herbe."],
    si: "Caille des blés — face blanchâtre chez le mâle, chant différent.",
    h: "Prairies, steppe et bords de champs.",
    di: "Khentii (Khurkh), Dornod (lac Buir), Khustai, Oulan-Bator, Terelj.",
    mi: "Visiteuse d’été, mai–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 7 à 12 œufs.",
    be: "Discrète ; court dans l’herbe.",
    v: "Un « gouhou-kr-r-r » râpeux.",
    cu: "La caille domestique élevée pour ses œufs vient de cette espèce.",
    co: "Quasi menacée.",
    w: "Prairies de Khurkh en juin.",
    bt: "juin–août",
    fa: ["Ancêtre de la caille domestique.", "Chant râpeux.", "Quasi menacée."]
  },
  "chukar-partridge": {
    name: "Perdrix choukar",
    s: "Perdrix dodue au « collier » noir autour d’une gorge crème, aux flancs barrés et au bec et pattes rouges. Résidente des pentes rocheuses du Gobi et de l’ouest.",
    d: "La Perdrix choukar vit sur les coteaux rocheux secs, de la Turquie à la Mongolie et à la Chine. Son « tchouk-tchouk-tchoukar » sonore résonne dans les vallées. En Mongolie, on la trouve dans les montagnes du Gobi et de l’ouest — Yolyn Am, lac Khar Us, lac Orog et Ikh Nart.",
    f: ["Gorge crème encadrée d’une bande noire partant de l’œil.", "Barres noires et marron marquées sur les flancs.", "Bec et pattes rouges.", "Dos gris."],
    si: "Perdrix de Daourie — face orange, plaque ventrale sombre, vit dans la steppe.",
    h: "Pentes rocheuses et vallées sèches.",
    di: "Montagnes du Gobi (Yolyn Am, Ikh Nart, lac Orog), ouest (lac Khar Us, Bayan-Ölgii).",
    mi: "Résidente.",
    fo: "Graines, pousses et insectes.",
    br: "Niche au sol sous les rochers ; 8 à 15 œufs.",
    be: "S’enfuit en courant vers le haut.",
    v: "Un « tchouk-tchouk-tchoukar » sonore.",
    cu: "Son nom imite son cri ; oiseau national du Pakistan.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am tôt le matin.",
    bt: "toute l’année",
    fa: ["Nommée d’après son cri.", "Oiseau national du Pakistan.", "Fuit en courant vers le haut."]
  },
  "common-pheasant": {
    name: "Faisan de Colchide",
    s: "Gallinacé à longue queue ; le mâle est cuivré à tête verte et face rouge. Résident local des fourrés riverains de l’ouest de la Mongolie.",
    d: "Le Faisan de Colchide est originaire d’Asie et a été introduit dans le monde entier. En Mongolie, les faisans sauvages vivent dans les roselières et fourrés de tamaris autour du lac Khar Us et dans le Gobi, où ils sont localisés.",
    f: ["Mâle : corps cuivré, tête verte, caroncules faciales rouges, longue queue barrée.", "Souvent un collier blanc.", "Femelle : brune mouchetée à queue plus courte."],
    si: "Inconfondable.",
    h: "Roselières et fourrés riverains.",
    di: "Ouest (lac Khar Us, vallées du Khovd), Gobi.",
    mi: "Résident.",
    fo: "Graines, céréales et insectes.",
    br: "Niche au sol ; 8 à 15 œufs.",
    be: "Court se mettre à couvert ; s’envole brusquement.",
    v: "Un « kork-kok » sonore.",
    cu: "Nommé d’après le fleuve Phase, dans l’antique Colchide (Géorgie).",
    co: "Préoccupation mineure.",
    w: "Fourrés du lac Khar Us.",
    bt: "toute l’année",
    fa: ["Nommé d’après un fleuve antique.", "Introduit dans le monde entier.", "Le mâle a une longue queue."]
  }
});
