B2T("en", {
  "willow-grouse": {
    T: { c: { white: 0.45, rufous: 0.3, brown: 0.2, red: 0.05 }, hb: ["forest", "mountain"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["35–43 cm", "55–66 cm", "430–810 g"] },
    s: "A plump grouse that turns pure white in winter and rich chestnut in summer, with white wings all year. Resident in willow thickets of the northern mountains.",
    d: "The Willow Ptarmigan lives in the tundra and taiga of the far north. Its feathered feet act as snowshoes. In Mongolia it lives in willow and dwarf-birch thickets in Khövsgöl, the Khentii and the Khangai, often near the tree line.",
    f: ["Winter: all white with a black tail.", "Summer: chestnut-brown head and body with white wings and belly.", "Red ‘eyebrow’ comb in males.", "Feathered feet."],
    si: "Rock Ptarmigan — smaller bill, greyer in summer, male has a black eye stripe in winter.",
    h: "Willow and birch scrub, bogs and tree line.",
    di: "Khövsgöl, Khentii (Terelj), Khangai.",
    mi: "Resident; moves locally in winter.",
    fo: "Willow buds, leaves and berries.",
    br: "Nests on the ground; 6–10 eggs; male helps guard chicks.",
    be: "Burrows into snow to keep warm.",
    v: "A loud laughing ‘go-back, go-back’.",
    cu: "The state bird of Alaska.",
    co: "Least Concern.",
    w: "Willow thickets near Khövsgöl.",
    bt: "all year",
    fa: ["White in winter.", "Feathered feet like snowshoes.", "Sleeps in snow burrows."]
  },
  "rock-ptarmigan": {
    T: { c: { white: 0.5, gray: 0.25, brown: 0.2, black: 0.05 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["31–35 cm", "54–60 cm", "400–600 g"] },
    s: "A mountain grouse of rocky summits, white in winter and grey-brown in summer. Resident on the highest peaks of the Altai, Khangai and Khövsgöl.",
    d: "The Rock Ptarmigan lives on Arctic tundra and high mountains. It moults three times a year to match the landscape. In Mongolia it lives above the tree line in the Khangai, Khövsgöl and the Altai (Tavan Bogd, Uvs region).",
    f: ["Winter: white; male with a black line from bill to eye.", "Summer: finely barred grey-brown with white wings.", "Small black bill.", "Feathered feet."],
    si: "Willow Grouse — larger bill, lower altitude, redder in summer.",
    h: "Rocky alpine tundra.",
    di: "Khangai, Khövsgöl, Altai (Tavan Bogd), Uvs.",
    mi: "Resident.",
    fo: "Buds, leaves, berries and seeds.",
    br: "Nests in a scrape among rocks; 6–9 eggs.",
    be: "Relies on camouflage; very tame.",
    v: "A dry, croaking rattle.",
    cu: "A symbol of Arctic survival in Inuit culture.",
    co: "Least Concern.",
    w: "Alpine plateaus of the Khangai in June.",
    bt: "June–August",
    fa: ["Moults three times a year.", "Lives above the tree line.", "Very tame."]
  },
  "western-capercaillie": {
    T: { c: { black: 0.45, brown: 0.3, white: 0.1, red: 0.05, gray: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["60–87 cm", "90–125 cm", "1.5–4.5 kg"] },
    s: "The largest grouse in the world; the male is dark with a white shoulder spot and a pale bill. Very rare in Mongolia, known from a few old records.",
    d: "The Western Capercaillie lives in the pine forests of Europe and western Siberia. In Mongolia its range meets that of the Black-billed Capercaillie, and there are only a few records from the west and north.",
    f: ["Male: huge, dark grey-black with a green breast and white shoulder spot.", "Pale ivory bill.", "Red comb over the eye.", "Female: brown barred with an orange breast."],
    si: "Black-billed Capercaillie — black bill, white spots on wings and tail.",
    h: "Old pine forest.",
    di: "Very rare; north-west Mongolia.",
    mi: "Resident.",
    fo: "Pine needles, buds and berries.",
    br: "Nests on the forest floor; 5–8 eggs.",
    be: "Males display at leks in spring.",
    v: "A strange clicking and popping song.",
    cu: "Its display song ends with a sound like a cork popping.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["World’s largest grouse.", "Eats pine needles in winter.", "Displays at leks."]
  },
  "black-billed-capercaillie": {
    T: { c: { black: 0.5, brown: 0.25, white: 0.15, red: 0.05, rufous: 0.05 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["69–97 cm", "—", "1.7–4 kg"] },
    s: "A huge, dark forest grouse with a black bill and bold white spots on wings and tail. A resident of larch forests; famous at Bogd Khan Uul and Terelj.",
    d: "The Black-billed Capercaillie lives in the larch taiga of eastern Siberia, north Mongolia and north-east China. Males gather at leks at dawn in spring. In Mongolia it is found in the Khentii (Bogd Khan Uul near Ulaanbaatar, Terelj) and the Khangai.",
    f: ["Male: black with white spots on the wings and upper tail.", "Black bill.", "Long, graduated tail.", "Female: rufous-brown barred."],
    si: "Western Capercaillie — pale bill, green breast. Black Grouse — smaller, lyre tail.",
    h: "Larch and pine forest.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khangai (Orkhon), Khövsgöl.",
    mi: "Resident.",
    fo: "Larch needles, buds and berries.",
    br: "Nests on the forest floor; 5–9 eggs.",
    be: "Lekking at dawn in April–May.",
    v: "Clicks and rattles at the lek.",
    cu: "Protected on Bogd Khan Uul, one of the world’s oldest protected mountains.",
    co: "Least Concern; in the Mongolian Red Book.",
    w: "Bogd Khan Uul and Terelj forests in May, at dawn.",
    bt: "April–May",
    fa: ["Lives in larch forests.", "White spots on the wings.", "Lives near Ulaanbaatar."]
  },
  "daurian-partridge": {
    T: { c: { gray: 0.35, rufous: 0.3, brown: 0.25, black: 0.1 }, hb: ["steppe", "forest"], bk: "short", bh: ["walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["28–30 cm", "—", "200–350 g"] },
    s: "A small partridge with an orange face, a black belly patch and a ‘beard’ of feathers in winter. A resident of steppe and forest edges.",
    d: "The Daurian Partridge lives from Central Asia to north-east China. It forms coveys in winter and grows long feathers on the throat. In Mongolia it is common around Ulaanbaatar, Khustai, Terelj and the Khurkh valley.",
    f: ["Orange face and throat.", "Grey breast with a black horseshoe on the belly.", "Chestnut bars on the flanks.", "Winter ‘beard’ of throat feathers."],
    si: "Chukar — cream throat with black necklace, red bill.",
    h: "Steppe with shrubs, forest edges and fields.",
    di: "Ulaanbaatar, Khustai, Terelj, Khurkh, Khar Us Nuur, Ikh Nart.",
    mi: "Resident.",
    fo: "Seeds, shoots and insects.",
    br: "Nests on the ground; 10–18 eggs.",
    be: "Lives in coveys in winter.",
    v: "A creaking ‘kirr-ik’.",
    cu: "Named after Dauria, the region east of Lake Baikal.",
    co: "Least Concern.",
    w: "Khustai and Bogd Khan Uul edges in winter.",
    bt: "all year",
    fa: ["Grows a winter beard.", "Large clutches.", "Named after Dauria."]
  },
  "rock-dove": {
    T: { c: { gray: 0.65, white: 0.1, black: 0.15, red: 0.05 }, hb: ["mountain", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["resident"], sz: ["29–35 cm", "62–72 cm", "240–380 g"] },
    s: "The wild ancestor of the town pigeon: blue-grey with two black wing bars and a white rump. Wild birds live on Gobi cliffs; town birds fill Ulaanbaatar.",
    d: "The Rock Dove lives wild on cliffs across Eurasia and Africa, and its domestic descendants live in cities worldwide. In Mongolia wild birds nest in rocky gorges such as Yolyn Am, while feral pigeons are abundant in Ulaanbaatar and towns.",
    f: ["Blue-grey with a glossy green-purple neck.", "Two black bars across the wing.", "White rump (in wild birds).", "Red eye."],
    si: "Hill Pigeon — white tail band, pale back. Stock Dove — no black bars, no white rump.",
    h: "Cliffs, gorges and towns.",
    di: "Ulaanbaatar, Yolyn Am, Khustai, Terelj, Khar Us Nuur, Orog Nuur.",
    mi: "Resident.",
    fo: "Seeds and grain.",
    br: "Nests on ledges or buildings; 2 eggs; several broods.",
    be: "Flies in fast flocks.",
    v: "A cooing ‘oo-roo-coo’.",
    cu: "Domesticated over 5,000 years ago; used as messenger pigeons.",
    co: "Least Concern.",
    w: "Yolyn Am cliffs; any town.",
    bt: "all year",
    fa: ["Ancestor of town pigeons.", "Used to carry messages.", "Feeds chicks with ‘pigeon milk’."]
  },
  "hill-pigeon": {
    T: { c: { gray: 0.55, white: 0.3, black: 0.15 }, hb: ["mountain", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["resident"], sz: ["31–35 cm", "—", "230–300 g"] },
    s: "A pale grey pigeon with a broad white band across its dark tail. A common resident of cliffs and villages across Mongolia.",
    d: "The Hill Pigeon lives in the mountains of Central and East Asia. It nests in cliffs and also in buildings and ger roofs in villages. In Mongolia it is widespread, from Khar Us Nuur and Khövsgöl to Ulaanbaatar, Terelj and Yolyn Am.",
    f: ["Pale grey back.", "Dark tail with a broad white band across the middle.", "Two black wing bars.", "White rump."],
    si: "Rock Dove — no white tail band.",
    h: "Cliffs, gorges and villages.",
    di: "Khar Us Nuur, Ulaanbaatar, Terelj, Yolyn Am, Khurkh, Khövsgöl.",
    mi: "Resident.",
    fo: "Seeds and grain.",
    br: "Colonial on cliffs or buildings; 2 eggs.",
    be: "Flocks feed on steppe and fields.",
    v: "A deep ‘gut-gut’.",
    cu: "Often nests in monasteries and old buildings.",
    co: "Least Concern.",
    w: "Terelj rocks and village roofs.",
    bt: "all year",
    fa: ["White band across the tail.", "Nests in cliffs and houses.", "Common across Mongolia."]
  },
  "stock-dove": {
    T: { c: { gray: 0.7, black: 0.1, rufous: 0.1, white: 0.1 }, hb: ["forest", "steppe"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["passage"], sz: ["28–32 cm", "60–66 cm", "250–340 g"] },
    s: "A plain blue-grey pigeon with a glossy green neck and dark eyes. A rare migrant in Mongolia.",
    d: "The Stock Dove nests in tree holes in Europe and western Asia. Rare records in Mongolia come from the west and around Ulaanbaatar.",
    f: ["All grey with a glossy green neck patch.", "Dark eye.", "Short black bars on the wing.", "No white rump."],
    si: "Rock Dove — white rump, bold wing bars.",
    h: "Open woodland and farmland.",
    di: "Rare; Ulaanbaatar, Khar Us Nuur.",
    mi: "Rare migrant.",
    fo: "Seeds.",
    br: "Nests in tree holes (not in Mongolia).",
    be: "Flies in small groups.",
    v: "A deep ‘oo-roo’.",
    cu: "Its name refers to ‘stock’ meaning tree trunk.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Nests in tree holes.", "Dark eye.", "Rare in Mongolia."]
  },
  "pale-backed-pigeon": {
    T: { c: { gray: 0.6, buff: 0.2, white: 0.1, black: 0.1 }, hb: ["desert"], bk: "short", bh: ["walk"], vt: ["hoot"], ac: "day", se: ["passage"], sz: ["29–31 cm", "—", "200–260 g"] },
    s: "A small, pale pigeon of Central Asian deserts. On the Mongolian list, with no GBIF records; Vulnerable.",
    d: "The Pale-backed (Yellow-eyed) Pigeon breeds in Central Asian oases and winters in Pakistan and India. It is Vulnerable. Any record in Mongolia would be exceptional.",
    f: ["Pale grey back.", "Yellow eye-ring.", "Pinkish breast.", "Short wing bars."],
    si: "Stock Dove — darker, dark eye.",
    h: "Desert oases with trees.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Seeds.",
    br: "Nests in tree holes (not in Mongolia).",
    be: "Feeds in flocks.",
    v: "Soft cooing.",
    cu: "Named after the naturalist Eduard Eversmann.",
    co: "Vulnerable.",
    w: "Not expected.",
    bt: "—",
    fa: ["Yellow eyes.", "Vulnerable.", "Central Asian species."]
  },
  "wood-pigeon": {
    T: { c: { gray: 0.6, white: 0.15, rufous: 0.15, black: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["passage"], sz: ["38–44 cm", "68–77 cm", "300–615 g"] },
    s: "A large, plump pigeon with white neck patches and white wing bands. A scarce autumn migrant, mainly in western Mongolia.",
    d: "The Common Wood Pigeon breeds from Europe to Central Asia. Eastern birds migrate in large flocks. In Mongolia it is a scarce migrant, mostly in October–December, in the west (Khar Us Nuur, Ölgii).",
    f: ["Large grey pigeon.", "White patch on the neck.", "White band across the wing in flight.", "Pinkish breast."],
    si: "Rock Dove and Hill Pigeon — smaller, no white neck patch.",
    h: "Woodland and parks.",
    di: "Western Mongolia (Khar Us Nuur, Ölgii), Ulaanbaatar.",
    mi: "Scarce migrant, September–December.",
    fo: "Seeds, grain and buds.",
    br: "Nests in trees (not confirmed in Mongolia).",
    be: "Claps its wings in display.",
    v: "A soft ‘coo-COO-coo, coo-coo’.",
    cu: "Europe’s commonest pigeon.",
    co: "Least Concern.",
    w: "Western Mongolia in autumn.",
    bt: "October–November",
    fa: ["White neck patch.", "Claps its wings.", "Large pigeon."]
  },
  "european-turtle-dove": {
    T: { c: { rufous: 0.4, gray: 0.3, black: 0.15, white: 0.15 }, hb: ["forest", "steppe"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["summer"], sz: ["26–28 cm", "47–53 cm", "85–170 g"] },
    s: "A slim dove with a scaly chestnut back and a black-and-white striped neck patch. A rare summer visitor to western Mongolia; Vulnerable.",
    d: "The European Turtle Dove breeds from Europe to western China and winters in Africa. It has declined steeply because of hunting and habitat loss. In Mongolia it is rare, in the far west.",
    f: ["Rufous back with black centres to the feathers.", "Black-and-white striped neck patch.", "Blue-grey head.", "Dark tail with white tips."],
    si: "Oriental Turtle Dove — larger, darker, grey tail tips.",
    h: "Woodland edges and scrub.",
    di: "Rare; far western Mongolia.",
    mi: "Summer visitor, May–September.",
    fo: "Seeds.",
    br: "Nests in shrubs; 2 eggs.",
    be: "Shy.",
    v: "A purring ‘turrr-turrr’.",
    cu: "A symbol of love in European poetry.",
    co: "Vulnerable.",
    w: "Not expected.",
    bt: "—",
    fa: ["Purring song.", "Vulnerable.", "Winters in Africa."]
  },
  "east-asian-turtle-dove": {
    T: { c: { rufous: 0.35, gray: 0.35, brown: 0.15, black: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["summer"], sz: ["33–35 cm", "53–60 cm", "180–270 g"] },
    s: "A large, dark turtle dove with scaly rufous upperparts and a striped neck patch. A summer visitor to woods and towns in northern and eastern Mongolia.",
    d: "The Oriental Turtle Dove breeds from Central Asia to Japan. In Mongolia it breeds in woodland, parks and river valleys, including Ulaanbaatar, the Khurkh valley and Terelj, and passes through Gobi oases.",
    f: ["Scaly rufous and black back.", "Striped black-and-grey neck patch.", "Pinkish-brown breast.", "Dark tail with grey tips."],
    si: "European Turtle Dove — smaller, paler, white tail tips. Eurasian Collared Dove — plain grey-buff, single black collar.",
    h: "Woodland, parks and river valleys.",
    di: "Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Dornod (Ganga Nuur).",
    mi: "Summer visitor, April–October; peaks in May and September.",
    fo: "Seeds and grain.",
    br: "Nests in trees; 2 eggs.",
    be: "Feeds on the ground.",
    v: "A deep ‘dur-dur-dudu’.",
    cu: "Common in Asian towns.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in May.",
    bt: "May–September",
    fa: ["Scaly back.", "Striped neck patch.", "Common in towns."]
  },
  "eurasian-collared-dove": {
    T: { c: { buff: 0.5, gray: 0.35, black: 0.1, white: 0.05 }, hb: ["settlement", "desert"], bk: "short", bh: ["walk", "perch"], vt: ["hoot"], ac: "day", se: ["resident"], sz: ["31–33 cm", "47–55 cm", "125–240 g"] },
    s: "A pale sandy-grey dove with a black half-collar. Has spread into Gobi oases and towns, including Ulaanbaatar.",
    d: "The Eurasian Collared Dove spread across Europe in the 20th century and has recently reached Mongolia. It lives near people in towns and oases. It is now common at Yolyn Am, in Gobi towns and in Ulaanbaatar.",
    f: ["Pale grey-buff body.", "Narrow black half-collar on the neck.", "Dark wingtips.", "Long tail with white underside."],
    si: "Oriental Turtle Dove — scaly back, striped neck patch.",
    h: "Towns, villages and oases.",
    di: "Gobi (Yolyn Am, Orog Nuur, Ikh Nart), Ulaanbaatar, Khurkh.",
    mi: "Resident.",
    fo: "Seeds and grain.",
    br: "Nests in trees or on buildings; 2 eggs; many broods.",
    be: "Lives close to people.",
    v: "A repeated ‘coo-COO-cuk’.",
    cu: "One of the fastest-spreading birds in the world.",
    co: "Least Concern.",
    w: "Dalanzadgad and Yolyn Am.",
    bt: "all year",
    fa: ["Spreading fast.", "Black half-collar.", "Lives near people."]
  },
  "laughing-dove": {
    T: { c: { rufous: 0.4, gray: 0.3, buff: 0.2, black: 0.1 }, hb: ["desert", "settlement"], bk: "short", bh: ["walk"], vt: ["hoot"], ac: "day", se: ["passage"], sz: ["23–26 cm", "40–45 cm", "70–140 g"] },
    s: "A small, reddish dove with a chequered black-spotted breast. A rare visitor to Gobi oases.",
    d: "The Laughing Dove lives in Africa, the Middle East and South Asia and is spreading. There are a few recent records in Mongolia, from Yolyn Am and the west.",
    f: ["Small and pinkish-brown.", "Breast band of black spots.", "Blue-grey wing panel.", "Long tail with white corners."],
    si: "Eurasian Collared Dove — larger, black collar.",
    h: "Oases and towns.",
    di: "Rare; Yolyn Am, Orog Nuur, western Mongolia.",
    mi: "Rare visitor.",
    fo: "Seeds.",
    br: "Nests in trees (not in Mongolia).",
    be: "Feeds on the ground.",
    v: "A soft, laughing ‘oo-oo-oo-oo’.",
    cu: "Named for its laughing call.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Laughing call.", "Spotted breast.", "Spreading."]
  }
});
