B2T("fr", {
  "willow-grouse": {
    name: "Lagopède des saules",
    s: "Tétras dodu, blanc pur en hiver et marron vif en été, aux ailes blanches toute l’année. Résident des fourrés de saules des montagnes du nord.",
    d: "Le Lagopède des saules vit dans la toundra et la taïga de l’extrême nord. Ses pattes emplumées lui servent de raquettes. En Mongolie, il vit dans les fourrés de saules et de bouleaux nains du Khövsgöl, du Khentii et du Khangaï, souvent près de la limite des arbres.",
    f: ["Hiver : entièrement blanc, queue noire.", "Été : tête et corps brun marron, ailes et ventre blancs.", "« Sourcil » rouge chez le mâle.", "Pattes emplumées."],
    si: "Lagopède alpin — bec plus petit, plus gris en été, mâle à trait noir sur l’œil en hiver.",
    h: "Fourrés de saules et de bouleaux, tourbières et limite des arbres.",
    di: "Khövsgöl, Khentii (Terelj), Khangaï.",
    mi: "Résident ; déplacements locaux en hiver.",
    fo: "Bourgeons, feuilles et baies de saule.",
    br: "Niche au sol ; 6 à 10 œufs ; le mâle aide à garder les poussins.",
    be: "S’enfouit dans la neige pour rester au chaud.",
    v: "Un fort « go-back, go-back » rieur.",
    cu: "Oiseau emblème de l’Alaska.",
    co: "Préoccupation mineure.",
    w: "Fourrés de saules près du Khövsgöl.",
    bt: "toute l’année",
    fa: ["Blanc en hiver.", "Pattes emplumées comme des raquettes.", "Dort dans des terriers de neige."]
  },
  "rock-ptarmigan": {
    name: "Lagopède alpin",
    s: "Tétras de montagne des sommets rocheux, blanc en hiver et gris-brun en été. Résident des plus hauts sommets de l’Altaï, du Khangaï et du Khövsgöl.",
    d: "Le Lagopède alpin vit dans la toundra arctique et les hautes montagnes. Il mue trois fois par an pour s’accorder au paysage. En Mongolie, il vit au-dessus de la limite des arbres dans le Khangaï, le Khövsgöl et l’Altaï (Tavan Bogd, région d’Uvs).",
    f: ["Hiver : blanc ; le mâle a une ligne noire du bec à l’œil.", "Été : gris-brun finement barré à ailes blanches.", "Petit bec noir.", "Pattes emplumées."],
    si: "Lagopède des saules — bec plus fort, altitude plus basse, plus roux en été.",
    h: "Toundra alpine rocheuse.",
    di: "Khangaï, Khövsgöl, Altaï (Tavan Bogd), Uvs.",
    mi: "Résident.",
    fo: "Bourgeons, feuilles, baies et graines.",
    br: "Niche dans une cuvette entre les rochers ; 6 à 9 œufs.",
    be: "Compte sur son camouflage ; très confiant.",
    v: "Un crépitement sec et rauque.",
    cu: "Symbole de survie arctique dans la culture inuite.",
    co: "Préoccupation mineure.",
    w: "Plateaux alpins du Khangaï en juin.",
    bt: "juin–août",
    fa: ["Mue trois fois par an.", "Vit au-dessus de la limite des arbres.", "Très confiant."]
  },
  "western-capercaillie": {
    name: "Grand Tétras",
    s: "Le plus grand tétras du monde ; le mâle est sombre avec une tache blanche à l’épaule et un bec pâle. Très rare en Mongolie, connu par quelques anciennes mentions.",
    d: "Le Grand Tétras vit dans les pinèdes d’Europe et de Sibérie occidentale. En Mongolie, son aire rejoint celle du Tétras à bec noir, et il n’existe que quelques mentions dans l’ouest et le nord.",
    f: ["Mâle : énorme, gris-noir à poitrine verte et tache blanche à l’épaule.", "Bec ivoire pâle.", "Caroncule rouge au-dessus de l’œil.", "Femelle : brune barrée à poitrine orangée."],
    si: "Tétras à bec noir — bec noir, taches blanches aux ailes et à la queue.",
    h: "Vieilles pinèdes.",
    di: "Très rare ; nord-ouest de la Mongolie.",
    mi: "Résident.",
    fo: "Aiguilles de pin, bourgeons et baies.",
    br: "Niche au sol en forêt ; 5 à 8 œufs.",
    be: "Les mâles paradent sur des places de chant au printemps.",
    v: "Un étrange chant de claquements et de « pop ».",
    cu: "Son chant se termine par un bruit de bouchon qui saute.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Plus grand tétras du monde.", "Mange des aiguilles de pin en hiver.", "Parade sur des places de chant."]
  },
  "black-billed-capercaillie": {
    name: "Tétras à bec noir",
    s: "Énorme tétras forestier sombre au bec noir et aux grosses taches blanches sur les ailes et la queue. Résident des forêts de mélèzes ; célèbre au Bogd Khan Uul et à Terelj.",
    d: "Le Tétras à bec noir vit dans la taïga de mélèzes de Sibérie orientale, du nord de la Mongolie et du nord-est de la Chine. Au printemps, les mâles se rassemblent à l’aube sur des places de parade. En Mongolie, il vit dans le Khentii (Bogd Khan Uul près d’Oulan-Bator, Terelj) et le Khangaï.",
    f: ["Mâle : noir avec des taches blanches sur les ailes et le dessus de la queue.", "Bec noir.", "Longue queue étagée.", "Femelle : brun roux barré."],
    si: "Grand Tétras — bec pâle, poitrine verte. Tétras lyre — plus petit, queue en lyre.",
    h: "Forêts de mélèzes et de pins.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khangaï (Orkhon), Khövsgöl.",
    mi: "Résident.",
    fo: "Aiguilles de mélèze, bourgeons et baies.",
    br: "Niche au sol en forêt ; 5 à 9 œufs.",
    be: "Parades à l’aube en avril–mai.",
    v: "Claquements et crépitements sur la place de parade.",
    cu: "Protégé au Bogd Khan Uul, l’une des plus anciennes montagnes protégées du monde.",
    co: "Préoccupation mineure ; inscrit au Livre rouge de Mongolie.",
    w: "Forêts du Bogd Khan Uul et de Terelj en mai, à l’aube.",
    bt: "avril–mai",
    fa: ["Vit dans les forêts de mélèzes.", "Taches blanches sur les ailes.", "Vit près d’Oulan-Bator."]
  },
  "daurian-partridge": {
    name: "Perdrix de Daourie",
    s: "Petite perdrix à face orange, plaque ventrale noire et « barbe » de plumes en hiver. Résidente des steppes et lisières.",
    d: "La Perdrix de Daourie vit de l’Asie centrale au nord-est de la Chine. Elle forme des compagnies en hiver et développe de longues plumes sur la gorge. En Mongolie, elle est commune autour d’Oulan-Bator, de Khustai, de Terelj et de la vallée de Khurkh.",
    f: ["Face et gorge orange.", "Poitrine grise avec un fer à cheval noir sur le ventre.", "Barres marron sur les flancs.", "« Barbe » hivernale de plumes gulaires."],
    si: "Perdrix choukar — gorge crème à collier noir, bec rouge.",
    h: "Steppe arbustive, lisières et champs.",
    di: "Oulan-Bator, Khustai, Terelj, Khurkh, lac Khar Us, Ikh Nart.",
    mi: "Résidente.",
    fo: "Graines, pousses et insectes.",
    br: "Niche au sol ; 10 à 18 œufs.",
    be: "Vit en compagnies en hiver.",
    v: "Un « kirr-ik » grinçant.",
    cu: "Nommée d’après la Daourie, région à l’est du Baïkal.",
    co: "Préoccupation mineure.",
    w: "Bords de Khustai et du Bogd Khan Uul en hiver.",
    bt: "toute l’année",
    fa: ["Porte une barbe en hiver.", "Grandes pontes.", "Nommée d’après la Daourie."]
  },
  "rock-dove": {
    name: "Pigeon biset",
    s: "L’ancêtre sauvage du pigeon des villes : gris-bleu à deux barres alaires noires et croupion blanc. Les oiseaux sauvages vivent sur les falaises du Gobi ; ceux des villes peuplent Oulan-Bator.",
    d: "Le Pigeon biset vit à l’état sauvage sur les falaises d’Eurasie et d’Afrique, et ses descendants domestiques peuplent les villes du monde entier. En Mongolie, les oiseaux sauvages nichent dans les gorges rocheuses comme Yolyn Am, tandis que les pigeons domestiques retournés à l’état sauvage abondent à Oulan-Bator et dans les villes.",
    f: ["Gris-bleu, cou irisé vert et pourpre.", "Deux barres noires sur l’aile.", "Croupion blanc (oiseaux sauvages).", "Œil rouge."],
    si: "Pigeon des rochers — bande blanche sur la queue, dos pâle. Pigeon colombin — sans barres noires ni croupion blanc.",
    h: "Falaises, gorges et villes.",
    di: "Oulan-Bator, Yolyn Am, Khustai, Terelj, lac Khar Us, lac Orog.",
    mi: "Résident.",
    fo: "Graines et céréales.",
    br: "Niche sur des corniches ou bâtiments ; 2 œufs ; plusieurs couvées.",
    be: "Vole en groupes rapides.",
    v: "Un roucoulement « ou-rou-cou ».",
    cu: "Domestiqué il y a plus de 5 000 ans ; utilisé comme pigeon voyageur.",
    co: "Préoccupation mineure.",
    w: "Falaises de Yolyn Am ; toute ville.",
    bt: "toute l’année",
    fa: ["Ancêtre des pigeons des villes.", "Servait à porter des messages.", "Nourrit ses petits de « lait de pigeon »."]
  },
  "hill-pigeon": {
    name: "Pigeon des rochers",
    s: "Pigeon gris pâle à large bande blanche en travers de la queue sombre. Résident commun des falaises et villages de toute la Mongolie.",
    d: "Le Pigeon des rochers vit dans les montagnes d’Asie centrale et orientale. Il niche dans les falaises mais aussi dans les bâtiments et les toits de yourtes des villages. En Mongolie, il est répandu, du lac Khar Us et du Khövsgöl à Oulan-Bator, Terelj et Yolyn Am.",
    f: ["Dos gris pâle.", "Queue sombre à large bande blanche médiane.", "Deux barres alaires noires.", "Croupion blanc."],
    si: "Pigeon biset — sans bande blanche sur la queue.",
    h: "Falaises, gorges et villages.",
    di: "Lac Khar Us, Oulan-Bator, Terelj, Yolyn Am, Khurkh, Khövsgöl.",
    mi: "Résident.",
    fo: "Graines et céréales.",
    br: "Colonial sur les falaises ou les bâtiments ; 2 œufs.",
    be: "Les groupes se nourrissent dans la steppe et les champs.",
    v: "Un « gout-gout » grave.",
    cu: "Niche souvent dans les monastères et vieux bâtiments.",
    co: "Préoccupation mineure.",
    w: "Rochers de Terelj et toits des villages.",
    bt: "toute l’année",
    fa: ["Bande blanche sur la queue.", "Niche dans les falaises et les maisons.", "Commun dans toute la Mongolie."]
  },
  "stock-dove": {
    name: "Pigeon colombin",
    s: "Pigeon gris-bleu uni au cou vert irisé et aux yeux sombres. Migrateur rare en Mongolie.",
    d: "Le Pigeon colombin niche dans les cavités d’arbres en Europe et en Asie occidentale. Les rares mentions mongoles viennent de l’ouest et des environs d’Oulan-Bator.",
    f: ["Entièrement gris avec une tache verte irisée sur le cou.", "Œil sombre.", "Courtes barres noires sur l’aile.", "Pas de croupion blanc."],
    si: "Pigeon biset — croupion blanc, barres alaires marquées.",
    h: "Bois clairs et cultures.",
    di: "Rare ; Oulan-Bator, lac Khar Us.",
    mi: "Migrateur rare.",
    fo: "Graines.",
    br: "Niche dans des cavités d’arbres (pas en Mongolie).",
    be: "Vole en petits groupes.",
    v: "Un « ou-rou » grave.",
    cu: "Son nom anglais « stock » désigne un tronc d’arbre.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Niche dans les arbres creux.", "Œil sombre.", "Rare en Mongolie."]
  },
  "pale-backed-pigeon": {
    name: "Pigeon d’Eversmann",
    s: "Petit pigeon pâle des déserts d’Asie centrale. Sur la liste mongole, sans mention GBIF ; Vulnérable.",
    d: "Le Pigeon d’Eversmann niche dans les oasis d’Asie centrale et hiverne au Pakistan et en Inde. Il est Vulnérable. Toute mention en Mongolie serait exceptionnelle.",
    f: ["Dos gris pâle.", "Cercle orbital jaune.", "Poitrine rosée.", "Courtes barres alaires."],
    si: "Pigeon colombin — plus sombre, œil sombre.",
    h: "Oasis boisées des déserts.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Graines.",
    br: "Niche dans des cavités d’arbres (pas en Mongolie).",
    be: "Se nourrit en groupes.",
    v: "Doux roucoulements.",
    cu: "Nommé d’après le naturaliste Eduard Eversmann.",
    co: "Vulnérable.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Yeux jaunes.", "Vulnérable.", "Espèce d’Asie centrale."]
  },
  "wood-pigeon": {
    name: "Pigeon ramier",
    s: "Grand pigeon dodu aux taches blanches sur le cou et aux bandes blanches sur les ailes. Migrateur d’automne peu commun, surtout dans l’ouest de la Mongolie.",
    d: "Le Pigeon ramier niche de l’Europe à l’Asie centrale. Les oiseaux orientaux migrent en grands vols. En Mongolie, c’est un migrateur peu commun, surtout en octobre–décembre, dans l’ouest (lac Khar Us, Ölgii).",
    f: ["Grand pigeon gris.", "Tache blanche sur le cou.", "Bande blanche en travers de l’aile en vol.", "Poitrine rosée."],
    si: "Pigeon biset et Pigeon des rochers — plus petits, sans tache blanche au cou.",
    h: "Bois et parcs.",
    di: "Ouest (lac Khar Us, Ölgii), Oulan-Bator.",
    mi: "Migrateur peu commun, septembre–décembre.",
    fo: "Graines, céréales et bourgeons.",
    br: "Niche dans les arbres (non confirmé en Mongolie).",
    be: "Claque des ailes en parade.",
    v: "Un doux « cou-COU-cou, cou-cou ».",
    cu: "Le pigeon le plus commun d’Europe.",
    co: "Préoccupation mineure.",
    w: "Ouest de la Mongolie en automne.",
    bt: "oct.–nov.",
    fa: ["Tache blanche au cou.", "Claque des ailes.", "Grand pigeon."]
  },
  "european-turtle-dove": {
    name: "Tourterelle des bois",
    s: "Tourterelle élancée au dos roux écailleux et à la tache de cou rayée noir et blanc. Visiteuse d’été rare dans l’ouest de la Mongolie ; Vulnérable.",
    d: "La Tourterelle des bois niche de l’Europe à l’ouest de la Chine et hiverne en Afrique. Elle a fortement décliné à cause de la chasse et de la perte d’habitat. En Mongolie, elle est rare, dans l’extrême ouest.",
    f: ["Dos roux à centres des plumes noirs.", "Tache rayée noir et blanc sur le cou.", "Tête gris-bleu.", "Queue sombre à extrémités blanches."],
    si: "Tourterelle orientale — plus grande, plus sombre, extrémités de queue grises.",
    h: "Lisières et broussailles.",
    di: "Rare ; extrême ouest de la Mongolie.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Graines.",
    br: "Niche dans les buissons ; 2 œufs.",
    be: "Farouche.",
    v: "Un ronronnement « tourrr-tourrr ».",
    cu: "Symbole d’amour dans la poésie européenne.",
    co: "Vulnérable.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Chant ronronnant.", "Vulnérable.", "Hiverne en Afrique."]
  },
  "east-asian-turtle-dove": {
    name: "Tourterelle orientale",
    s: "Grande tourterelle sombre au dos roux écailleux et à la tache de cou rayée. Visiteuse d’été des bois et des villes du nord et de l’est de la Mongolie.",
    d: "La Tourterelle orientale niche de l’Asie centrale au Japon. En Mongolie, elle niche dans les bois, parcs et vallées, notamment à Oulan-Bator, dans la vallée de Khurkh et à Terelj, et passe par les oasis du Gobi.",
    f: ["Dos écailleux roux et noir.", "Tache de cou rayée noir et gris.", "Poitrine brun rosé.", "Queue sombre à extrémités grises."],
    si: "Tourterelle des bois — plus petite, plus pâle, extrémités blanches. Tourterelle turque — gris-chamois uni, simple collier noir.",
    h: "Bois, parcs et vallées fluviales.",
    di: "Oulan-Bator, Khurkh, Terelj, Yolyn Am, Dornod (lac Ganga).",
    mi: "Visiteuse d’été, avril–octobre ; pics en mai et septembre.",
    fo: "Graines et céréales.",
    br: "Niche dans les arbres ; 2 œufs.",
    be: "Se nourrit au sol.",
    v: "Un « dour-dour-doudou » grave.",
    cu: "Commune dans les villes d’Asie.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en mai.",
    bt: "mai–sept.",
    fa: ["Dos écailleux.", "Tache rayée sur le cou.", "Commune en ville."]
  },
  "eurasian-collared-dove": {
    name: "Tourterelle turque",
    s: "Tourterelle gris sable pâle à demi-collier noir. S’est répandue dans les oasis du Gobi et les villes, dont Oulan-Bator.",
    d: "La Tourterelle turque a conquis l’Europe au XXᵉ siècle et a récemment atteint la Mongolie. Elle vit près des humains dans les villes et oasis. Elle est désormais commune à Yolyn Am, dans les villes du Gobi et à Oulan-Bator.",
    f: ["Corps gris-chamois pâle.", "Étroit demi-collier noir sur le cou.", "Extrémités des ailes sombres.", "Longue queue à dessous blanc."],
    si: "Tourterelle orientale — dos écailleux, tache rayée sur le cou.",
    h: "Villes, villages et oasis.",
    di: "Gobi (Yolyn Am, lac Orog, Ikh Nart), Oulan-Bator, Khurkh.",
    mi: "Résidente.",
    fo: "Graines et céréales.",
    br: "Niche dans les arbres ou sur les bâtiments ; 2 œufs ; nombreuses couvées.",
    be: "Vit près des humains.",
    v: "Un « cou-COU-couk » répété.",
    cu: "L’un des oiseaux à l’expansion la plus rapide au monde.",
    co: "Préoccupation mineure.",
    w: "Dalanzadgad et Yolyn Am.",
    bt: "toute l’année",
    fa: ["En expansion rapide.", "Demi-collier noir.", "Vit près des humains."]
  },
  "laughing-dove": {
    name: "Tourterelle maillée",
    s: "Petite tourterelle rougeâtre à poitrine mouchetée de noir. Visiteuse rare des oasis du Gobi.",
    d: "La Tourterelle maillée vit en Afrique, au Moyen-Orient et en Asie du Sud et s’étend. On compte quelques mentions récentes en Mongolie, à Yolyn Am et dans l’ouest.",
    f: ["Petite, brun rosé.", "Bande de taches noires sur la poitrine.", "Panneau alaire gris-bleu.", "Longue queue à coins blancs."],
    si: "Tourterelle turque — plus grande, collier noir.",
    h: "Oasis et villes.",
    di: "Rare ; Yolyn Am, lac Orog, ouest de la Mongolie.",
    mi: "Visiteuse rare.",
    fo: "Graines.",
    br: "Niche dans les arbres (pas en Mongolie).",
    be: "Se nourrit au sol.",
    v: "Un doux « ou-ou-ou-ou » rieur.",
    cu: "Son nom anglais évoque son chant rieur.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Chant rieur.", "Poitrine mouchetée.", "En expansion."]
  }
});
