B2T("en", {
  "indian-cuckoo": {
    T: { c: { gray: 0.45, brown: 0.3, white: 0.2, black: 0.05 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["32–33 cm", "—", "110–130 g"] },
    s: "A grey cuckoo with a brown back, known by its four-note call ‘one more bottle’. On the Mongolian list, with no GBIF records.",
    d: "The Indian Cuckoo breeds from India to south-east Siberia and lays its eggs in the nests of drongos and shrikes. It may occur in the far east of Mongolia, but there are no documented records.",
    f: ["Grey head and breast, brown back and wings.", "Barred belly.", "Broad dark band near the tail tip.", "Brown eye-ring."],
    si: "Common Cuckoo — grey back, different call.",
    h: "Broadleaf forest.",
    di: "Exceptional; possibly the far east.",
    mi: "Summer visitor.",
    fo: "Hairy caterpillars.",
    br: "Brood parasite.",
    be: "Calls from treetops.",
    v: "Four notes: ‘one-more-bot-tle’.",
    cu: "Its call is famous in India as a sign of the monsoon.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Four-note call.", "Lays eggs in other birds’ nests.", "Eats hairy caterpillars."]
  },
  "common-cuckoo": {
    T: { c: { gray: 0.55, white: 0.25, black: 0.1, rufous: 0.1 }, hb: ["forest", "steppe", "water"], bk: "short", bh: ["perch"], vt: ["hoot"], ac: "day", se: ["summer"], sz: ["32–34 cm", "55–65 cm", "100–140 g"] },
    s: "The famous ‘cuck-oo’ that lays its eggs in other birds’ nests. A common summer visitor across Mongolia, from forests to reedbeds.",
    d: "The Common Cuckoo breeds across Eurasia and winters in Africa. Females lay eggs matching those of their host species; the chick pushes out the host’s eggs. In Mongolia its call is heard everywhere in May–June — in Terelj, Ulaanbaatar, the Khurkh valley, Yolyn Am and Khustai.",
    f: ["Grey head, back and breast; barred white belly.", "Long tail with white spots.", "Pointed wings; hawk-like flight.", "Yellow eye-ring and feet.", "Some females are rufous (‘hepatic’)."],
    si: "Eurasian Sparrowhawk — rounded wings, hooked bill. Himalayan Cuckoo — hoopoe-like call, buff underparts.",
    h: "Forests, steppe with shrubs and reedbeds.",
    di: "All regions: Ulaanbaatar, Terelj, Khurkh, Yolyn Am, Khustai, Khar Us Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Hairy caterpillars and other insects.",
    br: "Brood parasite of pipits, warblers, wagtails and redstarts.",
    be: "Males call from treetops and posts.",
    v: "The famous ‘cuck-oo’; females make a bubbling call.",
    cu: "In Mongolian folklore counting cuckoo calls foretells the years of life.",
    co: "Least Concern.",
    w: "Terelj in June — listen at dawn.",
    bt: "May–June",
    fa: ["Lays eggs in other nests.", "Eats hairy caterpillars.", "Migrates to Africa."]
  },
  "himalayan-cuckoo": {
    T: { c: { gray: 0.45, buff: 0.25, white: 0.2, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["hoot"], ac: "day", se: ["summer"], sz: ["30–32 cm", "—", "80–120 g"] },
    s: "A cuckoo very like the Common Cuckoo but with a deep, hoopoe-like ‘poo-poo-poo-poo’ call. A rare summer visitor to the northern forests.",
    d: "The Oriental (Himalayan) Cuckoo complex breeds in the taiga of Siberia and in the Himalaya and winters in South-East Asia and Australia. In Mongolia a few are heard in the Khentii forests around Terelj and Ulaanbaatar.",
    f: ["Grey upperparts.", "Buffish underparts with bold dark bars.", "Buff undertail.", "Slightly smaller than the Common Cuckoo."],
    si: "Common Cuckoo — whiter below, finer bars, different call.",
    h: "Coniferous and mixed forest.",
    di: "Khentii (Terelj, Ulaanbaatar), Selenge.",
    mi: "Summer visitor, May–July.",
    fo: "Caterpillars.",
    br: "Brood parasite of leaf warblers.",
    be: "Calls from within the canopy.",
    v: "A deep ‘poo-poo-poo-poo’, like a Hoopoe.",
    cu: "Best identified by voice.",
    co: "Least Concern.",
    w: "Listen in Terelj forests in June.",
    bt: "June",
    fa: ["Sounds like a Hoopoe.", "Parasitises leaf warblers.", "Winters in Australia."]
  },
  "lesser-cuckoo": {
    T: { c: { gray: 0.5, white: 0.25, black: 0.15, rufous: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["22–27 cm", "—", "40–60 g"] },
    s: "The smallest grey cuckoo, with a loud, rhythmic song. On the Mongolian list, with no GBIF records.",
    d: "The Lesser Cuckoo breeds from the Himalaya to Japan and winters in Africa. It lays eggs in bush warbler nests. Mongolian records are exceptional.",
    f: ["Like a small Common Cuckoo.", "Grey upperparts, barred white belly.", "Dark eye."],
    si: "Common Cuckoo — larger.",
    h: "Forest edges and scrub.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Caterpillars.",
    br: "Brood parasite.",
    be: "Calls day and night.",
    v: "A staccato ‘tok-to-kyo-kyo-kyo’.",
    cu: "In Japan its song is said to mean ‘Tokkyo kyokakyoku’ (patent office).",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Smallest grey cuckoo.", "Calls at night.", "Winters in Africa."]
  },
  "grey-nightjar": {
    T: { c: { gray: 0.45, brown: 0.35, buff: 0.1, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["night", "perch"], vt: ["croak"], ac: "night", se: ["summer"], sz: ["28–32 cm", "—", "70–110 g"] },
    s: "A cryptic, grey-brown night bird with a tiny bill and huge mouth. A rare summer visitor to forests of the north-east.",
    d: "The Grey Nightjar breeds in eastern Asia and hunts moths at dusk. In Mongolia it has been recorded in the Khurkh valley and forests of Khentii.",
    f: ["Mottled grey-brown like tree bark.", "White throat patch.", "Male has white wing and tail spots.", "Long wings and tail."],
    si: "European Nightjar — paler, different song.",
    h: "Open forest and clearings.",
    di: "Rare; Khentii (Khurkh).",
    mi: "Summer visitor, June.",
    fo: "Moths and beetles caught in flight.",
    br: "Lays 2 eggs on the ground.",
    be: "Sits motionless on branches by day.",
    v: "A rapid ‘chuck-chuck-chuck’.",
    cu: "Called ‘jungle nightjar’ in India.",
    co: "Least Concern.",
    w: "Khurkh valley at dusk.",
    bt: "June",
    fa: ["Camouflaged like bark.", "Hunts at night.", "Huge mouth."]
  },
  "european-nightjar": {
    T: { c: { brown: 0.45, gray: 0.3, buff: 0.15, white: 0.1 }, hb: ["forest", "steppe", "desert"], bk: "short", bh: ["night", "perch"], vt: ["croak"], ac: "night", se: ["summer"], sz: ["24–28 cm", "52–59 cm", "50–100 g"] },
    s: "A long-winged night bird with bark-like camouflage and a churring song that lasts for minutes. A summer visitor to open woods and scrub, especially in the west.",
    d: "The European Nightjar breeds from Europe to Mongolia and winters in Africa. It hunts moths at dusk and sings a long, mechanical churr. In Mongolia it breeds in dry scrub and open woods, especially around Khar Us Nuur and in the Khurkh valley.",
    f: ["Grey-brown bark pattern.", "Flat head, tiny bill, large dark eyes.", "Male has white spots on wings and tail.", "Long wings and tail."],
    si: "Grey Nightjar — greyer, eastern.",
    h: "Open woodland, scrub and semi-desert.",
    di: "Khar Us Nuur, Khurkh, Ögii Nuur, Böön Tsagaan, Onon.",
    mi: "Summer visitor, May–September.",
    fo: "Moths and beetles.",
    br: "Lays 2 eggs on the ground.",
    be: "Hunts at dusk; claps its wings in display.",
    v: "A long ‘churrrrrr’.",
    cu: "Once called ‘goatsucker’ from a myth that it drank goats’ milk.",
    co: "Least Concern.",
    w: "Khar Us Nuur scrub at dusk in June.",
    bt: "June–July",
    fa: ["Churrs for minutes.", "Called ‘goatsucker’.", "Winters in Africa."]
  },
  "white-throated-needletail": {
    T: { c: { brown: 0.45, black: 0.3, white: 0.25 }, hb: ["forest", "water"], bk: "short", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["19–21 cm", "50–53 cm", "100–140 g"] },
    s: "A large, powerful swift with a white throat and white undertail — one of the fastest birds in level flight. A summer visitor to northern forests.",
    d: "The White-throated Needletail breeds in Siberia, north-east China and Japan and winters in Australia. It nests in hollow trees. In Mongolia it is found over forests and rivers in the Khentii (especially the Khurkh valley) and Dornod.",
    f: ["Bulky swift with a short square tail.", "White throat and white ‘horseshoe’ under the tail.", "Pale saddle on the back.", "Tail feathers end in spines."],
    si: "Fork-tailed Swift — forked tail, white rump.",
    h: "Over forests and rivers.",
    di: "Khentii (Khurkh, Terelj), Ulaanbaatar, Dornod.",
    mi: "Summer visitor, May–August.",
    fo: "Flying insects.",
    br: "Nests in hollow trees.",
    be: "Flies extremely fast; drinks in flight.",
    v: "High twittering.",
    cu: "Reported to fly at over 100 km/h.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["One of the fastest birds.", "Spiny tail tips.", "Nests in hollow trees."]
  },
  "fork-tailed-swift": {
    T: { c: { black: 0.6, brown: 0.2, white: 0.2 }, hb: ["mountain", "settlement"], bk: "short", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["17–18 cm", "48–54 cm", "30–50 g"] },
    s: "A dark swift with a white rump and a deeply forked tail. Very common in summer over cliffs and towns, including Ulaanbaatar.",
    d: "The Pacific (Fork-tailed) Swift breeds from Siberia to Japan and winters in Australia. In Mongolia it nests in rock crevices and buildings and is common over Ulaanbaatar, Yolyn Am, Terelj and Ögii Nuur.",
    f: ["Blackish with a broad white rump.", "Deeply forked tail.", "Pale throat.", "Scaly underparts."],
    si: "Common Swift — no white rump. Northern House Martin — smaller, white below.",
    h: "Cliffs, gorges and towns.",
    di: "Ulaanbaatar, Yolyn Am, Terelj, Ögii Nuur, Khurkh, Böön Tsagaan.",
    mi: "Summer visitor, May–August.",
    fo: "Flying insects.",
    br: "Colonial in crevices and buildings; 2–3 eggs.",
    be: "Screaming flocks at dusk.",
    v: "Shrill screaming.",
    cu: "Crosses the equator to winter in Australia.",
    co: "Least Concern.",
    w: "Over Ulaanbaatar on June evenings.",
    bt: "June–July",
    fa: ["White rump.", "Forked tail.", "Winters in Australia."]
  },
  "common-swift": {
    T: { c: { black: 0.75, brown: 0.2, white: 0.05 }, hb: ["mountain", "settlement"], bk: "short", bh: ["soar"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["16–17 cm", "38–40 cm", "35–50 g"] },
    s: "An all-dark swift with sickle wings that spends almost its whole life in the air. A common summer visitor, especially in the west and Gobi.",
    d: "The Common Swift breeds across Europe and Asia and winters in Africa. Young birds may stay airborne for ten months, even sleeping on the wing. In Mongolia it breeds in cliffs and buildings, common at Khar Us Nuur, Ulaanbaatar, Böön Tsagaan and Orog Nuur.",
    f: ["All sooty brown with a small pale throat.", "Long sickle-shaped wings.", "Shallow forked tail.", "Never perches on wires."],
    si: "Fork-tailed Swift — white rump. Swallows — white underparts, perch on wires.",
    h: "Cliffs, towns and open country.",
    di: "Khar Us Nuur, Ulaanbaatar, Böön Tsagaan, Orog Nuur, Terelj, Ögii Nuur.",
    mi: "Summer visitor, May–August.",
    fo: "Flying insects.",
    br: "Nests in crevices and roofs; 2–3 eggs.",
    be: "Eats, drinks and sleeps in flight.",
    v: "A screaming ‘sreee’.",
    cu: "Can stay in the air for 10 months without landing.",
    co: "Least Concern.",
    w: "Khar Us Nuur and Ulaanbaatar in June.",
    bt: "June–July",
    fa: ["Sleeps in flight.", "Never perches.", "Migrates to Africa."]
  },
  "common-kingfisher": {
    T: { c: { rufous: 0.45, gray: 0.35, white: 0.1, black: 0.1 }, hb: ["water"], bk: "long", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["16–17 cm", "24–26 cm", "34–46 g"] },
    s: "A small, dazzling blue-and-orange bird that dives headfirst for fish. A scarce summer visitor to rivers and lakes.",
    d: "The Common Kingfisher lives along clear waters across Eurasia and North Africa. It nests in burrows dug into riverbanks. In Mongolia it is found along rivers in Khentii (Khurkh, Onon), Dornod (Buir Nuur), Khar Us Nuur and near Ulaanbaatar.",
    f: ["Brilliant electric-blue back and orange underparts.", "Long, dagger-like bill.", "White throat and neck patch.", "Short tail.", "Flies fast and low over water."],
    si: "Black-capped Kingfisher — larger, red bill, black cap.",
    h: "Clear rivers and lakes with banks.",
    di: "Khentii (Khurkh, Onon), Dornod (Buir Nuur), Khar Us Nuur, Böön Tsagaan, Ulaanbaatar.",
    mi: "Summer visitor, April–October.",
    fo: "Small fish and aquatic insects.",
    br: "Nests at the end of a tunnel in a riverbank; 6–7 eggs.",
    be: "Dives from a perch.",
    v: "A shrill ‘cheee’.",
    cu: "Its shape inspired the nose of Japan’s bullet train.",
    co: "Least Concern.",
    w: "Onon River in summer.",
    bt: "May–September",
    fa: ["Inspired the bullet train.", "Nests in tunnels.", "Dives for fish."]
  },
  "black-capped-kingfisher": {
    T: { c: { red: 0.3, black: 0.3, white: 0.2, rufous: 0.2 }, hb: ["water"], bk: "long", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["28–31 cm", "—", "65–115 g"] },
    s: "A large kingfisher with a black cap, purple-blue back and big red bill. A rare spring migrant in the Gobi; Vulnerable.",
    d: "The Black-capped Kingfisher breeds from China to Korea and winters in South-East Asia. It is Vulnerable because of habitat loss. In Mongolia it has been recorded in May in the Gobi.",
    f: ["Black cap.", "Deep purple-blue back.", "White collar and throat, rufous belly.", "Large red bill.", "White wing patches in flight."],
    si: "Common Kingfisher — much smaller, orange below.",
    h: "Rivers and coasts.",
    di: "Rare; Gobi oases.",
    mi: "Rare migrant, May.",
    fo: "Fish, crabs and insects.",
    br: "Nests in banks (not in Mongolia).",
    be: "Perches conspicuously.",
    v: "A loud cackle.",
    cu: "Its feathers were once used in Chinese jewellery.",
    co: "Vulnerable.",
    w: "Not expected.",
    bt: "—",
    fa: ["Big red bill.", "Vulnerable.", "Rare in Mongolia."]
  },
  "dollarbird": {
    T: { c: { gray: 0.4, black: 0.3, red: 0.2, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch", "soar"], vt: ["croak"], ac: "day", se: ["passage"], sz: ["26–29 cm", "—", "110–185 g"] },
    s: "A stocky, dark roller with a red bill and silvery ‘coin’ spots on the wings. An exceptional vagrant with one old record.",
    d: "The Dollarbird breeds from India and East Asia to Australia. It catches insects in aerial sallies from high perches. One record exists from central Mongolia.",
    f: ["Dark blue-green body.", "Bright red bill and feet.", "Pale blue ‘dollar’ patch on each wing.", "Big head."],
    si: "Unmistakable.",
    h: "Open forest.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Large flying insects.",
    br: "Nests in tree holes (not in Mongolia).",
    be: "Hawks insects from high perches.",
    v: "A harsh ‘kek-kek’.",
    cu: "Named for its coin-like wing spots.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Coin spots on the wings.", "Red bill.", "Catches insects in flight."]
  },
  "european-bee-eater": {
    T: { c: { yellow: 0.3, rufous: 0.3, gray: 0.2, black: 0.1, white: 0.1 }, hb: ["steppe", "water"], bk: "curved", bh: ["perch", "soar"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["25–29 cm", "36–40 cm", "40–78 g"] },
    s: "A rainbow-coloured bird with a yellow throat and chestnut back that catches bees in flight. A local summer visitor to western Mongolia.",
    d: "The European Bee-eater breeds from southern Europe to Central Asia and western Mongolia and winters in Africa. It removes bee stings by rubbing the insect on a branch. In Mongolia it nests in sandy river banks in the west (Bayan-Ölgii, Khovd, Uvs).",
    f: ["Yellow throat bordered with black.", "Chestnut crown and back.", "Turquoise-blue underparts.", "Long, curved bill; pointed central tail feathers."],
    si: "Unmistakable in Mongolia.",
    h: "Open country with sandy banks.",
    di: "Western Mongolia (Bayan-Ölgii, Khovd, Uvs), rarely the Gobi.",
    mi: "Summer visitor, May–September.",
    fo: "Bees, wasps and dragonflies.",
    br: "Colonial in tunnels in sandy banks; 5–7 eggs.",
    be: "Hawks insects from wires and branches.",
    v: "A liquid ‘prruit’.",
    cu: "Beekeepers sometimes dislike it.",
    co: "Least Concern.",
    w: "River banks in Bayan-Ölgii in June.",
    bt: "June–August",
    fa: ["Rubs off bee stings.", "Nests in tunnels.", "Rainbow colours."]
  }
});
