B2T("fr", {
  "indian-cuckoo": {
    name: "Coucou à ailes courtes",
    s: "Coucou gris au dos brun, reconnaissable à son chant de quatre notes. Sur la liste mongole, sans mention GBIF.",
    d: "Le Coucou à ailes courtes niche de l’Inde au sud-est de la Sibérie et pond dans les nids des drongos et pies-grièches. Il pourrait fréquenter l’extrême est de la Mongolie, mais sans mention documentée.",
    f: ["Tête et poitrine grises, dos et ailes bruns.", "Ventre barré.", "Large bande sombre près du bout de la queue.", "Cercle orbital brun."],
    si: "Coucou gris — dos gris, chant différent.",
    h: "Forêts de feuillus.",
    di: "Exceptionnel ; peut-être l’extrême est.",
    mi: "Visiteur d’été.",
    fo: "Chenilles velues.",
    br: "Parasite de couvée.",
    be: "Chante depuis la cime des arbres.",
    v: "Quatre notes sifflées.",
    cu: "En Inde, son chant annonce la mousson.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Chant de quatre notes.", "Pond dans les nids d’autres oiseaux.", "Mange des chenilles velues."]
  },
  "common-cuckoo": {
    name: "Coucou gris",
    s: "Le célèbre « cou-cou » qui pond dans les nids d’autres oiseaux. Visiteur d’été commun dans toute la Mongolie, des forêts aux roselières.",
    d: "Le Coucou gris niche dans toute l’Eurasie et hiverne en Afrique. Les femelles pondent des œufs imitant ceux de leur hôte ; le poussin éjecte les œufs de l’hôte. En Mongolie, on l’entend partout en mai–juin — à Terelj, Oulan-Bator, dans la vallée de Khurkh, à Yolyn Am et Khustai.",
    f: ["Tête, dos et poitrine gris ; ventre blanc barré.", "Longue queue tachetée de blanc.", "Ailes pointues ; vol d’épervier.", "Cercle orbital et pattes jaunes.", "Certaines femelles sont rousses."],
    si: "Épervier d’Europe — ailes arrondies, bec crochu. Coucou de l’Himalaya — chant de huppe, dessous chamois.",
    h: "Forêts, steppe arbustive et roselières.",
    di: "Toutes les régions : Oulan-Bator, Terelj, Khurkh, Yolyn Am, Khustai, lac Khar Us.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Chenilles velues et autres insectes.",
    br: "Parasite des pipits, fauvettes, bergeronnettes et rougequeues.",
    be: "Les mâles chantent depuis les arbres et les poteaux.",
    v: "Le célèbre « cou-cou » ; la femelle émet un gloussement bouillonnant.",
    cu: "Dans le folklore mongol, compter ses chants prédit les années de vie.",
    co: "Préoccupation mineure.",
    w: "Terelj en juin — écoutez à l’aube.",
    bt: "mai–juin",
    fa: ["Pond dans d’autres nids.", "Mange des chenilles velues.", "Migre en Afrique."]
  },
  "himalayan-cuckoo": {
    name: "Coucou de l’Himalaya",
    s: "Coucou très semblable au Coucou gris mais au chant grave de huppe « pou-pou-pou-pou ». Visiteur d’été rare des forêts du nord.",
    d: "Le complexe du Coucou oriental niche dans la taïga sibérienne et l’Himalaya et hiverne en Asie du Sud-Est et en Australie. En Mongolie, quelques oiseaux chantent dans les forêts du Khentii autour de Terelj et d’Oulan-Bator.",
    f: ["Dessus gris.", "Dessous chamois à barres sombres marquées.", "Sous-caudales chamois.", "Un peu plus petit que le Coucou gris."],
    si: "Coucou gris — plus blanc dessous, barres plus fines, chant différent.",
    h: "Forêts de conifères et mixtes.",
    di: "Khentii (Terelj, Oulan-Bator), Selenge.",
    mi: "Visiteur d’été, mai–juillet.",
    fo: "Chenilles.",
    br: "Parasite des pouillots.",
    be: "Chante dans la canopée.",
    v: "Un grave « pou-pou-pou-pou », comme une huppe.",
    cu: "S’identifie surtout au chant.",
    co: "Préoccupation mineure.",
    w: "Écoutez dans les forêts de Terelj en juin.",
    bt: "juin",
    fa: ["Chante comme une huppe.", "Parasite les pouillots.", "Hiverne en Australie."]
  },
  "lesser-cuckoo": {
    name: "Petit Coucou",
    s: "Le plus petit coucou gris, au chant fort et rythmé. Sur la liste mongole, sans mention GBIF.",
    d: "Le Petit Coucou niche de l’Himalaya au Japon et hiverne en Afrique. Il pond dans les nids des bouscarles. Les mentions mongoles sont exceptionnelles.",
    f: ["Comme un petit Coucou gris.", "Dessus gris, ventre blanc barré.", "Œil sombre."],
    si: "Coucou gris — plus grand.",
    h: "Lisières et broussailles.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Chenilles.",
    br: "Parasite de couvée.",
    be: "Chante jour et nuit.",
    v: "Un « tok-to-kyo-kyo-kyo » saccadé.",
    cu: "Au Japon, son chant évoquerait « Tokkyo kyokakyoku » (bureau des brevets).",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Le plus petit coucou gris.", "Chante la nuit.", "Hiverne en Afrique."]
  },
  "grey-nightjar": {
    name: "Engoulevent de jungle",
    s: "Oiseau nocturne gris-brun cryptique, au bec minuscule et à la bouche immense. Visiteur d’été rare des forêts du nord-est.",
    d: "L’Engoulevent de jungle niche en Asie orientale et chasse les papillons de nuit au crépuscule. En Mongolie, il a été noté dans la vallée de Khurkh et les forêts du Khentii.",
    f: ["Gris-brun marbré comme l’écorce.", "Tache blanche sur la gorge.", "Taches blanches aux ailes et à la queue chez le mâle.", "Longues ailes et longue queue."],
    si: "Engoulevent d’Europe — plus pâle, chant différent.",
    h: "Forêts claires et clairières.",
    di: "Rare ; Khentii (Khurkh).",
    mi: "Visiteur d’été, juin.",
    fo: "Papillons de nuit et coléoptères capturés en vol.",
    br: "Pond 2 œufs au sol.",
    be: "Reste immobile sur les branches le jour.",
    v: "Un « tchouk-tchouk-tchouk » rapide.",
    cu: "Appelé « engoulevent de jungle » en Inde.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh au crépuscule.",
    bt: "juin",
    fa: ["Camouflé comme l’écorce.", "Chasse la nuit.", "Bouche immense."]
  },
  "european-nightjar": {
    name: "Engoulevent d’Europe",
    s: "Oiseau nocturne aux longues ailes, camouflé comme l’écorce, au chant ronronnant qui dure des minutes. Visiteur d’été des bois clairs et broussailles, surtout dans l’ouest.",
    d: "L’Engoulevent d’Europe niche de l’Europe à la Mongolie et hiverne en Afrique. Il chasse les papillons de nuit au crépuscule et chante un long ronronnement mécanique. En Mongolie, il niche dans les broussailles sèches et les bois clairs, surtout autour du lac Khar Us et dans la vallée de Khurkh.",
    f: ["Motif d’écorce gris-brun.", "Tête plate, bec minuscule, grands yeux sombres.", "Taches blanches aux ailes et à la queue chez le mâle.", "Longues ailes et longue queue."],
    si: "Engoulevent de jungle — plus gris, oriental.",
    h: "Bois clairs, broussailles et semi-désert.",
    di: "Lac Khar Us, Khurkh, lac Ögii, Böön Tsagaan, Onon.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Papillons de nuit et coléoptères.",
    br: "Pond 2 œufs au sol.",
    be: "Chasse au crépuscule ; claque des ailes en parade.",
    v: "Un long « rrrrrrr ».",
    cu: "Autrefois appelé « tète-chèvre », d’après une légende.",
    co: "Préoccupation mineure.",
    w: "Broussailles du lac Khar Us au crépuscule en juin.",
    bt: "juin–juil.",
    fa: ["Ronronne pendant des minutes.", "Surnommé « tète-chèvre ».", "Hiverne en Afrique."]
  },
  "white-throated-needletail": {
    name: "Martinet épineux",
    s: "Grand martinet puissant à gorge et sous-caudales blanches — l’un des oiseaux les plus rapides en vol horizontal. Visiteur d’été des forêts du nord.",
    d: "Le Martinet épineux niche en Sibérie, dans le nord-est de la Chine et au Japon et hiverne en Australie. Il niche dans les arbres creux. En Mongolie, on le voit au-dessus des forêts et rivières du Khentii (surtout la vallée de Khurkh) et du Dornod.",
    f: ["Martinet massif à queue courte et carrée.", "Gorge blanche et « fer à cheval » blanc sous la queue.", "Selle pâle sur le dos.", "Rectrices terminées par des épines."],
    si: "Martinet de Sibérie — queue fourchue, croupion blanc.",
    h: "Au-dessus des forêts et rivières.",
    di: "Khentii (Khurkh, Terelj), Oulan-Bator, Dornod.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes volants.",
    br: "Niche dans les arbres creux.",
    be: "Vole très vite ; boit en vol.",
    v: "Gazouillis aigus.",
    cu: "Dépasserait les 100 km/h.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["L’un des oiseaux les plus rapides.", "Rectrices épineuses.", "Niche dans les arbres creux."]
  },
  "fork-tailed-swift": {
    name: "Martinet de Sibérie",
    s: "Martinet sombre à croupion blanc et queue profondément fourchue. Très commun en été au-dessus des falaises et des villes, dont Oulan-Bator.",
    d: "Le Martinet de Sibérie niche de la Sibérie au Japon et hiverne en Australie. En Mongolie, il niche dans les fissures des rochers et les bâtiments et il est commun au-dessus d’Oulan-Bator, de Yolyn Am, de Terelj et du lac Ögii.",
    f: ["Noirâtre à large croupion blanc.", "Queue profondément fourchue.", "Gorge pâle.", "Dessous écailleux."],
    si: "Martinet noir — sans croupion blanc. Hirondelle de fenêtre — plus petite, blanche dessous.",
    h: "Falaises, gorges et villes.",
    di: "Oulan-Bator, Yolyn Am, Terelj, lac Ögii, Khurkh, Böön Tsagaan.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes volants.",
    br: "Colonial dans les fissures et bâtiments ; 2 ou 3 œufs.",
    be: "Groupes criards au crépuscule.",
    v: "Cris stridents.",
    cu: "Traverse l’équateur pour hiverner en Australie.",
    co: "Préoccupation mineure.",
    w: "Au-dessus d’Oulan-Bator les soirs de juin.",
    bt: "juin–juil.",
    fa: ["Croupion blanc.", "Queue fourchue.", "Hiverne en Australie."]
  },
  "common-swift": {
    name: "Martinet noir",
    s: "Martinet entièrement sombre aux ailes en faucille, qui passe presque toute sa vie en l’air. Visiteur d’été commun, surtout dans l’ouest et le Gobi.",
    d: "Le Martinet noir niche en Europe et en Asie et hiverne en Afrique. Les jeunes peuvent rester en vol dix mois, dormant même dans les airs. En Mongolie, il niche dans les falaises et bâtiments, commun au lac Khar Us, à Oulan-Bator, à Böön Tsagaan et au lac Orog.",
    f: ["Entièrement brun suie avec une petite gorge pâle.", "Longues ailes en faucille.", "Queue peu fourchue.", "Ne se pose jamais sur les fils."],
    si: "Martinet de Sibérie — croupion blanc. Hirondelles — dessous blanc, se posent sur les fils.",
    h: "Falaises, villes et milieux ouverts.",
    di: "Lac Khar Us, Oulan-Bator, Böön Tsagaan, lac Orog, Terelj, lac Ögii.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes volants.",
    br: "Niche dans les fissures et toits ; 2 ou 3 œufs.",
    be: "Mange, boit et dort en vol.",
    v: "Un « sriii » strident.",
    cu: "Peut rester dix mois en l’air sans se poser.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us et Oulan-Bator en juin.",
    bt: "juin–juil.",
    fa: ["Dort en vol.", "Ne se pose jamais.", "Migre en Afrique."]
  },
  "common-kingfisher": {
    name: "Martin-pêcheur d’Europe",
    s: "Petit oiseau éblouissant bleu et orange qui plonge tête la première sur les poissons. Visiteur d’été peu commun des rivières et lacs.",
    d: "Le Martin-pêcheur d’Europe vit le long des eaux claires d’Eurasie et d’Afrique du Nord. Il niche dans des terriers creusés dans les berges. En Mongolie, on le trouve le long des rivières du Khentii (Khurkh, Onon), du Dornod (lac Buir), au lac Khar Us et près d’Oulan-Bator.",
    f: ["Dos bleu électrique brillant, dessous orange.", "Long bec en poignard.", "Gorge et tache de cou blanches.", "Queue courte.", "Vol rapide et bas au-dessus de l’eau."],
    si: "Martin-chasseur à coiffe noire — plus grand, bec rouge, calotte noire.",
    h: "Rivières et lacs clairs à berges.",
    di: "Khentii (Khurkh, Onon), Dornod (lac Buir), lac Khar Us, Böön Tsagaan, Oulan-Bator.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Petits poissons et insectes aquatiques.",
    br: "Niche au fond d’un tunnel dans une berge ; 6 ou 7 œufs.",
    be: "Plonge depuis un perchoir.",
    v: "Un « tchiii » aigu.",
    cu: "Sa forme a inspiré le nez du train à grande vitesse japonais.",
    co: "Préoccupation mineure.",
    w: "Rivière Onon en été.",
    bt: "mai–sept.",
    fa: ["A inspiré le Shinkansen.", "Niche dans des tunnels.", "Plonge pour pêcher."]
  },
  "black-capped-kingfisher": {
    name: "Martin-chasseur à coiffe noire",
    s: "Grand martin-chasseur à calotte noire, dos bleu pourpre et gros bec rouge. Migrateur printanier rare dans le Gobi ; Vulnérable.",
    d: "Le Martin-chasseur à coiffe noire niche de la Chine à la Corée et hiverne en Asie du Sud-Est. Il est Vulnérable en raison de la perte d’habitat. En Mongolie, il a été noté en mai dans le Gobi.",
    f: ["Calotte noire.", "Dos bleu pourpre profond.", "Collier et gorge blancs, ventre roux.", "Gros bec rouge.", "Taches alaires blanches en vol."],
    si: "Martin-pêcheur d’Europe — bien plus petit, orange dessous.",
    h: "Rivières et côtes.",
    di: "Rare ; oasis du Gobi.",
    mi: "Migrateur rare, mai.",
    fo: "Poissons, crabes et insectes.",
    br: "Niche dans les berges (pas en Mongolie).",
    be: "Se perche bien en vue.",
    v: "Un fort caquètement.",
    cu: "Ses plumes servaient autrefois en joaillerie chinoise.",
    co: "Vulnérable.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Gros bec rouge.", "Vulnérable.", "Rare en Mongolie."]
  },
  "dollarbird": {
    name: "Rolle oriental",
    s: "Rollier trapu et sombre au bec rouge et aux taches argentées en « pièce de monnaie » sur les ailes. Erratique exceptionnel, avec une seule mention ancienne.",
    d: "Le Rolle oriental niche de l’Inde et de l’Asie orientale à l’Australie. Il capture les insectes en vol depuis des perchoirs élevés. Une mention existe pour le centre de la Mongolie.",
    f: ["Corps bleu-vert sombre.", "Bec et pattes rouge vif.", "Tache bleu pâle en « dollar » sur chaque aile.", "Grosse tête."],
    si: "Inconfondable.",
    h: "Forêts claires.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Gros insectes volants.",
    br: "Niche dans des cavités d’arbres (pas en Mongolie).",
    be: "Chasse les insectes depuis des perchoirs élevés.",
    v: "Un « kèk-kèk » rauque.",
    cu: "Son nom anglais vient de ses taches en forme de pièce.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Taches en pièce de monnaie.", "Bec rouge.", "Attrape les insectes en vol."]
  },
  "european-bee-eater": {
    name: "Guêpier d’Europe",
    s: "Oiseau aux couleurs d’arc-en-ciel, à gorge jaune et dos marron, qui capture les abeilles en vol. Visiteur d’été local dans l’ouest de la Mongolie.",
    d: "Le Guêpier d’Europe niche du sud de l’Europe à l’Asie centrale et à l’ouest de la Mongolie, et hiverne en Afrique. Il retire le dard des abeilles en les frottant sur une branche. En Mongolie, il niche dans les berges sableuses de l’ouest (Bayan-Ölgii, Khovd, Uvs).",
    f: ["Gorge jaune bordée de noir.", "Calotte et dos marron.", "Dessous bleu turquoise.", "Long bec arqué ; rectrices centrales pointues."],
    si: "Inconfondable en Mongolie.",
    h: "Milieux ouverts avec berges sableuses.",
    di: "Ouest (Bayan-Ölgii, Khovd, Uvs), rarement le Gobi.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Abeilles, guêpes et libellules.",
    br: "Colonial dans des tunnels creusés dans les berges ; 5 à 7 œufs.",
    be: "Chasse depuis les fils et les branches.",
    v: "Un « prrouit » liquide.",
    cu: "Pas toujours apprécié des apiculteurs.",
    co: "Préoccupation mineure.",
    w: "Berges du Bayan-Ölgii en juin.",
    bt: "juin–août",
    fa: ["Retire le dard des abeilles.", "Niche dans des tunnels.", "Couleurs d’arc-en-ciel."]
  }
});
