B2T("en", {
  "northern-wryneck": {
    T: { c: { brown: 0.45, gray: 0.3, buff: 0.2, black: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch", "walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["16–18 cm", "25–27 cm", "30–50 g"] },
    s: "A cryptic, bark-patterned relative of woodpeckers that twists its neck like a snake when threatened. A summer visitor to open woods across Mongolia.",
    d: "The Eurasian Wryneck breeds across Eurasia and winters in Africa and South Asia. Unlike other woodpeckers it does not drill wood but feeds on ants on the ground. In Mongolia it breeds in groves and forest edges — Ulaanbaatar, Terelj, the Khurkh valley and Khar Us Nuur — and passes through Gobi oases.",
    f: ["Grey-brown with bark-like patterns.", "Dark stripe down the nape and back.", "Short bill.", "Long, barred tail.", "Twists its head when alarmed."],
    si: "Pipits and larks — no bark pattern, live on open ground.",
    h: "Open woodland, groves and gardens.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Yolyn Am, Khövsgöl.",
    mi: "Summer visitor, May–September.",
    fo: "Ants and their larvae.",
    br: "Nests in tree holes; 7–10 eggs.",
    be: "Hisses and twists its neck like a snake.",
    v: "A loud, nasal ‘kyee-kyee-kyee’.",
    cu: "Used in ancient Greek love charms — the origin of the word ‘jinx’.",
    co: "Least Concern.",
    w: "Terelj and Ulaanbaatar parks in May.",
    bt: "May–June",
    fa: ["Twists its neck like a snake.", "Gave us the word ‘jinx’.", "Eats ants."]
  },
  "grey-headed-woodpecker": {
    T: { c: { gray: 0.4, yellow: 0.3, black: 0.1, red: 0.1, white: 0.1 }, hb: ["forest", "settlement"], bk: "long", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["26–33 cm", "38–40 cm", "110–160 g"] },
    s: "A green-and-grey woodpecker with a grey head; the male has a red forehead. A resident of forests and parks, often seen in Ulaanbaatar and Terelj.",
    d: "The Grey-headed Woodpecker lives from Europe to East Asia. It often feeds on the ground on ants. In Mongolia it is resident in the Khentii and Khangai forests and regularly visits parks and gardens in Ulaanbaatar in winter.",
    f: ["Olive-green back.", "Grey head with a thin black moustache.", "Male has a small red patch on the forehead.", "Yellowish rump.", "Undulating flight."],
    si: "Great Spotted Woodpecker — black and white.",
    h: "Mixed and deciduous forest, parks.",
    di: "Ulaanbaatar, Terelj, Khurkh, Orkhon valley, Khövsgöl.",
    mi: "Resident.",
    fo: "Ants, insects and berries.",
    br: "Excavates a nest hole; 5–7 eggs.",
    be: "Often feeds on the ground.",
    v: "A descending series of whistles.",
    cu: "Visits bird feeders in winter.",
    co: "Least Concern.",
    w: "Bogd Khan Uul and Terelj in winter.",
    bt: "all year",
    fa: ["Feeds on ants.", "Green back.", "Visits Ulaanbaatar in winter."]
  },
  "lesser-spotted-woodpecker": {
    T: { c: { black: 0.45, white: 0.45, red: 0.1 }, hb: ["forest", "settlement"], bk: "long", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["14–16 cm", "24–29 cm", "17–26 g"] },
    s: "A sparrow-sized black-and-white woodpecker with a barred back. A common resident of birch and poplar groves, especially around Ulaanbaatar.",
    d: "The Lesser Spotted Woodpecker lives across Eurasia. It feeds in the thin outer branches of trees. In Mongolia it is resident in the Khentii and around Ulaanbaatar and Terelj, and is often found in mixed winter flocks with tits.",
    f: ["Very small woodpecker.", "Black-and-white barred back (no large white shoulder patches).", "Male has a red crown.", "No red under the tail."],
    si: "Great Spotted and White-backed Woodpeckers — larger, red undertail.",
    h: "Birch, poplar and willow woods; parks.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khustai.",
    mi: "Resident.",
    fo: "Insects and larvae.",
    br: "Excavates a nest hole; 4–6 eggs.",
    be: "Joins tit flocks in winter.",
    v: "A thin ‘kee-kee-kee’; soft drumming.",
    cu: "The smallest woodpecker in Mongolia.",
    co: "Least Concern.",
    w: "Birch groves on Bogd Khan Uul.",
    bt: "all year",
    fa: ["Size of a sparrow.", "Barred back.", "Joins tit flocks."]
  },
  "rufous-bellied-woodpecker": {
    T: { c: { rufous: 0.4, black: 0.3, white: 0.2, red: 0.1 }, hb: ["forest"], bk: "long", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["20–25 cm", "—", "50–75 g"] },
    s: "A striking woodpecker with rufous underparts and a black-and-white barred back. A rare visitor to eastern Mongolia.",
    d: "The Rufous-bellied Woodpecker breeds from the Himalaya to north-east China and the Russian Far East. It drinks tree sap. In Mongolia it has been recorded in the far east in autumn.",
    f: ["Rich rufous face and underparts.", "Barred black-and-white back.", "Male has a red crown.", "Red undertail."],
    si: "Unmistakable.",
    h: "Deciduous forest.",
    di: "Rare; eastern Mongolia.",
    mi: "Rare migrant, August–September.",
    fo: "Insects and tree sap.",
    br: "Nests in tree holes (not in Mongolia).",
    be: "Drills sap wells.",
    v: "A rattling ‘kitititi’.",
    cu: "One of the few migratory woodpeckers.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Drinks tree sap.", "Migrates.", "Rufous belly."]
  },
  "eurasian-three-toed-woodpecker": {
    T: { c: { black: 0.45, white: 0.45, yellow: 0.1 }, hb: ["forest"], bk: "long", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["21–24 cm", "32–35 cm", "50–75 g"] },
    s: "A black-and-white taiga woodpecker with only three toes; the male has a yellow crown. Resident in conifer forests of the north.",
    d: "The Eurasian Three-toed Woodpecker lives in the boreal and mountain forests of Eurasia, often in stands with dead trees. It drills rings of sap holes in trunks. In Mongolia it is resident in the Khentii (Bogd Khan Uul, Terelj), Khangai and Khövsgöl.",
    f: ["Black-and-white with a white stripe down the back.", "Male has a yellow crown; female a grey one.", "No red anywhere.", "Only three toes."],
    si: "White-backed Woodpecker — red undertail. Great Spotted Woodpecker — red undertail, white shoulder patches.",
    h: "Spruce, larch and pine forest, especially with dead trees.",
    di: "Ulaanbaatar (Bogd Khan Uul), Terelj, Orkhon, Terkhiin Tsagaan Nuur, Khövsgöl.",
    mi: "Resident.",
    fo: "Bark beetle larvae and tree sap.",
    br: "Excavates a nest hole; 3–5 eggs.",
    be: "Drills rows of sap holes.",
    v: "A soft ‘kip’; drumming.",
    cu: "Helps control bark-beetle outbreaks.",
    co: "Least Concern.",
    w: "Bogd Khan Uul forests.",
    bt: "all year",
    fa: ["Has only three toes.", "Yellow crown.", "Eats bark beetles."]
  },
  "asian-short-toed-lark": {
    T: { c: { buff: 0.5, brown: 0.35, white: 0.15 }, hb: ["steppe", "desert", "water"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–14 cm", "—", "20–26 g"] },
    s: "A small, streaky lark of salty plains and dry steppe that sings in flight. One of the most common larks in Mongolia.",
    d: "The Asian Short-toed Lark breeds from Central Asia to north-east China. It is common in the Gobi, around salt lakes and in dry steppe. In Mongolia it is abundant at Ögii Nuur, Böön Tsagaan, Khar Us Nuur, Orog Nuur and Khustai.",
    f: ["Small, sandy-grey lark.", "Fine streaks on the breast.", "Short, stubby bill.", "Pale eyebrow."],
    si: "Greater Short-toed Lark — plain breast with dark neck patches. Eurasian Skylark — larger, crest, white trailing edge.",
    h: "Salt flats, dry steppe and lake shores.",
    di: "Ögii Nuur, Böön Tsagaan, Khar Us Nuur, Orog Nuur, Khustai, Buir Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 3–5 eggs.",
    be: "Sings in a circling song flight.",
    v: "A varied, twittering song.",
    cu: "Very common around Gobi salt lakes.",
    co: "Least Concern.",
    w: "Böön Tsagaan shores in May.",
    bt: "May–July",
    fa: ["Streaked breast.", "Sings in flight.", "Common in the Gobi."]
  },
  "lesser-short-toed-lark": {
    T: { c: { buff: 0.5, brown: 0.35, white: 0.15 }, hb: ["desert", "steppe"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–14 cm", "—", "18–25 g"] },
    s: "A small streaky lark of dry deserts, very similar to the Asian Short-toed Lark. A scarce summer visitor to the Gobi.",
    d: "The Lesser Short-toed Lark lives in dry open country from the Canary Islands to Central Asia. The Asian Short-toed Lark was once lumped with it. In Mongolia it is recorded in the Gobi (Böön Tsagaan, Orog Nuur, Yolyn Am) and the east.",
    f: ["Small sandy lark with a streaked breast.", "Stubby bill.", "Wingtips barely extend beyond the tertials (unlike Greater Short-toed Lark)."],
    si: "Asian Short-toed Lark — very similar; told by voice and range.",
    h: "Semi-desert.",
    di: "Gobi (Böön Tsagaan, Orog Nuur, Yolyn Am), Dornod.",
    mi: "Summer visitor, April–August.",
    fo: "Seeds and insects.",
    br: "Nests on the ground.",
    be: "Sings in circling flight.",
    v: "A rich, mimicking song.",
    cu: "A good mimic of other birds.",
    co: "Least Concern.",
    w: "Gobi lakes in May.",
    bt: "May–June",
    fa: ["Mimics other birds.", "Desert lark.", "Hard to identify."]
  },
  "black-lark": {
    T: { c: { black: 0.6, brown: 0.2, buff: 0.2 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["winter"], sz: ["19–21 cm", "—", "50–70 g"] },
    s: "A big, stout lark; the male is all black in spring. On the Mongolian list, with no GBIF records.",
    d: "The Black Lark breeds in the steppes of Kazakhstan and southern Russia. Males are black in the breeding season. A record in Mongolia would be exceptional.",
    f: ["Male: all black in spring.", "Heavy pale bill.", "Female: brownish, streaked."],
    si: "Mongolian Lark — chestnut and white.",
    h: "Dry steppe.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Seeds and insects.",
    br: "Nests in Kazakh steppe (not in Mongolia).",
    be: "Stays in steppe even in winter.",
    v: "A varied song.",
    cu: "Eats snow for water in winter.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Male all black.", "Eats snow.", "Steppe bird."]
  },
  "greater-short-toed-lark": {
    T: { c: { buff: 0.55, brown: 0.3, white: 0.1, black: 0.05 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–16 cm", "—", "20–26 g"] },
    s: "A pale, sandy lark with an unstreaked breast and small dark patches on the neck sides. A summer visitor to dry steppe.",
    d: "The Greater Short-toed Lark breeds from Europe to Mongolia and winters in Africa and India. In Mongolia it breeds in dry steppe, especially in Dornod (Buir Nuur), the Khurkh valley, Khustai and Ögii Nuur.",
    f: ["Pale sandy lark.", "Unstreaked breast with small dark neck patches.", "Rufous crown in some birds.", "Stubby pale bill."],
    si: "Asian Short-toed Lark — streaked breast.",
    h: "Dry, short-grass steppe.",
    di: "Dornod (Buir Nuur), Khurkh, Khustai, Ögii Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 3–5 eggs.",
    be: "Sings in undulating flight.",
    v: "A dry, stuttering song.",
    cu: "Winters in Africa.",
    co: "Least Concern.",
    w: "Khustai steppe in June.",
    bt: "May–July",
    fa: ["Plain breast.", "Dark neck patches.", "Winters in Africa."]
  },
  "white-winged-lark": {
    T: { c: { brown: 0.35, white: 0.3, rufous: 0.2, buff: 0.15 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["winter"], sz: ["17–19 cm", "—", "40–60 g"] },
    s: "A large lark with bold white panels in the wings and a rufous crown. On the Mongolian list, with no GBIF records.",
    d: "The White-winged Lark breeds in the steppes of Kazakhstan and south Russia and wanders in winter. Records in Mongolia are exceptional.",
    f: ["Large white panel on the secondaries.", "Rufous crown and wing coverts.", "Heavy bill."],
    si: "Mongolian Lark — black neck patches, larger white wing areas.",
    h: "Dry steppe.",
    di: "Exceptional vagrant.",
    mi: "Winter vagrant.",
    fo: "Seeds and insects.",
    br: "Nests in Kazakh steppe (not in Mongolia).",
    be: "Winter flocks wander widely.",
    v: "A rich song.",
    cu: "An irregular winter wanderer in Europe.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["White wing panels.", "Rufous crown.", "Steppe species."]
  },
  "eurasian-sky-lark": {
    T: { c: { brown: 0.5, buff: 0.35, white: 0.15 }, hb: ["steppe", "water"], bk: "short", bh: ["walk", "soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16–18 cm", "30–36 cm", "33–45 g"] },
    s: "The classic lark that sings for minutes while hovering high in the sky. A common summer visitor to steppe and meadows in the north and east.",
    d: "The Eurasian Skylark breeds across Eurasia. The eastern subspecies (pekinensis/intermedia) is common in Mongolian steppe. It is common in the Khurkh valley, around Ulaanbaatar, at Ögii Nuur and Buir Nuur.",
    f: ["Streaked brown with a small crest.", "White outer tail feathers.", "White trailing edge to the wing.", "Sings while hovering high."],
    si: "Crested Lark — larger crest, no white trailing edge. Mongolian Lark — black neck patches.",
    h: "Grassy steppe and meadows.",
    di: "Khurkh, Ulaanbaatar, Ögii Nuur, Buir Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 3–5 eggs.",
    be: "Rises singing high into the sky.",
    v: "A long, bubbling song from high in the sky.",
    cu: "Celebrated in poetry and music, from Shelley to Vaughan Williams.",
    co: "Least Concern.",
    w: "Khurkh valley in May.",
    bt: "April–July",
    fa: ["Sings for minutes in the air.", "Has a small crest.", "Celebrated in poetry."]
  },
  "crested-lark": {
    T: { c: { buff: 0.5, brown: 0.35, gray: 0.15 }, hb: ["desert", "settlement"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["17–19 cm", "29–38 cm", "37–55 g"] },
    s: "A sandy lark with a long, spiky crest. A resident of the Gobi, especially around settlements and oases.",
    d: "The Crested Lark lives in dry open places from Europe and Africa to China. It often lives near villages and roads. In Mongolia it is resident in the Gobi, especially at Yolyn Am, Orog Nuur, Ikh Nart and Böön Tsagaan.",
    f: ["Long, pointed crest.", "Sandy brown, streaked breast.", "Long, slightly curved bill.", "Rufous underwings; no white trailing edge."],
    si: "Eurasian Skylark — smaller crest, white trailing edge.",
    h: "Semi-desert, villages and roadsides.",
    di: "Gobi (Yolyn Am, Orog Nuur, Ikh Nart, Böön Tsagaan, Taatsiin Tsagaan).",
    mi: "Resident.",
    fo: "Seeds and insects.",
    br: "Nests on the ground; 3–5 eggs.",
    be: "Runs along tracks.",
    v: "A liquid ‘du-ee-dee’.",
    cu: "Often lives alongside people in villages.",
    co: "Least Concern.",
    w: "Yolyn Am car park and villages.",
    bt: "all year",
    fa: ["Spiky crest.", "Lives near villages.", "Resident in the Gobi."]
  }
});
