B2T("fr", {
  "northern-wryneck": {
    name: "Torcol fourmilier",
    s: "Parent cryptique des pics, au plumage d’écorce, qui tord le cou comme un serpent quand il est menacé. Visiteur d’été des bois clairs de toute la Mongolie.",
    d: "Le Torcol fourmilier niche dans toute l’Eurasie et hiverne en Afrique et en Asie du Sud. Contrairement aux autres pics, il ne creuse pas le bois mais mange des fourmis au sol. En Mongolie, il niche dans les bosquets et lisières — Oulan-Bator, Terelj, vallée de Khurkh, lac Khar Us — et passe par les oasis du Gobi.",
    f: ["Gris-brun à motifs d’écorce.", "Bande sombre sur la nuque et le dos.", "Bec court.", "Longue queue barrée.", "Tord la tête quand il est inquiet."],
    si: "Pipits et alouettes — sans motif d’écorce, vivent en terrain ouvert.",
    h: "Bois clairs, bosquets et jardins.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Yolyn Am, Khövsgöl.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Fourmis et leurs larves.",
    br: "Niche dans des cavités d’arbres ; 7 à 10 œufs.",
    be: "Siffle et tord le cou comme un serpent.",
    v: "Un « kyii-kyii-kyii » fort et nasal.",
    cu: "Utilisé dans les philtres d’amour grecs — à l’origine du mot anglais « jinx ».",
    co: "Préoccupation mineure.",
    w: "Terelj et parcs d’Oulan-Bator en mai.",
    bt: "mai–juin",
    fa: ["Tord le cou comme un serpent.", "A donné le mot « jinx ».", "Mange des fourmis."]
  },
  "grey-headed-woodpecker": {
    name: "Pic cendré",
    s: "Pic vert et gris à tête grise ; le mâle a le front rouge. Résident des forêts et parcs, souvent vu à Oulan-Bator et Terelj.",
    d: "Le Pic cendré vit de l’Europe à l’Asie orientale. Il se nourrit souvent de fourmis au sol. En Mongolie, il réside dans les forêts du Khentii et du Khangaï et visite régulièrement les parcs et jardins d’Oulan-Bator en hiver.",
    f: ["Dos vert olive.", "Tête grise à fine moustache noire.", "Petite tache rouge au front chez le mâle.", "Croupion jaunâtre.", "Vol onduleux."],
    si: "Pic épeiche — noir et blanc.",
    h: "Forêts mixtes et feuillues, parcs.",
    di: "Oulan-Bator, Terelj, Khurkh, vallée de l’Orkhon, Khövsgöl.",
    mi: "Résident.",
    fo: "Fourmis, insectes et baies.",
    br: "Creuse une loge ; 5 à 7 œufs.",
    be: "Se nourrit souvent au sol.",
    v: "Une série descendante de sifflements.",
    cu: "Fréquente les mangeoires en hiver.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul et Terelj en hiver.",
    bt: "toute l’année",
    fa: ["Mange des fourmis.", "Dos vert.", "Visite Oulan-Bator en hiver."]
  },
  "lesser-spotted-woodpecker": {
    name: "Pic épeichette",
    s: "Pic noir et blanc de la taille d’un moineau, au dos barré. Résident commun des bosquets de bouleaux et peupliers, surtout autour d’Oulan-Bator.",
    d: "Le Pic épeichette vit dans toute l’Eurasie. Il se nourrit dans les fines branches externes des arbres. En Mongolie, il réside dans le Khentii et autour d’Oulan-Bator et de Terelj, souvent dans les rondes hivernales de mésanges.",
    f: ["Très petit pic.", "Dos barré noir et blanc (sans grandes taches blanches scapulaires).", "Calotte rouge chez le mâle.", "Pas de rouge sous la queue."],
    si: "Pics épeiche et à dos blanc — plus grands, sous-caudales rouges.",
    h: "Bois de bouleaux, peupliers et saules ; parcs.",
    di: "Oulan-Bator, Terelj, Khurkh, Khustai.",
    mi: "Résident.",
    fo: "Insectes et larves.",
    br: "Creuse une loge ; 4 à 6 œufs.",
    be: "Rejoint les groupes de mésanges en hiver.",
    v: "Un fin « kii-kii-kii » ; tambourinage léger.",
    cu: "Le plus petit pic de Mongolie.",
    co: "Préoccupation mineure.",
    w: "Bouleaux du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Taille d’un moineau.", "Dos barré.", "Rejoint les mésanges."]
  },
  "rufous-bellied-woodpecker": {
    name: "Pic à ventre fauve",
    s: "Pic saisissant au dessous roux et au dos barré noir et blanc. Visiteur rare dans l’est de la Mongolie.",
    d: "Le Pic à ventre fauve niche de l’Himalaya au nord-est de la Chine et à l’Extrême-Orient russe. Il boit la sève des arbres. En Mongolie, il a été noté à l’extrême est en automne.",
    f: ["Face et dessous roux profond.", "Dos barré noir et blanc.", "Calotte rouge chez le mâle.", "Sous-caudales rouges."],
    si: "Inconfondable.",
    h: "Forêts feuillues.",
    di: "Rare ; est de la Mongolie.",
    mi: "Migrateur rare, août–septembre.",
    fo: "Insectes et sève.",
    br: "Niche dans des cavités d’arbres (pas en Mongolie).",
    be: "Perce des puits à sève.",
    v: "Un « kititititi » crépitant.",
    cu: "L’un des rares pics migrateurs.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Boit la sève.", "Migrateur.", "Ventre roux."]
  },
  "eurasian-three-toed-woodpecker": {
    name: "Pic tridactyle",
    s: "Pic noir et blanc de la taïga, à trois doigts seulement ; le mâle a la calotte jaune. Résident des forêts de conifères du nord.",
    d: "Le Pic tridactyle vit dans les forêts boréales et montagnardes d’Eurasie, souvent parmi les arbres morts. Il perce des anneaux de trous à sève dans les troncs. En Mongolie, il réside dans le Khentii (Bogd Khan Uul, Terelj), le Khangaï et le Khövsgöl.",
    f: ["Noir et blanc avec une bande blanche sur le dos.", "Calotte jaune chez le mâle, grise chez la femelle.", "Aucun rouge.", "Trois doigts seulement."],
    si: "Pic à dos blanc — sous-caudales rouges. Pic épeiche — sous-caudales rouges, taches scapulaires blanches.",
    h: "Forêts d’épicéas, de mélèzes et de pins, surtout avec arbres morts.",
    di: "Oulan-Bator (Bogd Khan Uul), Terelj, Orkhon, Terkhiin Tsagaan Nuur, Khövsgöl.",
    mi: "Résident.",
    fo: "Larves de scolytes et sève.",
    br: "Creuse une loge ; 3 à 5 œufs.",
    be: "Perce des rangées de trous à sève.",
    v: "Un doux « kip » ; tambourinage.",
    cu: "Aide à limiter les pullulations de scolytes.",
    co: "Préoccupation mineure.",
    w: "Forêts du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Trois doigts seulement.", "Calotte jaune.", "Mange des scolytes."]
  },
  "asian-short-toed-lark": {
    name: "Alouette de Swinhoe",
    s: "Petite alouette striée des plaines salées et steppes sèches, qui chante en vol. L’une des alouettes les plus communes de Mongolie.",
    d: "L’Alouette de Swinhoe niche de l’Asie centrale au nord-est de la Chine. Elle est commune dans le Gobi, autour des lacs salés et dans la steppe sèche. En Mongolie, elle abonde au lac Ögii, à Böön Tsagaan, au lac Khar Us, au lac Orog et à Khustai.",
    f: ["Petite alouette gris sable.", "Fines stries sur la poitrine.", "Bec court et trapu.", "Sourcil pâle."],
    si: "Alouette calandrelle — poitrine unie, taches sombres sur le cou. Alouette des champs — plus grande, huppe, bord de fuite blanc.",
    h: "Salines, steppe sèche et rives de lacs.",
    di: "Lac Ögii, Böön Tsagaan, lac Khar Us, lac Orog, Khustai, lac Buir.",
    mi: "Visiteuse d’été, mars–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 3 à 5 œufs.",
    be: "Chante en vol circulaire.",
    v: "Un chant gazouillé varié.",
    cu: "Très commune autour des lacs salés du Gobi.",
    co: "Préoccupation mineure.",
    w: "Rives de Böön Tsagaan en mai.",
    bt: "mai–juil.",
    fa: ["Poitrine striée.", "Chante en vol.", "Commune dans le Gobi."]
  },
  "lesser-short-toed-lark": {
    name: "Alouette pispolette",
    s: "Petite alouette striée des déserts secs, très semblable à l’Alouette de Swinhoe. Visiteuse d’été peu commune dans le Gobi.",
    d: "L’Alouette pispolette vit dans les milieux secs et ouverts, des Canaries à l’Asie centrale. L’Alouette de Swinhoe lui était autrefois rattachée. En Mongolie, elle est notée dans le Gobi (Böön Tsagaan, lac Orog, Yolyn Am) et l’est.",
    f: ["Petite alouette sable à poitrine striée.", "Bec trapu.", "Pointes des ailes dépassant à peine les tertiaires (contrairement à la calandrelle)."],
    si: "Alouette de Swinhoe — très semblable ; se distingue au chant et à l’aire.",
    h: "Semi-désert.",
    di: "Gobi (Böön Tsagaan, lac Orog, Yolyn Am), Dornod.",
    mi: "Visiteuse d’été, avril–août.",
    fo: "Graines et insectes.",
    br: "Niche au sol.",
    be: "Chante en vol circulaire.",
    v: "Un chant riche et imitateur.",
    cu: "Bonne imitatrice d’autres oiseaux.",
    co: "Préoccupation mineure.",
    w: "Lacs du Gobi en mai.",
    bt: "mai–juin",
    fa: ["Imite d’autres oiseaux.", "Alouette du désert.", "Difficile à identifier."]
  },
  "black-lark": {
    name: "Alouette nègre",
    s: "Grande alouette trapue ; le mâle est entièrement noir au printemps. Sur la liste mongole, sans mention GBIF.",
    d: "L’Alouette nègre niche dans les steppes du Kazakhstan et du sud de la Russie. Les mâles deviennent noirs en période nuptiale. Une mention en Mongolie serait exceptionnelle.",
    f: ["Mâle : entièrement noir au printemps.", "Bec pâle et fort.", "Femelle : brunâtre et striée."],
    si: "Alouette de Mongolie — rousse et blanche.",
    h: "Steppe sèche.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Graines et insectes.",
    br: "Niche dans les steppes kazakhes (pas en Mongolie).",
    be: "Reste dans la steppe même en hiver.",
    v: "Un chant varié.",
    cu: "Mange de la neige pour boire en hiver.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Mâle entièrement noir.", "Mange de la neige.", "Oiseau des steppes."]
  },
  "greater-short-toed-lark": {
    name: "Alouette calandrelle",
    s: "Alouette sable pâle à poitrine unie et petites taches sombres sur les côtés du cou. Visiteuse d’été des steppes sèches.",
    d: "L’Alouette calandrelle niche de l’Europe à la Mongolie et hiverne en Afrique et en Inde. En Mongolie, elle niche dans la steppe sèche, surtout dans le Dornod (lac Buir), la vallée de Khurkh, Khustai et autour du lac Ögii.",
    f: ["Alouette sable pâle.", "Poitrine unie avec de petites taches sombres sur le cou.", "Calotte rousse chez certains oiseaux.", "Bec pâle et trapu."],
    si: "Alouette de Swinhoe — poitrine striée.",
    h: "Steppe sèche à herbe rase.",
    di: "Dornod (lac Buir), Khurkh, Khustai, lac Ögii, lac Khar Us.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 3 à 5 œufs.",
    be: "Chante en vol onduleux.",
    v: "Un chant sec et bégayant.",
    cu: "Hiverne en Afrique.",
    co: "Préoccupation mineure.",
    w: "Steppe de Khustai en juin.",
    bt: "mai–juil.",
    fa: ["Poitrine unie.", "Taches sombres au cou.", "Hiverne en Afrique."]
  },
  "white-winged-lark": {
    name: "Alouette leucoptère",
    s: "Grande alouette aux grands panneaux alaires blancs et à calotte rousse. Sur la liste mongole, sans mention GBIF.",
    d: "L’Alouette leucoptère niche dans les steppes du Kazakhstan et du sud de la Russie et erre en hiver. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Grand panneau blanc sur les secondaires.", "Calotte et couvertures alaires rousses.", "Bec fort."],
    si: "Alouette de Mongolie — taches noires sur le cou, zones blanches plus grandes.",
    h: "Steppe sèche.",
    di: "Erratique exceptionnel.",
    mi: "Erratique hivernal.",
    fo: "Graines et insectes.",
    br: "Niche dans les steppes kazakhes (pas en Mongolie).",
    be: "Les groupes hivernaux errent loin.",
    v: "Un chant riche.",
    cu: "Erratique hivernale irrégulière en Europe.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Panneaux alaires blancs.", "Calotte rousse.", "Espèce des steppes."]
  },
  "eurasian-sky-lark": {
    name: "Alouette des champs",
    s: "L’alouette classique qui chante des minutes en planant haut dans le ciel. Visiteuse d’été commune des steppes et prairies du nord et de l’est.",
    d: "L’Alouette des champs niche dans toute l’Eurasie. La sous-espèce orientale est commune dans la steppe mongole. Elle abonde dans la vallée de Khurkh, autour d’Oulan-Bator, au lac Ögii et au lac Buir.",
    f: ["Brune striée avec une petite huppe.", "Rectrices externes blanches.", "Bord de fuite blanc à l’aile.", "Chante en vol stationnaire très haut."],
    si: "Cochevis huppé — huppe plus grande, sans bord de fuite blanc. Alouette de Mongolie — taches noires sur le cou.",
    h: "Steppe herbeuse et prairies.",
    di: "Khurkh, Oulan-Bator, lac Ögii, lac Buir, Böön Tsagaan, lac Orog.",
    mi: "Visiteuse d’été, mars–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 3 à 5 œufs.",
    be: "S’élève en chantant très haut dans le ciel.",
    v: "Un long chant perlé du haut du ciel.",
    cu: "Célébrée en poésie et en musique, de Shelley à Vaughan Williams.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en mai.",
    bt: "avril–juil.",
    fa: ["Chante des minutes en vol.", "Petite huppe.", "Célébrée en poésie."]
  },
  "crested-lark": {
    name: "Cochevis huppé",
    s: "Alouette sable à longue huppe pointue. Résident du Gobi, surtout près des villages et des oasis.",
    d: "Le Cochevis huppé vit dans les milieux secs et ouverts, de l’Europe et de l’Afrique à la Chine. Il vit souvent près des villages et des routes. En Mongolie, il réside dans le Gobi, en particulier à Yolyn Am, au lac Orog, à Ikh Nart et à Böön Tsagaan.",
    f: ["Longue huppe pointue.", "Brun sable, poitrine striée.", "Bec long légèrement arqué.", "Dessous des ailes roux ; pas de bord de fuite blanc."],
    si: "Alouette des champs — huppe plus petite, bord de fuite blanc.",
    h: "Semi-désert, villages et bords de routes.",
    di: "Gobi (Yolyn Am, lac Orog, Ikh Nart, Böön Tsagaan, Taatsiin Tsagaan).",
    mi: "Résident.",
    fo: "Graines et insectes.",
    br: "Niche au sol ; 3 à 5 œufs.",
    be: "Court le long des pistes.",
    v: "Un « dou-ii-dii » liquide.",
    cu: "Vit souvent aux côtés des humains dans les villages.",
    co: "Préoccupation mineure.",
    w: "Parking de Yolyn Am et villages.",
    bt: "toute l’année",
    fa: ["Huppe pointue.", "Vit près des villages.", "Résident du Gobi."]
  }
});
