B2T("en", {
  "forest-wagtail": {
    T: { c: { brown: 0.4, white: 0.35, black: 0.2, yellow: 0.05 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["16–18 cm", "—", "14–17 g"] },
    s: "A forest wagtail that sways its tail sideways, with two black breast bands. A rare migrant, recorded in Gobi oases.",
    d: "The Forest Wagtail breeds in forests of north-east China, Korea and the Russian Far East and winters in South and South-East Asia. It walks along forest paths swinging its tail from side to side. In Mongolia it has been recorded in May in the Gobi.",
    f: ["Olive-brown upperparts.", "Two black bands across the white breast.", "Bold white wing bars.", "Sways its tail sideways."],
    si: "Other wagtails — bob tails up and down.",
    h: "Forest floors and paths.",
    di: "Rare; Gobi oases.",
    mi: "Rare migrant, May.",
    fo: "Insects.",
    br: "Nests in trees (not in Mongolia).",
    be: "Wags its tail sideways.",
    v: "A sharp ‘pink’.",
    cu: "The only wagtail that nests in trees.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Wags its tail sideways.", "Nests in trees.", "Two breast bands."]
  },
  "pechora-pipit": {
    T: { c: { brown: 0.45, buff: 0.3, white: 0.15, black: 0.1 }, hb: ["water", "forest"], bk: "short", bh: ["walk"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["14–15 cm", "—", "20–25 g"] },
    s: "A skulking, heavily streaked pipit with pale ‘tram-lines’ on the back. A rare migrant, mostly in the east.",
    d: "The Pechora Pipit breeds in the Siberian tundra and taiga and winters in Indonesia and the Philippines. It is famously secretive and silent. In Mongolia it has been recorded at Buir Nuur and a few other sites.",
    f: ["Heavily streaked dark back with two white ‘braces’.", "White belly, streaked breast.", "Long primaries.", "Pinkish legs."],
    si: "Red-throated Pipit — no white braces, rufous throat in spring.",
    h: "Wet thickets and grass.",
    di: "Rare; Buir Nuur, Khustai, Khar Us Nuur.",
    mi: "Rare migrant, June and August–September.",
    fo: "Insects.",
    br: "Nests in the north (not in Mongolia).",
    be: "Very secretive.",
    v: "Rarely calls; a hard ‘tsip’.",
    cu: "Named after the Pechora River in Russia.",
    co: "Least Concern.",
    w: "Check dense cover at Buir Nuur.",
    bt: "August",
    fa: ["Very secretive.", "White braces on the back.", "Named after a Russian river."]
  },
  "tree-pipit": {
    T: { c: { brown: 0.45, buff: 0.35, white: 0.15, black: 0.05 }, hb: ["forest", "steppe"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["15 cm", "25–27 cm", "20–25 g"] },
    s: "A streaky pipit that sings in a ‘parachute’ flight from a treetop. A summer visitor to forest edges, mainly in western Mongolia.",
    d: "The Tree Pipit breeds from Europe to eastern Siberia and winters in Africa and India. In Mongolia it breeds at forest edges in the Altai, Khangai and Khentii and is common on passage in September.",
    f: ["Streaked brown upperparts.", "Buff breast with fine streaks.", "Short, curved hind claw.", "Song flight from a tree."],
    si: "Olive-backed Pipit — greener back, white spot behind the eye.",
    h: "Forest edges and clearings.",
    di: "Khar Us Nuur, Ulaanbaatar, Terelj, Khurkh, Khövsgöl, Orkhon.",
    mi: "Summer visitor and migrant, May–September.",
    fo: "Insects.",
    br: "Nests on the ground; 4–6 eggs.",
    be: "Parachutes down while singing.",
    v: "A loud, trilling song ending in ‘seea-seea-seea’.",
    cu: "Its song flight is a sign of summer in forest edges.",
    co: "Least Concern.",
    w: "Forest edges in the Altai in June.",
    bt: "June–September",
    fa: ["Parachute song flight.", "Winters in Africa.", "Sings from treetops."]
  },
  "olive-backed-pipit": {
    T: { c: { brown: 0.35, white: 0.3, buff: 0.2, black: 0.15 }, hb: ["forest"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["15 cm", "—", "20–25 g"] },
    s: "A greenish pipit with a bold face pattern and heavy black breast spots. A common summer visitor to the forests of the north.",
    d: "The Olive-backed Pipit breeds in the taiga from Russia to Japan and winters in South and South-East Asia. In Mongolia it is common in the Khentii forests (Terelj, Ulaanbaatar, Khurkh) and passes through Gobi oases.",
    f: ["Olive-green, faintly streaked back.", "Bold white eyebrow with a white spot and black spot behind the eye.", "Heavy black spots on a white breast.", "Pumps its tail."],
    si: "Tree Pipit — browner, streaked back, plain face.",
    h: "Coniferous and mixed forests.",
    di: "Ulaanbaatar, Terelj, Khurkh, Yolyn Am, Ögii Nuur, Terkhiin Tsagaan Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Insects and seeds.",
    br: "Nests on the forest floor; 4–5 eggs.",
    be: "Walks on forest floor; sings from trees.",
    v: "A rapid, sweet song.",
    cu: "Also called ‘Hodgson’s Pipit’.",
    co: "Least Concern.",
    w: "Terelj forests in June.",
    bt: "May–September",
    fa: ["Spots behind the eye.", "Pumps its tail.", "Forest pipit."]
  },
  "red-throated-pipit": {
    T: { c: { brown: 0.4, buff: 0.3, rufous: 0.2, black: 0.1 }, hb: ["water", "steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["14–15 cm", "25–27 cm", "18–25 g"] },
    s: "A dark-streaked pipit whose throat and face turn brick-red in spring. A migrant in May and September, especially in the east.",
    d: "The Red-throated Pipit breeds on Arctic tundra and winters in Africa and South-East Asia. In Mongolia it is seen on passage at Buir Nuur, the Khurkh valley and Khar Us Nuur.",
    f: ["Spring: brick-red face and throat.", "Heavily streaked back with pale lines.", "Streaked rump.", "Thin, high call."],
    si: "Pechora Pipit — white braces, no red throat.",
    h: "Wet grassland and lake shores.",
    di: "Buir Nuur, Khurkh, Khar Us Nuur, Böön Tsagaan, Ulaanbaatar.",
    mi: "Passage migrant, May and August–September.",
    fo: "Insects.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Feeds in wet meadows.",
    v: "A long, thin ‘pseeeh’.",
    cu: "Its red throat appears only in the breeding season.",
    co: "Least Concern.",
    w: "Buir Nuur in September.",
    bt: "May, September",
    fa: ["Red throat in spring.", "Arctic breeder.", "Thin call."]
  },
  "american-pipit": {
    T: { c: { brown: 0.4, buff: 0.35, gray: 0.15, white: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["15–17 cm", "—", "20–26 g"] },
    s: "A plain, buff pipit; the Siberian form (japonicus) is heavily streaked. A very rare migrant with one GBIF record.",
    d: "The Buff-bellied (American) Pipit breeds in North America and north-east Siberia. The Siberian subspecies migrates through East Asia. One record exists from the Khurkh valley.",
    f: ["Greyish upperparts.", "Buff underparts with dark streaks (Siberian form).", "Dark legs.", "Bobs its tail."],
    si: "Water Pipit — pinkish breast, fewer streaks.",
    h: "Wet fields and shores.",
    di: "Very rare; Khurkh.",
    mi: "Rare migrant.",
    fo: "Insects and seeds.",
    br: "Nests on tundra (not in Mongolia).",
    be: "Bobs its tail.",
    v: "A thin ‘pip-it’.",
    cu: "Siberian birds belong to the subspecies japonicus.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Very rare.", "Bobs its tail.", "Siberian form."]
  },
  "water-pipit": {
    T: { c: { gray: 0.35, brown: 0.3, buff: 0.2, white: 0.15 }, hb: ["mountain", "water"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["15–17 cm", "—", "18–25 g"] },
    s: "A mountain pipit with a grey head and pinkish breast in spring. Breeds on alpine meadows in the Altai and Khangai.",
    d: "The Water Pipit breeds in the mountains of Europe and Asia and winters at lower wetlands. In Mongolia it breeds on alpine meadows in the Altai, Khangai and Gobi-Altai (including Yolyn Am) and passes through in autumn.",
    f: ["Spring: grey head, pinkish unstreaked breast.", "Dark legs.", "White eyebrow.", "White outer tail feathers."],
    si: "American Pipit — buffier, streaked. Tree Pipit — pale legs, streaked breast.",
    h: "Alpine meadows; streams and lakes in winter.",
    di: "Altai (Khar Us Nuur area), Khangai, Yolyn Am, Ulaanbaatar, Orog Nuur.",
    mi: "Summer visitor and migrant, April–October.",
    fo: "Insects.",
    br: "Nests on the ground in alpine meadows.",
    be: "Song flight over mountain slopes.",
    v: "A trilling song in flight.",
    cu: "Called ‘Water Pipit’ because it winters by water.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "June–July",
    fa: ["Pink breast in spring.", "Mountain breeder.", "Winters by water."]
  },
  "richards-pipit": {
    T: { c: { brown: 0.45, buff: 0.4, white: 0.15 }, hb: ["steppe", "water"], bk: "short", bh: ["walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["17–20 cm", "29–33 cm", "25–36 g"] },
    s: "A large, long-legged pipit with a long hind claw that stands upright in grassland. A common summer visitor to wet meadows and steppe.",
    d: "Richard’s Pipit breeds from Central Asia to eastern Siberia and winters in South and South-East Asia. In Mongolia it is common in grassy meadows in the Khurkh valley, Ögii Nuur, around Ulaanbaatar and Khar Us Nuur.",
    f: ["Large pipit with long legs and a very long hind claw.", "Upright stance.", "Buff flanks, streaked breast band.", "Hovers before landing."],
    si: "Blyth’s Pipit — slightly smaller, shorter tail and claw; call differs.",
    h: "Grassy meadows and wet steppe.",
    di: "Khurkh, Ögii Nuur, Ulaanbaatar, Khar Us Nuur, Böön Tsagaan, Orog Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on the ground; 4–6 eggs.",
    be: "Bounding song flight.",
    v: "A loud, harsh ‘shreep’.",
    cu: "Named after the French naturalist Richard of Lunéville.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "May–August",
    fa: ["Long hind claw.", "Upright stance.", "Named after a French naturalist."]
  },
  "blyths-pipit": {
    T: { c: { brown: 0.45, buff: 0.4, white: 0.15 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["15–17 cm", "—", "22–28 g"] },
    s: "A large steppe pipit, very like Richard’s Pipit but more compact. Mongolia is a core breeding area — common on dry steppe.",
    d: "Blyth’s Pipit breeds mainly in Mongolia and adjacent Siberia and China and winters in India. It is common on dry grassy steppe around Ögii Nuur, Ulaanbaatar, the Khurkh valley, Terelj, Yolyn Am and Khustai.",
    f: ["Streaked brown with buff underparts.", "Shorter tail and hind claw than Richard’s.", "Squared centres to the wing coverts.", "Pale legs."],
    si: "Richard’s Pipit — larger, longer tail and claw, wetter habitats. Tawny Pipit — plainer back.",
    h: "Dry grassy steppe and mountain slopes.",
    di: "Ögii Nuur, Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Khustai.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on the ground; 4–5 eggs.",
    be: "Song flight over steppe.",
    v: "A buzzing ‘spzeeu’.",
    cu: "Mongolia holds much of its world breeding population.",
    co: "Least Concern.",
    w: "Khustai steppe in June.",
    bt: "May–August",
    fa: ["Breeds mainly in Mongolia.", "Very like Richard’s Pipit.", "Winters in India."]
  },
  "tawny-pipit": {
    T: { c: { buff: 0.55, brown: 0.3, white: 0.15 }, hb: ["steppe", "desert"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16–17 cm", "25–28 cm", "20–30 g"] },
    s: "A pale, sandy pipit with an almost plain back, like a wagtail. A summer visitor to dry steppe in western Mongolia.",
    d: "The Tawny Pipit breeds from Europe to Central Asia and western Mongolia and winters in Africa and India. In Mongolia it breeds in dry steppe of the west (Khar Us Nuur, Bayan-Ölgii, Achit Nuur).",
    f: ["Pale sandy, almost unstreaked back.", "Plain buff underparts.", "Dark stripe on the wing coverts.", "Wagtail-like shape."],
    si: "Blyth’s Pipit — streaked back and breast.",
    h: "Dry steppe and semi-desert.",
    di: "Western Mongolia (Khar Us Nuur, Ölgii, Achit Nuur, Tavan Bogd), Khövsgöl.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Runs like a wagtail.",
    v: "A repeated ‘chir-lee’.",
    cu: "One of the plainest pipits.",
    co: "Least Concern.",
    w: "Dry steppe around Khar Us Nuur in June.",
    bt: "June–July",
    fa: ["Almost plain back.", "Like a wagtail.", "Western steppe bird."]
  },
  "yellow-wagtail": {
    T: { c: { yellow: 0.5, gray: 0.2, brown: 0.15, white: 0.1, black: 0.05 }, hb: ["water", "steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["15–16 cm", "23–27 cm", "15–22 g"] },
    s: "A slim, bright yellow wagtail of wet meadows. Western forms breed in western Mongolia; Eastern Yellow Wagtails pass through the east.",
    d: "The Western Yellow Wagtail breeds across Europe and western Asia and winters in Africa; the Eastern Yellow Wagtail breeds in eastern Siberia. In Mongolia yellow wagtails breed in wet meadows of the west, especially Khar Us Nuur, Achit Nuur and Uvs.",
    f: ["Bright yellow underparts.", "Olive-green back.", "Head colour varies by form (grey, blue-grey, black).", "Long tail wagged constantly."],
    si: "Citrine Wagtail — yellow head, grey back. Grey Wagtail — grey back, longer tail, streams.",
    h: "Wet meadows and marsh edges.",
    di: "Western Mongolia (Khar Us Nuur, Achit Nuur, Uvs), Böön Tsagaan, Ulaanbaatar.",
    mi: "Summer visitor, April–September.",
    fo: "Insects, often around livestock.",
    br: "Nests on the ground; 4–6 eggs.",
    be: "Follows grazing animals to catch insects.",
    v: "A loud ‘tsweep’.",
    cu: "Its many subspecies are a puzzle for taxonomists.",
    co: "Least Concern.",
    w: "Khar Us Nuur meadows in June.",
    bt: "June–August",
    fa: ["Follows livestock.", "Many colour forms.", "Winters in Africa."]
  },
  "grey-wagtail": {
    T: { c: { gray: 0.4, yellow: 0.35, black: 0.15, white: 0.1 }, hb: ["water", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["17–20 cm", "25–27 cm", "15–23 g"] },
    s: "A long-tailed wagtail of fast streams, with a grey back and lemon-yellow underparts. Common along mountain rivers, including in Ulaanbaatar.",
    d: "The Grey Wagtail breeds by fast streams from Europe to East Asia. It pumps its very long tail constantly. In Mongolia it is common along mountain streams in the Khentii, around Ulaanbaatar, Terelj and the Khurkh valley and in Gobi oases such as Yolyn Am.",
    f: ["Blue-grey back.", "Lemon-yellow underparts and rump.", "Very long tail.", "Male has a black throat in summer.", "Pinkish legs."],
    si: "Yellow Wagtail — green back, shorter tail. Citrine Wagtail — yellow head.",
    h: "Fast rocky streams and rivers.",
    di: "Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Ögii Nuur, Khar Us Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Aquatic insects.",
    br: "Nests in crevices near water; 4–6 eggs.",
    be: "Pumps its tail constantly.",
    v: "A sharp ‘chee-tit’.",
    cu: "Despite its name, it is more yellow than grey.",
    co: "Least Concern.",
    w: "Terelj streams in summer.",
    bt: "May–September",
    fa: ["Longest-tailed wagtail.", "Loves fast streams.", "More yellow than grey."]
  },
  "citrine-wagtail": {
    T: { c: { yellow: 0.5, gray: 0.3, black: 0.1, white: 0.1 }, hb: ["water"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["15–17 cm", "24–28 cm", "18–25 g"] },
    s: "A wagtail with a bright lemon-yellow head and underparts and a grey back. Very common in wet places across Mongolia.",
    d: "The Citrine Wagtail breeds from eastern Europe to Mongolia and Tibet and winters in South Asia. In Mongolia it is one of the most common wetland birds, breeding in marshes and wet meadows in the Khurkh valley, around Ulaanbaatar, Ögii Nuur and Khar Us Nuur.",
    f: ["Male: all yellow head and underparts.", "Grey back; eastern birds have a black collar.", "Two white wing bars.", "Female: grey crown, yellow face."],
    si: "Yellow Wagtail — green back. Grey Wagtail — grey head, long tail.",
    h: "Marshes, wet meadows and stream sides.",
    di: "All regions: Khurkh, Ulaanbaatar, Ögii Nuur, Khar Us Nuur, Terelj, Yolyn Am.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests on the ground in tussocks; 4–5 eggs.",
    be: "Perches on reeds and bushes.",
    v: "A buzzing ‘tsreep’.",
    cu: "Its range has spread west into Europe.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "May–August",
    fa: ["Yellow head.", "Very common in Mongolia.", "Spreading westward."]
  },
  "white-wagtail": {
    T: { c: { white: 0.45, black: 0.3, gray: 0.25 }, hb: ["water", "settlement", "steppe"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer"], sz: ["16–19 cm", "25–30 cm", "18–27 g"] },
    s: "A lively black, white and grey wagtail that runs along shores and roads. The most common wagtail in Mongolia, found everywhere near water and gers.",
    d: "The White Wagtail breeds across Eurasia. Several subspecies with different head patterns occur in Mongolia (baicalensis, ocularis, personata, leucopsis). It nests near water, in buildings and even in gers. It is abundant in Ulaanbaatar, Terelj, the Khurkh valley and Khar Us Nuur.",
    f: ["White face and belly, black bib or cap (varies by subspecies).", "Grey or black back.", "Long black-and-white tail wagged constantly.", "Undulating flight."],
    si: "Citrine and Grey Wagtails — yellow underparts.",
    h: "River banks, lake shores, villages and ger camps.",
    di: "All regions: Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Yolyn Am, Ögii Nuur.",
    mi: "Summer visitor, March–October.",
    fo: "Insects.",
    br: "Nests in crevices, buildings or gers; 5–6 eggs.",
    be: "Runs after insects, wagging its tail.",
    v: "A lively ‘chizzik’.",
    cu: "Often nests inside the roof of herders’ gers.",
    co: "Least Concern.",
    w: "Anywhere near water in summer.",
    bt: "April–September",
    fa: ["Nests in gers.", "Several forms in Mongolia.", "Always wagging its tail."]
  }
});
