B2T("fr", {
  "forest-wagtail": {
    name: "Bergeronnette de forêt",
    s: "Bergeronnette forestière qui balance la queue latéralement, avec deux bandes pectorales noires. Migratrice rare, notée dans les oasis du Gobi.",
    d: "La Bergeronnette de forêt niche dans les forêts du nord-est de la Chine, de Corée et de l’Extrême-Orient russe et hiverne en Asie du Sud et du Sud-Est. Elle marche sur les sentiers forestiers en balançant la queue de côté. En Mongolie, elle a été notée en mai dans le Gobi.",
    f: ["Dessus brun olive.", "Deux bandes noires sur la poitrine blanche.", "Barres alaires blanches marquées.", "Balance la queue latéralement."],
    si: "Autres bergeronnettes — hochent la queue de haut en bas.",
    h: "Sol et sentiers forestiers.",
    di: "Rare ; oasis du Gobi.",
    mi: "Migratrice rare, mai.",
    fo: "Insectes.",
    br: "Niche dans les arbres (pas en Mongolie).",
    be: "Balance la queue de côté.",
    v: "Un « pink » sec.",
    cu: "La seule bergeronnette qui niche dans les arbres.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Balance la queue de côté.", "Niche dans les arbres.", "Deux bandes pectorales."]
  },
  "pechora-pipit": {
    name: "Pipit de la Petchora",
    s: "Pipit discret très strié, aux « rails » pâles sur le dos. Migrateur rare, surtout dans l’est.",
    d: "Le Pipit de la Petchora niche dans la toundra et la taïga sibériennes et hiverne en Indonésie et aux Philippines. Il est réputé discret et silencieux. En Mongolie, il a été noté au lac Buir et sur quelques autres sites.",
    f: ["Dos sombre très strié avec deux « bretelles » blanches.", "Ventre blanc, poitrine striée.", "Longues primaires.", "Pattes rosâtres."],
    si: "Pipit à gorge rousse — sans bretelles blanches, gorge rousse au printemps.",
    h: "Fourrés humides et herbes.",
    di: "Rare ; lac Buir, Khustai, lac Khar Us.",
    mi: "Migrateur rare, juin et août–septembre.",
    fo: "Insectes.",
    br: "Niche dans le nord (pas en Mongolie).",
    be: "Très discret.",
    v: "Crie rarement ; un « tsip » dur.",
    cu: "Nommé d’après la Petchora, fleuve de Russie.",
    co: "Préoccupation mineure.",
    w: "Vérifiez les couverts denses au lac Buir.",
    bt: "août",
    fa: ["Très discret.", "Bretelles blanches.", "Nommé d’après un fleuve russe."]
  },
  "tree-pipit": {
    name: "Pipit des arbres",
    s: "Pipit strié qui chante en descendant « en parachute » depuis la cime d’un arbre. Visiteur d’été des lisières, surtout dans l’ouest de la Mongolie.",
    d: "Le Pipit des arbres niche de l’Europe à la Sibérie orientale et hiverne en Afrique et en Inde. En Mongolie, il niche en lisière dans l’Altaï, le Khangaï et le Khentii et passe en nombre en septembre.",
    f: ["Dessus brun strié.", "Poitrine chamois finement striée.", "Ongle postérieur court et courbé.", "Vol chanté depuis un arbre."],
    si: "Pipit à dos olive — dos plus vert, tache blanche derrière l’œil.",
    h: "Lisières et clairières.",
    di: "Lac Khar Us, Oulan-Bator, Terelj, Khurkh, Khövsgöl, Orkhon.",
    mi: "Visiteur d’été et migrateur, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol ; 4 à 6 œufs.",
    be: "Descend en parachute en chantant.",
    v: "Un chant fort et trillé finissant en « siia-siia-siia ».",
    cu: "Son vol chanté annonce l’été en lisière.",
    co: "Préoccupation mineure.",
    w: "Lisières de l’Altaï en juin.",
    bt: "juin–sept.",
    fa: ["Vol chanté en parachute.", "Hiverne en Afrique.", "Chante depuis la cime des arbres."]
  },
  "olive-backed-pipit": {
    name: "Pipit à dos olive",
    s: "Pipit verdâtre au dessin facial marqué et aux grosses taches noires sur la poitrine. Visiteur d’été commun des forêts du nord.",
    d: "Le Pipit à dos olive niche dans la taïga, de la Russie au Japon, et hiverne en Asie du Sud et du Sud-Est. En Mongolie, il est commun dans les forêts du Khentii (Terelj, Oulan-Bator, Khurkh) et passe par les oasis du Gobi.",
    f: ["Dos vert olive faiblement strié.", "Sourcil blanc marqué avec une tache blanche et une noire derrière l’œil.", "Grosses taches noires sur la poitrine blanche.", "Hoche la queue."],
    si: "Pipit des arbres — plus brun, dos strié, face unie.",
    h: "Forêts de conifères et mixtes.",
    di: "Oulan-Bator, Terelj, Khurkh, Yolyn Am, lac Ögii, Terkhiin Tsagaan Nuur.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes et graines.",
    br: "Niche au sol en forêt ; 4 ou 5 œufs.",
    be: "Marche au sol ; chante depuis les arbres.",
    v: "Un chant rapide et doux.",
    cu: "Aussi appelé « Pipit de Hodgson ».",
    co: "Préoccupation mineure.",
    w: "Forêts de Terelj en juin.",
    bt: "mai–sept.",
    fa: ["Taches derrière l’œil.", "Hoche la queue.", "Pipit forestier."]
  },
  "red-throated-pipit": {
    name: "Pipit à gorge rousse",
    s: "Pipit fortement strié dont la face et la gorge deviennent rouge brique au printemps. Migrateur en mai et septembre, surtout dans l’est.",
    d: "Le Pipit à gorge rousse niche dans la toundra arctique et hiverne en Afrique et en Asie du Sud-Est. En Mongolie, il passe au lac Buir, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Printemps : face et gorge rouge brique.", "Dos très strié à lignes pâles.", "Croupion strié.", "Cri fin et aigu."],
    si: "Pipit de la Petchora — bretelles blanches, sans gorge rousse.",
    h: "Prairies humides et rives de lacs.",
    di: "Lac Buir, Khurkh, lac Khar Us, Böön Tsagaan, Oulan-Bator.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Insectes.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Se nourrit dans les prés humides.",
    v: "Un long et fin « psiiih ».",
    cu: "Sa gorge rousse n’apparaît qu’en période nuptiale.",
    co: "Préoccupation mineure.",
    w: "Lac Buir en septembre.",
    bt: "mai, sept.",
    fa: ["Gorge rousse au printemps.", "Nicheur arctique.", "Cri fin."]
  },
  "american-pipit": {
    name: "Pipit d’Amérique",
    s: "Pipit chamois uni ; la forme sibérienne (japonicus) est fortement striée. Migrateur très rare avec une seule mention GBIF.",
    d: "Le Pipit d’Amérique niche en Amérique du Nord et dans le nord-est de la Sibérie. La sous-espèce sibérienne migre par l’Asie orientale. Une mention existe dans la vallée de Khurkh.",
    f: ["Dessus grisâtre.", "Dessous chamois strié de sombre (forme sibérienne).", "Pattes sombres.", "Hoche la queue."],
    si: "Pipit spioncelle — poitrine rosée, moins striée.",
    h: "Champs humides et rives.",
    di: "Très rare ; Khurkh.",
    mi: "Migrateur rare.",
    fo: "Insectes et graines.",
    br: "Niche dans la toundra (pas en Mongolie).",
    be: "Hoche la queue.",
    v: "Un fin « pip-it ».",
    cu: "Les oiseaux sibériens appartiennent à la sous-espèce japonicus.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Très rare.", "Hoche la queue.", "Forme sibérienne."]
  },
  "water-pipit": {
    name: "Pipit spioncelle",
    s: "Pipit de montagne à tête grise et poitrine rosée au printemps. Niche dans les prairies alpines de l’Altaï et du Khangaï.",
    d: "Le Pipit spioncelle niche dans les montagnes d’Europe et d’Asie et hiverne dans les zones humides de plaine. En Mongolie, il niche dans les prairies alpines de l’Altaï, du Khangaï et de l’Altaï du Gobi (y compris Yolyn Am) et passe en automne.",
    f: ["Printemps : tête grise, poitrine rosée non striée.", "Pattes sombres.", "Sourcil blanc.", "Rectrices externes blanches."],
    si: "Pipit d’Amérique — plus chamois, strié. Pipit des arbres — pattes pâles, poitrine striée.",
    h: "Prairies alpines ; ruisseaux et lacs en hiver.",
    di: "Altaï (région du lac Khar Us), Khangaï, Yolyn Am, Oulan-Bator, lac Orog.",
    mi: "Visiteur d’été et migrateur, avril–octobre.",
    fo: "Insectes.",
    br: "Niche au sol dans les prairies alpines.",
    be: "Vol chanté au-dessus des pentes.",
    v: "Un chant trillé en vol.",
    cu: "Son nom anglais « Water Pipit » vient de ses hivers près de l’eau.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "juin–juil.",
    fa: ["Poitrine rose au printemps.", "Niche en montagne.", "Hiverne près de l’eau."]
  },
  "richards-pipit": {
    name: "Pipit de Richard",
    s: "Grand pipit haut sur pattes, à très long ongle postérieur, qui se tient droit dans l’herbe. Visiteur d’été commun des prairies humides et de la steppe.",
    d: "Le Pipit de Richard niche de l’Asie centrale à la Sibérie orientale et hiverne en Asie du Sud et du Sud-Est. En Mongolie, il est commun dans les prairies de la vallée de Khurkh, du lac Ögii, d’Oulan-Bator et du lac Khar Us.",
    f: ["Grand pipit aux longues pattes et très long ongle postérieur.", "Port dressé.", "Flancs chamois, bande pectorale striée.", "Fait du surplace avant de se poser."],
    si: "Pipit de Godlewski — un peu plus petit, queue et ongle plus courts ; cri différent.",
    h: "Prairies herbeuses et steppe humide.",
    di: "Khurkh, lac Ögii, Oulan-Bator, lac Khar Us, Böön Tsagaan, lac Orog.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol ; 4 à 6 œufs.",
    be: "Vol chanté bondissant.",
    v: "Un « chriip » fort et rauque.",
    cu: "Nommé d’après le naturaliste français Richard de Lunéville.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Long ongle postérieur.", "Port dressé.", "Nommé d’après un naturaliste français."]
  },
  "blyths-pipit": {
    name: "Pipit de Godlewski",
    s: "Grand pipit des steppes, très semblable au Pipit de Richard mais plus compact. La Mongolie est son principal bastion — commun dans la steppe sèche.",
    d: "Le Pipit de Godlewski niche surtout en Mongolie et dans les régions voisines de Sibérie et de Chine et hiverne en Inde. Il est commun dans la steppe herbeuse sèche autour du lac Ögii, d’Oulan-Bator, de la vallée de Khurkh, de Terelj, de Yolyn Am et de Khustai.",
    f: ["Brun strié, dessous chamois.", "Queue et ongle plus courts que le Pipit de Richard.", "Centres carrés aux couvertures alaires.", "Pattes pâles."],
    si: "Pipit de Richard — plus grand, queue et ongle plus longs, milieux plus humides. Pipit rousseline — dos plus uni.",
    h: "Steppe herbeuse sèche et pentes.",
    di: "Lac Ögii, Oulan-Bator, Khurkh, Terelj, Yolyn Am, Khustai.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol ; 4 ou 5 œufs.",
    be: "Vol chanté au-dessus de la steppe.",
    v: "Un « spziiou » bourdonnant.",
    cu: "La Mongolie abrite une grande part de sa population mondiale.",
    co: "Préoccupation mineure.",
    w: "Steppe de Khustai en juin.",
    bt: "mai–août",
    fa: ["Niche surtout en Mongolie.", "Très semblable au Pipit de Richard.", "Hiverne en Inde."]
  },
  "tawny-pipit": {
    name: "Pipit rousseline",
    s: "Pipit sable pâle au dos presque uni, rappelant une bergeronnette. Visiteur d’été des steppes sèches de l’ouest de la Mongolie.",
    d: "Le Pipit rousseline niche de l’Europe à l’Asie centrale et à l’ouest de la Mongolie et hiverne en Afrique et en Inde. En Mongolie, il niche dans la steppe sèche de l’ouest (lac Khar Us, Bayan-Ölgii, lac Achit).",
    f: ["Dos sable pâle presque sans stries.", "Dessous chamois uni.", "Trait sombre sur les couvertures alaires.", "Silhouette de bergeronnette."],
    si: "Pipit de Godlewski — dos et poitrine striés.",
    h: "Steppe sèche et semi-désert.",
    di: "Ouest (lac Khar Us, Ölgii, lac Achit, Tavan Bogd), Khövsgöl.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Court comme une bergeronnette.",
    v: "Un « tchir-li » répété.",
    cu: "L’un des pipits les plus unis.",
    co: "Préoccupation mineure.",
    w: "Steppe sèche autour du lac Khar Us en juin.",
    bt: "juin–juil.",
    fa: ["Dos presque uni.", "Ressemble à une bergeronnette.", "Oiseau des steppes de l’ouest."]
  },
  "yellow-wagtail": {
    name: "Bergeronnette printanière",
    s: "Bergeronnette élancée jaune vif des prairies humides. Les formes occidentales nichent dans l’ouest de la Mongolie ; les orientales passent dans l’est.",
    d: "La Bergeronnette printanière niche en Europe et en Asie occidentale et hiverne en Afrique ; la Bergeronnette de Béringie niche en Sibérie orientale. En Mongolie, les bergeronnettes jaunes nichent dans les prairies humides de l’ouest, surtout au lac Khar Us, au lac Achit et dans l’Uvs.",
    f: ["Dessous jaune vif.", "Dos vert olive.", "Couleur de la tête variable selon la forme (grise, gris-bleu, noire).", "Longue queue agitée sans cesse."],
    si: "Bergeronnette citrine — tête jaune, dos gris. Bergeronnette des ruisseaux — dos gris, queue plus longue, ruisseaux.",
    h: "Prairies humides et bords de marais.",
    di: "Ouest (lac Khar Us, lac Achit, Uvs), Böön Tsagaan, Oulan-Bator.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes, souvent près du bétail.",
    br: "Niche au sol ; 4 à 6 œufs.",
    be: "Suit les animaux au pâturage pour attraper les insectes.",
    v: "Un « tsouiip » sonore.",
    cu: "Ses nombreuses sous-espèces sont un casse-tête pour les taxonomistes.",
    co: "Préoccupation mineure.",
    w: "Prairies du lac Khar Us en juin.",
    bt: "juin–août",
    fa: ["Suit le bétail.", "Nombreuses formes.", "Hiverne en Afrique."]
  },
  "grey-wagtail": {
    name: "Bergeronnette des ruisseaux",
    s: "Bergeronnette à longue queue des ruisseaux rapides, au dos gris et au dessous jaune citron. Commune le long des rivières de montagne, jusqu’à Oulan-Bator.",
    d: "La Bergeronnette des ruisseaux niche près des cours d’eau rapides, de l’Europe à l’Asie orientale. Elle agite sans cesse sa très longue queue. En Mongolie, elle est commune le long des ruisseaux de montagne du Khentii, à Oulan-Bator, Terelj, dans la vallée de Khurkh et dans les oasis du Gobi comme Yolyn Am.",
    f: ["Dos gris-bleu.", "Dessous et croupion jaune citron.", "Très longue queue.", "Gorge noire chez le mâle en été.", "Pattes rosâtres."],
    si: "Bergeronnette printanière — dos vert, queue plus courte. Bergeronnette citrine — tête jaune.",
    h: "Ruisseaux et rivières rapides et pierreux.",
    di: "Oulan-Bator, Khurkh, Terelj, Yolyn Am, lac Ögii, lac Khar Us.",
    mi: "Visiteuse d’été, avril–octobre.",
    fo: "Insectes aquatiques.",
    br: "Niche dans les fissures près de l’eau ; 4 à 6 œufs.",
    be: "Agite sans cesse la queue.",
    v: "Un « tchi-tit » sec.",
    cu: "Malgré son nom anglais « grise », elle est plus jaune que grise.",
    co: "Préoccupation mineure.",
    w: "Ruisseaux de Terelj en été.",
    bt: "mai–sept.",
    fa: ["La bergeronnette à plus longue queue.", "Aime les ruisseaux rapides.", "Plus jaune que grise."]
  },
  "citrine-wagtail": {
    name: "Bergeronnette citrine",
    s: "Bergeronnette à tête et dessous jaune citron vif et dos gris. Très commune dans les milieux humides de toute la Mongolie.",
    d: "La Bergeronnette citrine niche de l’Europe de l’Est à la Mongolie et au Tibet et hiverne en Asie du Sud. En Mongolie, c’est l’un des oiseaux des zones humides les plus communs, nicheur dans les marais et prairies humides de la vallée de Khurkh, d’Oulan-Bator, du lac Ögii et du lac Khar Us.",
    f: ["Mâle : tête et dessous entièrement jaunes.", "Dos gris ; les oiseaux orientaux ont un collier noir.", "Deux barres alaires blanches.", "Femelle : calotte grise, face jaune."],
    si: "Bergeronnette printanière — dos vert. Bergeronnette des ruisseaux — tête grise, longue queue.",
    h: "Marais, prairies humides et bords de ruisseaux.",
    di: "Toutes les régions : Khurkh, Oulan-Bator, lac Ögii, lac Khar Us, Terelj, Yolyn Am.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche au sol dans les touffes ; 4 ou 5 œufs.",
    be: "Se perche sur les roseaux et buissons.",
    v: "Un « tsriip » bourdonnant.",
    cu: "Son aire s’est étendue vers l’ouest jusqu’en Europe.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Tête jaune.", "Très commune en Mongolie.", "S’étend vers l’ouest."]
  },
  "white-wagtail": {
    name: "Bergeronnette grise",
    s: "Bergeronnette vive noire, blanche et grise qui court sur les rives et les routes. La bergeronnette la plus commune de Mongolie, partout près de l’eau et des yourtes.",
    d: "La Bergeronnette grise niche dans toute l’Eurasie. Plusieurs sous-espèces aux motifs de tête différents vivent en Mongolie (baicalensis, ocularis, personata, leucopsis). Elle niche près de l’eau, dans les bâtiments et même dans les yourtes. Elle abonde à Oulan-Bator, Terelj, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Face et ventre blancs, bavette ou calotte noire (selon la sous-espèce).", "Dos gris ou noir.", "Longue queue noire et blanche sans cesse agitée.", "Vol onduleux."],
    si: "Bergeronnettes citrine et des ruisseaux — dessous jaune.",
    h: "Berges, rives, villages et camps de yourtes.",
    di: "Toutes les régions : Oulan-Bator, Terelj, Khurkh, lac Khar Us, Yolyn Am, lac Ögii.",
    mi: "Visiteuse d’été, mars–octobre.",
    fo: "Insectes.",
    br: "Niche dans les fissures, bâtiments ou yourtes ; 5 ou 6 œufs.",
    be: "Court après les insectes en agitant la queue.",
    v: "Un « tchizzik » vif.",
    cu: "Niche souvent dans le toit des yourtes des éleveurs.",
    co: "Préoccupation mineure.",
    w: "Partout près de l’eau en été.",
    bt: "avril–sept.",
    fa: ["Niche dans les yourtes.", "Plusieurs formes en Mongolie.", "Agite toujours la queue."]
  }
});
