B2T("en", {
  "northern-house-martin": {
    T: { c: { black: 0.45, white: 0.5, gray: 0.05 }, hb: ["mountain", "settlement"], bk: "short", bh: ["soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–15 cm", "26–29 cm", "15–23 g"] },
    s: "A small, glossy blue-black martin with a pure white rump and underparts. Nests in mud cups on cliffs and buildings.",
    d: "The Common House Martin breeds across Europe and northern Asia and winters in Africa and South Asia. It builds closed mud nests under eaves and overhangs. In Mongolia it nests on cliffs and buildings at Khar Us Nuur, Yolyn Am, Ulaanbaatar, the Khurkh valley and Terelj.",
    f: ["Glossy blue-black upperparts.", "Bright white rump.", "Pure white underparts.", "Short forked tail.", "Feathered white feet."],
    si: "Asian House Martin — greyer below, smaller white rump. Barn Swallow — long tail streamers, red throat.",
    h: "Cliffs, gorges and buildings near water.",
    di: "Khar Us Nuur, Yolyn Am, Ulaanbaatar, Khurkh, Ögii Nuur, Terelj.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Colonial; closed mud nests; 4–5 eggs.",
    be: "Feeds higher than swallows.",
    v: "A dry ‘prrit’.",
    cu: "Nests on houses, bringing luck in folk belief.",
    co: "Least Concern.",
    w: "Yolyn Am cliffs in June.",
    bt: "June–August",
    fa: ["White rump.", "Builds closed mud nests.", "Feathered feet."]
  },
  "asian-house-martin": {
    T: { c: { black: 0.45, white: 0.35, gray: 0.2 }, hb: ["mountain"], bk: "short", bh: ["soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12–13 cm", "—", "15–20 g"] },
    s: "A small martin like the Common House Martin but with greyish underparts and a smaller white rump. A scarce breeder on mountain cliffs.",
    d: "The Asian House Martin breeds in mountains from the Himalaya to Japan and winters in South-East Asia. In Mongolia it breeds locally on cliffs in the Altai and Gobi and near Ulaanbaatar.",
    f: ["Blue-black upperparts.", "Smaller white rump.", "Dusky grey underparts.", "Shallow forked tail."],
    si: "Northern House Martin — pure white below, larger rump patch.",
    h: "Mountain cliffs and gorges.",
    di: "Khar Us Nuur, Böön Tsagaan, Ulaanbaatar, Ölgii, Orog Nuur, Yolyn Am.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Colonial mud nests on cliffs.",
    be: "Feeds high over cliffs.",
    v: "A thin twitter.",
    cu: "Named after the French naturalist Bonaparte in French.",
    co: "Least Concern.",
    w: "Mountain gorges in the west.",
    bt: "June–July",
    fa: ["Grey below.", "Mountain species.", "Mud nests."]
  },
  "red-rumped-swallow": {
    T: { c: { black: 0.4, rufous: 0.3, white: 0.2, buff: 0.1 }, hb: ["mountain", "settlement"], bk: "short", bh: ["soar", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16–17 cm", "32–34 cm", "19–29 g"] },
    s: "A swallow with a rusty rump and nape, streaked underparts and long tail streamers. A scarce summer visitor.",
    d: "The Red-rumped Swallow breeds from southern Europe to East Asia. It builds a mud nest shaped like a bottle with an entrance tunnel. In Mongolia it is scarce, mostly in the north (Terelj, Ulaanbaatar, Terkhiin Tsagaan Nuur).",
    f: ["Rusty-orange rump and nape.", "Finely streaked buff underparts.", "Long tail streamers.", "Black undertail."],
    si: "Barn Swallow — dark rump, red throat, blue breast band.",
    h: "Rocky valleys, bridges and buildings.",
    di: "Terelj, Ulaanbaatar, Terkhiin Tsagaan Nuur, Khustai.",
    mi: "Summer visitor, May–August.",
    fo: "Flying insects.",
    br: "Bottle-shaped mud nest with a tunnel.",
    be: "Glides more than the Barn Swallow.",
    v: "A nasal ‘djuit’.",
    cu: "Its bottle nest is a masterpiece of mud engineering.",
    co: "Least Concern.",
    w: "Terelj rocks in June.",
    bt: "June",
    fa: ["Bottle-shaped nest.", "Rusty rump.", "Glides a lot."]
  },
  "barn-swallow": {
    T: { c: { black: 0.4, white: 0.3, red: 0.15, buff: 0.15 }, hb: ["settlement", "steppe", "water"], bk: "short", bh: ["soar", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["17–19 cm", "32–35 cm", "16–22 g"] },
    s: "The familiar swallow with a red throat and long tail streamers, nesting in barns and buildings. Very common across Mongolia.",
    d: "The Barn Swallow is the most widespread swallow in the world. It nests in open mud cups inside buildings. In Mongolia it is common near settlements, winter camps, lakes and rivers — Ögii Nuur, Khar Us Nuur, Ulaanbaatar, the Khurkh valley and Khustai.",
    f: ["Glossy blue upperparts.", "Dark red throat and forehead.", "Blue-black breast band.", "Long outer tail streamers.", "Pale buff or white underparts."],
    si: "Red-rumped Swallow — rusty rump. House martins — white rump, short tail.",
    h: "Villages, farms and open country near water.",
    di: "All regions: Ögii Nuur, Khar Us Nuur, Ulaanbaatar, Khurkh, Khustai, Yolyn Am.",
    mi: "Summer visitor, April–September.",
    fo: "Flying insects.",
    br: "Open mud cup inside buildings; 4–5 eggs; two broods.",
    be: "Skims low over water and fields.",
    v: "A cheerful twittering song.",
    cu: "A symbol of spring and good luck in many cultures.",
    co: "Least Concern.",
    w: "Any village in summer.",
    bt: "May–August",
    fa: ["Most widespread swallow.", "Long tail streamers.", "Nests in buildings."]
  },
  "eurasian-crag-martin": {
    T: { c: { brown: 0.6, buff: 0.3, white: 0.1 }, hb: ["mountain", "desert"], bk: "short", bh: ["soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–15 cm", "32–34 cm", "20–25 g"] },
    s: "A stocky, brown martin of cliffs with white spots in its square tail. Common in rocky gorges of the Gobi and west.",
    d: "The Eurasian Crag Martin breeds in mountains from southern Europe to China. It nests in half-cup mud nests on cliffs. In Mongolia it is common at Yolyn Am, Khar Us Nuur and other rocky gorges.",
    f: ["Plain grey-brown.", "White spots near the tip of the square tail (visible when spread).", "Dark underwing coverts.", "Buff underparts."],
    si: "Sand Martin — brown breast band, forked tail.",
    h: "Cliffs and gorges.",
    di: "Yolyn Am, Khar Us Nuur, Terkhiin Tsagaan, Orog Nuur, Ölgii, Orkhon.",
    mi: "Summer visitor, April–September.",
    fo: "Flying insects.",
    br: "Half-cup mud nest on cliffs; 3–4 eggs.",
    be: "Glides along cliff faces.",
    v: "A soft ‘trrt’.",
    cu: "One of the hardiest martins.",
    co: "Least Concern.",
    w: "Yolyn Am gorge.",
    bt: "May–August",
    fa: ["White tail spots.", "Lives on cliffs.", "Very hardy."]
  },
  "sand-martin": {
    T: { c: { brown: 0.5, white: 0.5 }, hb: ["water"], bk: "short", bh: ["soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12–13 cm", "26–29 cm", "11–18 g"] },
    s: "A small brown martin with a white belly and brown breast band, nesting in colonies in sandy banks.",
    d: "The Sand Martin breeds across the Northern Hemisphere, digging nest tunnels in river banks. In Mongolia it is common near rivers and lakes — Khar Us Nuur, Buir Nuur, Ögii Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["Brown upperparts.", "White underparts with a clear brown breast band.", "Short forked tail.", "Small size."],
    si: "Pale Martin — paler, weaker breast band. Crag Martin — larger, no breast band.",
    h: "River banks and lake shores.",
    di: "Khar Us Nuur, Buir Nuur, Ögii Nuur, Böön Tsagaan, Orog Nuur, Ulaanbaatar.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Colonial in burrows in sandy banks; 4–5 eggs.",
    be: "Hunts low over water.",
    v: "A dry, rasping twitter.",
    cu: "Its colonies look like honeycomb in river banks.",
    co: "Least Concern.",
    w: "Sandy banks of Buir Nuur in June.",
    bt: "June–July",
    fa: ["Digs nest tunnels.", "Brown breast band.", "Colonial."]
  },
  "pale-martin": {
    T: { c: { gray: 0.45, brown: 0.3, white: 0.25 }, hb: ["water", "desert"], bk: "short", bh: ["soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["11–12 cm", "—", "11–15 g"] },
    s: "A small, pale grey-brown martin with a faint breast band. Nests in sandy banks, mainly in the west and Gobi.",
    d: "The Pale Martin breeds in Central Asia, Mongolia and China. It was split from the Sand Martin. In Mongolia it is common at Khar Us Nuur, Ögii Nuur, Böön Tsagaan and Gobi lakes.",
    f: ["Paler grey-brown than Sand Martin.", "Diffuse, pale breast band.", "Pale throat.", "Shallow tail fork."],
    si: "Sand Martin — darker, sharp breast band.",
    h: "River banks and lake shores in dry areas.",
    di: "Khar Us Nuur, Ögii Nuur, Böön Tsagaan, Yolyn Am, Orog Nuur, Ölgii.",
    mi: "Summer visitor, April–September.",
    fo: "Flying insects.",
    br: "Colonial in sandy banks.",
    be: "Feeds over water.",
    v: "A soft twitter.",
    cu: "Recognised as a separate species only recently.",
    co: "Least Concern.",
    w: "Khar Us Nuur banks in June.",
    bt: "June–July",
    fa: ["Pale colour.", "Split from Sand Martin.", "Dry-country martin."]
  },
  "bull-headed-shrike": {
    T: { c: { rufous: 0.35, gray: 0.25, buff: 0.25, black: 0.15 }, hb: ["forest", "settlement"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["19–20 cm", "—", "30–45 g"] },
    s: "A big-headed East Asian shrike with a rufous crown and black mask. On the Mongolian list, with no GBIF records.",
    d: "The Bull-headed Shrike lives in Japan, Korea and north-east China. It impales prey on thorns as a ‘larder’. Mongolian records are exceptional.",
    f: ["Large head with a rufous crown.", "Black mask.", "Grey back.", "White wing patch."],
    si: "Brown Shrike — no white wing patch.",
    h: "Farmland and woodland edges.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects, lizards and small birds.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Impales prey on thorns.",
    v: "A harsh ‘kyi-kyi-kyi’.",
    cu: "Japanese folk belief says the height of its larder predicts snow depth.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Keeps a larder on thorns.", "Big head.", "East Asian species."]
  },
  "brown-shrike": {
    T: { c: { brown: 0.45, rufous: 0.2, buff: 0.2, black: 0.1, white: 0.05 }, hb: ["forest", "steppe", "settlement"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["17–20 cm", "—", "25–35 g"] },
    s: "A brown shrike with a black mask and white eyebrow, perching on bushes to catch insects. A common summer visitor in the north.",
    d: "The Brown Shrike breeds from Siberia to Japan and winters in South and South-East Asia. In Mongolia it is common in shrubby forest edges and river valleys of the Khentii (Khurkh, Terelj), around Ulaanbaatar and in Gobi oases on passage.",
    f: ["Brown back and tail.", "Black mask with a white eyebrow.", "Buff underparts.", "Hooked bill."],
    si: "Isabelline Shrike — paler, rufous tail. Red-backed Shrike — not in Mongolia.",
    h: "Forest edges, shrubs and river valleys.",
    di: "Khurkh, Ulaanbaatar, Terelj, Yolyn Am, Khustai, Ögii Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Large insects, small lizards and birds.",
    br: "Nests in bushes; 4–6 eggs.",
    be: "Hunts from exposed perches.",
    v: "A harsh ‘chak-chak’.",
    cu: "Shrikes are called ‘butcher birds’.",
    co: "Least Concern.",
    w: "Khurkh valley shrubs in June.",
    bt: "May–August",
    fa: ["Called a ‘butcher bird’.", "Black mask.", "Common in the north."]
  },
  "isabelline-shrike": {
    T: { c: { buff: 0.45, rufous: 0.25, gray: 0.15, black: 0.1, white: 0.05 }, hb: ["desert", "steppe"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["16–18 cm", "—", "25–35 g"] },
    s: "A pale sandy shrike with a rufous tail and black mask. A common summer visitor to the Gobi and western Mongolia.",
    d: "The Isabelline Shrike breeds in Central Asian deserts and steppe and winters in Africa and Arabia. In Mongolia it is common in desert shrubs and oases — Yolyn Am, Khar Us Nuur, Orog Nuur and Böön Tsagaan.",
    f: ["Pale sandy-grey back.", "Rusty-red tail.", "Black mask (male).", "Small white wing patch."],
    si: "Brown Shrike — darker brown, no rufous tail contrast.",
    h: "Desert shrubs, saxaul and oases.",
    di: "Yolyn Am, Khar Us Nuur, Orog Nuur, Böön Tsagaan, Khurkh, Ulaanbaatar.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and lizards.",
    br: "Nests in shrubs; 4–6 eggs.",
    be: "Impales prey on thorns.",
    v: "A harsh ‘chek’.",
    cu: "Named after the pale ‘Isabelline’ colour.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "May–August",
    fa: ["Rufous tail.", "Desert shrike.", "Named after a colour."]
  },
  "long-tailed-shrike": {
    T: { c: { rufous: 0.35, gray: 0.3, black: 0.25, white: 0.1 }, hb: ["steppe", "settlement"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["23–25 cm", "—", "35–50 g"] },
    s: "A large shrike with a long tail, grey crown and rufous flanks. A very rare vagrant with one record.",
    d: "The Long-tailed Shrike lives from Central Asia to South-East Asia. One record exists at Khar Us Nuur.",
    f: ["Long black tail.", "Grey crown and back, black mask.", "Rufous flanks and rump."],
    si: "Brown Shrike — smaller, shorter tail.",
    h: "Open country with bushes.",
    di: "Very rare; Khar Us Nuur.",
    mi: "Vagrant.",
    fo: "Insects, lizards.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Perches on wires.",
    v: "Harsh calls; mimics.",
    cu: "Its species name ‘schach’ comes from Persian.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Long tail.", "Mimics other birds.", "Very rare in Mongolia."]
  },
  "lesser-grey-shrike": {
    T: { c: { gray: 0.4, white: 0.3, black: 0.25, rufous: 0.05 }, hb: ["steppe"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["summer"], sz: ["19–21 cm", "—", "40–55 g"] },
    s: "A grey-and-black shrike with a broad black mask across the forehead and a pink-flushed breast. Rare in far western Mongolia.",
    d: "The Lesser Grey Shrike breeds from Europe to Central Asia and winters in southern Africa. In Mongolia there are records from the far west.",
    f: ["Black mask extending over the forehead.", "Grey back, black wings with a white patch.", "Pinkish breast.", "Shorter tail than Great Grey Shrike."],
    si: "Great Grey Shrike — mask does not cover the forehead, longer tail.",
    h: "Steppe with trees.",
    di: "Rare; far west.",
    mi: "Summer visitor.",
    fo: "Large insects.",
    br: "Nests in trees (rare in Mongolia).",
    be: "Hovers before pouncing.",
    v: "A harsh ‘chek’.",
    cu: "Winters as far south as South Africa.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Black forehead.", "Pink breast.", "Long-distance migrant."]
  },
  "chinese-grey-shrike": {
    T: { c: { gray: 0.45, white: 0.3, black: 0.25 }, hb: ["steppe"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["28–31 cm", "—", "80–100 g"] },
    s: "The largest shrike, grey with a long tail and big white wing patches. A resident of eastern steppes.",
    d: "The Chinese Grey Shrike breeds in north-east China, eastern Mongolia and Korea. In Mongolia it is found in Dornod (Buir Nuur, Ganga Nuur) and the eastern Gobi.",
    f: ["Very large, long-tailed grey shrike.", "Large white patch on the black wings.", "Black mask.", "Long graduated tail."],
    si: "Great Grey Shrike — smaller, smaller white wing patch.",
    h: "Open steppe with shrubs.",
    di: "Dornod (Buir Nuur, Ganga Nuur, Mongol Daguur), eastern Gobi, Khustai.",
    mi: "Resident; some move south in winter.",
    fo: "Rodents, small birds and large insects.",
    br: "Nests in shrubs.",
    be: "Hunts from high perches.",
    v: "A harsh chatter.",
    cu: "The world’s largest shrike.",
    co: "Least Concern.",
    w: "Buir Nuur steppe.",
    bt: "all year",
    fa: ["World’s largest shrike.", "Large white wing patch.", "Eastern steppe bird."]
  },
  "great-grey-shrike": {
    T: { c: { gray: 0.45, white: 0.3, black: 0.25 }, hb: ["desert", "steppe"], bk: "hooked", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["22–26 cm", "30–34 cm", "50–80 g"] },
    s: "A grey-and-white predator songbird with a black mask that impales prey on thorns. Resident in the Gobi, especially in saxaul.",
    d: "The Great Grey Shrike lives across the Northern Hemisphere. In Mongolia the pale desert form lives in the saxaul deserts of the Gobi (Orog Nuur, Yolyn Am, Böön Tsagaan) and the west.",
    f: ["Pale grey back, white underparts.", "Black mask.", "Black wings with a white patch.", "Long black-and-white tail."],
    si: "Chinese Grey Shrike — larger, bigger white wing patch.",
    h: "Saxaul desert and scrub.",
    di: "Gobi (Orog Nuur, Yolyn Am, Böön Tsagaan, Taatsiin Tsagaan), Khar Us Nuur.",
    mi: "Resident.",
    fo: "Rodents, lizards, small birds and insects.",
    br: "Nests in saxaul or shrubs.",
    be: "Keeps a larder of prey on thorns.",
    v: "A harsh ‘shek-shek’.",
    cu: "Its scientific name excubitor means ‘sentinel’.",
    co: "Least Concern.",
    w: "Saxaul near Orog Nuur.",
    bt: "all year",
    fa: ["Name means ‘sentinel’.", "Keeps a thorn larder.", "Desert form."]
  }
});
