B2T("fr", {
  "northern-house-martin": {
    name: "Hirondelle de fenêtre",
    s: "Petite hirondelle bleu-noir brillant au croupion et dessous d’un blanc pur. Niche dans des coupes de boue sur les falaises et bâtiments.",
    d: "L’Hirondelle de fenêtre niche en Europe et en Asie du Nord et hiverne en Afrique et en Asie du Sud. Elle construit des nids de boue fermés sous les avant-toits et surplombs. En Mongolie, elle niche sur les falaises et bâtiments au lac Khar Us, à Yolyn Am, Oulan-Bator, dans la vallée de Khurkh et à Terelj.",
    f: ["Dessus bleu-noir brillant.", "Croupion blanc éclatant.", "Dessous blanc pur.", "Courte queue fourchue.", "Pattes emplumées de blanc."],
    si: "Hirondelle de Bonaparte — plus grise dessous, croupion blanc plus petit. Hirondelle rustique — longs filets, gorge rouge.",
    h: "Falaises, gorges et bâtiments près de l’eau.",
    di: "Lac Khar Us, Yolyn Am, Oulan-Bator, Khurkh, lac Ögii, Terelj.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Coloniale ; nids de boue fermés ; 4 ou 5 œufs.",
    be: "Chasse plus haut que les hirondelles rustiques.",
    v: "Un « prrit » sec.",
    cu: "Nichant sur les maisons, elle porte bonheur selon la tradition.",
    co: "Préoccupation mineure.",
    w: "Falaises de Yolyn Am en juin.",
    bt: "juin–août",
    fa: ["Croupion blanc.", "Nids de boue fermés.", "Pattes emplumées."]
  },
  "asian-house-martin": {
    name: "Hirondelle de Bonaparte",
    s: "Petite hirondelle semblable à l’Hirondelle de fenêtre mais au dessous grisâtre et au croupion blanc plus petit. Nicheuse peu commune des falaises de montagne.",
    d: "L’Hirondelle de Bonaparte niche dans les montagnes, de l’Himalaya au Japon, et hiverne en Asie du Sud-Est. En Mongolie, elle niche localement sur les falaises de l’Altaï, du Gobi et près d’Oulan-Bator.",
    f: ["Dessus bleu-noir.", "Petit croupion blanc.", "Dessous gris terne.", "Queue peu fourchue."],
    si: "Hirondelle de fenêtre — blanc pur dessous, croupion plus grand.",
    h: "Falaises et gorges de montagne.",
    di: "Lac Khar Us, Böön Tsagaan, Oulan-Bator, Ölgii, lac Orog, Yolyn Am.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Nids de boue coloniaux sur les falaises.",
    be: "Chasse haut au-dessus des falaises.",
    v: "Un fin gazouillis.",
    cu: "Son nom français honore Charles-Lucien Bonaparte.",
    co: "Préoccupation mineure.",
    w: "Gorges de montagne dans l’ouest.",
    bt: "juin–juil.",
    fa: ["Grise dessous.", "Espèce montagnarde.", "Nids de boue."]
  },
  "red-rumped-swallow": {
    name: "Hirondelle striolée",
    s: "Hirondelle au croupion et à la nuque rouille, au dessous strié et aux longs filets. Visiteuse d’été peu commune.",
    d: "L’Hirondelle striolée niche du sud de l’Europe à l’Asie orientale. Elle construit un nid de boue en forme de bouteille avec un tunnel d’entrée. En Mongolie, elle est peu commune, surtout dans le nord (Terelj, Oulan-Bator, Terkhiin Tsagaan Nuur).",
    f: ["Croupion et nuque orange rouille.", "Dessous chamois finement strié.", "Longs filets caudaux.", "Sous-caudales noires."],
    si: "Hirondelle rustique — croupion sombre, gorge rouge, bande pectorale bleue.",
    h: "Vallées rocheuses, ponts et bâtiments.",
    di: "Terelj, Oulan-Bator, Terkhiin Tsagaan Nuur, Khustai.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes volants.",
    br: "Nid de boue en bouteille avec tunnel.",
    be: "Plane davantage que l’Hirondelle rustique.",
    v: "Un « djouit » nasal.",
    cu: "Son nid en bouteille est un chef-d’œuvre d’architecture de boue.",
    co: "Préoccupation mineure.",
    w: "Rochers de Terelj en juin.",
    bt: "juin",
    fa: ["Nid en forme de bouteille.", "Croupion rouille.", "Plane beaucoup."]
  },
  "barn-swallow": {
    name: "Hirondelle rustique",
    s: "L’hirondelle familière à gorge rouge et longs filets, nichant dans les granges et bâtiments. Très commune dans toute la Mongolie.",
    d: "L’Hirondelle rustique est l’hirondelle la plus répandue au monde. Elle niche dans des coupes de boue ouvertes à l’intérieur des bâtiments. En Mongolie, elle est commune près des villages, campements d’hiver, lacs et rivières — lac Ögii, lac Khar Us, Oulan-Bator, vallée de Khurkh et Khustai.",
    f: ["Dessus bleu brillant.", "Gorge et front rouge sombre.", "Bande pectorale bleu-noir.", "Longs filets caudaux externes.", "Dessous chamois pâle ou blanc."],
    si: "Hirondelle striolée — croupion rouille. Hirondelles de fenêtre — croupion blanc, queue courte.",
    h: "Villages, fermes et milieux ouverts près de l’eau.",
    di: "Toutes les régions : lac Ögii, lac Khar Us, Oulan-Bator, Khurkh, Khustai, Yolyn Am.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes volants.",
    br: "Coupe de boue ouverte dans les bâtiments ; 4 ou 5 œufs ; deux couvées.",
    be: "Rase l’eau et les champs.",
    v: "Un gazouillis joyeux.",
    cu: "Symbole du printemps et de la chance dans de nombreuses cultures.",
    co: "Préoccupation mineure.",
    w: "N’importe quel village en été.",
    bt: "mai–août",
    fa: ["L’hirondelle la plus répandue.", "Longs filets.", "Niche dans les bâtiments."]
  },
  "eurasian-crag-martin": {
    name: "Hirondelle de rochers",
    s: "Hirondelle trapue et brune des falaises, à taches blanches dans la queue carrée. Commune dans les gorges rocheuses du Gobi et de l’ouest.",
    d: "L’Hirondelle de rochers niche dans les montagnes, du sud de l’Europe à la Chine. Elle construit des demi-coupes de boue sur les falaises. En Mongolie, elle est commune à Yolyn Am, au lac Khar Us et dans d’autres gorges rocheuses.",
    f: ["Gris-brun uni.", "Taches blanches près du bout de la queue carrée (visibles queue étalée).", "Couvertures sous-alaires sombres.", "Dessous chamois."],
    si: "Hirondelle de rivage — bande pectorale brune, queue fourchue.",
    h: "Falaises et gorges.",
    di: "Yolyn Am, lac Khar Us, Terkhiin Tsagaan, lac Orog, Ölgii, Orkhon.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes volants.",
    br: "Demi-coupe de boue sur une falaise ; 3 ou 4 œufs.",
    be: "Glisse le long des parois.",
    v: "Un doux « trrt ».",
    cu: "L’une des hirondelles les plus rustiques.",
    co: "Préoccupation mineure.",
    w: "Gorge de Yolyn Am.",
    bt: "mai–août",
    fa: ["Taches blanches à la queue.", "Vit sur les falaises.", "Très rustique."]
  },
  "sand-martin": {
    name: "Hirondelle de rivage",
    s: "Petite hirondelle brune à ventre blanc et bande pectorale brune, nichant en colonies dans les berges sableuses.",
    d: "L’Hirondelle de rivage niche dans tout l’hémisphère Nord et creuse des tunnels dans les berges. En Mongolie, elle est commune près des rivières et lacs — lac Khar Us, lac Buir, lac Ögii, Böön Tsagaan et lac Orog.",
    f: ["Dessus brun.", "Dessous blanc avec une nette bande pectorale brune.", "Courte queue fourchue.", "Petite taille."],
    si: "Hirondelle pâle — plus pâle, bande pectorale floue. Hirondelle de rochers — plus grande, sans bande.",
    h: "Berges et rives de lacs.",
    di: "Lac Khar Us, lac Buir, lac Ögii, Böön Tsagaan, lac Orog, Oulan-Bator.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Coloniale dans des terriers de berges sableuses ; 4 ou 5 œufs.",
    be: "Chasse au ras de l’eau.",
    v: "Un gazouillis sec et râpeux.",
    cu: "Ses colonies ressemblent à un rayon de miel dans les berges.",
    co: "Préoccupation mineure.",
    w: "Berges sableuses du lac Buir en juin.",
    bt: "juin–juil.",
    fa: ["Creuse des tunnels.", "Bande pectorale brune.", "Coloniale."]
  },
  "pale-martin": {
    name: "Hirondelle pâle",
    s: "Petite hirondelle gris-brun pâle à bande pectorale faible. Niche dans les berges sableuses, surtout dans l’ouest et le Gobi.",
    d: "L’Hirondelle pâle niche en Asie centrale, en Mongolie et en Chine. Elle a été séparée de l’Hirondelle de rivage. En Mongolie, elle est commune au lac Khar Us, au lac Ögii, à Böön Tsagaan et sur les lacs du Gobi.",
    f: ["Gris-brun plus pâle que l’Hirondelle de rivage.", "Bande pectorale diffuse et pâle.", "Gorge pâle.", "Queue peu fourchue."],
    si: "Hirondelle de rivage — plus sombre, bande nette.",
    h: "Berges et rives en régions sèches.",
    di: "Lac Khar Us, lac Ögii, Böön Tsagaan, Yolyn Am, lac Orog, Ölgii.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes volants.",
    br: "Coloniale dans les berges sableuses.",
    be: "Chasse au-dessus de l’eau.",
    v: "Un doux gazouillis.",
    cu: "Reconnue comme espèce distincte depuis peu.",
    co: "Préoccupation mineure.",
    w: "Berges du lac Khar Us en juin.",
    bt: "juin–juil.",
    fa: ["Couleur pâle.", "Séparée de l’Hirondelle de rivage.", "Hirondelle des régions sèches."]
  },
  "bull-headed-shrike": {
    name: "Pie-grièche bucéphale",
    s: "Pie-grièche d’Asie orientale à grosse tête, calotte rousse et masque noir. Sur la liste mongole, sans mention GBIF.",
    d: "La Pie-grièche bucéphale vit au Japon, en Corée et dans le nord-est de la Chine. Elle empale ses proies sur des épines en « lardoir ». Les mentions mongoles sont exceptionnelles.",
    f: ["Grosse tête à calotte rousse.", "Masque noir.", "Dos gris.", "Tache alaire blanche."],
    si: "Pie-grièche brune — sans tache alaire blanche.",
    h: "Cultures et lisières.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes, lézards et petits oiseaux.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Empale ses proies sur des épines.",
    v: "Un « kyi-kyi-kyi » rauque.",
    cu: "Au Japon, la hauteur de son lardoir prédirait l’épaisseur de la neige.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Lardoir sur les épines.", "Grosse tête.", "Espèce d’Asie orientale."]
  },
  "brown-shrike": {
    name: "Pie-grièche brune",
    s: "Pie-grièche brune à masque noir et sourcil blanc, qui chasse les insectes depuis les buissons. Visiteuse d’été commune dans le nord.",
    d: "La Pie-grièche brune niche de la Sibérie au Japon et hiverne en Asie du Sud et du Sud-Est. En Mongolie, elle est commune dans les lisières buissonnantes et vallées du Khentii (Khurkh, Terelj), autour d’Oulan-Bator et dans les oasis du Gobi en migration.",
    f: ["Dos et queue bruns.", "Masque noir et sourcil blanc.", "Dessous chamois.", "Bec crochu."],
    si: "Pie-grièche isabelle — plus pâle, queue rousse.",
    h: "Lisières, buissons et vallées.",
    di: "Khurkh, Oulan-Bator, Terelj, Yolyn Am, Khustai, lac Ögii.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Gros insectes, petits lézards et oiseaux.",
    br: "Niche dans les buissons ; 4 à 6 œufs.",
    be: "Chasse depuis des perchoirs dégagés.",
    v: "Un « tchak-tchak » rauque.",
    cu: "Les pies-grièches sont surnommées « oiseaux bouchers ».",
    co: "Préoccupation mineure.",
    w: "Buissons de la vallée de Khurkh en juin.",
    bt: "mai–août",
    fa: ["Surnommée « oiseau boucher ».", "Masque noir.", "Commune dans le nord."]
  },
  "isabelline-shrike": {
    name: "Pie-grièche isabelle",
    s: "Pie-grièche sable pâle à queue rousse et masque noir. Visiteuse d’été commune du Gobi et de l’ouest de la Mongolie.",
    d: "La Pie-grièche isabelle niche dans les déserts et steppes d’Asie centrale et hiverne en Afrique et en Arabie. En Mongolie, elle est commune dans les buissons désertiques et les oasis — Yolyn Am, lac Khar Us, lac Orog et Böön Tsagaan.",
    f: ["Dos gris sable pâle.", "Queue roux vif.", "Masque noir (mâle).", "Petite tache alaire blanche."],
    si: "Pie-grièche brune — brun plus sombre, sans contraste de queue rousse.",
    h: "Buissons désertiques, saxaoul et oasis.",
    di: "Yolyn Am, lac Khar Us, lac Orog, Böön Tsagaan, Khurkh, Oulan-Bator.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes et lézards.",
    br: "Niche dans les buissons ; 4 à 6 œufs.",
    be: "Empale ses proies sur des épines.",
    v: "Un « tchèk » rauque.",
    cu: "Nommée d’après la couleur pâle dite « isabelle ».",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "mai–août",
    fa: ["Queue rousse.", "Pie-grièche du désert.", "Nommée d’après une couleur."]
  },
  "long-tailed-shrike": {
    name: "Pie-grièche schach",
    s: "Grande pie-grièche à longue queue, calotte grise et flancs roux. Erratique très rare avec une seule mention.",
    d: "La Pie-grièche schach vit de l’Asie centrale à l’Asie du Sud-Est. Une mention existe au lac Khar Us.",
    f: ["Longue queue noire.", "Calotte et dos gris, masque noir.", "Flancs et croupion roux."],
    si: "Pie-grièche brune — plus petite, queue plus courte.",
    h: "Milieux ouverts buissonnants.",
    di: "Très rare ; lac Khar Us.",
    mi: "Erratique.",
    fo: "Insectes, lézards.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Se perche sur les fils.",
    v: "Cris rauques ; imite d’autres oiseaux.",
    cu: "Son nom « schach » vient du persan.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Longue queue.", "Imite d’autres oiseaux.", "Très rare en Mongolie."]
  },
  "lesser-grey-shrike": {
    name: "Pie-grièche à poitrine rose",
    s: "Pie-grièche grise et noire au large masque noir couvrant le front et à la poitrine rosée. Rare dans l’extrême ouest de la Mongolie.",
    d: "La Pie-grièche à poitrine rose niche de l’Europe à l’Asie centrale et hiverne en Afrique australe. En Mongolie, il existe des mentions dans l’extrême ouest.",
    f: ["Masque noir s’étendant sur le front.", "Dos gris, ailes noires à tache blanche.", "Poitrine rosée.", "Queue plus courte que la Pie-grièche grise."],
    si: "Pie-grièche grise — masque ne couvrant pas le front, queue plus longue.",
    h: "Steppe arborée.",
    di: "Rare ; extrême ouest.",
    mi: "Visiteuse d’été.",
    fo: "Gros insectes.",
    br: "Niche dans les arbres (rare en Mongolie).",
    be: "Fait du surplace avant de fondre sur sa proie.",
    v: "Un « tchèk » rauque.",
    cu: "Hiverne jusqu’en Afrique du Sud.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Front noir.", "Poitrine rose.", "Grande migratrice."]
  },
  "chinese-grey-shrike": {
    name: "Pie-grièche à longue queue",
    s: "La plus grande pie-grièche, grise à longue queue et grands panneaux alaires blancs. Résidente des steppes de l’est.",
    d: "La Pie-grièche à longue queue (Pie-grièche de Chine) niche dans le nord-est de la Chine, l’est de la Mongolie et la Corée. En Mongolie, on la trouve dans le Dornod (lacs Buir et Ganga) et l’est du Gobi.",
    f: ["Très grande pie-grièche grise à longue queue.", "Grand panneau blanc sur les ailes noires.", "Masque noir.", "Longue queue étagée."],
    si: "Pie-grièche grise — plus petite, panneau blanc plus petit.",
    h: "Steppe ouverte buissonnante.",
    di: "Dornod (lac Buir, lac Ganga, Mongol Daguur), est du Gobi, Khustai.",
    mi: "Résidente ; certaines descendent vers le sud en hiver.",
    fo: "Rongeurs, petits oiseaux et gros insectes.",
    br: "Niche dans les buissons.",
    be: "Chasse depuis des perchoirs élevés.",
    v: "Un caquètement rauque.",
    cu: "La plus grande pie-grièche du monde.",
    co: "Préoccupation mineure.",
    w: "Steppe du lac Buir.",
    bt: "toute l’année",
    fa: ["Plus grande pie-grièche du monde.", "Grand panneau alaire blanc.", "Oiseau des steppes de l’est."]
  },
  "great-grey-shrike": {
    name: "Pie-grièche grise",
    s: "Passereau prédateur gris et blanc à masque noir qui empale ses proies sur des épines. Résidente du Gobi, surtout dans le saxaoul.",
    d: "La Pie-grièche grise vit dans tout l’hémisphère Nord. En Mongolie, sa forme désertique pâle vit dans les déserts à saxaoul du Gobi (lac Orog, Yolyn Am, Böön Tsagaan) et de l’ouest.",
    f: ["Dos gris pâle, dessous blanc.", "Masque noir.", "Ailes noires à tache blanche.", "Longue queue noire et blanche."],
    si: "Pie-grièche à longue queue — plus grande, panneau blanc plus grand.",
    h: "Désert à saxaoul et broussailles.",
    di: "Gobi (lac Orog, Yolyn Am, Böön Tsagaan, Taatsiin Tsagaan), lac Khar Us.",
    mi: "Résidente.",
    fo: "Rongeurs, lézards, petits oiseaux et insectes.",
    br: "Niche dans le saxaoul ou les buissons.",
    be: "Constitue un lardoir de proies sur les épines.",
    v: "Un « chèk-chèk » rauque.",
    cu: "Son nom scientifique excubitor signifie « sentinelle ».",
    co: "Préoccupation mineure.",
    w: "Saxaoul près du lac Orog.",
    bt: "toute l’année",
    fa: ["Son nom signifie « sentinelle ».", "Lardoir sur les épines.", "Forme désertique."]
  }
});
