B2T("en", {
  "red-billed-chough": {
    T: { c: { black: 0.9, red: 0.1 }, hb: ["mountain", "steppe", "settlement"], bk: "curved", bh: ["walk", "soar"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["37–41 cm", "73–90 cm", "260–380 g"] },
    s: "A glossy black crow with a curved red bill and red legs, tumbling acrobatically in flocks. Very common in Mongolia, from cliffs and steppe to Ulaanbaatar.",
    d: "The Red-billed Chough lives in mountains and coasts from Europe to China. Mongolia holds one of the largest populations in the world. It feeds on insects dug from grassland and nests in cliffs, buildings and even in wells. It is abundant around Ulaanbaatar, Terelj, the Khurkh valley, Khustai and Ögii Nuur.",
    f: ["Glossy blue-black plumage.", "Curved, bright red bill.", "Red legs.", "Deeply ‘fingered’ wings in flight.", "Noisy flocks with aerobatic flight."],
    si: "Carrion Crow and Rook — black bills. Daurian Jackdaw — pied or dark with short bill.",
    h: "Mountains, cliffs, steppe and towns.",
    di: "All regions: Ulaanbaatar, Khurkh, Terelj, Ögii Nuur, Khustai, Yolyn Am.",
    mi: "Resident; forms large winter flocks.",
    fo: "Insects and larvae dug from soil; grain.",
    br: "Nests in cliffs, buildings or wells; 3–5 eggs.",
    be: "Aerobatic flocks; digs in pastures.",
    v: "A ringing ‘chee-ow’.",
    cu: "Often nests in Buddhist monasteries.",
    co: "Least Concern.",
    w: "Ulaanbaatar outskirts and Terelj.",
    bt: "all year",
    fa: ["Red curved bill.", "Very common in Mongolia.", "Aerobatic flyer."]
  },
  "siberian-jay": {
    T: { c: { gray: 0.45, rufous: 0.35, brown: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["24–30 cm", "—", "70–100 g"] },
    s: "A fluffy grey-brown jay of the taiga with a rusty tail and wing patches. A tame resident of northern conifer forests, e.g. Bogd Khan Uul.",
    d: "The Siberian Jay lives in the boreal forests from Scandinavia to the Pacific. It stores food for winter and lives in family groups. In Mongolia it is found in the taiga of Khentii (Bogd Khan Uul, Terelj) and Khövsgöl.",
    f: ["Soft grey-brown plumage.", "Rusty-orange tail sides, rump and wing patch.", "Dark cap.", "Short bill."],
    si: "Eurasian Jay — pinkish, with a blue wing patch.",
    h: "Dense spruce and larch taiga.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khövsgöl, Khangai.",
    mi: "Resident.",
    fo: "Insects, berries, seeds and carrion; stores food.",
    br: "Nests in conifers; 3–4 eggs.",
    be: "Tame; moves in family groups.",
    v: "Mewing and harsh calls; mimics.",
    cu: "Called ‘bad luck bird’ in Latin (infaustus) because it visited hunters’ camps.",
    co: "Least Concern.",
    w: "Bogd Khan Uul forest trails.",
    bt: "all year",
    fa: ["Stores food for winter.", "Very tame.", "Latin name means ‘unlucky’."]
  },
  "eurasian-jay": {
    T: { c: { buff: 0.4, gray: 0.2, black: 0.15, white: 0.15, rufous: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["32–35 cm", "52–58 cm", "140–190 g"] },
    s: "A colourful pinkish jay with a bright blue-barred wing patch and black moustache. Resident in forests of the Khentii, including near Ulaanbaatar.",
    d: "The Eurasian Jay lives from Europe to Japan. It buries thousands of nuts each autumn and helps forests regenerate. In Mongolia it is resident in the Khentii (Bogd Khan Uul, Terelj) and parts of the Khangai.",
    f: ["Pinkish-brown body.", "Brilliant blue-and-black barred wing patch.", "Black moustache stripe.", "White rump in flight."],
    si: "Siberian Jay — grey with rusty tail.",
    h: "Deciduous and mixed forests.",
    di: "Ulaanbaatar (Bogd Khan Uul), Terelj, Khurkh, Khövsgöl, Orkhon.",
    mi: "Resident.",
    fo: "Nuts, seeds, insects and eggs.",
    br: "Nests in trees; 4–6 eggs.",
    be: "Buries nuts for winter.",
    v: "A harsh screech; excellent mimic.",
    cu: "Plants oak and pine forests by forgetting stored nuts.",
    co: "Least Concern.",
    w: "Bogd Khan Uul in autumn.",
    bt: "all year",
    fa: ["Plants forests.", "Blue wing patch.", "Excellent mimic."]
  },
  "mongolian-ground-jay": {
    T: { c: { buff: 0.5, black: 0.25, white: 0.15, gray: 0.1 }, hb: ["desert"], bk: "curved", bh: ["walk"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["28–30 cm", "—", "110–140 g"] },
    s: "A sandy desert crow that runs rather than flies, with a black cap and curved bill. A Mongolian speciality of the Gobi and western deserts.",
    d: "Henderson’s Ground-jay lives only in the deserts of Mongolia and north-west China. It runs fast over gravel plains and flies with bold white wing patches. In Mongolia it is found around Khar Us Nuur, Yolyn Am, Orog Nuur, Böön Tsagaan and Taatsiin Tsagaan.",
    f: ["Sandy-buff body.", "Glossy black cap.", "Long, curved black bill.", "Black wings with large white patches in flight.", "Long legs; runs."],
    si: "Unmistakable.",
    h: "Gravel and saxaul desert.",
    di: "Gobi (Yolyn Am, Orog Nuur, Böön Tsagaan, Taatsiin Tsagaan), west (Khar Us Nuur, Achit Nuur).",
    mi: "Resident.",
    fo: "Beetles, larvae, seeds and lizards.",
    br: "Nests in saxaul bushes; 3–5 eggs.",
    be: "Runs fast; stops to dig with its bill.",
    v: "A rattling ‘chuk-chuk’.",
    cu: "A symbol of the Gobi for birdwatchers.",
    co: "Least Concern.",
    w: "Gravel plains near Yolyn Am.",
    bt: "all year",
    fa: ["Runs instead of flying.", "Lives only in Central Asian deserts.", "Big white wing patches."]
  },
  "eurasian-magpie": {
    T: { c: { black: 0.55, white: 0.4, gray: 0.05 }, hb: ["settlement", "steppe", "forest"], bk: "short", bh: ["walk", "perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["44–46 cm", "52–60 cm", "180–270 g"] },
    s: "The black-and-white bird with a long glossy tail found around towns and gers. Very common in northern Mongolia.",
    d: "The Eurasian Magpie is found across Eurasia. It is one of the most intelligent birds — it recognises itself in a mirror. In Mongolia it is common in Ulaanbaatar, around winter camps, in the Khurkh valley, Terelj and Khustai.",
    f: ["Black head, breast and back; white belly and shoulders.", "Long, glossy green-blue tail.", "White wing patches in flight.", "Loud chattering call."],
    si: "Unmistakable.",
    h: "Villages, towns, river woods and steppe with trees.",
    di: "Ulaanbaatar, Khurkh, Terelj, Khustai, Khar Us Nuur, Terkhiin Tsagaan Nuur.",
    mi: "Resident.",
    fo: "Insects, eggs, carrion, scraps and seeds.",
    br: "Domed stick nest in trees; 5–7 eggs.",
    be: "Bold and curious.",
    v: "A loud chattering ‘chak-chak-chak’.",
    cu: "In Mongolian and Chinese belief, a magpie’s call announces guests or good news.",
    co: "Least Concern.",
    w: "Anywhere in Ulaanbaatar.",
    bt: "all year",
    fa: ["Recognises itself in a mirror.", "Announces guests in folklore.", "Domed nest."]
  },
  "eurasian-nutcracker": {
    T: { c: { brown: 0.6, white: 0.35, black: 0.05 }, hb: ["forest"], bk: "long", bh: ["perch"], vt: ["screech"], ac: "day", se: ["resident"], sz: ["32–38 cm", "52–58 cm", "130–190 g"] },
    s: "A dark brown crow covered with white spots, which caches Siberian pine seeds. Resident in mountain taiga, common on Bogd Khan Uul.",
    d: "The Spotted Nutcracker lives in conifer forests across Eurasia. It stores tens of thousands of Siberian pine seeds each autumn and remembers most hiding places. In Mongolia it is common in the Khentii (Bogd Khan Uul, Terelj) and Khangai.",
    f: ["Chocolate-brown with white spots.", "White undertail.", "Long, strong black bill.", "Short tail with white tip."],
    si: "Unmistakable.",
    h: "Siberian pine and larch forests.",
    di: "Ulaanbaatar (Bogd Khan Uul), Terelj, Orkhon, Khurkh, Khövsgöl.",
    mi: "Resident; irrupts when seed crops fail.",
    fo: "Pine seeds, hazelnuts, insects.",
    br: "Nests in conifers in early spring.",
    be: "Carries seeds in a throat pouch.",
    v: "A harsh ‘kraak’.",
    cu: "Plants new Siberian pine forests from forgotten caches.",
    co: "Least Concern.",
    w: "Bogd Khan Uul in September.",
    bt: "September–October",
    fa: ["Remembers thousands of caches.", "Throat pouch for seeds.", "Plants pine forests."]
  },
  "daurian-jackdaw": {
    T: { c: { black: 0.6, white: 0.35, gray: 0.05 }, hb: ["settlement", "steppe", "forest"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["summer", "resident"], sz: ["32–34 cm", "—", "180–230 g"] },
    s: "A small crow; adults are pied with a white collar and belly. Very common in northern Mongolia, especially around Ulaanbaatar.",
    d: "The Daurian Jackdaw breeds from south Siberia and Mongolia to China. It nests in holes in trees, cliffs and buildings. In Mongolia it is abundant in Ulaanbaatar, the Khurkh valley and Terelj, often with Rooks.",
    f: ["Adult: black with a white collar and belly.", "Young birds: dark all over.", "Dark eye.", "Short bill."],
    si: "Eurasian Jackdaw — grey nape, pale eye. Red-billed Chough — red bill.",
    h: "Towns, river valleys and forest edges.",
    di: "Ulaanbaatar, Khurkh, Terelj, Terkhiin Tsagaan Nuur, Orkhon, Khustai.",
    mi: "Summer visitor and resident.",
    fo: "Insects, seeds and scraps.",
    br: "Nests in holes; 4–6 eggs.",
    be: "Flocks with Rooks.",
    v: "A short ‘chak’.",
    cu: "Named after Dauria.",
    co: "Least Concern.",
    w: "Ulaanbaatar in May.",
    bt: "April–September",
    fa: ["Pied adults.", "Nests in holes.", "Flocks with Rooks."]
  },
  "eurasian-jackdaw": {
    T: { c: { black: 0.75, gray: 0.25 }, hb: ["settlement", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["34–39 cm", "64–73 cm", "180–260 g"] },
    s: "A small crow with a grey nape and pale eyes. Scarce in western Mongolia.",
    d: "The Western Jackdaw lives from Europe to Central Asia. In Mongolia it reaches the far west (Ölgii, Khar Us Nuur, Tavan Bogd).",
    f: ["Black with a grey nape.", "Pale silvery eye.", "Short bill."],
    si: "Daurian Jackdaw — dark eye, pied adults.",
    h: "Villages and cliffs.",
    di: "Western Mongolia (Ölgii, Khar Us Nuur, Tavan Bogd).",
    mi: "Resident.",
    fo: "Insects, seeds and scraps.",
    br: "Nests in holes.",
    be: "Social.",
    v: "A sharp ‘chak’.",
    cu: "Famous from Konrad Lorenz’s studies of animal behaviour.",
    co: "Least Concern.",
    w: "Ölgii town.",
    bt: "all year",
    fa: ["Pale eyes.", "Grey nape.", "Studied by Konrad Lorenz."]
  },
  "rook": {
    T: { c: { black: 0.85, white: 0.1, gray: 0.05 }, hb: ["settlement", "steppe"], bk: "long", bh: ["walk"], vt: ["croak"], ac: "day", se: ["summer", "resident"], sz: ["44–46 cm", "81–99 cm", "280–340 g"] },
    s: "A glossy black crow with a bare, pale face at the base of the bill. Nests in noisy colonies (rookeries) in trees in northern Mongolia.",
    d: "The Rook breeds across Eurasia. It nests in colonies in tall trees. In Mongolia it is common in the north, with rookeries in Ulaanbaatar, the Khurkh valley and Terelj.",
    f: ["Glossy black.", "Bare whitish skin around the base of the bill.", "Peaked crown.", "Shaggy ‘trousers’."],
    si: "Carrion Crow — feathered bill base, smoother look.",
    h: "Towns, farmland and river woods.",
    di: "Ulaanbaatar, Khurkh, Terelj, Khustai, Khar Us Nuur, Ögii Nuur.",
    mi: "Summer visitor; some winter.",
    fo: "Worms, grubs and grain.",
    br: "Colonial nests in treetops; 3–5 eggs.",
    be: "Feeds in flocks on fields.",
    v: "A deep ‘kaah’.",
    cu: "Rooks can use and make simple tools.",
    co: "Least Concern.",
    w: "Rookeries along the Tuul River in Ulaanbaatar.",
    bt: "April–August",
    fa: ["Bare face patch.", "Nests in colonies.", "Uses tools."]
  },
  "common-raven": {
    T: { c: { black: 1 }, hb: ["mountain", "steppe", "desert", "settlement"], bk: "long", bh: ["soar", "walk"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["54–67 cm", "115–150 cm", "0.7–1.6 kg"] },
    s: "The largest crow — huge, all black, with a wedge-shaped tail and deep croak. Common throughout Mongolia.",
    d: "The Common Raven is found across the Northern Hemisphere. It is highly intelligent, playful and a skilled scavenger. In Mongolia it lives everywhere, from Ulaanbaatar to the Gobi and Altai, following herders and wildlife.",
    f: ["Very large, all black.", "Heavy bill with shaggy throat feathers.", "Wedge-shaped tail in flight.", "Soars like a raptor."],
    si: "Carrion Crow — smaller, square tail.",
    h: "All habitats.",
    di: "All regions: Ulaanbaatar, Khurkh, Terelj, Khar Us Nuur, Ögii Nuur, Yolyn Am.",
    mi: "Resident.",
    fo: "Carrion, small animals, eggs and scraps.",
    br: "Nests on cliffs, trees or pylons; 4–6 eggs.",
    be: "Rolls and tumbles in flight.",
    v: "A deep ‘kronk’.",
    cu: "Revered in Mongolian and Siberian traditions as a clever messenger.",
    co: "Least Concern.",
    w: "Anywhere.",
    bt: "all year",
    fa: ["Largest songbird.", "Highly intelligent.", "Plays in the air."]
  },
  "carrion-crow": {
    T: { c: { black: 1 }, hb: ["settlement", "steppe", "forest"], bk: "long", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["resident"], sz: ["45–47 cm", "84–100 cm", "400–600 g"] },
    s: "An all-black crow with a stout bill. The eastern form is very common in Ulaanbaatar and across northern Mongolia.",
    d: "The Carrion Crow lives from Europe to Japan; the eastern subspecies (orientalis) is found in Mongolia. It is a common scavenger in towns, on rubbish tips and in the countryside. It is especially numerous in Ulaanbaatar, Terelj, the Khurkh valley and Khar Us Nuur.",
    f: ["All glossy black.", "Stout bill with feathered base.", "Square-ended tail.", "Walks confidently."],
    si: "Rook — bare face. Common Raven — much larger, wedge tail.",
    h: "Towns, farmland, steppe and forest edges.",
    di: "All regions: Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Khustai.",
    mi: "Resident.",
    fo: "Carrion, scraps, insects and eggs.",
    br: "Nests in trees; 3–5 eggs.",
    be: "Bold scavenger; drops nuts on roads.",
    v: "A harsh ‘kraa-kraa’.",
    cu: "One of the most common birds of Ulaanbaatar.",
    co: "Least Concern.",
    w: "Anywhere in Ulaanbaatar.",
    bt: "all year",
    fa: ["Very common in Ulaanbaatar.", "Scavenger.", "Square tail."]
  }
});
