B2T("fr", {
  "red-billed-chough": {
    name: "Crave à bec rouge",
    s: "Corvidé noir brillant au bec rouge arqué et aux pattes rouges, qui virevolte en groupes acrobatiques. Très commun en Mongolie, des falaises et steppes jusqu’à Oulan-Bator.",
    d: "Le Crave à bec rouge vit dans les montagnes et sur les côtes, de l’Europe à la Chine. La Mongolie abrite l’une des plus grandes populations au monde. Il se nourrit d’insectes déterrés dans les prairies et niche dans les falaises, les bâtiments et même les puits. Il abonde autour d’Oulan-Bator, de Terelj, de la vallée de Khurkh, de Khustai et du lac Ögii.",
    f: ["Plumage noir bleuté brillant.", "Bec rouge vif arqué.", "Pattes rouges.", "Ailes aux « doigts » profonds en vol.", "Groupes bruyants au vol acrobatique."],
    si: "Corneille et Corbeau freux — bec noir. Choucas de Daourie — pie ou sombre, bec court.",
    h: "Montagnes, falaises, steppe et villes.",
    di: "Toutes les régions : Oulan-Bator, Khurkh, Terelj, lac Ögii, Khustai, Yolyn Am.",
    mi: "Résident ; grands groupes en hiver.",
    fo: "Insectes et larves du sol ; céréales.",
    br: "Niche dans les falaises, bâtiments ou puits ; 3 à 5 œufs.",
    be: "Groupes acrobatiques ; fouille les pâturages.",
    v: "Un « tchii-aou » sonore.",
    cu: "Niche souvent dans les monastères bouddhistes.",
    co: "Préoccupation mineure.",
    w: "Abords d’Oulan-Bator et Terelj.",
    bt: "toute l’année",
    fa: ["Bec rouge arqué.", "Très commun en Mongolie.", "Voltigeur acrobatique."]
  },
  "siberian-jay": {
    name: "Mésangeai imitateur",
    s: "Geai duveteux gris-brun de la taïga, aux côtés de la queue et taches alaires rouille. Résident confiant des forêts de conifères du nord, comme au Bogd Khan Uul.",
    d: "Le Mésangeai imitateur vit dans les forêts boréales, de la Scandinavie au Pacifique. Il stocke de la nourriture pour l’hiver et vit en groupes familiaux. En Mongolie, on le trouve dans la taïga du Khentii (Bogd Khan Uul, Terelj) et du Khövsgöl.",
    f: ["Plumage gris-brun doux.", "Côtés de la queue, croupion et tache alaire orange rouille.", "Calotte sombre.", "Bec court."],
    si: "Geai des chênes — rosé, tache alaire bleue.",
    h: "Taïga dense d’épicéas et de mélèzes.",
    di: "Khentii (Bogd Khan Uul, Terelj), Khövsgöl, Khangaï.",
    mi: "Résident.",
    fo: "Insectes, baies, graines et charognes ; fait des réserves.",
    br: "Niche dans les conifères ; 3 ou 4 œufs.",
    be: "Confiant ; se déplace en groupes familiaux.",
    v: "Miaulements et cris rauques ; imite.",
    cu: "Son nom latin infaustus (« malchanceux ») vient de ses visites aux camps de chasseurs.",
    co: "Préoccupation mineure.",
    w: "Sentiers forestiers du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Fait des réserves pour l’hiver.", "Très confiant.", "Son nom latin signifie « malchanceux »."]
  },
  "eurasian-jay": {
    name: "Geai des chênes",
    s: "Geai rosé coloré à tache alaire barrée de bleu vif et moustache noire. Résident des forêts du Khentii, y compris près d’Oulan-Bator.",
    d: "Le Geai des chênes vit de l’Europe au Japon. Il enterre des milliers de glands et de noix chaque automne et aide les forêts à se régénérer. En Mongolie, il réside dans le Khentii (Bogd Khan Uul, Terelj) et une partie du Khangaï.",
    f: ["Corps brun rosé.", "Tache alaire barrée de bleu vif et de noir.", "Trait de moustache noir.", "Croupion blanc en vol."],
    si: "Mésangeai imitateur — gris à queue rouille.",
    h: "Forêts feuillues et mixtes.",
    di: "Oulan-Bator (Bogd Khan Uul), Terelj, Khurkh, Khövsgöl, Orkhon.",
    mi: "Résident.",
    fo: "Noix, graines, insectes et œufs.",
    br: "Niche dans les arbres ; 4 à 6 œufs.",
    be: "Enterre des noix pour l’hiver.",
    v: "Un cri rauque ; excellent imitateur.",
    cu: "Plante chênaies et pinèdes en oubliant ses réserves.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul en automne.",
    bt: "toute l’année",
    fa: ["Plante des forêts.", "Tache alaire bleue.", "Excellent imitateur."]
  },
  "mongolian-ground-jay": {
    name: "Podoce de Henderson",
    s: "Corvidé couleur sable des déserts qui court plutôt que de voler, à calotte noire et bec arqué. Une spécialité mongole du Gobi et des déserts de l’ouest.",
    d: "Le Podoce de Henderson vit uniquement dans les déserts de Mongolie et du nord-ouest de la Chine. Il court vite sur les regs et montre en vol de grandes taches alaires blanches. En Mongolie, on le trouve autour du lac Khar Us, de Yolyn Am, du lac Orog, de Böön Tsagaan et de Taatsiin Tsagaan.",
    f: ["Corps chamois sable.", "Calotte noire brillante.", "Long bec noir arqué.", "Ailes noires à grandes taches blanches en vol.", "Longues pattes ; court."],
    si: "Inconfondable.",
    h: "Regs et déserts à saxaoul.",
    di: "Gobi (Yolyn Am, lac Orog, Böön Tsagaan, Taatsiin Tsagaan), ouest (lac Khar Us, lac Achit).",
    mi: "Résident.",
    fo: "Coléoptères, larves, graines et lézards.",
    br: "Niche dans les buissons de saxaoul ; 3 à 5 œufs.",
    be: "Court vite ; s’arrête pour creuser avec son bec.",
    v: "Un « tchouk-tchouk » crépitant.",
    cu: "Un symbole du Gobi pour les ornithologues.",
    co: "Préoccupation mineure.",
    w: "Regs près de Yolyn Am.",
    bt: "toute l’année",
    fa: ["Court au lieu de voler.", "Vit seulement dans les déserts d’Asie centrale.", "Grandes taches alaires blanches."]
  },
  "eurasian-magpie": {
    name: "Pie bavarde",
    s: "L’oiseau noir et blanc à longue queue brillante des villes et des yourtes. Très commune dans le nord de la Mongolie.",
    d: "La Pie bavarde est présente dans toute l’Eurasie. C’est l’un des oiseaux les plus intelligents — elle se reconnaît dans un miroir. En Mongolie, elle est commune à Oulan-Bator, autour des campements d’hiver, dans la vallée de Khurkh, à Terelj et à Khustai.",
    f: ["Tête, poitrine et dos noirs ; ventre et épaules blancs.", "Longue queue brillante vert-bleu.", "Taches alaires blanches en vol.", "Jacassement sonore."],
    si: "Inconfondable.",
    h: "Villages, villes, bois riverains et steppe arborée.",
    di: "Oulan-Bator, Khurkh, Terelj, Khustai, lac Khar Us, Terkhiin Tsagaan Nuur.",
    mi: "Résidente.",
    fo: "Insectes, œufs, charognes, déchets et graines.",
    br: "Nid de branches en dôme dans les arbres ; 5 à 7 œufs.",
    be: "Hardie et curieuse.",
    v: "Un « tchak-tchak-tchak » sonore.",
    cu: "En Mongolie et en Chine, le cri de la pie annonce des invités ou une bonne nouvelle.",
    co: "Préoccupation mineure.",
    w: "Partout à Oulan-Bator.",
    bt: "toute l’année",
    fa: ["Se reconnaît dans un miroir.", "Annonce des invités.", "Nid en dôme."]
  },
  "eurasian-nutcracker": {
    name: "Cassenoix moucheté",
    s: "Corvidé brun foncé couvert de taches blanches, qui cache les graines de pin de Sibérie. Résident de la taïga de montagne, commun au Bogd Khan Uul.",
    d: "Le Cassenoix moucheté vit dans les forêts de conifères d’Eurasie. Il cache chaque automne des dizaines de milliers de graines de pin de Sibérie et retrouve la plupart de ses caches. En Mongolie, il est commun dans le Khentii (Bogd Khan Uul, Terelj) et le Khangaï.",
    f: ["Brun chocolat moucheté de blanc.", "Sous-caudales blanches.", "Long bec noir robuste.", "Queue courte à bout blanc."],
    si: "Inconfondable.",
    h: "Forêts de pins de Sibérie et de mélèzes.",
    di: "Oulan-Bator (Bogd Khan Uul), Terelj, Orkhon, Khurkh, Khövsgöl.",
    mi: "Résident ; invasions quand les graines manquent.",
    fo: "Graines de pin, noisettes, insectes.",
    br: "Niche dans les conifères au début du printemps.",
    be: "Transporte les graines dans une poche gulaire.",
    v: "Un « kraak » rauque.",
    cu: "Plante de nouvelles forêts de pins par ses caches oubliées.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul en septembre.",
    bt: "sept.–oct.",
    fa: ["Se souvient de milliers de caches.", "Poche gulaire à graines.", "Plante des pinèdes."]
  },
  "daurian-jackdaw": {
    name: "Choucas de Daourie",
    s: "Petit corvidé ; les adultes sont pie avec un collier et un ventre blancs. Très commun dans le nord de la Mongolie, surtout autour d’Oulan-Bator.",
    d: "Le Choucas de Daourie niche du sud de la Sibérie et de la Mongolie à la Chine. Il niche dans des cavités d’arbres, de falaises et de bâtiments. En Mongolie, il abonde à Oulan-Bator, dans la vallée de Khurkh et à Terelj, souvent avec les Corbeaux freux.",
    f: ["Adulte : noir avec collier et ventre blancs.", "Jeunes : entièrement sombres.", "Œil sombre.", "Bec court."],
    si: "Choucas des tours — nuque grise, œil pâle. Crave — bec rouge.",
    h: "Villes, vallées et lisières.",
    di: "Oulan-Bator, Khurkh, Terelj, Terkhiin Tsagaan Nuur, Orkhon, Khustai.",
    mi: "Visiteur d’été et résident.",
    fo: "Insectes, graines et déchets.",
    br: "Niche dans des cavités ; 4 à 6 œufs.",
    be: "En groupes avec les freux.",
    v: "Un « tchak » bref.",
    cu: "Nommé d’après la Daourie.",
    co: "Préoccupation mineure.",
    w: "Oulan-Bator en mai.",
    bt: "avril–sept.",
    fa: ["Adultes pie.", "Niche dans des cavités.", "En groupes avec les freux."]
  },
  "eurasian-jackdaw": {
    name: "Choucas des tours",
    s: "Petit corvidé à nuque grise et yeux pâles. Peu commun dans l’ouest de la Mongolie.",
    d: "Le Choucas des tours vit de l’Europe à l’Asie centrale. En Mongolie, il atteint l’extrême ouest (Ölgii, lac Khar Us, Tavan Bogd).",
    f: ["Noir à nuque grise.", "Œil pâle argenté.", "Bec court."],
    si: "Choucas de Daourie — œil sombre, adultes pie.",
    h: "Villages et falaises.",
    di: "Ouest de la Mongolie (Ölgii, lac Khar Us, Tavan Bogd).",
    mi: "Résident.",
    fo: "Insectes, graines et déchets.",
    br: "Niche dans des cavités.",
    be: "Sociable.",
    v: "Un « tchak » sec.",
    cu: "Rendu célèbre par les études de Konrad Lorenz sur le comportement animal.",
    co: "Préoccupation mineure.",
    w: "Ville d’Ölgii.",
    bt: "toute l’année",
    fa: ["Yeux pâles.", "Nuque grise.", "Étudié par Konrad Lorenz."]
  },
  "rook": {
    name: "Corbeau freux",
    s: "Corvidé noir brillant à face nue et pâle à la base du bec. Niche en colonies bruyantes (corbeautières) dans les arbres du nord de la Mongolie.",
    d: "Le Corbeau freux niche dans toute l’Eurasie, en colonies dans les grands arbres. En Mongolie, il est commun dans le nord, avec des corbeautières à Oulan-Bator, dans la vallée de Khurkh et à Terelj.",
    f: ["Noir brillant.", "Peau nue blanchâtre à la base du bec.", "Calotte en pointe.", "« Culotte » de plumes ébouriffées."],
    si: "Corneille noire — base du bec emplumée, aspect plus lisse.",
    h: "Villes, cultures et bois riverains.",
    di: "Oulan-Bator, Khurkh, Terelj, Khustai, lac Khar Us, lac Ögii.",
    mi: "Visiteur d’été ; quelques hivernants.",
    fo: "Vers, larves et céréales.",
    br: "Colonies à la cime des arbres ; 3 à 5 œufs.",
    be: "Se nourrit en groupes dans les champs.",
    v: "Un « kaah » grave.",
    cu: "Le freux sait utiliser et fabriquer des outils simples.",
    co: "Préoccupation mineure.",
    w: "Corbeautières le long de la Tuul à Oulan-Bator.",
    bt: "avril–août",
    fa: ["Face nue.", "Niche en colonies.", "Utilise des outils."]
  },
  "common-raven": {
    name: "Grand Corbeau",
    s: "Le plus grand corvidé — énorme, tout noir, à queue cunéiforme et croassement grave. Commun dans toute la Mongolie.",
    d: "Le Grand Corbeau est présent dans tout l’hémisphère Nord. Très intelligent et joueur, c’est un charognard habile. En Mongolie, il vit partout, d’Oulan-Bator au Gobi et à l’Altaï, suivant éleveurs et faune sauvage.",
    f: ["Très grand, entièrement noir.", "Bec massif et plumes de gorge hérissées.", "Queue cunéiforme en vol.", "Plane comme un rapace."],
    si: "Corneille noire — plus petite, queue carrée.",
    h: "Tous milieux.",
    di: "Toutes les régions : Oulan-Bator, Khurkh, Terelj, lac Khar Us, lac Ögii, Yolyn Am.",
    mi: "Résident.",
    fo: "Charognes, petits animaux, œufs et déchets.",
    br: "Niche sur les falaises, arbres ou pylônes ; 4 à 6 œufs.",
    be: "Fait des tonneaux et culbutes en vol.",
    v: "Un « kronk » grave.",
    cu: "Vénéré dans les traditions mongoles et sibériennes comme un messager rusé.",
    co: "Préoccupation mineure.",
    w: "Partout.",
    bt: "toute l’année",
    fa: ["Le plus grand passereau.", "Très intelligent.", "Joue en vol."]
  },
  "carrion-crow": {
    name: "Corneille noire",
    s: "Corvidé entièrement noir au bec fort. La forme orientale est très commune à Oulan-Bator et dans tout le nord de la Mongolie.",
    d: "La Corneille noire vit de l’Europe au Japon ; la sous-espèce orientale (orientalis) peuple la Mongolie. C’est un charognard commun des villes, décharges et campagnes. Elle est particulièrement nombreuse à Oulan-Bator, Terelj, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Entièrement noir brillant.", "Bec fort à base emplumée.", "Queue au bout carré.", "Marche avec assurance."],
    si: "Corbeau freux — face nue. Grand Corbeau — bien plus grand, queue cunéiforme.",
    h: "Villes, cultures, steppe et lisières.",
    di: "Toutes les régions : Oulan-Bator, Terelj, Khurkh, lac Khar Us, Khustai.",
    mi: "Résidente.",
    fo: "Charognes, déchets, insectes et œufs.",
    br: "Niche dans les arbres ; 3 à 5 œufs.",
    be: "Charognarde hardie ; lâche des noix sur les routes.",
    v: "Un « kraa-kraa » rauque.",
    cu: "L’un des oiseaux les plus communs d’Oulan-Bator.",
    co: "Préoccupation mineure.",
    w: "Partout à Oulan-Bator.",
    bt: "toute l’année",
    fa: ["Très commune à Oulan-Bator.", "Charognarde.", "Queue carrée."]
  }
});
