B2T("en", {
  "common-starling": {
    T: { c: { black: 0.7, white: 0.15, brown: 0.1, yellow: 0.05 }, hb: ["settlement", "steppe"], bk: "long", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["19–23 cm", "31–44 cm", "60–100 g"] },
    s: "A glossy, speckled black songbird with a pointed yellow bill, a skilled mimic. A summer visitor mainly to western Mongolia.",
    d: "The Common Starling breeds from Europe to western Mongolia and has been introduced worldwide. Winter flocks form huge swirling murmurations. In Mongolia it breeds in villages and river woods in the west, especially Khar Us Nuur and Achit Nuur.",
    f: ["Glossy black with purple-green sheen.", "White spots, strongest in winter.", "Pointed yellow bill in summer.", "Short tail, triangular wings."],
    si: "White-cheeked Starling — grey-brown with white cheeks, orange bill.",
    h: "Villages, farmland and river woods.",
    di: "Western Mongolia (Khar Us Nuur, Achit Nuur), Ulaanbaatar, Ögii Nuur, Khurkh.",
    mi: "Summer visitor, April–September.",
    fo: "Insects, worms and fruit.",
    br: "Nests in holes; 4–6 eggs.",
    be: "Flocks perform murmurations.",
    v: "A rambling song full of mimicry.",
    cu: "Mozart kept a pet starling that sang his melodies.",
    co: "Least Concern.",
    w: "Khar Us Nuur villages in June.",
    bt: "May–August",
    fa: ["Excellent mimic.", "Forms murmurations.", "Mozart’s pet bird."]
  },
  "rosy-starling": {
    T: { c: { black: 0.5, red: 0.3, white: 0.2 }, hb: ["steppe", "desert"], bk: "short", bh: ["walk", "soar"], vt: ["song"], ac: "day", se: ["summer"], sz: ["19–22 cm", "37–40 cm", "60–90 g"] },
    s: "A striking pink-and-black starling with a shaggy crest, following locust swarms. An irregular summer visitor to western Mongolia.",
    d: "The Rosy Starling breeds on the steppes of Central Asia and winters in India. It nests in huge colonies wherever grasshoppers are abundant. In Mongolia it appears in the west (Khar Us Nuur) and at Terkhiin Tsagaan Nuur and the Gobi.",
    f: ["Pink body.", "Glossy black head, wings and tail.", "Shaggy crest.", "Short pinkish bill."],
    si: "Unmistakable.",
    h: "Steppe with rocky places.",
    di: "Khar Us Nuur, Terkhiin Tsagaan Nuur, Orog Nuur, Yolyn Am, Ölgii.",
    mi: "Irregular summer visitor, May–August.",
    fo: "Grasshoppers and locusts; berries.",
    br: "Colonial in rock crevices.",
    be: "Follows locust outbreaks.",
    v: "Chattering song.",
    cu: "Farmers welcome it as a natural locust control.",
    co: "Least Concern.",
    w: "Western steppe in June in grasshopper years.",
    bt: "June",
    fa: ["Pink and black.", "Eats locusts.", "Irregular visitor."]
  },
  "purple-backed-starling": {
    T: { c: { gray: 0.4, black: 0.3, white: 0.2, buff: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16–19 cm", "—", "40–50 g"] },
    s: "A small starling with a pale grey head, purple-black back and white wing bars. A summer visitor, mainly in the Gobi and east.",
    d: "The Daurian Starling breeds in north-east China, Korea and south-east Siberia and winters in South-East Asia. In Mongolia it is seen at Yolyn Am, Ulaanbaatar, Terelj and Dornod.",
    f: ["Pale grey head and underparts.", "Glossy purple back.", "Black wings with white bars.", "Small dark patch on the nape."],
    si: "White-cheeked Starling — larger, orange bill.",
    h: "Woods, parks and villages.",
    di: "Yolyn Am, Ulaanbaatar, Terelj, Böön Tsagaan, Dornod.",
    mi: "Summer visitor, May–August.",
    fo: "Insects and fruit.",
    br: "Nests in tree holes.",
    be: "Forms small flocks.",
    v: "Soft chattering.",
    cu: "Also called the Daurian Starling.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May–June",
    fa: ["Purple back.", "White wing bars.", "Small starling."]
  },
  "white-cheeked-starling": {
    T: { c: { gray: 0.45, brown: 0.3, white: 0.15, black: 0.05, yellow: 0.05 }, hb: ["settlement", "forest", "steppe"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["22–24 cm", "—", "75–100 g"] },
    s: "A grey-brown starling with a white face and orange bill. Common in summer in northern and eastern Mongolia, including Ulaanbaatar.",
    d: "The White-cheeked Starling breeds in eastern Asia and winters in southern China. In Mongolia it nests in tree holes and buildings around Ulaanbaatar, the Khurkh valley, Terelj, Ganga Nuur and Gobi oases.",
    f: ["Grey-brown body.", "White face streaked with black.", "Orange bill and legs.", "White rump in flight."],
    si: "Common Starling — glossy black, spotted.",
    h: "Towns, parks and river woods.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Terelj, Ganga Nuur, Ögii Nuur.",
    mi: "Summer visitor, April–September.",
    fo: "Insects and fruit.",
    br: "Nests in holes; 4–7 eggs.",
    be: "Flocks on lawns and fields.",
    v: "A harsh, chattering song.",
    cu: "One of the most common birds in Tokyo.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in May.",
    bt: "May–August",
    fa: ["White face.", "Orange bill.", "Common in towns."]
  },
  "crested-myna": {
    T: { c: { black: 0.85, white: 0.1, yellow: 0.05 }, hb: ["settlement"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["25–27 cm", "—", "100–140 g"] },
    s: "An all-black myna with a tuft on the forehead and white wing patches. On the Mongolian list, with no GBIF records.",
    d: "The Crested Myna lives in southern China and Taiwan. Any record in Mongolia would be exceptional.",
    f: ["Black with a bushy tuft above the bill.", "White wing patches in flight.", "Ivory bill; pale eye."],
    si: "Unmistakable.",
    h: "Towns and farmland.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects and fruit.",
    br: "Nests in holes (not in Mongolia).",
    be: "Walks on lawns.",
    v: "Varied whistles; mimics.",
    cu: "Kept as a talking cage bird.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Forehead tuft.", "Mimics speech.", "Southern Chinese species."]
  },
  "eurasian-golden-oriole": {
    T: { c: { yellow: 0.6, black: 0.3, red: 0.05, gray: 0.05 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["22–25 cm", "44–47 cm", "56–79 g"] },
    s: "A brilliant golden-yellow bird with black wings and a fluty song. A scarce migrant in western Mongolia and Gobi oases.",
    d: "The Eurasian Golden Oriole breeds from Europe to western Siberia and winters in Africa. It stays hidden in tree canopies. In Mongolia it is a scarce visitor to Yolyn Am and Khar Us Nuur.",
    f: ["Male: golden yellow with black wings and tail.", "Pinkish-red bill.", "Female: greenish with streaked breast."],
    si: "Black-naped Oriole — black band through the eye to the nape.",
    h: "Tall broadleaf trees.",
    di: "Yolyn Am, Khar Us Nuur, Khurkh.",
    mi: "Rare migrant, May–August.",
    fo: "Insects and fruit.",
    br: "Hammock nest in a tree fork (not confirmed in Mongolia).",
    be: "Hides in the canopy.",
    v: "A fluty ‘weela-weeoo’.",
    cu: "A bird of summer in European folklore.",
    co: "Least Concern.",
    w: "Yolyn Am oasis in May.",
    bt: "May",
    fa: ["Golden plumage.", "Fluty song.", "Hides in treetops."]
  },
  "black-naped-oriole": {
    T: { c: { yellow: 0.65, black: 0.3, red: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage", "summer"], sz: ["25–28 cm", "—", "70–100 g"] },
    s: "A golden oriole with a broad black band from the eye to the nape. A scarce visitor to northern woods and Gobi oases.",
    d: "The Black-naped Oriole breeds from eastern Siberia to South-East Asia. In Mongolia it is recorded in Terelj, Ulaanbaatar, Yolyn Am and Dornod.",
    f: ["Bright yellow body.", "Black band through the eye to the nape.", "Black wings and tail.", "Pink bill."],
    si: "Eurasian Golden Oriole — no black nape band.",
    h: "Broadleaf woods and parks.",
    di: "Terelj, Ulaanbaatar, Yolyn Am, Mongol Daguur.",
    mi: "Scarce summer visitor and migrant, May–August.",
    fo: "Insects and fruit.",
    br: "Hammock nest in trees.",
    be: "Sings from the canopy.",
    v: "A loud, liquid whistle.",
    cu: "Its call is a sign of summer in China.",
    co: "Least Concern.",
    w: "Terelj in June.",
    bt: "June",
    fa: ["Black band on the nape.", "Bright yellow.", "Hammock nest."]
  },
  "black-drongo": {
    T: { c: { black: 0.95, white: 0.05 }, hb: ["steppe", "settlement"], bk: "short", bh: ["perch"], vt: ["screech"], ac: "day", se: ["passage"], sz: ["28–32 cm", "—", "40–60 g"] },
    s: "A glossy black bird with a long, deeply forked tail that sallies after insects. A scarce migrant, mainly at Yolyn Am.",
    d: "The Black Drongo breeds from India to north-east China. It is fearless and chases away crows and raptors. In Mongolia it appears in spring at Yolyn Am and in the east.",
    f: ["All glossy black.", "Long, deeply forked tail.", "Small white spot at the bill base.", "Upright stance on wires."],
    si: "Unmistakable.",
    h: "Open country with trees.",
    di: "Yolyn Am, Taatsiin Tsagaan, eastern Mongolia.",
    mi: "Scarce migrant, May–June.",
    fo: "Flying insects.",
    br: "Nests in trees (not in Mongolia).",
    be: "Chases away much larger birds.",
    v: "Harsh calls; mimics raptors.",
    cu: "Called ‘king crow’ in India for its boldness.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May",
    fa: ["Forked tail.", "Very bold.", "Mimics hawks."]
  },
  "bohemian-waxwing": {
    T: { c: { buff: 0.4, gray: 0.25, black: 0.15, yellow: 0.1, red: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["winter"], sz: ["19–23 cm", "32–35 cm", "50–70 g"] },
    s: "A plump, crested, pinkish-brown bird with red ‘wax’ tips on its wings and a yellow tail tip. Winter flocks visit berry trees in Ulaanbaatar.",
    d: "The Bohemian Waxwing breeds in the northern taiga and wanders south in winter in search of berries. In Mongolia flocks appear in Ulaanbaatar, Terelj and Gobi oases from October to April.",
    f: ["Prominent crest.", "Black mask and throat.", "Red waxy tips on the secondaries.", "Yellow-tipped tail.", "Trilling call."],
    si: "Japanese Waxwing — red tail tip, no yellow in the wing.",
    h: "Berry trees in towns and forests.",
    di: "Ulaanbaatar, Terelj, Yolyn Am, Khurkh.",
    mi: "Winter visitor, October–April.",
    fo: "Berries; insects in summer.",
    br: "Nests in the taiga (not in Mongolia).",
    be: "Travels in tight, trilling flocks.",
    v: "A high, bell-like trill.",
    cu: "Irruptions were once thought to foretell plagues.",
    co: "Least Concern.",
    w: "Rowan trees in Ulaanbaatar in winter.",
    bt: "November–March",
    fa: ["Red waxy wing tips.", "Crested.", "Berry-eater."]
  },
  "japanese-waxwing": {
    T: { c: { buff: 0.45, gray: 0.25, black: 0.15, red: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["winter"], sz: ["15–18 cm", "—", "50–60 g"] },
    s: "A crested waxwing with a red tail tip and black crest edge. A rare winter visitor; Near Threatened.",
    d: "The Japanese Waxwing breeds in the Russian Far East and winters in Japan, Korea and China. It has been recorded a few times in Ulaanbaatar in winter.",
    f: ["Crest with a black border.", "Red tail tip.", "Grey-brown body.", "Red wing panel, no waxy tips."],
    si: "Bohemian Waxwing — yellow tail tip.",
    h: "Berry trees.",
    di: "Rare; Ulaanbaatar, Dornod.",
    mi: "Rare winter visitor.",
    fo: "Berries.",
    br: "Nests in the Far East (not in Mongolia).",
    be: "Flocks with Bohemian Waxwings.",
    v: "A thin trill.",
    cu: "One of only three waxwing species.",
    co: "Near Threatened.",
    w: "Check waxwing flocks in Ulaanbaatar.",
    bt: "winter",
    fa: ["Red tail tip.", "Near Threatened.", "Rare in Mongolia."]
  },
  "flavescent-bulbul": {
    T: { c: { yellow: 0.4, brown: 0.3, gray: 0.2, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["20–22 cm", "—", "30–40 g"] },
    s: "An olive-yellow bulbul of South-East Asian hills. On the Mongolian list, with no GBIF records.",
    d: "The Flavescent Bulbul lives in the hills of north-east India and South-East Asia. A record in Mongolia would be exceptional.",
    f: ["Olive-brown upperparts.", "Yellowish underparts.", "White eyebrow line in front of the eye.", "Short crest."],
    si: "Unmistakable in Mongolia.",
    h: "Hill scrub.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Fruit and insects.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Lives in small groups.",
    v: "Cheerful whistles.",
    cu: "Bulbuls are common garden birds in tropical Asia.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Tropical species.", "Yellowish belly.", "Exceptional in Mongolia."]
  }
});
