B2T("fr", {
  "common-starling": {
    name: "Étourneau sansonnet",
    s: "Passereau noir brillant moucheté, au bec jaune pointu, habile imitateur. Visiteur d’été surtout dans l’ouest de la Mongolie.",
    d: "L’Étourneau sansonnet niche de l’Europe à l’ouest de la Mongolie et a été introduit dans le monde entier. Ses vols hivernaux forment d’immenses nuées tourbillonnantes. En Mongolie, il niche dans les villages et bois riverains de l’ouest, surtout au lac Khar Us et au lac Achit.",
    f: ["Noir brillant à reflets pourpres et verts.", "Taches blanches, plus marquées en hiver.", "Bec jaune pointu en été.", "Queue courte, ailes triangulaires."],
    si: "Étourneau gris — gris-brun à joues blanches, bec orange.",
    h: "Villages, cultures et bois riverains.",
    di: "Ouest (lac Khar Us, lac Achit), Oulan-Bator, lac Ögii, Khurkh.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes, vers et fruits.",
    br: "Niche dans des cavités ; 4 à 6 œufs.",
    be: "Les vols forment des nuées spectaculaires.",
    v: "Un chant décousu plein d’imitations.",
    cu: "Mozart avait un étourneau apprivoisé qui chantait ses mélodies.",
    co: "Préoccupation mineure.",
    w: "Villages du lac Khar Us en juin.",
    bt: "mai–août",
    fa: ["Excellent imitateur.", "Forme des nuées.", "Oiseau de compagnie de Mozart."]
  },
  "rosy-starling": {
    name: "Étourneau roselin",
    s: "Étourneau rose et noir saisissant à huppe ébouriffée, qui suit les essaims de criquets. Visiteur d’été irrégulier dans l’ouest de la Mongolie.",
    d: "L’Étourneau roselin niche dans les steppes d’Asie centrale et hiverne en Inde. Il niche en immenses colonies là où abondent les sauterelles. En Mongolie, il apparaît dans l’ouest (lac Khar Us), à Terkhiin Tsagaan Nuur et dans le Gobi.",
    f: ["Corps rose.", "Tête, ailes et queue noir brillant.", "Huppe ébouriffée.", "Bec court rosâtre."],
    si: "Inconfondable.",
    h: "Steppe avec rochers.",
    di: "Lac Khar Us, Terkhiin Tsagaan Nuur, lac Orog, Yolyn Am, Ölgii.",
    mi: "Visiteur d’été irrégulier, mai–août.",
    fo: "Sauterelles et criquets ; baies.",
    br: "Colonial dans les fissures rocheuses.",
    be: "Suit les pullulations de criquets.",
    v: "Chant jacassant.",
    cu: "Les agriculteurs l’apprécient comme régulateur naturel des criquets.",
    co: "Préoccupation mineure.",
    w: "Steppe de l’ouest en juin les années à sauterelles.",
    bt: "juin",
    fa: ["Rose et noir.", "Mange des criquets.", "Visiteur irrégulier."]
  },
  "purple-backed-starling": {
    name: "Étourneau de Daourie",
    s: "Petit étourneau à tête gris pâle, dos pourpre-noir et barres alaires blanches. Visiteur d’été, surtout dans le Gobi et l’est.",
    d: "L’Étourneau de Daourie niche dans le nord-est de la Chine, en Corée et dans le sud-est de la Sibérie et hiverne en Asie du Sud-Est. En Mongolie, on le voit à Yolyn Am, Oulan-Bator, Terelj et dans le Dornod.",
    f: ["Tête et dessous gris pâle.", "Dos pourpre brillant.", "Ailes noires à barres blanches.", "Petite tache sombre sur la nuque."],
    si: "Étourneau gris — plus grand, bec orange.",
    h: "Bois, parcs et villages.",
    di: "Yolyn Am, Oulan-Bator, Terelj, Böön Tsagaan, Dornod.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes et fruits.",
    br: "Niche dans des cavités d’arbres.",
    be: "Forme de petits groupes.",
    v: "Doux jacassement.",
    cu: "Nommé d’après la Daourie.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai–juin",
    fa: ["Dos pourpre.", "Barres alaires blanches.", "Petit étourneau."]
  },
  "white-cheeked-starling": {
    name: "Étourneau gris",
    s: "Étourneau gris-brun à face blanche et bec orange. Commun en été dans le nord et l’est de la Mongolie, dont Oulan-Bator.",
    d: "L’Étourneau gris niche en Asie orientale et hiverne dans le sud de la Chine. En Mongolie, il niche dans les cavités d’arbres et bâtiments autour d’Oulan-Bator, de la vallée de Khurkh, de Terelj, du lac Ganga et des oasis du Gobi.",
    f: ["Corps gris-brun.", "Face blanche striée de noir.", "Bec et pattes orange.", "Croupion blanc en vol."],
    si: "Étourneau sansonnet — noir brillant moucheté.",
    h: "Villes, parcs et bois riverains.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Terelj, lac Ganga, lac Ögii.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes et fruits.",
    br: "Niche dans des cavités ; 4 à 7 œufs.",
    be: "Groupes sur les pelouses et champs.",
    v: "Un chant rauque et jacassant.",
    cu: "L’un des oiseaux les plus communs de Tokyo.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en mai.",
    bt: "mai–août",
    fa: ["Face blanche.", "Bec orange.", "Commun en ville."]
  },
  "crested-myna": {
    name: "Martin huppé",
    s: "Martin entièrement noir à touffe frontale et taches alaires blanches. Sur la liste mongole, sans mention GBIF.",
    d: "Le Martin huppé vit dans le sud de la Chine et à Taïwan. Toute mention en Mongolie serait exceptionnelle.",
    f: ["Noir avec une touffe au-dessus du bec.", "Taches alaires blanches en vol.", "Bec ivoire ; œil pâle."],
    si: "Inconfondable.",
    h: "Villes et cultures.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes et fruits.",
    br: "Niche dans des cavités (pas en Mongolie).",
    be: "Marche sur les pelouses.",
    v: "Sifflements variés ; imite.",
    cu: "Élevé comme oiseau parleur.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Touffe frontale.", "Imite la parole.", "Espèce du sud de la Chine."]
  },
  "eurasian-golden-oriole": {
    name: "Loriot d’Europe",
    s: "Oiseau jaune d’or éclatant aux ailes noires et au chant flûté. Migrateur peu commun dans l’ouest de la Mongolie et les oasis du Gobi.",
    d: "Le Loriot d’Europe niche de l’Europe à la Sibérie occidentale et hiverne en Afrique. Il reste caché dans la canopée. En Mongolie, c’est un visiteur peu commun à Yolyn Am et au lac Khar Us.",
    f: ["Mâle : jaune d’or, ailes et queue noires.", "Bec rouge rosé.", "Femelle : verdâtre à poitrine striée."],
    si: "Loriot de Chine — bande noire de l’œil à la nuque.",
    h: "Grands arbres feuillus.",
    di: "Yolyn Am, lac Khar Us, Khurkh.",
    mi: "Migrateur rare, mai–août.",
    fo: "Insectes et fruits.",
    br: "Nid en hamac dans une fourche (non confirmé en Mongolie).",
    be: "Se cache dans la canopée.",
    v: "Un « ouila-ouiou » flûté.",
    cu: "Oiseau de l’été dans le folklore européen.",
    co: "Préoccupation mineure.",
    w: "Oasis de Yolyn Am en mai.",
    bt: "mai",
    fa: ["Plumage doré.", "Chant flûté.", "Se cache dans les cimes."]
  },
  "black-naped-oriole": {
    name: "Loriot de Chine",
    s: "Loriot doré à large bande noire de l’œil à la nuque. Visiteur peu commun des bois du nord et des oasis du Gobi.",
    d: "Le Loriot de Chine niche de la Sibérie orientale à l’Asie du Sud-Est. En Mongolie, il a été noté à Terelj, Oulan-Bator, Yolyn Am et dans le Dornod.",
    f: ["Corps jaune vif.", "Bande noire de l’œil à la nuque.", "Ailes et queue noires.", "Bec rose."],
    si: "Loriot d’Europe — sans bande noire sur la nuque.",
    h: "Bois feuillus et parcs.",
    di: "Terelj, Oulan-Bator, Yolyn Am, Mongol Daguur.",
    mi: "Visiteur d’été et migrateur peu commun, mai–août.",
    fo: "Insectes et fruits.",
    br: "Nid en hamac dans les arbres.",
    be: "Chante dans la canopée.",
    v: "Un sifflement fort et liquide.",
    cu: "Son chant annonce l’été en Chine.",
    co: "Préoccupation mineure.",
    w: "Terelj en juin.",
    bt: "juin",
    fa: ["Bande noire sur la nuque.", "Jaune vif.", "Nid en hamac."]
  },
  "black-drongo": {
    name: "Drongo royal",
    s: "Oiseau noir brillant à longue queue profondément fourchue, qui chasse les insectes en vol. Migrateur peu commun, surtout à Yolyn Am.",
    d: "Le Drongo royal niche de l’Inde au nord-est de la Chine. Intrépide, il chasse corbeaux et rapaces. En Mongolie, il apparaît au printemps à Yolyn Am et dans l’est.",
    f: ["Entièrement noir brillant.", "Longue queue profondément fourchue.", "Petite tache blanche à la base du bec.", "Port dressé sur les fils."],
    si: "Inconfondable.",
    h: "Milieux ouverts arborés.",
    di: "Yolyn Am, Taatsiin Tsagaan, est de la Mongolie.",
    mi: "Migrateur peu commun, mai–juin.",
    fo: "Insectes volants.",
    br: "Niche dans les arbres (pas en Mongolie).",
    be: "Chasse des oiseaux bien plus grands.",
    v: "Cris rauques ; imite les rapaces.",
    cu: "Appelé « roi des corbeaux » en Inde pour son audace.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai",
    fa: ["Queue fourchue.", "Très audacieux.", "Imite les rapaces."]
  },
  "bohemian-waxwing": {
    name: "Jaseur boréal",
    s: "Oiseau dodu et huppé brun rosé, aux pointes d’ailes rouges « de cire » et au bout de queue jaune. Les groupes d’hiver visitent les arbres à baies d’Oulan-Bator.",
    d: "Le Jaseur boréal niche dans la taïga nordique et erre vers le sud en hiver à la recherche de baies. En Mongolie, des groupes apparaissent à Oulan-Bator, Terelj et dans les oasis du Gobi d’octobre à avril.",
    f: ["Huppe marquée.", "Masque et gorge noirs.", "Extrémités rouges comme de la cire sur les secondaires.", "Queue terminée de jaune.", "Cri trillé."],
    si: "Jaseur du Japon — bout de queue rouge, sans jaune sur l’aile.",
    h: "Arbres à baies en ville et en forêt.",
    di: "Oulan-Bator, Terelj, Yolyn Am, Khurkh.",
    mi: "Visiteur d’hiver, octobre–avril.",
    fo: "Baies ; insectes en été.",
    br: "Niche dans la taïga (pas en Mongolie).",
    be: "Voyage en groupes serrés et trillants.",
    v: "Un trille aigu comme une clochette.",
    cu: "Ses invasions passaient autrefois pour annoncer la peste.",
    co: "Préoccupation mineure.",
    w: "Sorbiers d’Oulan-Bator en hiver.",
    bt: "nov.–mars",
    fa: ["Pointes d’ailes cireuses rouges.", "Huppé.", "Mangeur de baies."]
  },
  "japanese-waxwing": {
    name: "Jaseur du Japon",
    s: "Jaseur huppé à bout de queue rouge et huppe bordée de noir. Visiteur d’hiver rare ; Quasi menacé.",
    d: "Le Jaseur du Japon niche dans l’Extrême-Orient russe et hiverne au Japon, en Corée et en Chine. Il a été noté quelques fois à Oulan-Bator en hiver.",
    f: ["Huppe bordée de noir.", "Bout de la queue rouge.", "Corps gris-brun.", "Panneau alaire rouge, sans pointes cireuses."],
    si: "Jaseur boréal — bout de queue jaune.",
    h: "Arbres à baies.",
    di: "Rare ; Oulan-Bator, Dornod.",
    mi: "Visiteur d’hiver rare.",
    fo: "Baies.",
    br: "Niche en Extrême-Orient (pas en Mongolie).",
    be: "Se mêle aux Jaseurs boréaux.",
    v: "Un fin trille.",
    cu: "L’une des trois seules espèces de jaseurs.",
    co: "Quasi menacé.",
    w: "Vérifiez les groupes de jaseurs à Oulan-Bator.",
    bt: "hiver",
    fa: ["Bout de queue rouge.", "Quasi menacé.", "Rare en Mongolie."]
  },
  "flavescent-bulbul": {
    name: "Bulbul flavescent",
    s: "Bulbul jaune olive des collines d’Asie du Sud-Est. Sur la liste mongole, sans mention GBIF.",
    d: "Le Bulbul flavescent vit dans les collines du nord-est de l’Inde et d’Asie du Sud-Est. Une mention en Mongolie serait exceptionnelle.",
    f: ["Dessus brun olive.", "Dessous jaunâtre.", "Trait blanc devant l’œil.", "Courte huppe."],
    si: "Inconfondable en Mongolie.",
    h: "Broussailles des collines.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Fruits et insectes.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Vit en petits groupes.",
    v: "Sifflements joyeux.",
    cu: "Les bulbuls sont des oiseaux de jardin communs en Asie tropicale.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Espèce tropicale.", "Ventre jaunâtre.", "Exceptionnel en Mongolie."]
  }
});
