B2T("en", {
  "whites-thrush": {
    T: { c: { brown: 0.4, buff: 0.3, black: 0.15, white: 0.15 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["summer", "passage"], sz: ["27–31 cm", "—", "100–170 g"] },
    s: "A large thrush covered in golden-brown and black crescent ‘scales’. A shy summer visitor to northern forests and migrant through Gobi oases.",
    d: "White’s Thrush breeds in the taiga of Siberia and north-east Asia and winters in southern China and South-East Asia. It forages quietly on the forest floor. In Mongolia it breeds in the Khentii forests (Khurkh, Terelj, Ulaanbaatar) and is regularly seen on migration at Yolyn Am.",
    f: ["Golden-brown upperparts with black crescents.", "White underparts heavily scaled with black.", "Bold black-and-white underwing bands in flight.", "Large and round."],
    si: "Other thrushes — no scaly pattern.",
    h: "Damp forest floor.",
    di: "Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Khar Us Nuur, Ganga Nuur.",
    mi: "Summer visitor and migrant, May–September.",
    fo: "Worms and insects.",
    br: "Nests in trees; 4–5 eggs.",
    be: "Shuffles on the forest floor, rocking its body.",
    v: "A slow, mournful single whistle at night.",
    cu: "In Japan its eerie night whistle was linked to ghosts.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May–June",
    fa: ["Scaly pattern.", "Whistles at night.", "Striped underwing."],
    alt: []
  },
  "siberian-thrush": {
    T: { c: { black: 0.6, white: 0.3, gray: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["20–23 cm", "—", "60–75 g"] },
    s: "A dark slate thrush with a bold white eyebrow (male); brown and scaly female. A scarce migrant in eastern Mongolia.",
    d: "The Siberian Thrush breeds in the taiga of Siberia and winters in South-East Asia. In Mongolia it is seen on passage in the east, the Khentii and Gobi oases.",
    f: ["Male: slate-black with a white eyebrow.", "White bands under the wing.", "Female: brown with a buff eyebrow and scaly breast."],
    si: "Eurasian Blackbird — no eyebrow.",
    h: "Dense forest.",
    di: "Khurkh, Ulaanbaatar, Yolyn Am, Buir Nuur, Ikh Nart.",
    mi: "Passage migrant, May and September.",
    fo: "Insects and berries.",
    br: "Breeds in taiga (not confirmed in Mongolia).",
    be: "Secretive.",
    v: "A fluty song.",
    cu: "Striking white-browed male.",
    co: "Least Concern.",
    w: "Gobi oases in May.",
    bt: "May",
    fa: ["White eyebrow.", "Secretive.", "Taiga thrush."]
  },
  "mistle-thrush": {
    T: { c: { brown: 0.4, white: 0.35, black: 0.15, gray: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["27–28 cm", "42–48 cm", "100–150 g"] },
    s: "A large, pale thrush with bold round spots on the breast. A summer visitor to mountain forests in the west.",
    d: "The Mistle Thrush lives from Europe to Central Asia. In Mongolia it breeds in the Altai and Khangai mountain forests and Khövsgöl, and is seen around Ulaanbaatar.",
    f: ["Pale grey-brown back.", "Large round black spots on white underparts.", "White underwing.", "Upright stance."],
    si: "Song Thrush — smaller, warmer brown, smaller spots.",
    h: "Mountain forests and edges.",
    di: "Ulaanbaatar, Khar Us Nuur, Khövsgöl, Tavan Bogd, Uvs, Orkhon.",
    mi: "Summer visitor; some resident.",
    fo: "Worms, insects and berries.",
    br: "Nests in trees.",
    be: "Defends berry trees.",
    v: "A loud, mournful song, even in storms.",
    cu: "Called ‘storm cock’ for singing in bad weather.",
    co: "Least Concern.",
    w: "Altai forest edges.",
    bt: "May–July",
    fa: ["Sings in storms.", "Round spots.", "Guards berry trees."]
  },
  "song-thrush": {
    T: { c: { brown: 0.45, buff: 0.25, white: 0.2, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["20–23 cm", "33–36 cm", "65–100 g"] },
    s: "A warm brown thrush with neat arrow-shaped breast spots and a repetitive song. Rare in western Mongolia.",
    d: "The Song Thrush breeds from Europe to Siberia. In Mongolia it is found in western forests (Khar Us Nuur area) and the Khangai.",
    f: ["Warm brown back.", "Buff breast with dark arrowhead spots.", "Orange underwing.", "Smaller than Mistle Thrush."],
    si: "Mistle Thrush — larger, paler, round spots.",
    h: "Forests and parks.",
    di: "Khar Us Nuur, Orkhon, Ulaanbaatar, Khövsgöl, Uvs.",
    mi: "Summer visitor.",
    fo: "Worms and snails.",
    br: "Mud-lined nest in shrubs.",
    be: "Smashes snails on stones.",
    v: "Phrases repeated two or three times.",
    cu: "Its snail ‘anvils’ are famous.",
    co: "Least Concern.",
    w: "Western forests in June.",
    bt: "June",
    fa: ["Repeats its phrases.", "Smashes snails.", "Mud-lined nest."]
  },
  "redwing": {
    T: { c: { brown: 0.45, white: 0.3, rufous: 0.15, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk", "perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["20–24 cm", "33–35 cm", "50–75 g"] },
    s: "A small thrush with a bold creamy eyebrow and red flanks. A scarce migrant.",
    d: "The Redwing breeds across the northern taiga and winters in Europe and western Asia. In Mongolia it is scarce, recorded around Ulaanbaatar, Khar Us Nuur and Khövsgöl.",
    f: ["Bold cream eyebrow.", "Rusty-red flanks and underwing.", "Streaked breast."],
    si: "Naumann’s Thrush — rufous tail. Dusky Thrush — dark breast bands.",
    h: "Forests and berry bushes.",
    di: "Ulaanbaatar, Khar Us Nuur, Khövsgöl.",
    mi: "Passage migrant, spring and autumn.",
    fo: "Berries and insects.",
    br: "Nests in northern taiga.",
    be: "Flocks with other thrushes.",
    v: "A thin ‘seeip’ at night.",
    cu: "Its night calls mark autumn migration in Europe.",
    co: "Least Concern.",
    w: "Ulaanbaatar berry trees.",
    bt: "October",
    fa: ["Red flanks.", "Cream eyebrow.", "Night migrant."]
  },
  "eurasian-blackbird": {
    T: { c: { black: 0.8, brown: 0.1, yellow: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["23–29 cm", "34–38 cm", "80–110 g"] },
    s: "An all-black thrush with an orange-yellow bill (male). Local in the far west of Mongolia.",
    d: "The Common Blackbird lives from Europe to Central Asia. In Mongolia it is found locally in riverside woods in the west, especially around Khar Us Nuur.",
    f: ["Male: all black with an orange bill and eye-ring.", "Female: dark brown.", "Long tail."],
    si: "Siberian Thrush — white eyebrow.",
    h: "Woods and gardens.",
    di: "Khar Us Nuur, Khovd river woods.",
    mi: "Resident.",
    fo: "Worms, insects and berries.",
    br: "Nests in shrubs.",
    be: "Hops on the ground.",
    v: "A rich, fluty song.",
    cu: "Famous from the Beatles song ‘Blackbird’.",
    co: "Least Concern.",
    w: "Khar Us Nuur woods.",
    bt: "all year",
    fa: ["Orange bill.", "Fluty song.", "Local in Mongolia."]
  },
  "eyebrowed-thrush": {
    T: { c: { gray: 0.35, rufous: 0.3, brown: 0.2, white: 0.15 }, hb: ["forest"], bk: "short", bh: ["walk", "perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["21–23 cm", "—", "60–100 g"] },
    s: "A thrush with a grey head, white eyebrow and orange flanks. A common migrant, especially in Gobi oases and the north.",
    d: "The Eyebrowed Thrush breeds in the Siberian taiga and winters in South-East Asia. In Mongolia it passes through in May and September at Yolyn Am, Ulaanbaatar, the Khurkh valley and Terelj.",
    f: ["Grey head with a white eyebrow.", "Orange breast and flanks.", "White belly.", "Olive-brown back."],
    si: "Naumann’s Thrush — rufous tail, no grey head.",
    h: "Forests and oases.",
    di: "Yolyn Am, Ulaanbaatar, Khurkh, Terelj, Buir Nuur.",
    mi: "Passage migrant, May and September.",
    fo: "Insects and berries.",
    br: "Nests in taiga.",
    be: "Flocks on migration.",
    v: "A thin ‘tsip’.",
    cu: "One of the most numerous thrushes on the East Asian flyway.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May, September",
    fa: ["White eyebrow.", "Orange flanks.", "Common migrant."]
  },
  "pale-thrush": {
    T: { c: { brown: 0.5, gray: 0.3, white: 0.2 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["22–24 cm", "—", "70–90 g"] },
    s: "A plain brown thrush with white tail corners. On the Mongolian list, with no GBIF records.",
    d: "The Pale Thrush breeds in the Russian Far East and Korea and winters in southern Japan and China. Records in Mongolia are exceptional.",
    f: ["Plain brown upperparts.", "Grey head (male).", "White tips to outer tail feathers."],
    si: "Eyebrowed Thrush — white eyebrow.",
    h: "Forests.",
    di: "Exceptional vagrant.",
    mi: "Vagrant.",
    fo: "Insects and berries.",
    br: "Nests in the Far East.",
    be: "Shy.",
    v: "A thin ‘tsuu’.",
    cu: "Common winter bird in Japanese parks.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["White tail corners.", "Plain brown.", "East Asian species."]
  },
  "fieldfare": {
    T: { c: { gray: 0.35, brown: 0.3, rufous: 0.15, black: 0.1, white: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["winter", "passage"], sz: ["22–27 cm", "39–42 cm", "80–130 g"] },
    s: "A large thrush with a grey head and rump and chestnut back. A scarce winter visitor to berry trees in Ulaanbaatar.",
    d: "The Fieldfare breeds across the northern taiga and winters in flocks in Europe. In Mongolia it is seen mainly in winter around Ulaanbaatar and Terelj.",
    f: ["Grey head and rump.", "Chestnut back.", "Spotted orange breast.", "Black tail."],
    si: "Mistle Thrush — no grey head.",
    h: "Forests and berry trees.",
    di: "Ulaanbaatar, Terelj, Khar Us Nuur, Yolyn Am.",
    mi: "Winter visitor and migrant.",
    fo: "Berries and worms.",
    br: "Colonial in the taiga.",
    be: "Defends nests by bombing predators with droppings.",
    v: "A harsh ‘chak-chak’.",
    cu: "Its name means ‘field traveller’.",
    co: "Least Concern.",
    w: "Berry trees in Ulaanbaatar in winter.",
    bt: "winter",
    fa: ["Grey head.", "Bombs predators with droppings.", "Winter flocks."]
  },
  "naumanns-thrush": {
    T: { c: { rufous: 0.45, brown: 0.3, white: 0.15, gray: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["passage", "winter"], sz: ["23–25 cm", "—", "60–80 g"] },
    s: "A thrush with rufous-spotted underparts and a rufous tail. A common migrant and occasional winter visitor.",
    d: "Naumann’s Thrush breeds in central Siberia and winters in China. In Mongolia it is common on migration around Ulaanbaatar, the Khurkh valley and Yolyn Am.",
    f: ["Rufous breast and flanks with spots.", "Rufous tail.", "Pale eyebrow.", "Grey-brown back."],
    si: "Dusky Thrush — black-spotted breast bands, rufous wings.",
    h: "Forest edges and berry trees.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Terelj, Ögii Nuur.",
    mi: "Passage migrant; some winter.",
    fo: "Berries and insects.",
    br: "Nests in Siberia.",
    be: "Hybridises with Dusky Thrush.",
    v: "A harsh ‘chack’.",
    cu: "Named after the German ornithologist Naumann.",
    co: "Least Concern.",
    w: "Ulaanbaatar in October.",
    bt: "April, October",
    fa: ["Rufous tail.", "Hybridises with Dusky Thrush.", "Named after Naumann."]
  },
  "dusky-thrush": {
    T: { c: { black: 0.3, brown: 0.3, rufous: 0.2, white: 0.2 }, hb: ["forest", "settlement"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["passage", "winter"], sz: ["21–25 cm", "—", "60–90 g"] },
    s: "A thrush with rufous wings, a bold white eyebrow and black-spotted breast bands. A common migrant.",
    d: "The Dusky Thrush breeds in Siberia and winters in eastern Asia. In Mongolia it passes through Ulaanbaatar, the Khurkh valley, Yolyn Am and Terelj.",
    f: ["Bold white eyebrow and throat.", "Two black spotted breast bands.", "Rufous wing panel.", "Dark scaly back."],
    si: "Naumann’s Thrush — rufous breast, rufous tail.",
    h: "Forests, parks and berry trees.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Terelj, Ögii Nuur.",
    mi: "Passage migrant, April–May and September–October.",
    fo: "Berries and insects.",
    br: "Nests in Siberia.",
    be: "Upright stance on lawns.",
    v: "A harsh ‘chack-chack’.",
    cu: "Common winter thrush in Japan.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in October.",
    bt: "April, October",
    fa: ["Rufous wings.", "White eyebrow.", "Common migrant."]
  },
  "black-throated-thrush": {
    T: { c: { gray: 0.45, black: 0.25, white: 0.2, brown: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["summer", "passage"], sz: ["23–27 cm", "—", "70–100 g"] },
    s: "A grey thrush with a black throat and breast (male). Breeds in western mountain forests and passes through Ulaanbaatar.",
    d: "The Black-throated Thrush breeds from the Urals to western Mongolia and winters in the Himalaya. In Mongolia it breeds in the Altai (Khar Us Nuur area) and passes through Ulaanbaatar and Yolyn Am.",
    f: ["Grey back.", "Black throat and breast (male).", "White belly.", "Rufous underwing."],
    si: "Red-throated Thrush — red throat and tail.",
    h: "Mountain forest edges.",
    di: "Khar Us Nuur, Ulaanbaatar, Yolyn Am, Khurkh, Terelj, Ölgii.",
    mi: "Summer visitor and migrant.",
    fo: "Insects and berries.",
    br: "Nests in trees; 4–6 eggs.",
    be: "Feeds on open ground.",
    v: "A harsh ‘chack’.",
    cu: "Once lumped with Red-throated Thrush as ‘Dark-throated Thrush’.",
    co: "Least Concern.",
    w: "Altai forest edges in June.",
    bt: "May–September",
    fa: ["Black throat.", "Grey back.", "Western Mongolia."]
  },
  "red-throated-thrush": {
    T: { c: { gray: 0.45, rufous: 0.3, white: 0.2, brown: 0.05 }, hb: ["forest", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["croak"], ac: "day", se: ["summer", "passage"], sz: ["23–27 cm", "—", "70–100 g"] },
    s: "A grey thrush with a rusty-red throat, breast and tail sides. A common summer visitor to northern and central mountain forests.",
    d: "The Red-throated Thrush breeds in southern Siberia and Mongolia and winters in the Himalaya and China. In Mongolia it breeds in the Khentii, Khangai and Khövsgöl and is common around Ulaanbaatar, Terelj and Yolyn Am.",
    f: ["Grey back.", "Rusty-red throat, breast and eyebrow.", "Rufous outer tail feathers.", "White belly."],
    si: "Black-throated Thrush — black throat, grey tail.",
    h: "Mountain forest edges.",
    di: "Ulaanbaatar, Terelj, Yolyn Am, Khurkh, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Summer visitor and migrant, April–October.",
    fo: "Insects and berries.",
    br: "Nests in trees; 4–6 eggs.",
    be: "Hops on open ground.",
    v: "A harsh ‘chack’.",
    cu: "One of the most common thrushes of Mongolia.",
    co: "Least Concern.",
    w: "Terelj in May.",
    bt: "May–September",
    fa: ["Red throat.", "Rufous tail.", "Common in Mongolia."]
  }
});
