B2T("fr", {
  "whites-thrush": {
    name: "Grive dorée",
    s: "Grande grive couverte d’« écailles » brun doré et noires. Visiteuse d’été discrète des forêts du nord et migratrice dans les oasis du Gobi.",
    d: "La Grive dorée niche dans la taïga de Sibérie et d’Asie du Nord-Est et hiverne dans le sud de la Chine et en Asie du Sud-Est. Elle se nourrit discrètement au sol. En Mongolie, elle niche dans les forêts du Khentii (Khurkh, Terelj, Oulan-Bator) et passe régulièrement à Yolyn Am.",
    f: ["Dessus brun doré à croissants noirs.", "Dessous blanc fortement écaillé de noir.", "Bandes noires et blanches sous l’aile en vol.", "Grande et ronde."],
    si: "Autres grives — sans motif écailleux.",
    h: "Sol forestier humide.",
    di: "Oulan-Bator, Khurkh, Terelj, Yolyn Am, lac Khar Us, lac Ganga.",
    mi: "Visiteuse d’été et migratrice, mai–septembre.",
    fo: "Vers et insectes.",
    br: "Niche dans les arbres ; 4 ou 5 œufs.",
    be: "Se déplace au sol en balançant le corps.",
    v: "Un sifflement lent et plaintif la nuit.",
    cu: "Au Japon, son sifflement nocturne était associé aux fantômes.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai–juin",
    fa: ["Motif écailleux.", "Siffle la nuit.", "Dessous d’aile rayé."]
  },
  "siberian-thrush": {
    name: "Grive de Sibérie",
    s: "Grive ardoise sombre à sourcil blanc marqué (mâle) ; femelle brune et écailleuse. Migratrice peu commune dans l’est.",
    d: "La Grive de Sibérie niche dans la taïga sibérienne et hiverne en Asie du Sud-Est. En Mongolie, elle passe dans l’est, le Khentii et les oasis du Gobi.",
    f: ["Mâle : noir ardoise à sourcil blanc.", "Bandes blanches sous l’aile.", "Femelle : brune, sourcil chamois, poitrine écailleuse."],
    si: "Merle noir — sans sourcil.",
    h: "Forêt dense.",
    di: "Khurkh, Oulan-Bator, Yolyn Am, lac Buir, Ikh Nart.",
    mi: "Migratrice, mai et septembre.",
    fo: "Insectes et baies.",
    br: "Niche dans la taïga (non confirmé en Mongolie).",
    be: "Discrète.",
    v: "Un chant flûté.",
    cu: "Le mâle à sourcil blanc est spectaculaire.",
    co: "Préoccupation mineure.",
    w: "Oasis du Gobi en mai.",
    bt: "mai",
    fa: ["Sourcil blanc.", "Discrète.", "Grive de la taïga."]
  },
  "mistle-thrush": {
    name: "Grive draine",
    s: "Grande grive pâle à gros points ronds sur la poitrine. Visiteuse d’été des forêts de montagne de l’ouest.",
    d: "La Grive draine vit de l’Europe à l’Asie centrale. En Mongolie, elle niche dans les forêts de montagne de l’Altaï, du Khangaï et du Khövsgöl et se voit autour d’Oulan-Bator.",
    f: ["Dos gris-brun pâle.", "Gros points noirs ronds sur dessous blanc.", "Dessous d’aile blanc.", "Port dressé."],
    si: "Grive musicienne — plus petite, brun plus chaud, points plus petits.",
    h: "Forêts de montagne et lisières.",
    di: "Oulan-Bator, lac Khar Us, Khövsgöl, Tavan Bogd, Uvs, Orkhon.",
    mi: "Visiteuse d’été ; quelques résidentes.",
    fo: "Vers, insectes et baies.",
    br: "Niche dans les arbres.",
    be: "Défend les arbres à baies.",
    v: "Un chant fort et mélancolique, même sous l’orage.",
    cu: "Surnommée « coq des tempêtes » en anglais.",
    co: "Préoccupation mineure.",
    w: "Lisières de l’Altaï.",
    bt: "mai–juil.",
    fa: ["Chante sous l’orage.", "Points ronds.", "Défend les baies."]
  },
  "song-thrush": {
    name: "Grive musicienne",
    s: "Grive brun chaud aux petites taches en pointe de flèche et au chant répétitif. Rare dans l’ouest de la Mongolie.",
    d: "La Grive musicienne niche de l’Europe à la Sibérie. En Mongolie, on la trouve dans les forêts de l’ouest (région du lac Khar Us) et du Khangaï.",
    f: ["Dos brun chaud.", "Poitrine chamois à taches en flèche.", "Dessous d’aile orangé.", "Plus petite que la draine."],
    si: "Grive draine — plus grande, plus pâle, taches rondes.",
    h: "Forêts et parcs.",
    di: "Lac Khar Us, Orkhon, Oulan-Bator, Khövsgöl, Uvs.",
    mi: "Visiteuse d’été.",
    fo: "Vers et escargots.",
    br: "Nid garni de boue dans les buissons.",
    be: "Casse les escargots sur des pierres.",
    v: "Phrases répétées deux ou trois fois.",
    cu: "Ses « enclumes » à escargots sont célèbres.",
    co: "Préoccupation mineure.",
    w: "Forêts de l’ouest en juin.",
    bt: "juin",
    fa: ["Répète ses phrases.", "Casse les escargots.", "Nid garni de boue."]
  },
  "redwing": {
    name: "Grive mauvis",
    s: "Petite grive au sourcil crème marqué et aux flancs rouges. Migratrice peu commune.",
    d: "La Grive mauvis niche dans la taïga nordique et hiverne en Europe et en Asie occidentale. En Mongolie, elle est peu commune, notée à Oulan-Bator, au lac Khar Us et au Khövsgöl.",
    f: ["Sourcil crème marqué.", "Flancs et dessous d’aile rouge rouille.", "Poitrine striée."],
    si: "Grive de Naumann — queue rousse. Grive à ailes rousses — bandes pectorales sombres.",
    h: "Forêts et buissons à baies.",
    di: "Oulan-Bator, lac Khar Us, Khövsgöl.",
    mi: "Migratrice au printemps et en automne.",
    fo: "Baies et insectes.",
    br: "Niche dans la taïga nordique.",
    be: "En groupes avec d’autres grives.",
    v: "Un fin « siiip » la nuit.",
    cu: "Ses cris nocturnes marquent la migration d’automne en Europe.",
    co: "Préoccupation mineure.",
    w: "Arbres à baies d’Oulan-Bator.",
    bt: "octobre",
    fa: ["Flancs rouges.", "Sourcil crème.", "Migre la nuit."]
  },
  "eurasian-blackbird": {
    name: "Merle noir",
    s: "Grive entièrement noire au bec jaune orangé (mâle). Localisée dans l’extrême ouest de la Mongolie.",
    d: "Le Merle noir vit de l’Europe à l’Asie centrale. En Mongolie, il est local dans les bois riverains de l’ouest, surtout autour du lac Khar Us.",
    f: ["Mâle : entièrement noir, bec et cercle orbital orange.", "Femelle : brun sombre.", "Longue queue."],
    si: "Grive de Sibérie — sourcil blanc.",
    h: "Bois et jardins.",
    di: "Lac Khar Us, bois du Khovd.",
    mi: "Résident.",
    fo: "Vers, insectes et baies.",
    br: "Niche dans les buissons.",
    be: "Sautille au sol.",
    v: "Un chant riche et flûté.",
    cu: "Célèbre grâce à la chanson « Blackbird » des Beatles.",
    co: "Préoccupation mineure.",
    w: "Bois du lac Khar Us.",
    bt: "toute l’année",
    fa: ["Bec orange.", "Chant flûté.", "Local en Mongolie."]
  },
  "eyebrowed-thrush": {
    name: "Merle obscur",
    s: "Grive à tête grise, sourcil blanc et flancs orange. Migratrice commune, surtout dans les oasis du Gobi et le nord.",
    d: "Le Merle obscur niche dans la taïga sibérienne et hiverne en Asie du Sud-Est. En Mongolie, il passe en mai et septembre à Yolyn Am, Oulan-Bator, dans la vallée de Khurkh et à Terelj.",
    f: ["Tête grise à sourcil blanc.", "Poitrine et flancs orange.", "Ventre blanc.", "Dos brun olive."],
    si: "Grive de Naumann — queue rousse, sans tête grise.",
    h: "Forêts et oasis.",
    di: "Yolyn Am, Oulan-Bator, Khurkh, Terelj, lac Buir.",
    mi: "Migrateur, mai et septembre.",
    fo: "Insectes et baies.",
    br: "Niche dans la taïga.",
    be: "En groupes en migration.",
    v: "Un fin « tsip ».",
    cu: "L’une des grives les plus nombreuses de la voie est-asiatique.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai, sept.",
    fa: ["Sourcil blanc.", "Flancs orange.", "Migrateur commun."]
  },
  "pale-thrush": {
    name: "Merle pâle",
    s: "Grive brune unie aux coins de queue blancs. Sur la liste mongole, sans mention GBIF.",
    d: "Le Merle pâle niche dans l’Extrême-Orient russe et en Corée et hiverne dans le sud du Japon et en Chine. Les mentions mongoles sont exceptionnelles.",
    f: ["Dessus brun uni.", "Tête grise (mâle).", "Extrémités blanches aux rectrices externes."],
    si: "Merle obscur — sourcil blanc.",
    h: "Forêts.",
    di: "Erratique exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes et baies.",
    br: "Niche en Extrême-Orient.",
    be: "Farouche.",
    v: "Un fin « tsouu ».",
    cu: "Oiseau d’hiver commun dans les parcs japonais.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Coins de queue blancs.", "Brun uni.", "Espèce est-asiatique."]
  },
  "fieldfare": {
    name: "Grive litorne",
    s: "Grande grive à tête et croupion gris et dos marron. Visiteuse d’hiver peu commune des arbres à baies d’Oulan-Bator.",
    d: "La Grive litorne niche dans la taïga nordique et hiverne en groupes en Europe. En Mongolie, on la voit surtout en hiver autour d’Oulan-Bator et de Terelj.",
    f: ["Tête et croupion gris.", "Dos marron.", "Poitrine orangée tachetée.", "Queue noire."],
    si: "Grive draine — sans tête grise.",
    h: "Forêts et arbres à baies.",
    di: "Oulan-Bator, Terelj, lac Khar Us, Yolyn Am.",
    mi: "Hivernante et migratrice.",
    fo: "Baies et vers.",
    br: "Coloniale dans la taïga.",
    be: "Défend ses nids en bombardant les prédateurs de fientes.",
    v: "Un « tchak-tchak » rauque.",
    cu: "Son nom anglais signifie « voyageuse des champs ».",
    co: "Préoccupation mineure.",
    w: "Arbres à baies d’Oulan-Bator en hiver.",
    bt: "hiver",
    fa: ["Tête grise.", "Bombarde les prédateurs.", "Groupes hivernaux."]
  },
  "naumanns-thrush": {
    name: "Grive de Naumann",
    s: "Grive au dessous taché de roux et à queue rousse. Migratrice commune et hivernante occasionnelle.",
    d: "La Grive de Naumann niche en Sibérie centrale et hiverne en Chine. En Mongolie, elle est commune en migration autour d’Oulan-Bator, de la vallée de Khurkh et de Yolyn Am.",
    f: ["Poitrine et flancs tachés de roux.", "Queue rousse.", "Sourcil pâle.", "Dos gris-brun."],
    si: "Grive à ailes rousses — bandes pectorales tachées de noir, ailes rousses.",
    h: "Lisières et arbres à baies.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Terelj, lac Ögii.",
    mi: "Migratrice ; quelques hivernantes.",
    fo: "Baies et insectes.",
    br: "Niche en Sibérie.",
    be: "S’hybride avec la Grive à ailes rousses.",
    v: "Un « tchack » rauque.",
    cu: "Nommée d’après l’ornithologue allemand Naumann.",
    co: "Préoccupation mineure.",
    w: "Oulan-Bator en octobre.",
    bt: "avril, oct.",
    fa: ["Queue rousse.", "S’hybride avec la Grive à ailes rousses.", "Nommée d’après Naumann."]
  },
  "dusky-thrush": {
    name: "Grive à ailes rousses",
    s: "Grive aux ailes rousses, au sourcil blanc marqué et aux bandes pectorales tachées de noir. Migratrice commune.",
    d: "La Grive à ailes rousses niche en Sibérie et hiverne en Asie orientale. En Mongolie, elle passe par Oulan-Bator, la vallée de Khurkh, Yolyn Am et Terelj.",
    f: ["Sourcil et gorge blancs marqués.", "Deux bandes pectorales tachées de noir.", "Panneau alaire roux.", "Dos sombre écailleux."],
    si: "Grive de Naumann — poitrine et queue rousses.",
    h: "Forêts, parcs et arbres à baies.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Terelj, lac Ögii.",
    mi: "Migratrice, avril–mai et septembre–octobre.",
    fo: "Baies et insectes.",
    br: "Niche en Sibérie.",
    be: "Port dressé sur les pelouses.",
    v: "Un « tchack-tchack » rauque.",
    cu: "Grive d’hiver commune au Japon.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en octobre.",
    bt: "avril, oct.",
    fa: ["Ailes rousses.", "Sourcil blanc.", "Migratrice commune."]
  },
  "black-throated-thrush": {
    name: "Grive à gorge noire",
    s: "Grive grise à gorge et poitrine noires (mâle). Niche dans les forêts de montagne de l’ouest et passe par Oulan-Bator.",
    d: "La Grive à gorge noire niche de l’Oural à l’ouest de la Mongolie et hiverne dans l’Himalaya. En Mongolie, elle niche dans l’Altaï (région du lac Khar Us) et passe par Oulan-Bator et Yolyn Am.",
    f: ["Dos gris.", "Gorge et poitrine noires (mâle).", "Ventre blanc.", "Dessous d’aile roux."],
    si: "Grive à gorge rousse — gorge et queue rousses.",
    h: "Lisières des forêts de montagne.",
    di: "Lac Khar Us, Oulan-Bator, Yolyn Am, Khurkh, Terelj, Ölgii.",
    mi: "Visiteuse d’été et migratrice.",
    fo: "Insectes et baies.",
    br: "Niche dans les arbres ; 4 à 6 œufs.",
    be: "Se nourrit en terrain ouvert.",
    v: "Un « tchack » rauque.",
    cu: "Autrefois réunie à la Grive à gorge rousse.",
    co: "Préoccupation mineure.",
    w: "Lisières de l’Altaï en juin.",
    bt: "mai–sept.",
    fa: ["Gorge noire.", "Dos gris.", "Ouest de la Mongolie."]
  },
  "red-throated-thrush": {
    name: "Grive à gorge rousse",
    s: "Grive grise à gorge, poitrine et côtés de la queue roux rouille. Visiteuse d’été commune des forêts de montagne du nord et du centre.",
    d: "La Grive à gorge rousse niche dans le sud de la Sibérie et en Mongolie et hiverne dans l’Himalaya et en Chine. En Mongolie, elle niche dans le Khentii, le Khangaï et le Khövsgöl et est commune autour d’Oulan-Bator, de Terelj et de Yolyn Am.",
    f: ["Dos gris.", "Gorge, poitrine et sourcil roux rouille.", "Rectrices externes rousses.", "Ventre blanc."],
    si: "Grive à gorge noire — gorge noire, queue grise.",
    h: "Lisières des forêts de montagne.",
    di: "Oulan-Bator, Terelj, Yolyn Am, Khurkh, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Visiteuse d’été et migratrice, avril–octobre.",
    fo: "Insectes et baies.",
    br: "Niche dans les arbres ; 4 à 6 œufs.",
    be: "Sautille en terrain ouvert.",
    v: "Un « tchack » rauque.",
    cu: "L’une des grives les plus communes de Mongolie.",
    co: "Préoccupation mineure.",
    w: "Terelj en mai.",
    bt: "mai–sept.",
    fa: ["Gorge rousse.", "Queue rousse.", "Commune en Mongolie."]
  }
});
