B2T("en", {
  "spotted-flycatcher": {
    T: { c: { gray: 0.5, brown: 0.3, white: 0.2 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["silent"], ac: "day", se: ["summer"], sz: ["14–15 cm", "23–25 cm", "14–19 g"] },
    s: "A slim grey-brown flycatcher with a streaked crown and breast that sallies after insects. A summer visitor, mainly in the west.",
    d: "The Spotted Flycatcher breeds from Europe to Central Asia and winters in Africa. In Mongolia it breeds in woods of the west (Khar Us Nuur) and the Khangai, and passes Gobi oases.",
    f: ["Plain grey-brown upperparts.", "Streaked crown and breast.", "Upright posture on a perch.", "Returns to the same perch after catching insects."],
    si: "Grey-streaked Flycatcher — bolder streaks, long wings. Dark-sided Flycatcher — smudged breast.",
    h: "Open woods, parks and gardens.",
    di: "Khar Us Nuur, Ögii Nuur, Orkhon, Khurkh, Orog Nuur, Böön Tsagaan.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Nests on ledges or in tree crevices; 4–5 eggs.",
    be: "Sallies from a perch.",
    v: "A thin ‘tsee’.",
    cu: "One of the latest migrants to arrive in spring.",
    co: "Least Concern.",
    w: "Khar Us Nuur woods in June.",
    bt: "June–August",
    fa: ["Returns to the same perch.", "Streaked crown.", "Winters in Africa."]
  },
  "grey-streaked-flycatcher": {
    T: { c: { gray: 0.5, white: 0.35, brown: 0.15 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["silent"], ac: "day", se: ["passage"], sz: ["13–15 cm", "—", "13–17 g"] },
    s: "A grey flycatcher with crisp dark streaks on white underparts and long wings. A rare migrant in the north and east.",
    d: "The Grey-streaked Flycatcher breeds in the Russian Far East and north-east China and winters in the Philippines and Indonesia. In Mongolia it is rare, recorded in the Khurkh valley and Terelj.",
    f: ["Grey upperparts.", "White underparts with sharp grey streaks.", "Very long wings reaching near the tail tip.", "White eye-ring."],
    si: "Dark-sided Flycatcher — smudgy, not streaked. Spotted Flycatcher — streaked crown.",
    h: "Forest edges.",
    di: "Rare; Khurkh, Terelj, Ulaanbaatar.",
    mi: "Rare migrant.",
    fo: "Flying insects.",
    br: "Nests in the Far East.",
    be: "Perches high on dead twigs.",
    v: "Mostly silent.",
    cu: "One of the longest-winged flycatchers.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Very long wings.", "Crisp streaks.", "Rare in Mongolia."]
  },
  "dark-sided-flycatcher": {
    T: { c: { brown: 0.5, gray: 0.3, white: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["silent"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "—", "10–15 g"] },
    s: "A dark grey-brown flycatcher with smudgy flanks and a pale half-collar. A summer visitor to northern forests.",
    d: "The Dark-sided Flycatcher breeds in the taiga from Siberia to Japan and in the Himalaya, and winters in South-East Asia. In Mongolia it breeds in the Khentii (Terelj, Khurkh, Ulaanbaatar) and Khövsgöl.",
    f: ["Dark grey-brown upperparts.", "Dusky smudges on the breast and flanks.", "White throat and half-collar.", "Long wings."],
    si: "Asian Brown Flycatcher — paler, cleaner underparts.",
    h: "Coniferous and mixed forest.",
    di: "Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Buir Nuur, Khövsgöl.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Nests on branches; 3–4 eggs.",
    be: "Sallies from high perches.",
    v: "A thin trill.",
    cu: "A typical bird of the taiga canopy.",
    co: "Least Concern.",
    w: "Terelj forests in June.",
    bt: "June–August",
    fa: ["Smudgy flanks.", "Taiga bird.", "Long wings."]
  },
  "asian-brown-flycatcher": {
    T: { c: { gray: 0.45, brown: 0.3, white: 0.25 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["silent"], ac: "day", se: ["summer", "passage"], sz: ["12–14 cm", "—", "9–14 g"] },
    s: "A small, plain grey-brown flycatcher with a large eye ring. A common summer visitor and migrant.",
    d: "The Asian Brown Flycatcher breeds from Siberia to Japan and winters in South-East Asia and India. In Mongolia it breeds in the Khentii and is common on passage at Yolyn Am and Khustai.",
    f: ["Plain grey-brown above.", "Whitish below with a faint grey wash.", "Large dark eye with a white ring.", "Pale base to the lower bill."],
    si: "Dark-sided Flycatcher — darker, smudged below.",
    h: "Deciduous woods and parks.",
    di: "Khurkh, Ulaanbaatar, Yolyn Am, Terelj, Khustai, Orog Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Flying insects.",
    br: "Nests in trees; 4–5 eggs.",
    be: "Sallies quietly.",
    v: "A thin ‘tzi’.",
    cu: "Also called the Daurian Flycatcher.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May–September",
    fa: ["Large eye ring.", "Plain.", "Common migrant."]
  },
  "european-robin": {
    T: { c: { rufous: 0.4, brown: 0.35, gray: 0.15, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12.5–14 cm", "20–22 cm", "16–22 g"] },
    s: "The famous robin with an orange face and breast. A rare migrant in Mongolia.",
    d: "The European Robin lives from Europe to western Siberia. In Mongolia it is a rare visitor, recorded near Ulaanbaatar and at Khar Us Nuur.",
    f: ["Orange face and breast edged with grey.", "Olive-brown back.", "Large dark eye."],
    si: "Siberian Rubythroat — red throat only.",
    h: "Woods and gardens.",
    di: "Rare; Ulaanbaatar, Khar Us Nuur, Yolyn Am.",
    mi: "Rare migrant.",
    fo: "Insects and worms.",
    br: "Nests in cavities (not in Mongolia).",
    be: "Follows gardeners for worms.",
    v: "A liquid, melancholy song.",
    cu: "The national bird of the United Kingdom.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Orange breast.", "UK national bird.", "Rare in Mongolia."]
  },
  "rufous-tailed-robin": {
    T: { c: { brown: 0.5, rufous: 0.25, white: 0.25 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["13–14 cm", "—", "13–18 g"] },
    s: "A small, shy robin with a rufous tail and scaly breast. A rare migrant.",
    d: "The Rufous-tailed Robin breeds in the taiga of Siberia and winters in South-East Asia. In Mongolia it is rare, recorded in the east and west.",
    f: ["Olive-brown upperparts.", "Rufous tail, often shivered.", "Whitish breast with grey scales."],
    si: "Siberian Blue Robin (female) — blue rump.",
    h: "Dense forest undergrowth.",
    di: "Rare; eastern and western Mongolia, Ulaanbaatar.",
    mi: "Rare migrant.",
    fo: "Insects.",
    br: "Nests in taiga.",
    be: "Shivers its tail.",
    v: "A trilling song.",
    cu: "Its trilling song rings through the taiga.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Rufous tail.", "Shivers its tail.", "Secretive."]
  },
  "siberian-blue-robin": {
    T: { c: { gray: 0.35, white: 0.35, brown: 0.15, black: 0.15 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "—", "12–18 g"] },
    s: "The male is deep blue above and pure white below; the female is brown with a blue rump. A summer visitor to eastern forests.",
    d: "The Siberian Blue Robin breeds from south Siberia to Japan and winters in South-East Asia. In Mongolia it breeds in dense forests of the Khurkh valley and Dornod.",
    f: ["Male: deep blue upperparts, white underparts.", "Black line from bill to breast sides.", "Female: olive-brown with a blue rump.", "Long pink legs."],
    si: "Red-flanked Bluetail — orange flanks.",
    h: "Dense forest undergrowth.",
    di: "Khurkh, Buir Nuur, Ulaanbaatar, Ganga Nuur, Terelj.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on the ground; 4–6 eggs.",
    be: "Shivers its tail; skulks.",
    v: "A loud trilling song.",
    cu: "A beautiful jewel of eastern forests.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["Blue and white.", "Skulking.", "Eastern forests."]
  },
  "common-nightingale": {
    T: { c: { brown: 0.5, rufous: 0.3, buff: 0.2 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16.5 cm", "23–26 cm", "18–27 g"] },
    s: "A plain brown bird with a rufous tail, famous for its powerful song day and night. Local in far western Mongolia.",
    d: "The Common Nightingale breeds from Europe to Central Asia and winters in Africa. In Mongolia it is found in riverside thickets in the far west.",
    f: ["Plain warm brown.", "Rufous tail.", "Pale underparts.", "Large dark eye."],
    si: "Thrush Nightingale — not in Mongolia.",
    h: "Dense thickets near water.",
    di: "Far western Mongolia (Khar Us Nuur, Khovd river).",
    mi: "Summer visitor.",
    fo: "Insects.",
    br: "Nests low in dense cover.",
    be: "Sings at night.",
    v: "Rich, powerful song with long crescendos.",
    cu: "Celebrated in poetry from Keats to Persian ghazals.",
    co: "Least Concern.",
    w: "Riverside thickets at dusk.",
    bt: "June",
    fa: ["Sings at night.", "Rufous tail.", "Famed in poetry."]
  },
  "red-flanked-bluetail": {
    T: { c: { gray: 0.3, rufous: 0.3, white: 0.25, brown: 0.15 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "21–24 cm", "10–18 g"] },
    s: "A small chat with a blue tail and orange flanks; the male is blue above. Common in northern forests.",
    d: "The Red-flanked Bluetail breeds in the taiga from Finland to Japan and winters in South-East Asia. In Mongolia it breeds in the Khentii (Terelj, Ulaanbaatar, Khurkh) and passes through elsewhere.",
    f: ["Blue tail.", "Orange flanks.", "White throat.", "Male: blue upperparts; female: olive-brown."],
    si: "Siberian Blue Robin — no orange flanks.",
    h: "Coniferous forest.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Khövsgöl, Ganga Nuur.",
    mi: "Summer visitor, April–October.",
    fo: "Insects and berries.",
    br: "Nests in banks or roots.",
    be: "Flicks its tail.",
    v: "A short, sweet song.",
    cu: "Spreading westward into Europe.",
    co: "Least Concern.",
    w: "Terelj forests in May.",
    bt: "May–September",
    fa: ["Blue tail.", "Orange flanks.", "Spreading west."]
  },
  "taiga-flycatcher": {
    T: { c: { gray: 0.35, brown: 0.3, white: 0.2, black: 0.1, rufous: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["croak"], ac: "day", se: ["summer", "passage"], sz: ["11–12 cm", "—", "9–12 g"] },
    s: "A tiny flycatcher that cocks its black-and-white tail; the male has an orange throat in spring. Very common in forests and on migration.",
    d: "The Taiga Flycatcher breeds across the Siberian taiga and winters in South Asia. In Mongolia it breeds in the Khentii and is abundant on passage — Ulaanbaatar, the Khurkh valley, Terelj, Yolyn Am.",
    f: ["White sides to the black tail.", "Male: orange-red throat in spring.", "Grey-brown upperparts.", "Cocks its tail."],
    si: "Mugimaki Flycatcher — orange breast, white eyebrow spot. Asian Brown Flycatcher — no white tail sides.",
    h: "Forests, parks and oases.",
    di: "Ulaanbaatar, Khurkh, Terelj, Yolyn Am, Khustai, Khar Us Nuur.",
    mi: "Summer visitor and migrant, May–September.",
    fo: "Small insects.",
    br: "Nests in tree holes; 5–6 eggs.",
    be: "Cocks and flicks its tail.",
    v: "A dry rattle ‘trrrt’.",
    cu: "One of the most numerous flycatchers in Asia.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in May.",
    bt: "May–September",
    fa: ["Cocks its tail.", "Orange throat in spring.", "Very common."]
  },
  "mugimaki-flycatcher": {
    T: { c: { black: 0.35, rufous: 0.35, white: 0.3 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["13 cm", "—", "10–14 g"] },
    s: "A small flycatcher; the male is black above with an orange breast and a white eyebrow spot. A scarce migrant.",
    d: "The Mugimaki Flycatcher breeds in the Siberian taiga and winters in South-East Asia. In Mongolia it is scarce, recorded in the east, west and Khövsgöl.",
    f: ["Male: black upperparts, orange throat and breast.", "Short white stripe behind the eye.", "White wing patch."],
    si: "Taiga Flycatcher — no orange breast.",
    h: "Forest canopy.",
    di: "Ulaanbaatar, Ganga Nuur, Khurkh, Uvs, Khövsgöl.",
    mi: "Scarce migrant.",
    fo: "Insects.",
    br: "Nests in taiga.",
    be: "Feeds high in trees.",
    v: "A soft trill.",
    cu: "Its name comes from Japanese ‘mugimaki’ (wheat-sower).",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "May",
    fa: ["Orange breast.", "Japanese name.", "Scarce."]
  },
  "narcissus-flycatcher": {
    T: { c: { black: 0.4, yellow: 0.4, white: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["13 cm", "—", "12–14 g"] },
    s: "A brilliant black-and-yellow flycatcher with an orange throat. A very rare vagrant, recorded once.",
    d: "The Narcissus Flycatcher breeds in Japan and Sakhalin and winters in the Philippines and Borneo. A record in central Mongolia in 2026 is exceptional.",
    f: ["Male: black upperparts, yellow eyebrow and rump.", "Orange throat.", "White wing patch."],
    si: "Yellow-rumped Flycatcher — white eyebrow.",
    h: "Forest.",
    di: "Very rare vagrant.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in Japan.",
    be: "Sings from the canopy.",
    v: "A sweet, varied song.",
    cu: "Named after the narcissus flower for its yellow.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Yellow eyebrow.", "Orange throat.", "Very rare."]
  },
  "yellow-rumped-flycatcher": {
    T: { c: { black: 0.4, yellow: 0.35, white: 0.25 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13 cm", "—", "11–15 g"] },
    s: "The male is black above with a bright yellow rump and underparts and a white eyebrow. A summer visitor to eastern forests.",
    d: "The Yellow-rumped Flycatcher breeds in north-east China, Korea and south-east Siberia and winters in South-East Asia. In Mongolia it breeds in the Khurkh valley and Dornod and is seen at Yolyn Am.",
    f: ["Male: black upperparts, yellow underparts and rump.", "White eyebrow.", "White wing patch.", "Female: olive with a yellow rump."],
    si: "Narcissus Flycatcher — yellow eyebrow.",
    h: "Broadleaf forest.",
    di: "Khurkh, Yolyn Am, Buir Nuur, Ganga Nuur, Ulaanbaatar.",
    mi: "Summer visitor, May–August.",
    fo: "Insects.",
    br: "Nests in tree holes.",
    be: "Sings from mid-canopy.",
    v: "A rich, rolling song.",
    cu: "Also called the Tricolored Flycatcher.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["Yellow rump.", "White eyebrow.", "Eastern forests."]
  }
});
