B2T("fr", {
  "spotted-flycatcher": {
    name: "Gobemouche gris",
    s: "Gobemouche élancé gris-brun à calotte et poitrine striées, qui chasse les insectes en vol. Visiteur d’été, surtout dans l’ouest.",
    d: "Le Gobemouche gris niche de l’Europe à l’Asie centrale et hiverne en Afrique. En Mongolie, il niche dans les bois de l’ouest (lac Khar Us) et du Khangaï et passe par les oasis du Gobi.",
    f: ["Dessus gris-brun uni.", "Calotte et poitrine striées.", "Posture dressée sur un perchoir.", "Revient au même perchoir après chaque capture."],
    si: "Gobemouche à taches grises — stries plus nettes, longues ailes. Gobemouche de Sibérie — poitrine estompée.",
    h: "Bois clairs, parcs et jardins.",
    di: "Lac Khar Us, lac Ögii, Orkhon, Khurkh, lac Orog, Böön Tsagaan.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Niche sur une corniche ou une fissure d’arbre ; 4 ou 5 œufs.",
    be: "Chasse depuis un perchoir.",
    v: "Un fin « tsii ».",
    cu: "L’un des derniers migrateurs à arriver au printemps.",
    co: "Préoccupation mineure.",
    w: "Bois du lac Khar Us en juin.",
    bt: "juin–août",
    fa: ["Revient au même perchoir.", "Calotte striée.", "Hiverne en Afrique."]
  },
  "grey-streaked-flycatcher": {
    name: "Gobemouche à taches grises",
    s: "Gobemouche gris aux stries nettes sur un dessous blanc et aux longues ailes. Migrateur rare dans le nord et l’est.",
    d: "Le Gobemouche à taches grises niche dans l’Extrême-Orient russe et le nord-est de la Chine et hiverne aux Philippines et en Indonésie. En Mongolie, il est rare, noté dans la vallée de Khurkh et à Terelj.",
    f: ["Dessus gris.", "Dessous blanc à stries grises nettes.", "Très longues ailes atteignant presque le bout de la queue.", "Cercle orbital blanc."],
    si: "Gobemouche de Sibérie — estompé, non strié. Gobemouche gris — calotte striée.",
    h: "Lisières.",
    di: "Rare ; Khurkh, Terelj, Oulan-Bator.",
    mi: "Migrateur rare.",
    fo: "Insectes volants.",
    br: "Niche en Extrême-Orient.",
    be: "Se perche haut sur des rameaux morts.",
    v: "Surtout silencieux.",
    cu: "L’un des gobemouches aux ailes les plus longues.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Très longues ailes.", "Stries nettes.", "Rare en Mongolie."]
  },
  "dark-sided-flycatcher": {
    name: "Gobemouche de Sibérie",
    s: "Gobemouche gris-brun sombre aux flancs estompés et au demi-collier pâle. Visiteur d’été des forêts du nord.",
    d: "Le Gobemouche de Sibérie niche dans la taïga, de la Sibérie au Japon, et dans l’Himalaya, et hiverne en Asie du Sud-Est. En Mongolie, il niche dans le Khentii (Terelj, Khurkh, Oulan-Bator) et le Khövsgöl.",
    f: ["Dessus gris-brun sombre.", "Poitrine et flancs estompés de sombre.", "Gorge et demi-collier blancs.", "Longues ailes."],
    si: "Gobemouche brun — plus pâle, dessous plus net.",
    h: "Forêts de conifères et mixtes.",
    di: "Oulan-Bator, Khurkh, Terelj, Yolyn Am, lac Buir, Khövsgöl.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Niche sur une branche ; 3 ou 4 œufs.",
    be: "Chasse depuis des perchoirs élevés.",
    v: "Un fin trille.",
    cu: "Oiseau typique de la canopée de la taïga.",
    co: "Préoccupation mineure.",
    w: "Forêts de Terelj en juin.",
    bt: "juin–août",
    fa: ["Flancs estompés.", "Oiseau de la taïga.", "Longues ailes."]
  },
  "asian-brown-flycatcher": {
    name: "Gobemouche brun",
    s: "Petit gobemouche gris-brun uni au large cercle orbital. Visiteur d’été et migrateur commun.",
    d: "Le Gobemouche brun niche de la Sibérie au Japon et hiverne en Asie du Sud-Est et en Inde. En Mongolie, il niche dans le Khentii et passe en nombre à Yolyn Am et Khustai.",
    f: ["Dessus gris-brun uni.", "Dessous blanchâtre lavé de gris.", "Grand œil sombre cerclé de blanc.", "Base de la mandibule pâle."],
    si: "Gobemouche de Sibérie — plus sombre, dessous estompé.",
    h: "Bois feuillus et parcs.",
    di: "Khurkh, Oulan-Bator, Yolyn Am, Terelj, Khustai, lac Orog.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes volants.",
    br: "Niche dans les arbres ; 4 ou 5 œufs.",
    be: "Chasse discrètement.",
    v: "Un fin « tzi ».",
    cu: "Aussi appelé Gobemouche de Daourie.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai–sept.",
    fa: ["Large cercle orbital.", "Uni.", "Migrateur commun."]
  },
  "european-robin": {
    name: "Rougegorge familier",
    s: "Le célèbre rougegorge à face et poitrine orange. Migrateur rare en Mongolie.",
    d: "Le Rougegorge familier vit de l’Europe à la Sibérie occidentale. En Mongolie, c’est un visiteur rare, noté près d’Oulan-Bator et au lac Khar Us.",
    f: ["Face et poitrine orange bordées de gris.", "Dos brun olive.", "Grand œil sombre."],
    si: "Rossignol calliope — seule la gorge est rouge.",
    h: "Bois et jardins.",
    di: "Rare ; Oulan-Bator, lac Khar Us, Yolyn Am.",
    mi: "Migrateur rare.",
    fo: "Insectes et vers.",
    br: "Niche dans des cavités (pas en Mongolie).",
    be: "Suit les jardiniers pour les vers.",
    v: "Un chant liquide et mélancolique.",
    cu: "Oiseau national du Royaume-Uni.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Poitrine orange.", "Oiseau national britannique.", "Rare en Mongolie."]
  },
  "rufous-tailed-robin": {
    name: "Rossignol siffleur",
    s: "Petit rossignol discret à queue rousse et poitrine écailleuse. Migrateur rare.",
    d: "Le Rossignol siffleur niche dans la taïga sibérienne et hiverne en Asie du Sud-Est. En Mongolie, il est rare, noté dans l’est et l’ouest.",
    f: ["Dessus brun olive.", "Queue rousse, souvent tremblée.", "Poitrine blanchâtre écaillée de gris."],
    si: "Femelle de Rossignol bleu — croupion bleu.",
    h: "Sous-bois forestier dense.",
    di: "Rare ; est et ouest de la Mongolie, Oulan-Bator.",
    mi: "Migrateur rare.",
    fo: "Insectes.",
    br: "Niche dans la taïga.",
    be: "Fait trembler sa queue.",
    v: "Un chant trillé.",
    cu: "Son trille résonne dans la taïga.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Queue rousse.", "Fait trembler sa queue.", "Discret."]
  },
  "siberian-blue-robin": {
    name: "Rossignol bleu",
    s: "Le mâle est bleu profond dessus et blanc pur dessous ; la femelle est brune à croupion bleu. Visiteur d’été des forêts de l’est.",
    d: "Le Rossignol bleu niche du sud de la Sibérie au Japon et hiverne en Asie du Sud-Est. En Mongolie, il niche dans les forêts denses de la vallée de Khurkh et du Dornod.",
    f: ["Mâle : dessus bleu profond, dessous blanc.", "Trait noir du bec aux côtés de la poitrine.", "Femelle : brun olive à croupion bleu.", "Longues pattes roses."],
    si: "Rossignol à flancs roux — flancs orange.",
    h: "Sous-bois forestier dense.",
    di: "Khurkh, lac Buir, Oulan-Bator, lac Ganga, Terelj.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol ; 4 à 6 œufs.",
    be: "Fait trembler sa queue ; discret.",
    v: "Un chant trillé sonore.",
    cu: "Un joyau des forêts de l’est.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Bleu et blanc.", "Discret.", "Forêts de l’est."]
  },
  "common-nightingale": {
    name: "Rossignol philomèle",
    s: "Oiseau brun uni à queue rousse, célèbre pour son chant puissant de jour comme de nuit. Localisé dans l’extrême ouest de la Mongolie.",
    d: "Le Rossignol philomèle niche de l’Europe à l’Asie centrale et hiverne en Afrique. En Mongolie, on le trouve dans les fourrés riverains de l’extrême ouest.",
    f: ["Brun chaud uni.", "Queue rousse.", "Dessous pâle.", "Grand œil sombre."],
    si: "Peu de confusions possibles.",
    h: "Fourrés denses près de l’eau.",
    di: "Extrême ouest (lac Khar Us, rivière Khovd).",
    mi: "Visiteur d’été.",
    fo: "Insectes.",
    br: "Niche bas dans un couvert dense.",
    be: "Chante la nuit.",
    v: "Chant riche et puissant aux longs crescendos.",
    cu: "Célébré en poésie, de Keats aux ghazals persans.",
    co: "Préoccupation mineure.",
    w: "Fourrés riverains au crépuscule.",
    bt: "juin",
    fa: ["Chante la nuit.", "Queue rousse.", "Célèbre en poésie."]
  },
  "red-flanked-bluetail": {
    name: "Rossignol à flancs roux",
    s: "Petit traquet à queue bleue et flancs orange ; le mâle est bleu dessus. Commun dans les forêts du nord.",
    d: "Le Rossignol à flancs roux niche dans la taïga, de la Finlande au Japon, et hiverne en Asie du Sud-Est. En Mongolie, il niche dans le Khentii (Terelj, Oulan-Bator, Khurkh) et passe ailleurs.",
    f: ["Queue bleue.", "Flancs orange.", "Gorge blanche.", "Mâle : dessus bleu ; femelle : brun olive."],
    si: "Rossignol bleu — sans flancs orange.",
    h: "Forêts de conifères.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Khövsgöl, lac Ganga.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Insectes et baies.",
    br: "Niche dans les talus ou les racines.",
    be: "Agite la queue.",
    v: "Un chant court et doux.",
    cu: "S’étend vers l’ouest jusqu’en Europe.",
    co: "Préoccupation mineure.",
    w: "Forêts de Terelj en mai.",
    bt: "mai–sept.",
    fa: ["Queue bleue.", "Flancs orange.", "S’étend vers l’ouest."]
  },
  "taiga-flycatcher": {
    name: "Gobemouche de la taïga",
    s: "Minuscule gobemouche qui relève sa queue noire et blanche ; le mâle a la gorge orange au printemps. Très commun en forêt et en migration.",
    d: "Le Gobemouche de la taïga niche dans toute la taïga sibérienne et hiverne en Asie du Sud. En Mongolie, il niche dans le Khentii et abonde en migration — Oulan-Bator, vallée de Khurkh, Terelj, Yolyn Am.",
    f: ["Côtés blancs à la queue noire.", "Mâle : gorge rouge orangé au printemps.", "Dessus gris-brun.", "Relève la queue."],
    si: "Gobemouche mugimaki — poitrine orange, tache blanche post-oculaire. Gobemouche brun — sans blanc à la queue.",
    h: "Forêts, parcs et oasis.",
    di: "Oulan-Bator, Khurkh, Terelj, Yolyn Am, Khustai, lac Khar Us.",
    mi: "Visiteur d’été et migrateur, mai–septembre.",
    fo: "Petits insectes.",
    br: "Niche dans des cavités d’arbres ; 5 ou 6 œufs.",
    be: "Relève et agite la queue.",
    v: "Un crépitement sec « trrrt ».",
    cu: "L’un des gobemouches les plus nombreux d’Asie.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en mai.",
    bt: "mai–sept.",
    fa: ["Relève la queue.", "Gorge orange au printemps.", "Très commun."]
  },
  "mugimaki-flycatcher": {
    name: "Gobemouche mugimaki",
    s: "Petit gobemouche ; le mâle est noir dessus avec la poitrine orange et une tache blanche derrière l’œil. Migrateur peu commun.",
    d: "Le Gobemouche mugimaki niche dans la taïga sibérienne et hiverne en Asie du Sud-Est. En Mongolie, il est peu commun, noté dans l’est, l’ouest et le Khövsgöl.",
    f: ["Mâle : dessus noir, gorge et poitrine orange.", "Court trait blanc derrière l’œil.", "Tache alaire blanche."],
    si: "Gobemouche de la taïga — sans poitrine orange.",
    h: "Canopée forestière.",
    di: "Oulan-Bator, lac Ganga, Khurkh, Uvs, Khövsgöl.",
    mi: "Migrateur peu commun.",
    fo: "Insectes.",
    br: "Niche dans la taïga.",
    be: "Se nourrit haut dans les arbres.",
    v: "Un doux trille.",
    cu: "Son nom vient du japonais « mugimaki » (semeur de blé).",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "mai",
    fa: ["Poitrine orange.", "Nom japonais.", "Peu commun."]
  },
  "narcissus-flycatcher": {
    name: "Gobemouche narcisse",
    s: "Gobemouche noir et jaune éclatant à gorge orange. Erratique très rare, noté une seule fois.",
    d: "Le Gobemouche narcisse niche au Japon et à Sakhaline et hiverne aux Philippines et à Bornéo. Une mention dans le centre de la Mongolie en 2026 est exceptionnelle.",
    f: ["Mâle : dessus noir, sourcil et croupion jaunes.", "Gorge orange.", "Tache alaire blanche."],
    si: "Gobemouche à croupion jaune — sourcil blanc.",
    h: "Forêt.",
    di: "Erratique très rare.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche au Japon.",
    be: "Chante dans la canopée.",
    v: "Un chant doux et varié.",
    cu: "Nommé d’après le narcisse pour son jaune.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Sourcil jaune.", "Gorge orange.", "Très rare."]
  },
  "yellow-rumped-flycatcher": {
    name: "Gobemouche à croupion jaune",
    s: "Le mâle est noir dessus, jaune vif au croupion et dessous, avec un sourcil blanc. Visiteur d’été des forêts de l’est.",
    d: "Le Gobemouche à croupion jaune niche dans le nord-est de la Chine, en Corée et dans le sud-est de la Sibérie et hiverne en Asie du Sud-Est. En Mongolie, il niche dans la vallée de Khurkh et le Dornod et se voit à Yolyn Am.",
    f: ["Mâle : dessus noir, dessous et croupion jaunes.", "Sourcil blanc.", "Tache alaire blanche.", "Femelle : olive à croupion jaune."],
    si: "Gobemouche narcisse — sourcil jaune.",
    h: "Forêts feuillues.",
    di: "Khurkh, Yolyn Am, lac Buir, lac Ganga, Oulan-Bator.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes.",
    br: "Niche dans des cavités d’arbres.",
    be: "Chante dans la mi-canopée.",
    v: "Un chant riche et roulé.",
    cu: "Aussi appelé gobemouche tricolore.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Croupion jaune.", "Sourcil blanc.", "Forêts de l’est."]
  }
});
