B2T("en", {
  "eversmanns-redstart": {
    T: { c: { rufous: 0.4, gray: 0.3, black: 0.15, white: 0.15 }, hb: ["mountain", "forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16 cm", "—", "15–20 g"] },
    s: "A redstart with a grey crown, black mask, rusty throat and back, and white wing patch. A summer visitor to mountains of the west and Khangai.",
    d: "Eversmann’s (Rufous-backed) Redstart breeds in the mountains of Central Asia and western Mongolia and winters in Iran and Afghanistan. In Mongolia it breeds in juniper and larch scrub in the Altai (Khar Us Nuur area) and the Khangai (Terkhiin Tsagaan Nuur, Orkhon).",
    f: ["Male: grey crown, black mask.", "Rusty-orange throat, breast and back.", "Large white wing patch.", "Rufous tail with dark centre."],
    si: "Common Redstart — black throat, no wing patch. Daurian Redstart — black back.",
    h: "Mountain scrub and open forest.",
    di: "Khar Us Nuur, Terkhiin Tsagaan Nuur, Orkhon, Ögii Nuur, Ulaanbaatar.",
    mi: "Summer visitor, April–October.",
    fo: "Insects and berries.",
    br: "Nests in holes and crevices.",
    be: "Shivers its tail.",
    v: "A short, scratchy song.",
    cu: "Named after the naturalist Eduard Eversmann.",
    co: "Least Concern.",
    w: "Altai valleys in June.",
    bt: "May–August",
    fa: ["Rusty back.", "White wing patch.", "Mountain redstart."]
  },
  "common-redstart": {
    T: { c: { gray: 0.3, rufous: 0.35, black: 0.2, white: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–14.5 cm", "20–24 cm", "11–23 g"] },
    s: "A redstart with a grey back, black throat, white forehead and orange breast. A summer visitor to open woods in the north and west.",
    d: "The Common Redstart breeds from Europe to Lake Baikal and winters in Africa. In Mongolia it breeds in open larch and pine forests — Ulaanbaatar, Terelj, the Orkhon valley, Khar Us Nuur and Khövsgöl.",
    f: ["Male: grey back, black face and throat, white forehead.", "Orange breast.", "Rufous tail constantly quivering.", "Female: brownish with rufous tail."],
    si: "Daurian Redstart — white wing patch. Eversmann’s Redstart — rusty back.",
    h: "Open forests and parks.",
    di: "Ulaanbaatar, Terelj, Orkhon, Khar Us Nuur, Khövsgöl, Yolyn Am.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests in tree holes; 5–7 eggs.",
    be: "Quivers its tail.",
    v: "A short, melancholy song.",
    cu: "‘Start’ is an old word for tail.",
    co: "Least Concern.",
    w: "Terelj forest edges in June.",
    bt: "June",
    fa: ["Quivering red tail.", "White forehead.", "Winters in Africa."]
  },
  "black-redstart": {
    T: { c: { black: 0.5, gray: 0.2, rufous: 0.3 }, hb: ["mountain", "desert"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–14.5 cm", "23–26 cm", "12–20 g"] },
    s: "A sooty redstart of rocky places with a rufous tail and belly. Common in rocky mountains of the west and Gobi.",
    d: "The Black Redstart lives from Europe to China. The eastern form (phoenicuroides) has a rufous belly. In Mongolia it breeds in rocky gorges and cliffs — Khar Us Nuur, Yolyn Am, Terkhiin Tsagaan Nuur and Ölgii.",
    f: ["Male: sooty black head and breast.", "Rufous belly (eastern form) and tail.", "Female: grey-brown with rufous tail.", "Quivering tail."],
    si: "Common Redstart — orange breast, white forehead.",
    h: "Rocky slopes, cliffs and villages.",
    di: "Khar Us Nuur, Yolyn Am, Terkhiin Tsagaan Nuur, Ölgii, Orkhon.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests in crevices; 4–6 eggs.",
    be: "Bobs and quivers its tail.",
    v: "A scratchy song.",
    cu: "Colonised European cities after WWII bombing sites.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "May–August",
    fa: ["Sooty black.", "Rocky places.", "Rufous tail."]
  },
  "white-throated-rock-thrush": {
    T: { c: { rufous: 0.35, gray: 0.3, white: 0.15, black: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["17–19 cm", "—", "30–40 g"] },
    s: "A colourful rock thrush with a blue crown, white throat and chestnut underparts. A scarce summer visitor to eastern forests.",
    d: "The White-throated Rock Thrush breeds in south-east Siberia and north-east China and winters in South-East Asia. In Mongolia it is found in the east and the Khurkh valley.",
    f: ["Male: blue crown and nape.", "White throat patch.", "Chestnut underparts and rump.", "White wing patch."],
    si: "Common Rock Thrush — no white throat, lives on rocks.",
    h: "Rocky forest slopes.",
    di: "Khurkh, eastern Mongolia.",
    mi: "Summer visitor, May–August.",
    fo: "Insects.",
    br: "Nests in crevices.",
    be: "Sits quietly in trees.",
    v: "A sweet, fluty song.",
    cu: "Unlike other rock thrushes, it lives in forest.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["White throat.", "Forest rock thrush.", "Colourful."]
  },
  "common-rock-thrush": {
    T: { c: { gray: 0.3, rufous: 0.4, white: 0.1, black: 0.2 }, hb: ["mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16–19 cm", "33–37 cm", "40–60 g"] },
    s: "A stocky thrush; the male has a blue-grey head, orange breast and white back patch. A summer visitor to rocky slopes throughout Mongolia.",
    d: "The Rufous-tailed Rock Thrush breeds from southern Europe to Mongolia and winters in Africa. In Mongolia it is common on rocky slopes — Khar Us Nuur, Yolyn Am, Terelj, Ulaanbaatar and Khustai.",
    f: ["Male: blue-grey head, orange-red underparts and tail.", "White patch on the back.", "Female: mottled brown with rufous tail."],
    si: "Blue Rock Thrush — all blue.",
    h: "Rocky slopes and cliffs.",
    di: "Khar Us Nuur, Yolyn Am, Terelj, Ulaanbaatar, Khustai, Orkhon.",
    mi: "Summer visitor, May–September.",
    fo: "Insects and berries.",
    br: "Nests in rock crevices.",
    be: "Sings in a parachuting flight.",
    v: "A rich, fluty song.",
    cu: "Its song flight over rocky hills is a sign of spring.",
    co: "Least Concern.",
    w: "Terelj rocks in June.",
    bt: "May–August",
    fa: ["Orange breast.", "White back patch.", "Winters in Africa."]
  },
  "blue-rock-thrush": {
    T: { c: { gray: 0.5, rufous: 0.25, black: 0.25 }, hb: ["mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["21–23 cm", "33–37 cm", "50–70 g"] },
    s: "A blue thrush of rocky places; the eastern male has a chestnut belly. A very rare visitor to eastern Mongolia.",
    d: "The Blue Rock Thrush lives from southern Europe to East Asia. The eastern form (philippensis) has chestnut underparts. In Mongolia it was recorded in the east in 2026.",
    f: ["Male: deep blue with chestnut belly (eastern form).", "Long bill.", "Female: brown, scaly."],
    si: "Common Rock Thrush — orange tail, white back.",
    h: "Rocky coasts and cliffs.",
    di: "Very rare; eastern Mongolia.",
    mi: "Vagrant.",
    fo: "Insects and small lizards.",
    br: "Nests in crevices (not in Mongolia).",
    be: "Sits on rocks and roofs.",
    v: "A melodious song.",
    cu: "The national bird of Malta.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Blue body.", "National bird of Malta.", "Very rare in Mongolia."]
  },
  "hodgsons-bush-chat": {
    T: { c: { black: 0.35, white: 0.35, rufous: 0.2, brown: 0.1 }, hb: ["mountain", "steppe"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16 cm", "—", "18–22 g"] },
    s: "A large, black-and-white chat with a big white wing patch. Breeds in alpine meadows of the Khangai; globally Vulnerable.",
    d: "Hodgson’s (White-throated) Bushchat breeds only in the high mountains of Mongolia and adjacent Russia, and winters in the Himalayan foothills of India and Nepal. It is Vulnerable because its wintering grasslands are being lost. In Mongolia it breeds in the Khangai (Terkhiin Tsagaan Nuur, Orkhon) and the Altai.",
    f: ["Male: black head and back, white throat and collar.", "Large white wing patches.", "Rufous breast.", "Larger than Stonechat."],
    si: "Eastern Stonechat — smaller, black throat.",
    h: "Alpine meadows with scrub.",
    di: "Khangai (Terkhiin Tsagaan Nuur, Orkhon), Khar Us Nuur, Orog Nuur.",
    mi: "Summer visitor, May–September.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Perches on bushes.",
    v: "A short, scratchy song.",
    cu: "Mongolia is its main breeding area in the world.",
    co: "Vulnerable.",
    w: "Terkhiin Tsagaan Nuur meadows in June.",
    bt: "June",
    fa: ["Breeds mainly in Mongolia.", "Vulnerable.", "White wing patch."]
  },
  "northern-wheatear": {
    T: { c: { gray: 0.3, white: 0.3, black: 0.25, buff: 0.15 }, hb: ["steppe", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–16 cm", "26–32 cm", "20–30 g"] },
    s: "A grey-backed wheatear with a black mask and a white rump with a black ‘T’ on the tail. Common in steppe and mountains.",
    d: "The Northern Wheatear breeds across Eurasia and Arctic North America and winters in Africa — an extraordinary migration of up to 14,000 km. In Mongolia it is common in stony steppe and mountains — Ulaanbaatar, Khar Us Nuur, Terelj, Khurkh and Khustai.",
    f: ["Male: grey back, black mask, black wings.", "White rump and tail with a black ‘T’.", "Buff breast.", "Female: brownish."],
    si: "Isabelline Wheatear — pale sandy, broader tail band. Pied Wheatear — black back.",
    h: "Stony steppe and mountain slopes.",
    di: "Ulaanbaatar, Khar Us Nuur, Terelj, Khurkh, Khustai, Yolyn Am.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests in holes and burrows.",
    be: "Bobs and flicks its tail.",
    v: "A scratchy song.",
    cu: "Its migration is among the longest of any songbird.",
    co: "Least Concern.",
    w: "Terelj rocks in May.",
    bt: "May–August",
    fa: ["Migrates 14,000 km.", "Black ‘T’ on tail.", "Common in Mongolia."]
  },
  "isabelline-wheatear": {
    T: { c: { buff: 0.5, brown: 0.2, white: 0.2, black: 0.1 }, hb: ["steppe", "desert"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16.5 cm", "27–31 cm", "22–35 g"] },
    s: "A pale sandy wheatear that nests in marmot and pika burrows. Mongolia’s most common wheatear, everywhere on steppe.",
    d: "The Isabelline Wheatear breeds from Turkey to Mongolia and winters in Africa and India. It uses rodent burrows for nesting. In Mongolia it is abundant on steppe and semi-desert — Yolyn Am, Ulaanbaatar, Khurkh, Ögii Nuur and Khustai.",
    f: ["Pale sandy-buff, uniform.", "Black alula spot on the wing.", "Broad black tail band.", "Upright stance, long legs."],
    si: "Northern Wheatear (female) — darker, narrower tail band.",
    h: "Steppe and semi-desert with burrows.",
    di: "All regions: Yolyn Am, Ulaanbaatar, Khurkh, Ögii Nuur, Khar Us Nuur, Khustai.",
    mi: "Summer visitor, March–September.",
    fo: "Insects.",
    br: "Nests in rodent burrows.",
    be: "Mimics other birds; hovers in song flight.",
    v: "A loud, mimicking song.",
    cu: "Lives in marmot burrows alongside the marmots.",
    co: "Least Concern.",
    w: "Any steppe in May.",
    bt: "April–August",
    fa: ["Nests in burrows.", "Mongolia’s commonest wheatear.", "Excellent mimic."]
  },
  "desert-wheatear": {
    T: { c: { buff: 0.45, black: 0.35, white: 0.2 }, hb: ["desert"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "A sandy wheatear with a black throat and an all-black tail. Common in the Gobi and western deserts.",
    d: "The Desert Wheatear breeds from North Africa to Mongolia. In Mongolia it is common in the Gobi and deserts of the west — Khar Us Nuur, Yolyn Am, Orog Nuur and Böön Tsagaan.",
    f: ["Male: sandy back, black throat and face.", "Almost all-black tail.", "Black wings.", "White rump."],
    si: "Pied Wheatear — black back.",
    h: "Deserts and semi-deserts.",
    di: "Khar Us Nuur, Yolyn Am, Orog Nuur, Böön Tsagaan, Taatsiin Tsagaan, Ikh Nart.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests in holes or under shrubs.",
    be: "Perches on low shrubs.",
    v: "A plaintive song.",
    cu: "Adapted to extreme heat.",
    co: "Least Concern.",
    w: "Gobi in May.",
    bt: "May–August",
    fa: ["Black tail.", "Desert bird.", "Black throat."]
  },
  "pied-wheatear": {
    T: { c: { black: 0.5, white: 0.45, buff: 0.05 }, hb: ["steppe", "mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–16.5 cm", "—", "16–22 g"] },
    s: "A striking black-and-white wheatear with a black back and throat. Common on rocky steppe.",
    d: "The Pied Wheatear breeds from the Black Sea to Mongolia and winters in East Africa. In Mongolia it is common on rocky slopes — Khar Us Nuur, Khustai, Ulaanbaatar, Yolyn Am and Terelj.",
    f: ["Male: black back, face and throat.", "White crown and underparts.", "White rump and tail with a black ‘T’."],
    si: "Northern Wheatear — grey back. Desert Wheatear — sandy back.",
    h: "Rocky steppe and hills.",
    di: "Khar Us Nuur, Khustai, Ulaanbaatar, Yolyn Am, Orog Nuur, Terelj.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests in holes among rocks.",
    be: "Perches on rocks and wires.",
    v: "A varied song with mimicry.",
    cu: "Named ‘pleschanka’ after a Russian word for bald.",
    co: "Least Concern.",
    w: "Khustai rocks in June.",
    bt: "May–August",
    fa: ["Black back.", "White crown.", "Common on rocky steppe."]
  }
});
