B2T("fr", {
  "eversmanns-redstart": {
    name: "Rougequeue d’Eversmann",
    s: "Rougequeue à calotte grise, masque noir, gorge et dos rouille et tache alaire blanche. Visiteur d’été des montagnes de l’ouest et du Khangaï.",
    d: "Le Rougequeue d’Eversmann niche dans les montagnes d’Asie centrale et de l’ouest de la Mongolie et hiverne en Iran et en Afghanistan. En Mongolie, il niche dans les genévriers et mélèzes de l’Altaï (région du lac Khar Us) et du Khangaï (Terkhiin Tsagaan Nuur, Orkhon).",
    f: ["Mâle : calotte grise, masque noir.", "Gorge, poitrine et dos orange rouille.", "Grande tache alaire blanche.", "Queue rousse à centre sombre."],
    si: "Rougequeue à front blanc — gorge noire, sans tache alaire. Rougequeue aurore — dos noir.",
    h: "Broussailles de montagne et forêts claires.",
    di: "Lac Khar Us, Terkhiin Tsagaan Nuur, Orkhon, lac Ögii, Oulan-Bator.",
    mi: "Visiteur d’été, avril–octobre.",
    fo: "Insectes et baies.",
    br: "Niche dans des cavités et fissures.",
    be: "Fait trembler sa queue.",
    v: "Un chant court et grinçant.",
    cu: "Nommé d’après le naturaliste Eduard Eversmann.",
    co: "Préoccupation mineure.",
    w: "Vallées de l’Altaï en juin.",
    bt: "mai–août",
    fa: ["Dos rouille.", "Tache alaire blanche.", "Rougequeue montagnard."]
  },
  "common-redstart": {
    name: "Rougequeue à front blanc",
    s: "Rougequeue au dos gris, gorge noire, front blanc et poitrine orange. Visiteur d’été des bois clairs du nord et de l’ouest.",
    d: "Le Rougequeue à front blanc niche de l’Europe au lac Baïkal et hiverne en Afrique. En Mongolie, il niche dans les forêts claires de mélèzes et de pins — Oulan-Bator, Terelj, vallée de l’Orkhon, lac Khar Us et Khövsgöl.",
    f: ["Mâle : dos gris, face et gorge noires, front blanc.", "Poitrine orange.", "Queue rousse sans cesse tremblante.", "Femelle : brunâtre à queue rousse."],
    si: "Rougequeue aurore — tache alaire blanche. Rougequeue d’Eversmann — dos rouille.",
    h: "Forêts claires et parcs.",
    di: "Oulan-Bator, Terelj, Orkhon, lac Khar Us, Khövsgöl, Yolyn Am.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche dans des cavités d’arbres ; 5 à 7 œufs.",
    be: "Fait trembler sa queue.",
    v: "Un chant court et mélancolique.",
    cu: "« Queue rouge » : son nom décrit sa queue.",
    co: "Préoccupation mineure.",
    w: "Lisières de Terelj en juin.",
    bt: "juin",
    fa: ["Queue rouge tremblante.", "Front blanc.", "Hiverne en Afrique."]
  },
  "black-redstart": {
    name: "Rougequeue noir",
    s: "Rougequeue suie des lieux rocheux, à queue et ventre roux. Commun dans les montagnes rocheuses de l’ouest et du Gobi.",
    d: "Le Rougequeue noir vit de l’Europe à la Chine. La forme orientale (phoenicuroides) a le ventre roux. En Mongolie, il niche dans les gorges et falaises — lac Khar Us, Yolyn Am, Terkhiin Tsagaan Nuur et Ölgii.",
    f: ["Mâle : tête et poitrine noir suie.", "Ventre (forme orientale) et queue roux.", "Femelle : gris-brun à queue rousse.", "Queue tremblante."],
    si: "Rougequeue à front blanc — poitrine orange, front blanc.",
    h: "Pentes rocheuses, falaises et villages.",
    di: "Lac Khar Us, Yolyn Am, Terkhiin Tsagaan Nuur, Ölgii, Orkhon.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans les fissures ; 4 à 6 œufs.",
    be: "Hoche et fait trembler la queue.",
    v: "Un chant grinçant.",
    cu: "A colonisé les ruines des villes européennes après la Seconde Guerre mondiale.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "mai–août",
    fa: ["Noir suie.", "Lieux rocheux.", "Queue rousse."]
  },
  "white-throated-rock-thrush": {
    name: "Monticole à gorge blanche",
    s: "Monticole coloré à calotte bleue, gorge blanche et dessous marron. Visiteur d’été peu commun des forêts de l’est.",
    d: "Le Monticole à gorge blanche niche dans le sud-est de la Sibérie et le nord-est de la Chine et hiverne en Asie du Sud-Est. En Mongolie, on le trouve dans l’est et la vallée de Khurkh.",
    f: ["Mâle : calotte et nuque bleues.", "Tache gulaire blanche.", "Dessous et croupion marron.", "Tache alaire blanche."],
    si: "Monticole de roche — sans gorge blanche, vit sur les rochers.",
    h: "Pentes forestières rocheuses.",
    di: "Khurkh, est de la Mongolie.",
    mi: "Visiteur d’été, mai–août.",
    fo: "Insectes.",
    br: "Niche dans des fissures.",
    be: "Se tient tranquille dans les arbres.",
    v: "Un chant doux et flûté.",
    cu: "Contrairement aux autres monticoles, il vit en forêt.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Gorge blanche.", "Monticole forestier.", "Coloré."]
  },
  "common-rock-thrush": {
    name: "Monticole de roche",
    s: "Grive trapue ; le mâle a la tête gris-bleu, la poitrine orange et une tache dorsale blanche. Visiteur d’été des pentes rocheuses de toute la Mongolie.",
    d: "Le Monticole de roche niche du sud de l’Europe à la Mongolie et hiverne en Afrique. En Mongolie, il est commun sur les pentes rocheuses — lac Khar Us, Yolyn Am, Terelj, Oulan-Bator et Khustai.",
    f: ["Mâle : tête gris-bleu, dessous et queue rouge orangé.", "Tache blanche sur le dos.", "Femelle : brune mouchetée, queue rousse."],
    si: "Monticole bleu — entièrement bleu.",
    h: "Pentes rocheuses et falaises.",
    di: "Lac Khar Us, Yolyn Am, Terelj, Oulan-Bator, Khustai, Orkhon.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes et baies.",
    br: "Niche dans les fissures rocheuses.",
    be: "Chante en vol parachuté.",
    v: "Un chant riche et flûté.",
    cu: "Son vol chanté sur les collines rocheuses annonce le printemps.",
    co: "Préoccupation mineure.",
    w: "Rochers de Terelj en juin.",
    bt: "mai–août",
    fa: ["Poitrine orange.", "Tache dorsale blanche.", "Hiverne en Afrique."]
  },
  "blue-rock-thrush": {
    name: "Monticole bleu",
    s: "Grive bleue des rochers ; le mâle oriental a le ventre marron. Visiteur très rare dans l’est de la Mongolie.",
    d: "Le Monticole bleu vit du sud de l’Europe à l’Asie orientale. La forme orientale (philippensis) a le dessous marron. En Mongolie, il a été noté dans l’est en 2026.",
    f: ["Mâle : bleu profond à ventre marron (forme orientale).", "Long bec.", "Femelle : brune, écailleuse."],
    si: "Monticole de roche — queue orange, dos blanc.",
    h: "Côtes rocheuses et falaises.",
    di: "Très rare ; est de la Mongolie.",
    mi: "Erratique.",
    fo: "Insectes et petits lézards.",
    br: "Niche dans des fissures (pas en Mongolie).",
    be: "Se pose sur les rochers et les toits.",
    v: "Un chant mélodieux.",
    cu: "Oiseau national de Malte.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Corps bleu.", "Oiseau national de Malte.", "Très rare en Mongolie."]
  },
  "hodgsons-bush-chat": {
    name: "Tarier de Hodgson",
    s: "Grand tarier noir et blanc à grande tache alaire blanche. Niche dans les prairies alpines du Khangaï ; Vulnérable.",
    d: "Le Tarier de Hodgson niche uniquement dans les hautes montagnes de Mongolie et de Russie voisine et hiverne au pied de l’Himalaya en Inde et au Népal. Il est Vulnérable car ses prairies d’hivernage disparaissent. En Mongolie, il niche dans le Khangaï (Terkhiin Tsagaan Nuur, Orkhon) et l’Altaï.",
    f: ["Mâle : tête et dos noirs, gorge et collier blancs.", "Grandes taches alaires blanches.", "Poitrine rousse.", "Plus grand que le Tarier pâtre."],
    si: "Tarier de Sibérie — plus petit, gorge noire.",
    h: "Prairies alpines buissonnantes.",
    di: "Khangaï (Terkhiin Tsagaan Nuur, Orkhon), lac Khar Us, lac Orog.",
    mi: "Visiteur d’été, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Se perche sur les buissons.",
    v: "Un chant court et grinçant.",
    cu: "La Mongolie est son principal territoire de nidification.",
    co: "Vulnérable.",
    w: "Prairies de Terkhiin Tsagaan Nuur en juin.",
    bt: "juin",
    fa: ["Niche surtout en Mongolie.", "Vulnérable.", "Tache alaire blanche."]
  },
  "northern-wheatear": {
    name: "Traquet motteux",
    s: "Traquet à dos gris, masque noir et croupion blanc avec un « T » noir sur la queue. Commun dans les steppes et montagnes.",
    d: "Le Traquet motteux niche dans toute l’Eurasie et l’Amérique du Nord arctique et hiverne en Afrique — une migration extraordinaire jusqu’à 14 000 km. En Mongolie, il est commun dans les steppes pierreuses et montagnes — Oulan-Bator, lac Khar Us, Terelj, Khurkh et Khustai.",
    f: ["Mâle : dos gris, masque noir, ailes noires.", "Croupion et queue blancs à « T » noir.", "Poitrine chamois.", "Femelle : brunâtre."],
    si: "Traquet isabelle — sable pâle, bande caudale plus large. Traquet pie — dos noir.",
    h: "Steppe pierreuse et pentes.",
    di: "Oulan-Bator, lac Khar Us, Terelj, Khurkh, Khustai, Yolyn Am.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans des trous et terriers.",
    be: "Hoche et agite la queue.",
    v: "Un chant grinçant.",
    cu: "L’une des plus longues migrations chez les passereaux.",
    co: "Préoccupation mineure.",
    w: "Rochers de Terelj en mai.",
    bt: "mai–août",
    fa: ["Migre 14 000 km.", "« T » noir sur la queue.", "Commun en Mongolie."]
  },
  "isabelline-wheatear": {
    name: "Traquet isabelle",
    s: "Traquet sable pâle qui niche dans les terriers de marmottes et de pikas. Le traquet le plus commun de Mongolie, partout dans la steppe.",
    d: "Le Traquet isabelle niche de la Turquie à la Mongolie et hiverne en Afrique et en Inde. Il niche dans les terriers de rongeurs. En Mongolie, il abonde dans la steppe et le semi-désert — Yolyn Am, Oulan-Bator, Khurkh, lac Ögii et Khustai.",
    f: ["Sable chamois pâle, uniforme.", "Tache noire à l’alula.", "Large bande noire à la queue.", "Port dressé, longues pattes."],
    si: "Femelle de Traquet motteux — plus sombre, bande caudale plus étroite.",
    h: "Steppe et semi-désert à terriers.",
    di: "Toutes les régions : Yolyn Am, Oulan-Bator, Khurkh, lac Ögii, lac Khar Us, Khustai.",
    mi: "Visiteur d’été, mars–septembre.",
    fo: "Insectes.",
    br: "Niche dans les terriers de rongeurs.",
    be: "Imite d’autres oiseaux ; fait du surplace en chantant.",
    v: "Un chant sonore et imitateur.",
    cu: "Vit dans les terriers de marmottes aux côtés des marmottes.",
    co: "Préoccupation mineure.",
    w: "N’importe quelle steppe en mai.",
    bt: "avril–août",
    fa: ["Niche dans les terriers.", "Traquet le plus commun de Mongolie.", "Excellent imitateur."]
  },
  "desert-wheatear": {
    name: "Traquet du désert",
    s: "Traquet sable à gorge noire et queue entièrement noire. Commun dans le Gobi et les déserts de l’ouest.",
    d: "Le Traquet du désert niche de l’Afrique du Nord à la Mongolie. En Mongolie, il est commun dans le Gobi et les déserts de l’ouest — lac Khar Us, Yolyn Am, lac Orog et Böön Tsagaan.",
    f: ["Mâle : dos sable, gorge et face noires.", "Queue presque entièrement noire.", "Ailes noires.", "Croupion blanc."],
    si: "Traquet pie — dos noir.",
    h: "Déserts et semi-déserts.",
    di: "Lac Khar Us, Yolyn Am, lac Orog, Böön Tsagaan, Taatsiin Tsagaan, Ikh Nart.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans des trous ou sous les buissons.",
    be: "Se perche sur les buissons bas.",
    v: "Un chant plaintif.",
    cu: "Adapté à la chaleur extrême.",
    co: "Préoccupation mineure.",
    w: "Gobi en mai.",
    bt: "mai–août",
    fa: ["Queue noire.", "Oiseau du désert.", "Gorge noire."]
  },
  "pied-wheatear": {
    name: "Traquet pie",
    s: "Traquet noir et blanc saisissant à dos et gorge noirs. Commun sur les steppes rocheuses.",
    d: "Le Traquet pie niche de la mer Noire à la Mongolie et hiverne en Afrique de l’Est. En Mongolie, il est commun sur les pentes rocheuses — lac Khar Us, Khustai, Oulan-Bator, Yolyn Am et Terelj.",
    f: ["Mâle : dos, face et gorge noirs.", "Calotte et dessous blancs.", "Croupion et queue blancs à « T » noir."],
    si: "Traquet motteux — dos gris. Traquet du désert — dos sable.",
    h: "Steppe rocheuse et collines.",
    di: "Lac Khar Us, Khustai, Oulan-Bator, Yolyn Am, lac Orog, Terelj.",
    mi: "Visiteur d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans des trous entre les rochers.",
    be: "Se perche sur les rochers et les fils.",
    v: "Un chant varié avec imitations.",
    cu: "Son nom « pleschanka » vient d’un mot russe signifiant « chauve ».",
    co: "Préoccupation mineure.",
    w: "Rochers de Khustai en juin.",
    bt: "mai–août",
    fa: ["Dos noir.", "Calotte blanche.", "Commun sur les steppes rocheuses."]
  }
});
