B2T("en", {
  "alpine-accentor": {
    T: { c: { gray: 0.4, brown: 0.3, rufous: 0.2, white: 0.1 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["15–17.5 cm", "30–32 cm", "25–40 g"] },
    s: "A sparrow-like mountain bird with a grey head, a spotted throat and chestnut-streaked flanks. Resident on high rocky slopes.",
    d: "The Alpine Accentor lives on high mountains from Spain to Japan. In Mongolia it lives on rocky peaks of the Gobi-Altai (Yolyn Am), the Altai, Khangai and near Ulaanbaatar, descending in winter.",
    f: ["Grey head and breast.", "Black-and-white spotted throat patch.", "Chestnut-streaked flanks.", "Black wing coverts with white tips."],
    si: "Altai Accentor — white throat bordered black.",
    h: "High rocky slopes and screes.",
    di: "Yolyn Am, Ulaanbaatar (Bogd Khan Uul), Terelj, Terkhiin Tsagaan Nuur, Khar Us Nuur, Ölgii.",
    mi: "Resident; moves lower in winter.",
    fo: "Insects in summer, seeds in winter.",
    br: "Nests in rock crevices; complex group breeding.",
    be: "Very tame; creeps among rocks.",
    v: "A rippling, lark-like song.",
    cu: "Females mate with several males, who all help feed chicks.",
    co: "Least Concern.",
    w: "Yolyn Am rocks.",
    bt: "all year",
    fa: ["Spotted throat.", "Lives above the tree line.", "Group breeding."]
  },
  "altai-accentor": {
    T: { c: { gray: 0.35, rufous: 0.3, white: 0.2, black: 0.15 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–18 cm", "—", "20–30 g"] },
    s: "A grey-headed accentor with a white throat framed in black and rufous-spotted breast. Breeds on alpine slopes of the Altai and Khangai.",
    d: "The Altai Accentor breeds in the Altai, Sayan and Tian Shan and winters in the Himalaya. In Mongolia it breeds on high slopes around Khar Us Nuur, Ölgii and Tavan Bogd, and in the Khangai.",
    f: ["Grey head.", "White throat bordered by a black band.", "Rufous-spotted breast.", "Streaked back."],
    si: "Alpine Accentor — spotted throat, grey breast.",
    h: "Alpine meadows and screes.",
    di: "Khar Us Nuur, Orog Nuur, Ölgii, Tavan Bogd, Terkhiin Tsagaan Nuur.",
    mi: "Summer visitor; some winter.",
    fo: "Insects and seeds.",
    br: "Nests among rocks.",
    be: "Forages on the ground in flocks.",
    v: "A thin trill.",
    cu: "Also called Himalayan Accentor.",
    co: "Least Concern.",
    w: "Altai passes in summer.",
    bt: "June–August",
    fa: ["White throat.", "Alpine bird.", "Winters in the Himalaya."]
  },
  "siberian-accentor": {
    T: { c: { buff: 0.35, brown: 0.3, gray: 0.2, black: 0.15 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["whistle"], ac: "day", se: ["passage", "winter"], sz: ["13–15 cm", "—", "15–20 g"] },
    s: "A small accentor with a bold ochre eyebrow and throat and a black mask. A migrant and winter visitor, especially in the north.",
    d: "The Siberian Accentor breeds in the Siberian taiga and winters in China and Korea. In Mongolia it is common on passage and in winter around Ulaanbaatar, the Khurkh valley and Yolyn Am.",
    f: ["Bold ochre-buff eyebrow and throat.", "Black crown sides and mask.", "Streaked brown back.", "Grey neck patch."],
    si: "Brown Accentor — paler, white eyebrow.",
    h: "Scrub and forest edges.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Terelj, Ganga Nuur.",
    mi: "Passage migrant and winter visitor, October–April.",
    fo: "Seeds and insects.",
    br: "Nests in the Siberian taiga.",
    be: "Creeps under bushes.",
    v: "A thin ‘tsee-see’.",
    cu: "Has recently appeared in Europe in invasions.",
    co: "Least Concern.",
    w: "Bogd Khan Uul edges in October.",
    bt: "October–November",
    fa: ["Ochre eyebrow.", "Black mask.", "Winter visitor."]
  },
  "brown-accentor": {
    T: { c: { brown: 0.4, buff: 0.35, white: 0.15, black: 0.1 }, hb: ["mountain", "desert"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "A pale, sandy accentor with a whitish eyebrow and dark mask. Common in rocky gorges of the Gobi and west.",
    d: "The Brown Accentor lives in the dry mountains of Central Asia. In Mongolia it is common in rocky gorges — Yolyn Am, Khar Us Nuur, Ölgii and Orog Nuur — and near Ulaanbaatar in winter.",
    f: ["Whitish eyebrow.", "Dark brown mask.", "Pale buff underparts.", "Streaked brown back."],
    si: "Siberian Accentor — ochre eyebrow. Mongolian Accentor — greyer, plain.",
    h: "Rocky gorges and scrub in dry mountains.",
    di: "Yolyn Am, Khar Us Nuur, Ulaanbaatar, Ölgii, Orog Nuur, Terkhiin Tsagaan Nuur.",
    mi: "Resident; descends in winter.",
    fo: "Insects and seeds.",
    br: "Nests in bushes among rocks.",
    be: "Hops among rocks.",
    v: "A short trilling song.",
    cu: "Very common at Yolyn Am.",
    co: "Least Concern.",
    w: "Yolyn Am in any season.",
    bt: "all year",
    fa: ["White eyebrow.", "Dry mountains.", "Common at Yolyn Am."]
  },
  "black-throated-accentor": {
    T: { c: { brown: 0.35, black: 0.25, buff: 0.25, gray: 0.15 }, hb: ["mountain", "forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "An accentor with a black throat and mask and a buff eyebrow. Breeds in mountain scrub of far western Mongolia.",
    d: "The Black-throated Accentor breeds in the mountains of Central Asia and winters in lower valleys. In Mongolia it breeds mainly in the Altai around Khar Us Nuur.",
    f: ["Black throat and mask.", "Buff eyebrow and breast.", "Streaked brown back."],
    si: "Siberian Accentor — no black throat.",
    h: "Mountain juniper and scrub.",
    di: "Khar Us Nuur, Ölgii, Achit Nuur.",
    mi: "Summer visitor.",
    fo: "Insects and seeds.",
    br: "Nests in bushes.",
    be: "Skulks in shrubs.",
    v: "A thin, warbling song.",
    cu: "A western Mongolian speciality.",
    co: "Least Concern.",
    w: "Juniper scrub near Khar Us Nuur.",
    bt: "June",
    fa: ["Black throat.", "Juniper scrub.", "Western bird."]
  },
  "mongolian-accentor": {
    T: { c: { gray: 0.45, brown: 0.35, buff: 0.2 }, hb: ["mountain", "desert"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["15 cm", "—", "17–22 g"] },
    s: "A plain grey-brown accentor found almost only in Mongolia’s Gobi mountains. A near-endemic speciality, common at Yolyn Am.",
    d: "Kozlov’s (Mongolian) Accentor is found almost entirely in Mongolia and adjacent northern China, in dry mountain scrub. In Mongolia it is common at Yolyn Am and other Gobi-Altai gorges, and in the west.",
    f: ["Plain grey-brown with faint streaks.", "Pale throat.", "No strong face pattern.", "Streaked back."],
    si: "Brown Accentor — white eyebrow and dark mask.",
    h: "Dry mountain scrub and gorges.",
    di: "Yolyn Am, Khar Us Nuur, Taatsiin Tsagaan, Orog Nuur, Ulaanbaatar (winter), Terelj.",
    mi: "Resident; moves locally.",
    fo: "Seeds and insects.",
    br: "Nests in bushes.",
    be: "Unobtrusive.",
    v: "A soft twitter.",
    cu: "Named after the Russian explorer Pyotr Kozlov.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "all year",
    fa: ["Nearly endemic to Mongolia.", "Named after Kozlov.", "Plain colour."]
  },
  "eurasian-wren": {
    T: { c: { brown: 0.7, rufous: 0.2, buff: 0.1 }, hb: ["forest"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["9–10.5 cm", "13–17 cm", "7–12 g"] },
    s: "A tiny, round brown bird with a cocked tail and an amazingly loud song. Scarce in northern and eastern forests.",
    d: "The Eurasian Wren lives across Eurasia. It is one of the smallest birds but has one of the loudest songs. In Mongolia it is scarce, recorded in the Khurkh valley, Ulaanbaatar, Buir Nuur and Terelj.",
    f: ["Tiny and round.", "Cocked short tail.", "Brown with fine barring.", "Pale eyebrow."],
    si: "Unmistakable.",
    h: "Dense undergrowth near water.",
    di: "Khurkh, Ulaanbaatar, Buir Nuur, Terelj, Yolyn Am, Ganga Nuur.",
    mi: "Resident; some move.",
    fo: "Small insects and spiders.",
    br: "Domed nest; males build several.",
    be: "Creeps like a mouse.",
    v: "Very loud, rapid trilling song.",
    cu: "‘King of birds’ in European folklore.",
    co: "Least Concern.",
    w: "Riverside thickets in the Khurkh valley.",
    bt: "all year",
    fa: ["Tiny but loud.", "Cocked tail.", "Males build several nests."]
  },
  "goldcrest": {
    T: { c: { gray: 0.4, yellow: 0.3, white: 0.2, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["8.5–9.5 cm", "13–15 cm", "4.5–7 g"] },
    s: "The smallest bird of Mongolia — olive-green with a golden crown stripe edged in black. Lives in spruce forests.",
    d: "The Goldcrest lives in conifer forests across Eurasia. It weighs as little as a coin. In Mongolia it lives in spruce forests of the Khentii (Bogd Khan Uul, Terelj, Khurkh) and the Altai.",
    f: ["Tiny, olive-green.", "Yellow (female) or orange-yellow (male) crown stripe bordered black.", "Two white wing bars.", "Plain face with a dark eye."],
    si: "Pallas’s Leaf Warbler — yellow rump, eyebrow.",
    h: "Spruce and fir forests.",
    di: "Ulaanbaatar (Bogd Khan Uul), Khurkh, Terelj, Khar Us Nuur, Khövsgöl.",
    mi: "Resident; some migrate.",
    fo: "Tiny insects and spiders.",
    br: "Hanging nest in conifers; 7–10 eggs.",
    be: "Hovers at branch tips.",
    v: "A very high ‘see-see-see’.",
    cu: "Weighs about the same as a 5-gram coin.",
    co: "Least Concern.",
    w: "Spruce trees on Bogd Khan Uul.",
    bt: "all year",
    fa: ["Smallest bird in Mongolia.", "Golden crown.", "Hanging nest."]
  },
  "long-tailed-tit": {
    T: { c: { white: 0.6, black: 0.25, gray: 0.1, rufous: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["13–15 cm", "16–19 cm", "7–9 g"] },
    s: "A tiny fluffy ball with a very long tail; the northern form has a pure white head. Flocks roam woods and parks, especially in Ulaanbaatar.",
    d: "The Long-tailed Tit lives across Eurasia. The Siberian form (caudatus) has a snow-white head. It builds a domed nest of moss and spider silk lined with thousands of feathers. In Mongolia it is common in winter around Ulaanbaatar, Terelj and the Khurkh valley.",
    f: ["Tiny round body, very long tail.", "White head (northern form).", "Black and pinkish back.", "Tiny bill."],
    si: "Unmistakable.",
    h: "Woods, river thickets and parks.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Khövsgöl, Buir Nuur.",
    mi: "Resident; roams in winter.",
    fo: "Tiny insects and spiders.",
    br: "Domed feather-lined nest; 8–12 eggs.",
    be: "Travels in chattering flocks; roosts huddled together.",
    v: "Thin ‘see-see’ and rattling ‘trrr’.",
    cu: "Its nest may contain over 2,000 feathers.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in winter.",
    bt: "October–March",
    fa: ["White head.", "Feather-lined nest.", "Huddles to keep warm."]
  },
  "penduline-tit": {
    T: { c: { gray: 0.35, rufous: 0.3, black: 0.2, buff: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["passage"], sz: ["10–11 cm", "—", "8–10 g"] },
    s: "A tiny tit with a black mask that weaves a hanging, bottle-shaped nest. A very rare visitor.",
    d: "The Chinese Penduline Tit breeds in north-east China and south-east Siberia. It builds a felted nest with a spout entrance hanging from willow twigs. One record exists from Terelj.",
    f: ["Black mask (male).", "Grey head, chestnut back.", "Tiny pointed bill."],
    si: "Unmistakable.",
    h: "Reedbeds and willows.",
    di: "Very rare; Terelj.",
    mi: "Vagrant.",
    fo: "Insects and seeds.",
    br: "Hanging woven nest.",
    be: "Hangs acrobatically in reeds.",
    v: "A thin ‘tsee’.",
    cu: "Its felted nests were once used as children’s slippers.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Hanging nest.", "Black mask.", "Very rare."]
  },
  "bearded-reedling": {
    T: { c: { rufous: 0.45, gray: 0.25, black: 0.15, white: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["14–15.5 cm", "16–18 cm", "12–18 g"] },
    s: "A tawny, long-tailed reed bird; the male has a blue-grey head and a black ‘moustache’. Resident in reedbeds, especially at Khar Us Nuur.",
    d: "The Bearded Reedling lives in large reedbeds from Europe to eastern Asia. It changes its diet from insects in summer to reed seeds in winter. In Mongolia it is common at Khar Us Nuur and other reedy lakes (Orog Nuur, Buir Nuur).",
    f: ["Tawny body, long tail.", "Male: blue-grey head with black moustache.", "Orange-yellow bill.", "Female: plain tawny head."],
    si: "Unmistakable.",
    h: "Large reedbeds.",
    di: "Khar Us Nuur, Orog Nuur, Achit Nuur, Taatsiin Tsagaan, Böön Tsagaan, Buir Nuur.",
    mi: "Resident.",
    fo: "Insects in summer, reed seeds in winter.",
    br: "Nests low in reeds; 4–8 eggs.",
    be: "Climbs reeds; moves in flocks.",
    v: "A ringing ‘ping-ping’.",
    cu: "Not a true tit — it is in its own family.",
    co: "Least Concern.",
    w: "Khar Us Nuur reeds.",
    bt: "all year",
    fa: ["Black moustache.", "Own family.", "Switches diet in winter."]
  },
  "eurasian-nuthatch": {
    T: { c: { gray: 0.45, white: 0.3, black: 0.15, rufous: 0.1 }, hb: ["forest", "settlement"], bk: "long", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["12–14.5 cm", "22–27 cm", "17–28 g"] },
    s: "A compact blue-grey bird with a black eye-stripe that climbs down tree trunks head-first. Common in northern forests and Ulaanbaatar parks.",
    d: "The Eurasian Nuthatch lives across Eurasia. The Siberian form has white underparts. It wedges seeds into bark and hammers them open. In Mongolia it is common in the Khentii and Khangai forests and visits feeders in Ulaanbaatar.",
    f: ["Blue-grey upperparts.", "Black eye-stripe.", "White underparts (Siberian form).", "Strong, pointed bill.", "Short tail; climbs head-down."],
    si: "Eurasian Treecreeper — brown, climbs upwards.",
    h: "Forests and parks.",
    di: "Ulaanbaatar, Terelj, Khurkh, Orkhon, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Resident.",
    fo: "Insects, seeds and nuts.",
    br: "Nests in holes, plastering the entrance with mud.",
    be: "Climbs head-first down trunks.",
    v: "A loud ‘twit-twit’.",
    cu: "Narrows its nest entrance with mud to keep out larger birds.",
    co: "Least Concern.",
    w: "Bogd Khan Uul and city parks.",
    bt: "all year",
    fa: ["Climbs head-down.", "Plasters its nest with mud.", "Common in Ulaanbaatar."]
  },
  "wallcreeper": {
    T: { c: { gray: 0.45, red: 0.3, black: 0.2, white: 0.05 }, hb: ["mountain"], bk: "curved", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["15.5–17 cm", "27–32 cm", "15–22 g"] },
    s: "A grey cliff bird that flicks open crimson wings like a butterfly. A prized sighting at Yolyn Am.",
    d: "The Wallcreeper lives on cliffs in mountains from Spain to China. It creeps up rock faces, flicking its wings to show red patches. In Mongolia it is found in the Gobi-Altai gorges, especially Yolyn Am, and the Altai.",
    f: ["Grey body.", "Broad wings with crimson panels and white spots.", "Long, curved black bill.", "Black throat in summer."],
    si: "Unmistakable.",
    h: "Cliffs and gorges.",
    di: "Yolyn Am, Khar Us Nuur, Terelj, Tavan Bogd.",
    mi: "Resident; descends in winter.",
    fo: "Insects and spiders from rock crevices.",
    br: "Nests deep in rock crevices.",
    be: "Flutters like a butterfly on cliffs.",
    v: "A thin, rising whistle.",
    cu: "Called ‘butterfly bird’ in several languages.",
    co: "Least Concern.",
    w: "Yolyn Am cliffs.",
    bt: "all year",
    fa: ["Crimson wings.", "Flutters like a butterfly.", "Lives on cliffs."]
  },
  "eurasian-treecreeper": {
    T: { c: { brown: 0.5, white: 0.35, buff: 0.15 }, hb: ["forest"], bk: "curved", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["12.5 cm", "17–21 cm", "8–12 g"] },
    s: "A small, mouse-like brown bird with a thin curved bill that spirals up tree trunks. Resident in northern forests.",
    d: "The Eurasian Treecreeper lives across Eurasia. It uses its stiff tail as a prop while climbing. In Mongolia it lives in the Khentii (Bogd Khan Uul, Terelj), Khangai and Khövsgöl forests.",
    f: ["Streaked brown upperparts.", "White underparts.", "Thin, down-curved bill.", "Stiff pointed tail."],
    si: "Eurasian Nuthatch — blue-grey, climbs head-down.",
    h: "Mature forests.",
    di: "Ulaanbaatar (Bogd Khan Uul), Terelj, Khövsgöl, Orkhon, Ganga Nuur.",
    mi: "Resident.",
    fo: "Insects from bark.",
    br: "Nests behind loose bark.",
    be: "Spirals up a trunk, then flies to the base of the next.",
    v: "A thin, high ‘tsee’.",
    cu: "Roosts in groups in crevices on cold nights.",
    co: "Least Concern.",
    w: "Bogd Khan Uul forests.",
    bt: "all year",
    fa: ["Climbs in spirals.", "Stiff tail.", "Mouse-like."]
  }
});
