B2T("fr", {
  "alpine-accentor": {
    name: "Accenteur alpin",
    s: "Oiseau de montagne ressemblant à un moineau, à tête grise, gorge tachetée et flancs striés de marron. Résident des pentes rocheuses élevées.",
    d: "L’Accenteur alpin vit en haute montagne, de l’Espagne au Japon. En Mongolie, il vit sur les sommets rocheux de l’Altaï du Gobi (Yolyn Am), de l’Altaï, du Khangaï et près d’Oulan-Bator, descendant en hiver.",
    f: ["Tête et poitrine grises.", "Gorge tachetée de noir et de blanc.", "Flancs striés de marron.", "Couvertures alaires noires à pointes blanches."],
    si: "Accenteur de l’Himalaya — gorge blanche bordée de noir.",
    h: "Pentes rocheuses et éboulis d’altitude.",
    di: "Yolyn Am, Oulan-Bator (Bogd Khan Uul), Terelj, Terkhiin Tsagaan Nuur, lac Khar Us, Ölgii.",
    mi: "Résident ; descend en hiver.",
    fo: "Insectes en été, graines en hiver.",
    br: "Niche dans les fissures ; reproduction en groupe complexe.",
    be: "Très confiant ; se faufile entre les rochers.",
    v: "Un chant roulé d’alouette.",
    cu: "Les femelles s’accouplent avec plusieurs mâles qui nourrissent tous les poussins.",
    co: "Préoccupation mineure.",
    w: "Rochers de Yolyn Am.",
    bt: "toute l’année",
    fa: ["Gorge tachetée.", "Vit au-dessus de la limite des arbres.", "Reproduction en groupe."]
  },
  "altai-accentor": {
    name: "Accenteur de l’Himalaya",
    s: "Accenteur à tête grise, gorge blanche encadrée de noir et poitrine tachetée de roux. Niche sur les pentes alpines de l’Altaï et du Khangaï.",
    d: "L’Accenteur de l’Himalaya niche dans l’Altaï, les Saïan et le Tian Shan et hiverne dans l’Himalaya. En Mongolie, il niche sur les hautes pentes autour du lac Khar Us, d’Ölgii et de Tavan Bogd, et dans le Khangaï.",
    f: ["Tête grise.", "Gorge blanche bordée d’une bande noire.", "Poitrine tachetée de roux.", "Dos strié."],
    si: "Accenteur alpin — gorge tachetée, poitrine grise.",
    h: "Prairies alpines et éboulis.",
    di: "Lac Khar Us, lac Orog, Ölgii, Tavan Bogd, Terkhiin Tsagaan Nuur.",
    mi: "Visiteur d’été ; quelques hivernants.",
    fo: "Insectes et graines.",
    br: "Niche parmi les rochers.",
    be: "Se nourrit au sol en groupes.",
    v: "Un fin trille.",
    cu: "Aussi appelé Accenteur de l’Altaï.",
    co: "Préoccupation mineure.",
    w: "Cols de l’Altaï en été.",
    bt: "juin–août",
    fa: ["Gorge blanche.", "Oiseau alpin.", "Hiverne dans l’Himalaya."]
  },
  "siberian-accentor": {
    name: "Accenteur montanelle",
    s: "Petit accenteur au sourcil et à la gorge ocre vif et au masque noir. Migrateur et hivernant, surtout dans le nord.",
    d: "L’Accenteur montanelle niche dans la taïga sibérienne et hiverne en Chine et en Corée. En Mongolie, il est commun en migration et en hiver autour d’Oulan-Bator, de la vallée de Khurkh et de Yolyn Am.",
    f: ["Sourcil et gorge ocre vif.", "Côtés de la calotte et masque noirs.", "Dos brun strié.", "Tache grise sur le cou."],
    si: "Accenteur brun — plus pâle, sourcil blanc.",
    h: "Broussailles et lisières.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Terelj, lac Ganga.",
    mi: "Migrateur et hivernant, octobre–avril.",
    fo: "Graines et insectes.",
    br: "Niche dans la taïga sibérienne.",
    be: "Se faufile sous les buissons.",
    v: "Un fin « tsii-sii ».",
    cu: "Est récemment apparu en Europe lors d’invasions.",
    co: "Préoccupation mineure.",
    w: "Bords du Bogd Khan Uul en octobre.",
    bt: "oct.–nov.",
    fa: ["Sourcil ocre.", "Masque noir.", "Hivernant."]
  },
  "brown-accentor": {
    name: "Accenteur brun",
    s: "Accenteur sable pâle au sourcil blanchâtre et masque sombre. Commun dans les gorges rocheuses du Gobi et de l’ouest.",
    d: "L’Accenteur brun vit dans les montagnes sèches d’Asie centrale. En Mongolie, il est commun dans les gorges rocheuses — Yolyn Am, lac Khar Us, Ölgii, lac Orog — et près d’Oulan-Bator en hiver.",
    f: ["Sourcil blanchâtre.", "Masque brun foncé.", "Dessous chamois pâle.", "Dos brun strié."],
    si: "Accenteur montanelle — sourcil ocre. Accenteur de Koslov — plus gris, uni.",
    h: "Gorges rocheuses et broussailles des montagnes sèches.",
    di: "Yolyn Am, lac Khar Us, Oulan-Bator, Ölgii, lac Orog, Terkhiin Tsagaan Nuur.",
    mi: "Résident ; descend en hiver.",
    fo: "Insectes et graines.",
    br: "Niche dans les buissons entre les rochers.",
    be: "Sautille entre les rochers.",
    v: "Un court chant trillé.",
    cu: "Très commun à Yolyn Am.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en toute saison.",
    bt: "toute l’année",
    fa: ["Sourcil blanc.", "Montagnes sèches.", "Commun à Yolyn Am."]
  },
  "black-throated-accentor": {
    name: "Accenteur à gorge noire",
    s: "Accenteur à gorge et masque noirs et sourcil chamois. Niche dans les broussailles de montagne de l’extrême ouest.",
    d: "L’Accenteur à gorge noire niche dans les montagnes d’Asie centrale et hiverne dans les vallées. En Mongolie, il niche surtout dans l’Altaï autour du lac Khar Us.",
    f: ["Gorge et masque noirs.", "Sourcil et poitrine chamois.", "Dos brun strié."],
    si: "Accenteur montanelle — sans gorge noire.",
    h: "Genévriers et broussailles de montagne.",
    di: "Lac Khar Us, Ölgii, lac Achit.",
    mi: "Visiteur d’été.",
    fo: "Insectes et graines.",
    br: "Niche dans les buissons.",
    be: "Discret dans les arbustes.",
    v: "Un chant fin et gazouillé.",
    cu: "Une spécialité de l’ouest mongol.",
    co: "Préoccupation mineure.",
    w: "Genévriers près du lac Khar Us.",
    bt: "juin",
    fa: ["Gorge noire.", "Genévriers.", "Oiseau de l’ouest."]
  },
  "mongolian-accentor": {
    name: "Accenteur de Koslov",
    s: "Accenteur gris-brun uni présent presque uniquement dans les montagnes du Gobi mongol. Quasi-endémique, commun à Yolyn Am.",
    d: "L’Accenteur de Koslov vit presque entièrement en Mongolie et dans le nord de la Chine voisine, dans les broussailles des montagnes sèches. En Mongolie, il est commun à Yolyn Am et dans d’autres gorges de l’Altaï du Gobi, ainsi que dans l’ouest.",
    f: ["Gris-brun uni finement strié.", "Gorge pâle.", "Pas de dessin facial marqué.", "Dos strié."],
    si: "Accenteur brun — sourcil blanc et masque sombre.",
    h: "Broussailles et gorges des montagnes sèches.",
    di: "Yolyn Am, lac Khar Us, Taatsiin Tsagaan, lac Orog, Oulan-Bator (hiver), Terelj.",
    mi: "Résident ; déplacements locaux.",
    fo: "Graines et insectes.",
    br: "Niche dans les buissons.",
    be: "Discret.",
    v: "Un doux gazouillis.",
    cu: "Nommé d’après l’explorateur russe Piotr Kozlov.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "toute l’année",
    fa: ["Presque endémique de Mongolie.", "Nommé d’après Kozlov.", "Couleur unie."]
  },
  "eurasian-wren": {
    name: "Troglodyte mignon",
    s: "Minuscule oiseau brun et rond à queue dressée et au chant étonnamment puissant. Peu commun dans les forêts du nord et de l’est.",
    d: "Le Troglodyte mignon vit dans toute l’Eurasie. C’est l’un des plus petits oiseaux mais aussi l’un des plus sonores. En Mongolie, il est peu commun, noté dans la vallée de Khurkh, à Oulan-Bator, au lac Buir et à Terelj.",
    f: ["Minuscule et rond.", "Courte queue dressée.", "Brun finement barré.", "Sourcil pâle."],
    si: "Inconfondable.",
    h: "Sous-bois denses près de l’eau.",
    di: "Khurkh, Oulan-Bator, lac Buir, Terelj, Yolyn Am, lac Ganga.",
    mi: "Résident ; certains se déplacent.",
    fo: "Petits insectes et araignées.",
    br: "Nid en dôme ; le mâle en construit plusieurs.",
    be: "Se faufile comme une souris.",
    v: "Un chant trillé très fort et rapide.",
    cu: "« Roi des oiseaux » dans le folklore européen.",
    co: "Préoccupation mineure.",
    w: "Fourrés riverains de la vallée de Khurkh.",
    bt: "toute l’année",
    fa: ["Minuscule mais bruyant.", "Queue dressée.", "Le mâle bâtit plusieurs nids."]
  },
  "goldcrest": {
    name: "Roitelet huppé",
    s: "Le plus petit oiseau de Mongolie — vert olive avec une bande dorée sur la calotte bordée de noir. Vit dans les forêts d’épicéas.",
    d: "Le Roitelet huppé vit dans les forêts de conifères d’Eurasie. Il pèse autant qu’une pièce de monnaie. En Mongolie, il vit dans les pessières du Khentii (Bogd Khan Uul, Terelj, Khurkh) et de l’Altaï.",
    f: ["Minuscule, vert olive.", "Bande jaune (femelle) ou orange-jaune (mâle) sur la calotte, bordée de noir.", "Deux barres alaires blanches.", "Face unie à œil sombre."],
    si: "Pouillot de Pallas — croupion jaune, sourcil.",
    h: "Forêts d’épicéas et de sapins.",
    di: "Oulan-Bator (Bogd Khan Uul), Khurkh, Terelj, lac Khar Us, Khövsgöl.",
    mi: "Résident ; certains migrent.",
    fo: "Minuscules insectes et araignées.",
    br: "Nid suspendu dans les conifères ; 7 à 10 œufs.",
    be: "Fait du surplace au bout des rameaux.",
    v: "Un « sii-sii-sii » très aigu.",
    cu: "Pèse environ autant qu’une pièce de 5 grammes.",
    co: "Préoccupation mineure.",
    w: "Épicéas du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Plus petit oiseau de Mongolie.", "Couronne dorée.", "Nid suspendu."]
  },
  "long-tailed-tit": {
    name: "Mésange à longue queue",
    s: "Minuscule boule duveteuse à très longue queue ; la forme nordique a la tête d’un blanc pur. Des groupes parcourent bois et parcs, surtout à Oulan-Bator.",
    d: "La Mésange à longue queue vit dans toute l’Eurasie. La forme sibérienne (caudatus) a la tête blanc neige. Elle construit un nid en dôme de mousse et de soie d’araignée, garni de milliers de plumes. En Mongolie, elle est commune en hiver autour d’Oulan-Bator, de Terelj et de la vallée de Khurkh.",
    f: ["Minuscule corps rond, très longue queue.", "Tête blanche (forme nordique).", "Dos noir et rosé.", "Bec minuscule."],
    si: "Inconfondable.",
    h: "Bois, fourrés riverains et parcs.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Khövsgöl, lac Buir.",
    mi: "Résidente ; erratique en hiver.",
    fo: "Minuscules insectes et araignées.",
    br: "Nid en dôme garni de plumes ; 8 à 12 œufs.",
    be: "Voyage en groupes bavards ; dort serrée contre ses congénères.",
    v: "Des « sii-sii » fins et un « trrr » roulé.",
    cu: "Son nid peut contenir plus de 2 000 plumes.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en hiver.",
    bt: "oct.–mars",
    fa: ["Tête blanche.", "Nid garni de plumes.", "Se serre pour garder la chaleur."]
  },
  "penduline-tit": {
    name: "Rémiz de Chine",
    s: "Minuscule mésange à masque noir qui tisse un nid suspendu en forme de bouteille. Visiteur très rare.",
    d: "Le Rémiz de Chine niche dans le nord-est de la Chine et le sud-est de la Sibérie. Il construit un nid feutré à entrée en bec suspendu aux rameaux de saule. Une mention existe à Terelj.",
    f: ["Masque noir (mâle).", "Tête grise, dos marron.", "Minuscule bec pointu."],
    si: "Inconfondable.",
    h: "Roselières et saules.",
    di: "Très rare ; Terelj.",
    mi: "Erratique.",
    fo: "Insectes et graines.",
    br: "Nid tissé suspendu.",
    be: "Se suspend acrobatiquement dans les roseaux.",
    v: "Un fin « tsii ».",
    cu: "Ses nids feutrés servaient autrefois de chaussons d’enfant.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Nid suspendu.", "Masque noir.", "Très rare."]
  },
  "bearded-reedling": {
    name: "Panure à moustaches",
    s: "Oiseau fauve à longue queue des roselières ; le mâle a la tête gris-bleu et une « moustache » noire. Résident des roselières, surtout au lac Khar Us.",
    d: "La Panure à moustaches vit dans les grandes roselières, de l’Europe à l’Asie orientale. Elle passe d’un régime d’insectes en été aux graines de roseau en hiver. En Mongolie, elle est commune au lac Khar Us et sur d’autres lacs à roseaux (lac Orog, lac Buir).",
    f: ["Corps fauve, longue queue.", "Mâle : tête gris-bleu à moustache noire.", "Bec jaune orangé.", "Femelle : tête fauve unie."],
    si: "Inconfondable.",
    h: "Grandes roselières.",
    di: "Lac Khar Us, lac Orog, lac Achit, Taatsiin Tsagaan, Böön Tsagaan, lac Buir.",
    mi: "Résidente.",
    fo: "Insectes en été, graines de roseau en hiver.",
    br: "Niche bas dans les roseaux ; 4 à 8 œufs.",
    be: "Grimpe aux roseaux ; se déplace en groupes.",
    v: "Un « ping-ping » sonore.",
    cu: "Ce n’est pas une vraie mésange — elle forme sa propre famille.",
    co: "Préoccupation mineure.",
    w: "Roseaux du lac Khar Us.",
    bt: "toute l’année",
    fa: ["Moustache noire.", "Famille à part.", "Change de régime en hiver."]
  },
  "eurasian-nuthatch": {
    name: "Sittelle torchepot",
    s: "Oiseau compact gris-bleu à trait oculaire noir qui descend les troncs tête en bas. Commune dans les forêts du nord et les parcs d’Oulan-Bator.",
    d: "La Sittelle torchepot vit dans toute l’Eurasie. La forme sibérienne a le dessous blanc. Elle coince des graines dans l’écorce pour les casser à coups de bec. En Mongolie, elle est commune dans les forêts du Khentii et du Khangaï et visite les mangeoires d’Oulan-Bator.",
    f: ["Dessus gris-bleu.", "Trait oculaire noir.", "Dessous blanc (forme sibérienne).", "Bec fort et pointu.", "Queue courte ; descend tête en bas."],
    si: "Grimpereau des bois — brun, grimpe vers le haut.",
    h: "Forêts et parcs.",
    di: "Oulan-Bator, Terelj, Khurkh, Orkhon, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Résidente.",
    fo: "Insectes, graines et noix.",
    br: "Niche dans une cavité dont elle réduit l’entrée avec de la boue.",
    be: "Descend les troncs tête la première.",
    v: "Un « touit-touit » sonore.",
    cu: "Maçonne l’entrée de son nid pour en exclure les oiseaux plus grands.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul et parcs de la ville.",
    bt: "toute l’année",
    fa: ["Descend tête en bas.", "Maçonne son nid.", "Commune à Oulan-Bator."]
  },
  "wallcreeper": {
    name: "Tichodrome échelette",
    s: "Oiseau gris des falaises qui ouvre ses ailes cramoisies comme un papillon. Une observation recherchée à Yolyn Am.",
    d: "Le Tichodrome échelette vit sur les falaises des montagnes, de l’Espagne à la Chine. Il grimpe sur les parois en agitant les ailes pour montrer ses taches rouges. En Mongolie, on le trouve dans les gorges de l’Altaï du Gobi, surtout à Yolyn Am, et dans l’Altaï.",
    f: ["Corps gris.", "Ailes larges à panneaux cramoisis et taches blanches.", "Long bec noir arqué.", "Gorge noire en été."],
    si: "Inconfondable.",
    h: "Falaises et gorges.",
    di: "Yolyn Am, lac Khar Us, Terelj, Tavan Bogd.",
    mi: "Résident ; descend en hiver.",
    fo: "Insectes et araignées des fissures.",
    br: "Niche au fond des fissures rocheuses.",
    be: "Voltige comme un papillon sur les falaises.",
    v: "Un fin sifflement montant.",
    cu: "Appelé « oiseau-papillon » dans plusieurs langues.",
    co: "Préoccupation mineure.",
    w: "Falaises de Yolyn Am.",
    bt: "toute l’année",
    fa: ["Ailes cramoisies.", "Voltige comme un papillon.", "Vit sur les falaises."]
  },
  "eurasian-treecreeper": {
    name: "Grimpereau des bois",
    s: "Petit oiseau brun comme une souris, au bec fin arqué, qui monte en spirale le long des troncs. Résident des forêts du nord.",
    d: "Le Grimpereau des bois vit dans toute l’Eurasie. Il s’appuie sur sa queue raide pour grimper. En Mongolie, il vit dans les forêts du Khentii (Bogd Khan Uul, Terelj), du Khangaï et du Khövsgöl.",
    f: ["Dessus brun strié.", "Dessous blanc.", "Bec fin et arqué.", "Queue raide et pointue."],
    si: "Sittelle torchepot — gris-bleu, descend tête en bas.",
    h: "Forêts matures.",
    di: "Oulan-Bator (Bogd Khan Uul), Terelj, Khövsgöl, Orkhon, lac Ganga.",
    mi: "Résident.",
    fo: "Insectes de l’écorce.",
    br: "Niche derrière l’écorce décollée.",
    be: "Monte en spirale puis vole au pied de l’arbre suivant.",
    v: "Un fin « tsii » aigu.",
    cu: "Dort en groupe dans des fissures par grand froid.",
    co: "Préoccupation mineure.",
    w: "Forêts du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Grimpe en spirale.", "Queue raide.", "Comme une souris."]
  }
});
