B2T("en", {
  "eurasian-blackcap": {
    T: { c: { gray: 0.55, black: 0.2, brown: 0.15, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["13–15 cm", "20–23 cm", "16–25 g"] },
    s: "A grey warbler; the male has a neat black cap, the female a brown one. A very rare visitor.",
    d: "The Eurasian Blackcap breeds from Europe to western Siberia and winters in Africa and Europe. In Mongolia it has been recorded in the Khurkh valley.",
    f: ["Grey body.", "Black cap (male) or brown cap (female).", "Plain wings."],
    si: "Marsh and Willow Tits — black bib, not warblers.",
    h: "Woods with undergrowth.",
    di: "Very rare; Khurkh.",
    mi: "Vagrant.",
    fo: "Insects and berries.",
    br: "Nests in shrubs (not in Mongolia).",
    be: "Skulks in bushes.",
    v: "A rich, fluty song.",
    cu: "Some now winter in Britain instead of Africa.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Black cap.", "Fluty song.", "Very rare in Mongolia."]
  },
  "asian-desert-warbler": {
    T: { c: { buff: 0.5, gray: 0.3, rufous: 0.15, yellow: 0.05 }, hb: ["desert"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["11.5–12.5 cm", "—", "8–10 g"] },
    s: "A small, pale sandy warbler with a rusty tail and yellow eye that often runs on the ground. Common in Gobi saxaul and scrub.",
    d: "The Asian Desert Warbler breeds in Central Asian deserts and winters in the Middle East and India. It often follows wheatears. In Mongolia it is common in desert scrub — Khar Us Nuur, Orog Nuur, Böön Tsagaan and Taatsiin Tsagaan.",
    f: ["Pale sandy-grey.", "Rufous tail.", "Yellow eye and legs.", "Often runs on the ground."],
    si: "Lesser Whitethroat — grey, white throat, dark mask.",
    h: "Desert scrub and saxaul.",
    di: "Khar Us Nuur, Orog Nuur, Böön Tsagaan, Taatsiin Tsagaan, Yolyn Am.",
    mi: "Summer visitor, April–September.",
    fo: "Insects.",
    br: "Nests in low shrubs.",
    be: "Follows wheatears to catch disturbed insects.",
    v: "A jingling song.",
    cu: "Commonly associates with Desert Wheatears.",
    co: "Least Concern.",
    w: "Saxaul near Orog Nuur in May.",
    bt: "May–July",
    fa: ["Rufous tail.", "Runs on the ground.", "Follows wheatears."]
  },
  "barred-warbler": {
    T: { c: { gray: 0.5, white: 0.35, black: 0.1, yellow: 0.05 }, hb: ["forest", "desert"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15.5–17 cm", "—", "22–36 g"] },
    s: "A large grey warbler with a fierce yellow eye and crescent bars on the underparts. A summer visitor to scrub in the west and Gobi.",
    d: "The Barred Warbler breeds from central Europe to Mongolia and winters in East Africa. It often nests near shrikes. In Mongolia it breeds in thorny scrub at Yolyn Am, Khar Us Nuur and Achit Nuur.",
    f: ["Grey upperparts.", "Dark crescent barring on white underparts.", "Yellow eye.", "White wing bars."],
    si: "Lesser Whitethroat — smaller, plain below.",
    h: "Thorny scrub and forest edges.",
    di: "Yolyn Am, Khar Us Nuur, Orog Nuur, Achit Nuur, Ölgii.",
    mi: "Summer visitor, May–August.",
    fo: "Insects and berries.",
    br: "Nests in thorny bushes, often near shrikes.",
    be: "Skulks; sings in flight.",
    v: "A scratchy song.",
    cu: "Nests near shrikes for protection.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "June",
    fa: ["Barred underparts.", "Yellow eye.", "Nests near shrikes."]
  },
  "lesser-whitethroat": {
    T: { c: { gray: 0.45, white: 0.35, brown: 0.15, black: 0.05 }, hb: ["forest", "desert", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12.5–13.5 cm", "—", "10–16 g"] },
    s: "A neat grey-brown warbler with a white throat and dark ear patch. Common in scrub across Mongolia, including desert forms.",
    d: "The Lesser Whitethroat breeds from Europe to Mongolia. Several forms occur, including the pale desert form ‘halimodendri’. In Mongolia it is common in shrubs — Ulaanbaatar, Terelj, the Khurkh valley and Khar Us Nuur.",
    f: ["Grey-brown back.", "White throat.", "Dark grey ear coverts.", "Dark legs."],
    si: "Common Whitethroat — rufous wings. Asian Desert Warbler — sandy, rufous tail.",
    h: "Shrubs, forest edges and desert scrub.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Yolyn Am, Khustai.",
    mi: "Summer visitor, May–September.",
    fo: "Insects and berries.",
    br: "Nests in bushes.",
    be: "Skulks in thick cover.",
    v: "A dry rattle after a soft warble.",
    cu: "Migrates southeast rather than south.",
    co: "Least Concern.",
    w: "Terelj shrubs in June.",
    bt: "June–July",
    fa: ["White throat.", "Dark ear patch.", "Common."]
  },
  "common-whitethroat": {
    T: { c: { gray: 0.35, brown: 0.3, rufous: 0.2, white: 0.15 }, hb: ["steppe", "forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–15 cm", "18–23 cm", "12–18 g"] },
    s: "A lively warbler with a white throat and rusty wing panels, singing from bush tops. Common in scrub in the north and west.",
    d: "The Common Whitethroat breeds from Europe to Mongolia and winters in Africa. In Mongolia it breeds in shrubby steppe and forest edges — Khurkh, Ulaanbaatar, Yolyn Am and Terelj.",
    f: ["White throat, puffed when singing.", "Rufous wing panels.", "Grey head (male).", "Pale legs."],
    si: "Lesser Whitethroat — no rufous wings, dark ear patch.",
    h: "Scrub, hedges and forest edges.",
    di: "Khurkh, Ulaanbaatar, Yolyn Am, Terelj, Khar Us Nuur, Khustai.",
    mi: "Summer visitor, May–September.",
    fo: "Insects and berries.",
    br: "Nests low in bushes.",
    be: "Song flight from bush tops.",
    v: "A scratchy, fast warble.",
    cu: "A typical bird of scrubby edges.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "June",
    fa: ["Rusty wings.", "White throat.", "Song flight."]
  },
  "chinese-hill-warbler": {
    T: { c: { brown: 0.45, white: 0.3, rufous: 0.15, gray: 0.1 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["16–17 cm", "—", "15–20 g"] },
    s: "A long-tailed, streaky babbler-like warbler of dry Chinese hills. On the Mongolian list, with no GBIF records.",
    d: "The Chinese Hill Warbler lives in dry scrubby hills of northern China. Records in Mongolia are exceptional.",
    f: ["Streaked brown back.", "Long graduated tail.", "White underparts with chestnut flank streaks."],
    si: "Unmistakable in Mongolia.",
    h: "Dry scrubby hills.",
    di: "Exceptional.",
    mi: "Resident near the border.",
    fo: "Insects and seeds.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Runs on the ground.",
    v: "A ringing song.",
    cu: "Also called the Beijing Babbler.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Long tail.", "Chinese species.", "Runs on the ground."]
  },
  "reed-parrotbill": {
    T: { c: { gray: 0.35, buff: 0.35, black: 0.15, yellow: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["18–20 cm", "—", "20–25 g"] },
    s: "A long-tailed reed bird with a thick yellow parrot-like bill and black eyebrow. Rare in reedbeds of far eastern Mongolia.",
    d: "The Reed Parrotbill lives in reedbeds of eastern China and far eastern Mongolia. It is Near Threatened because of reed harvesting. In Mongolia it is known from reedbeds in Dornod (Buir Nuur, Khalkh River).",
    f: ["Thick yellow bill.", "Grey head with a black eyebrow.", "Buff body, long tail."],
    si: "Bearded Reedling — thin bill.",
    h: "Reedbeds.",
    di: "Dornod (Buir Nuur, Khalkh River).",
    mi: "Resident.",
    fo: "Insects from reed stems.",
    br: "Nests in reeds.",
    be: "Tears open reed stems.",
    v: "A ringing ‘chew’.",
    cu: "Depends on uncut reedbeds.",
    co: "Near Threatened.",
    w: "Buir Nuur reeds.",
    bt: "all year",
    fa: ["Parrot-like bill.", "Tears open reeds.", "Near Threatened."]
  },
  "vinous-throated-parrotbill": {
    T: { c: { brown: 0.5, rufous: 0.3, buff: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["resident"], sz: ["11–13 cm", "—", "9–12 g"] },
    s: "A tiny, round brown bird with a stubby bill and long tail. On the Mongolian list, with no GBIF records.",
    d: "The Vinous-throated Parrotbill lives in scrub of China and Korea in noisy flocks. Records in Mongolia are exceptional.",
    f: ["Tiny, rufous-brown.", "Short stubby bill.", "Long tail."],
    si: "Long-tailed Tit — white head.",
    h: "Scrub and grass.",
    di: "Exceptional.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Nests in bushes.",
    be: "Moves in noisy flocks.",
    v: "Constant twittering.",
    cu: "Common in Korean gardens.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Stubby bill.", "Flocks.", "Tiny."]
  },
  "coal-tit": {
    T: { c: { black: 0.35, gray: 0.35, white: 0.25, buff: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["10–11.5 cm", "17–21 cm", "8–10 g"] },
    s: "A tiny tit with a black cap, white cheeks and a white nape patch. Common in conifer forests and Ulaanbaatar parks.",
    d: "The Coal Tit lives in conifer forests across Eurasia. It stores seeds in bark crevices. In Mongolia it is common in the Khentii — Ulaanbaatar, Terelj, the Khurkh valley.",
    f: ["Black cap and bib.", "White cheeks.", "White patch on the nape.", "Two white wing bars."],
    si: "Great Tit — yellow belly. Willow Tit — no nape patch.",
    h: "Coniferous forests and parks.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Khövsgöl, Yolyn Am.",
    mi: "Resident.",
    fo: "Insects and conifer seeds.",
    br: "Nests in holes; 7–10 eggs.",
    be: "Stores food for winter.",
    v: "A high ‘weechoo-weechoo’.",
    cu: "Visits bird feeders in Ulaanbaatar.",
    co: "Least Concern.",
    w: "Bogd Khan Uul forests.",
    bt: "all year",
    fa: ["White nape patch.", "Stores food.", "Smallest tit in Mongolia."]
  },
  "marsh-tit": {
    T: { c: { brown: 0.4, black: 0.2, white: 0.3, gray: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["11.5–13 cm", "18–19 cm", "10–13 g"] },
    s: "A small tit with a glossy black cap and small black bib. Resident in deciduous woods of the north.",
    d: "The Marsh Tit lives in deciduous woods across Eurasia. In Mongolia it is found in the Khentii (Ulaanbaatar, Terelj, Khurkh) and Khövsgöl.",
    f: ["Glossy black cap.", "Small black bib.", "Plain brown back.", "Pale cheeks."],
    si: "Willow Tit — matt cap, pale wing panel.",
    h: "Deciduous and mixed woods.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khövsgöl, Orkhon, Onon.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Nests in holes.",
    be: "Caches seeds.",
    v: "A sneezing ‘pitchoo’.",
    cu: "Despite its name it avoids marshes.",
    co: "Least Concern.",
    w: "Bogd Khan Uul.",
    bt: "all year",
    fa: ["Glossy cap.", "‘Pitchoo’ call.", "Avoids marshes."]
  },
  "willow-tit": {
    T: { c: { brown: 0.35, black: 0.25, white: 0.35, gray: 0.05 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["11.5 cm", "17–20 cm", "9–12 g"] },
    s: "A small tit with a sooty-black cap and white cheeks; the northern form is very pale. Common in northern forests and Ulaanbaatar.",
    d: "The Willow Tit lives across the boreal forests of Eurasia. It excavates its own nest hole in rotten wood. In Mongolia it is very common in the Khentii and Khangai — Ulaanbaatar, Terelj, Orkhon.",
    f: ["Sooty-black cap.", "Large white cheeks.", "Pale wing panel.", "Pale grey-buff flanks."],
    si: "Marsh Tit — glossy cap. Siberian Tit — brown cap.",
    h: "Coniferous and mixed forest.",
    di: "Ulaanbaatar, Terelj, Khurkh, Orkhon, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Digs its own hole in rotten wood.",
    be: "Hoards thousands of seeds.",
    v: "A nasal ‘tchay-tchay’.",
    cu: "One of the hardiest small birds of the taiga.",
    co: "Least Concern.",
    w: "Bogd Khan Uul.",
    bt: "all year",
    fa: ["Digs its own nest hole.", "Sooty cap.", "Very common."]
  },
  "siberian-tit": {
    T: { c: { brown: 0.45, white: 0.3, black: 0.15, rufous: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["13.5 cm", "—", "11–14 g"] },
    s: "A fluffy tit with a dusky brown cap and rusty flanks, living in cold taiga. Resident in Bogd Khan Uul and Terelj.",
    d: "The Grey-headed Chickadee lives in the northern taiga from Scandinavia to Alaska. It survives extreme cold. In Mongolia it is found in Ulaanbaatar (Bogd Khan Uul), Terelj and Khövsgöl.",
    f: ["Dusky brown cap.", "Black bib.", "White cheeks.", "Rusty-buff flanks."],
    si: "Willow Tit — black cap.",
    h: "Coniferous taiga.",
    di: "Ulaanbaatar (Bogd Khan Uul), Terelj, Khövsgöl, Onon, Orkhon.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Nests in holes.",
    be: "Stores food.",
    v: "A drawn-out ‘tchee-err’.",
    cu: "Can survive −45 °C.",
    co: "Least Concern.",
    w: "Terelj forests in winter.",
    bt: "all year",
    fa: ["Brown cap.", "Survives extreme cold.", "Taiga bird."]
  },
  "azure-tit": {
    T: { c: { white: 0.45, gray: 0.3, black: 0.15, yellow: 0.1 }, hb: ["forest", "water", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["12–13.5 cm", "—", "14–18 g"] },
    s: "A beautiful pale blue-and-white tit with a long tail and white wing panel. Common in willow thickets and in Ulaanbaatar.",
    d: "The Azure Tit lives from Belarus to Mongolia and China, in river thickets and woods. In Mongolia it is especially common in Ulaanbaatar along the Tuul River, the Khurkh valley and Khar Us Nuur.",
    f: ["Mostly white with pale blue back.", "Dark eye-stripe.", "Large white wing panel.", "Long blue-and-white tail."],
    si: "Unmistakable.",
    h: "Willow and poplar thickets by rivers.",
    di: "Ulaanbaatar (Tuul River), Khar Us Nuur, Khurkh, Terelj, Khustai, Ölgii.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Nests in tree holes.",
    be: "Acrobatic in thickets.",
    v: "A tinkling ‘tsi-tsi-dzhe’.",
    cu: "One of the most beautiful tits in Asia.",
    co: "Least Concern.",
    w: "Tuul River in Ulaanbaatar in winter.",
    bt: "all year",
    fa: ["White and blue.", "Long tail.", "Common in Ulaanbaatar."]
  },
  "great-tit": {
    T: { c: { black: 0.3, yellow: 0.3, white: 0.2, gray: 0.2 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["13.5–15 cm", "22–25 cm", "15–21 g"] },
    s: "The largest tit, with a black head, white cheeks and a black stripe down a yellow belly. Very common in Ulaanbaatar.",
    d: "The Great Tit lives across Eurasia. It is highly adaptable and learns new tricks quickly. In Mongolia it is abundant in Ulaanbaatar, Terelj, the Khurkh valley and Khar Us Nuur.",
    f: ["Black head with white cheeks.", "Yellow belly with a black central stripe.", "Olive-green back.", "White wing bar."],
    si: "Coal Tit — smaller, no yellow. Azure Tit — white.",
    h: "Woods, parks and towns.",
    di: "Ulaanbaatar, Terelj, Khar Us Nuur, Khurkh, Ölgii, Orkhon.",
    mi: "Resident.",
    fo: "Insects, seeds and scraps.",
    br: "Nests in holes and nest boxes; 6–12 eggs.",
    be: "Bold at feeders.",
    v: "A loud ‘tea-cher, tea-cher’.",
    cu: "Scientists have watched great tits learn to open milk bottles.",
    co: "Least Concern.",
    w: "Any park in Ulaanbaatar.",
    bt: "all year",
    fa: ["Largest tit.", "Very adaptable.", "Common in Ulaanbaatar."]
  },
  "turkestan-tit": {
    T: { c: { gray: 0.45, white: 0.3, black: 0.25 }, hb: ["desert", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["14–15 cm", "—", "14–18 g"] },
    s: "A grey-and-white version of the Great Tit with no yellow, living in Central Asian desert oases. Listed for Mongolia with no GBIF records.",
    d: "The Turkestan Tit (Parus major bokharensis group) lives in the oases and riverine woods of Central Asian deserts. It is sometimes treated as a separate species. Records in Mongolia are exceptional.",
    f: ["Grey back.", "White underparts with a black central stripe.", "Black head with white cheeks.", "Long tail."],
    si: "Great Tit — yellow belly, green back.",
    h: "Desert oases and poplar groves.",
    di: "Exceptional.",
    mi: "Resident.",
    fo: "Insects and seeds.",
    br: "Nests in holes.",
    be: "Like Great Tit.",
    v: "Great Tit-like song.",
    cu: "A desert-adapted form of the Great Tit.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["No yellow.", "Desert form.", "Sometimes a separate species."]
  }
});
