B2T("fr", {
  "eurasian-blackcap": {
    name: "Fauvette à tête noire",
    s: "Fauvette grise ; le mâle a une calotte noire nette, la femelle une calotte brune. Visiteuse très rare.",
    d: "La Fauvette à tête noire niche de l’Europe à la Sibérie occidentale et hiverne en Afrique et en Europe. En Mongolie, elle a été notée dans la vallée de Khurkh.",
    f: ["Corps gris.", "Calotte noire (mâle) ou brune (femelle).", "Ailes unies."],
    si: "Mésanges nonnette et boréale — bavette noire, ce ne sont pas des fauvettes.",
    h: "Bois à sous-bois.",
    di: "Très rare ; Khurkh.",
    mi: "Erratique.",
    fo: "Insectes et baies.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Discrète dans les buissons.",
    v: "Un chant riche et flûté.",
    cu: "Certaines hivernent désormais en Grande-Bretagne plutôt qu’en Afrique.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Calotte noire.", "Chant flûté.", "Très rare en Mongolie."]
  },
  "asian-desert-warbler": {
    name: "Fauvette naine",
    s: "Petite fauvette sable pâle à queue rousse et œil jaune, qui court souvent au sol. Commune dans le saxaoul et les broussailles du Gobi.",
    d: "La Fauvette naine niche dans les déserts d’Asie centrale et hiverne au Moyen-Orient et en Inde. Elle suit souvent les traquets. En Mongolie, elle est commune dans les broussailles désertiques — lac Khar Us, lac Orog, Böön Tsagaan et Taatsiin Tsagaan.",
    f: ["Gris sable pâle.", "Queue rousse.", "Œil et pattes jaunes.", "Court souvent au sol."],
    si: "Fauvette babillarde — grise, gorge blanche, masque sombre.",
    h: "Broussailles désertiques et saxaoul.",
    di: "Lac Khar Us, lac Orog, Böön Tsagaan, Taatsiin Tsagaan, Yolyn Am.",
    mi: "Visiteuse d’été, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans les buissons bas.",
    be: "Suit les traquets pour capturer les insectes dérangés.",
    v: "Un chant tintant.",
    cu: "S’associe souvent au Traquet du désert.",
    co: "Préoccupation mineure.",
    w: "Saxaoul près du lac Orog en mai.",
    bt: "mai–juil.",
    fa: ["Queue rousse.", "Court au sol.", "Suit les traquets."]
  },
  "barred-warbler": {
    name: "Fauvette épervière",
    s: "Grande fauvette grise à l’œil jaune farouche et aux croissants barrés sur le dessous. Visiteuse d’été des broussailles de l’ouest et du Gobi.",
    d: "La Fauvette épervière niche de l’Europe centrale à la Mongolie et hiverne en Afrique de l’Est. Elle niche souvent près des pies-grièches. En Mongolie, elle niche dans les broussailles épineuses de Yolyn Am, du lac Khar Us et du lac Achit.",
    f: ["Dessus gris.", "Croissants sombres sur le dessous blanc.", "Œil jaune.", "Barres alaires blanches."],
    si: "Fauvette babillarde — plus petite, dessous uni.",
    h: "Broussailles épineuses et lisières.",
    di: "Yolyn Am, lac Khar Us, lac Orog, lac Achit, Ölgii.",
    mi: "Visiteuse d’été, mai–août.",
    fo: "Insectes et baies.",
    br: "Niche dans les buissons épineux, souvent près des pies-grièches.",
    be: "Discrète ; chante en vol.",
    v: "Un chant grinçant.",
    cu: "Niche près des pies-grièches pour être protégée.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "juin",
    fa: ["Dessous barré.", "Œil jaune.", "Niche près des pies-grièches."]
  },
  "lesser-whitethroat": {
    name: "Fauvette babillarde",
    s: "Fauvette gris-brun soignée à gorge blanche et tache auriculaire sombre. Commune dans les broussailles de toute la Mongolie, y compris des formes désertiques.",
    d: "La Fauvette babillarde niche de l’Europe à la Mongolie. Plusieurs formes s’y rencontrent, dont la forme désertique pâle « halimodendri ». En Mongolie, elle est commune dans les buissons — Oulan-Bator, Terelj, vallée de Khurkh et lac Khar Us.",
    f: ["Dos gris-brun.", "Gorge blanche.", "Couvertures auriculaires gris foncé.", "Pattes sombres."],
    si: "Fauvette grisette — ailes rousses. Fauvette naine — sable, queue rousse.",
    h: "Buissons, lisières et broussailles désertiques.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Yolyn Am, Khustai.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Insectes et baies.",
    br: "Niche dans les buissons.",
    be: "Discrète dans le couvert dense.",
    v: "Un crépitement sec après un doux gazouillis.",
    cu: "Migre vers le sud-est plutôt que vers le sud.",
    co: "Préoccupation mineure.",
    w: "Buissons de Terelj en juin.",
    bt: "juin–juil.",
    fa: ["Gorge blanche.", "Tache auriculaire sombre.", "Commune."]
  },
  "common-whitethroat": {
    name: "Fauvette grisette",
    s: "Fauvette vive à gorge blanche et panneaux alaires roux, chantant du haut des buissons. Commune dans les broussailles du nord et de l’ouest.",
    d: "La Fauvette grisette niche de l’Europe à la Mongolie et hiverne en Afrique. En Mongolie, elle niche dans les steppes buissonnantes et lisières — Khurkh, Oulan-Bator, Yolyn Am et Terelj.",
    f: ["Gorge blanche gonflée en chantant.", "Panneaux alaires roux.", "Tête grise (mâle).", "Pattes pâles."],
    si: "Fauvette babillarde — sans ailes rousses, tache auriculaire sombre.",
    h: "Broussailles, haies et lisières.",
    di: "Khurkh, Oulan-Bator, Yolyn Am, Terelj, lac Khar Us, Khustai.",
    mi: "Visiteuse d’été, mai–septembre.",
    fo: "Insectes et baies.",
    br: "Niche bas dans les buissons.",
    be: "Vol chanté depuis le sommet des buissons.",
    v: "Un gazouillis rapide et grinçant.",
    cu: "Oiseau typique des lisières buissonnantes.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Ailes rousses.", "Gorge blanche.", "Vol chanté."]
  },
  "chinese-hill-warbler": {
    name: "Rhopophile de Pékin",
    s: "Oiseau strié à longue queue des collines sèches de Chine. Sur la liste mongole, sans mention GBIF.",
    d: "Le Rhopophile de Pékin vit dans les collines sèches et buissonnantes du nord de la Chine. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dos brun strié.", "Longue queue étagée.", "Dessous blanc à stries marron sur les flancs."],
    si: "Inconfondable en Mongolie.",
    h: "Collines sèches buissonnantes.",
    di: "Exceptionnel.",
    mi: "Résident près de la frontière.",
    fo: "Insectes et graines.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Court au sol.",
    v: "Un chant sonore.",
    cu: "Aussi appelé Garrulaxe de Pékin.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Longue queue.", "Espèce chinoise.", "Court au sol."]
  },
  "reed-parrotbill": {
    name: "Paradoxornis du Yangtsé",
    s: "Oiseau des roseaux à longue queue, gros bec jaune de perroquet et sourcil noir. Rare dans les roselières de l’extrême est de la Mongolie.",
    d: "Le Paradoxornis du Yangtsé vit dans les roselières de l’est de la Chine et de l’extrême est de la Mongolie. Il est Quasi menacé à cause de la coupe des roseaux. En Mongolie, il est connu des roselières du Dornod (lac Buir, rivière Khalkh).",
    f: ["Gros bec jaune.", "Tête grise à sourcil noir.", "Corps chamois, longue queue."],
    si: "Panure à moustaches — bec fin.",
    h: "Roselières.",
    di: "Dornod (lac Buir, rivière Khalkh).",
    mi: "Résident.",
    fo: "Insectes des tiges de roseaux.",
    br: "Niche dans les roseaux.",
    be: "Déchire les tiges de roseaux.",
    v: "Un « tchiou » sonore.",
    cu: "Dépend des roselières non fauchées.",
    co: "Quasi menacé.",
    w: "Roseaux du lac Buir.",
    bt: "toute l’année",
    fa: ["Bec de perroquet.", "Déchire les roseaux.", "Quasi menacé."]
  },
  "vinous-throated-parrotbill": {
    name: "Paradoxornis de Webb",
    s: "Minuscule oiseau rond et brun au bec trapu et à longue queue. Sur la liste mongole, sans mention GBIF.",
    d: "Le Paradoxornis de Webb vit en groupes bruyants dans les broussailles de Chine et de Corée. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Minuscule, brun roux.", "Bec court et trapu.", "Longue queue."],
    si: "Mésange à longue queue — tête blanche.",
    h: "Broussailles et herbes.",
    di: "Exceptionnel.",
    mi: "Résident.",
    fo: "Insectes et graines.",
    br: "Niche dans les buissons.",
    be: "Se déplace en groupes bruyants.",
    v: "Gazouillis constant.",
    cu: "Commun dans les jardins coréens.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Bec trapu.", "En groupes.", "Minuscule."]
  },
  "coal-tit": {
    name: "Mésange noire",
    s: "Minuscule mésange à calotte noire, joues blanches et tache blanche sur la nuque. Commune dans les forêts de conifères et parcs d’Oulan-Bator.",
    d: "La Mésange noire vit dans les forêts de conifères d’Eurasie. Elle stocke des graines dans les fissures de l’écorce. En Mongolie, elle est commune dans le Khentii — Oulan-Bator, Terelj, vallée de Khurkh.",
    f: ["Calotte et bavette noires.", "Joues blanches.", "Tache blanche sur la nuque.", "Deux barres alaires blanches."],
    si: "Mésange charbonnière — ventre jaune. Mésange boréale — sans tache nucale.",
    h: "Forêts de conifères et parcs.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Khövsgöl, Yolyn Am.",
    mi: "Résidente.",
    fo: "Insectes et graines de conifères.",
    br: "Niche dans des cavités ; 7 à 10 œufs.",
    be: "Fait des réserves pour l’hiver.",
    v: "Un « ouitchou-ouitchou » aigu.",
    cu: "Fréquente les mangeoires d’Oulan-Bator.",
    co: "Préoccupation mineure.",
    w: "Forêts du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Tache nucale blanche.", "Fait des réserves.", "Plus petite mésange de Mongolie."]
  },
  "marsh-tit": {
    name: "Mésange nonnette",
    s: "Petite mésange à calotte noire brillante et petite bavette noire. Résidente des bois feuillus du nord.",
    d: "La Mésange nonnette vit dans les bois feuillus d’Eurasie. En Mongolie, on la trouve dans le Khentii (Oulan-Bator, Terelj, Khurkh) et le Khövsgöl.",
    f: ["Calotte noire brillante.", "Petite bavette noire.", "Dos brun uni.", "Joues pâles."],
    si: "Mésange boréale — calotte mate, panneau alaire pâle.",
    h: "Bois feuillus et mixtes.",
    di: "Oulan-Bator, Terelj, Khurkh, Khövsgöl, Orkhon, Onon.",
    mi: "Résidente.",
    fo: "Insectes et graines.",
    br: "Niche dans des cavités.",
    be: "Cache des graines.",
    v: "Un « pitchou » éternué.",
    cu: "Malgré son nom anglais (« des marais »), elle évite les marais.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Calotte brillante.", "Cri « pitchou ».", "Évite les marais."]
  },
  "willow-tit": {
    name: "Mésange boréale",
    s: "Petite mésange à calotte noir suie et joues blanches ; la forme nordique est très pâle. Commune dans les forêts du nord et à Oulan-Bator.",
    d: "La Mésange boréale vit dans toutes les forêts boréales d’Eurasie. Elle creuse elle-même sa loge dans le bois pourri. En Mongolie, elle est très commune dans le Khentii et le Khangaï — Oulan-Bator, Terelj, Orkhon.",
    f: ["Calotte noir suie.", "Grandes joues blanches.", "Panneau alaire pâle.", "Flancs gris-chamois pâle."],
    si: "Mésange nonnette — calotte brillante. Mésange lapone — calotte brune.",
    h: "Forêts de conifères et mixtes.",
    di: "Oulan-Bator, Terelj, Khurkh, Orkhon, Khövsgöl, Terkhiin Tsagaan Nuur.",
    mi: "Résidente.",
    fo: "Insectes et graines.",
    br: "Creuse sa propre loge dans le bois pourri.",
    be: "Stocke des milliers de graines.",
    v: "Un « tchè-tchè » nasal.",
    cu: "L’un des petits oiseaux les plus rustiques de la taïga.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Creuse sa loge.", "Calotte suie.", "Très commune."]
  },
  "siberian-tit": {
    name: "Mésange lapone",
    s: "Mésange duveteuse à calotte brun terne et flancs rouille, vivant dans la taïga froide. Résidente au Bogd Khan Uul et à Terelj.",
    d: "La Mésange lapone vit dans la taïga nordique, de la Scandinavie à l’Alaska. Elle résiste à des froids extrêmes. En Mongolie, on la trouve à Oulan-Bator (Bogd Khan Uul), Terelj et au Khövsgöl.",
    f: ["Calotte brun terne.", "Bavette noire.", "Joues blanches.", "Flancs chamois rouille."],
    si: "Mésange boréale — calotte noire.",
    h: "Taïga de conifères.",
    di: "Oulan-Bator (Bogd Khan Uul), Terelj, Khövsgöl, Onon, Orkhon.",
    mi: "Résidente.",
    fo: "Insectes et graines.",
    br: "Niche dans des cavités.",
    be: "Fait des réserves.",
    v: "Un « tchii-èrr » traînant.",
    cu: "Survit à −45 °C.",
    co: "Préoccupation mineure.",
    w: "Forêts de Terelj en hiver.",
    bt: "toute l’année",
    fa: ["Calotte brune.", "Survit au grand froid.", "Oiseau de la taïga."]
  },
  "azure-tit": {
    name: "Mésange azurée",
    s: "Superbe mésange blanc et bleu pâle à longue queue et panneau alaire blanc. Commune dans les saulaies et à Oulan-Bator.",
    d: "La Mésange azurée vit de la Biélorussie à la Mongolie et à la Chine, dans les fourrés riverains et bois. En Mongolie, elle est particulièrement commune à Oulan-Bator le long de la Tuul, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Surtout blanche à dos bleu pâle.", "Trait oculaire sombre.", "Grand panneau alaire blanc.", "Longue queue bleue et blanche."],
    si: "Inconfondable.",
    h: "Fourrés de saules et peupliers riverains.",
    di: "Oulan-Bator (Tuul), lac Khar Us, Khurkh, Terelj, Khustai, Ölgii.",
    mi: "Résidente.",
    fo: "Insectes et graines.",
    br: "Niche dans des cavités d’arbres.",
    be: "Acrobate dans les fourrés.",
    v: "Un « tsi-tsi-dje » tintant.",
    cu: "L’une des plus belles mésanges d’Asie.",
    co: "Préoccupation mineure.",
    w: "Rivière Tuul à Oulan-Bator en hiver.",
    bt: "toute l’année",
    fa: ["Blanc et bleu.", "Longue queue.", "Commune à Oulan-Bator."]
  },
  "great-tit": {
    name: "Mésange charbonnière",
    s: "La plus grande mésange, à tête noire, joues blanches et bande noire sur un ventre jaune. Très commune à Oulan-Bator.",
    d: "La Mésange charbonnière vit dans toute l’Eurasie. Très adaptable, elle apprend vite de nouveaux comportements. En Mongolie, elle abonde à Oulan-Bator, Terelj, dans la vallée de Khurkh et au lac Khar Us.",
    f: ["Tête noire à joues blanches.", "Ventre jaune à bande centrale noire.", "Dos vert olive.", "Barre alaire blanche."],
    si: "Mésange noire — plus petite, sans jaune. Mésange azurée — blanche.",
    h: "Bois, parcs et villes.",
    di: "Oulan-Bator, Terelj, lac Khar Us, Khurkh, Ölgii, Orkhon.",
    mi: "Résidente.",
    fo: "Insectes, graines et restes.",
    br: "Niche dans des cavités et nichoirs ; 6 à 12 œufs.",
    be: "Hardie aux mangeoires.",
    v: "Un « ti-tu, ti-tu » sonore.",
    cu: "On a vu des mésanges apprendre à ouvrir les bouteilles de lait.",
    co: "Préoccupation mineure.",
    w: "N’importe quel parc d’Oulan-Bator.",
    bt: "toute l’année",
    fa: ["Plus grande mésange.", "Très adaptable.", "Commune à Oulan-Bator."]
  },
  "turkestan-tit": {
    name: "Mésange de Boukhara",
    s: "Version gris et blanc de la Mésange charbonnière, sans jaune, vivant dans les oasis d’Asie centrale. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "La Mésange de Boukhara (groupe Parus major bokharensis) vit dans les oasis et bois riverains des déserts d’Asie centrale. Elle est parfois considérée comme une espèce distincte. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dos gris.", "Dessous blanc à bande centrale noire.", "Tête noire à joues blanches.", "Longue queue."],
    si: "Mésange charbonnière — ventre jaune, dos vert.",
    h: "Oasis désertiques et peupleraies.",
    di: "Exceptionnel.",
    mi: "Résidente.",
    fo: "Insectes et graines.",
    br: "Niche dans des cavités.",
    be: "Comme la charbonnière.",
    v: "Chant de charbonnière.",
    cu: "Forme de la charbonnière adaptée au désert.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Sans jaune.", "Forme désertique.", "Parfois espèce à part."]
  }
});
