B2T("en", {
  "wood-warbler": {
    T: { c: { yellow: 0.4, white: 0.35, gray: 0.15, brown: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["11–12.5 cm", "19.5–24 cm", "8–12 g"] },
    s: "A bright leaf warbler with a lemon-yellow throat and brow and silky-white belly. A scarce autumn migrant, mostly in the west.",
    d: "The Wood Warbler breeds in the beech and oak woods of Europe east to the Urals and winters in tropical Africa. In Mongolia it is a scarce migrant, mostly in August–September in the west — Khar Us Nuur, with odd records at Khurkh and Ulaanbaatar.",
    f: ["Bright yellow throat and eyebrow.", "Clean white belly.", "Long wings, short tail.", "Upperparts yellow-olive."],
    si: "Willow Warbler — duller, shorter wings, less contrast.",
    h: "Woods and riverine groves on passage.",
    di: "West (Khar Us Nuur); scarce elsewhere.",
    mi: "Passage migrant, mainly Aug–Sep.",
    fo: "Insects.",
    br: "Nests on the forest floor (not in Mongolia).",
    be: "Feeds high in the canopy.",
    v: "A shivering trill, like a spinning coin.",
    cu: "Its Latin name sibilatrix means 'female whistler'.",
    co: "Least Concern.",
    w: "Khar Us Nuur groves in September.",
    bt: "Aug–Sep",
    fa: ["Yellow throat, white belly.", "Shivering song.", "Scarce migrant."]
  },
  "yellow-browed-warbler": {
    T: { c: { yellow: 0.4, white: 0.3, gray: 0.2, brown: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["9.5–11 cm", "15–18 cm", "5–8 g"] },
    s: "A tiny, restless leaf warbler with a long creamy eyebrow and two pale wing bars. Common in northern forests and on migration across Mongolia.",
    d: "The Yellow-browed Warbler breeds in the Siberian taiga and winters in South and Southeast Asia. A few stray to western Europe every autumn. In Mongolia it breeds in the Khentii forests and passes through in large numbers — Khurkh, Ulaanbaatar and Terelj.",
    f: ["Long creamy eyebrow.", "Two pale wing bars.", "Pale-edged tertials.", "No crown stripe."],
    si: "Hume's Leaf Warbler — duller, one clear wing bar. Pallas's Leaf Warbler — yellow rump, crown stripe.",
    h: "Taiga and riverine woods.",
    di: "Khurkh, Ulaanbaatar, Terelj, Buir Nuur, Ganga Nuur, Khar Us Nuur.",
    mi: "Summer visitor and migrant, May–Sep.",
    fo: "Small insects.",
    br: "Nests on the ground under cover.",
    be: "Flicks wings constantly as it feeds.",
    v: "A loud, rising 'tsweet'.",
    cu: "One of the most frequent Siberian strays to Europe.",
    co: "Least Concern.",
    w: "Khurkh valley in May.",
    bt: "May–Jun",
    fa: ["Long pale eyebrow.", "Two wing bars.", "Siberian stray to Europe."]
  },
  "humes-leaf-warbler": {
    T: { c: { gray: 0.4, white: 0.3, yellow: 0.2, brown: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["9.5–11 cm", "15–18 cm", "5–7 g"] },
    s: "A small, greyish leaf warbler with a long eyebrow and one clear wing bar. Common in the larch forests of western and central mountains.",
    d: "Hume's Leaf Warbler breeds in the mountains of inner Asia and winters mainly in India. It was split from the Yellow-browed Warbler. In Mongolia it breeds in the Altai and Khangai larch forests — Khar Us Nuur, Terkhiin Tsagaan Nuur and Orkhon.",
    f: ["Greyer than Yellow-browed.", "One clear wing bar.", "Long eyebrow.", "Dark legs."],
    si: "Yellow-browed Warbler — brighter, two clear wing bars.",
    h: "Mountain larch forests.",
    di: "Khar Us Nuur, Ulaanbaatar, Böön Tsagaan, Terelj, Terkhiin Tsagaan Nuur, Orkhon.",
    mi: "Summer visitor, May–Sep.",
    fo: "Small insects.",
    br: "Nests on the ground.",
    be: "Restless in treetops.",
    v: "A double 'tiss-yip'.",
    cu: "Named after Allan Octavian Hume, who also helped found the Indian National Congress.",
    co: "Least Concern.",
    w: "Larch forest in the Khangai in June.",
    bt: "Jun",
    fa: ["One wing bar.", "Split from Yellow-browed.", "Larch forests."]
  },
  "pallass-leaf-warbler": {
    T: { c: { yellow: 0.45, white: 0.3, gray: 0.15, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["9–10 cm", "—", "5–7 g"] },
    s: "A tiny, big-headed warbler with a lemon-yellow rump, crown stripe and double wing bars. Common in northern forests and the Gobi on passage.",
    d: "Pallas's Leaf Warbler breeds in mountain forests from southern Siberia to northern Mongolia and winters in south China. It is one of the smallest warblers of the region. In Mongolia it breeds in the Khentii and passes in numbers — Ulaanbaatar, Khurkh, Yolyn Am and Terelj.",
    f: ["Lemon-yellow rump.", "Yellow crown stripe.", "Two yellow wing bars.", "Long yellow eyebrow."],
    si: "Yellow-browed Warbler — no rump patch or crown stripe.",
    h: "Coniferous forest; any trees on passage.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Terelj, Buir Nuur, Ögii Nuur.",
    mi: "Summer visitor and migrant, May–Oct.",
    fo: "Small insects.",
    br: "Nests in conifers.",
    be: "Hovers to show its yellow rump.",
    v: "A loud, varied song with trills.",
    cu: "Named after the naturalist Peter Simon Pallas.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May–Jun",
    fa: ["Yellow rump.", "Tiny.", "Hovers when feeding."]
  },
  "dusky-warbler": {
    T: { c: { brown: 0.6, buff: 0.25, white: 0.15 }, hb: ["forest", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["11–12 cm", "—", "8–11 g"] },
    s: "A plain brown warbler with a pale eyebrow and a hard 'tak' call, skulking in wet thickets. Very common in Mongolia.",
    d: "The Dusky Warbler breeds in the taiga bogs and wet thickets of the east Palearctic and winters in South and Southeast Asia. In Mongolia it is abundant in willow and birch thickets — Khurkh, Ulaanbaatar, Terelj, Yolyn Am and Khar Us Nuur.",
    f: ["Plain brown upperparts.", "Buff flanks.", "Whitish eyebrow, sharp in front.", "Fine bill."],
    si: "Radde's Warbler — thicker bill, paler stout legs, buffier eyebrow.",
    h: "Wet thickets, willows, bogs.",
    di: "Khurkh, Ulaanbaatar, Terelj, Yolyn Am, Khar Us Nuur, Buir Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests low in a bush; 5–6 eggs.",
    be: "Skulks low; flicks tail.",
    v: "A hard 'tak' call; rattling song.",
    cu: "Has wintered in Britain, 3,000 km off course.",
    co: "Least Concern.",
    w: "Willows at Khurkh in June.",
    bt: "Jun",
    fa: ["'Tak' call.", "Plain brown.", "Very common."]
  },
  "willow-warbler": {
    T: { c: { yellow: 0.35, gray: 0.3, white: 0.25, brown: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["11–12.5 cm", "17–22 cm", "7–12 g"] },
    s: "A slim, yellow-tinged leaf warbler with pale legs and a sweet falling song. An uncommon migrant, mostly in the west.",
    d: "The Willow Warbler breeds from Ireland to eastern Siberia and winters in sub-Saharan Africa — one of the longest migrations for so small a bird. In Mongolia it is an uncommon passage migrant, mostly in September — Khurkh and Khar Us Nuur.",
    f: ["Yellowish wash below.", "Clear eyebrow.", "Pale legs.", "Longer wings than Chiffchaff."],
    si: "Common Chiffchaff — dark legs, shorter wings, tail-dipping.",
    h: "Birch and willow woods.",
    di: "Khurkh, Khar Us Nuur, Onon.",
    mi: "Passage migrant, May and Sep.",
    fo: "Insects.",
    br: "Domed nest on the ground (not in Mongolia).",
    be: "Active in foliage.",
    v: "A sweet, descending cadence.",
    cu: "Eastern birds still fly to Africa, a journey of up to 12,000 km.",
    co: "Least Concern.",
    w: "Khurkh in September.",
    bt: "Sep",
    fa: ["Pale legs.", "Falling song.", "Very long migration."]
  },
  "common-chiffchaff": {
    T: { c: { brown: 0.4, gray: 0.3, white: 0.2, buff: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["10–12 cm", "15–21 cm", "6–9 g"] },
    s: "A plain brown-grey leaf warbler with dark legs that dips its tail and sings its own name. Common in the west, especially the Siberian form.",
    d: "The Common Chiffchaff breeds across the Palearctic and winters in southern Europe, Africa and southern Asia. In Mongolia the greyish Siberian form (tristis) breeds in western forests — Khar Us Nuur — and migrates across the country.",
    f: ["Grey-brown upperparts.", "Dark legs.", "Short eyebrow.", "Dips its tail."],
    si: "Willow Warbler — pale legs, yellower, longer wings.",
    h: "Riverine woods and forest edges.",
    di: "Khar Us Nuur, Khurkh, Ulaanbaatar, Yolyn Am, Böön Tsagaan.",
    mi: "Summer visitor and migrant, Apr–Oct.",
    fo: "Insects.",
    br: "Domed nest near the ground; female does most work.",
    be: "Constantly dips its tail.",
    v: "'Chiff-chaff-chiff-chaff'; the Siberian form sings differently.",
    cu: "The name copies the song.",
    co: "Least Concern.",
    w: "Khar Us Nuur in September.",
    bt: "May–Jun",
    fa: ["Sings its name.", "Dark legs.", "Siberian grey form."]
  },
  "sulphur-bellied-warbler": {
    T: { c: { brown: 0.4, yellow: 0.3, buff: 0.2, gray: 0.1 }, hb: ["mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["11–12 cm", "—", "8–10 g"] },
    s: "A dusky warbler of rocky slopes with a bright yellow eyebrow and sulphur-buff underparts that climbs rocks like a nuthatch. Local in the Gobi and Altai.",
    d: "The Sulphur-bellied Warbler breeds on rocky scrubby slopes of Central Asia and winters in India. In Mongolia it breeds in rocky gorges of the Gobi Altai and Altai — Yolyn Am, Khar Us Nuur and Tavan Bogd.",
    f: ["Bright yellow eyebrow.", "Sulphur-buff underparts.", "Dull brown upperparts.", "Climbs over rocks."],
    si: "Dusky Warbler — whitish eyebrow, lives in thickets.",
    h: "Rocky gorges with scrub.",
    di: "Yolyn Am, Khar Us Nuur, Tavan Bogd, Ölgii, Achit Nuur.",
    mi: "Summer visitor, May–Aug.",
    fo: "Insects.",
    br: "Nests low in bushes on rocky slopes.",
    be: "Creeps and hops over rocks.",
    v: "A single 'cheep' call; short trilling song.",
    cu: "Behaves more like a nuthatch than a leaf warbler.",
    co: "Least Concern.",
    w: "Yolyn Am gorge in June.",
    bt: "Jun–Jul",
    fa: ["Climbs rocks.", "Yellow eyebrow.", "Rocky gorges."]
  },
  "yellow-streaked-warbler": {
    T: { c: { brown: 0.5, buff: 0.3, yellow: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12–13 cm", "—", "9–11 g"] },
    s: "A brownish Chinese leaf warbler with fine yellow streaks below. On the Mongolian list, no GBIF records.",
    d: "The Yellow-streaked Warbler breeds in the temperate forests of China and winters in Yunnan and northern Southeast Asia. Records in Mongolia are exceptional.",
    f: ["Olive-brown upperparts.", "Fine yellow streaking below.", "Long pale eyebrow.", "Stout bill."],
    si: "Radde's Warbler — no yellow streaks.",
    h: "Temperate forest and scrub.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Feeds low in thickets.",
    v: "Dozens of different syllable types.",
    cu: "Its song is unusually varied for a leaf warbler.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Yellow streaks.", "Chinese species.", "Varied song."]
  },
  "raddes-warbler": {
    T: { c: { brown: 0.55, buff: 0.3, yellow: 0.15 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["12–14 cm", "—", "10–14 g"] },
    s: "A chunky brown warbler with a thick bill, stout pale legs and a long buff eyebrow. Uncommon in northern and eastern forests.",
    d: "Radde's Warbler breeds in Siberia and northeast Asia and winters in Southeast Asia. In Mongolia it breeds in forest undergrowth of the north and east — Khurkh, Terelj and Ulaanbaatar.",
    f: ["Thick bill.", "Stout pale legs, large feet.", "Long buff eyebrow.", "Buff underparts."],
    si: "Dusky Warbler — finer bill, darker legs, 'tak' call.",
    h: "Forest undergrowth and thickets.",
    di: "Khurkh, Yolyn Am, Terelj, Ulaanbaatar, Khar Us Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests low in shrubs.",
    be: "Often on the ground.",
    v: "A soft 'chick' call.",
    cu: "Named after Gustav Radde; the Latin name honours astronomer Ludwig Schwarz.",
    co: "Least Concern.",
    w: "Khurkh valley in May.",
    bt: "Jun",
    fa: ["Thick bill.", "Big pale feet.", "Ground-loving."]
  },
  "green-leaf-warbler": {
    T: { c: { yellow: 0.55, gray: 0.25, white: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["10–11 cm", "—", "7–9 g"] },
    s: "A bright yellow-green relative of the Greenish Warbler from the Caucasus. On the Mongolian list, no GBIF records.",
    d: "The Green Warbler breeds in the Caucasus and nearby mountains and winters in India. It is closely related to the Greenish Warbler. Records in Mongolia are exceptional.",
    f: ["Bright yellow-green above.", "Yellow underparts.", "One strong wing bar.", "Yellow eyebrow."],
    si: "Greenish Warbler — whitish below.",
    h: "Mountain forest.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests on the ground (not in Mongolia).",
    be: "Active in treetops.",
    v: "A bright, fast song.",
    cu: "Its Latin name nitidus means 'shining'.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Yellow below.", "Caucasus species.", "One wing bar."]
  },
  "greenish-leaf-warbler": {
    T: { c: { gray: 0.4, white: 0.35, yellow: 0.15, brown: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["10–11 cm", "15–21 cm", "6–9 g"] },
    s: "A greyish-green leaf warbler with a long eyebrow and one thin wing bar. Breeds in western and central mountain forests.",
    d: "The Greenish Warbler breeds from northeast Europe across temperate Asia and winters in India. Its forms around the Tibetan Plateau are a famous 'ring species'. In Mongolia it breeds in the forests of the Altai and Khangai — Khar Us Nuur, Terkhiin Tsagaan Nuur and Terelj.",
    f: ["Grey-green upperparts.", "Whitish underparts.", "One thin wing bar.", "Long eyebrow."],
    si: "Two-barred Warbler — two wing bars. Arctic Warbler — larger, heavier bill.",
    h: "Mountain forest.",
    di: "Khar Us Nuur, Yolyn Am, Terelj, Ulaanbaatar, Böön Tsagaan, Terkhiin Tsagaan Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Active in the canopy.",
    v: "A fast, ringing song.",
    cu: "A textbook example of a 'ring species' around Tibet.",
    co: "Least Concern.",
    w: "Khar Us Nuur in June.",
    bt: "Jun",
    fa: ["Ring species.", "One wing bar.", "Mountain forests."]
  },
  "two-barred-leaf-warbler": {
    T: { c: { gray: 0.4, white: 0.35, yellow: 0.15, black: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["10–12 cm", "—", "6–9 g"] },
    s: "A greenish leaf warbler with two white wing bars and dark legs. Common in northern Mongolian forests.",
    d: "The Two-barred Warbler breeds in northern Mongolia, Manchuria and southern Siberia and winters in Southeast Asia. It was formerly lumped with the Greenish Warbler. In Mongolia it is common in the Khentii — Khurkh, Ulaanbaatar and Terelj.",
    f: ["Two white wing bars.", "Long eyebrow.", "Dark grey legs.", "Whitish underparts."],
    si: "Greenish Warbler — one wing bar. Yellow-browed Warbler — smaller, pale-edged tertials.",
    h: "Taiga and mixed forest.",
    di: "Khurkh, Ulaanbaatar, Terelj, Yolyn Am, Buir Nuur, Orog Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Moults before autumn migration.",
    v: "A fast, trilling song.",
    cu: "Described by Robert Swinhoe in 1861.",
    co: "Least Concern.",
    w: "Bogd Khan Uul in June.",
    bt: "Jun",
    fa: ["Two wing bars.", "Split from Greenish.", "Common in the Khentii."]
  },
  "arctic-warbler": {
    T: { c: { gray: 0.4, white: 0.3, yellow: 0.2, brown: 0.1 }, hb: ["forest", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["11.5–13 cm", "—", "8–15 g"] },
    s: "A robust leaf warbler with a heavy bill, long eyebrow and thin wing bar. Common in birch and willow woods by water.",
    d: "The Arctic Warbler breeds from Scandinavia to Alaska and winters in Southeast Asia — one of the longest migrations of any Old World insect-eater. In Mongolia it breeds in the north and migrates widely — Khurkh, Ulaanbaatar, Terelj and Yolyn Am.",
    f: ["Heavy bill.", "Long eyebrow not reaching the forehead.", "Thin wing bar.", "Pale legs."],
    si: "Greenish Warbler — smaller, finer bill.",
    h: "Birch and willow woods near water.",
    di: "Khurkh, Ulaanbaatar, Terelj, Yolyn Am, Ganga Nuur, Buir Nuur.",
    mi: "Summer visitor and migrant, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground in a low shrub.",
    be: "Arrives late, often in June.",
    v: "A buzzing 'dzrit' and a trilling song.",
    cu: "Has colonised Alaska from Asia.",
    co: "Least Concern.",
    w: "Khurkh in late May.",
    bt: "Jun",
    fa: ["Heavy bill.", "Breeds in Alaska too.", "Long migration."]
  },
  "pale-legged-leaf-warbler": {
    T: { c: { brown: 0.45, white: 0.35, gray: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["11–12 cm", "—", "8–10 g"] },
    s: "A brownish leaf warbler with a grey crown, long white eyebrow and pale pink legs. A rare migrant in the east.",
    d: "The Pale-legged Leaf Warbler breeds in Manchuria and winters in Southeast Asia. In Mongolia there are a few records from the east, around Ganga Nuur.",
    f: ["Grey-brown crown.", "Long white eyebrow.", "Pale pink legs.", "Whitish underparts."],
    si: "Arctic Warbler — greener, less contrasting.",
    h: "Forest undergrowth.",
    di: "East (Ganga Nuur).",
    mi: "Rare migrant, May.",
    fo: "Insects.",
    br: "Nests on the ground (not in Mongolia).",
    be: "Dips its tail.",
    v: "A high, insect-like 'tiririri'.",
    cu: "Its song resembles a cricket.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Pale legs.", "Cricket-like song.", "Rare in the east."]
  }
});
