B2T("fr", {
  "wood-warbler": {
    name: "Pouillot siffleur",
    s: "Pouillot vif à gorge et sourcil jaune citron et ventre blanc soyeux. Migrateur d’automne peu commun, surtout dans l’ouest.",
    d: "Le Pouillot siffleur niche dans les hêtraies et chênaies d’Europe jusqu’à l’Oural et hiverne en Afrique tropicale. En Mongolie, c’est un migrateur peu commun, surtout en août–septembre dans l’ouest — lac Khar Us, avec quelques mentions à Khurkh et Oulan-Bator.",
    f: ["Gorge et sourcil jaune vif.", "Ventre blanc net.", "Ailes longues, queue courte.", "Dessus olive-jaune."],
    si: "Pouillot fitis — plus terne, ailes plus courtes, moins de contraste.",
    h: "Bois et bosquets riverains en migration.",
    di: "Ouest (lac Khar Us) ; rare ailleurs.",
    mi: "Migrateur, surtout août–septembre.",
    fo: "Insectes.",
    br: "Niche au sol en forêt (pas en Mongolie).",
    be: "Se nourrit haut dans la canopée.",
    v: "Un trille frémissant, comme une pièce qui tourne.",
    cu: "Son nom latin sibilatrix signifie « siffleuse ».",
    co: "Préoccupation mineure.",
    w: "Bosquets du lac Khar Us en septembre.",
    bt: "août–sept.",
    fa: ["Gorge jaune, ventre blanc.", "Chant frémissant.", "Migrateur peu commun."]
  },
  "yellow-browed-warbler": {
    name: "Pouillot à grands sourcils",
    s: "Minuscule pouillot remuant à long sourcil crème et deux barres alaires pâles. Commun dans les forêts du nord et en migration dans toute la Mongolie.",
    d: "Le Pouillot à grands sourcils niche dans la taïga sibérienne et hiverne en Asie du Sud et du Sud-Est. Quelques-uns s’égarent en Europe occidentale chaque automne. En Mongolie, il niche dans les forêts du Khentii et passe en grand nombre — Khurkh, Oulan-Bator et Terelj.",
    f: ["Long sourcil crème.", "Deux barres alaires pâles.", "Tertiaires bordées de pâle.", "Pas de bande coronale."],
    si: "Pouillot de Hume — plus terne, une seule barre nette. Pouillot de Pallas — croupion jaune, bande coronale.",
    h: "Taïga et bois riverains.",
    di: "Khurkh, Oulan-Bator, Terelj, lac Buir, lac Ganga, lac Khar Us.",
    mi: "Estivant et migrateur, mai–septembre.",
    fo: "Petits insectes.",
    br: "Niche au sol sous le couvert.",
    be: "Agite sans cesse les ailes en se nourrissant.",
    v: "Un « tsouiit » sonore et montant.",
    cu: "L’un des égarés sibériens les plus fréquents en Europe.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en mai.",
    bt: "mai–juin",
    fa: ["Long sourcil pâle.", "Deux barres alaires.", "Égaré sibérien en Europe."]
  },
  "humes-leaf-warbler": {
    name: "Pouillot de Hume",
    s: "Petit pouillot grisâtre à long sourcil et une seule barre alaire nette. Commun dans les forêts de mélèzes des montagnes de l’ouest et du centre.",
    d: "Le Pouillot de Hume niche dans les montagnes d’Asie intérieure et hiverne surtout en Inde. Il a été séparé du Pouillot à grands sourcils. En Mongolie, il niche dans les forêts de mélèzes de l’Altaï et du Khangaï — lac Khar Us, Terkhiin Tsagaan Nuur et Orkhon.",
    f: ["Plus gris que le Pouillot à grands sourcils.", "Une barre alaire nette.", "Long sourcil.", "Pattes sombres."],
    si: "Pouillot à grands sourcils — plus vif, deux barres nettes.",
    h: "Forêts de mélèzes de montagne.",
    di: "Lac Khar Us, Oulan-Bator, Böön Tsagaan, Terelj, Terkhiin Tsagaan Nuur, Orkhon.",
    mi: "Estivant, mai–septembre.",
    fo: "Petits insectes.",
    br: "Niche au sol.",
    be: "Remuant dans les cimes.",
    v: "Un double « tiss-yip ».",
    cu: "Nommé d’après Allan Octavian Hume, qui contribua aussi à fonder le Congrès national indien.",
    co: "Préoccupation mineure.",
    w: "Forêt de mélèzes du Khangaï en juin.",
    bt: "juin",
    fa: ["Une barre alaire.", "Séparé du grands-sourcils.", "Forêts de mélèzes."]
  },
  "pallass-leaf-warbler": {
    name: "Pouillot de Pallas",
    s: "Minuscule pouillot à grosse tête, croupion jaune citron, bande coronale et doubles barres alaires. Commun dans les forêts du nord et dans le Gobi en migration.",
    d: "Le Pouillot de Pallas niche dans les forêts de montagne du sud de la Sibérie au nord de la Mongolie et hiverne dans le sud de la Chine. C’est l’un des plus petits pouillots de la région. En Mongolie, il niche dans le Khentii et passe en nombre — Oulan-Bator, Khurkh, Yolyn Am et Terelj.",
    f: ["Croupion jaune citron.", "Bande coronale jaune.", "Deux barres alaires jaunes.", "Long sourcil jaune."],
    si: "Pouillot à grands sourcils — sans croupion jaune ni bande coronale.",
    h: "Forêts de conifères ; tout arbre en migration.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Terelj, lac Buir, lac Ögii.",
    mi: "Estivant et migrateur, mai–octobre.",
    fo: "Petits insectes.",
    br: "Niche dans les conifères.",
    be: "Fait du surplace en montrant son croupion jaune.",
    v: "Un chant sonore et varié, avec des trilles.",
    cu: "Nommé d’après le naturaliste Peter Simon Pallas.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai–juin",
    fa: ["Croupion jaune.", "Minuscule.", "Fait du surplace."]
  },
  "dusky-warbler": {
    name: "Pouillot brun",
    s: "Pouillot brun uni à sourcil pâle et cri « tac » sec, caché dans les fourrés humides. Très commun en Mongolie.",
    d: "Le Pouillot brun niche dans les tourbières de la taïga et les fourrés humides du Paléarctique oriental et hiverne en Asie du Sud et du Sud-Est. En Mongolie, il abonde dans les fourrés de saules et bouleaux — Khurkh, Oulan-Bator, Terelj, Yolyn Am et lac Khar Us.",
    f: ["Dessus brun uni.", "Flancs chamois.", "Sourcil blanchâtre, net en avant.", "Bec fin."],
    si: "Pouillot de Schwarz — bec plus fort, pattes pâles et robustes, sourcil chamois.",
    h: "Fourrés humides, saules et tourbières.",
    di: "Khurkh, Oulan-Bator, Terelj, Yolyn Am, lac Khar Us, lac Buir.",
    mi: "Estivant, mai–septembre.",
    fo: "Insectes.",
    br: "Niche bas dans un buisson ; 5 à 6 œufs.",
    be: "Se cache bas ; agite la queue.",
    v: "Un « tac » sec ; chant crépitant.",
    cu: "A hiverné en Grande-Bretagne, à 3 000 km de sa route.",
    co: "Préoccupation mineure.",
    w: "Saules de Khurkh en juin.",
    bt: "juin",
    fa: ["Cri « tac ».", "Brun uni.", "Très commun."]
  },
  "willow-warbler": {
    name: "Pouillot fitis",
    s: "Pouillot élancé lavé de jaune, à pattes pâles et doux chant descendant. Migrateur peu commun, surtout dans l’ouest.",
    d: "Le Pouillot fitis niche de l’Irlande à la Sibérie orientale et hiverne en Afrique subsaharienne — l’une des plus longues migrations pour un oiseau si petit. En Mongolie, c’est un migrateur peu commun, surtout en septembre — Khurkh et lac Khar Us.",
    f: ["Dessous lavé de jaune.", "Sourcil net.", "Pattes pâles.", "Ailes plus longues que le véloce."],
    si: "Pouillot véloce — pattes sombres, ailes plus courtes, hoche la queue.",
    h: "Bois de bouleaux et de saules.",
    di: "Khurkh, lac Khar Us, Onon.",
    mi: "Migrateur, mai et septembre.",
    fo: "Insectes.",
    br: "Nid en dôme au sol (pas en Mongolie).",
    be: "Actif dans le feuillage.",
    v: "Une douce cadence descendante.",
    cu: "Les oiseaux de l’est volent jusqu’en Afrique, soit jusqu’à 12 000 km.",
    co: "Préoccupation mineure.",
    w: "Khurkh en septembre.",
    bt: "sept.",
    fa: ["Pattes pâles.", "Chant descendant.", "Très longue migration."]
  },
  "common-chiffchaff": {
    name: "Pouillot véloce",
    s: "Pouillot gris-brun uni à pattes sombres, qui hoche la queue et chante son nom anglais. Commun dans l’ouest, surtout la forme sibérienne.",
    d: "Le Pouillot véloce niche dans tout le Paléarctique et hiverne en Europe du Sud, en Afrique et en Asie du Sud. En Mongolie, la forme sibérienne grisâtre (tristis) niche dans les forêts de l’ouest — lac Khar Us — et migre à travers le pays.",
    f: ["Dessus gris-brun.", "Pattes sombres.", "Sourcil court.", "Hoche la queue."],
    si: "Pouillot fitis — pattes pâles, plus jaune, ailes plus longues.",
    h: "Bois riverains et lisières.",
    di: "Lac Khar Us, Khurkh, Oulan-Bator, Yolyn Am, Böön Tsagaan.",
    mi: "Estivant et migrateur, avril–octobre.",
    fo: "Insectes.",
    br: "Nid en dôme près du sol ; la femelle fait l’essentiel.",
    be: "Hoche sans cesse la queue.",
    v: "« Tchif-tchaf-tchif-tchaf » ; la forme sibérienne chante autrement.",
    cu: "Son nom anglais, chiffchaff, imite son chant.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en septembre.",
    bt: "mai–juin",
    fa: ["Chante « tchif-tchaf ».", "Pattes sombres.", "Forme sibérienne grise."]
  },
  "sulphur-bellied-warbler": {
    name: "Pouillot griséole",
    s: "Pouillot terne des pentes rocheuses, à sourcil jaune vif et dessous jaune soufre, qui grimpe sur les rochers comme une sittelle. Local dans le Gobi et l’Altaï.",
    d: "Le Pouillot griséole niche sur les pentes rocheuses buissonnantes d’Asie centrale et hiverne en Inde. En Mongolie, il niche dans les gorges rocheuses de l’Altaï du Gobi et de l’Altaï — Yolyn Am, lac Khar Us et Tavan Bogd.",
    f: ["Sourcil jaune vif.", "Dessous jaune soufre-chamois.", "Dessus brun terne.", "Grimpe sur les rochers."],
    si: "Pouillot brun — sourcil blanchâtre, vit dans les fourrés.",
    h: "Gorges rocheuses buissonnantes.",
    di: "Yolyn Am, lac Khar Us, Tavan Bogd, Ölgii, lac Achit.",
    mi: "Estivant, mai–août.",
    fo: "Insectes.",
    br: "Niche bas dans les buissons des pentes rocheuses.",
    be: "Rampe et sautille sur les rochers.",
    v: "Un « tchip » isolé ; court chant trillé.",
    cu: "Se comporte davantage comme une sittelle que comme un pouillot.",
    co: "Préoccupation mineure.",
    w: "Gorge de Yolyn Am en juin.",
    bt: "juin–juil.",
    fa: ["Grimpe aux rochers.", "Sourcil jaune.", "Gorges rocheuses."]
  },
  "yellow-streaked-warbler": {
    name: "Pouillot de Milne-Edwards",
    s: "Pouillot brunâtre de Chine à fines stries jaunes dessous. Inscrit pour la Mongolie, sans mention GBIF.",
    d: "Le Pouillot de Milne-Edwards niche dans les forêts tempérées de Chine et hiverne au Yunnan et dans le nord de l’Asie du Sud-Est. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dessus brun olive.", "Fines stries jaunes dessous.", "Long sourcil pâle.", "Bec assez fort."],
    si: "Pouillot de Schwarz — sans stries jaunes.",
    h: "Forêts tempérées et broussailles.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Se nourrit bas dans les fourrés.",
    v: "Des dizaines de types de syllabes.",
    cu: "Son chant est exceptionnellement varié pour un pouillot.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Stries jaunes.", "Espèce chinoise.", "Chant varié."]
  },
  "raddes-warbler": {
    name: "Pouillot de Schwarz",
    s: "Pouillot brun trapu à bec épais, pattes pâles robustes et long sourcil chamois. Peu commun dans les forêts du nord et de l’est.",
    d: "Le Pouillot de Schwarz niche en Sibérie et en Asie du Nord-Est et hiverne en Asie du Sud-Est. En Mongolie, il niche dans le sous-bois des forêts du nord et de l’est — Khurkh, Terelj et Oulan-Bator.",
    f: ["Bec épais.", "Pattes pâles robustes, grands pieds.", "Long sourcil chamois.", "Dessous chamois."],
    si: "Pouillot brun — bec plus fin, pattes plus sombres, cri « tac ».",
    h: "Sous-bois forestier et fourrés.",
    di: "Khurkh, Yolyn Am, Terelj, Oulan-Bator, lac Khar Us.",
    mi: "Estivant, mai–septembre.",
    fo: "Insectes.",
    br: "Niche bas dans les arbustes.",
    be: "Souvent au sol.",
    v: "Un doux « tchik ».",
    cu: "Son nom anglais honore Gustav Radde, son nom latin l’astronome Ludwig Schwarz.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en mai.",
    bt: "juin",
    fa: ["Bec épais.", "Grands pieds pâles.", "Aime le sol."]
  },
  "green-leaf-warbler": {
    name: "Pouillot du Caucase",
    s: "Proche parent jaune-vert vif du Pouillot verdâtre, originaire du Caucase. Inscrit pour la Mongolie, sans mention GBIF.",
    d: "Le Pouillot du Caucase niche dans le Caucase et les montagnes voisines et hiverne en Inde. Il est étroitement apparenté au Pouillot verdâtre. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dessus jaune-vert vif.", "Dessous jaune.", "Une barre alaire nette.", "Sourcil jaune."],
    si: "Pouillot verdâtre — dessous blanchâtre.",
    h: "Forêts de montagne.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche au sol (pas en Mongolie).",
    be: "Actif dans les cimes.",
    v: "Un chant vif et rapide.",
    cu: "Son nom latin nitidus signifie « brillant ».",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Dessous jaune.", "Espèce du Caucase.", "Une barre alaire."]
  },
  "greenish-leaf-warbler": {
    name: "Pouillot verdâtre",
    s: "Pouillot gris-vert à long sourcil et une fine barre alaire. Niche dans les forêts de montagne de l’ouest et du centre.",
    d: "Le Pouillot verdâtre niche du nord-est de l’Europe à toute l’Asie tempérée et hiverne en Inde. Ses formes autour du plateau tibétain constituent une célèbre « espèce en anneau ». En Mongolie, il niche dans les forêts de l’Altaï et du Khangaï — lac Khar Us, Terkhiin Tsagaan Nuur et Terelj.",
    f: ["Dessus gris-vert.", "Dessous blanchâtre.", "Une fine barre alaire.", "Long sourcil."],
    si: "Pouillot à deux barres — deux barres alaires. Pouillot boréal — plus grand, bec plus fort.",
    h: "Forêts de montagne.",
    di: "Lac Khar Us, Yolyn Am, Terelj, Oulan-Bator, Böön Tsagaan, Terkhiin Tsagaan Nuur.",
    mi: "Estivant, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Actif dans la canopée.",
    v: "Un chant rapide et sonore.",
    cu: "Exemple classique d’« espèce en anneau » autour du Tibet.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en juin.",
    bt: "juin",
    fa: ["Espèce en anneau.", "Une barre alaire.", "Forêts de montagne."]
  },
  "two-barred-leaf-warbler": {
    name: "Pouillot à deux barres",
    s: "Pouillot verdâtre à deux barres alaires blanches et pattes sombres. Commun dans les forêts du nord de la Mongolie.",
    d: "Le Pouillot à deux barres niche dans le nord de la Mongolie, en Mandchourie et dans le sud de la Sibérie et hiverne en Asie du Sud-Est. Il était autrefois réuni au Pouillot verdâtre. En Mongolie, il est commun dans le Khentii — Khurkh, Oulan-Bator et Terelj.",
    f: ["Deux barres alaires blanches.", "Long sourcil.", "Pattes gris foncé.", "Dessous blanchâtre."],
    si: "Pouillot verdâtre — une seule barre. Pouillot à grands sourcils — plus petit, tertiaires bordées de pâle.",
    h: "Taïga et forêts mixtes.",
    di: "Khurkh, Oulan-Bator, Terelj, Yolyn Am, lac Buir, lac Orog.",
    mi: "Estivant, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Mue avant la migration d’automne.",
    v: "Un chant rapide et trillé.",
    cu: "Décrit par Robert Swinhoe en 1861.",
    co: "Préoccupation mineure.",
    w: "Bogd Khan Uul en juin.",
    bt: "juin",
    fa: ["Deux barres alaires.", "Séparé du verdâtre.", "Commun dans le Khentii."]
  },
  "arctic-warbler": {
    name: "Pouillot boréal",
    s: "Pouillot robuste à bec fort, long sourcil et fine barre alaire. Commun dans les bois de bouleaux et saules près de l’eau.",
    d: "Le Pouillot boréal niche de la Scandinavie à l’Alaska et hiverne en Asie du Sud-Est — l’une des plus longues migrations des insectivores de l’Ancien Monde. En Mongolie, il niche dans le nord et migre largement — Khurkh, Oulan-Bator, Terelj et Yolyn Am.",
    f: ["Bec fort.", "Long sourcil n’atteignant pas le front.", "Fine barre alaire.", "Pattes pâles."],
    si: "Pouillot verdâtre — plus petit, bec plus fin.",
    h: "Bois de bouleaux et saules près de l’eau.",
    di: "Khurkh, Oulan-Bator, Terelj, Yolyn Am, lac Ganga, lac Buir.",
    mi: "Estivant et migrateur, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol sous un arbuste bas.",
    be: "Arrive tard, souvent en juin.",
    v: "Un « dzrit » bourdonnant et un chant trillé.",
    cu: "A colonisé l’Alaska depuis l’Asie.",
    co: "Préoccupation mineure.",
    w: "Khurkh fin mai.",
    bt: "juin",
    fa: ["Bec fort.", "Niche aussi en Alaska.", "Longue migration."]
  },
  "pale-legged-leaf-warbler": {
    name: "Pouillot à pattes claires",
    s: "Pouillot brunâtre à calotte grise, long sourcil blanc et pattes rose pâle. Migrateur rare dans l’est.",
    d: "Le Pouillot à pattes claires niche en Mandchourie et hiverne en Asie du Sud-Est. En Mongolie, il existe quelques mentions dans l’est, autour du lac Ganga.",
    f: ["Calotte gris-brun.", "Long sourcil blanc.", "Pattes rose pâle.", "Dessous blanchâtre."],
    si: "Pouillot boréal — plus vert, moins contrasté.",
    h: "Sous-bois forestier.",
    di: "Est (lac Ganga).",
    mi: "Migrateur rare, mai.",
    fo: "Insectes.",
    br: "Niche au sol (pas en Mongolie).",
    be: "Hoche la queue.",
    v: "Un « tiririri » aigu d’insecte.",
    cu: "Son chant rappelle un grillon.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Pattes pâles.", "Chant de grillon.", "Rare dans l’est."]
  }
});
