B2T("en", {
  "thick-billed-warbler": {
    T: { c: { brown: 0.6, buff: 0.3, white: 0.1 }, hb: ["forest", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["16–17.5 cm", "—", "22–31 g"] },
    s: "A large, plain brown warbler with a short, thick bill and a round-headed, 'surprised' look. Common in thickets of the north and east.",
    d: "The Thick-billed Warbler breeds from southern Siberia to Mongolia and northeast China and winters in South and Southeast Asia. It is nearly as big as a Great Reed Warbler. In Mongolia it breeds in dense riverside scrub — Khurkh, Ulaanbaatar, Terelj and Yolyn Am.",
    f: ["Plain brown upperparts.", "Short, thick bill.", "No eyebrow; pale lores.", "Long rounded tail."],
    si: "East Asian Reed Warbler — pale eyebrow, long bill, lives in reeds.",
    h: "Dense thickets, bushy river banks, forest edge.",
    di: "Khurkh, Ulaanbaatar, Yolyn Am, Terelj, Orog Nuur, Ganga Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Large insects.",
    br: "Nests low in a bush; 5–6 eggs.",
    be: "Skulks, but sings from a bush top.",
    v: "A loud, varied song with mimicry.",
    cu: "Its 'blank' face, with no eyebrow, is the best field mark.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "Jun",
    fa: ["Thick bill.", "No eyebrow.", "Big, plain warbler."]
  },
  "sykess-warbler": {
    T: { c: { gray: 0.45, brown: 0.3, white: 0.25 }, hb: ["desert", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["11.5–12.5 cm", "—", "7–10 g"] },
    s: "A small, pale grey-brown tree warbler of desert scrub. On the Mongolian list, no GBIF records.",
    d: "Sykes's Warbler breeds from Arabia to Turkestan and western China and winters in the Indian subcontinent. It was formerly lumped with the Booted Warbler. Records in Mongolia are exceptional.",
    f: ["Pale grey-brown upperparts.", "Short pale eyebrow.", "Long, fine bill.", "Square tail with pale edges."],
    si: "Blyth's Reed Warbler — darker, rounder tail.",
    h: "Tamarisk and desert scrub.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Flicks its tail downward.",
    v: "A chattering, rambling song.",
    cu: "Named after Colonel William Henry Sykes of British India.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Pale.", "Desert scrub.", "Split from Booted Warbler."]
  },
  "black-browed-reed-warbler": {
    T: { c: { brown: 0.5, buff: 0.25, white: 0.15, black: 0.1 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12.5–13.5 cm", "—", "8–10 g"] },
    s: "A small reed warbler with a bold creamy eyebrow edged above by a black stripe. Local in eastern wetlands.",
    d: "The Black-browed Reed Warbler breeds from eastern Mongolia and southeast Russia to eastern China and Japan and winters in Southeast Asia. In Mongolia it breeds in the reedbeds and wet meadows of the east — Ganga Nuur, Buir Nuur and the Daguur area.",
    f: ["Creamy eyebrow.", "Black stripe above the eyebrow.", "Warm brown upperparts.", "Whitish underparts."],
    si: "Paddyfield Warbler — no black crown stripe, paler.",
    h: "Reedbeds and wet sedge meadows.",
    di: "Ganga Nuur, Buir Nuur, Khurkh, Daguur, Onon.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests low in reeds or grass.",
    be: "Forages close to the ground among reeds.",
    v: "A varied, scratchy song.",
    cu: "Described by Robert Swinhoe in 1860.",
    co: "Least Concern.",
    w: "Buir Nuur reeds in July.",
    bt: "Jun–Jul",
    fa: ["Black brow stripe.", "Eastern wetlands.", "Small reed warbler."]
  },
  "blyths-reed-warbler": {
    T: { c: { brown: 0.55, buff: 0.25, white: 0.2 }, hb: ["forest", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12.5–14 cm", "17–19 cm", "9–13 g"] },
    s: "A plain, cold-brown warbler of bushes and forest edges with a superb mimicking song. Common in the far west.",
    d: "Blyth's Reed Warbler breeds across the Palearctic and winters in South Asia. It has been spreading westward in Europe. In Mongolia it breeds in bushy valleys of the west — especially around Khar Us Nuur.",
    f: ["Plain grey-brown upperparts.", "Short pale eyebrow.", "Short, rounded wings.", "Greyish legs."],
    si: "Paddyfield Warbler — warmer, stronger eyebrow, dark crown edge.",
    h: "Bushes, forest edges, tall herbs.",
    di: "Khar Us Nuur, Tavan Bogd, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests in tall herbs or bushes.",
    be: "Sings at night as well as by day.",
    v: "Slow, repeated phrases with much mimicry.",
    cu: "Named after the zoologist Edward Blyth.",
    co: "Least Concern.",
    w: "Khar Us Nuur in June.",
    bt: "Jun–Jul",
    fa: ["Great mimic.", "Plain brown.", "Spreading west in Europe."]
  },
  "paddyfield-warbler": {
    T: { c: { brown: 0.45, buff: 0.35, white: 0.2 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12–13 cm", "15–17 cm", "8–11 g"] },
    s: "A small, warm-brown reed warbler with a strong white eyebrow and short bill. Common in the reedbeds of western lakes.",
    d: "The Paddyfield Warbler breeds in the temperate central Palearctic and winters in India and Pakistan. In Mongolia it breeds in reedbeds and wet scrub of western and Gobi lakes — Khar Us Nuur, Böön Tsagaan and Orog Nuur.",
    f: ["Warm brown upperparts.", "Strong white eyebrow.", "Dark line along the crown edge.", "Short bill."],
    si: "Black-browed Reed Warbler — bold black stripe above the eyebrow.",
    h: "Reedbeds and lakeside scrub.",
    di: "Khar Us Nuur, Khurkh, Böön Tsagaan, Orog Nuur, Ulaanbaatar, Ganga Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests in reeds.",
    be: "Often cocks its tail.",
    v: "A fast, chattering song.",
    cu: "Its Latin name agricola means 'farmer'.",
    co: "Least Concern.",
    w: "Khar Us Nuur reeds in June.",
    bt: "Jun",
    fa: ["White eyebrow.", "Cocked tail.", "Western lakes."]
  },
  "great-reed-warbler": {
    T: { c: { brown: 0.55, buff: 0.3, white: 0.15 }, hb: ["water"], bk: "long", bh: ["perch"], vt: ["song", "croak"], ac: "day", se: ["summer"], sz: ["16–20 cm", "24–29 cm", "22–36 g"] },
    s: "The largest reed warbler, thrush-sized, with a loud, croaking 'karra-karra' song. Local in western reedbeds.",
    d: "The Great Reed Warbler breeds across Europe and the western Palearctic and winters in sub-Saharan Africa. In Mongolia it breeds only in the far west — mainly Khar Us Nuur, also Achit and Uvs Nuur.",
    f: ["Thrush-sized.", "Long, strong bill.", "Pale eyebrow.", "Warm brown upperparts."],
    si: "East Asian Reed Warbler — slightly smaller, streaked breast; eastern.",
    h: "Tall reedbeds.",
    di: "Khar Us Nuur, Böön Tsagaan, Achit Nuur, Uvs Nuur, Ölgii.",
    mi: "Summer visitor, May–Sep.",
    fo: "Large insects, small frogs.",
    br: "Nest woven around reed stems; often polygynous.",
    be: "Sings from reed tops.",
    v: "A loud, croaking 'karra-karra-kiet'.",
    cu: "The largest warbler in Eurasia.",
    co: "Least Concern.",
    w: "Khar Us Nuur in June.",
    bt: "Jun",
    fa: ["Largest reed warbler.", "Croaking song.", "Far west only."]
  },
  "east-asian-reed-warbler": {
    T: { c: { brown: 0.55, buff: 0.25, white: 0.2 }, hb: ["water"], bk: "long", bh: ["perch"], vt: ["song", "croak"], ac: "day", se: ["summer"], sz: ["18–20 cm", "23–26 cm", "22–30 g"] },
    s: "A large, loud reed warbler with fine grey streaks on the breast. Common in reedbeds of the north and east.",
    d: "The Oriental Reed Warbler breeds in eastern Asia and winters in Southeast Asia. It was formerly lumped with the Great Reed Warbler. In Mongolia it breeds in reedbeds — Khurkh, Ulaanbaatar, Böön Tsagaan, Ganga Nuur and Ögii Nuur.",
    f: ["Large, brown.", "Fine grey streaks on throat and breast.", "Whitish tail tips.", "Dark eyestripe, pale eyebrow."],
    si: "Great Reed Warbler — unstreaked; western.",
    h: "Reedbeds.",
    di: "Khurkh, Ulaanbaatar, Böön Tsagaan, Ganga Nuur, Ögii Nuur, Terkhiin Tsagaan Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Large insects.",
    br: "Nest woven around reed stems.",
    be: "Sings loudly from reed tops.",
    v: "A harsh, grating 'gurk-gurk-kiri'.",
    cu: "Its breast streaks set it apart from the Great Reed Warbler.",
    co: "Least Concern.",
    w: "Ögii Nuur reeds in June.",
    bt: "Jun",
    fa: ["Streaked breast.", "Loud.", "Eastern cousin of Great Reed."]
  },
  "clamorous-reed-warbler": {
    T: { c: { brown: 0.55, buff: 0.3, white: 0.15 }, hb: ["water"], bk: "long", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["18–20 cm", "—", "25–32 g"] },
    s: "A large, long-billed southern reed warbler. On the Mongolian list, no GBIF records.",
    d: "The Clamorous Reed Warbler breeds from Egypt through Pakistan and India to south China and Southeast Asia. Records in Mongolia are exceptional.",
    f: ["Large and long-tailed.", "Very long bill.", "Short wings.", "Plain brown."],
    si: "Great Reed Warbler — longer wings, shorter bill.",
    h: "Reedbeds.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in reeds (not in Mongolia).",
    be: "Noisy.",
    v: "A loud, varied song.",
    cu: "Its Latin name stentoreus refers to Stentor, the loud-voiced Greek herald.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Long bill.", "Southern species.", "Loud voice."]
  },
  "grays-warbler": {
    T: { c: { brown: 0.5, gray: 0.3, buff: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["15–18 cm", "—", "25–32 g"] },
    s: "A large, plain olive-brown grasshopper warbler with a grey breast. A very rare visitor.",
    d: "Gray's Grasshopper Warbler breeds in southern Siberia, northeast China and Korea and winters in Southeast Asia. In Mongolia there is a single GBIF record from the north.",
    f: ["Plain olive-brown upperparts.", "Grey breast.", "Pale eyebrow.", "Large for its group."],
    si: "Thick-billed Warbler — no eyebrow.",
    h: "Forest thickets.",
    di: "Very rare; north.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in thickets (not in Mongolia).",
    be: "Very skulking.",
    v: "A loud, rich song.",
    cu: "Named after the zoologist George Robert Gray.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Grey breast.", "Very skulking.", "Very rare."]
  },
  "japanese-swamp-warbler": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.2 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12–13.5 cm", "—", "11–15 g"] },
    s: "A small, streaked warbler of reedbeds with a long tail. Local in the far east.",
    d: "The Marsh Grassbird lives in reedbeds in China, Japan, Korea, Russia and eastern Mongolia. It is threatened locally by habitat loss. In Mongolia it is known only from wetlands in the far east, mostly in summer.",
    f: ["Streaked brown upperparts.", "Pale underparts.", "Long, graduated tail.", "Pale eyebrow."],
    si: "Rusty-rumped Warbler — rufous rump, white tail tips.",
    h: "Reedbeds.",
    di: "Far east (Dornod).",
    mi: "Summer visitor.",
    fo: "Insects.",
    br: "Nests in reeds.",
    be: "Song flight above reeds.",
    v: "A rattling song given in flight.",
    cu: "Also called Japanese Swamp Warbler.",
    co: "Least Concern; locally threatened by habitat loss.",
    w: "Reedbeds in the far east in July.",
    bt: "Jul",
    fa: ["Streaked.", "Song flight.", "Far east only."]
  },
  "rusty-rumped-warbler": {
    T: { c: { brown: 0.5, rufous: 0.2, buff: 0.2, white: 0.1 }, hb: ["water", "forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "—", "13–17 g"] },
    s: "A heavily streaked grasshopper warbler with a rusty rump and white-tipped tail. Common in wet meadows and thickets.",
    d: "Pallas's Grasshopper Warbler breeds from the Altai and Mongolia to northeast China and Korea and winters from India to Indonesia. In Mongolia it breeds in wet meadows and willow scrub — Khurkh, Böön Tsagaan, Yolyn Am and Orog Nuur.",
    f: ["Streaked back.", "Rusty rump.", "White tips to a dark tail.", "Pale eyebrow."],
    si: "Lanceolated Warbler — smaller, streaked breast, no white tail tips.",
    h: "Wet meadows, reeds, willow scrub.",
    di: "Khurkh, Böön Tsagaan, Yolyn Am, Orog Nuur, Khar Us Nuur, Ulaanbaatar.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground in dense grass.",
    be: "Runs mouse-like through vegetation.",
    v: "A short, scratchy song.",
    cu: "Named after Peter Simon Pallas.",
    co: "Least Concern.",
    w: "Khurkh in June.",
    bt: "Jun",
    fa: ["Rusty rump.", "White tail tips.", "Mouse-like."]
  },
  "middendorffs-warbler": {
    T: { c: { brown: 0.55, buff: 0.3, white: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["15–16 cm", "—", "15–20 g"] },
    s: "A plain, brown grasshopper warbler of northeast Asia. On the Mongolian list, no GBIF records.",
    d: "Middendorff's Grasshopper Warbler breeds from eastern Siberia to northern Japan and Kamchatka and winters in the Philippines, Borneo and Sulawesi. Records in Mongolia are exceptional.",
    f: ["Plain brown upperparts.", "Pale eyebrow.", "White tips to the tail.", "Buff flanks."],
    si: "Rusty-rumped Warbler — streaked back.",
    h: "Coastal scrub and grass.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in grass (not in Mongolia).",
    be: "Skulking.",
    v: "A short, repeated phrase.",
    cu: "Named after the Siberian explorer Alexander von Middendorff.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Plain brown.", "Northeast Asian.", "Skulking."]
  },
  "lanceolated-warbler": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.1, black: 0.1 }, hb: ["water", "forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["11.5–12 cm", "—", "9–12 g"] },
    s: "A tiny, heavily streaked grasshopper warbler with a necklace of fine streaks. Creeps like a mouse in grassy scrub.",
    d: "The Lanceolated Warbler breeds from European Russia to Japan and winters in Southeast Asia. In Mongolia it breeds in wet grassy scrub of the north and east — Khurkh, Terelj and Ulaanbaatar.",
    f: ["Heavily streaked above.", "Fine streaks across the breast.", "Streaked flanks.", "Small and short-tailed."],
    si: "Rusty-rumped Warbler — larger, rufous rump, white tail tips.",
    h: "Wet grassland with bushes.",
    di: "Khurkh, Terelj, Ulaanbaatar, Ganga Nuur, Buir Nuur, Khar Us Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Creeps like a mouse and is hard to flush.",
    v: "A monotonous, insect-like reeling.",
    cu: "Its Latin name means 'spear-shaped', after the breast streaks.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "Jun",
    fa: ["Streaked breast.", "Reeling song.", "Mouse-like."]
  },
  "savis-warbler": {
    T: { c: { brown: 0.6, buff: 0.25, white: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13.5–15 cm", "18–21 cm", "13–20 g"] },
    s: "A plain brown reed-bed warbler with a long, low buzzing song. Local in western lakes.",
    d: "Savi's Warbler breeds in Europe and the western Palearctic and winters in Africa. In Mongolia it breeds only in the reedbeds of the far west — Khar Us Nuur and Orog Nuur.",
    f: ["Unstreaked brown upperparts.", "Plain throat.", "Broad, rounded tail.", "Long undertail coverts."],
    si: "Great Reed Warbler — much larger, pale eyebrow.",
    h: "Reedbeds with bushes.",
    di: "Khar Us Nuur, Orog Nuur, Böön Tsagaan.",
    mi: "Summer visitor, Apr–Sep.",
    fo: "Insects.",
    br: "Nests in reeds; 3–6 eggs.",
    be: "Sings from reed tops at dusk.",
    v: "A low, fast buzzing reel.",
    cu: "Named after the Italian naturalist Paolo Savi.",
    co: "Least Concern.",
    w: "Khar Us Nuur in June evenings.",
    bt: "Jun",
    fa: ["Buzzing song.", "Plain brown.", "Western reedbeds."]
  },
  "chinese-bush-warbler": {
    T: { c: { brown: 0.55, buff: 0.3, white: 0.15 }, hb: ["forest", "water"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["12–13 cm", "—", "10–12 g"] },
    s: "A plain brown bush warbler with a buff wash below and a buzzing song. Breeds in wet meadows of the Khentii.",
    d: "The Chinese Bush Warbler breeds from eastern Siberia to Tibet and south China and winters in northeast India and Southeast Asia. In Mongolia it breeds in the Khentii — Khurkh, Ulaanbaatar and Terelj.",
    f: ["Plain olive-brown upperparts.", "Buff underparts.", "Short pale eyebrow.", "Graduated tail."],
    si: "Savi's Warbler — larger, western.",
    h: "Wet grassy meadows with shrubs.",
    di: "Khurkh, Ulaanbaatar, Terelj, Buir Nuur, Ganga Nuur.",
    mi: "Summer visitor, May–Sep.",
    fo: "Insects.",
    br: "Nests on the ground.",
    be: "Very skulking.",
    v: "A dry, insect-like 'zie-zie-zie'.",
    cu: "Described by Robert Swinhoe in 1871.",
    co: "Least Concern.",
    w: "Terelj meadows in June.",
    bt: "Jun",
    fa: ["Plain brown.", "Insect-like song.", "Khentii meadows."]
  },
  "grasshopper-warbler": {
    T: { c: { brown: 0.5, buff: 0.3, white: 0.1, black: 0.1 }, hb: ["water"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12.5–13.5 cm", "15–19 cm", "11–15 g"] },
    s: "A streaky brown warbler whose song is a long, reeling insect-like trill. An uncommon migrant in the west.",
    d: "The Common Grasshopper Warbler breeds across temperate Europe and the western Palearctic and winters in Africa and India. In Mongolia it is an uncommon migrant in the west — Khar Us Nuur and Uvs Nuur.",
    f: ["Streaked olive-brown upperparts.", "Faint pale eyebrow.", "Lightly streaked undertail.", "Rounded tail."],
    si: "Lanceolated Warbler — heavier breast streaks.",
    h: "Dense grass near water.",
    di: "Khar Us Nuur, Uvs Nuur.",
    mi: "Passage migrant, May–Oct.",
    fo: "Insects.",
    br: "Nests in grass (not in Mongolia).",
    be: "Creeps through grass.",
    v: "A reeling trill that can last minutes.",
    cu: "Its song sounds like a fishing reel.",
    co: "Least Concern.",
    w: "Khar Us Nuur in September.",
    bt: "Sep",
    fa: ["Reeling song.", "Streaky.", "Western migrant."]
  },
  "spotted-bush-warbler": {
    T: { c: { brown: 0.5, gray: 0.25, white: 0.15, black: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12–13 cm", "—", "10–12 g"] },
    s: "A dark bush warbler with a grey face and spotted throat, from the Himalayas and China. On the Mongolian list, no GBIF records.",
    d: "The Spotted Bush Warbler lives in the Himalayas, Yunnan and central China. Records in Mongolia are exceptional.",
    f: ["Dark brown upperparts.", "Grey face and breast.", "Dark spots on the throat.", "Barred undertail."],
    si: "Chinese Bush Warbler — plain throat.",
    h: "Mountain scrub.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Insects.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Skulking.",
    v: "A repeated buzzing phrase.",
    cu: "Its Latin name thoracica refers to the spotted chest.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Spotted throat.", "Himalayan species.", "Skulking."]
  }
});
