B2T("fr", {
  "thick-billed-warbler": {
    name: "Rousserolle à gros bec",
    s: "Grande rousserolle brun uni au bec court et épais, à tête ronde et à l’air « étonné ». Commune dans les fourrés du nord et de l’est.",
    d: "La Rousserolle à gros bec niche du sud de la Sibérie à la Mongolie et au nord-est de la Chine et hiverne en Asie du Sud et du Sud-Est. Elle est presque aussi grande que la Rousserolle turdoïde. En Mongolie, elle niche dans les broussailles riveraines denses — Khurkh, Oulan-Bator, Terelj et Yolyn Am.",
    f: ["Dessus brun uni.", "Bec court et épais.", "Pas de sourcil ; lores pâles.", "Longue queue arrondie."],
    si: "Rousserolle d’Orient — sourcil pâle, bec long, vit dans les roseaux.",
    h: "Fourrés denses, berges buissonnantes, lisières.",
    di: "Khurkh, Oulan-Bator, Yolyn Am, Terelj, lac Orog, lac Ganga.",
    mi: "Estivante, mai–septembre.",
    fo: "Gros insectes.",
    br: "Niche bas dans un buisson ; 5 à 6 œufs.",
    be: "Discrète, mais chante du sommet d’un buisson.",
    v: "Un chant sonore et varié, avec imitations.",
    cu: "Sa face « vide », sans sourcil, est le meilleur critère.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Bec épais.", "Sans sourcil.", "Grande et unie."]
  },
  "sykess-warbler": {
    name: "Hypolaïs rama",
    s: "Petite hypolaïs gris-brun pâle des broussailles désertiques. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "L’Hypolaïs rama niche de l’Arabie au Turkestan et à l’ouest de la Chine et hiverne dans le sous-continent indien. Elle était autrefois réunie à l’Hypolaïs bottée. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dessus gris-brun pâle.", "Court sourcil pâle.", "Bec long et fin.", "Queue carrée à bords pâles."],
    si: "Rousserolle des buissons — plus sombre, queue arrondie.",
    h: "Tamaris et broussailles désertiques.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Abaisse la queue par saccades.",
    v: "Un chant bavard et décousu.",
    cu: "Son nom anglais honore le colonel William Henry Sykes, de l’Inde britannique.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Pâle.", "Broussailles désertiques.", "Séparée de l’Hypolaïs bottée."]
  },
  "black-browed-reed-warbler": {
    name: "Rousserolle de Schrenck",
    s: "Petite rousserolle au sourcil crème bordé au-dessus d’une bande noire. Locale dans les zones humides de l’est.",
    d: "La Rousserolle de Schrenck niche de l’est de la Mongolie et du sud-est de la Russie à l’est de la Chine et au Japon et hiverne en Asie du Sud-Est. En Mongolie, elle niche dans les roselières et prairies humides de l’est — lac Ganga, lac Buir et région de Daguur.",
    f: ["Sourcil crème.", "Bande noire au-dessus du sourcil.", "Dessus brun chaud.", "Dessous blanchâtre."],
    si: "Rousserolle isabelle — sans bande coronale noire, plus pâle.",
    h: "Roselières et prairies humides à laîches.",
    di: "Lac Ganga, lac Buir, Khurkh, Daguur, Onon.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche bas dans les roseaux ou l’herbe.",
    be: "Se nourrit près du sol dans les roseaux.",
    v: "Un chant varié et grinçant.",
    cu: "Décrite par Robert Swinhoe en 1860.",
    co: "Préoccupation mineure.",
    w: "Roseaux du lac Buir en juillet.",
    bt: "juin–juil.",
    fa: ["Sourcil bordé de noir.", "Zones humides de l’est.", "Petite rousserolle."]
  },
  "blyths-reed-warbler": {
    name: "Rousserolle des buissons",
    s: "Rousserolle brun froid uni des buissons et lisières, au superbe chant imitateur. Commune dans l’extrême ouest.",
    d: "La Rousserolle des buissons niche dans tout le Paléarctique et hiverne en Asie du Sud. Elle s’étend vers l’ouest en Europe. En Mongolie, elle niche dans les vallées buissonnantes de l’ouest — surtout autour du lac Khar Us.",
    f: ["Dessus gris-brun uni.", "Court sourcil pâle.", "Ailes courtes et arrondies.", "Pattes grisâtres."],
    si: "Rousserolle isabelle — plus chaude, sourcil plus net, bord de calotte sombre.",
    h: "Buissons, lisières et hautes herbes.",
    di: "Lac Khar Us, Tavan Bogd, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche dans les hautes herbes ou buissons.",
    be: "Chante la nuit comme le jour.",
    v: "Des phrases lentes et répétées, pleines d’imitations.",
    cu: "Nommée d’après le zoologiste Edward Blyth.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en juin.",
    bt: "juin–juil.",
    fa: ["Grande imitatrice.", "Brun uni.", "S’étend vers l’ouest en Europe."]
  },
  "paddyfield-warbler": {
    name: "Rousserolle isabelle",
    s: "Petite rousserolle brun chaud au net sourcil blanc et bec court. Commune dans les roselières des lacs de l’ouest.",
    d: "La Rousserolle isabelle niche dans le Paléarctique central tempéré et hiverne en Inde et au Pakistan. En Mongolie, elle niche dans les roselières et broussailles humides des lacs de l’ouest et du Gobi — lac Khar Us, Böön Tsagaan et lac Orog.",
    f: ["Dessus brun chaud.", "Net sourcil blanc.", "Trait sombre au bord de la calotte.", "Bec court."],
    si: "Rousserolle de Schrenck — nette bande noire au-dessus du sourcil.",
    h: "Roselières et broussailles lacustres.",
    di: "Lac Khar Us, Khurkh, Böön Tsagaan, lac Orog, Oulan-Bator, lac Ganga.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche dans les roseaux.",
    be: "Redresse souvent la queue.",
    v: "Un chant rapide et bavard.",
    cu: "Son nom latin agricola signifie « paysan ».",
    co: "Préoccupation mineure.",
    w: "Roseaux du lac Khar Us en juin.",
    bt: "juin",
    fa: ["Sourcil blanc.", "Queue redressée.", "Lacs de l’ouest."]
  },
  "great-reed-warbler": {
    name: "Rousserolle turdoïde",
    s: "La plus grande rousserolle, de la taille d’une grive, au chant rauque et sonore « karra-karra ». Locale dans les roselières de l’ouest.",
    d: "La Rousserolle turdoïde niche dans toute l’Europe et le Paléarctique occidental et hiverne en Afrique subsaharienne. En Mongolie, elle ne niche que dans l’extrême ouest — surtout au lac Khar Us, aussi aux lacs Achit et Uvs.",
    f: ["Taille d’une grive.", "Bec long et fort.", "Sourcil pâle.", "Dessus brun chaud."],
    si: "Rousserolle d’Orient — un peu plus petite, poitrine striée ; à l’est.",
    h: "Hautes roselières.",
    di: "Lac Khar Us, Böön Tsagaan, lac Achit, lac Uvs, Ölgii.",
    mi: "Estivante, mai–septembre.",
    fo: "Gros insectes, petites grenouilles.",
    br: "Nid tissé autour des tiges ; souvent polygyne.",
    be: "Chante au sommet des roseaux.",
    v: "Un « karra-karra-kiet » rauque et sonore.",
    cu: "La plus grande fauvette d’Eurasie.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en juin.",
    bt: "juin",
    fa: ["Plus grande rousserolle.", "Chant rauque.", "Extrême ouest seulement."]
  },
  "east-asian-reed-warbler": {
    name: "Rousserolle d’Orient",
    s: "Grande rousserolle bruyante à fines stries grises sur la poitrine. Commune dans les roselières du nord et de l’est.",
    d: "La Rousserolle d’Orient niche en Asie orientale et hiverne en Asie du Sud-Est. Elle était autrefois réunie à la Rousserolle turdoïde. En Mongolie, elle niche dans les roselières — Khurkh, Oulan-Bator, Böön Tsagaan, lac Ganga et lac Ögii.",
    f: ["Grande, brune.", "Fines stries grises sur gorge et poitrine.", "Pointes de la queue blanchâtres.", "Trait oculaire sombre, sourcil pâle."],
    si: "Rousserolle turdoïde — sans stries ; à l’ouest.",
    h: "Roselières.",
    di: "Khurkh, Oulan-Bator, Böön Tsagaan, lac Ganga, lac Ögii, Terkhiin Tsagaan Nuur.",
    mi: "Estivante, mai–septembre.",
    fo: "Gros insectes.",
    br: "Nid tissé autour des tiges de roseaux.",
    be: "Chante fort au sommet des roseaux.",
    v: "Un « gourk-gourk-kiri » rauque et grinçant.",
    cu: "Ses stries pectorales la distinguent de la turdoïde.",
    co: "Préoccupation mineure.",
    w: "Roseaux du lac Ögii en juin.",
    bt: "juin",
    fa: ["Poitrine striée.", "Bruyante.", "Cousine orientale de la turdoïde."]
  },
  "clamorous-reed-warbler": {
    name: "Rousserolle stentor",
    s: "Grande rousserolle méridionale au long bec. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "La Rousserolle stentor niche de l’Égypte au Pakistan, à l’Inde, au sud de la Chine et à l’Asie du Sud-Est. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Grande, à longue queue.", "Très long bec.", "Ailes courtes.", "Brun uni."],
    si: "Rousserolle turdoïde — ailes plus longues, bec plus court.",
    h: "Roselières.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les roseaux (pas en Mongolie).",
    be: "Bruyante.",
    v: "Un chant sonore et varié.",
    cu: "Son nom évoque Stentor, le héraut grec à la voix puissante.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Long bec.", "Espèce méridionale.", "Voix puissante."]
  },
  "grays-warbler": {
    name: "Locustelle fasciée",
    s: "Grande locustelle brun olive uni à poitrine grise. Visiteuse très rare.",
    d: "La Locustelle fasciée niche dans le sud de la Sibérie, le nord-est de la Chine et en Corée et hiverne en Asie du Sud-Est. En Mongolie, il n’existe qu’une mention GBIF, dans le nord.",
    f: ["Dessus brun olive uni.", "Poitrine grise.", "Sourcil pâle.", "Grande pour une locustelle."],
    si: "Rousserolle à gros bec — sans sourcil.",
    h: "Fourrés forestiers.",
    di: "Très rare ; nord.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les fourrés (pas en Mongolie).",
    be: "Très discrète.",
    v: "Un chant sonore et riche.",
    cu: "Son nom anglais honore le zoologiste George Robert Gray.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Poitrine grise.", "Très discrète.", "Très rare."]
  },
  "japanese-swamp-warbler": {
    name: "Locustelle du Japon",
    s: "Petite fauvette striée des roselières, à longue queue. Locale dans l’extrême est.",
    d: "La Locustelle du Japon vit dans les roselières de Chine, du Japon, de Corée, de Russie et de l’est de la Mongolie. La perte d’habitat la menace localement. En Mongolie, elle n’est connue que des zones humides de l’extrême est, surtout en été.",
    f: ["Dessus brun strié.", "Dessous pâle.", "Longue queue étagée.", "Sourcil pâle."],
    si: "Locustelle de Pallas — croupion roux, pointes de queue blanches.",
    h: "Roselières.",
    di: "Extrême est (Dornod).",
    mi: "Estivante.",
    fo: "Insectes.",
    br: "Niche dans les roseaux.",
    be: "Vol chanté au-dessus des roseaux.",
    v: "Un chant crépitant émis en vol.",
    cu: "Aussi appelée « fauvette des marais du Japon ».",
    co: "Préoccupation mineure ; menacée localement par la perte d’habitat.",
    w: "Roselières de l’extrême est en juillet.",
    bt: "juil.",
    fa: ["Striée.", "Vol chanté.", "Extrême est seulement."]
  },
  "rusty-rumped-warbler": {
    name: "Locustelle de Pallas",
    s: "Locustelle très striée au croupion roux et à la queue tachée de blanc. Commune dans les prairies humides et les fourrés.",
    d: "La Locustelle de Pallas niche de l’Altaï et de la Mongolie au nord-est de la Chine et à la Corée et hiverne de l’Inde à l’Indonésie. En Mongolie, elle niche dans les prairies humides et fourrés de saules — Khurkh, Böön Tsagaan, Yolyn Am et lac Orog.",
    f: ["Dos strié.", "Croupion roux.", "Pointes blanches à la queue sombre.", "Sourcil pâle."],
    si: "Locustelle lancéolée — plus petite, poitrine striée, sans pointes blanches.",
    h: "Prairies humides, roseaux, fourrés de saules.",
    di: "Khurkh, Böön Tsagaan, Yolyn Am, lac Orog, lac Khar Us, Oulan-Bator.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol dans l’herbe dense.",
    be: "Court comme une souris dans la végétation.",
    v: "Un chant bref et grinçant.",
    cu: "Nommée d’après Peter Simon Pallas.",
    co: "Préoccupation mineure.",
    w: "Khurkh en juin.",
    bt: "juin",
    fa: ["Croupion roux.", "Pointes de queue blanches.", "Comme une souris."]
  },
  "middendorffs-warbler": {
    name: "Locustelle de Middendorff",
    s: "Locustelle brune et unie d’Asie du Nord-Est. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "La Locustelle de Middendorff niche de la Sibérie orientale au nord du Japon et au Kamtchatka et hiverne aux Philippines, à Bornéo et à Sulawesi. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dessus brun uni.", "Sourcil pâle.", "Pointes blanches à la queue.", "Flancs chamois."],
    si: "Locustelle de Pallas — dos strié.",
    h: "Broussailles et herbes côtières.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans l’herbe (pas en Mongolie).",
    be: "Discrète.",
    v: "Une courte phrase répétée.",
    cu: "Nommée d’après l’explorateur de la Sibérie Alexander von Middendorff.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Brun uni.", "Asie du Nord-Est.", "Discrète."]
  },
  "lanceolated-warbler": {
    name: "Locustelle lancéolée",
    s: "Minuscule locustelle très striée au « collier » de fines stries. Se faufile comme une souris dans les broussailles herbeuses.",
    d: "La Locustelle lancéolée niche de la Russie d’Europe au Japon et hiverne en Asie du Sud-Est. En Mongolie, elle niche dans les broussailles herbeuses humides du nord et de l’est — Khurkh, Terelj et Oulan-Bator.",
    f: ["Dessus très strié.", "Fines stries en travers de la poitrine.", "Flancs striés.", "Petite, queue courte."],
    si: "Locustelle de Pallas — plus grande, croupion roux, pointes de queue blanches.",
    h: "Prairies humides buissonnantes.",
    di: "Khurkh, Terelj, Oulan-Bator, lac Ganga, lac Buir, lac Khar Us.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Se faufile comme une souris, difficile à lever.",
    v: "Un grésillement monotone d’insecte.",
    cu: "Son nom latin signifie « en forme de lance », d’après les stries.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Poitrine striée.", "Chant d’insecte.", "Comme une souris."]
  },
  "savis-warbler": {
    name: "Locustelle luscinioïde",
    s: "Locustelle brun uni des roselières, au long chant grave et bourdonnant. Locale sur les lacs de l’ouest.",
    d: "La Locustelle luscinioïde niche en Europe et dans le Paléarctique occidental et hiverne en Afrique. En Mongolie, elle ne niche que dans les roselières de l’extrême ouest — lac Khar Us et lac Orog.",
    f: ["Dessus brun sans stries.", "Gorge unie.", "Queue large et arrondie.", "Longues sous-caudales."],
    si: "Rousserolle turdoïde — bien plus grande, sourcil pâle.",
    h: "Roselières avec buissons.",
    di: "Lac Khar Us, lac Orog, Böön Tsagaan.",
    mi: "Estivante, avril–septembre.",
    fo: "Insectes.",
    br: "Niche dans les roseaux ; 3 à 6 œufs.",
    be: "Chante au sommet des roseaux au crépuscule.",
    v: "Un grésillement grave et rapide.",
    cu: "Nommée d’après le naturaliste italien Paolo Savi.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us les soirs de juin.",
    bt: "juin",
    fa: ["Chant bourdonnant.", "Brun uni.", "Roselières de l’ouest."]
  },
  "chinese-bush-warbler": {
    name: "Bouscarle de Taczanowski",
    s: "Bouscarle brun uni, lavée de chamois dessous, au chant bourdonnant. Niche dans les prairies humides du Khentii.",
    d: "La Bouscarle de Taczanowski niche de la Sibérie orientale au Tibet et au sud de la Chine et hiverne dans le nord-est de l’Inde et en Asie du Sud-Est. En Mongolie, elle niche dans le Khentii — Khurkh, Oulan-Bator et Terelj.",
    f: ["Dessus brun olive uni.", "Dessous chamois.", "Court sourcil pâle.", "Queue étagée."],
    si: "Locustelle luscinioïde — plus grande, à l’ouest.",
    h: "Prairies humides herbeuses avec arbustes.",
    di: "Khurkh, Oulan-Bator, Terelj, lac Buir, lac Ganga.",
    mi: "Estivante, mai–septembre.",
    fo: "Insectes.",
    br: "Niche au sol.",
    be: "Très discrète.",
    v: "Un « zi-zi-zi » sec d’insecte.",
    cu: "Décrite par Robert Swinhoe en 1871.",
    co: "Préoccupation mineure.",
    w: "Prairies de Terelj en juin.",
    bt: "juin",
    fa: ["Brun uni.", "Chant d’insecte.", "Prairies du Khentii."]
  },
  "grasshopper-warbler": {
    name: "Locustelle tachetée",
    s: "Locustelle brune striée dont le chant est un long grésillement d’insecte. Migratrice peu commune dans l’ouest.",
    d: "La Locustelle tachetée niche dans l’Europe tempérée et le Paléarctique occidental et hiverne en Afrique et en Inde. En Mongolie, c’est une migratrice peu commune dans l’ouest — lac Khar Us et lac Uvs.",
    f: ["Dessus brun olive strié.", "Faible sourcil pâle.", "Sous-caudales légèrement striées.", "Queue arrondie."],
    si: "Locustelle lancéolée — stries pectorales plus marquées.",
    h: "Herbes denses près de l’eau.",
    di: "Lac Khar Us, lac Uvs.",
    mi: "Migratrice, mai–octobre.",
    fo: "Insectes.",
    br: "Niche dans l’herbe (pas en Mongolie).",
    be: "Se faufile dans l’herbe.",
    v: "Un grésillement pouvant durer plusieurs minutes.",
    cu: "Son chant évoque un moulinet de pêche.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en septembre.",
    bt: "sept.",
    fa: ["Chant grésillant.", "Striée.", "Migratrice de l’ouest."]
  },
  "spotted-bush-warbler": {
    name: "Bouscarle tachetée",
    s: "Bouscarle sombre à face grise et gorge tachetée, de l’Himalaya et de Chine. Inscrite pour la Mongolie, sans mention GBIF.",
    d: "La Bouscarle tachetée vit dans le nord de l’Himalaya, au Yunnan et en Chine centrale. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Dessus brun sombre.", "Face et poitrine grises.", "Taches sombres sur la gorge.", "Sous-caudales barrées."],
    si: "Bouscarle de Taczanowski — gorge unie.",
    h: "Broussailles de montagne.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Insectes.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Discrète.",
    v: "Une phrase bourdonnante répétée.",
    cu: "Son nom latin thoracica évoque la poitrine tachetée.",
    co: "Préoccupation mineure.",
    w: "Non attendue.",
    bt: "—",
    fa: ["Gorge tachetée.", "Espèce himalayenne.", "Discrète."]
  }
});
