B2T("en", {
  "common-chaffinch": {
    T: { c: { rufous: 0.3, gray: 0.25, brown: 0.2, white: 0.15, black: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage", "winter"], sz: ["14.5–16 cm", "24.5–28.5 cm", "18–29 g"] },
    s: "A finch with two bold white wing bars; the male has a blue-grey cap and rusty-pink breast. A regular migrant and winter visitor, mostly in the west and Ulaanbaatar.",
    d: "The Common Chaffinch breeds across Europe and western Asia and is one of Europe's commonest birds. In Mongolia it is a regular migrant and winterer, often with Bramblings — Ulaanbaatar, Khar Us Nuur and Yolyn Am.",
    f: ["Two bold white wing bars.", "Male: blue-grey cap, pinkish-rust breast.", "Female: olive-brown.", "White outer tail feathers."],
    si: "Brambling — orange shoulder, white rump.",
    h: "Woods, parks and bushes.",
    di: "Ulaanbaatar, Khar Us Nuur, Yolyn Am, Khurkh, Terelj, Uvs Nuur.",
    mi: "Migrant and winter visitor, Sep–May.",
    fo: "Seeds; insects in summer.",
    br: "Neat cup nest in a fork (not regularly in Mongolia).",
    be: "Feeds on the ground in flocks.",
    v: "A rattling song ending in a flourish; 'pink' call.",
    cu: "Its Latin name coelebs means 'bachelor' — females often migrate separately.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in October.",
    bt: "Sep–Oct",
    fa: ["Two white wing bars.", "'Bachelor' finch.", "Winter visitor."]
  },
  "brambling": {
    T: { c: { rufous: 0.35, black: 0.25, white: 0.25, brown: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage", "winter"], sz: ["14–16 cm", "25–26 cm", "17–30 g"] },
    s: "A northern finch with an orange breast and shoulders and a white rump. A common migrant in flocks across Mongolia.",
    d: "The Brambling breeds in the birch and conifer forests of the north and migrates in flocks, sometimes of millions. In Mongolia it passes through in numbers in April–May and September–October — Ulaanbaatar, Khurkh, Khar Us Nuur and Yolyn Am.",
    f: ["Orange breast and shoulders.", "White rump.", "Male: black head in summer.", "Spotted flanks."],
    si: "Common Chaffinch — no white rump, grey cap.",
    h: "Birch forest; any trees and fields on passage.",
    di: "Ulaanbaatar, Khurkh, Khar Us Nuur, Yolyn Am, Khövsgöl, Terelj.",
    mi: "Passage migrant, Apr–May and Sep–Oct.",
    fo: "Seeds, beech mast; insects in summer.",
    br: "Nests in northern birches.",
    be: "Travels in large flocks.",
    v: "A wheezing 'dzweee' song; nasal 'tchway' call.",
    cu: "Winter roosts in Europe can hold millions of birds.",
    co: "Least Concern.",
    w: "Ulaanbaatar in late September.",
    bt: "Sep–Oct",
    fa: ["Orange breast.", "White rump.", "Huge flocks."]
  },
  "hawfinch": {
    T: { c: { brown: 0.35, rufous: 0.2, gray: 0.15, black: 0.15, white: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["16.5–18 cm", "29–33 cm", "48–62 g"] },
    s: "A stocky finch with a huge conical bill that can crack cherry stones. Common in Ulaanbaatar on passage, breeds in the north.",
    d: "The Hawfinch breeds across Europe and temperate Asia; Asian birds migrate south in winter. In Mongolia it breeds in northern woods and passes through in numbers, especially in May — Ulaanbaatar, Yolyn Am, Khurkh and Terelj.",
    f: ["Massive conical bill.", "Orange-brown head, grey collar.", "Black bib and eye patch.", "Broad white wing bar."],
    si: "Yellow-billed Grosbeak — yellow bill, black head (male).",
    h: "Deciduous woods, parks and gardens.",
    di: "Ulaanbaatar, Yolyn Am, Khurkh, Terelj, Khustai, Ikh Nart.",
    mi: "Summer visitor and migrant; some winter.",
    fo: "Hard seeds and fruit stones.",
    br: "Nests in trees.",
    be: "Shy; stays high in trees.",
    v: "A sharp, clicking 'tsik'.",
    cu: "Its bill can exert a force of over 45 kg.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in May.",
    bt: "May",
    fa: ["Huge bill.", "Cracks cherry stones.", "Common in May."]
  },
  "yellow-billed-grosbeak": {
    T: { c: { gray: 0.35, black: 0.25, yellow: 0.2, white: 0.1, brown: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["15–18 cm", "—", "40–55 g"] },
    s: "A grey grosbeak with a big yellow bill; the male has a glossy black head. A scarce spring migrant in the Gobi and east.",
    d: "The Chinese Grosbeak breeds in the Russian Far East, Manchuria, Korea and China. In Mongolia it is a scarce spring migrant, mostly in May — Yolyn Am and Ganga Nuur.",
    f: ["Large yellow bill with dark tip.", "Male: glossy black head.", "Grey body.", "Black wings with white tips."],
    si: "Hawfinch — brown, grey bill.",
    h: "Woods and gardens.",
    di: "Yolyn Am, Ganga Nuur, Gobi oases.",
    mi: "Passage migrant, May.",
    fo: "Seeds, buds, fruit.",
    br: "Nests in trees (not in Mongolia).",
    be: "Travels in small flocks.",
    v: "A melodious whistled song.",
    cu: "A popular cage bird in China.",
    co: "Least Concern.",
    w: "Yolyn Am in May.",
    bt: "May",
    fa: ["Yellow bill.", "Black head.", "Scarce spring migrant."]
  },
  "great-rosefinch": {
    T: { c: { red: 0.45, white: 0.2, gray: 0.2, brown: 0.15 }, hb: ["mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["19–21 cm", "—", "40–50 g"] },
    s: "A large rosefinch; the male is deep crimson with white spots. Local in the high mountains of the far west.",
    d: "The Great Rosefinch lives in the high mountains from the Caucasus to Central Asia and China. In Mongolia it lives in the high Altai and Mongol Altai — Khar Us Nuur area, Ölgii and Achit Nuur.",
    f: ["Large size.", "Male: crimson with white spots.", "Female: grey-brown, streaked.", "Heavy bill."],
    si: "Red-mantled Rosefinch — smaller, pink eyebrow.",
    h: "High rocky slopes and alpine scrub.",
    di: "Khar Us Nuur, Yolyn Am, Ölgii, Achit Nuur, Orog Nuur.",
    mi: "Resident; moves lower in winter.",
    fo: "Seeds and buds.",
    br: "Nests among rocks or bushes.",
    be: "Feeds on the ground.",
    v: "A soft whistled song.",
    cu: "The largest rosefinch in Mongolia.",
    co: "Least Concern.",
    w: "High Altai in June.",
    bt: "Jun",
    fa: ["Crimson with white spots.", "Largest rosefinch.", "High mountains."]
  },
  "long-tailed-rosefinch": {
    T: { c: { red: 0.35, white: 0.25, brown: 0.2, gray: 0.2 }, hb: ["forest", "water", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["15–18 cm", "—", "15–18 g"] },
    s: "A small pink finch with a long white-edged tail and white wing bars. Very common around Ulaanbaatar all year.",
    d: "The Siberian Long-tailed Rosefinch lives in willow thickets and forest edges from Kazakhstan to Japan. In Mongolia it is very common year-round in the north — Ulaanbaatar (especially along the Tuul), Terelj and Khurkh.",
    f: ["Long tail with white edges.", "Male: rose-pink with frosty white face.", "Two white wing bars.", "Stubby bill."],
    si: "Pallas's Rosefinch — no long tail or white wing bars.",
    h: "Willow thickets, riverbanks, forest edges.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khar Us Nuur, Yolyn Am, Buir Nuur.",
    mi: "Resident.",
    fo: "Seeds of weeds and herbs.",
    br: "Nests in bushes.",
    be: "Flicks its long tail.",
    v: "A soft, trilling song; 'pee-pee-pee' call.",
    cu: "Common in the cage-bird trade, so European records are doubtful.",
    co: "Least Concern.",
    w: "Tuul River in Ulaanbaatar in winter.",
    bt: "All year",
    fa: ["Long tail.", "Pink.", "Common in Ulaanbaatar."]
  },
  "pallass-rosefinch": {
    T: { c: { red: 0.5, white: 0.2, brown: 0.2, gray: 0.1 }, hb: ["forest", "mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["winter"], sz: ["15–17 cm", "—", "22–30 g"] },
    s: "A beautiful raspberry-pink finch with a frosty-white scaled crown and throat. A winter visitor to the north.",
    d: "Pallas's Rosefinch breeds in the boreal forests of Siberia and winters in Mongolia, China, Korea and Japan. In Mongolia it winters in the north — Ulaanbaatar, Terkhiin Tsagaan Nuur, Khar Us Nuur and Terelj.",
    f: ["Male: deep raspberry-pink.", "Silvery scaling on crown and throat.", "Two pale wing bars.", "Female: streaked brown with pink rump."],
    si: "Long-tailed Rosefinch — long white-edged tail.",
    h: "Forest edges, scrub and hillsides in winter.",
    di: "Ulaanbaatar, Terkhiin Tsagaan Nuur, Khar Us Nuur, Terelj, Yolyn Am, Khövsgöl.",
    mi: "Winter visitor, Oct–Apr.",
    fo: "Seeds and buds.",
    br: "Nests in Siberian forests (not in Mongolia).",
    be: "Feeds in small flocks.",
    v: "A soft 'zit' call.",
    cu: "Named after Peter Simon Pallas.",
    co: "Least Concern.",
    w: "Bogd Khan Uul slopes in March.",
    bt: "Nov–Mar",
    fa: ["Raspberry pink.", "Frosty crown.", "Winter visitor."]
  },
  "red-mantled-rosefinch": {
    T: { c: { red: 0.4, brown: 0.3, gray: 0.2, white: 0.1 }, hb: ["mountain"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident", "winter"], sz: ["15–17 cm", "—", "25–30 g"] },
    s: "A rosefinch with a pink eyebrow and rose-flushed back. Mainly in the far west, especially around Khar Us Nuur in autumn and winter.",
    d: "The Red-mantled Rosefinch lives in the mountains of Central Asia, from Afghanistan to western China and Mongolia. In Mongolia it is found in the west, with most records around Khar Us Nuur in autumn and winter.",
    f: ["Pink eyebrow and throat.", "Rose-washed brown mantle.", "Pink rump.", "Female: streaked brown."],
    si: "Great Rosefinch — larger, white spots.",
    h: "Juniper and mountain scrub.",
    di: "Khar Us Nuur, Yolyn Am, Ulaanbaatar, Ölgii.",
    mi: "Resident and winter visitor.",
    fo: "Seeds and berries, especially juniper.",
    br: "Nests in juniper and bushes.",
    be: "Feeds low in scrub.",
    v: "A sweet, warbling song.",
    cu: "Its Mongolian name refers to juniper, its favourite habitat.",
    co: "Least Concern.",
    w: "Khar Us Nuur in October.",
    bt: "Sep–Oct",
    fa: ["Pink eyebrow.", "Juniper lover.", "Far west."]
  },
  "p-re-davids-rosefinch": {
    T: { c: { red: 0.4, brown: 0.35, buff: 0.15, white: 0.1 }, hb: ["mountain", "desert"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–15 cm", "—", "18–25 g"] },
    s: "A small rosefinch with a streaked brown back and pink underparts and eyebrow. Breeds in the Gobi mountains, especially Yolyn Am.",
    d: "The Chinese Beautiful Rosefinch lives in northern China and Mongolia. In Mongolia it breeds in the scrubby gorges of the Gobi — above all Yolyn Am, where most records come from.",
    f: ["Male: pink eyebrow and underparts.", "Streaked brown back.", "Pale pink rump.", "Female: streaked brown."],
    si: "Long-tailed Rosefinch — long tail, white wing bars.",
    h: "Scrubby mountain gorges.",
    di: "Yolyn Am, Ikh Nart, Gobi Gurvan Saikhan.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds.",
    br: "Nests in bushes.",
    be: "Feeds low in shrubs.",
    v: "A soft 'tchip'.",
    cu: "Named after the French missionary-naturalist Armand David.",
    co: "Not evaluated separately by the IUCN.",
    w: "Yolyn Am in June.",
    bt: "Jun",
    fa: ["Pink eyebrow.", "Gobi gorges.", "Yolyn Am specialty."]
  },
  "pine-grosbeak": {
    T: { c: { red: 0.4, gray: 0.3, yellow: 0.1, black: 0.1, white: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song", "whistle"], ac: "day", se: ["winter"], sz: ["19–22 cm", "30–35 cm", "50–65 g"] },
    s: "A large, plump, tame finch; the male is rosy-red, the female golden-olive. A scarce winter visitor to Ulaanbaatar and Terelj.",
    d: "The Pine Grosbeak lives in coniferous forests across the northern Holarctic. It eats mainly fruit, especially rowan berries. In Mongolia it is a winter visitor to the Khentii — mainly Ulaanbaatar and Terelj.",
    f: ["Large and long-tailed.", "Male: rosy red.", "Female: golden-olive head.", "Two white wing bars."],
    si: "Red Crossbill — crossed bill, shorter tail.",
    h: "Coniferous forest; berry trees in winter.",
    di: "Ulaanbaatar, Terelj, Onon, Orkhon.",
    mi: "Winter visitor, Nov–Apr.",
    fo: "Berries, buds and seeds.",
    br: "Nests in conifers (rarely in Mongolia).",
    be: "Remarkably tame.",
    v: "A fluty whistled 'tee-tew-tee'.",
    cu: "So tame it can sometimes be picked up by hand.",
    co: "Least Concern.",
    w: "Terelj rowan trees in winter.",
    bt: "Dec–Feb",
    fa: ["Very tame.", "Berry eater.", "Winter visitor."]
  },
  "eurasian-bullfinch": {
    T: { c: { red: 0.3, gray: 0.3, black: 0.25, white: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["whistle"], ac: "day", se: ["winter"], sz: ["14.5–16.5 cm", "22–29 cm", "21–38 g"] },
    s: "A plump finch with a black cap; the male has a rosy-red or grey breast. A winter visitor to Ulaanbaatar.",
    d: "The Eurasian Bullfinch breeds across Eurasia. The Siberian grey-breasted form (cineracea) and red-breasted birds both occur in Mongolia in winter — mainly Ulaanbaatar, Khar Us Nuur and Terelj.",
    f: ["Black cap and tail.", "Male: rosy-red breast (grey in cineracea).", "Grey back.", "White rump."],
    si: "Pine Grosbeak — larger, no black cap.",
    h: "Woods, parks and gardens.",
    di: "Ulaanbaatar, Khar Us Nuur, Terelj, Yolyn Am.",
    mi: "Winter visitor, Oct–Apr.",
    fo: "Buds, seeds and berries.",
    br: "Nests in shrubs (not regularly in Mongolia).",
    be: "Moves quietly in pairs.",
    v: "A soft, piping 'pew'.",
    cu: "Can learn to whistle human tunes.",
    co: "Least Concern.",
    w: "Ulaanbaatar parks in November.",
    bt: "Nov–Feb",
    fa: ["Black cap.", "Piping call.", "Winter visitor."]
  },
  "mongolian-finch": {
    T: { c: { buff: 0.4, brown: 0.25, white: 0.2, red: 0.15 }, hb: ["desert", "mountain"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–15 cm", "—", "20–25 g"] },
    s: "A sandy desert finch with pink and white wing panels and a stubby bill. Common in the rocky semi-deserts of the west and Gobi.",
    d: "The Mongolian Finch lives in the arid mountains of Central Asia. In Mongolia it is common in rocky desert and dry slopes — Khar Us Nuur, Yolyn Am, Orog Nuur and Böön Tsagaan.",
    f: ["Sandy-buff body.", "Pink and white wing panels.", "Short, thick yellowish bill.", "Male: pink flush in breeding season."],
    si: "Desert Finch — black-and-pink wings, black bill.",
    h: "Rocky semi-desert and dry mountain slopes.",
    di: "Khar Us Nuur, Yolyn Am, Orog Nuur, Böön Tsagaan, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Summer visitor, Apr–Oct; some stay.",
    fo: "Seeds.",
    br: "Nests among rocks.",
    be: "Drinks at springs in flocks.",
    v: "A soft, rising 'djou-voo'.",
    cu: "Also called the Mongolian Trumpeter Finch.",
    co: "Least Concern.",
    w: "Springs at Yolyn Am in June.",
    bt: "Jun–Jul",
    fa: ["Pink wing panels.", "Desert finch.", "Named after Mongolia."]
  },
  "plain-mountain-finch": {
    T: { c: { brown: 0.5, buff: 0.3, gray: 0.1, white: 0.1 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–17 cm", "—", "20–25 g"] },
    s: "A sparrow-like brown mountain finch with streaked back and pale wing bars. Local in the high Altai.",
    d: "Hodgson's Mountain Finch lives in the Himalayas and high mountains of Central Asia. In Mongolia it is found only in the high Altai — Tavan Bogd, Khar Us Nuur and Ölgii.",
    f: ["Streaked brown back.", "Plain buff-grey underparts.", "Pale wing bars.", "Forked tail."],
    si: "Brandt's Mountain Finch — darker head, pink rump.",
    h: "High alpine meadows and scree.",
    di: "Tavan Bogd, Khar Us Nuur, Ölgii.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds.",
    br: "Nests in rock crevices.",
    be: "Feeds on the ground in flocks.",
    v: "A twittering song.",
    cu: "Looks remarkably like a House Sparrow.",
    co: "Least Concern.",
    w: "Tavan Bogd in July.",
    bt: "Jul",
    fa: ["Sparrow-like.", "High Altai.", "Streaked back."]
  }
});
