B2T("fr", {
  "common-chaffinch": {
    name: "Pinson des arbres",
    s: "Pinson à deux nettes barres alaires blanches ; le mâle a une calotte gris-bleu et une poitrine rose-roux. Migrateur et hivernant régulier, surtout dans l’ouest et à Oulan-Bator.",
    d: "Le Pinson des arbres niche dans toute l’Europe et l’Asie occidentale ; c’est l’un des oiseaux les plus communs d’Europe. En Mongolie, il est migrateur et hivernant régulier, souvent avec les Pinsons du Nord — Oulan-Bator, lac Khar Us et Yolyn Am.",
    f: ["Deux nettes barres alaires blanches.", "Mâle : calotte gris-bleu, poitrine rose-roux.", "Femelle : brun olive.", "Rectrices externes blanches."],
    si: "Pinson du Nord — épaule orangée, croupion blanc.",
    h: "Bois, parcs et buissons.",
    di: "Oulan-Bator, lac Khar Us, Yolyn Am, Khurkh, Terelj, lac Uvs.",
    mi: "Migrateur et hivernant, septembre–mai.",
    fo: "Graines ; insectes en été.",
    br: "Nid en coupe soignée dans une fourche (pas régulièrement en Mongolie).",
    be: "Se nourrit au sol en groupes.",
    v: "Un chant roulé terminé en fioriture ; cri « pink ».",
    cu: "Son nom latin coelebs signifie « célibataire » — les femelles migrent souvent à part.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en octobre.",
    bt: "sept.–oct.",
    fa: ["Deux barres blanches.", "Pinson « célibataire ».", "Hivernant."]
  },
  "brambling": {
    name: "Pinson du Nord",
    s: "Pinson nordique à poitrine et épaules orangées et croupion blanc. Migrateur commun en groupes dans toute la Mongolie.",
    d: "Le Pinson du Nord niche dans les forêts de bouleaux et de conifères du nord et migre en bandes, parfois de plusieurs millions. En Mongolie, il passe en nombre en avril–mai et septembre–octobre — Oulan-Bator, Khurkh, lac Khar Us et Yolyn Am.",
    f: ["Poitrine et épaules orangées.", "Croupion blanc.", "Mâle : tête noire en été.", "Flancs tachetés."],
    si: "Pinson des arbres — sans croupion blanc, calotte grise.",
    h: "Bétulaies ; tout arbre et champ en migration.",
    di: "Oulan-Bator, Khurkh, lac Khar Us, Yolyn Am, Khövsgöl, Terelj.",
    mi: "Migrateur, avril–mai et septembre–octobre.",
    fo: "Graines, faînes ; insectes en été.",
    br: "Niche dans les bouleaux nordiques.",
    be: "Voyage en grandes bandes.",
    v: "Un chant nasillard « dzouiii » ; cri « tchouè ».",
    cu: "Ses dortoirs hivernaux en Europe peuvent réunir des millions d’oiseaux.",
    co: "Préoccupation mineure.",
    w: "Oulan-Bator fin septembre.",
    bt: "sept.–oct.",
    fa: ["Poitrine orangée.", "Croupion blanc.", "Bandes immenses."]
  },
  "hawfinch": {
    name: "Gros-bec casse-noyaux",
    s: "Pinson trapu à énorme bec conique capable de casser les noyaux de cerise. Commun à Oulan-Bator en migration, niche dans le nord.",
    d: "Le Gros-bec casse-noyaux niche dans toute l’Europe et l’Asie tempérée ; les oiseaux asiatiques migrent vers le sud en hiver. En Mongolie, il niche dans les bois du nord et passe en nombre, surtout en mai — Oulan-Bator, Yolyn Am, Khurkh et Terelj.",
    f: ["Énorme bec conique.", "Tête brun-orangé, collier gris.", "Bavette et lore noirs.", "Large barre alaire blanche."],
    si: "Gros-bec migrateur — bec jaune, tête noire (mâle).",
    h: "Bois feuillus, parcs et jardins.",
    di: "Oulan-Bator, Yolyn Am, Khurkh, Terelj, Khustai, Ikh Nart.",
    mi: "Estivant et migrateur ; certains hivernent.",
    fo: "Graines dures et noyaux.",
    br: "Niche dans les arbres.",
    be: "Farouche ; reste haut dans les arbres.",
    v: "Un « tsik » sec et claquant.",
    cu: "Son bec peut exercer une force de plus de 45 kg.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en mai.",
    bt: "mai",
    fa: ["Bec énorme.", "Casse les noyaux.", "Commun en mai."]
  },
  "yellow-billed-grosbeak": {
    name: "Gros-bec migrateur",
    s: "Gros-bec gris au grand bec jaune ; le mâle a la tête noir brillant. Migrateur printanier peu commun dans le Gobi et l’est.",
    d: "Le Gros-bec migrateur niche dans l’Extrême-Orient russe, en Mandchourie, en Corée et en Chine. En Mongolie, c’est un migrateur printanier peu commun, surtout en mai — Yolyn Am et lac Ganga.",
    f: ["Grand bec jaune à pointe sombre.", "Mâle : tête noir brillant.", "Corps gris.", "Ailes noires à pointes blanches."],
    si: "Gros-bec casse-noyaux — brun, bec gris.",
    h: "Bois et jardins.",
    di: "Yolyn Am, lac Ganga, oasis du Gobi.",
    mi: "Migrateur, mai.",
    fo: "Graines, bourgeons, fruits.",
    br: "Niche dans les arbres (pas en Mongolie).",
    be: "Voyage en petits groupes.",
    v: "Un chant sifflé mélodieux.",
    cu: "Oiseau de cage prisé en Chine.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en mai.",
    bt: "mai",
    fa: ["Bec jaune.", "Tête noire.", "Migrateur printanier peu commun."]
  },
  "great-rosefinch": {
    name: "Roselin tacheté",
    s: "Grand roselin ; le mâle est cramoisi foncé tacheté de blanc. Local dans les hautes montagnes de l’extrême ouest.",
    d: "Le Roselin tacheté vit dans les hautes montagnes du Caucase à l’Asie centrale et à la Chine. En Mongolie, il vit dans le haut Altaï et l’Altaï mongol — région du lac Khar Us, Ölgii et lac Achit.",
    f: ["Grande taille.", "Mâle : cramoisi tacheté de blanc.", "Femelle : gris-brun striée.", "Bec fort."],
    si: "Roselin à dos rouge — plus petit, sourcil rose.",
    h: "Hautes pentes rocheuses et broussailles alpines.",
    di: "Lac Khar Us, Yolyn Am, Ölgii, lac Achit, lac Orog.",
    mi: "Résident ; descend en hiver.",
    fo: "Graines et bourgeons.",
    br: "Niche parmi les rochers ou buissons.",
    be: "Se nourrit au sol.",
    v: "Un doux chant sifflé.",
    cu: "Le plus grand roselin de Mongolie.",
    co: "Préoccupation mineure.",
    w: "Haut Altaï en juin.",
    bt: "juin",
    fa: ["Cramoisi tacheté de blanc.", "Plus grand roselin.", "Hautes montagnes."]
  },
  "long-tailed-rosefinch": {
    name: "Roselin à longue queue",
    s: "Petit roselin rose à longue queue bordée de blanc et barres alaires blanches. Très commun autour d’Oulan-Bator toute l’année.",
    d: "Le Roselin à longue queue vit dans les fourrés de saules et lisières du Kazakhstan au Japon. En Mongolie, il est très commun toute l’année dans le nord — Oulan-Bator (surtout le long de la Tuul), Terelj et Khurkh.",
    f: ["Longue queue bordée de blanc.", "Mâle : rose à face givrée de blanc.", "Deux barres alaires blanches.", "Bec trapu."],
    si: "Roselin rose — sans longue queue ni barres blanches.",
    h: "Fourrés de saules, berges, lisières.",
    di: "Oulan-Bator, Terelj, Khurkh, lac Khar Us, Yolyn Am, lac Buir.",
    mi: "Résident.",
    fo: "Graines d’herbes et de plantes.",
    br: "Niche dans les buissons.",
    be: "Agite sa longue queue.",
    v: "Un doux chant trillé ; cri « pi-pi-pi ».",
    cu: "Fréquent dans le commerce d’oiseaux de cage, d’où des mentions européennes douteuses.",
    co: "Préoccupation mineure.",
    w: "Rivière Tuul à Oulan-Bator en hiver.",
    bt: "toute l’année",
    fa: ["Longue queue.", "Rose.", "Commun à Oulan-Bator."]
  },
  "pallass-rosefinch": {
    name: "Roselin rose",
    s: "Superbe roselin rose framboise à calotte et gorge écaillées de blanc givré. Hivernant dans le nord.",
    d: "Le Roselin rose niche dans les forêts boréales de Sibérie et hiverne en Mongolie, en Chine, en Corée et au Japon. En Mongolie, il hiverne dans le nord — Oulan-Bator, Terkhiin Tsagaan Nuur, lac Khar Us et Terelj.",
    f: ["Mâle : rose framboise profond.", "Écailles argentées sur calotte et gorge.", "Deux barres alaires pâles.", "Femelle : brune striée à croupion rose."],
    si: "Roselin à longue queue — longue queue bordée de blanc.",
    h: "Lisières, broussailles et collines en hiver.",
    di: "Oulan-Bator, Terkhiin Tsagaan Nuur, lac Khar Us, Terelj, Yolyn Am, Khövsgöl.",
    mi: "Hivernant, octobre–avril.",
    fo: "Graines et bourgeons.",
    br: "Niche dans les forêts sibériennes (pas en Mongolie).",
    be: "Se nourrit en petits groupes.",
    v: "Un doux « zit ».",
    cu: "Nommé d’après Peter Simon Pallas.",
    co: "Préoccupation mineure.",
    w: "Pentes du Bogd Khan Uul en mars.",
    bt: "nov.–mars",
    fa: ["Rose framboise.", "Calotte givrée.", "Hivernant."]
  },
  "red-mantled-rosefinch": {
    name: "Roselin à dos rouge",
    s: "Roselin à sourcil rose et dos lavé de rose. Surtout dans l’extrême ouest, notamment autour du lac Khar Us en automne et en hiver.",
    d: "Le Roselin à dos rouge vit dans les montagnes d’Asie centrale, de l’Afghanistan à l’ouest de la Chine et à la Mongolie. En Mongolie, on le trouve dans l’ouest, la plupart des mentions venant du lac Khar Us en automne et en hiver.",
    f: ["Sourcil et gorge roses.", "Manteau brun lavé de rose.", "Croupion rose.", "Femelle : brune striée."],
    si: "Roselin tacheté — plus grand, taches blanches.",
    h: "Genévriers et broussailles de montagne.",
    di: "Lac Khar Us, Yolyn Am, Oulan-Bator, Ölgii.",
    mi: "Résident et hivernant.",
    fo: "Graines et baies, surtout de genévrier.",
    br: "Niche dans les genévriers et buissons.",
    be: "Se nourrit bas dans les broussailles.",
    v: "Un doux chant gazouillé.",
    cu: "Son nom mongol évoque le genévrier, son habitat favori.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en octobre.",
    bt: "sept.–oct.",
    fa: ["Sourcil rose.", "Ami des genévriers.", "Extrême ouest."]
  },
  "p-re-davids-rosefinch": {
    name: "Roselin de David",
    s: "Petit roselin à dos brun strié, dessous et sourcil roses. Niche dans les montagnes du Gobi, surtout à Yolyn Am.",
    d: "Le Roselin de David vit dans le nord de la Chine et en Mongolie. En Mongolie, il niche dans les gorges buissonnantes du Gobi — la plupart des mentions viennent de Yolyn Am.",
    f: ["Mâle : sourcil et dessous roses.", "Dos brun strié.", "Croupion rose pâle.", "Femelle : brune striée."],
    si: "Roselin à longue queue — longue queue, barres alaires blanches.",
    h: "Gorges montagneuses buissonnantes.",
    di: "Yolyn Am, Ikh Nart, Gobi Gurvan Saikhan.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines.",
    br: "Niche dans les buissons.",
    be: "Se nourrit bas dans les arbustes.",
    v: "Un doux « tchip ».",
    cu: "Nommé d’après le missionnaire naturaliste français Armand David.",
    co: "Non évalué séparément par l’UICN.",
    w: "Yolyn Am en juin.",
    bt: "juin",
    fa: ["Sourcil rose.", "Gorges du Gobi.", "Spécialité de Yolyn Am."]
  },
  "pine-grosbeak": {
    name: "Durbec des sapins",
    s: "Grand pinson dodu et confiant ; le mâle est rouge rosé, la femelle olive doré. Hivernant peu commun à Oulan-Bator et Terelj.",
    d: "Le Durbec des sapins vit dans les forêts de conifères de tout le nord holarctique. Il mange surtout des fruits, en particulier les baies de sorbier. En Mongolie, il hiverne dans le Khentii — surtout à Oulan-Bator et Terelj.",
    f: ["Grand, à longue queue.", "Mâle : rouge rosé.", "Femelle : tête olive doré.", "Deux barres alaires blanches."],
    si: "Bec-croisé des sapins — bec croisé, queue plus courte.",
    h: "Forêts de conifères ; arbres à baies en hiver.",
    di: "Oulan-Bator, Terelj, Onon, Orkhon.",
    mi: "Hivernant, novembre–avril.",
    fo: "Baies, bourgeons et graines.",
    br: "Niche dans les conifères (rarement en Mongolie).",
    be: "Remarquablement confiant.",
    v: "Un sifflement flûté « ti-tiou-ti ».",
    cu: "Si confiant qu’on peut parfois le prendre à la main.",
    co: "Préoccupation mineure.",
    w: "Sorbiers de Terelj en hiver.",
    bt: "déc.–févr.",
    fa: ["Très confiant.", "Mangeur de baies.", "Hivernant."]
  },
  "eurasian-bullfinch": {
    name: "Bouvreuil pivoine",
    s: "Pinson dodu à calotte noire ; le mâle a la poitrine rouge rosé ou grise. Hivernant à Oulan-Bator.",
    d: "Le Bouvreuil pivoine niche dans toute l’Eurasie. La forme sibérienne à poitrine grise (cineracea) et des oiseaux à poitrine rouge hivernent en Mongolie — surtout Oulan-Bator, lac Khar Us et Terelj.",
    f: ["Calotte et queue noires.", "Mâle : poitrine rouge rosé (grise chez cineracea).", "Dos gris.", "Croupion blanc."],
    si: "Durbec des sapins — plus grand, sans calotte noire.",
    h: "Bois, parcs et jardins.",
    di: "Oulan-Bator, lac Khar Us, Terelj, Yolyn Am.",
    mi: "Hivernant, octobre–avril.",
    fo: "Bourgeons, graines et baies.",
    br: "Niche dans les arbustes (pas régulièrement en Mongolie).",
    be: "Se déplace discrètement en couple.",
    v: "Un doux « piou » flûté.",
    cu: "Peut apprendre à siffler des airs humains.",
    co: "Préoccupation mineure.",
    w: "Parcs d’Oulan-Bator en novembre.",
    bt: "nov.–févr.",
    fa: ["Calotte noire.", "Cri flûté.", "Hivernant."]
  },
  "mongolian-finch": {
    name: "Roselin de Mongolie",
    s: "Roselin sable du désert à panneaux alaires roses et blancs et bec trapu. Commun dans les semi-déserts rocheux de l’ouest et du Gobi.",
    d: "Le Roselin de Mongolie vit dans les montagnes arides d’Asie centrale. En Mongolie, il est commun dans les déserts rocheux et pentes sèches — lac Khar Us, Yolyn Am, lac Orog et Böön Tsagaan.",
    f: ["Corps chamois sable.", "Panneaux alaires roses et blancs.", "Bec court et épais jaunâtre.", "Mâle : lavé de rose en période nuptiale."],
    si: "Roselin de Lichtenstein — ailes noires et roses, bec noir.",
    h: "Semi-déserts rocheux et pentes sèches.",
    di: "Lac Khar Us, Yolyn Am, lac Orog, Böön Tsagaan, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Estivant, avril–octobre ; certains restent.",
    fo: "Graines.",
    br: "Niche parmi les rochers.",
    be: "Vient boire aux sources en groupes.",
    v: "Un doux « djou-vou » montant.",
    cu: "Aussi appelé Bouvreuil trompetteur de Mongolie.",
    co: "Préoccupation mineure.",
    w: "Sources de Yolyn Am en juin.",
    bt: "juin–juil.",
    fa: ["Ailes roses.", "Roselin du désert.", "Porte le nom de la Mongolie."]
  },
  "plain-mountain-finch": {
    name: "Roselin de Hodgson",
    s: "Roselin montagnard brun, semblable à un moineau, à dos strié et barres alaires pâles. Local dans le haut Altaï.",
    d: "Le Roselin de Hodgson vit dans l’Himalaya et les hautes montagnes d’Asie centrale. En Mongolie, il n’est présent que dans le haut Altaï — Tavan Bogd, lac Khar Us et Ölgii.",
    f: ["Dos brun strié.", "Dessous chamois-gris uni.", "Barres alaires pâles.", "Queue fourchue."],
    si: "Roselin de Brandt — tête plus sombre, croupion rose.",
    h: "Prairies alpines et éboulis.",
    di: "Tavan Bogd, lac Khar Us, Ölgii.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines.",
    br: "Niche dans les fissures des rochers.",
    be: "Se nourrit au sol en groupes.",
    v: "Un chant gazouillé.",
    cu: "Ressemble étonnamment à un Moineau domestique.",
    co: "Préoccupation mineure.",
    w: "Tavan Bogd en juillet.",
    bt: "juil.",
    fa: ["Comme un moineau.", "Haut Altaï.", "Dos strié."]
  }
});
