B2T("en", {
  "brandts-mountain-finch": {
    T: { c: { brown: 0.35, black: 0.25, gray: 0.2, red: 0.1, white: 0.1 }, hb: ["mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["16–19 cm", "—", "25–35 g"] },
    s: "A dark-headed high-mountain finch with a pinkish rump and white wing panels. Found only at high altitude in the Altai.",
    d: "Brandt's Mountain Finch lives at very high altitude from Central Asia to the Himalayas and Tibet. In Mongolia it lives in the high Altai — Tavan Bogd, Khar Us Nuur and Ölgii.",
    f: ["Blackish head.", "Grey-brown body.", "Pinkish rump.", "Whitish wing panels in flight."],
    si: "Plain Mountain Finch — paler, sparrow-like.",
    h: "High scree, glacier edges and alpine meadows.",
    di: "Tavan Bogd, Khar Us Nuur, Ölgii.",
    mi: "Resident; moves lower in winter.",
    fo: "Seeds.",
    br: "Nests in rock crevices at high altitude.",
    be: "Feeds in flocks on bare ground.",
    v: "A twittering 'twitt-twitt'.",
    cu: "Breeds at up to 6,000 m in Tibet.",
    co: "Least Concern.",
    w: "Tavan Bogd in July.",
    bt: "Jun–Jul",
    fa: ["Dark head.", "Very high altitude.", "Pink rump."]
  },
  "desert-finch": {
    T: { c: { buff: 0.45, brown: 0.2, black: 0.15, red: 0.1, white: 0.1 }, hb: ["desert", "settlement"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–15 cm", "—", "20–25 g"] },
    s: "A sandy finch with black-and-pink wings and a black bill. Local in the southern Gobi, mostly Yolyn Am.",
    d: "The Desert Finch lives in dry lands from Turkey to western China. Its relationships long confused taxonomists. In Mongolia it is local in the southern Gobi, above all around Yolyn Am.",
    f: ["Sandy-buff body.", "Black and pink wings.", "Black bill (male).", "Black-and-white tail."],
    si: "Mongolian Finch — pale yellowish bill, pink-and-white wings.",
    h: "Oases, orchards and scrub in desert.",
    di: "Yolyn Am, southern Gobi oases.",
    mi: "Summer visitor, Mar–Oct.",
    fo: "Seeds.",
    br: "Nests in trees and bushes.",
    be: "Visits water in flocks.",
    v: "A soft, purring song.",
    cu: "Also called Lichtenstein's Desert Finch.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "Jun",
    fa: ["Pink-and-black wings.", "Black bill.", "Gobi oases."]
  },
  "european-greenfinch": {
    T: { c: { yellow: 0.5, gray: 0.25, brown: 0.15, black: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["14–16 cm", "24.5–27.5 cm", "25–32 g"] },
    s: "A stocky olive-green finch with bright yellow flashes on the wings and tail. Local in the far west.",
    d: "The European Greenfinch lives across Europe, North Africa and southwest Asia and has been introduced to Australia and New Zealand. In Mongolia it is found mainly in the far west — Khar Us Nuur — with a few records at Ulaanbaatar.",
    f: ["Olive-green body.", "Yellow wing edge.", "Yellow sides to the tail.", "Heavy pale bill."],
    si: "Grey-capped Greenfinch — grey head, brown back; eastern.",
    h: "Woods, parks and gardens.",
    di: "Khar Us Nuur, Ulaanbaatar, Ölgii, Achit Nuur.",
    mi: "Summer visitor and migrant, Apr–Oct.",
    fo: "Seeds.",
    br: "Nests in shrubs and trees.",
    be: "Song flight like a bat.",
    v: "A wheezing 'dzweee' and twittering song.",
    cu: "Populations in Europe have crashed due to a parasitic disease.",
    co: "Least Concern.",
    w: "Khar Us Nuur in May.",
    bt: "May",
    fa: ["Yellow wing flash.", "Wheezing song.", "Far west."]
  },
  "grey-capped-greenfinch": {
    T: { c: { brown: 0.35, yellow: 0.3, gray: 0.2, black: 0.15 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "—", "18–25 g"] },
    s: "A greenfinch with a grey head, warm brown back and bold yellow wing patches. Local in the east and north.",
    d: "The Oriental Greenfinch breeds in the woods of the east Palearctic. In Mongolia it is found in the east and north — Khurkh, Ganga Nuur, Onon and Ulaanbaatar.",
    f: ["Grey head.", "Warm brown back.", "Big yellow wing patch.", "Pink bill."],
    si: "European Greenfinch — all green; western.",
    h: "Open woods, villages and gardens.",
    di: "Khurkh, Ganga Nuur, Onon, Ulaanbaatar, Buir Nuur, Orkhon.",
    mi: "Summer visitor and migrant, May–Oct.",
    fo: "Seeds.",
    br: "Nests in trees.",
    be: "Often in small flocks.",
    v: "A twittering song and nasal 'dzweee'.",
    cu: "Common in cities in Japan and China.",
    co: "Least Concern.",
    w: "Khurkh in May.",
    bt: "May",
    fa: ["Grey head.", "Yellow wing patches.", "Eastern finch."]
  },
  "twite": {
    T: { c: { brown: 0.45, buff: 0.3, black: 0.1, red: 0.1, white: 0.05 }, hb: ["mountain", "steppe"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["12.5–14 cm", "22–24 cm", "13–17 g"] },
    s: "A streaky brown mountain finch with a yellow winter bill and a pink rump in males. Common in western and Gobi mountains.",
    d: "The Twite has a split range — northern Europe and the mountains of Asia from Turkey to Mongolia. In Mongolia it is common in rocky mountains and steppe — Yolyn Am, Khar Us Nuur, Ulaanbaatar and Ölgii.",
    f: ["Streaky brown.", "Warm buff throat.", "Yellow bill in winter.", "Male: pink rump."],
    si: "Common Linnet — grey head, red breast (male).",
    h: "Rocky mountains, steppe and scree.",
    di: "Yolyn Am, Khar Us Nuur, Ulaanbaatar, Terelj, Ölgii, Tavan Bogd.",
    mi: "Resident; forms flocks in winter.",
    fo: "Small seeds.",
    br: "Nests low among rocks and bushes.",
    be: "Flocks in winter.",
    v: "A nasal 'tveiht' — its name.",
    cu: "Its English name imitates its call.",
    co: "Least Concern.",
    w: "Yolyn Am in June.",
    bt: "May–Jul",
    fa: ["Named after its call.", "Streaky.", "Mountain finch."]
  },
  "common-linnet": {
    T: { c: { brown: 0.45, red: 0.2, gray: 0.2, white: 0.15 }, hb: ["steppe", "mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["13–14 cm", "21–25 cm", "15–26 g"] },
    s: "A slim finch; the male has a grey head, chestnut back and crimson breast and forehead. Local in the far west.",
    d: "The Common Linnet breeds across Europe, North Africa and western Asia. Its name comes from its fondness for flax seeds. In Mongolia it is found only in the far west — Khar Us Nuur, Tavan Bogd and Ölgii.",
    f: ["Male: crimson forehead and breast.", "Grey head.", "Chestnut back.", "White flashes in wings and tail."],
    si: "Twite — streakier, no red breast.",
    h: "Scrub, open slopes and fields.",
    di: "Khar Us Nuur, Tavan Bogd, Yolyn Am, Ölgii.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds, especially flax and weeds.",
    br: "Nests in bushes.",
    be: "Sings from bush tops.",
    v: "A pleasant twittering song.",
    cu: "Once a popular cage bird for its sweet song.",
    co: "Least Concern.",
    w: "Khar Us Nuur in July.",
    bt: "Jul",
    fa: ["Red breast.", "Flax eater.", "Far west."]
  },
  "common-redpoll": {
    T: { c: { brown: 0.35, white: 0.3, red: 0.15, black: 0.1, gray: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["winter"], sz: ["11.5–14 cm", "20–25 cm", "10–16 g"] },
    s: "A small streaky finch with a red forehead and black chin; males flush pink on the breast. A winter visitor in flocks to Ulaanbaatar.",
    d: "The Redpoll breeds in the Arctic and northern taiga around the world. In Mongolia it arrives in winter flocks — mainly Ulaanbaatar and Terelj, also Khar Us Nuur and Yolyn Am.",
    f: ["Red forehead.", "Small black chin.", "Streaky grey-brown.", "Male: pink breast."],
    si: "Arctic Redpoll — paler, white unstreaked rump.",
    h: "Birch and larch woods, weedy fields.",
    di: "Ulaanbaatar, Terelj, Khar Us Nuur, Yolyn Am, Khurkh, Khövsgöl.",
    mi: "Winter visitor, Oct–Apr.",
    fo: "Birch and alder seeds.",
    br: "Nests in the far north (not in Mongolia).",
    be: "Hangs acrobatically from birch twigs.",
    v: "A buzzing 'chett-chett-chett'.",
    cu: "Can survive −50 °C, storing seeds in a throat pouch.",
    co: "Least Concern.",
    w: "Ulaanbaatar birches in January.",
    bt: "Dec–Feb",
    fa: ["Red forehead.", "Winter flocks.", "Survives −50 °C."]
  },
  "arctic-redpoll": {
    T: { c: { white: 0.45, gray: 0.2, brown: 0.2, red: 0.1, black: 0.05 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["winter"], sz: ["12–14 cm", "—", "11–16 g"] },
    s: "A frosty-white redpoll with an unstreaked white rump and tiny bill. On the Mongolian list, no GBIF records.",
    d: "The Arctic Redpoll breeds in the high Arctic tundra. Many authorities now lump it with the Common Redpoll. It may join winter redpoll flocks in northern Mongolia.",
    f: ["Very pale, frosty.", "Unstreaked white rump.", "Tiny bill.", "Red forehead."],
    si: "Common Redpoll — darker, streaked rump.",
    h: "Tundra; birch woods in winter.",
    di: "Exceptional.",
    mi: "Winter vagrant.",
    fo: "Seeds.",
    br: "Nests in Arctic tundra (not in Mongolia).",
    be: "Mixes with Common Redpolls.",
    v: "Like Common Redpoll.",
    cu: "Also called Hoary Redpoll.",
    co: "Least Concern; often lumped with Common Redpoll.",
    w: "Check redpoll flocks in winter.",
    bt: "—",
    fa: ["Frosty white.", "White rump.", "Often lumped."]
  },
  "red-crossbill": {
    T: { c: { red: 0.4, yellow: 0.2, brown: 0.2, black: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["15–17 cm", "27–30 cm", "30–48 g"] },
    s: "A stocky finch with crossed mandible tips for prying seeds from cones; males red, females greenish-yellow. Common in Khentii forests.",
    d: "The Red Crossbill lives in conifer forests across the Northern Hemisphere and wanders widely in search of cones. In Mongolia it lives in the Khentii and Khangai forests — Ulaanbaatar, Terelj, Khövsgöl and Orkhon.",
    f: ["Crossed bill tips.", "Male: brick red.", "Female: greenish-yellow.", "Dark wings without bars."],
    si: "White-winged Crossbill — two white wing bars.",
    h: "Larch, pine and spruce forest.",
    di: "Ulaanbaatar, Terelj, Khövsgöl, Orkhon, Khurkh, Tavan Bogd.",
    mi: "Resident and nomadic.",
    fo: "Conifer seeds.",
    br: "Can nest in any month, even in winter, when cones are plentiful.",
    be: "Climbs like a parrot on cones.",
    v: "A hard 'jip-jip'.",
    cu: "Its crossed bill is used to prise open cone scales.",
    co: "Least Concern.",
    w: "Bogd Khan Uul larches.",
    bt: "All year",
    fa: ["Crossed bill.", "Breeds even in winter.", "Parrot-like."]
  },
  "white-winged-crossbill": {
    T: { c: { red: 0.35, black: 0.3, white: 0.2, yellow: 0.15 }, hb: ["forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["14–16 cm", "26–29 cm", "25–40 g"] },
    s: "A crossbill with two broad white wing bars; males pinkish-red. Scarce in the larch forests around Ulaanbaatar and Terelj.",
    d: "The Two-barred Crossbill breeds in the conifer forests of North America and the Palearctic. It prefers larch cones. In Mongolia it is scarce in the Khentii — Ulaanbaatar and Terelj.",
    f: ["Crossed bill tips.", "Two broad white wing bars.", "Male: pinkish-red.", "Black wings."],
    si: "Red Crossbill — no white wing bars.",
    h: "Larch forest.",
    di: "Ulaanbaatar, Terelj, Orkhon, Onon.",
    mi: "Resident and nomadic.",
    fo: "Larch seeds.",
    br: "Nests in conifers.",
    be: "Feeds acrobatically on cones.",
    v: "A dry, trumpeting 'glip-glip'.",
    cu: "Its slender bill suits small larch cones.",
    co: "Least Concern.",
    w: "Larches of Terelj.",
    bt: "All year",
    fa: ["White wing bars.", "Crossed bill.", "Larch specialist."]
  },
  "european-goldfinch": {
    T: { c: { red: 0.2, black: 0.25, white: 0.2, yellow: 0.2, brown: 0.15 }, hb: ["steppe", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12–13 cm", "21–25 cm", "14–19 g"] },
    s: "A colourful finch with a red face and golden-yellow wing bars. Rare, in the far west.",
    d: "The European Goldfinch lives across Europe, North Africa and western Asia; its grey-headed eastern form reaches Mongolia. In Mongolia it is rare in the far west — Uvs Nuur and Tavan Bogd.",
    f: ["Red face.", "Broad golden wing bar.", "Black-and-white wings.", "Buff-brown back."],
    si: "Unmistakable.",
    h: "Open woods and weedy places.",
    di: "Uvs Nuur, Tavan Bogd.",
    mi: "Rare visitor.",
    fo: "Thistle and other seeds.",
    br: "Nests in trees (rarely in Mongolia).",
    be: "Picks seeds from thistle heads.",
    v: "A liquid, tinkling twitter.",
    cu: "A symbol of the Passion in Renaissance paintings.",
    co: "Least Concern.",
    w: "Uvs Nuur in August.",
    bt: "Aug",
    fa: ["Red face.", "Gold wing bars.", "Thistle eater."]
  },
  "eurasian-siskin": {
    T: { c: { yellow: 0.45, black: 0.2, gray: 0.15, white: 0.1, brown: 0.1 }, hb: ["forest", "settlement"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["11–12.5 cm", "20–23 cm", "10–18 g"] },
    s: "A small, streaky yellow-green finch; the male has a black cap and chin. A common migrant in flocks.",
    d: "The Eurasian Siskin is common in European and Siberian forests. In Mongolia it passes through in flocks, mostly in May and October — Ulaanbaatar, Yolyn Am, Terelj and Khar Us Nuur.",
    f: ["Yellow-green body.", "Male: black cap and chin.", "Yellow wing bars.", "Streaked flanks."],
    si: "European Greenfinch — larger, no black cap.",
    h: "Conifer and birch woods, alders.",
    di: "Ulaanbaatar, Yolyn Am, Terelj, Khar Us Nuur, Khurkh, Buir Nuur.",
    mi: "Passage migrant, Apr–May and Sep–Oct.",
    fo: "Alder, birch and spruce seeds.",
    br: "Nests high in conifers.",
    be: "Hangs upside down like a tit.",
    v: "A wheezy twittering song.",
    cu: "Archaic English names include 'aberdevine'.",
    co: "Least Concern.",
    w: "Ulaanbaatar in May.",
    bt: "May, Oct",
    fa: ["Black cap.", "Acrobatic.", "Migrant flocks."]
  }
});
