B2T("fr", {
  "brandts-mountain-finch": {
    name: "Roselin de Brandt",
    s: "Roselin de haute montagne à tête sombre, croupion rosé et panneaux alaires blancs. Uniquement à haute altitude dans l’Altaï.",
    d: "Le Roselin de Brandt vit à très haute altitude, de l’Asie centrale à l’Himalaya et au Tibet. En Mongolie, il vit dans le haut Altaï — Tavan Bogd, lac Khar Us et Ölgii.",
    f: ["Tête noirâtre.", "Corps gris-brun.", "Croupion rosé.", "Panneaux alaires blanchâtres en vol."],
    si: "Roselin de Hodgson — plus pâle, semblable à un moineau.",
    h: "Hauts éboulis, bords de glaciers et prairies alpines.",
    di: "Tavan Bogd, lac Khar Us, Ölgii.",
    mi: "Résident ; descend en hiver.",
    fo: "Graines.",
    br: "Niche dans les fissures des rochers en altitude.",
    be: "Se nourrit en groupes sur sol nu.",
    v: "Un gazouillis « touitt-touitt ».",
    cu: "Niche jusqu’à 6 000 m au Tibet.",
    co: "Préoccupation mineure.",
    w: "Tavan Bogd en juillet.",
    bt: "juin–juil.",
    fa: ["Tête sombre.", "Très haute altitude.", "Croupion rose."]
  },
  "desert-finch": {
    name: "Roselin de Lichtenstein",
    s: "Roselin sable aux ailes noires et roses et au bec noir. Local dans le sud du Gobi, surtout à Yolyn Am.",
    d: "Le Roselin de Lichtenstein vit dans les terres arides de la Turquie à l’ouest de la Chine. Sa classification a longtemps été confuse. En Mongolie, il est local dans le sud du Gobi, surtout autour de Yolyn Am.",
    f: ["Corps chamois sable.", "Ailes noires et roses.", "Bec noir (mâle).", "Queue noire et blanche."],
    si: "Roselin de Mongolie — bec jaunâtre pâle, ailes roses et blanches.",
    h: "Oasis, vergers et broussailles désertiques.",
    di: "Yolyn Am, oasis du sud du Gobi.",
    mi: "Estivant, mars–octobre.",
    fo: "Graines.",
    br: "Niche dans les arbres et buissons.",
    be: "Vient boire en groupes.",
    v: "Un doux chant ronronnant.",
    cu: "Aussi appelé Roselin du désert.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "juin",
    fa: ["Ailes roses et noires.", "Bec noir.", "Oasis du Gobi."]
  },
  "european-greenfinch": {
    name: "Verdier d’Europe",
    s: "Pinson trapu vert olive aux éclats jaune vif sur les ailes et la queue. Local dans l’extrême ouest.",
    d: "Le Verdier d’Europe vit en Europe, en Afrique du Nord et en Asie du Sud-Ouest ; il a été introduit en Australie et en Nouvelle-Zélande. En Mongolie, on le trouve surtout dans l’extrême ouest — lac Khar Us — avec quelques mentions à Oulan-Bator.",
    f: ["Corps vert olive.", "Bord de l’aile jaune.", "Côtés de la queue jaunes.", "Bec fort et pâle."],
    si: "Verdier de Chine — tête grise, dos brun ; à l’est.",
    h: "Bois, parcs et jardins.",
    di: "Lac Khar Us, Oulan-Bator, Ölgii, lac Achit.",
    mi: "Estivant et migrateur, avril–octobre.",
    fo: "Graines.",
    br: "Niche dans les arbustes et arbres.",
    be: "Vol chanté papillonnant comme une chauve-souris.",
    v: "Un « dzouiii » nasillard et un chant gazouillé.",
    cu: "Ses populations européennes se sont effondrées à cause d’une maladie parasitaire.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en mai.",
    bt: "mai",
    fa: ["Éclat jaune sur l’aile.", "Chant nasillard.", "Extrême ouest."]
  },
  "grey-capped-greenfinch": {
    name: "Verdier de Chine",
    s: "Verdier à tête grise, dos brun chaud et grands panneaux alaires jaunes. Local dans l’est et le nord.",
    d: "Le Verdier de Chine niche dans les bois du Paléarctique oriental. En Mongolie, on le trouve dans l’est et le nord — Khurkh, lac Ganga, Onon et Oulan-Bator.",
    f: ["Tête grise.", "Dos brun chaud.", "Grand panneau alaire jaune.", "Bec rose."],
    si: "Verdier d’Europe — entièrement vert ; à l’ouest.",
    h: "Bois clairs, villages et jardins.",
    di: "Khurkh, lac Ganga, Onon, Oulan-Bator, lac Buir, Orkhon.",
    mi: "Estivant et migrateur, mai–octobre.",
    fo: "Graines.",
    br: "Niche dans les arbres.",
    be: "Souvent en petits groupes.",
    v: "Un chant gazouillé et un « dzouiii » nasal.",
    cu: "Commun dans les villes du Japon et de Chine.",
    co: "Préoccupation mineure.",
    w: "Khurkh en mai.",
    bt: "mai",
    fa: ["Tête grise.", "Panneaux alaires jaunes.", "Verdier de l’est."]
  },
  "twite": {
    name: "Linotte à bec jaune",
    s: "Linotte montagnarde brune striée, au bec jaune en hiver et au croupion rose chez le mâle. Commune dans les montagnes de l’ouest et du Gobi.",
    d: "La Linotte à bec jaune a une aire disjointe — Europe du Nord et montagnes d’Asie, de la Turquie à la Mongolie. En Mongolie, elle est commune dans les montagnes rocheuses et la steppe — Yolyn Am, lac Khar Us, Oulan-Bator et Ölgii.",
    f: ["Brune striée.", "Gorge chamois chaud.", "Bec jaune en hiver.", "Mâle : croupion rose."],
    si: "Linotte mélodieuse — tête grise, poitrine rouge (mâle).",
    h: "Montagnes rocheuses, steppe et éboulis.",
    di: "Yolyn Am, lac Khar Us, Oulan-Bator, Terelj, Ölgii, Tavan Bogd.",
    mi: "Résidente ; en groupes l’hiver.",
    fo: "Petites graines.",
    br: "Niche bas parmi les rochers et buissons.",
    be: "En groupes en hiver.",
    v: "Un « tvèït » nasal — d’où son nom anglais.",
    cu: "Son nom anglais, twite, imite son cri.",
    co: "Préoccupation mineure.",
    w: "Yolyn Am en juin.",
    bt: "mai–juil.",
    fa: ["Nommée d’après son cri.", "Striée.", "Linotte de montagne."]
  },
  "common-linnet": {
    name: "Linotte mélodieuse",
    s: "Linotte élancée ; le mâle a la tête grise, le dos châtain, la poitrine et le front cramoisis. Locale dans l’extrême ouest.",
    d: "La Linotte mélodieuse niche en Europe, en Afrique du Nord et en Asie occidentale. Son nom vient de son goût pour les graines de lin. En Mongolie, elle n’est présente que dans l’extrême ouest — lac Khar Us, Tavan Bogd et Ölgii.",
    f: ["Mâle : front et poitrine cramoisis.", "Tête grise.", "Dos châtain.", "Éclats blancs aux ailes et à la queue."],
    si: "Linotte à bec jaune — plus striée, sans poitrine rouge.",
    h: "Broussailles, pentes ouvertes et champs.",
    di: "Lac Khar Us, Tavan Bogd, Yolyn Am, Ölgii.",
    mi: "Estivante, mai–septembre.",
    fo: "Graines, surtout de lin et d’adventices.",
    br: "Niche dans les buissons.",
    be: "Chante du sommet des buissons.",
    v: "Un agréable chant gazouillé.",
    cu: "Autrefois oiseau de cage prisé pour son chant.",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en juillet.",
    bt: "juil.",
    fa: ["Poitrine rouge.", "Mangeuse de lin.", "Extrême ouest."]
  },
  "common-redpoll": {
    name: "Sizerin flammé",
    s: "Petit fringille strié à front rouge et menton noir ; le mâle a la poitrine rosée. Hivernant en groupes à Oulan-Bator.",
    d: "Le Sizerin flammé niche dans l’Arctique et la taïga septentrionale tout autour du globe. En Mongolie, il arrive en bandes hivernales — surtout à Oulan-Bator et Terelj, aussi au lac Khar Us et à Yolyn Am.",
    f: ["Front rouge.", "Petit menton noir.", "Gris-brun strié.", "Mâle : poitrine rose."],
    si: "Sizerin blanchâtre — plus pâle, croupion blanc non strié.",
    h: "Bois de bouleaux et mélèzes, friches.",
    di: "Oulan-Bator, Terelj, lac Khar Us, Yolyn Am, Khurkh, Khövsgöl.",
    mi: "Hivernant, octobre–avril.",
    fo: "Graines de bouleau et d’aulne.",
    br: "Niche dans le Grand Nord (pas en Mongolie).",
    be: "Se suspend en acrobate aux rameaux de bouleau.",
    v: "Un « tchett-tchett-tchett » bourdonnant.",
    cu: "Survit à −50 °C en stockant des graines dans une poche de la gorge.",
    co: "Préoccupation mineure.",
    w: "Bouleaux d’Oulan-Bator en janvier.",
    bt: "déc.–févr.",
    fa: ["Front rouge.", "Bandes hivernales.", "Survit à −50 °C."]
  },
  "arctic-redpoll": {
    name: "Sizerin blanchâtre",
    s: "Sizerin blanc givré au croupion blanc non strié et au bec minuscule. Inscrit pour la Mongolie, sans mention GBIF.",
    d: "Le Sizerin blanchâtre niche dans la toundra du Haut-Arctique. Beaucoup d’auteurs le réunissent désormais au Sizerin flammé. Il peut se joindre aux bandes hivernales de sizerins dans le nord de la Mongolie.",
    f: ["Très pâle, givré.", "Croupion blanc non strié.", "Bec minuscule.", "Front rouge."],
    si: "Sizerin flammé — plus sombre, croupion strié.",
    h: "Toundra ; bétulaies en hiver.",
    di: "Exceptionnel.",
    mi: "Erratique hivernal.",
    fo: "Graines.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Se mêle aux Sizerins flammés.",
    v: "Comme le Sizerin flammé.",
    cu: "Aussi appelé Sizerin d’Hornemann.",
    co: "Préoccupation mineure ; souvent réuni au Sizerin flammé.",
    w: "Examiner les bandes de sizerins en hiver.",
    bt: "—",
    fa: ["Blanc givré.", "Croupion blanc.", "Souvent réuni."]
  },
  "red-crossbill": {
    name: "Bec-croisé des sapins",
    s: "Fringille trapu aux mandibules croisées pour extraire les graines des cônes ; mâle rouge, femelle jaune-vert. Commun dans les forêts du Khentii.",
    d: "Le Bec-croisé des sapins vit dans les forêts de conifères de tout l’hémisphère Nord et erre largement à la recherche de cônes. En Mongolie, il vit dans les forêts du Khentii et du Khangaï — Oulan-Bator, Terelj, Khövsgöl et Orkhon.",
    f: ["Pointes du bec croisées.", "Mâle : rouge brique.", "Femelle : jaune verdâtre.", "Ailes sombres sans barres."],
    si: "Bec-croisé bifascié — deux barres alaires blanches.",
    h: "Forêts de mélèzes, pins et épicéas.",
    di: "Oulan-Bator, Terelj, Khövsgöl, Orkhon, Khurkh, Tavan Bogd.",
    mi: "Résident et nomade.",
    fo: "Graines de conifères.",
    br: "Peut nicher à tout mois, même en hiver, si les cônes abondent.",
    be: "Grimpe sur les cônes comme un perroquet.",
    v: "Un « djip-djip » sec.",
    cu: "Son bec croisé sert à écarter les écailles des cônes.",
    co: "Préoccupation mineure.",
    w: "Mélèzes du Bogd Khan Uul.",
    bt: "toute l’année",
    fa: ["Bec croisé.", "Niche même en hiver.", "Comme un perroquet."]
  },
  "white-winged-crossbill": {
    name: "Bec-croisé bifascié",
    s: "Bec-croisé à deux larges barres alaires blanches ; mâle rouge rosé. Peu commun dans les mélèzes autour d’Oulan-Bator et de Terelj.",
    d: "Le Bec-croisé bifascié niche dans les forêts de conifères d’Amérique du Nord et du Paléarctique. Il préfère les cônes de mélèze. En Mongolie, il est peu commun dans le Khentii — Oulan-Bator et Terelj.",
    f: ["Pointes du bec croisées.", "Deux larges barres alaires blanches.", "Mâle : rouge rosé.", "Ailes noires."],
    si: "Bec-croisé des sapins — sans barres blanches.",
    h: "Forêts de mélèzes.",
    di: "Oulan-Bator, Terelj, Orkhon, Onon.",
    mi: "Résident et nomade.",
    fo: "Graines de mélèze.",
    br: "Niche dans les conifères.",
    be: "Se nourrit en acrobate sur les cônes.",
    v: "Un « glip-glip » sec, comme une trompette.",
    cu: "Son bec fin convient aux petits cônes de mélèze.",
    co: "Préoccupation mineure.",
    w: "Mélèzes de Terelj.",
    bt: "toute l’année",
    fa: ["Barres alaires blanches.", "Bec croisé.", "Spécialiste du mélèze."]
  },
  "european-goldfinch": {
    name: "Chardonneret élégant",
    s: "Fringille coloré à face rouge et barres alaires jaune d’or. Rare, dans l’extrême ouest.",
    d: "Le Chardonneret élégant vit en Europe, en Afrique du Nord et en Asie occidentale ; sa forme orientale à tête grise atteint la Mongolie. En Mongolie, il est rare dans l’extrême ouest — lac Uvs et Tavan Bogd.",
    f: ["Face rouge.", "Large barre alaire dorée.", "Ailes noires et blanches.", "Dos brun chamois."],
    si: "Inconfondable.",
    h: "Bois clairs et friches.",
    di: "Lac Uvs, Tavan Bogd.",
    mi: "Visiteur rare.",
    fo: "Graines de chardon et autres.",
    br: "Niche dans les arbres (rarement en Mongolie).",
    be: "Picore les graines des capitules de chardon.",
    v: "Un gazouillis liquide et tintant.",
    cu: "Symbole de la Passion dans la peinture de la Renaissance.",
    co: "Préoccupation mineure.",
    w: "Lac Uvs en août.",
    bt: "août",
    fa: ["Face rouge.", "Barres dorées.", "Mangeur de chardons."]
  },
  "eurasian-siskin": {
    name: "Tarin des aulnes",
    s: "Petit fringille jaune-vert strié ; le mâle a la calotte et le menton noirs. Migrateur commun en bandes.",
    d: "Le Tarin des aulnes est commun dans les forêts d’Europe et de Sibérie. En Mongolie, il passe en bandes, surtout en mai et en octobre — Oulan-Bator, Yolyn Am, Terelj et lac Khar Us.",
    f: ["Corps jaune-vert.", "Mâle : calotte et menton noirs.", "Barres alaires jaunes.", "Flancs striés."],
    si: "Verdier d’Europe — plus grand, sans calotte noire.",
    h: "Bois de conifères et de bouleaux, aulnaies.",
    di: "Oulan-Bator, Yolyn Am, Terelj, lac Khar Us, Khurkh, lac Buir.",
    mi: "Migrateur, avril–mai et septembre–octobre.",
    fo: "Graines d’aulne, de bouleau et d’épicéa.",
    br: "Niche haut dans les conifères.",
    be: "Se suspend la tête en bas comme une mésange.",
    v: "Un gazouillis nasillard.",
    cu: "En anglais ancien, on l’appelait « aberdevine ».",
    co: "Préoccupation mineure.",
    w: "Oulan-Bator en mai.",
    bt: "mai, oct.",
    fa: ["Calotte noire.", "Acrobate.", "Bandes migratrices."]
  }
});
