B2T("en", {
  "red-headed-bunting": {
    T: { c: { yellow: 0.4, rufous: 0.3, brown: 0.2, buff: 0.1 }, hb: ["steppe"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["16–17 cm", "—", "20–30 g"] },
    s: "A bunting with a chestnut head and breast and bright yellow underparts. A rare visitor to the west and Gobi.",
    d: "The Red-headed Bunting breeds in the steppes of Central Asia and winters in India. In Mongolia it is a rare visitor, mostly in June — the far west and Gobi.",
    f: ["Male: chestnut head and breast.", "Bright yellow underparts.", "Greenish-brown back.", "Female: pale and plain."],
    si: "Black-headed Bunting — black head (male).",
    h: "Dry steppe with bushes and fields.",
    di: "West (Khar Us Nuur) and Gobi; rare.",
    mi: "Rare visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests in bushes (not regularly in Mongolia).",
    be: "Sings from bush tops.",
    v: "A short, jingling song.",
    cu: "Flocks can damage grain crops in India.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Chestnut head.", "Yellow belly.", "Rare visitor."]
  },
  "black-headed-bunting": {
    T: { c: { yellow: 0.45, black: 0.25, rufous: 0.2, brown: 0.1 }, hb: ["steppe"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["passage"], sz: ["16–18 cm", "—", "23–33 g"] },
    s: "A large bunting; the male has a black hood, chestnut back and yellow underparts. On the Mongolian list, no GBIF records.",
    d: "The Black-headed Bunting breeds from southeast Europe to Iran and winters mainly in India. Records in Mongolia are exceptional.",
    f: ["Male: black hood.", "Bright yellow underparts.", "Chestnut back.", "No white in tail."],
    si: "Red-headed Bunting — chestnut head.",
    h: "Open scrub and fields.",
    di: "Exceptional.",
    mi: "Vagrant.",
    fo: "Seeds and insects.",
    br: "Nests in bushes (not in Mongolia).",
    be: "Sings from high perches.",
    v: "A jangling song.",
    cu: "Migrates east to India rather than south to Africa.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Black hood.", "Yellow belly.", "Exceptional."]
  },
  "chestnut-eared-bunting": {
    T: { c: { brown: 0.35, rufous: 0.25, gray: 0.2, white: 0.1, black: 0.1 }, hb: ["steppe", "water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16 cm", "—", "18–24 g"] },
    s: "A bunting with a grey head, chestnut ear patch and a black-and-chestnut breast band. Breeds in wet meadows of the north and east.",
    d: "The Chestnut-eared Bunting breeds in eastern Asia from Mongolia to Japan and winters further south. In Mongolia it breeds in bushy wet meadows — above all in the Khurkh valley.",
    f: ["Grey crown and nape.", "Chestnut ear patch.", "Black streaked necklace and chestnut band.", "White throat."],
    si: "Meadow Bunting — bold striped head, no breast band.",
    h: "Wet meadows with bushes.",
    di: "Khurkh, Ulaanbaatar, Khustai, Terelj, Yolyn Am.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests on the ground in grass.",
    be: "Sings from bush tops.",
    v: "A fast, twittering song.",
    cu: "Also called the Grey-headed Bunting.",
    co: "Least Concern.",
    w: "Khurkh valley in June.",
    bt: "Jun",
    fa: ["Chestnut ear patch.", "Breast band.", "Khurkh specialty."]
  },
  "jankowskis-bunting": {
    T: { c: { rufous: 0.35, gray: 0.25, brown: 0.2, white: 0.1, black: 0.1 }, hb: ["steppe"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["16 cm", "—", "18–22 g"] },
    s: "An endangered bunting with a rufous back, grey face and dark belly patch. Discovered breeding in eastern Mongolia in 2020.",
    d: "Jankowski's Bunting breeds in the grassy scrub of Manchuria, the Russian Far East and northeast Korea; it has vanished from much of its range. In 2020 it was found breeding in eastern Mongolia — a key refuge for the species.",
    f: ["Rufous back.", "Grey face with dark ear patch.", "Dark chestnut belly patch (male).", "White eyebrow."],
    si: "Meadow Bunting — no belly patch.",
    h: "Steppe with low shrubs.",
    di: "Far east (Dornod).",
    mi: "Summer visitor, May–Oct.",
    fo: "Seeds and insects.",
    br: "Nests on the ground under shrubs.",
    be: "Sings from low bushes.",
    v: "A short, sweet song.",
    cu: "Its Mongolian population may now be one of the largest in the world.",
    co: "Endangered.",
    w: "Eastern steppe in June (with care).",
    bt: "Jun",
    fa: ["Endangered.", "Found in Mongolia in 2020.", "Rufous back."]
  },
  "meadow-bunting": {
    T: { c: { rufous: 0.35, brown: 0.3, white: 0.2, black: 0.15 }, hb: ["steppe", "mountain", "forest"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["resident"], sz: ["15–16.5 cm", "—", "20–25 g"] },
    s: "A rufous bunting with a boldly striped black-and-white face. Common in rocky scrub around Ulaanbaatar and Khustai.",
    d: "The Meadow Bunting lives in eastern Asia, from Central Asia to Japan. In Mongolia it is common in scrubby slopes of the north — Ulaanbaatar, Khustai, Khurkh and Terelj.",
    f: ["Rufous-brown body.", "Bold white eyebrow and moustache.", "Dark cheek patch.", "Streaked back."],
    si: "Godlewski's Bunting — grey head with chestnut stripes.",
    h: "Rocky scrubby slopes and forest edges.",
    di: "Ulaanbaatar, Khustai, Khurkh, Khar Us Nuur, Terelj, Ganga Nuur.",
    mi: "Resident; partly migratory.",
    fo: "Seeds and insects.",
    br: "Nests on the ground or in bushes.",
    be: "Sings from rocks and bush tops.",
    v: "A short, varied song.",
    cu: "Also called the Siberian Meadow Bunting.",
    co: "Least Concern.",
    w: "Khustai slopes in May.",
    bt: "May–Jun",
    fa: ["Striped face.", "Rufous.", "Common near Ulaanbaatar."]
  },
  "godlewskis-bunting": {
    T: { c: { gray: 0.35, rufous: 0.3, brown: 0.2, black: 0.15 }, hb: ["mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["16–17 cm", "—", "18–25 g"] },
    s: "A grey-headed bunting with chestnut head stripes and a rufous body. Common in the rocky mountains of the Gobi and west.",
    d: "Godlewski's Bunting lives in the rocky mountains of Central Asia and China. In Mongolia it is common in rocky gorges — Yolyn Am, Khar Us Nuur, Ulaanbaatar and Terelj.",
    f: ["Grey head.", "Chestnut crown and eye stripes.", "Rufous back and belly.", "Grey throat and breast."],
    si: "Rock Bunting — black head stripes.",
    h: "Rocky gorges and scrubby slopes.",
    di: "Yolyn Am, Khar Us Nuur, Ulaanbaatar, Terelj, Orog Nuur, Khustai.",
    mi: "Resident.",
    fo: "Seeds and insects.",
    br: "Nests among rocks.",
    be: "Hops among boulders.",
    v: "A high, tinkling song.",
    cu: "Named after the Polish collector Wiktor Godlewski.",
    co: "Least Concern.",
    w: "Yolyn Am gorge in May.",
    bt: "May–Jun",
    fa: ["Grey head.", "Chestnut stripes.", "Rocky gorges."]
  },
  "rock-bunting": {
    T: { c: { gray: 0.35, rufous: 0.3, black: 0.2, brown: 0.15 }, hb: ["mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16.5 cm", "22–27 cm", "20–27 g"] },
    s: "A grey-headed bunting with black head stripes and a rufous body. Rare in the far west.",
    d: "The Rock Bunting lives in the mountains of southern Europe, North Africa and Central Asia. In Mongolia it is rare in the far west — mostly around Khar Us Nuur.",
    f: ["Grey head.", "Black crown and eye stripes.", "Rufous belly.", "Streaked brown back."],
    si: "Godlewski's Bunting — chestnut head stripes.",
    h: "Rocky slopes with bushes.",
    di: "Khar Us Nuur, Terkhiin Tsagaan Nuur.",
    mi: "Rare summer visitor.",
    fo: "Seeds and insects.",
    br: "Nests among rocks.",
    be: "Flicks its tail.",
    v: "A thin 'tsi' and a short song.",
    cu: "Its Latin name cia comes from an Italian name for the bird.",
    co: "Least Concern.",
    w: "Not expected.",
    bt: "—",
    fa: ["Black head stripes.", "Rufous belly.", "Rare."]
  },
  "grey-necked-bunting": {
    T: { c: { gray: 0.35, rufous: 0.3, buff: 0.2, white: 0.15 }, hb: ["mountain", "desert"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16 cm", "—", "18–24 g"] },
    s: "A bunting with a plain grey head, white eye ring and pinkish-rufous underparts. Common on dry rocky slopes of the west and Gobi.",
    d: "The Grey-necked Bunting breeds from the Caspian Sea to the Altai and winters in India. In Mongolia it breeds on dry rocky slopes — Khar Us Nuur, Orog Nuur, Yolyn Am and Ölgii.",
    f: ["Plain grey head.", "White eye ring.", "Pinkish throat stripe.", "Rufous underparts."],
    si: "Ortolan Bunting — greenish-grey head, yellow throat.",
    h: "Dry rocky slopes and semi-desert.",
    di: "Khar Us Nuur, Orog Nuur, Yolyn Am, Ölgii, Terkhiin Tsagaan Nuur, Tavan Bogd.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests on the ground among rocks.",
    be: "Sings from rocks.",
    v: "A short, ringing song.",
    cu: "Named after the Scottish physician Francis Buchanan-Hamilton.",
    co: "Least Concern.",
    w: "Khar Us Nuur slopes in June.",
    bt: "Jun",
    fa: ["Grey head.", "Eye ring.", "Rocky slopes."]
  },
  "ortolan-bunting": {
    T: { c: { rufous: 0.3, gray: 0.25, yellow: 0.2, brown: 0.25 }, hb: ["steppe", "mountain"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer"], sz: ["15–16.5 cm", "23–29 cm", "20–25 g"] },
    s: "A bunting with a greenish-grey head, yellow throat and moustache, and pink bill. Breeds in the west and Khangai.",
    d: "The Ortolan Bunting breeds from Europe to western Mongolia and winters in Africa. It has declined sharply in Europe, partly due to illegal hunting in France. In Mongolia it breeds on scrubby slopes — Khar Us Nuur, Terkhiin Tsagaan Nuur, Orkhon and Khövsgöl.",
    f: ["Greenish-grey head.", "Yellow throat and moustache.", "Pale eye ring.", "Pink bill."],
    si: "Grey-necked Bunting — grey head, pinkish throat.",
    h: "Scrubby slopes and forest-steppe.",
    di: "Khar Us Nuur, Terkhiin Tsagaan Nuur, Orkhon, Khövsgöl, Tavan Bogd.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests on the ground.",
    be: "Sings from bushes.",
    v: "A melancholy 'sia-sia-sia-drü-drü'.",
    cu: "Once a French delicacy, eaten with a napkin over the head; hunting is now banned.",
    co: "Least Concern.",
    w: "Terkhiin Tsagaan Nuur in June.",
    bt: "Jun",
    fa: ["Yellow throat.", "Pink bill.", "Former delicacy."]
  },
  "yellowhammer": {
    T: { c: { yellow: 0.5, brown: 0.3, rufous: 0.15, black: 0.05 }, hb: ["steppe", "forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["winter", "passage"], sz: ["16–16.5 cm", "23–29.5 cm", "24–30 g"] },
    s: "A bright yellow bunting with a rusty rump. Scarce in the west and north, often mixed with Pine Buntings.",
    d: "The Yellowhammer lives across Europe and western Siberia; eastern birds migrate. It hybridises with the Pine Bunting where their ranges meet. In Mongolia it is scarce — Khar Us Nuur, Khustai and Khurkh.",
    f: ["Male: bright yellow head.", "Rusty rump.", "Streaked brown back.", "White outer tail."],
    si: "Pine Bunting — white head pattern, chestnut throat.",
    h: "Farmland, forest edges and scrub.",
    di: "Khar Us Nuur, Khustai, Khurkh, Khövsgöl, Ulaanbaatar.",
    mi: "Scarce migrant and winter visitor.",
    fo: "Seeds and insects.",
    br: "Nests on the ground (rarely in Mongolia).",
    be: "Mixes with Pine Buntings.",
    v: "'A little bit of bread and no cheese'.",
    cu: "Its song is said to have inspired Beethoven's Fifth Symphony.",
    co: "Least Concern.",
    w: "Mixed bunting flocks in winter.",
    bt: "Oct–Nov",
    fa: ["Bright yellow.", "Hybridises with Pine Bunting.", "'Bread and no cheese'."]
  },
  "pine-bunting": {
    T: { c: { rufous: 0.35, white: 0.25, brown: 0.25, black: 0.15 }, hb: ["forest", "steppe"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["16–17.5 cm", "26–29 cm", "25–35 g"] },
    s: "A large bunting; the male has a white crown and cheeks and a chestnut throat and eyebrow. Very common in northern forest edges.",
    d: "The Pine Bunting breeds in Siberia east of the Urals and winters from Central Asia to China. In Mongolia it is very common at forest edges of the north — Ulaanbaatar, Terelj, Khurkh and Khövsgöl.",
    f: ["Male: white crown and cheek.", "Chestnut throat and eyebrow.", "Rusty rump.", "Female: streaky, whitish."],
    si: "Yellowhammer — yellow instead of white.",
    h: "Open larch and pine forest, edges.",
    di: "Ulaanbaatar, Terelj, Khurkh, Khövsgöl, Khustai, Khar Us Nuur.",
    mi: "Summer visitor and migrant, Mar–Oct.",
    fo: "Seeds and insects.",
    br: "Nests on the ground.",
    be: "Sings from tree tops.",
    v: "A Yellowhammer-like song.",
    cu: "Hybrids with Yellowhammers can show yellow and white.",
    co: "Least Concern.",
    w: "Terelj in June.",
    bt: "May–Jun",
    fa: ["White crown.", "Chestnut throat.", "Very common."]
  }
});
