B2T("fr", {
  "red-headed-bunting": {
    name: "Bruant à tête rousse",
    s: "Bruant à tête et poitrine châtain et dessous jaune vif. Visiteur rare dans l’ouest et le Gobi.",
    d: "Le Bruant à tête rousse niche dans les steppes d’Asie centrale et hiverne en Inde. En Mongolie, c’est un visiteur rare, surtout en juin — extrême ouest et Gobi.",
    f: ["Mâle : tête et poitrine châtain.", "Dessous jaune vif.", "Dos brun verdâtre.", "Femelle : pâle et terne."],
    si: "Bruant mélanocéphale — tête noire (mâle).",
    h: "Steppe sèche buissonnante et champs.",
    di: "Ouest (lac Khar Us) et Gobi ; rare.",
    mi: "Visiteur rare, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche dans les buissons (pas régulièrement en Mongolie).",
    be: "Chante du sommet des buissons.",
    v: "Un court chant cliquetant.",
    cu: "Ses bandes peuvent endommager les céréales en Inde.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Tête châtain.", "Ventre jaune.", "Visiteur rare."]
  },
  "black-headed-bunting": {
    name: "Bruant mélanocéphale",
    s: "Grand bruant ; le mâle a un capuchon noir, le dos châtain et le dessous jaune. Inscrit pour la Mongolie, sans mention GBIF.",
    d: "Le Bruant mélanocéphale niche du sud-est de l’Europe à l’Iran et hiverne surtout en Inde. Les mentions en Mongolie sont exceptionnelles.",
    f: ["Mâle : capuchon noir.", "Dessous jaune vif.", "Dos châtain.", "Pas de blanc à la queue."],
    si: "Bruant à tête rousse — tête châtain.",
    h: "Broussailles ouvertes et champs.",
    di: "Exceptionnel.",
    mi: "Erratique.",
    fo: "Graines et insectes.",
    br: "Niche dans les buissons (pas en Mongolie).",
    be: "Chante de perchoirs élevés.",
    v: "Un chant cliquetant.",
    cu: "Migre vers l’est, en Inde, plutôt que vers l’Afrique.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Capuchon noir.", "Ventre jaune.", "Exceptionnel."]
  },
  "chestnut-eared-bunting": {
    name: "Bruant à oreillons",
    s: "Bruant à tête grise, joue châtain et bande pectorale noire et châtain. Niche dans les prairies humides du nord et de l’est.",
    d: "Le Bruant à oreillons niche en Asie orientale, de la Mongolie au Japon, et hiverne plus au sud. En Mongolie, il niche dans les prairies humides buissonnantes — surtout dans la vallée de Khurkh.",
    f: ["Calotte et nuque grises.", "Joue châtain.", "Collier strié de noir et bande châtain.", "Gorge blanche."],
    si: "Bruant à longue queue — tête rayée, sans bande pectorale.",
    h: "Prairies humides buissonnantes.",
    di: "Khurkh, Oulan-Bator, Khustai, Terelj, Yolyn Am.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol dans l’herbe.",
    be: "Chante du sommet des buissons.",
    v: "Un chant rapide et gazouillé.",
    cu: "Aussi appelé Bruant à tête grise.",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en juin.",
    bt: "juin",
    fa: ["Joue châtain.", "Bande pectorale.", "Spécialité de Khurkh."]
  },
  "jankowskis-bunting": {
    name: "Bruant de Jankowski",
    s: "Bruant menacé à dos roux, face grise et tache ventrale sombre. Découvert nicheur dans l’est de la Mongolie en 2020.",
    d: "Le Bruant de Jankowski niche dans les broussailles herbeuses de Mandchourie, de l’Extrême-Orient russe et du nord-est de la Corée ; il a disparu de la plus grande partie de son aire. En 2020, il a été découvert nicheur dans l’est de la Mongolie — un refuge clé pour l’espèce.",
    f: ["Dos roux.", "Face grise à joue sombre.", "Tache ventrale châtain foncé (mâle).", "Sourcil blanc."],
    si: "Bruant à longue queue — sans tache ventrale.",
    h: "Steppe à arbustes bas.",
    di: "Extrême est (Dornod).",
    mi: "Estivant, mai–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol sous les arbustes.",
    be: "Chante depuis les buissons bas.",
    v: "Un court chant mélodieux.",
    cu: "Sa population mongole pourrait être l’une des plus importantes au monde.",
    co: "En danger.",
    w: "Steppe orientale en juin (avec précaution).",
    bt: "juin",
    fa: ["En danger.", "Découvert en Mongolie en 2020.", "Dos roux."]
  },
  "meadow-bunting": {
    name: "Bruant à longue queue",
    s: "Bruant roux à la face nettement rayée de noir et blanc. Commun dans les broussailles rocheuses autour d’Oulan-Bator et de Khustai.",
    d: "Le Bruant à longue queue vit en Asie orientale, de l’Asie centrale au Japon. En Mongolie, il est commun sur les pentes buissonnantes du nord — Oulan-Bator, Khustai, Khurkh et Terelj.",
    f: ["Corps brun roux.", "Net sourcil et moustache blancs.", "Joue sombre.", "Dos strié."],
    si: "Bruant de Godlewski — tête grise rayée de châtain.",
    h: "Pentes rocheuses buissonnantes et lisières.",
    di: "Oulan-Bator, Khustai, Khurkh, lac Khar Us, Terelj, lac Ganga.",
    mi: "Résident ; en partie migrateur.",
    fo: "Graines et insectes.",
    br: "Niche au sol ou dans les buissons.",
    be: "Chante sur les rochers et buissons.",
    v: "Un chant court et varié.",
    cu: "Aussi appelé Bruant des prés de Sibérie.",
    co: "Préoccupation mineure.",
    w: "Pentes de Khustai en mai.",
    bt: "mai–juin",
    fa: ["Face rayée.", "Roux.", "Commun près d’Oulan-Bator."]
  },
  "godlewskis-bunting": {
    name: "Bruant de Godlewski",
    s: "Bruant à tête grise rayée de châtain et corps roux. Commun dans les montagnes rocheuses du Gobi et de l’ouest.",
    d: "Le Bruant de Godlewski vit dans les montagnes rocheuses d’Asie centrale et de Chine. En Mongolie, il est commun dans les gorges rocheuses — Yolyn Am, lac Khar Us, Oulan-Bator et Terelj.",
    f: ["Tête grise.", "Bandes coronales et oculaires châtain.", "Dos et ventre roux.", "Gorge et poitrine grises."],
    si: "Bruant fou — bandes céphaliques noires.",
    h: "Gorges rocheuses et pentes buissonnantes.",
    di: "Yolyn Am, lac Khar Us, Oulan-Bator, Terelj, lac Orog, Khustai.",
    mi: "Résident.",
    fo: "Graines et insectes.",
    br: "Niche parmi les rochers.",
    be: "Sautille entre les blocs.",
    v: "Un chant aigu et tintant.",
    cu: "Nommé d’après le collecteur polonais Wiktor Godlewski.",
    co: "Préoccupation mineure.",
    w: "Gorge de Yolyn Am en mai.",
    bt: "mai–juin",
    fa: ["Tête grise.", "Bandes châtain.", "Gorges rocheuses."]
  },
  "rock-bunting": {
    name: "Bruant fou",
    s: "Bruant à tête grise rayée de noir et corps roux. Rare dans l’extrême ouest.",
    d: "Le Bruant fou vit dans les montagnes d’Europe du Sud, d’Afrique du Nord et d’Asie centrale. En Mongolie, il est rare dans l’extrême ouest — surtout autour du lac Khar Us.",
    f: ["Tête grise.", "Bandes coronales et oculaires noires.", "Ventre roux.", "Dos brun strié."],
    si: "Bruant de Godlewski — bandes céphaliques châtain.",
    h: "Pentes rocheuses buissonnantes.",
    di: "Lac Khar Us, Terkhiin Tsagaan Nuur.",
    mi: "Estivant rare.",
    fo: "Graines et insectes.",
    br: "Niche parmi les rochers.",
    be: "Agite la queue.",
    v: "Un « tsi » fin et un court chant.",
    cu: "Son nom latin cia vient d’un nom italien de l’oiseau.",
    co: "Préoccupation mineure.",
    w: "Non attendu.",
    bt: "—",
    fa: ["Bandes noires.", "Ventre roux.", "Rare."]
  },
  "grey-necked-bunting": {
    name: "Bruant à cou gris",
    s: "Bruant à tête grise unie, cercle oculaire blanc et dessous roux rosé. Commun sur les pentes rocheuses sèches de l’ouest et du Gobi.",
    d: "Le Bruant à cou gris niche de la mer Caspienne à l’Altaï et hiverne en Inde. En Mongolie, il niche sur les pentes rocheuses sèches — lac Khar Us, lac Orog, Yolyn Am et Ölgii.",
    f: ["Tête grise unie.", "Cercle oculaire blanc.", "Trait gulaire rosé.", "Dessous roux."],
    si: "Bruant ortolan — tête gris verdâtre, gorge jaune.",
    h: "Pentes rocheuses sèches et semi-désert.",
    di: "Lac Khar Us, lac Orog, Yolyn Am, Ölgii, Terkhiin Tsagaan Nuur, Tavan Bogd.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol parmi les rochers.",
    be: "Chante sur les rochers.",
    v: "Un chant court et sonore.",
    cu: "Nommé d’après le médecin écossais Francis Buchanan-Hamilton.",
    co: "Préoccupation mineure.",
    w: "Pentes du lac Khar Us en juin.",
    bt: "juin",
    fa: ["Tête grise.", "Cercle oculaire.", "Pentes rocheuses."]
  },
  "ortolan-bunting": {
    name: "Bruant ortolan",
    s: "Bruant à tête gris verdâtre, gorge et moustache jaunes et bec rose. Niche dans l’ouest et le Khangaï.",
    d: "Le Bruant ortolan niche de l’Europe à l’ouest de la Mongolie et hiverne en Afrique. Il a fortement décliné en Europe, en partie à cause du braconnage en France. En Mongolie, il niche sur les pentes buissonnantes — lac Khar Us, Terkhiin Tsagaan Nuur, Orkhon et Khövsgöl.",
    f: ["Tête gris verdâtre.", "Gorge et moustache jaunes.", "Cercle oculaire pâle.", "Bec rose."],
    si: "Bruant à cou gris — tête grise, gorge rosée.",
    h: "Pentes buissonnantes et steppe boisée.",
    di: "Lac Khar Us, Terkhiin Tsagaan Nuur, Orkhon, Khövsgöl, Tavan Bogd.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol.",
    be: "Chante dans les buissons.",
    v: "Un mélancolique « sia-sia-sia-dru-dru ».",
    cu: "Mets français autrefois dégusté la tête sous une serviette ; sa chasse est désormais interdite.",
    co: "Préoccupation mineure.",
    w: "Terkhiin Tsagaan Nuur en juin.",
    bt: "juin",
    fa: ["Gorge jaune.", "Bec rose.", "Ancien mets de luxe."]
  },
  "yellowhammer": {
    name: "Bruant jaune",
    s: "Bruant jaune vif au croupion roux. Peu commun dans l’ouest et le nord, souvent mêlé aux Bruants à calotte blanche.",
    d: "Le Bruant jaune vit en Europe et en Sibérie occidentale ; les oiseaux de l’est migrent. Il s’hybride avec le Bruant à calotte blanche là où leurs aires se rencontrent. En Mongolie, il est peu commun — lac Khar Us, Khustai et Khurkh.",
    f: ["Mâle : tête jaune vif.", "Croupion roux.", "Dos brun strié.", "Rectrices externes blanches."],
    si: "Bruant à calotte blanche — motif céphalique blanc, gorge châtain.",
    h: "Cultures, lisières et broussailles.",
    di: "Lac Khar Us, Khustai, Khurkh, Khövsgöl, Oulan-Bator.",
    mi: "Migrateur et hivernant peu commun.",
    fo: "Graines et insectes.",
    br: "Niche au sol (rarement en Mongolie).",
    be: "Se mêle aux Bruants à calotte blanche.",
    v: "Une série de notes terminée par une note traînante.",
    cu: "Son chant aurait inspiré la Cinquième Symphonie de Beethoven.",
    co: "Préoccupation mineure.",
    w: "Bandes mixtes de bruants en hiver.",
    bt: "oct.–nov.",
    fa: ["Jaune vif.", "S’hybride avec le calotte blanche.", "Lien avec Beethoven."]
  },
  "pine-bunting": {
    name: "Bruant à calotte blanche",
    s: "Grand bruant ; le mâle a la calotte et les joues blanches, la gorge et le sourcil châtain. Très commun en lisière des forêts du nord.",
    d: "Le Bruant à calotte blanche niche en Sibérie à l’est de l’Oural et hiverne de l’Asie centrale à la Chine. En Mongolie, il est très commun en lisière des forêts du nord — Oulan-Bator, Terelj, Khurkh et Khövsgöl.",
    f: ["Mâle : calotte et joue blanches.", "Gorge et sourcil châtain.", "Croupion roux.", "Femelle : striée, blanchâtre."],
    si: "Bruant jaune — du jaune au lieu du blanc.",
    h: "Forêts claires de mélèzes et de pins, lisières.",
    di: "Oulan-Bator, Terelj, Khurkh, Khövsgöl, Khustai, lac Khar Us.",
    mi: "Estivant et migrateur, mars–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol.",
    be: "Chante à la cime des arbres.",
    v: "Un chant proche de celui du Bruant jaune.",
    cu: "Les hybrides avec le Bruant jaune montrent parfois du jaune et du blanc.",
    co: "Préoccupation mineure.",
    w: "Terelj en juin.",
    bt: "mai–juin",
    fa: ["Calotte blanche.", "Gorge châtain.", "Très commun."]
  }
});
