B2T("en", {
  "yellow-throated-bunting": {
    T: { c: { yellow: 0.3, black: 0.25, brown: 0.25, white: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["15–16 cm", "—", "15–22 g"] },
    s: "A striking bunting with a black crest, black mask and bright yellow eyebrow and throat. A scarce migrant in the east.",
    d: "The Yellow-throated Bunting breeds in the woods of northeast China, Korea and the Russian Far East. In Mongolia it is a scarce migrant in the east — Ganga Nuur, with odd records at Terelj and Ulaanbaatar.",
    f: ["Black crest.", "Bright yellow eyebrow and throat.", "Black mask and breast patch.", "Chestnut-streaked back."],
    si: "Yellow-browed Bunting — no crest, black-and-white head.",
    h: "Forest edges and undergrowth.",
    di: "Ganga Nuur, Terelj, Ulaanbaatar; east.",
    mi: "Passage migrant, May and Oct.",
    fo: "Seeds and insects.",
    br: "Nests on the ground (not in Mongolia).",
    be: "Raises its crest when alarmed.",
    v: "A thin 'tzik'.",
    cu: "Also called the Elegant Bunting.",
    co: "Least Concern.",
    w: "Eastern oases in October.",
    bt: "Oct",
    fa: ["Crested.", "Yellow throat.", "Scarce migrant."]
  },
  "japanese-reed-bunting": {
    T: { c: { rufous: 0.35, black: 0.3, buff: 0.2, white: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer"], sz: ["14–15 cm", "—", "13–16 g"] },
    s: "A small reed bunting; the male has a black head and an ochre-cinnamon rump. Local in eastern marshes; Near Threatened.",
    d: "The Ochre-rumped Bunting lives in the grassy marshes of Manchuria, Korea and Japan. It is Near Threatened by the loss of wetlands. In Mongolia it breeds only in the marshes of the far east — Buir Nuur and the Daguur area.",
    f: ["Male: all-black head.", "Ochre-cinnamon rump.", "Streaked rufous back.", "No white collar."],
    si: "Eurasian Reed Bunting — white collar and moustache.",
    h: "Wet grassy marshes and reedbeds.",
    di: "Buir Nuur, Daguur, Dornod marshes.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests on the ground in grass tussocks.",
    be: "Sings from reed tops.",
    v: "A short, twittering song.",
    cu: "Also called the Ochre-rumped Bunting.",
    co: "Near Threatened.",
    w: "Buir Nuur marshes in May.",
    bt: "May–Jul",
    fa: ["Ochre rump.", "Black head.", "Near Threatened."]
  },
  "pallass-reed-bunting": {
    T: { c: { white: 0.35, black: 0.25, brown: 0.25, buff: 0.15 }, hb: ["water", "steppe"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13–14 cm", "—", "12–15 g"] },
    s: "A small, pale reed bunting; the male has a black head and throat and a white collar. Very common on migration.",
    d: "Pallas's Reed Bunting breeds in the steppe and tundra of Siberia and Mongolia and winters in China. In Mongolia it breeds in wet steppe and passes in large numbers — Khurkh, Ögii Nuur, Ulaanbaatar and Buir Nuur.",
    f: ["Male: black head and throat.", "White collar and moustache.", "Pale, sandy back.", "Whitish rump."],
    si: "Eurasian Reed Bunting — larger, darker, rufous wing coverts.",
    h: "Wet steppe, willow scrub and reedbeds.",
    di: "Khurkh, Ögii Nuur, Ulaanbaatar, Buir Nuur, Yolyn Am, Khustai.",
    mi: "Summer visitor and migrant, Apr–Oct.",
    fo: "Seeds and insects.",
    br: "Nests on the ground.",
    be: "Flocks on passage.",
    v: "A sparrow-like 'chleep'.",
    cu: "Named after Peter Simon Pallas.",
    co: "Least Concern.",
    w: "Ögii Nuur in May.",
    bt: "May",
    fa: ["Black head.", "White collar.", "Very common."]
  },
  "eurasian-reed-bunting": {
    T: { c: { brown: 0.35, black: 0.25, white: 0.25, rufous: 0.15 }, hb: ["water"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["13.5–15.5 cm", "21–28 cm", "15–22 g"] },
    s: "A reed bunting; the male has a black head and throat, white collar and moustache. Common in reedbeds across Mongolia.",
    d: "The Common Reed Bunting breeds across Europe and the Palearctic. In Mongolia it breeds in reedbeds — Khar Us Nuur, Khurkh, Ulaanbaatar and Buir Nuur.",
    f: ["Male: black head and throat.", "White moustache and collar.", "Streaked rufous-brown back.", "Rufous wing coverts."],
    si: "Pallas's Reed Bunting — smaller, paler.",
    h: "Reedbeds and wet scrub.",
    di: "Khar Us Nuur, Khurkh, Ulaanbaatar, Buir Nuur, Ganga Nuur, Yolyn Am.",
    mi: "Summer visitor and migrant, Mar–Oct.",
    fo: "Seeds and insects.",
    br: "Nests low in reeds or tussocks.",
    be: "Sings from reed tops.",
    v: "A simple 'tweek-tweek-tititick'.",
    cu: "Females fake injury to lure predators away from the nest.",
    co: "Least Concern.",
    w: "Khar Us Nuur reeds in May.",
    bt: "May–Jun",
    fa: ["Black head.", "White moustache.", "Reedbed bird."]
  },
  "black-faced-bunting": {
    T: { c: { gray: 0.35, yellow: 0.3, brown: 0.2, black: 0.15 }, hb: ["forest", "water"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["14–16 cm", "—", "15–22 g"] },
    s: "A bunting with a dark grey-green head, black face and yellowish underparts. Very common in the thickets of the north.",
    d: "The Black-faced Bunting breeds in the undergrowth of Siberia, northern China and Japan and winters in southern China. In Mongolia it is very common in riverine thickets — Khurkh, Ulaanbaatar, Terelj and Yolyn Am.",
    f: ["Male: grey-green head.", "Black face.", "Yellowish underparts.", "Streaked brown back."],
    si: "Yellow-breasted Bunting — chestnut back, yellow breast.",
    h: "Riverine thickets and forest undergrowth.",
    di: "Khurkh, Ulaanbaatar, Terelj, Yolyn Am, Buir Nuur, Ganga Nuur.",
    mi: "Summer visitor and migrant, May–Oct.",
    fo: "Seeds and insects.",
    br: "Nests low in bushes.",
    be: "Flicks its tail showing white edges.",
    v: "A sharp 'tzit'.",
    cu: "One of the most frequent buntings in Mongolian thickets.",
    co: "Least Concern.",
    w: "Khurkh in May.",
    bt: "May–Jun",
    fa: ["Black face.", "Grey-green head.", "Very common."]
  },
  "rustic-bunting": {
    T: { c: { rufous: 0.35, white: 0.3, black: 0.2, brown: 0.15 }, hb: ["forest", "water"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["13–14.5 cm", "—", "16–24 g"] },
    s: "A bunting with a small crest, black-and-white head and rusty breast band. A migrant, mostly in autumn; Near Threatened.",
    d: "The Rustic Bunting breeds in the boggy taiga of northern Eurasia and winters in China and Japan. Its population has declined sharply. In Mongolia it is a migrant, mostly in October — Ulaanbaatar, Khurkh and Ganga Nuur.",
    f: ["Small crest.", "Black-and-white head (male).", "Rusty breast band and flank streaks.", "White belly."],
    si: "Little Bunting — smaller, rufous face.",
    h: "Wet forest, thickets on passage.",
    di: "Ulaanbaatar, Khurkh, Khar Us Nuur, Ganga Nuur, Khustai, Buir Nuur.",
    mi: "Passage migrant, Apr–May and Sep–Oct.",
    fo: "Seeds and insects.",
    br: "Nests in taiga bogs (not in Mongolia).",
    be: "Raises its crest.",
    v: "A sharp 'tsip'.",
    cu: "Declined by up to 90% since 1980.",
    co: "Near Threatened.",
    w: "Ulaanbaatar in October.",
    bt: "Oct",
    fa: ["Crested.", "Rusty breast band.", "Near Threatened."]
  },
  "chestnut-bunting": {
    T: { c: { rufous: 0.45, yellow: 0.35, brown: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "A small bunting; the male is rich chestnut above and on the breast with yellow underparts. A migrant in the north and east.",
    d: "The Chestnut Bunting breeds in the taiga of Siberia and winters in southern China and Southeast Asia. In Mongolia it is a migrant, especially in August — above all in the Khurkh valley.",
    f: ["Male: chestnut head, back and breast.", "Yellow underparts.", "Short tail, little white.", "Female: plain olive-brown."],
    si: "Yellow-breasted Bunting — white wing patch, black face.",
    h: "Forest undergrowth and thickets.",
    di: "Khurkh, Buir Nuur, Ganga Nuur, Khövsgöl, Orkhon.",
    mi: "Passage migrant, May and Aug–Sep.",
    fo: "Seeds and insects.",
    br: "Nests in Siberian forests (not in Mongolia).",
    be: "Feeds on the ground in cover.",
    v: "A thin 'zip'.",
    cu: "Its Latin name rutila means 'reddish'.",
    co: "Least Concern.",
    w: "Khurkh valley in August.",
    bt: "Aug",
    fa: ["Chestnut.", "Yellow belly.", "Khurkh migrant."]
  },
  "little-bunting": {
    T: { c: { brown: 0.4, rufous: 0.25, white: 0.2, black: 0.15 }, hb: ["forest", "water"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["12–14 cm", "—", "12–18 g"] },
    s: "A small, streaky bunting with a rufous face and crown stripe. The commonest bunting on migration.",
    d: "The Little Bunting breeds in the Siberian taiga and winters in China and Southeast Asia. In Mongolia it is an abundant migrant in May and September — Khurkh, Ulaanbaatar, Yolyn Am and Terelj.",
    f: ["Rufous face and crown stripe.", "Pale eye ring.", "Fine breast streaks.", "Straight-edged bill."],
    si: "Rustic Bunting — larger, rusty breast band.",
    h: "Thickets, meadows and fields on passage.",
    di: "Khurkh, Ulaanbaatar, Yolyn Am, Terelj, Khar Us Nuur, Khustai.",
    mi: "Passage migrant, May and Sep.",
    fo: "Seeds and insects.",
    br: "Nests in Siberian taiga (not in Mongolia).",
    be: "Feeds unobtrusively on the ground.",
    v: "A hard 'tik'.",
    cu: "First described by Peter Simon Pallas in 1776.",
    co: "Least Concern.",
    w: "Khurkh in May.",
    bt: "May, Sep",
    fa: ["Rufous face.", "Small.", "Abundant migrant."]
  },
  "yellow-breasted-bunting": {
    T: { c: { yellow: 0.4, rufous: 0.25, black: 0.15, white: 0.1, brown: 0.1 }, hb: ["water", "steppe"], bk: "short", bh: ["perch"], vt: ["song"], ac: "day", se: ["summer", "passage"], sz: ["14–16 cm", "—", "17–27 g"] },
    s: "A bunting with a yellow breast, chestnut back and neck band, black face and a white wing patch. Critically Endangered; still breeds in the north.",
    d: "The Yellow-breasted Bunting was once one of the most abundant birds of Eurasia; mass trapping on its wintering grounds in China caused a 90% crash. In Mongolia it still breeds in wet meadows — especially the Khurkh valley, Ulaanbaatar and Terelj.",
    f: ["Male: black face.", "Yellow underparts.", "Chestnut breast band and back.", "Big white wing patch."],
    si: "Chestnut Bunting — no white wing patch.",
    h: "Wet meadows with bushes, willow scrub.",
    di: "Khurkh, Ulaanbaatar, Terelj, Ögii Nuur, Daguur, Böön Tsagaan.",
    mi: "Summer visitor, May–Sep.",
    fo: "Seeds and insects.",
    br: "Nests low in bushes or grass.",
    be: "Sings from bush tops.",
    v: "A loud, varied 'tsi-tsi-tsuu'.",
    cu: "Trapped in China as 'rice bird'; now fully protected.",
    co: "Critically Endangered.",
    w: "Khurkh valley in June (do not disturb nests).",
    bt: "Jun",
    fa: ["Critically Endangered.", "White wing patch.", "Still breeds in Mongolia."]
  },
  "yellow-browed-bunting": {
    T: { c: { brown: 0.35, black: 0.25, white: 0.2, yellow: 0.2 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "A bunting with a black-and-white striped head and a yellow front to the eyebrow. An uncommon autumn migrant in the east and north.",
    d: "The Yellow-browed Bunting breeds in central Siberia and winters in southern China. In Mongolia it is an uncommon migrant, mostly in August–September — Khurkh and Buir Nuur.",
    f: ["Black crown with white centre stripe.", "Yellow front of eyebrow.", "Black cheek.", "Streaked breast."],
    si: "Tristram's Bunting — no yellow, black throat.",
    h: "Forest undergrowth and thickets.",
    di: "Khurkh, Buir Nuur, Ganga Nuur, Onon, Khar Us Nuur.",
    mi: "Passage migrant, May and Aug–Sep.",
    fo: "Seeds and insects.",
    br: "Nests in Siberian forests (not in Mongolia).",
    be: "Feeds on the ground.",
    v: "A thin 'tsip'.",
    cu: "Its Latin name chrysophrys means 'golden eyebrow'.",
    co: "Least Concern.",
    w: "Khurkh in September.",
    bt: "Sep",
    fa: ["Yellow eyebrow.", "Striped head.", "Autumn migrant."]
  },
  "tristrams-bunting": {
    T: { c: { black: 0.3, white: 0.3, brown: 0.3, rufous: 0.1 }, hb: ["forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["passage"], sz: ["14–15 cm", "—", "15–20 g"] },
    s: "A bunting with a boldly black-and-white striped head and black throat. A scarce migrant in the east and Gobi.",
    d: "Tristram's Bunting breeds in eastern Manchuria and the Russian Far East and winters in central and southern China. In Mongolia it is a scarce migrant, mostly in May — Khurkh, Ganga Nuur and Buir Nuur.",
    f: ["Bold black-and-white head stripes.", "Black throat (male).", "Rufous rump.", "Streaked brown back."],
    si: "Yellow-browed Bunting — yellow on eyebrow, white throat.",
    h: "Forest undergrowth.",
    di: "Khurkh, Ganga Nuur, Buir Nuur, Gobi oases.",
    mi: "Passage migrant, May and Sep.",
    fo: "Seeds and insects.",
    br: "Nests in forests (not in Mongolia).",
    be: "Skulks on the forest floor.",
    v: "A soft 'tzip'.",
    cu: "Named after the English cleric and naturalist Henry Baker Tristram.",
    co: "Least Concern.",
    w: "Khurkh in May.",
    bt: "May",
    fa: ["Striped head.", "Black throat.", "Scarce migrant."]
  }
});
