B2T("fr", {
  "yellow-throated-bunting": {
    name: "Bruant élégant",
    s: "Bruant frappant à huppe noire, masque noir, sourcil et gorge jaune vif. Migrateur peu commun dans l’est.",
    d: "Le Bruant élégant niche dans les bois du nord-est de la Chine, de la Corée et de l’Extrême-Orient russe. En Mongolie, c’est un migrateur peu commun dans l’est — lac Ganga, avec quelques mentions à Terelj et Oulan-Bator.",
    f: ["Huppe noire.", "Sourcil et gorge jaune vif.", "Masque et plastron noirs.", "Dos strié de châtain."],
    si: "Bruant à sourcils jaunes — sans huppe, tête noir et blanc.",
    h: "Lisières et sous-bois.",
    di: "Lac Ganga, Terelj, Oulan-Bator ; est.",
    mi: "Migrateur, mai et octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol (pas en Mongolie).",
    be: "Dresse sa huppe quand il est inquiet.",
    v: "Un « tzik » fin.",
    cu: "Son nom anglais signifie « bruant à gorge jaune ».",
    co: "Préoccupation mineure.",
    w: "Oasis de l’est en octobre.",
    bt: "oct.",
    fa: ["Huppé.", "Gorge jaune.", "Migrateur peu commun."]
  },
  "japanese-reed-bunting": {
    name: "Bruant de Yéso",
    s: "Petit bruant des marais ; le mâle a la tête noire et le croupion ocre-cannelle. Local dans les marais de l’est ; Quasi menacé.",
    d: "Le Bruant de Yéso vit dans les marais herbeux de Mandchourie, de Corée et du Japon. Il est Quasi menacé par la disparition des zones humides. En Mongolie, il ne niche que dans les marais de l’extrême est — lac Buir et région de Daguur.",
    f: ["Mâle : tête entièrement noire.", "Croupion ocre-cannelle.", "Dos roux strié.", "Pas de collier blanc."],
    si: "Bruant des roseaux — collier et moustache blancs.",
    h: "Marais herbeux humides et roselières.",
    di: "Lac Buir, Daguur, marais du Dornod.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche au sol dans les touradons.",
    be: "Chante au sommet des roseaux.",
    v: "Un court chant gazouillé.",
    cu: "Yéso est l’ancien nom d’Hokkaido.",
    co: "Quasi menacé.",
    w: "Marais du lac Buir en mai.",
    bt: "mai–juil.",
    fa: ["Croupion ocre.", "Tête noire.", "Quasi menacé."]
  },
  "pallass-reed-bunting": {
    name: "Bruant de Pallas",
    s: "Petit bruant des marais pâle ; le mâle a la tête et la gorge noires et un collier blanc. Très commun en migration.",
    d: "Le Bruant de Pallas niche dans la steppe et la toundra de Sibérie et de Mongolie et hiverne en Chine. En Mongolie, il niche dans la steppe humide et passe en grand nombre — Khurkh, lac Ögii, Oulan-Bator et lac Buir.",
    f: ["Mâle : tête et gorge noires.", "Collier et moustache blancs.", "Dos pâle sableux.", "Croupion blanchâtre."],
    si: "Bruant des roseaux — plus grand, plus sombre, couvertures rousses.",
    h: "Steppe humide, saulaies et roselières.",
    di: "Khurkh, lac Ögii, Oulan-Bator, lac Buir, Yolyn Am, Khustai.",
    mi: "Estivant et migrateur, avril–octobre.",
    fo: "Graines et insectes.",
    br: "Niche au sol.",
    be: "En groupes en migration.",
    v: "Un « tchlip » de moineau.",
    cu: "Nommé d’après Peter Simon Pallas.",
    co: "Préoccupation mineure.",
    w: "Lac Ögii en mai.",
    bt: "mai",
    fa: ["Tête noire.", "Collier blanc.", "Très commun."]
  },
  "eurasian-reed-bunting": {
    name: "Bruant des roseaux",
    s: "Bruant des roselières ; le mâle a la tête et la gorge noires, le collier et la moustache blancs. Commun dans les roselières de toute la Mongolie.",
    d: "Le Bruant des roseaux niche dans toute l’Europe et le Paléarctique. En Mongolie, il niche dans les roselières — lac Khar Us, Khurkh, Oulan-Bator et lac Buir.",
    f: ["Mâle : tête et gorge noires.", "Moustache et collier blancs.", "Dos brun roux strié.", "Couvertures alaires rousses."],
    si: "Bruant de Pallas — plus petit, plus pâle.",
    h: "Roselières et broussailles humides.",
    di: "Lac Khar Us, Khurkh, Oulan-Bator, lac Buir, lac Ganga, Yolyn Am.",
    mi: "Estivant et migrateur, mars–octobre.",
    fo: "Graines et insectes.",
    br: "Niche bas dans les roseaux ou touradons.",
    be: "Chante au sommet des roseaux.",
    v: "Un simple « tswik-tswik-tititik ».",
    cu: "La femelle simule une blessure pour éloigner les prédateurs du nid.",
    co: "Préoccupation mineure.",
    w: "Roseaux du lac Khar Us en mai.",
    bt: "mai–juin",
    fa: ["Tête noire.", "Moustache blanche.", "Oiseau des roselières."]
  },
  "black-faced-bunting": {
    name: "Bruant masqué",
    s: "Bruant à tête gris-vert foncé, face noire et dessous jaunâtre. Très commun dans les fourrés du nord.",
    d: "Le Bruant masqué niche dans le sous-bois de Sibérie, du nord de la Chine et du Japon et hiverne dans le sud de la Chine. En Mongolie, il est très commun dans les fourrés riverains — Khurkh, Oulan-Bator, Terelj et Yolyn Am.",
    f: ["Mâle : tête gris-vert.", "Face noire.", "Dessous jaunâtre.", "Dos brun strié."],
    si: "Bruant auréole — dos châtain, poitrine jaune.",
    h: "Fourrés riverains et sous-bois.",
    di: "Khurkh, Oulan-Bator, Terelj, Yolyn Am, lac Buir, lac Ganga.",
    mi: "Estivant et migrateur, mai–octobre.",
    fo: "Graines et insectes.",
    br: "Niche bas dans les buissons.",
    be: "Agite la queue en montrant ses bords blancs.",
    v: "Un « tzit » sec.",
    cu: "L’un des bruants les plus fréquents dans les fourrés mongols.",
    co: "Préoccupation mineure.",
    w: "Khurkh en mai.",
    bt: "mai–juin",
    fa: ["Face noire.", "Tête gris-vert.", "Très commun."]
  },
  "rustic-bunting": {
    name: "Bruant rustique",
    s: "Bruant à petite huppe, tête noir et blanc et bande pectorale rousse. Migrateur, surtout en automne ; Quasi menacé.",
    d: "Le Bruant rustique niche dans la taïga marécageuse du nord de l’Eurasie et hiverne en Chine et au Japon. Sa population a fortement décliné. En Mongolie, c’est un migrateur, surtout en octobre — Oulan-Bator, Khurkh et lac Ganga.",
    f: ["Petite huppe.", "Tête noir et blanc (mâle).", "Bande pectorale et stries des flancs rousses.", "Ventre blanc."],
    si: "Bruant nain — plus petit, face rousse.",
    h: "Forêts humides, fourrés en migration.",
    di: "Oulan-Bator, Khurkh, lac Khar Us, lac Ganga, Khustai, lac Buir.",
    mi: "Migrateur, avril–mai et septembre–octobre.",
    fo: "Graines et insectes.",
    br: "Niche dans les tourbières de la taïga (pas en Mongolie).",
    be: "Dresse sa huppe.",
    v: "Un « tsip » sec.",
    cu: "A décliné jusqu’à 90 % depuis 1980.",
    co: "Quasi menacé.",
    w: "Oulan-Bator en octobre.",
    bt: "oct.",
    fa: ["Huppé.", "Bande pectorale rousse.", "Quasi menacé."]
  },
  "chestnut-bunting": {
    name: "Bruant roux",
    s: "Petit bruant ; le mâle est châtain vif dessus et sur la poitrine, jaune dessous. Migrateur dans le nord et l’est.",
    d: "Le Bruant roux niche dans la taïga sibérienne et hiverne dans le sud de la Chine et en Asie du Sud-Est. En Mongolie, c’est un migrateur, surtout en août — avant tout dans la vallée de Khurkh.",
    f: ["Mâle : tête, dos et poitrine châtain.", "Dessous jaune.", "Queue courte, peu de blanc.", "Femelle : brun olive terne."],
    si: "Bruant auréole — tache alaire blanche, face noire.",
    h: "Sous-bois et fourrés.",
    di: "Khurkh, lac Buir, lac Ganga, Khövsgöl, Orkhon.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Graines et insectes.",
    br: "Niche dans les forêts sibériennes (pas en Mongolie).",
    be: "Se nourrit au sol à couvert.",
    v: "Un « zip » fin.",
    cu: "Son nom latin rutila signifie « rougeâtre ».",
    co: "Préoccupation mineure.",
    w: "Vallée de Khurkh en août.",
    bt: "août",
    fa: ["Châtain.", "Ventre jaune.", "Migrateur de Khurkh."]
  },
  "little-bunting": {
    name: "Bruant nain",
    s: "Petit bruant strié à face et bande coronale rousses. Le bruant le plus commun en migration.",
    d: "Le Bruant nain niche dans la taïga sibérienne et hiverne en Chine et en Asie du Sud-Est. En Mongolie, c’est un migrateur abondant en mai et septembre — Khurkh, Oulan-Bator, Yolyn Am et Terelj.",
    f: ["Face et bande coronale rousses.", "Cercle oculaire pâle.", "Fines stries pectorales.", "Bec à bord droit."],
    si: "Bruant rustique — plus grand, bande pectorale rousse.",
    h: "Fourrés, prairies et champs en migration.",
    di: "Khurkh, Oulan-Bator, Yolyn Am, Terelj, lac Khar Us, Khustai.",
    mi: "Migrateur, mai et septembre.",
    fo: "Graines et insectes.",
    br: "Niche dans la taïga sibérienne (pas en Mongolie).",
    be: "Se nourrit discrètement au sol.",
    v: "Un « tik » sec.",
    cu: "Décrit pour la première fois par Peter Simon Pallas en 1776.",
    co: "Préoccupation mineure.",
    w: "Khurkh en mai.",
    bt: "mai, sept.",
    fa: ["Face rousse.", "Petit.", "Migrateur abondant."]
  },
  "yellow-breasted-bunting": {
    name: "Bruant auréole",
    s: "Bruant à poitrine jaune, dos et collier châtain, face noire et tache alaire blanche. En danger critique ; niche encore dans le nord.",
    d: "Le Bruant auréole était l’un des oiseaux les plus abondants d’Eurasie ; le piégeage massif sur ses quartiers d’hiver en Chine a provoqué un effondrement de 90 %. En Mongolie, il niche encore dans les prairies humides — surtout la vallée de Khurkh, Oulan-Bator et Terelj.",
    f: ["Mâle : face noire.", "Dessous jaune.", "Bande pectorale et dos châtain.", "Grande tache alaire blanche."],
    si: "Bruant roux — sans tache alaire blanche.",
    h: "Prairies humides buissonnantes, saulaies.",
    di: "Khurkh, Oulan-Bator, Terelj, lac Ögii, Daguur, Böön Tsagaan.",
    mi: "Estivant, mai–septembre.",
    fo: "Graines et insectes.",
    br: "Niche bas dans les buissons ou l’herbe.",
    be: "Chante du sommet des buissons.",
    v: "Un « tsi-tsi-tsou » sonore et varié.",
    cu: "Piégé en Chine comme « oiseau du riz » ; désormais totalement protégé.",
    co: "En danger critique.",
    w: "Vallée de Khurkh en juin (ne pas déranger les nids).",
    bt: "juin",
    fa: ["En danger critique.", "Tache alaire blanche.", "Niche encore en Mongolie."]
  },
  "yellow-browed-bunting": {
    name: "Bruant à sourcils jaunes",
    s: "Bruant à tête rayée de noir et blanc, l’avant du sourcil jaune. Migrateur d’automne peu commun dans l’est et le nord.",
    d: "Le Bruant à sourcils jaunes niche en Sibérie centrale et hiverne dans le sud de la Chine. En Mongolie, c’est un migrateur peu commun, surtout en août–septembre — Khurkh et lac Buir.",
    f: ["Calotte noire à bande centrale blanche.", "Avant du sourcil jaune.", "Joue noire.", "Poitrine striée."],
    si: "Bruant de Tristram — sans jaune, gorge noire.",
    h: "Sous-bois et fourrés.",
    di: "Khurkh, lac Buir, lac Ganga, Onon, lac Khar Us.",
    mi: "Migrateur, mai et août–septembre.",
    fo: "Graines et insectes.",
    br: "Niche dans les forêts sibériennes (pas en Mongolie).",
    be: "Se nourrit au sol.",
    v: "Un « tsip » fin.",
    cu: "Son nom latin chrysophrys signifie « sourcil d’or ».",
    co: "Préoccupation mineure.",
    w: "Khurkh en septembre.",
    bt: "sept.",
    fa: ["Sourcil jaune.", "Tête rayée.", "Migrateur d’automne."]
  },
  "tristrams-bunting": {
    name: "Bruant de Tristram",
    s: "Bruant à tête nettement rayée de noir et blanc et gorge noire. Migrateur peu commun dans l’est et le Gobi.",
    d: "Le Bruant de Tristram niche dans l’est de la Mandchourie et l’Extrême-Orient russe et hiverne dans le centre et le sud de la Chine. En Mongolie, c’est un migrateur peu commun, surtout en mai — Khurkh, lac Ganga et lac Buir.",
    f: ["Tête nettement rayée de noir et blanc.", "Gorge noire (mâle).", "Croupion roux.", "Dos brun strié."],
    si: "Bruant à sourcils jaunes — jaune au sourcil, gorge blanche.",
    h: "Sous-bois forestier.",
    di: "Khurkh, lac Ganga, lac Buir, oasis du Gobi.",
    mi: "Migrateur, mai et septembre.",
    fo: "Graines et insectes.",
    br: "Niche en forêt (pas en Mongolie).",
    be: "Se cache au sol en forêt.",
    v: "Un doux « tzip ».",
    cu: "Nommé d’après le clergyman et naturaliste anglais Henry Baker Tristram.",
    co: "Préoccupation mineure.",
    w: "Khurkh en mai.",
    bt: "mai",
    fa: ["Tête rayée.", "Gorge noire.", "Migrateur peu commun."]
  }
});
