B2T("en", {
  "saxaul-sparrow": {
    T: { c: { gray: 0.35, buff: 0.3, black: 0.2, rufous: 0.15 }, hb: ["desert"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["14–16 cm", "—", "25–32 g"] },
    s: "A large, pale desert sparrow; the male has a black crown stripe and bib and cinnamon sides to the head. Found in Gobi saxaul groves.",
    d: "The Saxaul Sparrow lives in the saxaul and poplar groves of Central Asian deserts. In Mongolia it is found in the Gobi — oases and saxaul thickets of the south, including Yolyn Am and Taatsiin Tsagaan Nuur.",
    f: ["Male: black crown stripe and bib.", "Cinnamon band behind the eye.", "Pale grey-buff body.", "Female: plain with a faint pattern."],
    si: "House Sparrow — grey crown, chestnut back.",
    h: "Saxaul groves, desert oases and wells.",
    di: "Southern Gobi oases, Yolyn Am, Taatsiin Tsagaan Nuur.",
    mi: "Resident; wanders in winter.",
    fo: "Seeds and insects.",
    br: "Nests in tree holes or old nests.",
    be: "Visits wells and springs to drink.",
    v: "A soft chirping.",
    cu: "Its Latin name means 'sand-tree sparrow', after the saxaul.",
    co: "Least Concern.",
    w: "Gobi oases in June.",
    bt: "May–Jun",
    fa: ["Desert sparrow.", "Saxaul groves.", "Cinnamon head band."]
  },
  "house-sparrow": {
    T: { c: { brown: 0.4, gray: 0.3, black: 0.15, white: 0.15 }, hb: ["settlement"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["14–18 cm", "19–25 cm", "24–40 g"] },
    s: "The familiar town sparrow; the male has a grey crown, chestnut nape and black bib. Common in towns, gers and camps across Mongolia.",
    d: "The House Sparrow lives alongside people almost everywhere in the world. In Mongolia it is common wherever there are buildings or gers — Ulaanbaatar, Khustai, Terelj, Khar Us Nuur and soum centres.",
    f: ["Male: grey crown, chestnut nape.", "Black bib.", "Pale grey cheeks.", "Female: plain buff-brown."],
    si: "Eurasian Tree Sparrow — chestnut crown, black cheek spot.",
    h: "Towns, villages, gers and farms.",
    di: "Ulaanbaatar, Khustai, Terelj, Khar Us Nuur, Ögii Nuur, Yolyn Am.",
    mi: "Resident.",
    fo: "Seeds, scraps and insects.",
    br: "Nests in building crevices; several broods a year.",
    be: "Dust-bathes and chatters in groups.",
    v: "A lively 'chirrup'.",
    cu: "Has followed farming people around the world for 10,000 years.",
    co: "Least Concern.",
    w: "Any soum centre.",
    bt: "All year",
    fa: ["Lives with people.", "Grey crown.", "Everywhere."]
  },
  "eurasian-tree-sparrow": {
    T: { c: { brown: 0.4, rufous: 0.2, white: 0.2, black: 0.2 }, hb: ["settlement", "forest"], bk: "short", bh: ["perch", "walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["12.5–14 cm", "20–22 cm", "19–25 g"] },
    s: "A neat sparrow with a chestnut crown and a black spot on a white cheek; sexes alike. The commonest sparrow in Mongolia.",
    d: "The Eurasian Tree Sparrow lives across Eurasia; in East Asia it replaces the House Sparrow in towns. In Mongolia it is abundant around settlements, farms and riverside trees — Ulaanbaatar, Khurkh, Yolyn Am and Khustai.",
    f: ["Chestnut crown.", "Black spot on white cheek.", "Small black bib.", "Sexes alike."],
    si: "House Sparrow — grey crown, no cheek spot.",
    h: "Villages, farms, riverside woods.",
    di: "Ulaanbaatar, Khurkh, Yolyn Am, Khustai, Terelj, Ögii Nuur.",
    mi: "Resident.",
    fo: "Seeds and insects.",
    br: "Nests in holes in trees, walls and nest boxes.",
    be: "Lives in noisy flocks.",
    v: "A higher 'tchip' than the House Sparrow.",
    cu: "Mao's 'Four Pests' campaign killed hundreds of millions in China in 1958.",
    co: "Least Concern.",
    w: "Anywhere in Ulaanbaatar.",
    bt: "All year",
    fa: ["Cheek spot.", "Chestnut crown.", "Commonest sparrow."]
  },
  "rock-sparrow": {
    T: { c: { brown: 0.45, buff: 0.3, gray: 0.1, white: 0.1, yellow: 0.05 }, hb: ["mountain", "steppe", "desert"], bk: "short", bh: ["walk", "perch"], vt: ["song"], ac: "day", se: ["summer", "resident"], sz: ["14–15 cm", "28–32 cm", "28–37 g"] },
    s: "A stocky, streaky sparrow with a striped head, pale tail spots and a small yellow throat spot. Very common on rocky slopes across Mongolia.",
    d: "The Rock Sparrow breeds on barren rocky hills from the Canary Islands to Mongolia and China. In Mongolia it is very common in rocky places — Khar Us Nuur, Yolyn Am, Ögii Nuur, Ulaanbaatar and Khustai.",
    f: ["Striped crown.", "Pale eyebrow.", "White spots at the tail tip.", "Small yellow throat spot."],
    si: "Père David's Snowfinch — plain back, black face.",
    h: "Rocky slopes, cliffs, ruins and buildings.",
    di: "Khar Us Nuur, Yolyn Am, Ögii Nuur, Ulaanbaatar, Khustai, Khurkh.",
    mi: "Summer visitor and resident, Apr–Oct.",
    fo: "Seeds and insects.",
    br: "Nests in rock crevices and walls.",
    be: "Flocks on migration.",
    v: "A nasal 'pey-ee'.",
    cu: "The only species in its genus, Petronia.",
    co: "Least Concern.",
    w: "Ögii Nuur cliffs in June.",
    bt: "Jun",
    fa: ["Striped head.", "Yellow throat spot.", "Very common."]
  },
  "p-re-davids-snowfinch": {
    T: { c: { buff: 0.4, brown: 0.3, black: 0.15, white: 0.15 }, hb: ["steppe"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["resident"], sz: ["13–15 cm", "—", "20–25 g"] },
    s: "A small sandy snowfinch with a black face and throat that lives in pika and marmot colonies. A characteristic steppe bird.",
    d: "Père David's Snowfinch lives in the steppes of Mongolia, southern Siberia and northern China. It nests in the burrows of pikas and marmots. In Mongolia it is common in short-grass steppe — Ögii Nuur, Khar Us Nuur, Yolyn Am, Khustai and Ölgii.",
    f: ["Black forehead, face and throat.", "Sandy-brown body.", "White in wings and tail.", "Short tail."],
    si: "Rock Sparrow — striped head, no black face.",
    h: "Short-grass steppe with rodent colonies.",
    di: "Ögii Nuur, Khar Us Nuur, Yolyn Am, Khustai, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Resident.",
    fo: "Seeds and insects.",
    br: "Nests in pika and marmot burrows.",
    be: "Runs over bare ground; dives into burrows.",
    v: "A soft twittering.",
    cu: "Also called the Small Snowfinch.",
    co: "Least Concern.",
    w: "Steppe near Ögii Nuur in June.",
    bt: "Jun",
    fa: ["Nests in rodent burrows.", "Black face.", "Steppe bird."]
  },
  "lapland-longspur": {
    T: { c: { brown: 0.35, rufous: 0.2, black: 0.2, white: 0.15, buff: 0.1 }, hb: ["steppe", "water"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["passage", "winter"], sz: ["15–16 cm", "25–28 cm", "20–30 g"] },
    s: "A bunting-like bird with a chestnut nape and, in summer, a black face; walks on the ground. A migrant, mostly in September–October.",
    d: "The Lapland Longspur breeds on the Arctic tundra all around the pole. In Mongolia it is a migrant and scarce winterer on open ground — Khar Us Nuur, Khurkh, Khustai and Tavan Bogd.",
    f: ["Chestnut nape.", "Rufous wing panel.", "Male in summer: black face and breast.", "Long hind claw."],
    si: "Snow Bunting — much whiter.",
    h: "Open steppe, fields and lake shores.",
    di: "Khar Us Nuur, Khurkh, Khustai, Tavan Bogd, Ulaanbaatar, Yolyn Am.",
    mi: "Passage migrant, Apr–May and Sep–Oct; some winter.",
    fo: "Seeds; insects in summer.",
    br: "Nests on the Arctic tundra (not in Mongolia).",
    be: "Walks, rather than hops.",
    v: "A dry rattle 'tik-ik-ik-teu'.",
    cu: "Its long hind claw gives it the name 'longspur'.",
    co: "Least Concern.",
    w: "Khar Us Nuur in September.",
    bt: "Sep–Oct",
    fa: ["Long hind claw.", "Chestnut nape.", "Arctic migrant."]
  },
  "snow-bunting": {
    T: { c: { white: 0.5, black: 0.2, brown: 0.2, buff: 0.1 }, hb: ["steppe", "mountain"], bk: "short", bh: ["walk"], vt: ["song"], ac: "day", se: ["winter"], sz: ["15–18 cm", "32–38 cm", "30–40 g"] },
    s: "A mostly white Arctic bunting with black wing tips; flocks look like snowflakes. A rare winter visitor.",
    d: "The Snow Bunting breeds across the high Arctic and on a few high mountains. In Mongolia it is a rare winter visitor in the north and east — Ulaanbaatar and Terelj.",
    f: ["Mostly white.", "Black wing tips.", "Winter: sandy-brown head and back.", "Short yellow bill in winter."],
    si: "Lapland Longspur — much darker.",
    h: "Open snowy ground, fields.",
    di: "Ulaanbaatar, Terelj; north and east.",
    mi: "Rare winter visitor, Oct–Mar.",
    fo: "Seeds.",
    br: "Nests in Arctic rock crevices (not in Mongolia).",
    be: "Flocks roll over the ground.",
    v: "A rippling 'tirrirrip'.",
    cu: "One of the northernmost breeding songbirds in the world.",
    co: "Least Concern.",
    w: "Snowy fields near Ulaanbaatar in December.",
    bt: "Nov–Dec",
    fa: ["White.", "Like snowflakes.", "Rare winter visitor."]
  }
});
