B2T("fr", {
  "saxaul-sparrow": {
    name: "Moineau des saxaouls",
    s: "Grand moineau pâle du désert ; le mâle a une bande coronale et une bavette noires et les côtés de la tête cannelle. Présent dans les bosquets de saxaoul du Gobi.",
    d: "Le Moineau des saxaouls vit dans les bosquets de saxaoul et de peupliers des déserts d’Asie centrale. En Mongolie, on le trouve dans le Gobi — oasis et fourrés de saxaoul du sud, dont Yolyn Am et Taatsiin Tsagaan Nuur.",
    f: ["Mâle : bande coronale et bavette noires.", "Bande cannelle derrière l’œil.", "Corps gris-chamois pâle.", "Femelle : terne, dessin estompé."],
    si: "Moineau domestique — calotte grise, dos châtain.",
    h: "Bosquets de saxaoul, oasis et puits.",
    di: "Oasis du sud du Gobi, Yolyn Am, Taatsiin Tsagaan Nuur.",
    mi: "Résident ; erratique en hiver.",
    fo: "Graines et insectes.",
    br: "Niche dans des cavités d’arbres ou de vieux nids.",
    be: "Vient boire aux puits et sources.",
    v: "Un doux pépiement.",
    cu: "Son nom latin signifie « moineau de l’arbre des sables », le saxaoul.",
    co: "Préoccupation mineure.",
    w: "Oasis du Gobi en juin.",
    bt: "mai–juin",
    fa: ["Moineau du désert.", "Bosquets de saxaoul.", "Bande céphalique cannelle."]
  },
  "house-sparrow": {
    name: "Moineau domestique",
    s: "Le moineau familier des villes ; le mâle a la calotte grise, la nuque châtain et la bavette noire. Commun dans les villes, yourtes et camps de toute la Mongolie.",
    d: "Le Moineau domestique vit aux côtés de l’homme presque partout dans le monde. En Mongolie, il est commun partout où il y a des bâtiments ou des yourtes — Oulan-Bator, Khustai, Terelj, lac Khar Us et centres de soums.",
    f: ["Mâle : calotte grise, nuque châtain.", "Bavette noire.", "Joues gris pâle.", "Femelle : brun chamois terne."],
    si: "Moineau friquet — calotte châtain, tache noire sur la joue.",
    h: "Villes, villages, yourtes et fermes.",
    di: "Oulan-Bator, Khustai, Terelj, lac Khar Us, lac Ögii, Yolyn Am.",
    mi: "Résident.",
    fo: "Graines, restes et insectes.",
    br: "Niche dans les anfractuosités des bâtiments ; plusieurs couvées par an.",
    be: "Prend des bains de poussière et piaille en groupe.",
    v: "Un vif « tchirrup ».",
    cu: "Suit les agriculteurs à travers le monde depuis 10 000 ans.",
    co: "Préoccupation mineure.",
    w: "N’importe quel centre de soum.",
    bt: "toute l’année",
    fa: ["Vit avec l’homme.", "Calotte grise.", "Partout."]
  },
  "eurasian-tree-sparrow": {
    name: "Moineau friquet",
    s: "Moineau soigné à calotte châtain et tache noire sur joue blanche ; sexes semblables. Le moineau le plus commun de Mongolie.",
    d: "Le Moineau friquet vit dans toute l’Eurasie ; en Asie orientale, il remplace le Moineau domestique en ville. En Mongolie, il abonde autour des villages, fermes et arbres riverains — Oulan-Bator, Khurkh, Yolyn Am et Khustai.",
    f: ["Calotte châtain.", "Tache noire sur joue blanche.", "Petite bavette noire.", "Sexes semblables."],
    si: "Moineau domestique — calotte grise, sans tache jugale.",
    h: "Villages, fermes, bois riverains.",
    di: "Oulan-Bator, Khurkh, Yolyn Am, Khustai, Terelj, lac Ögii.",
    mi: "Résident.",
    fo: "Graines et insectes.",
    br: "Niche dans des cavités d’arbres, de murs et des nichoirs.",
    be: "Vit en groupes bruyants.",
    v: "Un « tchip » plus aigu que le domestique.",
    cu: "La campagne des « Quatre nuisibles » de Mao en 1958 en tua des centaines de millions en Chine.",
    co: "Préoccupation mineure.",
    w: "Partout à Oulan-Bator.",
    bt: "toute l’année",
    fa: ["Tache jugale.", "Calotte châtain.", "Moineau le plus commun."]
  },
  "rock-sparrow": {
    name: "Moineau soulcie",
    s: "Moineau trapu strié, à tête rayée, taches caudales pâles et petite tache jaune à la gorge. Très commun sur les pentes rocheuses de toute la Mongolie.",
    d: "Le Moineau soulcie niche sur les collines rocheuses dénudées, des Canaries à la Mongolie et à la Chine. En Mongolie, il est très commun dans les lieux rocheux — lac Khar Us, Yolyn Am, lac Ögii, Oulan-Bator et Khustai.",
    f: ["Calotte rayée.", "Sourcil pâle.", "Taches blanches au bout de la queue.", "Petite tache jaune à la gorge."],
    si: "Niverolle de David — dos uni, face noire.",
    h: "Pentes rocheuses, falaises, ruines et bâtiments.",
    di: "Lac Khar Us, Yolyn Am, lac Ögii, Oulan-Bator, Khustai, Khurkh.",
    mi: "Estivant et résident, avril–octobre.",
    fo: "Graines et insectes.",
    br: "Niche dans les fissures des rochers et des murs.",
    be: "En groupes en migration.",
    v: "Un « pé-i » nasal.",
    cu: "Seule espèce du genre Petronia.",
    co: "Préoccupation mineure.",
    w: "Falaises du lac Ögii en juin.",
    bt: "juin",
    fa: ["Tête rayée.", "Tache jaune à la gorge.", "Très commun."]
  },
  "p-re-davids-snowfinch": {
    name: "Niverolle de David",
    s: "Petite niverolle sable à face et gorge noires qui vit dans les colonies de pikas et de marmottes. Oiseau typique de la steppe.",
    d: "La Niverolle de David vit dans les steppes de Mongolie, du sud de la Sibérie et du nord de la Chine. Elle niche dans les terriers de pikas et de marmottes. En Mongolie, elle est commune dans la steppe à herbe rase — lac Ögii, lac Khar Us, Yolyn Am, Khustai et Ölgii.",
    f: ["Front, face et gorge noirs.", "Corps brun sable.", "Blanc aux ailes et à la queue.", "Queue courte."],
    si: "Moineau soulcie — tête rayée, sans face noire.",
    h: "Steppe rase à colonies de rongeurs.",
    di: "Lac Ögii, lac Khar Us, Yolyn Am, Khustai, Ölgii, Taatsiin Tsagaan Nuur.",
    mi: "Résidente.",
    fo: "Graines et insectes.",
    br: "Niche dans les terriers de pikas et de marmottes.",
    be: "Court sur le sol nu ; plonge dans les terriers.",
    v: "Un doux gazouillis.",
    cu: "Aussi appelée Petite niverolle.",
    co: "Préoccupation mineure.",
    w: "Steppe près du lac Ögii en juin.",
    bt: "juin",
    fa: ["Niche dans les terriers.", "Face noire.", "Oiseau de steppe."]
  },
  "lapland-longspur": {
    name: "Bruant lapon",
    s: "Oiseau semblable à un bruant, à nuque châtain et, en été, face noire ; marche au sol. Migrateur, surtout en septembre–octobre.",
    d: "Le Bruant lapon niche dans la toundra arctique tout autour du pôle. En Mongolie, c’est un migrateur et un hivernant peu commun en terrain ouvert — lac Khar Us, Khurkh, Khustai et Tavan Bogd.",
    f: ["Nuque châtain.", "Panneau alaire roux.", "Mâle en été : face et poitrine noires.", "Long ongle postérieur."],
    si: "Bruant des neiges — bien plus blanc.",
    h: "Steppe ouverte, champs et rives de lacs.",
    di: "Lac Khar Us, Khurkh, Khustai, Tavan Bogd, Oulan-Bator, Yolyn Am.",
    mi: "Migrateur, avril–mai et septembre–octobre ; quelques hivernants.",
    fo: "Graines ; insectes en été.",
    br: "Niche dans la toundra arctique (pas en Mongolie).",
    be: "Marche plutôt qu’il ne sautille.",
    v: "Un crépitement sec « tik-ik-ik-teu ».",
    cu: "Son long ongle postérieur lui vaut le nom anglais de « longspur ».",
    co: "Préoccupation mineure.",
    w: "Lac Khar Us en septembre.",
    bt: "sept.–oct.",
    fa: ["Long ongle.", "Nuque châtain.", "Migrateur arctique."]
  },
  "snow-bunting": {
    name: "Bruant des neiges",
    s: "Bruant arctique presque blanc aux pointes d’ailes noires ; ses bandes ressemblent à des flocons. Hivernant rare.",
    d: "Le Bruant des neiges niche dans le Haut-Arctique et sur quelques hauts sommets. En Mongolie, c’est un hivernant rare dans le nord et l’est — Oulan-Bator et Terelj.",
    f: ["Surtout blanc.", "Pointes des ailes noires.", "Hiver : tête et dos brun sable.", "Bec court jaune en hiver."],
    si: "Bruant lapon — bien plus sombre.",
    h: "Terrains ouverts enneigés, champs.",
    di: "Oulan-Bator, Terelj ; nord et est.",
    mi: "Hivernant rare, octobre–mars.",
    fo: "Graines.",
    br: "Niche dans les fissures rocheuses arctiques (pas en Mongolie).",
    be: "Les bandes « roulent » au ras du sol.",
    v: "Un « tirrirrip » ondulant.",
    cu: "L’un des passereaux nicheurs les plus septentrionaux du monde.",
    co: "Préoccupation mineure.",
    w: "Champs enneigés près d’Oulan-Bator en décembre.",
    bt: "nov.–déc.",
    fa: ["Blanc.", "Comme des flocons.", "Hivernant rare."]
  }
});
